LLVM: llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair > Struct Reference
llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair > Struct Reference
Provide DenseMapInfo for TargetInstrInfo::RegSubRegPair.
#include "llvm/CodeGen/TargetInstrInfo.h"
Public Types
using RegInfo = DenseMapInfo<Register>
using SubRegInfo = DenseMapInfo<unsigned>
Static Public Member Functions
static TargetInstrInfo::RegSubRegPair getEmptyKey ()
static TargetInstrInfo::RegSubRegPair getTombstoneKey ()
static unsigned getHashValue (const TargetInstrInfo::RegSubRegPair &Val)
Reuse getHashValue implementation from std::pair<unsigned, unsigned>.
static bool isEqual (const TargetInstrInfo::RegSubRegPair &LHS, const TargetInstrInfo::RegSubRegPair &RHS)
Detailed Description
Provide DenseMapInfo for TargetInstrInfo::RegSubRegPair.
Definition at line 2406 of file TargetInstrInfo.h.
Member Typedef Documentation
RegInfo
using llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::RegInfo = DenseMapInfo<Register>
Definition at line 2407 of file TargetInstrInfo.h.
SubRegInfo
using llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::SubRegInfo = DenseMapInfo<unsigned>
Definition at line 2408 of file TargetInstrInfo.h.
Member Function Documentation
getEmptyKey()
TargetInstrInfo::RegSubRegPair llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::getEmptyKey () inline static
Definition at line 2410 of file TargetInstrInfo.h.
References llvm::DenseMapInfo< Register >::getEmptyKey().
getHashValue()
unsigned llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::getHashValue (const TargetInstrInfo::RegSubRegPair & Val) inline static
Reuse getHashValue implementation from std::pair<unsigned, unsigned>.
Definition at line 2422 of file TargetInstrInfo.h.
References getHashValue(), llvm::TargetInstrInfo::RegSubRegPair::Reg, and llvm::TargetInstrInfo::RegSubRegPair::SubReg.
Referenced by getHashValue().
getTombstoneKey()
TargetInstrInfo::RegSubRegPair llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::getTombstoneKey () inline static
Definition at line 2415 of file TargetInstrInfo.h.
References llvm::DenseMapInfo< Register >::getTombstoneKey().
isEqual()
bool llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::isEqual (const TargetInstrInfo::RegSubRegPair & LHS, const TargetInstrInfo::RegSubRegPair & RHS) inline static
Definition at line 2427 of file TargetInstrInfo.h.
References LHS, and RHS.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetInstrInfo.h