LLVM: llvm::TargetLowering::CallLoweringInfo Struct Reference
llvm::TargetLowering::CallLoweringInfo Struct Reference
This structure contains all information that is necessary for lowering calls.
#include "llvm/CodeGen/TargetLowering.h"
Public Member Functions
CallLoweringInfo (SelectionDAG &DAG)
CallLoweringInfo & setDebugLoc (const SDLoc &dl)
CallLoweringInfo & setChain (SDValue InChain)
CallLoweringInfo & setLibCallee (CallingConv::ID CC, Type *ResultType, SDValue Target, ArgListTy &&ArgsList)
CallLoweringInfo & setLibCallee (CallingConv::ID CC, Type *ResultType, Type *OrigResultType, SDValue Target, ArgListTy &&ArgsList)
CallLoweringInfo & setCallee (CallingConv::ID CC, Type *ResultType, SDValue Target, ArgListTy &&ArgsList, AttributeSet ResultAttrs={})
CallLoweringInfo & setCallee (Type *ResultType, FunctionType *FTy, SDValue Target, ArgListTy &&ArgsList, const CallBase &Call)
CallLoweringInfo & setInRegister (bool Value=true)
CallLoweringInfo & setNoReturn (bool Value=true)
CallLoweringInfo & setVarArg (bool Value=true)
CallLoweringInfo & setTailCall (bool Value=true)
CallLoweringInfo & setDiscardResult (bool Value=true)
CallLoweringInfo & setConvergent (bool Value=true)
CallLoweringInfo & setSExtResult (bool Value=true)
CallLoweringInfo & setZExtResult (bool Value=true)
CallLoweringInfo & setIsPatchPoint (bool Value=true)
CallLoweringInfo & setIsPreallocated (bool Value=true)
CallLoweringInfo & setPtrAuth (PtrAuthInfo Value)
CallLoweringInfo & setIsPostTypeLegalization (bool Value=true)
CallLoweringInfo & setCFIType (const ConstantInt *Type)
CallLoweringInfo & setConvergenceControlToken (SDValue Token)
CallLoweringInfo & setDeactivationSymbol (GlobalValue *Sym)
ArgListTy & getArgs ()
Public Attributes
SDValue Chain
Type * OrigRetTy = nullptr
Original unlegalized return type.
Type * RetTy = nullptr
Same as OrigRetTy, or partially legalized for soft float libcalls.
bool RetSExt: 1
bool RetZExt: 1
bool IsVarArg: 1
bool IsInReg: 1
bool DoesNotReturn: 1
bool IsReturnValueUsed: 1
bool IsConvergent: 1
bool IsPatchPoint: 1
bool IsPreallocated: 1
bool NoMerge: 1
bool IsTailCall = false
bool IsPostTypeLegalization = false
unsigned NumFixedArgs = -1
CallingConv::ID CallConv = CallingConv::C
SDValue Callee
ArgListTy Args
SelectionDAG & DAG
SDLoc DL
const CallBase * CB = nullptr
SmallVector< ISD::OutputArg, 32 > Outs
SmallVector< SDValue, 32 > OutVals
SmallVector< ISD::InputArg, 32 > Ins
SmallVector< SDValue, 4 > InVals
const ConstantInt * CFIType = nullptr
SDValue ConvergenceControlToken
GlobalValue * DeactivationSymbol = nullptr
std::optional< PtrAuthInfo > PAI
Detailed Description
This structure contains all information that is necessary for lowering calls.
It is passed to TLI::LowerCallTo when the SelectionDAG builder needs to lower a call, and targets will see this struct in their LowerCall implementation.
Definition at line 4758 of file TargetLowering.h.
Constructor & Destructor Documentation
CallLoweringInfo()
llvm::TargetLowering::CallLoweringInfo::CallLoweringInfo (SelectionDAG & DAG) inline
Definition at line 4799 of file TargetLowering.h.
References DAG, DoesNotReturn, IsConvergent, IsInReg, IsPatchPoint, IsPreallocated, IsReturnValueUsed, IsVarArg, NoMerge, RetSExt, and RetZExt.
Referenced by setCallee(), setCallee(), setCFIType(), setChain(), setConvergenceControlToken(), setConvergent(), setDeactivationSymbol(), setDebugLoc(), setDiscardResult(), setInRegister(), setIsPatchPoint(), setIsPostTypeLegalization(), setIsPreallocated(), setLibCallee(), setLibCallee(), setNoReturn(), setPtrAuth(), setSExtResult(), setTailCall(), setVarArg(), and setZExtResult().
Member Function Documentation
getArgs()
ArgListTy & llvm::TargetLowering::CallLoweringInfo::getArgs () inline
Definition at line 4954 of file TargetLowering.h.
References Args.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), and llvm::TargetLowering::LowerCallTo().
setCallee() [1/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setCallee (CallingConv::ID CC, Type * ResultType, SDValue Target, ArgListTy && ArgsList, AttributeSet ResultAttrs = {}) inline
Definition at line 4837 of file TargetLowering.h.
References CallLoweringInfo().
Referenced by llvm::SelectionDAGBuilder::LowerCallTo(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
setCallee() [2/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setCallee (Type * ResultType, FunctionType * FTy, SDValue Target, ArgListTy && ArgsList, const CallBase & Call) inline
Definition at line 4853 of file TargetLowering.h.
References Args, CallConv, Callee, CallLoweringInfo(), CB, DoesNotReturn, llvm::FunctionType::getNumParams(), llvm::isa(), IsInReg, IsReturnValueUsed, IsVarArg, llvm::FunctionType::isVarArg(), NoMerge, NumFixedArgs, OrigRetTy, RetSExt, RetTy, and RetZExt.
setCFIType()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setCFIType (const ConstantInt * Type) inline
Definition at line 4939 of file TargetLowering.h.
References CallLoweringInfo(), and CFIType.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setChain()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setChain (SDValue InChain) inline
Definition at line 4810 of file TargetLowering.h.
References CallLoweringInfo(), and Chain.
Referenced by emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcmp(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getStrcpy(), llvm::SelectionDAG::getStrlen(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), llvm::SelectionDAG::makeStateFunctionCall(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
setConvergenceControlToken()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setConvergenceControlToken (SDValue Token) inline
Definition at line 4944 of file TargetLowering.h.
References CallLoweringInfo(), and ConvergenceControlToken.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setConvergent()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setConvergent (bool Value = true) inline
Definition at line 4904 of file TargetLowering.h.
References CallLoweringInfo(), and IsConvergent.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setDeactivationSymbol()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setDeactivationSymbol (GlobalValue * Sym) inline
Definition at line 4949 of file TargetLowering.h.
References CallLoweringInfo(), and DeactivationSymbol.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setDebugLoc()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setDebugLoc (const SDLoc & dl) inline
Definition at line 4805 of file TargetLowering.h.
References CallLoweringInfo(), and DL.
Referenced by emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcmp(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getStrcpy(), llvm::SelectionDAG::getStrlen(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), llvm::SelectionDAG::makeStateFunctionCall(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
setDiscardResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setDiscardResult (bool Value = true) inline
Definition at line 4899 of file TargetLowering.h.
References CallLoweringInfo(), and IsReturnValueUsed.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), and llvm::SelectionDAGBuilder::populateCallLoweringInfo().
setInRegister()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setInRegister (bool Value = true) inline
Definition at line 4879 of file TargetLowering.h.
References CallLoweringInfo(), and IsInReg.
setIsPatchPoint()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setIsPatchPoint (bool Value = true) inline
Definition at line 4919 of file TargetLowering.h.
References CallLoweringInfo(), and IsPatchPoint.
Referenced by llvm::SelectionDAGBuilder::populateCallLoweringInfo().
setIsPostTypeLegalization()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setIsPostTypeLegalization (bool Value = true) inline
Definition at line 4934 of file TargetLowering.h.
References CallLoweringInfo(), and IsPostTypeLegalization.
Referenced by llvm::TargetLowering::makeLibCall().
setIsPreallocated()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setIsPreallocated (bool Value = true) inline
Definition at line 4924 of file TargetLowering.h.
References CallLoweringInfo(), and IsPreallocated.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo(), and llvm::SelectionDAGBuilder::populateCallLoweringInfo().
setLibCallee() [1/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setLibCallee (CallingConv::ID CC, Type * ResultType, SDValue Target, ArgListTy && ArgsList) inline
Definition at line 4816 of file TargetLowering.h.
References CallLoweringInfo(), and setLibCallee().
Referenced by emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcmp(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getStrcpy(), llvm::SelectionDAG::getStrlen(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::TargetLowering::makeLibCall(), llvm::SelectionDAG::makeStateFunctionCall(), and setLibCallee().
setLibCallee() [2/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setLibCallee (CallingConv::ID CC, Type * ResultType, Type * OrigResultType, SDValue Target, ArgListTy && ArgsList) inline
Definition at line 4822 of file TargetLowering.h.
References Args, CallConv, Callee, CallLoweringInfo(), DAG, NumFixedArgs, OrigRetTy, and RetTy.
setNoReturn()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setNoReturn (bool Value = true) inline
Definition at line 4884 of file TargetLowering.h.
References CallLoweringInfo(), and DoesNotReturn.
Referenced by llvm::SystemZTargetLowering::makeExternalCall(), and llvm::TargetLowering::makeLibCall().
setPtrAuth()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setPtrAuth (PtrAuthInfo Value) inline
Definition at line 4929 of file TargetLowering.h.
References CallLoweringInfo(), and PAI.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setSExtResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setSExtResult (bool Value = true) inline
Definition at line 4909 of file TargetLowering.h.
References CallLoweringInfo(), and RetSExt.
Referenced by llvm::SystemZTargetLowering::makeExternalCall(), and llvm::TargetLowering::makeLibCall().
setTailCall()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setTailCall (bool Value = true) inline
Definition at line 4894 of file TargetLowering.h.
References CallLoweringInfo(), and IsTailCall.
Referenced by llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcmp(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getStrcpy(), llvm::SelectionDAG::getStrlen(), and llvm::SelectionDAGBuilder::LowerCallTo().
setVarArg()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setVarArg (bool Value = true) inline
Definition at line 4889 of file TargetLowering.h.
References CallLoweringInfo(), and IsVarArg.
setZExtResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setZExtResult (bool Value = true) inline
Definition at line 4914 of file TargetLowering.h.
References CallLoweringInfo(), and RetZExt.
Referenced by llvm::SystemZTargetLowering::makeExternalCall(), and llvm::TargetLowering::makeLibCall().
Member Data Documentation
Args
ArgListTy llvm::TargetLowering::CallLoweringInfo::Args
Definition at line 4785 of file TargetLowering.h.
Referenced by analyzeCallOperands(), getArgs(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), setCallee(), and setLibCallee().
CallConv
CallingConv::ID llvm::TargetLowering::CallLoweringInfo::CallConv = CallingConv::C
Definition at line 4783 of file TargetLowering.h.
Referenced by analyzeCallOperands(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setLibCallee().
Callee
SDValue llvm::TargetLowering::CallLoweringInfo::Callee
Definition at line 4784 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), getSMECallAttrs(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), setCallee(), and setLibCallee().
CB
const CallBase* llvm::TargetLowering::CallLoweringInfo::CB = nullptr
Definition at line 4788 of file TargetLowering.h.
Referenced by getSMECallAttrs(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::SITargetLowering::passSpecialInputs(), and setCallee().
CFIType
const ConstantInt* llvm::TargetLowering::CallLoweringInfo::CFIType = nullptr
Definition at line 4793 of file TargetLowering.h.
Referenced by llvm::RISCVTargetLowering::LowerCall(), and setCFIType().
Chain
SDValue llvm::TargetLowering::CallLoweringInfo::Chain
Definition at line 4759 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), and setChain().
ConvergenceControlToken
SDValue llvm::TargetLowering::CallLoweringInfo::ConvergenceControlToken
Definition at line 4794 of file TargetLowering.h.
Referenced by llvm::SITargetLowering::LowerCall(), and setConvergenceControlToken().
DAG
SelectionDAG& llvm::TargetLowering::CallLoweringInfo::DAG
Definition at line 4786 of file TargetLowering.h.
Referenced by analyzeCallOperands(), CallLoweringInfo(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::SITargetLowering::passSpecialInputs(), and setLibCallee().
DeactivationSymbol
GlobalValue* llvm::TargetLowering::CallLoweringInfo::DeactivationSymbol = nullptr
Definition at line 4795 of file TargetLowering.h.
Referenced by setDeactivationSymbol().
DL
SDLoc llvm::TargetLowering::CallLoweringInfo::DL
Definition at line 4787 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::SITargetLowering::passSpecialInputs(), and setDebugLoc().
DoesNotReturn
bool llvm::TargetLowering::CallLoweringInfo::DoesNotReturn
Definition at line 4768 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::HexagonTargetLowering::LowerCall(), setCallee(), and setNoReturn().
Ins
SmallVector<ISD::InputArg, 32> llvm::TargetLowering::CallLoweringInfo::Ins
Definition at line 4791 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and llvm::AMDGPUTargetLowering::lowerUnhandledCall().
InVals
SmallVector<SDValue, 4> llvm::TargetLowering::CallLoweringInfo::InVals
Definition at line 4792 of file TargetLowering.h.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo(), and llvm::TargetLowering::LowerCallTo().
IsConvergent
bool llvm::TargetLowering::CallLoweringInfo::IsConvergent
Definition at line 4770 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::NVPTXTargetLowering::LowerCall(), and setConvergent().
IsInReg
bool llvm::TargetLowering::CallLoweringInfo::IsInReg
Definition at line 4767 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setInRegister().
IsPatchPoint
bool llvm::TargetLowering::CallLoweringInfo::IsPatchPoint
Definition at line 4771 of file TargetLowering.h.
Referenced by CallLoweringInfo(), and setIsPatchPoint().
IsPostTypeLegalization
bool llvm::TargetLowering::CallLoweringInfo::IsPostTypeLegalization = false
Definition at line 4780 of file TargetLowering.h.
Referenced by llvm::TargetLowering::LowerCallTo(), and setIsPostTypeLegalization().
IsPreallocated
bool llvm::TargetLowering::CallLoweringInfo::IsPreallocated
Definition at line 4772 of file TargetLowering.h.
Referenced by CallLoweringInfo(), and setIsPreallocated().
IsReturnValueUsed
bool llvm::TargetLowering::CallLoweringInfo::IsReturnValueUsed
Definition at line 4769 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setDiscardResult().
IsTailCall
bool llvm::TargetLowering::CallLoweringInfo::IsTailCall = false
Definition at line 4777 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), and setTailCall().
IsVarArg
bool llvm::TargetLowering::CallLoweringInfo::IsVarArg
Definition at line 4766 of file TargetLowering.h.
Referenced by analyzeCallOperands(), CallLoweringInfo(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setVarArg().
NoMerge
bool llvm::TargetLowering::CallLoweringInfo::NoMerge
Definition at line 4773 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), and setCallee().
NumFixedArgs
unsigned llvm::TargetLowering::CallLoweringInfo::NumFixedArgs = -1
Definition at line 4782 of file TargetLowering.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setLibCallee().
OrigRetTy
Type* llvm::TargetLowering::CallLoweringInfo::OrigRetTy = nullptr
Original unlegalized return type.
Definition at line 4761 of file TargetLowering.h.
Referenced by llvm::TargetLowering::LowerCallTo(), setCallee(), and setLibCallee().
Outs
SmallVector<ISD::OutputArg, 32> llvm::TargetLowering::CallLoweringInfo::Outs
Definition at line 4789 of file TargetLowering.h.
Referenced by analyzeCallOperands(), llvm::SparcTargetLowering::IsEligibleForTailCallOptimization(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and mayBeSRetTailCallCompatible().
OutVals
SmallVector<SDValue, 32> llvm::TargetLowering::CallLoweringInfo::OutVals
Definition at line 4790 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and mayBeSRetTailCallCompatible().
PAI
std::optional<PtrAuthInfo> llvm::TargetLowering::CallLoweringInfo::PAI
Definition at line 4797 of file TargetLowering.h.
Referenced by setPtrAuth().
RetSExt
bool llvm::TargetLowering::CallLoweringInfo::RetSExt
Definition at line 4764 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setSExtResult().
RetTy
Type* llvm::TargetLowering::CallLoweringInfo::RetTy = nullptr
Same as OrigRetTy, or partially legalized for soft float libcalls.
Definition at line 4763 of file TargetLowering.h.
Referenced by getReturnAttrs(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setLibCallee().
RetZExt
bool llvm::TargetLowering::CallLoweringInfo::RetZExt
Definition at line 4765 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setZExtResult().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetLowering.h