LLVM: llvm::ms_demangle::FunctionSignatureNode Struct Reference
llvm::ms_demangle::FunctionSignatureNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
FunctionSignatureNode (NodeKind K)
FunctionSignatureNode ()
void outputPre (OutputBuffer &OB, OutputFlags Flags) const override
void outputPost (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::TypeNode
TypeNode (NodeKind K)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
DEMANGLE_ABI std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Static Public Member Functions inherited from llvm::ms_demangle::TypeNode
static bool classof (const Node *N)
Public Attributes
PointerAffinity Affinity = PointerAffinity::None
CallingConv CallConvention = CallingConv::None
FuncClass FunctionClass = FC_Global
FunctionRefQualifier RefQualifier = FunctionRefQualifier::None
TypeNode * ReturnType = nullptr
bool IsVariadic = false
NodeArrayNode * Params = nullptr
bool IsNoexcept = false
Public Attributes inherited from llvm::ms_demangle::TypeNode
Qualifiers Quals = Q_None
Detailed Description
Definition at line 350 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
FunctionSignatureNode() [1/2]
llvm::ms_demangle::FunctionSignatureNode::FunctionSignatureNode (NodeKind K) inline explicit
Definition at line 351 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::TypeNode::TypeNode().
Referenced by llvm::ms_demangle::ThunkSignatureNode::ThunkSignatureNode().
FunctionSignatureNode() [2/2]
llvm::ms_demangle::FunctionSignatureNode::FunctionSignatureNode () inline
Definition at line 352 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::FunctionSignature, and llvm::ms_demangle::TypeNode::TypeNode().
Member Function Documentation
classof()
bool llvm::ms_demangle::FunctionSignatureNode::classof (const Node * N) inline static
Definition at line 357 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::FunctionSignature, llvm::ms_demangle::FunctionSignatureEnd, and N.
outputPost()
void FunctionSignatureNode::outputPost (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Reimplemented in llvm::ms_demangle::ThunkSignatureNode.
Definition at line 419 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::FC_NoParameterList, FunctionClass, IsNoexcept, IsVariadic, llvm::ms_demangle::OF_NoReturnType, Params, llvm::ms_demangle::Q_Const, llvm::ms_demangle::Q_Restrict, llvm::ms_demangle::Q_Unaligned, llvm::ms_demangle::Q_Volatile, llvm::ms_demangle::TypeNode::Quals, llvm::ms_demangle::Reference, RefQualifier, ReturnType, and llvm::ms_demangle::RValueReference.
Referenced by llvm::ms_demangle::ThunkSignatureNode::outputPost().
outputPre()
void FunctionSignatureNode::outputPre (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Reimplemented in llvm::ms_demangle::ThunkSignatureNode.
Definition at line 387 of file MicrosoftDemangleNodes.cpp.
References CallConvention, llvm::ms_demangle::FC_ExternC, llvm::ms_demangle::FC_Global, llvm::ms_demangle::FC_Private, llvm::ms_demangle::FC_Protected, llvm::ms_demangle::FC_Public, llvm::ms_demangle::FC_Static, llvm::ms_demangle::FC_Virtual, FunctionClass, llvm::ms_demangle::OF_NoAccessSpecifier, llvm::ms_demangle::OF_NoCallingConvention, llvm::ms_demangle::OF_NoMemberType, llvm::ms_demangle::OF_NoReturnType, outputCallingConvention(), and ReturnType.
Referenced by llvm::ms_demangle::PointerTypeNode::outputPre(), and llvm::ms_demangle::ThunkSignatureNode::outputPre().
Member Data Documentation
Affinity
PointerAffinity llvm::ms_demangle::FunctionSignatureNode::Affinity = PointerAffinity::None
Definition at line 364 of file MicrosoftDemangleNodes.h.
CallConvention
CallingConv llvm::ms_demangle::FunctionSignatureNode::CallConvention = CallingConv::None
Definition at line 367 of file MicrosoftDemangleNodes.h.
Referenced by outputPre(), and llvm::ms_demangle::PointerTypeNode::outputPre().
FunctionClass
FuncClass llvm::ms_demangle::FunctionSignatureNode::FunctionClass = FC_Global
Definition at line 370 of file MicrosoftDemangleNodes.h.
Referenced by outputPost(), llvm::ms_demangle::ThunkSignatureNode::outputPost(), and outputPre().
IsNoexcept
bool llvm::ms_demangle::FunctionSignatureNode::IsNoexcept = false
Definition at line 384 of file MicrosoftDemangleNodes.h.
Referenced by outputPost().
IsVariadic
bool llvm::ms_demangle::FunctionSignatureNode::IsVariadic = false
Definition at line 378 of file MicrosoftDemangleNodes.h.
Referenced by outputPost().
Params
NodeArrayNode* llvm::ms_demangle::FunctionSignatureNode::Params = nullptr
Definition at line 381 of file MicrosoftDemangleNodes.h.
Referenced by outputPost().
RefQualifier
FunctionRefQualifier llvm::ms_demangle::FunctionSignatureNode::RefQualifier = FunctionRefQualifier::None
Definition at line 372 of file MicrosoftDemangleNodes.h.
Referenced by outputPost().
ReturnType
TypeNode* llvm::ms_demangle::FunctionSignatureNode::ReturnType = nullptr
Definition at line 375 of file MicrosoftDemangleNodes.h.
Referenced by outputPost(), and outputPre().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp