LLVM: llvm::TargetRegistry Struct Reference
llvm::TargetRegistry Struct Reference
TargetRegistry - Generic interface to target specific features.
#include "llvm/MC/TargetRegistry.h"
Classes
class iterator
Public Member Functions
TargetRegistry ()=delete
Static Public Member Functions
static LLVM_ABI void printRegisteredTargetsForVersion (raw_ostream &OS)
printRegisteredTargetsForVersion - Print the registered targets appropriately for inclusion in a tool's version output.
Registry Access
static LLVM_ABI iterator_range< iterator > targets ()
static const Target * lookupTarget (StringRef TripleStr, std::string &Error)
lookupTarget - Lookup a target based on a target triple.
static LLVM_ABI const Target * lookupTarget (const Triple &TheTriple, std::string &Error)
lookupTarget - Lookup a target based on a target triple.
static LLVM_ABI const Target * lookupTarget (StringRef ArchName, Triple &TheTriple, std::string &Error)
lookupTarget - Lookup a target based on an architecture name and a target triple.
Target Registration
static LLVM_ABI void RegisterTarget (Target &T, const char *Name, const char *ShortDesc, const char *BackendName, Target::ArchMatchFnTy ArchMatchFn, bool HasJIT=false)
RegisterTarget - Register the given target.
static void RegisterMCAsmInfo (Target &T, Target::MCAsmInfoCtorFnTy Fn)
RegisterMCAsmInfo - Register a MCAsmInfo implementation for the given target.
static void RegisterMCObjectFileInfo (Target &T, Target::MCObjectFileInfoCtorFnTy Fn)
Register a MCObjectFileInfo implementation for the given target.
static void RegisterMCInstrInfo (Target &T, Target::MCInstrInfoCtorFnTy Fn)
RegisterMCInstrInfo - Register a MCInstrInfo implementation for the given target.
static void RegisterMCInstrAnalysis (Target &T, Target::MCInstrAnalysisCtorFnTy Fn)
RegisterMCInstrAnalysis - Register a MCInstrAnalysis implementation for the given target.
static void RegisterMCRegInfo (Target &T, Target::MCRegInfoCtorFnTy Fn)
RegisterMCRegInfo - Register a MCRegisterInfo implementation for the given target.
static void RegisterMCSubtargetInfo (Target &T, Target::MCSubtargetInfoCtorFnTy Fn)
RegisterMCSubtargetInfo - Register a MCSubtargetInfo implementation for the given target.
static void RegisterTargetMachine (Target &T, Target::TargetMachineCtorTy Fn)
RegisterTargetMachine - Register a TargetMachine implementation for the given target.
static void RegisterMCAsmBackend (Target &T, Target::MCAsmBackendCtorTy Fn)
RegisterMCAsmBackend - Register a MCAsmBackend implementation for the given target.
static void RegisterMCAsmParser (Target &T, Target::MCAsmParserCtorTy Fn)
RegisterMCAsmParser - Register a MCTargetAsmParser implementation for the given target.
static void RegisterAsmPrinter (Target &T, Target::AsmPrinterCtorTy Fn)
RegisterAsmPrinter - Register an AsmPrinter implementation for the given target.
static void RegisterMCDisassembler (Target &T, Target::MCDisassemblerCtorTy Fn)
RegisterMCDisassembler - Register a MCDisassembler implementation for the given target.
static void RegisterMCInstPrinter (Target &T, Target::MCInstPrinterCtorTy Fn)
RegisterMCInstPrinter - Register a MCInstPrinter implementation for the given target.
static void RegisterMCCodeEmitter (Target &T, Target::MCCodeEmitterCtorTy Fn)
RegisterMCCodeEmitter - Register a MCCodeEmitter implementation for the given target.
static void RegisterCOFFStreamer (Target &T, Target::COFFStreamerCtorTy Fn)
static void RegisterMachOStreamer (Target &T, Target::MachOStreamerCtorTy Fn)
static void RegisterELFStreamer (Target &T, Target::ELFStreamerCtorTy Fn)
static void RegisterXCOFFStreamer (Target &T, Target::XCOFFStreamerCtorTy Fn)
static void RegisterNullTargetStreamer (Target &T, Target::NullTargetStreamerCtorTy Fn)
static void RegisterAsmStreamer (Target &T, Target::AsmStreamerCtorTy Fn)
static void RegisterAsmTargetStreamer (Target &T, Target::AsmTargetStreamerCtorTy Fn)
static void RegisterObjectTargetStreamer (Target &T, Target::ObjectTargetStreamerCtorTy Fn)
static void RegisterMCRelocationInfo (Target &T, Target::MCRelocationInfoCtorTy Fn)
RegisterMCRelocationInfo - Register an MCRelocationInfo implementation for the given target.
static void RegisterMCSymbolizer (Target &T, Target::MCSymbolizerCtorTy Fn)
RegisterMCSymbolizer - Register an MCSymbolizer implementation for the given target.
static void RegisterCustomBehaviour (Target &T, Target::CustomBehaviourCtorTy Fn)
RegisterCustomBehaviour - Register a CustomBehaviour implementation for the given target.
static void RegisterInstrPostProcess (Target &T, Target::InstrPostProcessCtorTy Fn)
RegisterInstrPostProcess - Register an InstrPostProcess implementation for the given target.
static void RegisterInstrumentManager (Target &T, Target::InstrumentManagerCtorTy Fn)
RegisterInstrumentManager - Register an InstrumentManager implementation for the given target.
Detailed Description
TargetRegistry - Generic interface to target specific features.
Definition at line 680 of file TargetRegistry.h.
Constructor & Destructor Documentation
TargetRegistry()
llvm::TargetRegistry::TargetRegistry () delete
Member Function Documentation
lookupTarget() [1/3]
const Target * TargetRegistry::lookupTarget (const Triple & TheTriple, std::string & Error) static
lookupTarget - Lookup a target based on a target triple.
Parameters
Triple - The triple to use for finding a target.
Error - On failure, an error string describing why no target was found.
Definition at line 142 of file TargetRegistry.cpp.
References llvm::begin(), llvm::end(), llvm::find_if(), I, T, and targets().
lookupTarget() [2/3]
const Target * TargetRegistry::lookupTarget (StringRef ArchName, Triple & TheTriple, std::string & Error) static
lookupTarget - Lookup a target based on an architecture name and a target triple.
If the architecture name is non-empty, then the lookup is done by architecture. Otherwise, the target triple is used.
Parameters
ArchName - The architecture to use for finding a target.
TheTriple - The triple to use for finding a target. The triple is updated with canonical architecture name if a lookup by architecture is done.
Error - On failure, an error string describing why no target was found.
Definition at line 105 of file TargetRegistry.cpp.
References llvm::StringRef::empty(), llvm::end(), llvm::find_if(), llvm::Triple::getArchTypeForLLVMName(), llvm::Triple::getTriple(), I, lookupTarget(), llvm::Triple::setArch(), T, targets(), and llvm::Triple::UnknownArch.
lookupTarget() [3/3]
const Target * llvm::TargetRegistry::lookupTarget (StringRef TripleStr, std::string & Error) inline static
lookupTarget - Lookup a target based on a target triple.
Parameters
TripleStr - The triple to use for finding a target.
Error - On failure, an error string describing why no target was found.
Definition at line 742 of file TargetRegistry.h.
References lookupTarget().
Referenced by llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::create(), createTargetMachine(), llvm::orc::JITTargetMachineBuilder::createTargetMachine(), llvm::codegen::createTargetMachineForTriple(), llvm::object::ELFObjectFileBase::getPltEntries(), llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), initAndLookupTarget(), initializeRecordStreamer(), LLVMCreateDisasmCPUFeatures(), LLVMGetTargetFromTriple(), llvm::logicalview::LVBinaryReader::loadGenericTargetInfo(), lookupTarget(), lookupTarget(), llvm::EngineBuilder::selectTarget(), llvm::SPIRVTranslate(), and llvm::BitcodeWriter::writeSymtab().
printRegisteredTargetsForVersion()
void TargetRegistry::printRegisteredTargetsForVersion (raw_ostream & OS) static
printRegisteredTargetsForVersion - Print the registered targets appropriately for inclusion in a tool's version output.
Definition at line 198 of file TargetRegistry.cpp.
References llvm::array_pod_sort(), llvm::Target::getShortDescription(), llvm::raw_ostream::indent(), T, TargetArraySortFn(), and targets().
RegisterAsmPrinter()
void llvm::TargetRegistry::RegisterAsmPrinter (Target & T, Target::AsmPrinterCtorTy Fn) inline static
RegisterAsmPrinter - Register an AsmPrinter implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an AsmPrinter for the target.
Definition at line 917 of file TargetRegistry.h.
References T.
Referenced by INITIALIZE_PASS(), LLVMInitializeAMDGPUAsmPrinter(), and llvm::RegisterAsmPrinter< AsmPrinterImpl >::RegisterAsmPrinter().
RegisterAsmStreamer()
void llvm::TargetRegistry::RegisterAsmStreamer (Target & T, Target::AsmStreamerCtorTy Fn) inline static
Definition at line 982 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeSystemZTargetMC().
RegisterAsmTargetStreamer()
void llvm::TargetRegistry::RegisterAsmTargetStreamer (Target & T, Target::AsmTargetStreamerCtorTy Fn) inline static
Definition at line 986 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTargetMC(), and LLVMInitializeXtensaTargetMC().
RegisterCOFFStreamer()
void llvm::TargetRegistry::RegisterCOFFStreamer (Target & T, Target::COFFStreamerCtorTy Fn) inline static
Definition at line 961 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeMipsTargetMC(), and LLVMInitializeX86TargetMC().
RegisterCustomBehaviour()
void llvm::TargetRegistry::RegisterCustomBehaviour (Target & T, Target::CustomBehaviourCtorTy Fn) inline static
RegisterCustomBehaviour - Register a CustomBehaviour implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a CustomBehaviour for the target.
Definition at line 1033 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAMDGPUTargetMCA().
RegisterELFStreamer()
void llvm::TargetRegistry::RegisterELFStreamer (Target & T, Target::ELFStreamerCtorTy Fn) inline static
Definition at line 969 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), and LLVMInitializeX86TargetMC().
RegisterInstrPostProcess()
void llvm::TargetRegistry::RegisterInstrPostProcess (Target & T, Target::InstrPostProcessCtorTy Fn) inline static
RegisterInstrPostProcess - Register an InstrPostProcess implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an InstrPostProcess for the target.
Definition at line 1047 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAMDGPUTargetMCA(), and LLVMInitializeX86TargetMCA().
RegisterInstrumentManager()
void llvm::TargetRegistry::RegisterInstrumentManager (Target & T, Target::InstrumentManagerCtorTy Fn) inline static
RegisterInstrumentManager - Register an InstrumentManager implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an InstrumentManager for the target.
Definition at line 1062 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeRISCVTargetMCA().
RegisterMachOStreamer()
void llvm::TargetRegistry::RegisterMachOStreamer (Target & T, Target::MachOStreamerCtorTy Fn) inline static
Definition at line 965 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeARMTargetMC(), and LLVMInitializeRISCVTargetMC().
RegisterMCAsmBackend()
void llvm::TargetRegistry::RegisterMCAsmBackend (Target & T, Target::MCAsmBackendCtorTy Fn) inline static
RegisterMCAsmBackend - Register a MCAsmBackend implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an AsmBackend for the target.
Definition at line 891 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXtensaTargetMC(), and llvm::RegisterMCAsmBackend< MCAsmBackendImpl >::RegisterMCAsmBackend().
RegisterMCAsmInfo()
void llvm::TargetRegistry::RegisterMCAsmInfo (Target & T, Target::MCAsmInfoCtorFnTy Fn) inline static
RegisterMCAsmInfo - Register a MCAsmInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a MCAsmInfo for the target.
Definition at line 805 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeCSKYTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeXtensaTargetMC(), llvm::RegisterMCAsmInfo< MCAsmInfoImpl >::RegisterMCAsmInfo(), and llvm::RegisterMCAsmInfoFn::RegisterMCAsmInfoFn().
RegisterMCAsmParser()
void llvm::TargetRegistry::RegisterMCAsmParser (Target & T, Target::MCAsmParserCtorTy Fn) inline static
RegisterMCAsmParser - Register a MCTargetAsmParser implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCTargetAsmParser for the target.
Definition at line 904 of file TargetRegistry.h.
References T.
Referenced by llvm::RegisterMCAsmParser< MCAsmParserImpl >::RegisterMCAsmParser().
RegisterMCCodeEmitter()
void llvm::TargetRegistry::RegisterMCCodeEmitter (Target & T, Target::MCCodeEmitterCtorTy Fn) inline static
RegisterMCCodeEmitter - Register a MCCodeEmitter implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCCodeEmitter for the target.
Definition at line 957 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXtensaTargetMC(), and llvm::RegisterMCCodeEmitter< MCCodeEmitterImpl >::RegisterMCCodeEmitter().
RegisterMCDisassembler()
void llvm::TargetRegistry::RegisterMCDisassembler (Target & T, Target::MCDisassemblerCtorTy Fn) inline static
RegisterMCDisassembler - Register a MCDisassembler implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCDisassembler for the target.
Definition at line 930 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64Disassembler(), LLVMInitializeAMDGPUDisassembler(), LLVMInitializeARCDisassembler(), LLVMInitializeARMDisassembler(), LLVMInitializeAVRDisassembler(), LLVMInitializeBPFDisassembler(), LLVMInitializeCSKYDisassembler(), LLVMInitializeHexagonDisassembler(), LLVMInitializeLanaiDisassembler(), LLVMInitializeLoongArchDisassembler(), LLVMInitializeM68kDisassembler(), LLVMInitializeMipsDisassembler(), LLVMInitializeMSP430Disassembler(), LLVMInitializePowerPCDisassembler(), LLVMInitializeRISCVDisassembler(), LLVMInitializeSparcDisassembler(), LLVMInitializeSystemZDisassembler(), LLVMInitializeVEDisassembler(), LLVMInitializeWebAssemblyDisassembler(), LLVMInitializeX86Disassembler(), LLVMInitializeXCoreDisassembler(), and LLVMInitializeXtensaDisassembler().
RegisterMCInstPrinter()
void llvm::TargetRegistry::RegisterMCInstPrinter (Target & T, Target::MCInstPrinterCtorTy Fn) inline static
RegisterMCInstPrinter - Register a MCInstPrinter implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCInstPrinter for the target.
Definition at line 944 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTargetMC(), and LLVMInitializeXtensaTargetMC().
RegisterMCInstrAnalysis()
void llvm::TargetRegistry::RegisterMCInstrAnalysis (Target & T, Target::MCInstrAnalysisCtorFnTy Fn) inline static
RegisterMCInstrAnalysis - Register a MCInstrAnalysis implementation for the given target.
Definition at line 837 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeX86TargetMC(), llvm::RegisterMCInstrAnalysis< MCInstrAnalysisImpl >::RegisterMCInstrAnalysis(), and llvm::RegisterMCInstrAnalysisFn::RegisterMCInstrAnalysisFn().
RegisterMCInstrInfo()
void llvm::TargetRegistry::RegisterMCInstrInfo (Target & T, Target::MCInstrInfoCtorFnTy Fn) inline static
RegisterMCInstrInfo - Register a MCInstrInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a MCInstrInfo for the target.
Definition at line 831 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaTargetMC(), llvm::RegisterMCInstrInfo< MCInstrInfoImpl >::RegisterMCInstrInfo(), and llvm::RegisterMCInstrInfoFn::RegisterMCInstrInfoFn().
RegisterMCObjectFileInfo()
void llvm::TargetRegistry::RegisterMCObjectFileInfo (Target & T, Target::MCObjectFileInfoCtorFnTy Fn) inline static
Register a MCObjectFileInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a MCObjectFileInfo for the target.
Definition at line 817 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeRISCVTargetMC(), llvm::RegisterMCObjectFileInfo< MCObjectFileInfoImpl >::RegisterMCObjectFileInfo(), and llvm::RegisterMCObjectFileInfoFn::RegisterMCObjectFileInfoFn().
RegisterMCRegInfo()
void llvm::TargetRegistry::RegisterMCRegInfo (Target & T, Target::MCRegInfoCtorFnTy Fn) inline static
RegisterMCRegInfo - Register a MCRegisterInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a MCRegisterInfo for the target.
Definition at line 851 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaTargetMC(), llvm::RegisterMCRegInfo< MCRegisterInfoImpl >::RegisterMCRegInfo(), and llvm::RegisterMCRegInfoFn::RegisterMCRegInfoFn().
RegisterMCRelocationInfo()
void llvm::TargetRegistry::RegisterMCRelocationInfo (Target & T, Target::MCRelocationInfoCtorTy Fn) inline static
RegisterMCRelocationInfo - Register an MCRelocationInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCRelocationInfo for the target.
Definition at line 1006 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeARMTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeM68kTargetMC(), and LLVMInitializeX86TargetMC().
RegisterMCSubtargetInfo()
void llvm::TargetRegistry::RegisterMCSubtargetInfo (Target & T, Target::MCSubtargetInfoCtorFnTy Fn) inline static
RegisterMCSubtargetInfo - Register a MCSubtargetInfo implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a MCSubtargetInfo for the target.
Definition at line 864 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaTargetMC(), llvm::RegisterMCSubtargetInfo< MCSubtargetInfoImpl >::RegisterMCSubtargetInfo(), and llvm::RegisterMCSubtargetInfoFn::RegisterMCSubtargetInfoFn().
RegisterMCSymbolizer()
void llvm::TargetRegistry::RegisterMCSymbolizer (Target & T, Target::MCSymbolizerCtorTy Fn) inline static
RegisterMCSymbolizer - Register an MCSymbolizer implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct an MCSymbolizer for the target.
Definition at line 1020 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64Disassembler(), and LLVMInitializeAMDGPUDisassembler().
RegisterNullTargetStreamer()
void llvm::TargetRegistry::RegisterNullTargetStreamer (Target & T, Target::NullTargetStreamerCtorTy Fn) inline static
Definition at line 977 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), and LLVMInitializeXCoreTargetMC().
RegisterObjectTargetStreamer()
void llvm::TargetRegistry::RegisterObjectTargetStreamer (Target & T, Target::ObjectTargetStreamerCtorTy Fn) inline static
Definition at line 992 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRTargetMC(), LLVMInitializeCSKYTargetMC(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLoongArchTargetMC(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430TargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeRISCVTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86TargetMC(), and LLVMInitializeXtensaTargetMC().
RegisterTarget()
void TargetRegistry::RegisterTarget (Target & T, const char * Name, const char * ShortDesc, const char * BackendName, Target::ArchMatchFnTy ArchMatchFn, bool HasJIT = false) static
RegisterTarget - Register the given target.
Attempts to register a target which has already been registered will be ignored.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Name - The target name. This should be a static string.
ShortDesc - A short target description. This should be a static string.
BackendName - The name of the backend. This should be a static string that is the same for all targets that share a backend implementation and must match the name used in the 'def X : Target ...' in TableGen.
ArchMatchFn - The arch match checking function for this target.
HasJIT - Whether the target supports JIT code generation.
Definition at line 169 of file TargetRegistry.cpp.
References assert(), FirstTarget, and T.
Referenced by LLVMInitializeAArch64TargetInfo(), LLVMInitializeBPFTargetInfo(), and llvm::RegisterTarget< TargetArchType, HasJIT >::RegisterTarget().
RegisterTargetMachine()
void llvm::TargetRegistry::RegisterTargetMachine (Target & T, Target::TargetMachineCtorTy Fn) inline static
RegisterTargetMachine - Register a TargetMachine implementation for the given target.
Clients are responsible for ensuring that registration doesn't occur while another thread is attempting to access the registry. Typically this is done by initializing all targets at program startup.
Parameters
T - The target being registered.
Fn - A function to construct a TargetMachine for the target.
Definition at line 878 of file TargetRegistry.h.
References T.
Referenced by llvm::RegisterTargetMachine< TargetMachineImpl >::RegisterTargetMachine().
RegisterXCOFFStreamer()
void llvm::TargetRegistry::RegisterXCOFFStreamer (Target & T, Target::XCOFFStreamerCtorTy Fn) inline static
Definition at line 973 of file TargetRegistry.h.
References T.
Referenced by LLVMInitializePowerPCTargetMC().
targets()
iterator_range< TargetRegistry::iterator > TargetRegistry::targets () static
Definition at line 101 of file TargetRegistry.cpp.
References FirstTarget, and llvm::make_range().
Referenced by LLVMGetFirstTarget(), LLVMGetTargetFromName(), lookupTarget(), lookupTarget(), printRegisteredTargetsForVersion(), and llvm::EngineBuilder::selectTarget().
The documentation for this struct was generated from the following files:
include/llvm/MC/TargetRegistry.h
lib/MC/TargetRegistry.cpp