LLVM: llvm::orc::MachOBuilderDylibLoadCommand< LCType > Struct Template Reference
llvm::orc::MachOBuilderDylibLoadCommand< LCType > Struct Template Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Public Member Functions
MachOBuilderDylibLoadCommand (std::string Name, uint32_t Timestamp, uint32_t CurrentVersion, uint32_t CompatibilityVersion)
size_t write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) override
Public Attributes
std::string Name
Detailed Description
template<MachO::LoadCommandType LCType>
struct llvm::orc::MachOBuilderDylibLoadCommand< LCType >
Definition at line 85 of file MachOBuilder.h.
Constructor & Destructor Documentation
MachOBuilderDylibLoadCommand()
template<MachO::LoadCommandType LCType> llvm::orc::MachOBuilderDylibLoadCommand< LCType >::MachOBuilderDylibLoadCommand (std::string Name, uint32_t Timestamp, uint32_t CurrentVersion, uint32_t CompatibilityVersion) inline
Definition at line 88 of file MachOBuilder.h.
References llvm::move(), and Name.
Member Function Documentation
write()
template<MachO::LoadCommandType LCType> size_t llvm::orc::MachOBuilderDylibLoadCommand< LCType >::write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) inline override
Definition at line 97 of file MachOBuilder.h.
References llvm::MutableArrayRef< T >::data(), Name, llvm::Offset, and llvm::orc::writeMachOStruct().
Member Data Documentation
Name
template<MachO::LoadCommandType LCType> std::string llvm::orc::MachOBuilderDylibLoadCommand< LCType >::Name
Definition at line 104 of file MachOBuilder.h.
Referenced by MachOBuilderDylibLoadCommand(), and write().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h