LLVM: llvm::lsp::DocumentLink Struct Reference
llvm::lsp::DocumentLink Struct Reference
A range in a text document that links to an internal or external resource, like another text document or a web site.
#include "llvm/Support/LSP/Protocol.h"
Public Member Functions
DocumentLink ()=default
DocumentLink (Range range, URIForFile target)
Public Attributes
Range range
The range this link applies to.
URIForFile target
The uri this link points to. If missing a resolve request is sent later.
Friends
bool operator== (const DocumentLink &lhs, const DocumentLink &rhs)
bool operator!= (const DocumentLink &lhs, const DocumentLink &rhs)
Detailed Description
A range in a text document that links to an internal or external resource, like another text document or a web site.
Definition at line 1062 of file Protocol.h.
Constructor & Destructor Documentation
DocumentLink() [1/2]
llvm::lsp::DocumentLink::DocumentLink () default
Referenced by operator!=, and operator==.
DocumentLink() [2/2]
llvm::lsp::DocumentLink::DocumentLink (Range range, URIForFile target) inline
Definition at line 1064 of file Protocol.h.
References llvm::move(), range, and target.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const DocumentLink & lhs, const DocumentLink & rhs) friend
Definition at line 1084 of file Protocol.h.
References DocumentLink().
operator==
bool operator== (const DocumentLink & lhs, const DocumentLink & rhs) friend
Definition at line 1080 of file Protocol.h.
References DocumentLink(), range, and target.
Member Data Documentation
range
Range llvm::lsp::DocumentLink::range
The range this link applies to.
Definition at line 1068 of file Protocol.h.
Referenced by DocumentLink(), and operator==.
target
URIForFile llvm::lsp::DocumentLink::target
The uri this link points to. If missing a resolve request is sent later.
Definition at line 1071 of file Protocol.h.
Referenced by DocumentLink(), and operator==.
The documentation for this struct was generated from the following file:
include/llvm/Support/LSP/Protocol.h