LLVM: llvm::DenseMapInfo< ArrayRef< T >, void > Struct Template Reference
llvm::DenseMapInfo< ArrayRef< T >, void > Struct Template Reference
#include "llvm/ADT/ArrayRef.h"
Static Public Member Functions
static ArrayRef< T > getEmptyKey ()
static ArrayRef< T > getTombstoneKey ()
static unsigned getHashValue (ArrayRef< T > Val)
static bool isEqual (ArrayRef< T > LHS, ArrayRef< T > RHS)
Detailed Description
template<typename T>
struct llvm::DenseMapInfo< ArrayRef< T >, void >
Definition at line 589 of file ArrayRef.h.
Member Function Documentation
getEmptyKey()
template<typename T> ArrayRef< T > llvm::DenseMapInfo< ArrayRef< T >, void >::getEmptyKey () inline static
Definition at line 590 of file ArrayRef.h.
References T.
Referenced by getHashValue(), and isEqual().
getHashValue()
template<typename T> unsigned llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue (ArrayRef< T > Val) inline static
Definition at line 600 of file ArrayRef.h.
References assert(), data, llvm::ArrayRef< T >::data(), getEmptyKey(), getTombstoneKey(), and llvm::hash_value().
getTombstoneKey()
template<typename T> ArrayRef< T > llvm::DenseMapInfo< ArrayRef< T >, void >::getTombstoneKey () inline static
Definition at line 595 of file ArrayRef.h.
References T.
Referenced by getHashValue(), and isEqual().
isEqual()
template<typename T> bool llvm::DenseMapInfo< ArrayRef< T >, void >::isEqual (ArrayRef< T > LHS, ArrayRef< T > RHS) inline static
Definition at line 608 of file ArrayRef.h.
References data, getEmptyKey(), getTombstoneKey(), LHS, and RHS.
The documentation for this struct was generated from the following file:
include/llvm/ADT/ArrayRef.h