LLVM: llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain > Struct Template Reference
llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Types
using PredType = Pred_t
Public Member Functions
MaxMin_match (const LHS_P &L, const RHS_P &R)
template<typename MatchContext>
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
LHS_P LHS
RHS_P RHS
Detailed Description
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false>
struct llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >
Definition at line 677 of file SDPatternMatch.h.
Member Typedef Documentation
PredType
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false> using llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::PredType = Pred_t
Definition at line 678 of file SDPatternMatch.h.
Constructor & Destructor Documentation
MaxMin_match()
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false> llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::MaxMin_match (const LHS_P & L, const RHS_P & R) inline
Definition at line 682 of file SDPatternMatch.h.
References LHS, and RHS.
Member Function Documentation
match()
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false> template<typename MatchContext> bool llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 685 of file SDPatternMatch.h.
References assert(), llvm::cast(), Cond, llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::FirstIndex, LHS, llvm::SDPatternMatch::m_Opc(), N, RHS, llvm::SDPatternMatch::sd_context_match(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::Size, and llvm::ISD::VSELECT.
Member Data Documentation
LHS
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false> LHS_P llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::LHS
Definition at line 679 of file SDPatternMatch.h.
Referenced by match(), and MaxMin_match().
RHS
template<typename LHS_P, typename RHS_P, typename Pred_t, bool Commutable = false, bool ExcludeChain = false> RHS_P llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::RHS
Definition at line 680 of file SDPatternMatch.h.
Referenced by match(), and MaxMin_match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h