LLVM: llvm::objcopy::dxbc::Object Struct Reference
llvm::objcopy::dxbc::Object Struct Reference
#include "ObjCopy/DXContainer/DXContainerObject.h"
Public Member Functions
size_t headerSize () const
Error removeParts (PartPred ToRemove)
void recomputeHeader ()
Public Attributes
::llvm::dxbc::Header Header
SmallVector< Part > Parts
Detailed Description
Definition at line 34 of file DXContainerObject.h.
Member Function Documentation
headerSize()
size_t llvm::objcopy::dxbc::Object::headerSize () const inline
Definition at line 38 of file DXContainerObject.h.
References Parts.
Referenced by recomputeHeader().
recomputeHeader()
void llvm::objcopy::dxbc::Object::recomputeHeader ()
Definition at line 20 of file DXContainerObject.cpp.
References Header, headerSize(), P, and Parts.
Referenced by llvm::objcopy::dxbc::extractPartAsObject().
removeParts()
Error llvm::objcopy::dxbc::Object::removeParts (PartPred ToRemove)
Definition at line 15 of file DXContainerObject.cpp.
References llvm::erase_if(), Parts, llvm::Error::success(), and ToRemove.
Member Data Documentation
Header
::llvm::dxbc::Header llvm::objcopy::dxbc::Object::Header
Definition at line 35 of file DXContainerObject.h.
Referenced by llvm::objcopy::dxbc::extractPartAsObject(), and recomputeHeader().
Parts
SmallVector<Part> llvm::objcopy::dxbc::Object::Parts
Definition at line 36 of file DXContainerObject.h.
Referenced by llvm::objcopy::dxbc::extractPartAsObject(), headerSize(), recomputeHeader(), and removeParts().
The documentation for this struct was generated from the following files:
lib/ObjCopy/DXContainer/DXContainerObject.h
lib/ObjCopy/DXContainer/DXContainerObject.cpp