LLVM: llvm::codeview::BinaryAnnotationIterator Struct Reference
llvm::codeview::BinaryAnnotationIterator Struct Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
BinaryAnnotationIterator ()=default
BinaryAnnotationIterator (ArrayRef< uint8_t > Annotations)
BinaryAnnotationIterator (const BinaryAnnotationIterator &Other)
bool operator== (BinaryAnnotationIterator Other) const
BinaryAnnotationIterator & operator= (const BinaryAnnotationIterator Other)
BinaryAnnotationIterator & operator++ ()
const DecodedAnnotation & operator* ()
Public Member Functions inherited from llvm::iterator_facade_base< BinaryAnnotationIterator, std::forward_iterator_tag, DecodedAnnotation >
BinaryAnnotationIterator operator+ (std::ptrdiff_t n) const
BinaryAnnotationIterator operator- (std::ptrdiff_t n) const
BinaryAnnotationIterator & operator++ ()
BinaryAnnotationIterator & operator-- ()
bool operator!= (const BinaryAnnotationIterator &RHS) const
bool operator> (const BinaryAnnotationIterator &RHS) const
bool operator<= (const BinaryAnnotationIterator &RHS) const
bool operator>= (const BinaryAnnotationIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< BinaryAnnotationIterator, std::forward_iterator_tag, DecodedAnnotation >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Definition at line 204 of file SymbolRecord.h.
Constructor & Destructor Documentation
BinaryAnnotationIterator() [1/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator () default
Referenced by BinaryAnnotationIterator(), operator++(), operator=(), and operator==().
BinaryAnnotationIterator() [2/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator (ArrayRef< uint8_t > Annotations) inline
Definition at line 209 of file SymbolRecord.h.
BinaryAnnotationIterator() [3/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator (const BinaryAnnotationIterator & Other) inline
Definition at line 210 of file SymbolRecord.h.
References BinaryAnnotationIterator().
Member Function Documentation
operator*()
const DecodedAnnotation & llvm::codeview::BinaryAnnotationIterator::operator* () inline
Definition at line 233 of file SymbolRecord.h.
operator++()
BinaryAnnotationIterator & llvm::codeview::BinaryAnnotationIterator::operator++ () inline
Definition at line 222 of file SymbolRecord.h.
References BinaryAnnotationIterator().
operator=()
BinaryAnnotationIterator & llvm::codeview::BinaryAnnotationIterator::operator= (const BinaryAnnotationIterator Other) inline
Definition at line 217 of file SymbolRecord.h.
References BinaryAnnotationIterator(), and llvm::codeview::Other.
operator==()
bool llvm::codeview::BinaryAnnotationIterator::operator== (BinaryAnnotationIterator Other) const inline
Definition at line 213 of file SymbolRecord.h.
References BinaryAnnotationIterator(), and llvm::codeview::Other.
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h