LLVM: llvm::memprof::IndexedAllocationInfo Struct Reference
llvm::memprof::IndexedAllocationInfo Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
IndexedAllocationInfo ()=default
IndexedAllocationInfo (CallStackId CSId, const MemInfoBlock &MB, const MemProfSchema &Schema=getFullSchema())
IndexedAllocationInfo (CallStackId CSId, const PortableMemInfoBlock &MB)
LLVM_ABI size_t serializedSize (const MemProfSchema &Schema, IndexedVersion Version) const
bool operator== (const IndexedAllocationInfo &Other) const
bool operator!= (const IndexedAllocationInfo &Other) const
Public Attributes
CallStackId CSId = 0
PortableMemInfoBlock Info
Detailed Description
Definition at line 381 of file MemProf.h.
Constructor & Destructor Documentation
IndexedAllocationInfo() [1/3]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo () default
Referenced by operator!=(), and operator==().
IndexedAllocationInfo() [2/3]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo (CallStackId CSId, const MemInfoBlock & MB, const MemProfSchema & Schema = getFullSchema()) inline
Definition at line 389 of file MemProf.h.
References CSId, llvm::memprof::getFullSchema(), and Info.
IndexedAllocationInfo() [3/3]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo (CallStackId CSId, const PortableMemInfoBlock & MB) inline
Definition at line 392 of file MemProf.h.
References CSId, and Info.
Member Function Documentation
operator!=()
bool llvm::memprof::IndexedAllocationInfo::operator!= (const IndexedAllocationInfo & Other) const inline
Definition at line 408 of file MemProf.h.
References IndexedAllocationInfo(), and operator==().
operator==()
bool llvm::memprof::IndexedAllocationInfo::operator== (const IndexedAllocationInfo & Other) const inline
Definition at line 399 of file MemProf.h.
References CSId, IndexedAllocationInfo(), and Info.
serializedSize()
size_t llvm::memprof::IndexedAllocationInfo::serializedSize (const MemProfSchema & Schema, IndexedVersion Version) const
Definition at line 44 of file MemProf.cpp.
References llvm_unreachable, llvm::memprof::serializedSizeV2(), llvm::memprof::serializedSizeV3(), llvm::Version, llvm::memprof::Version2, llvm::memprof::Version3, and llvm::memprof::Version4.
Member Data Documentation
CSId
CallStackId llvm::memprof::IndexedAllocationInfo::CSId = 0
Definition at line 384 of file MemProf.h.
Referenced by llvm::IndexedMemProfReader::getMemProfCallerCalleePairs(), IndexedAllocationInfo(), IndexedAllocationInfo(), and operator==().
Info
PortableMemInfoBlock llvm::memprof::IndexedAllocationInfo::Info
Definition at line 386 of file MemProf.h.
Referenced by IndexedAllocationInfo(), IndexedAllocationInfo(), and operator==().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/MemProf.h
lib/ProfileData/MemProf.cpp