LLVM: llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs > Struct Template Reference
llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs > Struct Template Reference
#include "llvm/ExecutionEngine/Orc/CallSPSViaEPC.h"
Public Types
using RetSerialization = shared::SPSArgList<SPSRetT>
using ArgSerialization = shared::SPSArgList<SPSArgTs...>
Public Member Functions
template<typename... ArgTs>
Expected< shared::WrapperFunctionBuffer > serialize (ArgTs &&...Args)
Detailed Description
template<typename SPSRetT, typename... SPSArgTs>
struct llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs >
Definition at line 24 of file CallSPSViaEPC.h.
Member Typedef Documentation
ArgSerialization
template<typename SPSRetT, typename... SPSArgTs> using llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs >::ArgSerialization = shared::SPSArgList<SPSArgTs...>
Definition at line 26 of file CallSPSViaEPC.h.
RetSerialization
template<typename SPSRetT, typename... SPSArgTs> using llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs >::RetSerialization = shared::SPSArgList<SPSRetT>
Definition at line 25 of file CallSPSViaEPC.h.
Member Function Documentation
serialize()
template<typename SPSRetT, typename... SPSArgTs> template<typename... ArgTs> Expected< shared::WrapperFunctionBuffer > llvm::orc::detail::SPSCallSerializationImpl< SPSRetT, SPSArgTs >::serialize (ArgTs &&... Args) inline
Definition at line 29 of file CallSPSViaEPC.h.
References llvm::orc::shared::WrapperFunctionBuffer::allocate(), llvm::inconvertibleErrorCode(), and llvm::make_error().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/CallSPSViaEPC.h