LLVM: llvm::yaml::MappingTraits< WasmYAML::ElemSegment > Struct Reference
llvm::yaml::MappingTraits< WasmYAML::ElemSegment > Struct Reference
#include "llvm/ObjectYAML/WasmYAML.h"
Static Public Member Functions
static void mapping (IO &IO, WasmYAML::ElemSegment &Segment)
Detailed Description
Definition at line 550 of file WasmYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< WasmYAML::ElemSegment >::mapping (IO & IO, WasmYAML::ElemSegment & Segment) static
Definition at line 380 of file WasmYAML.cpp.
References llvm::WasmYAML::ElemSegment::ElemKind, llvm::WasmYAML::ElemSegment::Flags, llvm::WasmYAML::ElemSegment::Functions, llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::WasmYAML::ElemSegment::Offset, llvm::yaml::IO::outputting(), llvm::WasmYAML::ElemSegment::TableNumber, llvm::wasm::WASM_ELEM_SEGMENT_HAS_TABLE_NUMBER, and llvm::wasm::WASM_ELEM_SEGMENT_MASK_HAS_ELEM_DESC.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/WasmYAML.h
lib/ObjectYAML/WasmYAML.cpp