LLVM: llvm::lowertypetests::BitSetBuilder Struct Reference
llvm::lowertypetests::BitSetBuilder Struct Reference
#include "llvm/Transforms/IPO/LowerTypeTests.h"
Public Member Functions
BitSetBuilder (ArrayRef< uint64_t > Offsets)
LLVM_ABI BitSetInfo build ()
Public Attributes
SmallVector< uint64_t, 16 > Offsets
uint64_t Min = std::numeric_limits<uint64_t>::max()
uint64_t Max = 0
Detailed Description
Definition at line 62 of file LowerTypeTests.h.
Constructor & Destructor Documentation
BitSetBuilder()
llvm::lowertypetests::BitSetBuilder::BitSetBuilder (ArrayRef< uint64_t > Offsets) inline explicit
Definition at line 67 of file LowerTypeTests.h.
References Offsets.
Member Function Documentation
build()
BitSetInfo BitSetBuilder::build ()
Definition at line 165 of file LowerTypeTests.cpp.
References llvm::lowertypetests::BitSetInfo::AlignLog2, llvm::lowertypetests::BitSetInfo::Bits, llvm::lowertypetests::BitSetInfo::BitSize, llvm::lowertypetests::BitSetInfo::ByteOffset, llvm::countr_zero(), Max, Min, llvm::Offset, and Offsets.
Referenced by buildBitSet().
Member Data Documentation
Max
uint64_t llvm::lowertypetests::BitSetBuilder::Max = 0
Definition at line 65 of file LowerTypeTests.h.
Referenced by build().
Min
uint64_t llvm::lowertypetests::BitSetBuilder::Min = std::numeric_limits<uint64_t>::max()
Definition at line 64 of file LowerTypeTests.h.
Referenced by build().
Offsets
SmallVector<uint64_t, 16> llvm::lowertypetests::BitSetBuilder::Offsets
Definition at line 63 of file LowerTypeTests.h.
Referenced by BitSetBuilder(), and build().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/LowerTypeTests.h
lib/Transforms/IPO/LowerTypeTests.cpp