LLVM: llvm::sframe::FDEInfo< E > Struct Template Reference
llvm::sframe::FDEInfo< E > Struct Template Reference
#include "llvm/BinaryFormat/SFrame.h"
Public Member Functions
uint8_t getPAuthKey () const
FDEType getFDEType () const
FREType getFREType () const
void setPAuthKey (uint8_t P)
void setFDEType (FDEType D)
void setFREType (FREType R)
void setFuncInfo (uint8_t PAuthKey, FDEType FDE, FREType FRE)
uint8_t getFuncInfo () const
Public Attributes
detail::packed< uint8_t, E > Info
Detailed Description
template<endianness E>
struct llvm::sframe::FDEInfo< E >
Definition at line 107 of file SFrame.h.
Member Function Documentation
getFDEType()
template<endianness E> FDEType llvm::sframe::FDEInfo< E >::getFDEType () const inline
Definition at line 111 of file SFrame.h.
References Info.
Referenced by setFREType(), and setPAuthKey().
getFREType()
template<endianness E> FREType llvm::sframe::FDEInfo< E >::getFREType () const inline
Definition at line 112 of file SFrame.h.
References Info.
Referenced by setFDEType(), and setPAuthKey().
getFuncInfo()
template<endianness E> uint8_t llvm::sframe::FDEInfo< E >::getFuncInfo () const inline
Definition at line 120 of file SFrame.h.
References Info.
getPAuthKey()
template<endianness E> uint8_t llvm::sframe::FDEInfo< E >::getPAuthKey () const inline
Definition at line 110 of file SFrame.h.
References Info.
Referenced by setFDEType(), and setFREType().
setFDEType()
template<endianness E> void llvm::sframe::FDEInfo< E >::setFDEType (FDEType D) inline
Definition at line 114 of file SFrame.h.
References D(), getFREType(), getPAuthKey(), and setFuncInfo().
setFREType()
template<endianness E> void llvm::sframe::FDEInfo< E >::setFREType (FREType R) inline
Definition at line 115 of file SFrame.h.
References getFDEType(), getPAuthKey(), and setFuncInfo().
setFuncInfo()
template<endianness E> void llvm::sframe::FDEInfo< E >::setFuncInfo (uint8_t PAuthKey, FDEType FDE, FREType FRE) inline
Definition at line 116 of file SFrame.h.
References Info.
Referenced by setFDEType(), setFREType(), and setPAuthKey().
setPAuthKey()
template<endianness E> void llvm::sframe::FDEInfo< E >::setPAuthKey (uint8_t P) inline
Definition at line 113 of file SFrame.h.
References getFDEType(), getFREType(), P, and setFuncInfo().
Member Data Documentation
Info
template<endianness E> detail::packed<uint8_t, E> llvm::sframe::FDEInfo< E >::Info
Definition at line 108 of file SFrame.h.
Referenced by getFDEType(), getFREType(), getFuncInfo(), getPAuthKey(), and setFuncInfo().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/SFrame.h