LLVM: RemoveMask_match< Op0_t, Op1_t > Struct Template Reference
RemoveMask_match< Op0_t, Op1_t > Struct Template Reference
Public Member Functions
RemoveMask_match (const Op0_t &In, Op1_t &Out)
template<typename OpTy>
bool match (OpTy *V) const
Public Attributes
Op0_t In
Op1_t & Out
Detailed Description
template<typename Op0_t, typename Op1_t>
struct RemoveMask_match< Op0_t, Op1_t >
Definition at line 2889 of file VPlanTransforms.cpp.
Constructor & Destructor Documentation
RemoveMask_match()
template<typename Op0_t, typename Op1_t> RemoveMask_match< Op0_t, Op1_t >::RemoveMask_match (const Op0_t & In, Op1_t & Out) inline
Definition at line 2893 of file VPlanTransforms.cpp.
References In, and Out.
Member Function Documentation
match()
template<typename Op0_t, typename Op1_t> template<typename OpTy> bool RemoveMask_match< Op0_t, Op1_t >::match (OpTy * V) const inline
Definition at line 2895 of file VPlanTransforms.cpp.
References In, llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_Specific(), llvm::VPlanPatternMatch::m_VPValue(), llvm::SCEVPatternMatch::match(), and Out.
Member Data Documentation
In
template<typename Op0_t, typename Op1_t> Op0_t RemoveMask_match< Op0_t, Op1_t >::In
Definition at line 2890 of file VPlanTransforms.cpp.
Referenced by match(), and RemoveMask_match().
Out
template<typename Op0_t, typename Op1_t> Op1_t& RemoveMask_match< Op0_t, Op1_t >::Out
Definition at line 2891 of file VPlanTransforms.cpp.
Referenced by match(), and RemoveMask_match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanTransforms.cpp