LLVM: llvm::MachineInstrBundleIteratorHelper< true > Struct Reference
llvm::MachineInstrBundleIteratorHelper< true > Struct Reference
#include "llvm/CodeGen/MachineInstrBundleIterator.h"
Static Public Member Functions
template<class Iterator>
static Iterator getBundleBegin (Iterator I)
Get the beginning of the current bundle.
template<class Iterator>
static Iterator getBundleFinal (Iterator I)
Get the final node of the current bundle.
template<class Iterator>
static void increment (Iterator &I)
Increment reverse ilist iterator.
template<class Iterator>
static void decrement (Iterator &I)
Decrement reverse ilist iterator.
Detailed Description
Definition at line 79 of file MachineInstrBundleIterator.h.
Member Function Documentation
decrement()
template<class Iterator> void llvm::MachineInstrBundleIteratorHelper< true >::decrement (Iterator & I) inline static
Decrement reverse ilist iterator.
Definition at line 100 of file MachineInstrBundleIterator.h.
References getBundleFinal(), and I.
getBundleBegin()
template<class Iterator> Iterator llvm::MachineInstrBundleIteratorHelper< true >::getBundleBegin (Iterator I) inline static
Get the beginning of the current bundle.
Definition at line 81 of file MachineInstrBundleIterator.h.
References I.
Referenced by increment().
getBundleFinal()
template<class Iterator> Iterator llvm::MachineInstrBundleIteratorHelper< true >::getBundleFinal (Iterator I) inline static
Get the final node of the current bundle.
Definition at line 88 of file MachineInstrBundleIterator.h.
References I.
Referenced by decrement().
increment()
template<class Iterator> void llvm::MachineInstrBundleIteratorHelper< true >::increment (Iterator & I) inline static
Increment reverse ilist iterator.
Definition at line 95 of file MachineInstrBundleIterator.h.
References getBundleBegin(), and I.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineInstrBundleIterator.h