LLVM: llvm::sframe::FREInfo< E > Struct Template Reference
llvm::sframe::FREInfo< E > Struct Template Reference
#include "llvm/BinaryFormat/SFrame.h"
Public Member Functions
bool isReturnAddressSigned () const
FREOffset getOffsetSize () const
uint8_t getOffsetCount () const
BaseReg getBaseRegister () const
void setReturnAddressSigned (bool RA)
void setOffsetSize (FREOffset Sz)
void setOffsetCount (uint8_t N)
void setBaseRegister (BaseReg Reg)
void setFREInfo (bool RA, FREOffset Sz, uint8_t N, BaseReg Reg)
uint8_t getFREInfo () const
Public Attributes
detail::packed< uint8_t, E > Info
Detailed Description
template<endianness E>
struct llvm::sframe::FREInfo< E >
Definition at line 133 of file SFrame.h.
Member Function Documentation
getBaseRegister()
template<endianness E> BaseReg llvm::sframe::FREInfo< E >::getBaseRegister () const inline
Definition at line 141 of file SFrame.h.
References Info.
Referenced by setOffsetCount(), setOffsetSize(), and setReturnAddressSigned().
getFREInfo()
template<endianness E> uint8_t llvm::sframe::FREInfo< E >::getFREInfo () const inline
Definition at line 159 of file SFrame.h.
References Info.
getOffsetCount()
template<endianness E> uint8_t llvm::sframe::FREInfo< E >::getOffsetCount () const inline
Definition at line 140 of file SFrame.h.
References Info.
Referenced by readFRE(), setBaseRegister(), setOffsetSize(), and setReturnAddressSigned().
getOffsetSize()
template<endianness E> FREOffset llvm::sframe::FREInfo< E >::getOffsetSize () const inline
Definition at line 137 of file SFrame.h.
References Info.
Referenced by readFRE(), setBaseRegister(), setOffsetCount(), and setReturnAddressSigned().
isReturnAddressSigned()
template<endianness E> bool llvm::sframe::FREInfo< E >::isReturnAddressSigned () const inline
Definition at line 136 of file SFrame.h.
References Info.
Referenced by setBaseRegister(), setOffsetCount(), and setOffsetSize().
setBaseRegister()
template<endianness E> void llvm::sframe::FREInfo< E >::setBaseRegister (BaseReg Reg) inline
Definition at line 152 of file SFrame.h.
References getOffsetCount(), getOffsetSize(), isReturnAddressSigned(), Reg, and setFREInfo().
setFREInfo()
template<endianness E> void llvm::sframe::FREInfo< E >::setFREInfo (bool RA, FREOffset Sz, uint8_t N, BaseReg Reg) inline
Definition at line 155 of file SFrame.h.
References Info, N, RA, and Reg.
Referenced by setBaseRegister(), setOffsetCount(), setOffsetSize(), and setReturnAddressSigned().
setOffsetCount()
template<endianness E> void llvm::sframe::FREInfo< E >::setOffsetCount (uint8_t N) inline
Definition at line 149 of file SFrame.h.
References getBaseRegister(), getOffsetSize(), isReturnAddressSigned(), N, and setFREInfo().
setOffsetSize()
template<endianness E> void llvm::sframe::FREInfo< E >::setOffsetSize (FREOffset Sz) inline
Definition at line 145 of file SFrame.h.
References getBaseRegister(), getOffsetCount(), isReturnAddressSigned(), and setFREInfo().
setReturnAddressSigned()
template<endianness E> void llvm::sframe::FREInfo< E >::setReturnAddressSigned (bool RA) inline
Definition at line 142 of file SFrame.h.
References getBaseRegister(), getOffsetCount(), getOffsetSize(), RA, and setFREInfo().
Member Data Documentation
Info
template<endianness E> detail::packed<uint8_t, E> llvm::sframe::FREInfo< E >::Info
Definition at line 134 of file SFrame.h.
Referenced by getBaseRegister(), getFREInfo(), getOffsetCount(), getOffsetSize(), isReturnAddressSigned(), readFRE(), and setFREInfo().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/SFrame.h