LLVM: llvm::remarks::YAMLRemarkSerializer Struct Reference
llvm::remarks::YAMLRemarkSerializer Struct Reference
Serialize the remarks to YAML.
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLRemarkSerializer (raw_ostream &OS)
YAMLRemarkSerializer (raw_ostream &OS, StringTable StrTabIn)
void emit (const Remark &Remark) override
Emit a remark to the stream.
std::unique_ptr< MetaSerializer > metaSerializer (raw_ostream &OS, StringRef ExternalFilename) override
Return the corresponding metadata serializer.
Public Member Functions inherited from llvm::remarks::RemarkSerializer
RemarkSerializer (Format SerializerFormat, raw_ostream &OS)
virtual ~RemarkSerializer ()=default
virtual void finalize ()
Finalize remark emission (e.g.
Static Public Member Functions
static bool classof (const RemarkSerializer *S)
Public Attributes
yaml::Output YAMLOutput
The YAML streamer.
Public Attributes inherited from llvm::remarks::RemarkSerializer
Format SerializerFormat
The format of the serializer.
raw_ostream & OS
The open raw_ostream that the remark diagnostics are emitted to.
std::optional< StringTable > StrTab
The string table containing all the unique strings used in the output.
Detailed Description
Serialize the remarks to YAML.
One remark entry looks like this: — !<TYPE> Pass: <PASSNAME> Name: <REMARKNAME> DebugLoc: { File: <SOURCEFILENAME>, Line: <SOURCELINE>, Column: <SOURCECOLUMN> } Function: <FUNCTIONNAME> Args:
<KEY>:
DebugLoc: { File: <FILE>, Line: <LINE>, Column: <COL> } ...
Definition at line 34 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLRemarkSerializer() [1/2]
YAMLRemarkSerializer::YAMLRemarkSerializer (raw_ostream & OS)
Definition at line 134 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::RemarkSerializer::OS, llvm::remarks::RemarkSerializer::RemarkSerializer(), YAMLOutput, and YAMLRemarkSerializer().
Referenced by YAMLRemarkSerializer(), and YAMLRemarkSerializer().
YAMLRemarkSerializer() [2/2]
YAMLRemarkSerializer::YAMLRemarkSerializer (raw_ostream & OS, StringTable StrTabIn)
Definition at line 138 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::RemarkSerializer::OS, llvm::remarks::RemarkSerializer::StrTab, and YAMLRemarkSerializer().
Member Function Documentation
classof()
bool llvm::remarks::YAMLRemarkSerializer::classof (const RemarkSerializer * S) inline static
Definition at line 45 of file YAMLRemarkSerializer.h.
References llvm::remarks::RemarkSerializer::RemarkSerializer(), llvm::remarks::RemarkSerializer::SerializerFormat, and llvm::remarks::YAML.
emit()
void YAMLRemarkSerializer::emit (const Remark & Remark) override virtual
Emit a remark to the stream.
Implements llvm::remarks::RemarkSerializer.
Definition at line 144 of file YAMLRemarkSerializer.cpp.
References YAMLOutput.
metaSerializer()
std::unique_ptr< MetaSerializer > YAMLRemarkSerializer::metaSerializer (raw_ostream & OS, StringRef ExternalFilename) override virtual
Return the corresponding metadata serializer.
Implements llvm::remarks::RemarkSerializer.
Definition at line 152 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::RemarkSerializer::OS.
Member Data Documentation
YAMLOutput
yaml::Output llvm::remarks::YAMLRemarkSerializer::YAMLOutput
The YAML streamer.
Definition at line 36 of file YAMLRemarkSerializer.h.
Referenced by emit(), and YAMLRemarkSerializer().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp