LLVM: llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes > Struct Template Reference
llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes > Struct Template Reference
SpecificCmp_match is a variant of Cmp_match that matches the comparison predicate, instead of binding it.
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
SpecificCmp_match (CmpPredicate Pred, const Op0_t &LHS, const Op1_t &RHS)
bool match (const VPValue *V) const
Public Attributes
const CmpPredicate Predicate
Op0_t Op0
Op1_t Op1
Detailed Description
template<typename Op0_t, typename Op1_t, unsigned... Opcodes>
struct llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >
SpecificCmp_match is a variant of Cmp_match that matches the comparison predicate, instead of binding it.
Definition at line 636 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
SpecificCmp_match()
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::SpecificCmp_match (CmpPredicate Pred, const Op0_t & LHS, const Op1_t & RHS) inline
Definition at line 641 of file VPlanPatternMatch.h.
References LHS, Op0, Op1, Predicate, and RHS.
Member Function Documentation
match()
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> bool llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::match (const VPValue * V) const inline
Definition at line 644 of file VPlanPatternMatch.h.
References llvm::CmpPredicate::getMatching(), match(), Op0, Op1, and Predicate.
Referenced by match().
Member Data Documentation
Op0
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> Op0_t llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::Op0
Definition at line 638 of file VPlanPatternMatch.h.
Referenced by match(), and SpecificCmp_match().
Op1
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> Op1_t llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::Op1
Definition at line 639 of file VPlanPatternMatch.h.
Referenced by match(), and SpecificCmp_match().
Predicate
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> const CmpPredicate llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::Predicate
Definition at line 637 of file VPlanPatternMatch.h.
Referenced by match(), and SpecificCmp_match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h