LLVM: llvm::GVNPass::Expression Struct Reference
llvm::GVNPass::Expression Struct Reference
Public Member Functions
Expression (uint32_t Op=~2U)
bool operator== (const Expression &Other) const
Public Attributes
uint32_t Opcode
bool Commutative = false
Type * Ty = nullptr
SmallVector< uint32_t, 4 > VarArgs
AttributeList Attrs
Friends
hash_code hash_value (const Expression &Value)
Detailed Description
Definition at line 140 of file GVN.cpp.
Constructor & Destructor Documentation
Expression()
llvm::GVNPass::Expression::Expression (uint32_t Op = ~2U) inline
Definition at line 150 of file GVN.cpp.
References Opcode.
Referenced by hash_value, and operator==().
Member Function Documentation
operator==()
bool llvm::GVNPass::Expression::operator== (const Expression & Other) const inline
Definition at line 152 of file GVN.cpp.
References Attrs, Expression(), Opcode, llvm::Other, Ty, and VarArgs.
Friends And Related Symbol Documentation
hash_value
hash_code hash_value (const Expression & Value) friend
Definition at line 167 of file GVN.cpp.
References Expression(), llvm::hash_combine(), and llvm::hash_combine_range().
Member Data Documentation
Attrs
AttributeList llvm::GVNPass::Expression::Attrs
Definition at line 148 of file GVN.cpp.
Referenced by operator==().
Commutative
bool llvm::GVNPass::Expression::Commutative = false
Definition at line 142 of file GVN.cpp.
Opcode
uint32_t llvm::GVNPass::Expression::Opcode
Definition at line 141 of file GVN.cpp.
Referenced by Expression(), and operator==().
Ty
Type* llvm::GVNPass::Expression::Ty = nullptr
Definition at line 145 of file GVN.cpp.
Referenced by operator==().
VarArgs
SmallVector<uint32_t, 4> llvm::GVNPass::Expression::VarArgs
Definition at line 146 of file GVN.cpp.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/GVN.cpp