LLVM: llvm::yaml::MappingTraits< const InterfaceFile * > Struct Reference
llvm::yaml::MappingTraits< const InterfaceFile * > Struct Reference
Classes
struct NormalizedTBD
struct NormalizedTBD_V4
Public Types
using SectionList = std::vector<SymbolSection>
Static Public Member Functions
static void setFileTypeForInput (TextAPIContext *Ctx, IO &IO)
static void mapping (IO &IO, const InterfaceFile *&File)
static void mapKeysToValues (FileType FileKind, IO &IO, const InterfaceFile *&File)
static void mapKeysToValuesV4 (IO &IO, const InterfaceFile *&File)
Detailed Description
Definition at line 399 of file TextStub.cpp.
Member Typedef Documentation
SectionList
using llvm::yaml::MappingTraits< const InterfaceFile * >::SectionList = std::vector<SymbolSection>
Definition at line 765 of file TextStub.cpp.
Member Function Documentation
mapKeysToValues()
void llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValues (FileType FileKind, IO & IO, const InterfaceFile *& File) inline static
Definition at line 984 of file TextStub.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::MachO::None, None, llvm::MachO::Retain_Release, llvm::MachO::TBD_V1, and llvm::MachO::TBD_V3.
Referenced by mapping().
mapKeysToValuesV4()
void llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValuesV4 (IO & IO, const InterfaceFile *& File) inline static
Definition at line 1015 of file TextStub.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapOptionalWithContext(), llvm::yaml::IO::mapRequired(), llvm::yaml::IO::mapTag(), and None.
Referenced by mapping().
mapping()
void llvm::yaml::MappingTraits< const InterfaceFile * >::mapping (IO & IO, const InterfaceFile *& File) inline static
Definition at line 725 of file TextStub.cpp.
References assert(), llvm::yaml::IO::getContext(), llvm::MachO::Invalid, llvm_unreachable, mapKeysToValues(), mapKeysToValuesV4(), llvm::yaml::IO::mapTag(), llvm::yaml::IO::outputting(), llvm::yaml::IO::setError(), setFileTypeForInput(), llvm::MachO::TBD_V1, llvm::MachO::TBD_V2, llvm::MachO::TBD_V3, and llvm::MachO::TBD_V4.
setFileTypeForInput()
void llvm::yaml::MappingTraits< const InterfaceFile * >::setFileTypeForInput (TextAPIContext * Ctx, IO & IO) inline static
Definition at line 709 of file TextStub.cpp.
References llvm::MachO::Invalid, llvm::yaml::IO::mapTag(), llvm::MachO::TBD_V1, llvm::MachO::TBD_V2, llvm::MachO::TBD_V3, and llvm::MachO::TBD_V4.
Referenced by mapping().
The documentation for this struct was generated from the following file:
lib/TextAPI/TextStub.cpp