LLVM: llvm::memprof::FrameIdConverter< MapTy > Struct Template Reference
llvm::memprof::FrameIdConverter< MapTy > Struct Template Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
FrameIdConverter ()=delete
FrameIdConverter (MapTy &Map)
FrameIdConverter (const FrameIdConverter &)=delete
FrameIdConverter & operator= (const FrameIdConverter &)=delete
Frame operator() (FrameId Id)
Public Attributes
std::optional< FrameId > LastUnmappedId
MapTy & Map
Detailed Description
template<typename MapTy>
struct llvm::memprof::FrameIdConverter< MapTy >
Definition at line 40 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
FrameIdConverter() [1/3]
template<typename MapTy> llvm::memprof::FrameIdConverter< MapTy >::FrameIdConverter () delete
Referenced by FrameIdConverter(), and operator=().
FrameIdConverter() [2/3]
template<typename MapTy> llvm::memprof::FrameIdConverter< MapTy >::FrameIdConverter (MapTy & Map) inline
Definition at line 45 of file MemProfRadixTree.h.
References Map.
FrameIdConverter() [3/3]
template<typename MapTy> llvm::memprof::FrameIdConverter< MapTy >::FrameIdConverter (const FrameIdConverter< MapTy > &) delete
References FrameIdConverter().
Member Function Documentation
operator()()
template<typename MapTy> Frame llvm::memprof::FrameIdConverter< MapTy >::operator() (FrameId Id) inline
Definition at line 53 of file MemProfRadixTree.h.
References llvm::memprof::detail::DerefIterator(), LastUnmappedId, and Map.
operator=()
template<typename MapTy> FrameIdConverter & llvm::memprof::FrameIdConverter< MapTy >::operator= (const FrameIdConverter< MapTy > &) delete
References FrameIdConverter().
Member Data Documentation
LastUnmappedId
template<typename MapTy> std::optional<FrameId> llvm::memprof::FrameIdConverter< MapTy >::LastUnmappedId
Definition at line 41 of file MemProfRadixTree.h.
Referenced by getMemProfRecordV2(), and operator()().
Map
template<typename MapTy> MapTy& llvm::memprof::FrameIdConverter< MapTy >::Map
Definition at line 42 of file MemProfRadixTree.h.
Referenced by FrameIdConverter(), and operator()().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProfRadixTree.h