LLVM: llvm::df_iterator_default_set< NodeRef, SmallSize > Struct Template Reference
llvm::df_iterator_default_set< NodeRef, SmallSize > Struct Template Reference
#include "llvm/ADT/DepthFirstIterator.h"
Public Types
using BaseSet = SmallPtrSet<NodeRef, SmallSize>
using iterator = typename BaseSet::iterator
Public Types inherited from llvm::SmallPtrSetImpl< NodeRef >
using iterator
using const_iterator
using key_type
using value_type
Public Types inherited from llvm::SmallPtrSetImplBase
using size_type = unsigned
Public Member Functions
std::pair< iterator, bool > insert (NodeRef N)
template<typename IterT>
void insert (IterT Begin, IterT End)
void completed (NodeRef)
Public Member Functions inherited from llvm::SmallPtrSet< NodeRef, 8 >
SmallPtrSet ()
SmallPtrSet< NodeRef, SmallSize > & operator= (const SmallPtrSet< NodeRef, SmallSize > &RHS)
void swap (SmallPtrSet< NodeRef, SmallSize > &RHS)
swap - Swaps the elements of two sets.
Public Member Functions inherited from llvm::SmallPtrSetImpl< NodeRef >
SmallPtrSetImpl (const SmallPtrSetImpl &)=delete
std::pair< iterator, bool > insert (NodeRef Ptr)
Inserts Ptr if and only if there is no element in the container equal to Ptr.
bool erase (NodeRef Ptr)
Remove pointer from the set.
bool remove_if (UnaryPredicate P)
Remove elements that match the given predicate.
size_type count (ConstPtrType Ptr) const
count - Return 1 if the specified pointer is in the set, 0 otherwise.
iterator find (ConstPtrType Ptr) const
bool contains (ConstPtrType Ptr) const
void insert_range (Range &&R)
iterator begin () const
iterator end () const
Public Member Functions inherited from llvm::SmallPtrSetImplBase
SmallPtrSetImplBase & operator= (const SmallPtrSetImplBase &)=delete
bool empty () const
size_type size () const
size_type capacity () const
void clear ()
void reserve (size_type NewNumEntries)
Public Member Functions inherited from llvm::DebugEpochBase
void incrementEpoch ()
Additional Inherited Members
Protected Member Functions inherited from llvm::SmallPtrSetImpl< NodeRef >
LLVM_ABI SmallPtrSetImplBase (const void **SmallStorage, const SmallPtrSetImplBase &that)
LLVM_ABI SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize, const void **RHSSmallStorage, SmallPtrSetImplBase &&that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize)
Protected Member Functions inherited from llvm::SmallPtrSetImplBase
LLVM_ABI SmallPtrSetImplBase (const void **SmallStorage, const SmallPtrSetImplBase &that)
LLVM_ABI SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize, const void **RHSSmallStorage, SmallPtrSetImplBase &&that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize)
~SmallPtrSetImplBase ()
const void ** EndPointer () const
iterator_range< const void ** > small_buckets ()
iterator_range< const void *const * > small_buckets () const
iterator_range< const void ** > buckets ()
iterator_range< const void *const * > buckets () const
std::pair< const void *const *, bool > insert_imp (const void *Ptr)
insert_imp - This returns true if the pointer was new to the set, false if it was already in the set.
bool erase_imp (const void *Ptr)
erase_imp - If the set contains the specified pointer, remove it and return true, otherwise return false.
const void *const * find_imp (const void *Ptr) const
Returns the raw pointer needed to construct an iterator.
bool contains_imp (const void *Ptr) const
bool isSmall () const
LLVM_ABI void swap (const void **SmallStorage, const void **RHSSmallStorage, SmallPtrSetImplBase &RHS)
swap - Swaps the elements of two sets.
LLVM_ABI void copyFrom (const void **SmallStorage, const SmallPtrSetImplBase &RHS)
LLVM_ABI void moveFrom (const void **SmallStorage, unsigned SmallSize, const void **RHSSmallStorage, SmallPtrSetImplBase &&RHS)
Static Protected Member Functions inherited from llvm::SmallPtrSetImplBase
static void * getTombstoneMarker ()
static void * getEmptyMarker ()
Protected Attributes inherited from llvm::SmallPtrSetImplBase
const void ** CurArray
The current set of buckets, in either small or big representation.
unsigned CurArraySize
CurArraySize - The allocated size of CurArray, always a power of two.
unsigned NumEntries
Number of elements in CurArray that contain a value.
unsigned NumTombstones
Number of tombstones in CurArray.
bool IsSmall
Whether the set is in small representation.
Detailed Description
template<typename NodeRef, unsigned SmallSize = 8>
struct llvm::df_iterator_default_set< NodeRef, SmallSize >
Definition at line 70 of file DepthFirstIterator.h.
Member Typedef Documentation
BaseSet
template<typename NodeRef, unsigned SmallSize = 8> using llvm::df_iterator_default_set< NodeRef, SmallSize >::BaseSet = SmallPtrSet<NodeRef, SmallSize>
Definition at line 71 of file DepthFirstIterator.h.
iterator
template<typename NodeRef, unsigned SmallSize = 8> using llvm::df_iterator_default_set< NodeRef, SmallSize >::iterator = typename BaseSet::iterator
Definition at line 72 of file DepthFirstIterator.h.
Member Function Documentation
completed()
template<typename NodeRef, unsigned SmallSize = 8> void llvm::df_iterator_default_set< NodeRef, SmallSize >::completed (NodeRef) inline
Definition at line 78 of file DepthFirstIterator.h.
insert() [1/2]
template<typename NodeRef, unsigned SmallSize = 8> template<typename IterT> void llvm::df_iterator_default_set< NodeRef, SmallSize >::insert (IterT Begin, IterT End) inline
Definition at line 76 of file DepthFirstIterator.h.
References llvm::SmallPtrSetImpl< NodeRef >::insert().
insert() [2/2]
template<typename NodeRef, unsigned SmallSize = 8> std::pair< iterator, bool > llvm::df_iterator_default_set< NodeRef, SmallSize >::insert (NodeRef N) inline
Definition at line 74 of file DepthFirstIterator.h.
References llvm::SmallPtrSetImpl< NodeRef >::insert(), and N.
Referenced by llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), and llvm::GenericCycle< ContextT >::verifyCycle().
The documentation for this struct was generated from the following file:
include/llvm/ADT/DepthFirstIterator.h