LLVM: llvm::remarks::RemarkParser Struct Reference
llvm::remarks::RemarkParser Struct Reference abstract
Parser used to parse a raw buffer to remarks::Remark objects.
#include "llvm/Remarks/RemarkParser.h"
Public Member Functions
RemarkParser (Format ParserFormat)
virtual Expected< std::unique_ptr< Remark > > next ()=0
If no error occurs, this returns a valid Remark object.
virtual ~RemarkParser ()=default
Public Attributes
Format ParserFormat
The format of the parser.
std::string ExternalFilePrependPath
Path to prepend when opening an external remark file.
Detailed Description
Parser used to parse a raw buffer to remarks::Remark objects.
Definition at line 41 of file RemarkParser.h.
Constructor & Destructor Documentation
RemarkParser()
llvm::remarks::RemarkParser::RemarkParser (Format ParserFormat) inline
Definition at line 47 of file RemarkParser.h.
References ParserFormat.
Referenced by llvm::remarks::BitstreamRemarkParser::BitstreamRemarkParser(), llvm::remarks::BitstreamRemarkParser::classof(), llvm::remarks::YAMLRemarkParser::classof(), and llvm::remarks::YAMLRemarkParser::YAMLRemarkParser().
~RemarkParser()
virtual llvm::remarks::RemarkParser::~RemarkParser () virtual default
Member Function Documentation
next()
virtual Expected< std::unique_ptr< Remark > > llvm::remarks::RemarkParser::next () pure virtual
If no error occurs, this returns a valid Remark object.
If an error of type EndOfFileError occurs, it is safe to recover from it by stopping the parsing. If any other error occurs, it should be propagated to the user. The pointer should never be null.
Implemented in llvm::remarks::BitstreamRemarkParser, and llvm::remarks::YAMLRemarkParser.
Referenced by llvm::remarks::RemarkLinker::link(), and LLVMRemarkParserGetNext().
Member Data Documentation
ExternalFilePrependPath
std::string llvm::remarks::RemarkParser::ExternalFilePrependPath
Path to prepend when opening an external remark file.
Definition at line 45 of file RemarkParser.h.
ParserFormat
Format llvm::remarks::RemarkParser::ParserFormat
The format of the parser.
Definition at line 43 of file RemarkParser.h.
Referenced by RemarkParser().
The documentation for this struct was generated from the following file:
include/llvm/Remarks/RemarkParser.h