LLVM: llvm::rdf::NodeBase Struct Reference
llvm::rdf::NodeBase Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Classes
struct Def_struct
struct PhiU_struct
struct Code_struct
struct Ref_struct
Public Member Functions
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (Node NA)
void init ()
void setNext (NodeId N)
Protected Attributes
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct RefData
Code_struct CodeData
};
Detailed Description
Definition at line 487 of file RDFGraph.h.
Constructor & Destructor Documentation
NodeBase()
llvm::rdf::NodeBase::NodeBase () default
Referenced by llvm::rdf::CodeNode::getFirstMember(), llvm::rdf::CodeNode::getLastMember(), llvm::rdf::RefNode::getNextRef(), llvm::rdf::RefNode::getOwner(), llvm::rdf::CodeNode::members_if(), and llvm::rdf::CodeNode::removeMember().
Member Function Documentation
append()
void llvm::rdf::NodeBase::append (Node NA)
Definition at line 389 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAddr< T >::Id, and Next.
Referenced by llvm::rdf::CodeNode::addMemberAfter().
getAttrs()
uint16_t llvm::rdf::NodeBase::getAttrs () const inline
Definition at line 497 of file RDFGraph.h.
References Attrs.
Referenced by setFlags().
getFlags()
uint16_t llvm::rdf::NodeBase::getFlags () const inline
Definition at line 494 of file RDFGraph.h.
References Attrs, and llvm::rdf::NodeAttrs::flags().
Referenced by llvm::rdf::RefNode::getOp(), llvm::rdf::PhiUseNode::getPredecessor(), and llvm::rdf::PhiUseNode::setPredecessor().
getKind()
uint16_t llvm::rdf::NodeBase::getKind () const inline
Definition at line 493 of file RDFGraph.h.
References Attrs, and llvm::rdf::NodeAttrs::kind().
Referenced by llvm::rdf::BlockNode::addPhi(), llvm::rdf::InstrNode::getOwner(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::DataFlowGraph::IsDef(), llvm::rdf::RefNode::isDef(), llvm::rdf::DataFlowGraph::IsPhi(), llvm::rdf::DataFlowGraph::IsRef(), llvm::rdf::DataFlowGraph::IsUse(), and llvm::rdf::RefNode::isUse().
getNext()
NodeId llvm::rdf::NodeBase::getNext () const inline
Definition at line 495 of file RDFGraph.h.
References Next.
Referenced by llvm::rdf::RefNode::getNextRef(), llvm::rdf::InstrNode::getOwner(), llvm::rdf::RefNode::getOwner(), and llvm::rdf::CodeNode::removeMember().
getType()
uint16_t llvm::rdf::NodeBase::getType () const inline
Definition at line 492 of file RDFGraph.h.
References Attrs, and llvm::rdf::NodeAttrs::type().
Referenced by llvm::rdf::BlockNode::addPhi(), llvm::rdf::InstrNode::getOwner(), llvm::rdf::RefNode::getOwner(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::DataFlowGraph::IsDef(), llvm::rdf::RefNode::isDef(), llvm::rdf::DataFlowGraph::IsPhi(), llvm::rdf::DataFlowGraph::IsRef(), llvm::rdf::DataFlowGraph::IsUse(), and llvm::rdf::RefNode::isUse().
init()
void llvm::rdf::NodeBase::init () inline
Definition at line 505 of file RDFGraph.h.
setAttrs()
void llvm::rdf::NodeBase::setAttrs (uint16_t A) inline
Definition at line 498 of file RDFGraph.h.
References A(), and Attrs.
Referenced by setFlags().
setFlags()
void llvm::rdf::NodeBase::setFlags (uint16_t F) inline
Definition at line 499 of file RDFGraph.h.
References F, getAttrs(), llvm::rdf::NodeAttrs::set_flags(), and setAttrs().
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
setNext()
void llvm::rdf::NodeBase::setNext (NodeId N) inline
Definition at line 507 of file RDFGraph.h.
References N, and Next.
Referenced by llvm::rdf::CodeNode::addMember(), llvm::rdf::BlockNode::addPhi(), and llvm::rdf::CodeNode::removeMember().
Member Data Documentation
[union]
union { ... } llvm::rdf::NodeBase
Attrs
uint16_t llvm::rdf::NodeBase::Attrs protected
Definition at line 510 of file RDFGraph.h.
Referenced by getAttrs(), getFlags(), getKind(), llvm::rdf::RefNode::getRegRef(), getType(), setAttrs(), llvm::rdf::RefNode::setRegRef(), and llvm::rdf::RefNode::setRegRef().
CodeData
Code_struct llvm::rdf::NodeBase::CodeData
Definition at line 541 of file RDFGraph.h.
Referenced by llvm::rdf::CodeNode::addMember(), llvm::rdf::CodeNode::addMemberAfter(), llvm::rdf::BlockNode::addPhi(), llvm::rdf::CodeNode::getCode(), llvm::rdf::CodeNode::getFirstMember(), llvm::rdf::CodeNode::getLastMember(), llvm::rdf::CodeNode::removeMember(), and llvm::rdf::CodeNode::setCode().
Next
NodeId llvm::rdf::NodeBase::Next protected
Definition at line 512 of file RDFGraph.h.
Referenced by append(), getNext(), and setNext().
RefData
Ref_struct llvm::rdf::NodeBase::RefData
Definition at line 540 of file RDFGraph.h.
Referenced by llvm::rdf::RefNode::getOp(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::rdf::DefNode::getReachedDef(), llvm::rdf::DefNode::getReachedUse(), llvm::rdf::RefNode::getReachingDef(), llvm::rdf::RefNode::getRegRef(), llvm::rdf::RefNode::getSibling(), llvm::rdf::DefNode::linkToDef(), llvm::rdf::UseNode::linkToDef(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::rdf::DefNode::setReachedDef(), llvm::rdf::DefNode::setReachedUse(), llvm::rdf::RefNode::setReachingDef(), llvm::rdf::RefNode::setRegRef(), llvm::rdf::RefNode::setRegRef(), and llvm::rdf::RefNode::setSibling().
Reserved
uint16_t llvm::rdf::NodeBase::Reserved protected
Definition at line 511 of file RDFGraph.h.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp