LLVM: llvm::NVPTXScopes Struct Reference
llvm::NVPTXScopes Struct Reference
#include "Target/NVPTX/NVPTXISelDAGToDAG.h"
Public Member Functions
NVPTXScopes ()=default
NVPTXScopes (LLVMContext &C)
NVPTX::Scope operator[] (SyncScope::ID ID) const
bool empty () const
Detailed Description
Definition at line 31 of file NVPTXISelDAGToDAG.h.
Constructor & Destructor Documentation
NVPTXScopes() [1/2]
llvm::NVPTXScopes::NVPTXScopes () default
References llvm::CallingConv::C.
NVPTXScopes() [2/2]
NVPTXScopes::NVPTXScopes (LLVMContext & C)
Definition at line 1869 of file NVPTXISelDAGToDAG.cpp.
References llvm::NVPTX::Block, llvm::CallingConv::C, llvm::NVPTX::Cluster, llvm::NVPTX::Device, llvm::NVPTX::System, and llvm::NVPTX::Thread.
Member Function Documentation
empty()
bool NVPTXScopes::empty () const
Definition at line 1903 of file NVPTXISelDAGToDAG.cpp.
operator[]()
NVPTX::Scope NVPTXScopes::operator[] (SyncScope::ID ID) const
Definition at line 1877 of file NVPTXISelDAGToDAG.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::formatv(), llvm_unreachable, llvm::make_range(), name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reportFatalUsageError().
The documentation for this struct was generated from the following files:
lib/Target/NVPTX/NVPTXISelDAGToDAG.h
lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp