LLVM: llvm::AAMDNodes Struct Reference
llvm::AAMDNodes Struct Reference
A collection of metadata nodes that might be associated with a memory access used by the alias-analysis infrastructure.
#include "llvm/IR/Metadata.h"
Public Member Functions
AAMDNodes ()=default
AAMDNodes (MDNode *T, MDNode *TS, MDNode *S, MDNode *N, MDNode *NAS)
bool operator== (const AAMDNodes &A) const
bool operator!= (const AAMDNodes &A) const
operator bool () const
AAMDNodes intersect (const AAMDNodes &Other) const
Given two sets of AAMDNodes that apply to the same pointer, give the best AAMDNodes that are compatible with both (i.e.
AAMDNodes shift (size_t Offset) const
Create a new AAMDNode that describes this AAMDNode after applying a constant offset to the start of the pointer.
AAMDNodes extendTo (ssize_t Len) const
Create a new AAMDNode that describes this AAMDNode after extending it to apply to a series of bytes of length Len.
LLVM_ABI AAMDNodes merge (const AAMDNodes &Other) const
Given two sets of AAMDNodes applying to potentially different locations, determine the best AAMDNodes that apply to both.
LLVM_ABI AAMDNodes concat (const AAMDNodes &Other) const
Determine the best AAMDNodes after concatenating two different locations together.
LLVM_ABI AAMDNodes adjustForAccess (unsigned AccessSize)
Create a new AAMDNode for accessing AccessSize bytes of this AAMDNode.
LLVM_ABI AAMDNodes adjustForAccess (size_t Offset, Type *AccessTy, const DataLayout &DL)
LLVM_ABI AAMDNodes adjustForAccess (size_t Offset, unsigned AccessSize)
Static Public Member Functions
static LLVM_ABI MDNode * shiftTBAA (MDNode *M, size_t off)
static LLVM_ABI MDNode * shiftTBAAStruct (MDNode *M, size_t off)
static LLVM_ABI MDNode * extendToTBAA (MDNode *TBAA, ssize_t len)
Public Attributes
MDNode * TBAA = nullptr
The tag for type-based alias analysis.
MDNode * TBAAStruct = nullptr
The tag for type-based alias analysis (tbaa struct).
MDNode * Scope = nullptr
The tag for alias scope specification (used with noalias).
MDNode * NoAlias = nullptr
The tag specifying the noalias scope.
MDNode * NoAliasAddrSpace = nullptr
The tag specifying the noalias address spaces.
Detailed Description
A collection of metadata nodes that might be associated with a memory access used by the alias-analysis infrastructure.
Definition at line 761 of file Metadata.h.
Constructor & Destructor Documentation
AAMDNodes() [1/2]
llvm::AAMDNodes::AAMDNodes () explicit default
Referenced by adjustForAccess(), adjustForAccess(), adjustForAccess(), concat(), extendTo(), intersect(), merge(), operator!=(), operator==(), and shift().
AAMDNodes() [2/2]
llvm::AAMDNodes::AAMDNodes (MDNode * T, MDNode * TS, MDNode * S, MDNode * N, MDNode * NAS) inline explicit
Definition at line 763 of file Metadata.h.
References N, NoAlias, NoAliasAddrSpace, Scope, T, TBAA, and TBAAStruct.
Member Function Documentation
adjustForAccess() [1/3]
AAMDNodes AAMDNodes::adjustForAccess (size_t Offset, Type * AccessTy, const DataLayout & DL)
Definition at line 865 of file TypeBasedAliasAnalysis.cpp.
References AAMDNodes(), DL, llvm::Offset, shift(), and Size.
adjustForAccess() [2/3]
AAMDNodes AAMDNodes::adjustForAccess (size_t Offset, unsigned AccessSize)
Definition at line 877 of file TypeBasedAliasAnalysis.cpp.
References AAMDNodes(), llvm::Offset, and shift().
adjustForAccess() [3/3]
AAMDNodes AAMDNodes::adjustForAccess (unsigned AccessSize)
Create a new AAMDNode for accessing AccessSize bytes of this AAMDNode.
If this AAMDNode has !tbaa.struct and AccessSize matches the size of the field at offset 0, get the TBAA tag describing the accessed field. If such an AAMDNode already embeds !tbaa, the existing one is retrieved. Finally, !tbaa.struct is zeroed out.
Definition at line 849 of file TypeBasedAliasAnalysis.cpp.
References AAMDNodes(), llvm::cast(), llvm::mdconst::extract(), llvm::mdconst::hasa(), and llvm::isa().
concat()
AAMDNodes AAMDNodes::concat (const AAMDNodes & Other) const
Determine the best AAMDNodes after concatenating two different locations together.
Different from merge, where different locations should overlap each other, concat puts non-overlapping locations together.
Definition at line 553 of file TypeBasedAliasAnalysis.cpp.
References AAMDNodes(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericNoaliasAddrspace(), llvm::MDNode::intersect(), NoAlias, NoAliasAddrSpace, llvm::Other, and Scope.
Referenced by foldLoadsRecursive(), and mergeConsecutivePartStores().
extendTo()
AAMDNodes llvm::AAMDNodes::extendTo (ssize_t Len) const inline
Create a new AAMDNode that describes this AAMDNode after extending it to apply to a series of bytes of length Len.
A size of -1 denotes an unknown size.
Definition at line 834 of file Metadata.h.
References AAMDNodes(), extendToTBAA(), NoAlias, NoAliasAddrSpace, Scope, TBAA, and TBAAStruct.
extendToTBAA()
MDNode * AAMDNodes::extendToTBAA (MDNode * TBAA, ssize_t len) static
Definition at line 815 of file TypeBasedAliasAnalysis.cpp.
References llvm::ConstantInt::equalsInt(), llvm::mdconst::extract(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDNode::getContext(), llvm::Value::getType(), isStructPathTBAA(), llvm::MDNode::operands(), and llvm::Tag.
Referenced by extendTo().
intersect()
AAMDNodes llvm::AAMDNodes::intersect (const AAMDNodes & Other) const inline
Given two sets of AAMDNodes that apply to the same pointer, give the best AAMDNodes that are compatible with both (i.e.
a set of nodes whose allowable aliasing conclusions are a subset of those allowable by both of the inputs). However, for efficiency reasons, do not create any new MDNodes.
Definition at line 807 of file Metadata.h.
References AAMDNodes(), NoAlias, NoAliasAddrSpace, llvm::Other, Scope, TBAA, and TBAAStruct.
merge()
AAMDNodes AAMDNodes::merge (const AAMDNodes & Other) const
Given two sets of AAMDNodes applying to potentially different locations, determine the best AAMDNodes that apply to both.
Definition at line 542 of file TypeBasedAliasAnalysis.cpp.
References AAMDNodes(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericNoaliasAddrspace(), llvm::MDNode::getMostGenericTBAA(), llvm::MDNode::intersect(), NoAlias, NoAliasAddrSpace, llvm::Other, Scope, and TBAA.
Referenced by mergeConditionalStoreToAddress(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), and llvm::promoteLoopAccessesToScalars().
operator bool()
llvm::AAMDNodes::operator bool () const inline explicit
Definition at line 773 of file Metadata.h.
References NoAlias, NoAliasAddrSpace, Scope, TBAA, and TBAAStruct.
operator!=()
bool llvm::AAMDNodes::operator!= (const AAMDNodes & A) const inline
Definition at line 771 of file Metadata.h.
References A(), and AAMDNodes().
operator==()
bool llvm::AAMDNodes::operator== (const AAMDNodes & A) const inline
Definition at line 766 of file Metadata.h.
References A(), AAMDNodes(), NoAlias, NoAliasAddrSpace, Scope, TBAA, and TBAAStruct.
shift()
AAMDNodes llvm::AAMDNodes::shift (size_t Offset) const inline
Create a new AAMDNode that describes this AAMDNode after applying a constant offset to the start of the pointer.
Definition at line 820 of file Metadata.h.
References AAMDNodes(), NoAlias, NoAliasAddrSpace, llvm::Offset, Scope, shiftTBAA(), shiftTBAAStruct(), TBAA, and TBAAStruct.
Referenced by adjustForAccess(), and adjustForAccess().
shiftTBAA()
MDNode * AAMDNodes::shiftTBAA (MDNode * M, size_t off) static
Definition at line 766 of file TypeBasedAliasAnalysis.cpp.
References isStructPathTBAA(), and llvm::Offset.
Referenced by shift().
shiftTBAAStruct()
MDNode * AAMDNodes::shiftTBAAStruct (MDNode * M, size_t off) static
Definition at line 785 of file TypeBasedAliasAnalysis.cpp.
References llvm::mdconst::extract(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDNode::getContext(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Offset, llvm::size(), and llvm::Sub.
Referenced by shift().
Member Data Documentation
NoAlias
MDNode* llvm::AAMDNodes::NoAlias = nullptr
The tag specifying the noalias scope.
Definition at line 787 of file Metadata.h.
Referenced by AAMDNodes(), llvm::ScopedNoAliasAAResult::alias(), concat(), extendTo(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), llvm::VPlanTransforms::hoistInvariantLoads(), intersect(), merge(), operator bool(), operator==(), and shift().
NoAliasAddrSpace
MDNode* llvm::AAMDNodes::NoAliasAddrSpace = nullptr
The tag specifying the noalias address spaces.
Definition at line 790 of file Metadata.h.
Referenced by AAMDNodes(), concat(), extendTo(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), intersect(), merge(), operator bool(), operator==(), and shift().
Scope
MDNode* llvm::AAMDNodes::Scope = nullptr
The tag for alias scope specification (used with noalias).
Definition at line 784 of file Metadata.h.
Referenced by AAMDNodes(), llvm::ScopedNoAliasAAResult::alias(), concat(), extendTo(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), llvm::VPlanTransforms::hoistInvariantLoads(), intersect(), merge(), operator bool(), operator==(), and shift().
TBAA
MDNode* llvm::AAMDNodes::TBAA = nullptr
The tag for type-based alias analysis.
Definition at line 778 of file Metadata.h.
Referenced by AAMDNodes(), llvm::TypeBasedAAResult::alias(), collectMemAccessInfo(), extendTo(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), intersect(), merge(), operator bool(), operator==(), and shift().
TBAAStruct
MDNode* llvm::AAMDNodes::TBAAStruct = nullptr
The tag for type-based alias analysis (tbaa struct).
Definition at line 781 of file Metadata.h.
Referenced by AAMDNodes(), extendTo(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), intersect(), operator bool(), operator==(), and shift().
The documentation for this struct was generated from the following files:
include/llvm/IR/Metadata.h
lib/Analysis/TypeBasedAliasAnalysis.cpp