LLVM: llvm::MCCFIInstruction::CommonFields Struct Reference
llvm::MCCFIInstruction::CommonFields Struct Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
CommonFields (unsigned Reg, int64_t Off=0, unsigned Reg2=std::numeric_limits< unsigned >::max(), unsigned AddrSpace=0)
CommonFields ()
Public Attributes
unsigned Register
int64_t Offset
unsigned Register2
unsigned AddressSpace
Detailed Description
Definition at line 536 of file MCDwarf.h.
Constructor & Destructor Documentation
CommonFields() [1/2]
llvm::MCCFIInstruction::CommonFields::CommonFields (unsigned Reg, int64_t Off = 0, unsigned Reg2 = std::numeric_limits<unsigned>::max(), unsigned AddrSpace = 0) inline
Definition at line 545 of file MCDwarf.h.
References AddressSpace, Offset, Reg, Register, and Register2.
Referenced by CommonFields().
CommonFields() [2/2]
llvm::MCCFIInstruction::CommonFields::CommonFields () inline
Definition at line 550 of file MCDwarf.h.
References CommonFields(), and llvm::max().
Member Data Documentation
AddressSpace
unsigned llvm::MCCFIInstruction::CommonFields::AddressSpace
Definition at line 540 of file MCDwarf.h.
Referenced by CommonFields().
Offset
int64_t llvm::MCCFIInstruction::CommonFields::Offset
Definition at line 538 of file MCDwarf.h.
Referenced by CommonFields().
Register
unsigned llvm::MCCFIInstruction::CommonFields::Register
Definition at line 537 of file MCDwarf.h.
Referenced by CommonFields().
Register2
unsigned llvm::MCCFIInstruction::CommonFields::Register2
Definition at line 539 of file MCDwarf.h.
Referenced by CommonFields().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCDwarf.h