LLVM: llvm::MCAsmMacro Struct Reference
llvm::MCAsmMacro Struct Reference
#include "llvm/MC/MCAsmMacro.h"
Public Member Functions
MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P)
MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P, std::vector< std::string > L, bool F)
void dump () const
LLVM_DUMP_METHOD void dump (raw_ostream &OS) const
Public Attributes
StringRef Name
StringRef Body
MCAsmMacroParameters Parameters
std::vector< std::string > Locals
bool IsFunction = false
unsigned Count = 0
Detailed Description
Definition at line 135 of file MCAsmMacro.h.
Constructor & Destructor Documentation
MCAsmMacro() [1/2]
llvm::MCAsmMacro::MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P) inline
Definition at line 144 of file MCAsmMacro.h.
References B(), Body, llvm::move(), N, Name, P, and Parameters.
MCAsmMacro() [2/2]
llvm::MCAsmMacro::MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P, std::vector< std::string > L, bool F) inline
Definition at line 146 of file MCAsmMacro.h.
References B(), Body, F, IsFunction, Locals, llvm::move(), N, Name, P, and Parameters.
Member Function Documentation
dump() [1/2]
void llvm::MCAsmMacro::dump () const inline
Definition at line 152 of file MCAsmMacro.h.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void MCAsmMacro::dump (raw_ostream & OS) const
Definition at line 34 of file MCAsmMacro.cpp.
References Body, Locals, Name, P, and Parameters.
Member Data Documentation
Body
StringRef llvm::MCAsmMacro::Body
Definition at line 137 of file MCAsmMacro.h.
Referenced by dump(), MCAsmMacro(), and MCAsmMacro().
Count
unsigned llvm::MCAsmMacro::Count = 0
Definition at line 141 of file MCAsmMacro.h.
IsFunction
bool llvm::MCAsmMacro::IsFunction = false
Definition at line 140 of file MCAsmMacro.h.
Referenced by MCAsmMacro().
Locals
std::vector<std::string> llvm::MCAsmMacro::Locals
Definition at line 139 of file MCAsmMacro.h.
Referenced by dump(), and MCAsmMacro().
Name
StringRef llvm::MCAsmMacro::Name
Definition at line 136 of file MCAsmMacro.h.
Referenced by dump(), MCAsmMacro(), and MCAsmMacro().
Parameters
MCAsmMacroParameters llvm::MCAsmMacro::Parameters
Definition at line 138 of file MCAsmMacro.h.
Referenced by dump(), MCAsmMacro(), and MCAsmMacro().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCAsmMacro.h
lib/MC/MCAsmMacro.cpp