LLVM: llvm::AMDGPU::HardwareLimits Struct Reference
llvm::AMDGPU::HardwareLimits Struct Reference
Represents the hardware counter limits for different wait count types.
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
HardwareLimits ()=default
HardwareLimits (const IsaVersion &IV, bool HasExtendedWaitCounts)
Initializes hardware limits from ISA version.
Public Attributes
unsigned LoadcntMax
unsigned ExpcntMax
unsigned DscntMax
unsigned StorecntMax
unsigned SamplecntMax
unsigned BvhcntMax
unsigned KmcntMax
unsigned XcntMax
unsigned VaVdstMax
unsigned VmVsrcMax
Detailed Description
Represents the hardware counter limits for different wait count types.
Definition at line 1135 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
HardwareLimits() [1/2]
llvm::AMDGPU::HardwareLimits::HardwareLimits () default
References IV.
HardwareLimits() [2/2]
llvm::AMDGPU::HardwareLimits::HardwareLimits (const IsaVersion & IV, bool HasExtendedWaitCounts)
Initializes hardware limits from ISA version.
HasExtendedWaitCounts should be true for gfx12+.
Definition at line 1788 of file AMDGPUBaseInfo.cpp.
References BvhcntMax, DscntMax, ExpcntMax, llvm::AMDGPU::getBvhcntBitMask(), llvm::AMDGPU::getDscntBitMask(), llvm::AMDGPU::getExpcntBitMask(), llvm::AMDGPU::getKmcntBitMask(), llvm::AMDGPU::getLgkmcntBitMask(), llvm::AMDGPU::getLoadcntBitMask(), llvm::AMDGPU::getSamplecntBitMask(), llvm::AMDGPU::getStorecntBitMask(), llvm::AMDGPU::DepCtr::getVaVdstBitMask(), llvm::AMDGPU::getVmcntBitMask(), llvm::AMDGPU::DepCtr::getVmVsrcBitMask(), llvm::AMDGPU::getXcntBitMask(), IV, KmcntMax, LoadcntMax, SamplecntMax, StorecntMax, VaVdstMax, VmVsrcMax, and XcntMax.
Member Data Documentation
BvhcntMax
unsigned llvm::AMDGPU::HardwareLimits::BvhcntMax
Definition at line 1141 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
DscntMax
unsigned llvm::AMDGPU::HardwareLimits::DscntMax
Definition at line 1138 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
ExpcntMax
unsigned llvm::AMDGPU::HardwareLimits::ExpcntMax
Definition at line 1137 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
KmcntMax
unsigned llvm::AMDGPU::HardwareLimits::KmcntMax
Definition at line 1142 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
LoadcntMax
unsigned llvm::AMDGPU::HardwareLimits::LoadcntMax
Definition at line 1136 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
SamplecntMax
unsigned llvm::AMDGPU::HardwareLimits::SamplecntMax
Definition at line 1140 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
StorecntMax
unsigned llvm::AMDGPU::HardwareLimits::StorecntMax
Definition at line 1139 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
VaVdstMax
unsigned llvm::AMDGPU::HardwareLimits::VaVdstMax
Definition at line 1144 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
VmVsrcMax
unsigned llvm::AMDGPU::HardwareLimits::VmVsrcMax
Definition at line 1145 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
XcntMax
unsigned llvm::AMDGPU::HardwareLimits::XcntMax
Definition at line 1143 of file AMDGPUBaseInfo.h.
Referenced by HardwareLimits().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp