LLVM: llvm::GraphTraits< CallGraphNode * > Struct Reference
llvm::GraphTraits< CallGraphNode * > Struct Reference
#include "llvm/Analysis/CallGraph.h"
Public Types
using NodeRef = CallGraphNode *
using CGNPairTy = CallGraphNode::CallRecord
using ChildIteratorType
Static Public Member Functions
static NodeRef getEntryNode (CallGraphNode *CGN)
static CallGraphNode * CGNGetValue (CGNPairTy P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 416 of file CallGraph.h.
Member Typedef Documentation
CGNPairTy
using llvm::GraphTraits< CallGraphNode * >::CGNPairTy = CallGraphNode::CallRecord
Definition at line 418 of file CallGraph.h.
ChildIteratorType
using llvm::GraphTraits< CallGraphNode * >::ChildIteratorType
Initial value:
mapped_iterator<CallGraphNode::iterator, decltype(&CGNGetValue)>
Definition at line 423 of file CallGraph.h.
NodeRef
using llvm::GraphTraits< CallGraphNode * >::NodeRef = CallGraphNode *
Definition at line 417 of file CallGraph.h.
Member Function Documentation
CGNGetValue()
CallGraphNode * llvm::GraphTraits< CallGraphNode * >::CGNGetValue (CGNPairTy P) inline static
Definition at line 421 of file CallGraph.h.
References P.
Referenced by child_begin(), and child_end().
child_begin()
ChildIteratorType llvm::GraphTraits< CallGraphNode * >::child_begin (NodeRef N) inline static
Definition at line 426 of file CallGraph.h.
References CGNGetValue(), and N.
child_end()
ChildIteratorType llvm::GraphTraits< CallGraphNode * >::child_end (NodeRef N) inline static
Definition at line 430 of file CallGraph.h.
References CGNGetValue(), and N.
getEntryNode()
NodeRef llvm::GraphTraits< CallGraphNode * >::getEntryNode (CallGraphNode * CGN) inline static
Definition at line 420 of file CallGraph.h.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CallGraph.h