LLVM: llvm::codeview::serialize_null_term_string_array_impl Struct Reference
llvm::codeview::serialize_null_term_string_array_impl Struct Reference
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
Public Member Functions
serialize_null_term_string_array_impl (std::vector< StringRef > &Item)
Error deserialize (BinaryStreamReader &Reader) const
Public Attributes
std::vector< StringRef > & Item
Detailed Description
Definition at line 119 of file RecordSerialization.h.
Constructor & Destructor Documentation
serialize_null_term_string_array_impl()
llvm::codeview::serialize_null_term_string_array_impl::serialize_null_term_string_array_impl (std::vector< StringRef > & Item) inline
Definition at line 120 of file RecordSerialization.h.
References Item.
Member Function Documentation
deserialize()
Error llvm::codeview::serialize_null_term_string_array_impl::deserialize (BinaryStreamReader & Reader) const inline
Definition at line 123 of file RecordSerialization.h.
References llvm::codeview::EC, llvm::BinaryStreamReader::empty(), llvm::codeview::insufficient_buffer, Item, llvm::make_error(), llvm::BinaryStreamReader::peek(), llvm::BinaryStreamReader::readCString(), and llvm::BinaryStreamReader::skip().
Referenced by llvm::codeview::consume().
Member Data Documentation
Item
std::vector<StringRef>& llvm::codeview::serialize_null_term_string_array_impl::Item
Definition at line 137 of file RecordSerialization.h.
Referenced by deserialize(), and serialize_null_term_string_array_impl().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/RecordSerialization.h