LLVM: llvm::rdf::PhysicalRegisterInfo Struct Reference
llvm::rdf::PhysicalRegisterInfo Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Public Member Functions
PhysicalRegisterInfo (const TargetRegisterInfo &tri, const MachineFunction &mf)
RegisterId getRegMaskId (const uint32_t *RM) const
const uint32_t * getRegMaskBits (RegisterRef RR) const
bool alias (RegisterRef RA, RegisterRef RB) const
std::set< RegisterId > getAliasSet (RegisterRef RR) const
RegisterRef getRefForUnit (MCRegUnit U) const
const BitVector & getMaskUnits (RegisterRef RR) const
std::set< RegisterId > getUnits (RegisterRef RR) const
const BitVector & getUnitAliases (MCRegUnit U) const
RegisterRef mapTo (RegisterRef RR, RegisterId R) const
const TargetRegisterInfo & getTRI () const
bool equal_to (RegisterRef A, RegisterRef B) const
bool less (RegisterRef A, RegisterRef B) const
void print (raw_ostream &OS, RegisterRef A) const
void print (raw_ostream &OS, const RegisterAggr &A) const
Detailed Description
Definition at line 147 of file RDFRegisters.h.
Constructor & Destructor Documentation
PhysicalRegisterInfo()
llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo (const TargetRegisterInfo & tri, const MachineFunction & mf)
Definition at line 28 of file RDFRegisters.cpp.
References for().
Member Function Documentation
alias()
bool llvm::rdf::PhysicalRegisterInfo::alias (RegisterRef RA, RegisterRef RB) const
Definition at line 100 of file RDFRegisters.cpp.
References alias(), llvm::rdf::disjoint(), getUnits(), and RA.
Referenced by alias().
equal_to()
bool llvm::rdf::PhysicalRegisterInfo::equal_to (RegisterRef A, RegisterRef B) const
Definition at line 178 of file RDFRegisters.cpp.
References A(), B(), equal_to(), getTRI(), and llvm::MCRegUnitMaskIterator::isValid().
Referenced by equal_to(), and llvm::rdf::CopyPropagation::run().
getAliasSet()
std::set< RegisterId > llvm::rdf::PhysicalRegisterInfo::getAliasSet (RegisterRef RR) const
Definition at line 104 of file RDFRegisters.cpp.
References llvm::rdf::RegisterRef::asMCReg(), assert(), getAliasSet(), getRegMaskBits(), llvm::rdf::RegisterRef::isMask(), llvm::rdf::RegisterRef::isReg(), llvm::rdf::RegisterRef::isUnit(), and llvm::MCRegAliasIterator::isValid().
Referenced by getAliasSet().
getMaskUnits()
const BitVector & llvm::rdf::PhysicalRegisterInfo::getMaskUnits (RegisterRef RR) const inline
Definition at line 168 of file RDFRegisters.h.
References llvm::rdf::RegisterRef::asMaskIdx().
getRefForUnit()
RegisterRef llvm::rdf::PhysicalRegisterInfo::getRefForUnit (MCRegUnit U) const inline
Definition at line 164 of file RDFRegisters.h.
References Reg.
getRegMaskBits()
const uint32_t * llvm::rdf::PhysicalRegisterInfo::getRegMaskBits (RegisterRef RR) const inline
Definition at line 155 of file RDFRegisters.h.
References llvm::rdf::RegisterRef::asMaskIdx().
Referenced by getAliasSet(), and getUnits().
getRegMaskId()
RegisterId llvm::rdf::PhysicalRegisterInfo::getRegMaskId (const uint32_t * RM) const inline
Definition at line 151 of file RDFRegisters.h.
References llvm::rdf::RegisterRef::toMaskId().
getTRI()
const TargetRegisterInfo & llvm::rdf::PhysicalRegisterInfo::getTRI () const inline
Definition at line 179 of file RDFRegisters.h.
Referenced by equal_to(), and less().
getUnitAliases()
const BitVector & llvm::rdf::PhysicalRegisterInfo::getUnitAliases (MCRegUnit U) const inline
Definition at line 174 of file RDFRegisters.h.
getUnits()
std::set< RegisterId > llvm::rdf::PhysicalRegisterInfo::getUnits (RegisterRef RR) const
Definition at line 126 of file RDFRegisters.cpp.
References llvm::rdf::RegisterRef::asMCReg(), assert(), llvm::CallingConv::C, llvm::countr_zero(), E(), getRegMaskBits(), getUnits(), I, llvm::rdf::RegisterRef::isMask(), llvm::rdf::RegisterRef::isReg(), llvm::MCRegUnitMaskIterator::isValid(), llvm::rdf::RegisterRef::Mask, llvm::maskLeadingOnes(), llvm::maskTrailingOnes(), llvm::LaneBitmask::none(), and T.
Referenced by alias(), and getUnits().
less()
bool llvm::rdf::PhysicalRegisterInfo::less (RegisterRef A, RegisterRef B) const
Definition at line 214 of file RDFRegisters.cpp.
References A(), B(), getTRI(), llvm::MCRegUnitMaskIterator::isValid(), and less().
Referenced by less().
mapTo()
RegisterRef llvm::rdf::PhysicalRegisterInfo::mapTo (RegisterRef RR, RegisterId R) const
Definition at line 162 of file RDFRegisters.cpp.
References llvm::rdf::RegisterRef::asMCReg(), llvm::LaneBitmask::getAll(), llvm::rdf::RegisterRef::Id, llvm::TargetRegisterClass::LaneMask, llvm_unreachable, mapTo(), and llvm::rdf::RegisterRef::Mask.
Referenced by mapTo().
print() [1/2]
void llvm::rdf::PhysicalRegisterInfo::print (raw_ostream & OS, const RegisterAggr & A) const
Definition at line 269 of file RDFRegisters.cpp.
References A(), and print().
print() [2/2]
void llvm::rdf::PhysicalRegisterInfo::print (raw_ostream & OS, RegisterRef A) const
Definition at line 252 of file RDFRegisters.cpp.
References A(), llvm::format(), print(), llvm::printReg(), llvm::printRegUnit(), and Reg.
Referenced by print(), and print().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFRegisters.h
lib/CodeGen/RDFRegisters.cpp