LLVM: llvm::DIArgListInfo Struct Reference
llvm::DIArgListInfo Struct Reference
DenseMapInfo for DIArgList.
#include "IR/LLVMContextImpl.h"
Public Types
using KeyTy = DIArgListKeyInfo
Static Public Member Functions
static DIArgList * getEmptyKey ()
static DIArgList * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const DIArgList *N)
static bool isEqual (const KeyTy &LHS, const DIArgList *RHS)
static bool isEqual (const DIArgList *LHS, const DIArgList *RHS)
Detailed Description
DenseMapInfo for DIArgList.
Definition at line 1504 of file LLVMContextImpl.h.
Member Typedef Documentation
KeyTy
using llvm::DIArgListInfo::KeyTy = DIArgListKeyInfo
Definition at line 1505 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
DIArgList * llvm::DIArgListInfo::getEmptyKey () inline static
Definition at line 1507 of file LLVMContextImpl.h.
Referenced by isEqual().
getHashValue() [1/2]
unsigned llvm::DIArgListInfo::getHashValue (const DIArgList * N) inline static
Definition at line 1517 of file LLVMContextImpl.h.
References llvm::DIArgListKeyInfo::getHashValue(), and N.
getHashValue() [2/2]
unsigned llvm::DIArgListInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 1515 of file LLVMContextImpl.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getTombstoneKey()
DIArgList * llvm::DIArgListInfo::getTombstoneKey () inline static
Definition at line 1511 of file LLVMContextImpl.h.
Referenced by isEqual().
isEqual() [1/2]
bool llvm::DIArgListInfo::isEqual (const DIArgList * LHS, const DIArgList * RHS) inline static
Definition at line 1527 of file LLVMContextImpl.h.
References LHS, and RHS.
isEqual() [2/2]
bool llvm::DIArgListInfo::isEqual (const KeyTy & LHS, const DIArgList * RHS) inline static
Definition at line 1521 of file LLVMContextImpl.h.
References getEmptyKey(), getTombstoneKey(), LHS, and RHS.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h