LLVM: llvm::dxil::ComputedShaderFlags Struct Reference
llvm::dxil::ComputedShaderFlags Struct Reference
#include "Target/DirectX/DXILShaderFlags.h"
Public Member Functions
ComputedShaderFlags ()
constexpr uint64_t getMask (int Bit) const
uint64_t getModuleFlags () const
operator uint64_t () const
uint64_t getFeatureFlags () const
void merge (const ComputedShaderFlags CSF)
void print (raw_ostream &OS=dbgs()) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 34 of file DXILShaderFlags.h.
Constructor & Destructor Documentation
ComputedShaderFlags()
llvm::dxil::ComputedShaderFlags::ComputedShaderFlags () inline
Definition at line 43 of file DXILShaderFlags.h.
Referenced by merge().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void llvm::dxil::ComputedShaderFlags::dump () const inline
Definition at line 83 of file DXILShaderFlags.h.
References LLVM_DUMP_METHOD, and print().
getFeatureFlags()
uint64_t llvm::dxil::ComputedShaderFlags::getFeatureFlags () const inline
Definition at line 67 of file DXILShaderFlags.h.
getMask()
uint64_t llvm::dxil::ComputedShaderFlags::getMask (int Bit) const inline constexpr
Definition at line 47 of file DXILShaderFlags.h.
getModuleFlags()
uint64_t llvm::dxil::ComputedShaderFlags::getModuleFlags () const inline
Definition at line 51 of file DXILShaderFlags.h.
Referenced by operator uint64_t().
merge()
void llvm::dxil::ComputedShaderFlags::merge (const ComputedShaderFlags CSF) inline
Definition at line 75 of file DXILShaderFlags.h.
References ComputedShaderFlags().
Referenced by llvm::dxil::ModuleShaderFlags::initialize().
operator uint64_t()
llvm::dxil::ComputedShaderFlags::operator uint64_t () const inline
Definition at line 59 of file DXILShaderFlags.h.
References getModuleFlags().
print()
void ComputedShaderFlags::print (raw_ostream & OS = dbgs()) const
Definition at line 362 of file DXILShaderFlags.cpp.
References llvm::formatv().
Referenced by dump(), and llvm::dxil::ShaderFlagsAnalysisPrinter::run().
The documentation for this struct was generated from the following files:
lib/Target/DirectX/DXILShaderFlags.h
lib/Target/DirectX/DXILShaderFlags.cpp