LLVM: llvm::dwarf_linker::classic::PatchLocation Struct Reference
llvm::dwarf_linker::classic::PatchLocation Struct Reference
#include "llvm/DWARFLinker/Classic/DWARFLinkerCompileUnit.h"
Public Member Functions
PatchLocation ()=default
PatchLocation (DIE::value_iterator I)
PatchLocation (DIE::value_iterator I, int64_t Reloc)
void set (uint64_t New) const
uint64_t get () const
Public Attributes
DIE::value_iterator I
int64_t RelocAdjustment = 0
Detailed Description
Definition at line 37 of file DWARFLinkerCompileUnit.h.
Constructor & Destructor Documentation
PatchLocation() [1/3]
llvm::dwarf_linker::classic::PatchLocation::PatchLocation () default
PatchLocation() [2/3]
llvm::dwarf_linker::classic::PatchLocation::PatchLocation (DIE::value_iterator I) inline
Definition at line 42 of file DWARFLinkerCompileUnit.h.
References I.
PatchLocation() [3/3]
llvm::dwarf_linker::classic::PatchLocation::PatchLocation (DIE::value_iterator I, int64_t Reloc) inline
Definition at line 43 of file DWARFLinkerCompileUnit.h.
References I, and RelocAdjustment.
Member Function Documentation
get()
uint64_t llvm::dwarf_linker::classic::PatchLocation::get () const inline
Definition at line 53 of file DWARFLinkerCompileUnit.h.
References assert(), and I.
set()
void llvm::dwarf_linker::classic::PatchLocation::set (uint64_t New) const inline
Definition at line 46 of file DWARFLinkerCompileUnit.h.
References assert(), and I.
Referenced by llvm::dwarf_linker::classic::CompileUnit::fixupForwardReferences().
Member Data Documentation
I
DIE::value_iterator llvm::dwarf_linker::classic::PatchLocation::I
Definition at line 38 of file DWARFLinkerCompileUnit.h.
Referenced by get(), PatchLocation(), PatchLocation(), and set().
RelocAdjustment
int64_t llvm::dwarf_linker::classic::PatchLocation::RelocAdjustment = 0
Definition at line 39 of file DWARFLinkerCompileUnit.h.
Referenced by PatchLocation().
The documentation for this struct was generated from the following file:
include/llvm/DWARFLinker/Classic/DWARFLinkerCompileUnit.h