LLVM: llvm::orc::SPSCallSerializer< void(SPSArgTs...)> Struct Template Reference
llvm::orc::SPSCallSerializer< void(SPSArgTs...)> Struct Template Reference
SPS serialization for void calls.
#include "llvm/ExecutionEngine/Orc/CallSPSViaEPC.h"
Public Member Functions
template<typename RetT>
std::enable_if_t< std::is_void_v< RetT >, Error > deserialize (shared::WrapperFunctionBuffer ResultBytes)
Detailed Description
template<typename... SPSArgTs>
struct llvm::orc::SPSCallSerializer< void(SPSArgTs...)>
SPS serialization for void calls.
Definition at line 65 of file CallSPSViaEPC.h.
Member Function Documentation
deserialize()
template<typename... SPSArgTs> template<typename RetT> std::enable_if_t< std::is_void_v< RetT >, Error > llvm::orc::SPSCallSerializer< void(SPSArgTs...)>::deserialize (shared::WrapperFunctionBuffer ResultBytes) inline
Definition at line 69 of file CallSPSViaEPC.h.
References llvm::orc::shared::WrapperFunctionBuffer::empty(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/CallSPSViaEPC.h