LLVM: llvm::cl::OptionValueBase< DataType, false > Struct Template Reference
llvm::cl::OptionValueBase< DataType, false > Struct Template Reference
#include "llvm/Support/CommandLine.h"
Public Types
using WrapperType = DataType
Public Member Functions
bool hasValue () const
const DataType & getValue () const
void setValue (const DT &)
bool compare (const DataType &) const
Public Member Functions inherited from llvm::cl::OptionValueCopy< DataType >
OptionValueCopy ()=default
bool hasValue () const
const DataType & getValue () const
void setValue (const DataType &V)
bool compare (const DataType &V) const
bool compare (const GenericOptionValue &V) const override
Protected Member Functions
OptionValueBase ()=default
OptionValueBase (const OptionValueBase &)=default
OptionValueBase & operator= (const OptionValueBase &)=default
~OptionValueBase ()=default
Protected Member Functions inherited from llvm::cl::GenericOptionValue
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Protected Member Functions inherited from llvm::cl::OptionValueCopy< DataType >
OptionValueCopy (const OptionValueCopy &)=default
OptionValueCopy & operator= (const OptionValueCopy &)=default
~OptionValueCopy ()=default
Detailed Description
template<class DataType>
struct llvm::cl::OptionValueBase< DataType, false >
Definition at line 612 of file CommandLine.h.
Member Typedef Documentation
WrapperType
template<class DataType> using llvm::cl::OptionValueBase< DataType, false >::WrapperType = DataType
Definition at line 613 of file CommandLine.h.
Constructor & Destructor Documentation
OptionValueBase() [1/2]
template<class DataType> llvm::cl::OptionValueBase< DataType, false >::OptionValueBase () protected default
Referenced by operator=(), and OptionValueBase().
OptionValueBase() [2/2]
template<class DataType> llvm::cl::OptionValueBase< DataType, false >::OptionValueBase (const OptionValueBase< DataType, false > &) protected default
References OptionValueBase().
~OptionValueBase()
template<class DataType> llvm::cl::OptionValueBase< DataType, false >::~OptionValueBase () protected default
Member Function Documentation
compare()
bool llvm::cl::OptionValueBase< DataType, isClass >::compare (const DataType &) const inline
Definition at line 563 of file CommandLine.h.
getValue()
const DataType & llvm::cl::OptionValueBase< DataType, isClass >::getValue () const inline
Definition at line 557 of file CommandLine.h.
hasValue()
bool llvm::cl::OptionValueBase< DataType, isClass >::hasValue () const inline
Definition at line 555 of file CommandLine.h.
operator=()
template<class DataType> OptionValueBase & llvm::cl::OptionValueBase< DataType, false >::operator= (const OptionValueBase< DataType, false > &) protected default
References OptionValueBase().
setValue()
void llvm::cl::OptionValueBase< DataType, isClass >::setValue (const DT &) inline
Definition at line 560 of file CommandLine.h.
The documentation for this struct was generated from the following file:
include/llvm/Support/CommandLine.h