LLVM: llvm::GraphTraits< Inverse< BasicBlock * > > Struct Reference
llvm::GraphTraits< Inverse< BasicBlock * > > Struct Reference
#include "llvm/IR/CFG.h"
Public Types
using NodeRef = BasicBlock *
using ChildIteratorType = pred_iterator
Static Public Member Functions
static NodeRef getEntryNode (Inverse< BasicBlock * > G)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static unsigned getNumber (const BasicBlock *BB)
Detailed Description
Definition at line 336 of file CFG.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< Inverse< BasicBlock * > >::ChildIteratorType = pred_iterator
Definition at line 338 of file CFG.h.
NodeRef
using llvm::GraphTraits< Inverse< BasicBlock * > >::NodeRef = BasicBlock *
Definition at line 337 of file CFG.h.
Member Function Documentation
child_begin()
ChildIteratorType llvm::GraphTraits< Inverse< BasicBlock * > >::child_begin (NodeRef N) inline static
Definition at line 341 of file CFG.h.
References N, and llvm::pred_begin().
child_end()
ChildIteratorType llvm::GraphTraits< Inverse< BasicBlock * > >::child_end (NodeRef N) inline static
Definition at line 342 of file CFG.h.
References N, and llvm::pred_end().
getEntryNode()
NodeRef llvm::GraphTraits< Inverse< BasicBlock * > >::getEntryNode (Inverse< BasicBlock * > G) inline static
Definition at line 340 of file CFG.h.
References G.
getNumber()
unsigned llvm::GraphTraits< Inverse< BasicBlock * > >::getNumber (const BasicBlock * BB) inline static
Definition at line 344 of file CFG.h.
References llvm::BasicBlock::getNumber().
The documentation for this struct was generated from the following file:
include/llvm/IR/CFG.h