LLVM: SVEIntrinsicInfo Struct Reference
SVEIntrinsicInfo Struct Reference
Public Member Functions
operator bool () const
bool hasGoverningPredicate () const
unsigned getGoverningPredicateOperandIdx () const
SVEIntrinsicInfo & setGoverningPredicateOperandIdx (unsigned Index)
bool hasMatchingUndefIntrinsic () const
Intrinsic::ID getMatchingUndefIntrinsic () const
SVEIntrinsicInfo & setMatchingUndefIntrinsic (Intrinsic::ID IID)
bool hasMatchingIROpode () const
unsigned getMatchingIROpode () const
SVEIntrinsicInfo & setMatchingIROpcode (unsigned Opcode)
bool inactiveLanesTakenFromOperand () const
unsigned getOperandIdxInactiveLanesTakenFrom () const
SVEIntrinsicInfo & setOperandIdxInactiveLanesTakenFrom (unsigned Index)
bool inactiveLanesAreNotDefined () const
SVEIntrinsicInfo & setInactiveLanesAreNotDefined ()
bool inactiveLanesAreUnused () const
SVEIntrinsicInfo & setInactiveLanesAreUnused ()
bool resultIsZeroInitialized () const
SVEIntrinsicInfo & setResultIsZeroInitialized ()
bool hasOperandWithNoActiveLanes () const
unsigned getOperandIdxWithNoActiveLanes () const
SVEIntrinsicInfo & setOperandIdxWithNoActiveLanes (unsigned Index)
Static Public Member Functions
static SVEIntrinsicInfo defaultMergingOp (Intrinsic::ID IID=Intrinsic::not_intrinsic)
static SVEIntrinsicInfo defaultMergingUnaryOp ()
static SVEIntrinsicInfo defaultMergingUnaryNarrowingTopOp ()
static SVEIntrinsicInfo defaultUndefOp ()
static SVEIntrinsicInfo defaultVoidOp (unsigned GPIndex)
static SVEIntrinsicInfo defaultZeroingOp ()
Detailed Description
Definition at line 1133 of file AArch64TargetTransformInfo.cpp.
Member Function Documentation
defaultMergingOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultMergingOp (Intrinsic::ID IID = Intrinsic::not_intrinsic) inline static
Definition at line 1141 of file AArch64TargetTransformInfo.cpp.
References llvm::Intrinsic::not_intrinsic, setGoverningPredicateOperandIdx(), setMatchingUndefIntrinsic(), and setOperandIdxInactiveLanesTakenFrom().
Referenced by constructSVEIntrinsicInfo().
defaultMergingUnaryNarrowingTopOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultMergingUnaryNarrowingTopOp () inline static
Definition at line 1157 of file AArch64TargetTransformInfo.cpp.
References setGoverningPredicateOperandIdx(), and setOperandIdxInactiveLanesTakenFrom().
Referenced by constructSVEIntrinsicInfo().
defaultMergingUnaryOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultMergingUnaryOp () inline static
Definition at line 1149 of file AArch64TargetTransformInfo.cpp.
References setGoverningPredicateOperandIdx(), setOperandIdxInactiveLanesTakenFrom(), and setOperandIdxWithNoActiveLanes().
Referenced by constructSVEIntrinsicInfo().
defaultUndefOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultUndefOp () inline static
Definition at line 1164 of file AArch64TargetTransformInfo.cpp.
References setGoverningPredicateOperandIdx(), and setInactiveLanesAreNotDefined().
Referenced by constructSVEIntrinsicInfo().
defaultVoidOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultVoidOp (unsigned GPIndex) inline static
Definition at line 1172 of file AArch64TargetTransformInfo.cpp.
References setGoverningPredicateOperandIdx(), and setInactiveLanesAreUnused().
Referenced by constructSVEIntrinsicInfo().
defaultZeroingOp()
SVEIntrinsicInfo SVEIntrinsicInfo::defaultZeroingOp () inline static
Definition at line 1180 of file AArch64TargetTransformInfo.cpp.
References setGoverningPredicateOperandIdx(), setInactiveLanesAreUnused(), and setResultIsZeroInitialized().
Referenced by constructSVEIntrinsicInfo().
getGoverningPredicateOperandIdx()
unsigned SVEIntrinsicInfo::getGoverningPredicateOperandIdx () const inline
Definition at line 1199 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasGoverningPredicate().
Referenced by simplifySVEIntrinsic().
getMatchingIROpode()
unsigned SVEIntrinsicInfo::getMatchingIROpode () const inline
Definition at line 1235 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasMatchingIROpode().
Referenced by simplifySVEIntrinsic(), and simplifySVEIntrinsicBinOp().
getMatchingUndefIntrinsic()
Intrinsic::ID SVEIntrinsicInfo::getMatchingUndefIntrinsic () const inline
Definition at line 1222 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasMatchingUndefIntrinsic().
Referenced by simplifySVEIntrinsic().
getOperandIdxInactiveLanesTakenFrom()
unsigned SVEIntrinsicInfo::getOperandIdxInactiveLanesTakenFrom () const inline
Definition at line 1254 of file AArch64TargetTransformInfo.cpp.
References assert(), and inactiveLanesTakenFromOperand().
Referenced by simplifySVEIntrinsic(), and simplifySVEIntrinsicBinOp().
getOperandIdxWithNoActiveLanes()
unsigned SVEIntrinsicInfo::getOperandIdxWithNoActiveLanes () const inline
Definition at line 1306 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasOperandWithNoActiveLanes().
Referenced by simplifySVEIntrinsic().
hasGoverningPredicate()
bool SVEIntrinsicInfo::hasGoverningPredicate () const inline
Definition at line 1195 of file AArch64TargetTransformInfo.cpp.
Referenced by getGoverningPredicateOperandIdx(), operator bool(), setGoverningPredicateOperandIdx(), and simplifySVEIntrinsic().
hasMatchingIROpode()
bool SVEIntrinsicInfo::hasMatchingIROpode () const inline
Definition at line 1233 of file AArch64TargetTransformInfo.cpp.
Referenced by getMatchingIROpode(), setMatchingIROpcode(), and simplifySVEIntrinsic().
hasMatchingUndefIntrinsic()
bool SVEIntrinsicInfo::hasMatchingUndefIntrinsic () const inline
Definition at line 1218 of file AArch64TargetTransformInfo.cpp.
References llvm::Intrinsic::not_intrinsic.
Referenced by getMatchingUndefIntrinsic(), setMatchingUndefIntrinsic(), and simplifySVEIntrinsic().
hasOperandWithNoActiveLanes()
bool SVEIntrinsicInfo::hasOperandWithNoActiveLanes () const inline
Definition at line 1302 of file AArch64TargetTransformInfo.cpp.
Referenced by getOperandIdxWithNoActiveLanes(), setOperandIdxWithNoActiveLanes(), and simplifySVEIntrinsic().
inactiveLanesAreNotDefined()
bool SVEIntrinsicInfo::inactiveLanesAreNotDefined () const inline
Definition at line 1266 of file AArch64TargetTransformInfo.cpp.
Referenced by simplifySVEIntrinsicBinOp().
inactiveLanesAreUnused()
bool SVEIntrinsicInfo::inactiveLanesAreUnused () const inline
Definition at line 1276 of file AArch64TargetTransformInfo.cpp.
Referenced by simplifySVEIntrinsic().
inactiveLanesTakenFromOperand()
bool SVEIntrinsicInfo::inactiveLanesTakenFromOperand () const inline
Definition at line 1250 of file AArch64TargetTransformInfo.cpp.
Referenced by getOperandIdxInactiveLanesTakenFrom(), and simplifySVEIntrinsic().
operator bool()
SVEIntrinsicInfo::operator bool () const inline explicit
Definition at line 1189 of file AArch64TargetTransformInfo.cpp.
References hasGoverningPredicate().
resultIsZeroInitialized()
bool SVEIntrinsicInfo::resultIsZeroInitialized () const inline
Definition at line 1289 of file AArch64TargetTransformInfo.cpp.
Referenced by simplifySVEIntrinsic().
setGoverningPredicateOperandIdx()
SVEIntrinsicInfo & SVEIntrinsicInfo::setGoverningPredicateOperandIdx (unsigned Index) inline
Definition at line 1204 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasGoverningPredicate().
Referenced by defaultMergingOp(), defaultMergingUnaryNarrowingTopOp(), defaultMergingUnaryOp(), defaultUndefOp(), defaultVoidOp(), and defaultZeroingOp().
setInactiveLanesAreNotDefined()
SVEIntrinsicInfo & SVEIntrinsicInfo::setInactiveLanesAreNotDefined () inline
Definition at line 1270 of file AArch64TargetTransformInfo.cpp.
References assert().
Referenced by defaultUndefOp().
setInactiveLanesAreUnused()
SVEIntrinsicInfo & SVEIntrinsicInfo::setInactiveLanesAreUnused () inline
Definition at line 1280 of file AArch64TargetTransformInfo.cpp.
References assert().
Referenced by defaultVoidOp(), and defaultZeroingOp().
setMatchingIROpcode()
SVEIntrinsicInfo & SVEIntrinsicInfo::setMatchingIROpcode (unsigned Opcode) inline
Definition at line 1240 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasMatchingIROpode().
Referenced by constructSVEIntrinsicInfo().
setMatchingUndefIntrinsic()
SVEIntrinsicInfo & SVEIntrinsicInfo::setMatchingUndefIntrinsic (Intrinsic::ID IID) inline
Definition at line 1227 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasMatchingUndefIntrinsic().
Referenced by defaultMergingOp().
setOperandIdxInactiveLanesTakenFrom()
SVEIntrinsicInfo & SVEIntrinsicInfo::setOperandIdxInactiveLanesTakenFrom (unsigned Index) inline
Definition at line 1259 of file AArch64TargetTransformInfo.cpp.
References assert().
Referenced by defaultMergingOp(), defaultMergingUnaryNarrowingTopOp(), and defaultMergingUnaryOp().
setOperandIdxWithNoActiveLanes()
SVEIntrinsicInfo & SVEIntrinsicInfo::setOperandIdxWithNoActiveLanes (unsigned Index) inline
Definition at line 1311 of file AArch64TargetTransformInfo.cpp.
References assert(), and hasOperandWithNoActiveLanes().
Referenced by defaultMergingUnaryOp().
setResultIsZeroInitialized()
SVEIntrinsicInfo & SVEIntrinsicInfo::setResultIsZeroInitialized () inline
Definition at line 1291 of file AArch64TargetTransformInfo.cpp.
Referenced by defaultZeroingOp().
The documentation for this struct was generated from the following file:
lib/Target/AArch64/AArch64TargetTransformInfo.cpp