LLVM: llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex > Struct Reference
llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex > Struct Reference
#include "Target/CSKY/MCTargetDesc/CSKYTargetStreamer.h"
Static Public Member Functions
static CSKYTargetStreamer::SymbolIndex getEmptyKey ()
static CSKYTargetStreamer::SymbolIndex getTombstoneKey ()
static unsigned getHashValue (const CSKYTargetStreamer::SymbolIndex &V)
static bool isEqual (const CSKYTargetStreamer::SymbolIndex &A, const CSKYTargetStreamer::SymbolIndex &B)
Detailed Description
Definition at line 77 of file CSKYTargetStreamer.h.
Member Function Documentation
getEmptyKey()
CSKYTargetStreamer::SymbolIndex llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::getEmptyKey () inline static
Definition at line 78 of file CSKYTargetStreamer.h.
References llvm::CSKY::S_Invalid.
getHashValue()
unsigned llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::getHashValue (const CSKYTargetStreamer::SymbolIndex & V) inline static
Definition at line 84 of file CSKYTargetStreamer.h.
References llvm::hash_combine().
getTombstoneKey()
CSKYTargetStreamer::SymbolIndex llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::getTombstoneKey () inline static
Definition at line 81 of file CSKYTargetStreamer.h.
References llvm::CSKY::S_Invalid.
isEqual()
bool llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::isEqual (const CSKYTargetStreamer::SymbolIndex & A, const CSKYTargetStreamer::SymbolIndex & B) inline static
Definition at line 88 of file CSKYTargetStreamer.h.
References A(), and B().
The documentation for this struct was generated from the following file:
lib/Target/CSKY/MCTargetDesc/CSKYTargetStreamer.h