LLVM: llvm::cl::OptionValue< DataType > Struct Template Reference
llvm::cl::OptionValue< DataType > Struct Template Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
OptionValue ()=default
OptionValue (const DataType &V)
template<class DT>
OptionValue< DataType > & operator= (const DT &V)
Public Member Functions inherited from llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >
bool hasValue () const
const DataType & getValue () const
void setValue (const DT &)
bool compare (const DataType &) const
Public Member Functions inherited from llvm::cl::GenericOptionValue
virtual bool compare (const GenericOptionValue &V) const =0
Additional Inherited Members
Public Types inherited from llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >
using WrapperType
Protected Member Functions inherited from llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >
~OptionValueBase ()=default
Protected Member Functions inherited from llvm::cl::GenericOptionValue
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Detailed Description
template<class DataType>
struct llvm::cl::OptionValue< DataType >
Definition at line 624 of file CommandLine.h.
Constructor & Destructor Documentation
OptionValue() [1/2]
template<class DataType> llvm::cl::OptionValue< DataType >::OptionValue () default
Referenced by operator=().
OptionValue() [2/2]
template<class DataType> llvm::cl::OptionValue< DataType >::OptionValue (const DataType & V) inline
Definition at line 628 of file CommandLine.h.
References llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >::setValue().
Member Function Documentation
operator=()
template<class DataType> template<class DT> OptionValue< DataType > & llvm::cl::OptionValue< DataType >::operator= (const DT & V) inline
Definition at line 631 of file CommandLine.h.
References OptionValue(), and llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >::setValue().
The documentation for this struct was generated from the following file:
include/llvm/Support/CommandLine.h