LLVM: llvm::ms_demangle::QualifiedNameNode Struct Reference
llvm::ms_demangle::QualifiedNameNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
QualifiedNameNode ()
void output (OutputBuffer &OB, OutputFlags Flags) const override
IdentifierNode * getUnqualifiedIdentifier ()
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
DEMANGLE_ABI std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Public Attributes
NodeArrayNode * Components = nullptr
Detailed Description
Definition at line 623 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
QualifiedNameNode()
llvm::ms_demangle::QualifiedNameNode::QualifiedNameNode () inline
Definition at line 624 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::Node::Node().
Member Function Documentation
classof()
bool llvm::ms_demangle::QualifiedNameNode::classof (const Node * N) inline static
Definition at line 628 of file MicrosoftDemangleNodes.h.
References N, llvm::ms_demangle::Node::Node(), and llvm::ms_demangle::QualifiedName.
getUnqualifiedIdentifier()
IdentifierNode * llvm::ms_demangle::QualifiedNameNode::getUnqualifiedIdentifier () inline
Definition at line 634 of file MicrosoftDemangleNodes.h.
References Components, and llvm::ms_demangle::Node::Node().
output()
void QualifiedNameNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Definition at line 640 of file MicrosoftDemangleNodes.cpp.
References Components.
Member Data Documentation
Components
NodeArrayNode* llvm::ms_demangle::QualifiedNameNode::Components = nullptr
Definition at line 632 of file MicrosoftDemangleNodes.h.
Referenced by getUnqualifiedIdentifier(), output(), and synthesizeQualifiedName().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp