LLVM: llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable > Struct Template Reference
llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
SpecificCmpClass_match (CmpPredicate Pred, const LHS_t &LHS, const RHS_t &RHS)
template<typename OpTy>
bool match (OpTy *V) const
Public Attributes
const CmpPredicate Predicate
LHS_t L
RHS_t R
Detailed Description
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false>
struct llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >
Definition at line 1810 of file PatternMatch.h.
Constructor & Destructor Documentation
SpecificCmpClass_match()
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false> llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::SpecificCmpClass_match (CmpPredicate Pred, const LHS_t & LHS, const RHS_t & RHS) inline
Definition at line 1815 of file PatternMatch.h.
References L, LHS, Predicate, R, and RHS.
Member Function Documentation
match()
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false> template<typename OpTy> bool llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::match (OpTy * V) const inline
Definition at line 1818 of file PatternMatch.h.
References llvm::dyn_cast(), llvm::CmpPredicate::get(), llvm::CmpPredicate::getMatching(), llvm::CmpPredicate::getSwapped(), I, L, Predicate, and R.
Member Data Documentation
L
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false> LHS_t llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::L
Definition at line 1812 of file PatternMatch.h.
Referenced by match(), and SpecificCmpClass_match().
Predicate
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false> const CmpPredicate llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::Predicate
Definition at line 1811 of file PatternMatch.h.
Referenced by match(), and SpecificCmpClass_match().
R
template<typename LHS_t, typename RHS_t, typename Class, bool Commutable = false> RHS_t llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::R
Definition at line 1813 of file PatternMatch.h.
Referenced by match(), and SpecificCmpClass_match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h