LLVM: llvm::mcdxbc::RootSignatureDesc Struct Reference
llvm::mcdxbc::RootSignatureDesc Struct Reference
#include "llvm/MC/DXContainerRootSignature.h"
Public Member Functions
LLVM_ABI void write (raw_ostream &OS) const
LLVM_ABI size_t getSize () const
LLVM_ABI uint32_t computeRootParametersOffset () const
LLVM_ABI uint32_t computeStaticSamplersOffset () const
Public Attributes
uint32_t Version = 2U
uint32_t Flags = 0U
uint32_t RootParameterOffset = 0U
uint32_t StaticSamplersOffset = 0u
uint32_t NumStaticSamplers = 0u
mcdxbc::RootParametersContainer ParametersContainer
SmallVector< StaticSampler > StaticSamplers
Detailed Description
Definition at line 138 of file DXContainerRootSignature.h.
Member Function Documentation
computeRootParametersOffset()
uint32_t RootSignatureDesc::computeRootParametersOffset () const
Definition at line 42 of file DXContainerRootSignature.cpp.
Referenced by computeStaticSamplersOffset().
computeStaticSamplersOffset()
uint32_t RootSignatureDesc::computeStaticSamplersOffset () const
Definition at line 46 of file DXContainerRootSignature.cpp.
References computeRootParametersOffset(), I, llvm::Offset, ParametersContainer, llvm::mcdxbc::DescriptorTable::Ranges, and Version.
Referenced by getSize(), and write().
getSize()
size_t RootSignatureDesc::getSize () const
Definition at line 32 of file DXContainerRootSignature.cpp.
References computeStaticSamplersOffset(), StaticSamplers, StaticSamplersOffset, and Version.
Referenced by write().
write()
void RootSignatureDesc::write (raw_ostream & OS) const
Definition at line 82 of file DXContainerRootSignature.cpp.
References assert(), computeStaticSamplersOffset(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::mcdxbc::RootDescriptor::Flags, Flags, getSize(), I, llvm::little, llvm::Offset, ParametersContainer, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Range, llvm::mcdxbc::DescriptorTable::Ranges, llvm::mcdxbc::RootDescriptor::RegisterSpace, llvm::raw_svector_ostream::reserveExtraSpace(), rewriteOffsetToCurrentByte(), RootParameterOffset, llvm::mcdxbc::RootDescriptor::ShaderRegister, llvm::SmallVectorTemplateCommon< T, typename >::size(), StaticSamplers, Version, llvm::raw_ostream::write(), llvm::support::endian::write(), and writePlaceholder().
Member Data Documentation
Flags
uint32_t llvm::mcdxbc::RootSignatureDesc::Flags = 0U
Definition at line 141 of file DXContainerRootSignature.h.
Referenced by validateRootSignature(), and write().
NumStaticSamplers
uint32_t llvm::mcdxbc::RootSignatureDesc::NumStaticSamplers = 0u
Definition at line 144 of file DXContainerRootSignature.h.
ParametersContainer
mcdxbc::RootParametersContainer llvm::mcdxbc::RootSignatureDesc::ParametersContainer
Definition at line 145 of file DXContainerRootSignature.h.
Referenced by computeStaticSamplersOffset(), validateRootSignature(), and write().
RootParameterOffset
uint32_t llvm::mcdxbc::RootSignatureDesc::RootParameterOffset = 0U
Definition at line 142 of file DXContainerRootSignature.h.
Referenced by write().
StaticSamplers
SmallVector<StaticSampler> llvm::mcdxbc::RootSignatureDesc::StaticSamplers
Definition at line 146 of file DXContainerRootSignature.h.
Referenced by getSize(), validateRootSignature(), and write().
StaticSamplersOffset
uint32_t llvm::mcdxbc::RootSignatureDesc::StaticSamplersOffset = 0u
Definition at line 143 of file DXContainerRootSignature.h.
Referenced by getSize().
Version
uint32_t llvm::mcdxbc::RootSignatureDesc::Version = 2U
Definition at line 140 of file DXContainerRootSignature.h.
Referenced by computeStaticSamplersOffset(), getSize(), llvm::hlsl::rootsig::MetadataParser::ParseRootSignature(), and write().
The documentation for this struct was generated from the following files:
include/llvm/MC/DXContainerRootSignature.h
lib/MC/DXContainerRootSignature.cpp