LLVM: lib/Target/SystemZ/SystemZISelLowering.cpp File Reference
SystemZISelLowering.cpp File Reference
#include "SystemZISelLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZConstantPoolValue.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZTargetMachine.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include <cctype>
#include <optional>
#include "SystemZGenCallingConv.inc"
Classes
struct AddressingMode
Macros
#define DEBUG_TYPE "systemz-lower"
#define CONV(X)
Enumerations
enum class CmpMode { Int , FP , StrictFP , SignalingFP }
Functions
static bool is32Bit (EVT VT)
static MachineOperand earlyUseOperand (MachineOperand Op)
static AddressingMode getLoadStoreAddrMode (bool HasVector, Type *Ty)
static AddressingMode supportedAddressingMode (Instruction *I, bool HasVector)
static std::pair< unsigned, const TargetRegisterClass * > parseRegisterNumber (StringRef Constraint, const TargetRegisterClass *RC, const unsigned *Map, unsigned Size)
static SDValue getCCResult (SelectionDAG &DAG, SDValue CCReg)
static SDValue convertLocVTToValVT (SelectionDAG &DAG, const SDLoc &DL, CCValAssign &VA, SDValue Chain, SDValue Value)
static SDValue convertValVTToLocVT (SelectionDAG &DAG, const SDLoc &DL, CCValAssign &VA, SDValue Value)
static SDValue lowerI128ToGR128 (SelectionDAG &DAG, SDValue In)
static SDValue lowerGR128ToI128 (SelectionDAG &DAG, SDValue In)
template<class ArgTy>
static bool analyzeArgSplit (const SmallVectorImpl< ArgTy > &Args, SmallVector< CCValAssign, 16 > &ArgLocs, unsigned I, MVT &PartVT, unsigned &NumParts)
static bool canUseSiblingCall (const CCState &ArgCCInfo, SmallVectorImpl< CCValAssign > &ArgLocs, SmallVectorImpl< ISD::OutputArg > &Outs)
static SDValue getADAEntry (SelectionDAG &DAG, SDValue Val, SDLoc DL, unsigned Offset, bool LoadAdr=false)
static SDValue getADAEntry (SelectionDAG &DAG, const GlobalValue *GV, SDLoc DL, EVT PtrVT)
static bool getzOSCalleeAndADA (SelectionDAG &DAG, SDValue &Callee, SDValue &ADA, SDLoc &DL, SDValue &Chain)
static bool isIntrinsicWithCCAndChain (SDValue Op, unsigned &Opcode, unsigned &CCValid)
static bool isIntrinsicWithCC (SDValue Op, unsigned &Opcode, unsigned &CCValid)
static SDNode * emitIntrinsicWithCCAndChain (SelectionDAG &DAG, SDValue Op, unsigned Opcode)
static SDNode * emitIntrinsicWithCC (SelectionDAG &DAG, SDValue Op, unsigned Opcode)
static unsigned CCMaskForCondCode (ISD::CondCode CC)
static void adjustZeroCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustSubwordCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType)
static bool shouldSwapCmpOperands (const Comparison &C)
static void adjustForSubtraction (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustForFNeg (Comparison &C)
static void adjustForLTGFR (Comparison &C)
static void adjustICmpTruncate (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static bool isSimpleShift (SDValue N, unsigned &ShiftVal)
static unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType)
static void adjustForTestUnderMask (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustICmp128 (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustForRedundantAnd (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static Comparison getIntrinsicCmp (SelectionDAG &DAG, unsigned Opcode, SDValue Call, unsigned CCValid, uint64_t CC, ISD::CondCode Cond)
static Comparison getCmp (SelectionDAG &DAG, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, const SDLoc &DL, SDValue Chain=SDValue(), bool IsSignaling=false)
static SDValue emitCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void lowerMUL_LOHI32 (SelectionDAG &DAG, const SDLoc &DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue &Hi, SDValue &Lo)
static void lowerGR128Binary (SelectionDAG &DAG, const SDLoc &DL, EVT VT, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue &Even, SDValue &Odd)
static SDValue emitSETCC (SelectionDAG &DAG, const SDLoc &DL, SDValue CCReg, unsigned CCValid, unsigned CCMask)
static unsigned getVectorComparison (ISD::CondCode CC, CmpMode Mode)
static unsigned getVectorComparisonOrInvert (ISD::CondCode CC, CmpMode Mode, bool &Invert)
static SDValue expandV4F32ToV2F64 (SelectionDAG &DAG, int Start, const SDLoc &DL, SDValue Op, SDValue Chain)
static bool isAbsolute (SDValue CmpOp, SDValue Pos, SDValue Neg)
static SDValue getAbsolute (SelectionDAG &DAG, const SDLoc &DL, SDValue Op, bool IsNegative)
static SDValue getI128Select (SelectionDAG &DAG, const SDLoc &DL, Comparison C, SDValue TrueOp, SDValue FalseOp)
static bool isAddCarryChain (SDValue Carry)
static bool isSubBorrowChain (SDValue Carry)
static void getCSAddressAndShifts (SDValue Addr, SelectionDAG &DAG, SDLoc DL, SDValue &AlignedAddr, SDValue &BitShift, SDValue &NegBitShift)
static bool chooseShuffleOpNos (int *OpNos, unsigned &OpNo0, unsigned &OpNo1)
static bool matchPermute (const SmallVectorImpl< int > &Bytes, const Permute &P, unsigned &OpNo0, unsigned &OpNo1)
static const Permute * matchPermute (const SmallVectorImpl< int > &Bytes, unsigned &OpNo0, unsigned &OpNo1)
static bool matchDoublePermute (const SmallVectorImpl< int > &Bytes, const Permute &P, SmallVectorImpl< int > &Transform)
static const Permute * matchDoublePermute (const SmallVectorImpl< int > &Bytes, SmallVectorImpl< int > &Transform)
static bool getVPermMask (SDValue ShuffleOp, SmallVectorImpl< int > &Bytes)
static bool getShuffleInput (const SmallVectorImpl< int > &Bytes, unsigned Start, unsigned BytesPerElement, int &Base)
static bool isShlDoublePermute (const SmallVectorImpl< int > &Bytes, unsigned &StartIndex, unsigned &OpNo0, unsigned &OpNo1)
static SDValue getPermuteNode (SelectionDAG &DAG, const SDLoc &DL, const Permute &P, SDValue Op0, SDValue Op1)
static bool isZeroVector (SDValue N)
static uint32_t findZeroVectorIdx (SDValue *Ops, unsigned Num)
static SDValue getGeneralPermuteNode (SelectionDAG &DAG, const SDLoc &DL, SDValue *Ops, const SmallVectorImpl< int > &Bytes)
static void dumpBytes (const SmallVectorImpl< int > &Bytes, std::string Msg)
static bool isScalarToVector (SDValue Op)
static SDValue buildScalarToVector (SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Value)
static SDValue buildMergeScalars (SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Op0, SDValue Op1)
static SDValue joinDwords (SelectionDAG &DAG, const SDLoc &DL, SDValue Op0, SDValue Op1)
static SDValue tryBuildVectorShuffle (SelectionDAG &DAG, BuildVectorSDNode *BVN)
static SDValue mergeHighParts (SelectionDAG &DAG, const SDLoc &DL, unsigned MergedBits, EVT VT, SDValue Op0, SDValue Op1)
static SDValue buildFPVecFromScalars4 (SelectionDAG &DAG, const SDLoc &DL, EVT VT, SmallVectorImpl< SDValue > &Elems, unsigned Pos)
static SDValue convertToF16 (SDValue Op, SelectionDAG &DAG)
static SDValue convertFromF16 (SDValue Op, SDLoc DL, SelectionDAG &DAG)
static SDValue lowerAddrSpaceCast (SDValue Op, SelectionDAG &DAG)
static SDValue expandBitCastI128ToF128 (SelectionDAG &DAG, SDValue Src, const SDLoc &SL)
static SDValue expandBitCastF128ToI128 (SelectionDAG &DAG, SDValue Src, const SDLoc &SL)
static bool isI128MovedToParts (LoadSDNode *LD, SDNode *&LoPart, SDNode *&HiPart)
static bool isF128MovedToParts (LoadSDNode *LD, SDNode *&LoPart, SDNode *&HiPart)
static bool isVectorElementSwap (ArrayRef< int > M, EVT VT)
static bool isOnlyUsedByStores (SDValue StoredVal, SelectionDAG &DAG)
static bool isI128MovedFromParts (SDValue Val, SDValue &LoPart, SDValue &HiPart)
static bool isF128MovedFromParts (SDValue Val, SDValue &LoPart, SDValue &HiPart)
static SDValue MergeInputChains (SDNode *N1, SDNode *N2)
static std::pair< SDValue, int > findCCUse (const SDValue &Val)
static bool combineCCMask (SDValue &CCReg, int &CCValid, int &CCMask, SelectionDAG &DAG)
static SmallVector< SDValue, 4 > simplifyAssumingCCVal (SDValue &Val, SDValue &CC, SelectionDAG &DAG)
static unsigned detectEvenOddMultiplyOperand (const SelectionDAG &DAG, const SystemZSubtarget &Subtarget, SDValue &Op)
static APInt getDemandedSrcElements (SDValue Op, const APInt &DemandedElts, unsigned OpNo)
static void computeKnownBitsBinOp (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth, unsigned OpNo)
static unsigned computeNumSignBitsBinOp (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth, unsigned OpNo)
static Register forceReg (MachineInstr &MI, MachineOperand &Base, const SystemZInstrInfo *TII)
static bool checkCCKill (MachineInstr &MI, MachineBasicBlock *MBB)
static bool isSelectPseudo (MachineInstr &MI)
static void createPHIsForSelects (SmallVector< MachineInstr *, 8 > &Selects, MachineBasicBlock *TrueMBB, MachineBasicBlock *FalseMBB, MachineBasicBlock *SinkMBB)
static void printFunctionArgExts (const Function *F, raw_fd_ostream &OS)
Variables
static cl::opt< bool > EnableIntArgExtCheck ("argext-abi-check", cl::init(false), cl::desc("Verify that narrow int args are properly extended per the " "SystemZ ABI."))
static const Permute PermuteForms []
Macro Definition Documentation
CONV
#define CONV (X)
Value:
case ISD::SET##X: return SystemZ::CCMASK_CMP_##X; \
case ISD::SETO##X: return SystemZ::CCMASK_CMP_##X; \
case ISD::SETU##X: return SystemZ::CCMASK_CMP_UO | SystemZ::CCMASK_CMP_##X
Referenced by CCMaskForCondCode().
DEBUG_TYPE
#define DEBUG_TYPE "systemz-lower"
Definition at line 37 of file SystemZISelLowering.cpp.
Enumeration Type Documentation
CmpMode
enum class CmpMode strong
Enumerator
Int
FP
StrictFP
SignalingFP
Definition at line 3698 of file SystemZISelLowering.cpp.
Function Documentation
adjustForFNeg()
void adjustForFNeg (Comparison & C) static
Definition at line 3122 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::ISD::FNEG, N, and llvm::SystemZ::reverseCCMask().
Referenced by getCmp().
adjustForLTGFR()
void adjustForLTGFR (Comparison & C) static
Definition at line 3145 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::ISD::Constant, llvm::dyn_cast(), N, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, and llvm::SDNode::users().
Referenced by getCmp().
adjustForRedundantAnd()
void adjustForRedundantAnd (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3495 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::CallingConv::C, llvm::SelectionDAG::computeKnownBits(), DL, llvm::dyn_cast(), and llvm::KnownBits::Zero.
Referenced by getCmp().
adjustForSubtraction()
void adjustForSubtraction (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3099 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_NE, DL, llvm::SelectionDAG::getConstant(), N, llvm::SDNodeFlags::NoWrap, and llvm::ISD::SUB.
Referenced by getCmp().
adjustForTestUnderMask()
void adjustForTestUnderMask (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3299 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::SystemZICMP::Any, llvm::ISD::BITCAST, llvm::CallingConv::C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_TM, llvm::SystemZ::CCMASK_VCMP, llvm::SystemZ::CCMASK_VCMP_ALL, DL, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getTestUnderMaskCond(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), isSimpleShift(), llvm::ISD::SHL, llvm::SystemZICMP::SignedOnly, llvm::ISD::SRL, and llvm::SystemZICMP::UnsignedOnly.
Referenced by getCmp().
adjustICmp128()
void adjustICmp128 (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3409 of file SystemZISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::CallingConv::C, llvm::SystemZ::CCMASK_1, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_VCMP, llvm::SystemZ::CCMASK_VCMP_ALL, llvm::SystemZ::CCMASK_VCMP_NONE, DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSubtarget(), llvm::isAllOnesConstant(), llvm::isBitwiseNot(), llvm::isNullConstant(), llvm_unreachable, llvm::peekThroughBitcasts(), std::swap(), and llvm::SystemZICMP::UnsignedOnly.
Referenced by getCmp().
adjustICmpTruncate()
void adjustICmpTruncate (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3167 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::ISD::Constant, DL, llvm::SelectionDAG::getConstant(), llvm::ISD::LOAD, llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::ISD::TRUNCATE, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
Referenced by getCmp().
adjustSubwordCmp()
void adjustSubwordCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2940 of file SystemZISelLowering.cpp.
References llvm::SystemZICMP::Any, llvm::CallingConv::C, llvm::cast(), llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::ISD::Constant, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getExtLoad(), llvm::ISD::LOAD, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
Referenced by getCmp().
adjustZeroCmp()
void adjustZeroCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2920 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, DL, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), and llvm::SystemZICMP::UnsignedOnly.
Referenced by getCmp().
analyzeArgSplit()
template<class ArgTy> bool analyzeArgSplit (const SmallVectorImpl< ArgTy > & Args, SmallVector< CCValAssign, 16 > & ArgLocs, unsigned I, MVT & PartVT, unsigned & NumParts) static
Definition at line 2015 of file SystemZISelLowering.cpp.
References assert(), I, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerFormalArguments().
buildFPVecFromScalars4()
SDValue buildFPVecFromScalars4 (SelectionDAG & DAG, const SDLoc & DL, EVT VT, SmallVectorImpl< SDValue > & Elems, unsigned Pos) static
Definition at line 6400 of file SystemZISelLowering.cpp.
References buildMergeScalars(), DL, llvm::SDValue::getOpcode(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getSimpleVT(), llvm::SDValue::isUndef(), and mergeHighParts().
buildMergeScalars()
SDValue buildMergeScalars (SelectionDAG & DAG, const SDLoc & DL, EVT VT, SDValue Op0, SDValue Op1) static
Definition at line 6290 of file SystemZISelLowering.cpp.
References buildScalarToVector(), DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::isUndef(), and Op0.
Referenced by buildFPVecFromScalars4().
buildScalarToVector()
SDValue buildScalarToVector (SelectionDAG & DAG, const SDLoc & DL, EVT VT, SDValue Value) static
Definition at line 6274 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::Constant, llvm::ISD::ConstantFP, DL, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::EVT::getVectorNumElements(), and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by buildMergeScalars().
canUseSiblingCall()
bool canUseSiblingCall (const CCState & ArgCCInfo, SmallVectorImpl< CCValAssign > & ArgLocs, SmallVectorImpl< ISD::OutputArg > & Outs) static
Definition at line 2226 of file SystemZISelLowering.cpp.
References E(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), I, llvm::CCValAssign::Indirect, llvm::CCValAssign::isRegLoc(), Reg, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::SystemZTargetLowering::LowerCall().
CCMaskForCondCode()
unsigned CCMaskForCondCode (ISD::CondCode CC) static
Definition at line 2895 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_O, llvm::SystemZ::CCMASK_CMP_UO, CONV, EQ, llvm_unreachable, llvm::ISD::SETO, and llvm::ISD::SETUO.
Referenced by getCmp().
checkCCKill()
bool checkCCKill (MachineInstr & MI, MachineBasicBlock * MBB) static
Definition at line 9742 of file SystemZISelLowering.cpp.
References MBB, and MI.
chooseShuffleOpNos()
bool chooseShuffleOpNos (int * OpNos, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 5666 of file SystemZISelLowering.cpp.
Referenced by isShlDoublePermute(), and matchPermute().
combineCCMask()
bool combineCCMask (SDValue & CCReg, int & CCValid, int & CCMask, SelectionDAG & DAG) static
Definition at line 8819 of file SystemZISelLowering.cpp.
References llvm::AllOnes, llvm::SystemZ::CCMASK_ICMP, llvm::SystemZ::CCMASK_TM, llvm::dyn_cast(), findCCUse(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), Op0, llvm::SystemZICMP::SignedOnly, and simplifyAssumingCCVal().
Referenced by simplifyAssumingCCVal().
computeKnownBitsBinOp()
void computeKnownBitsBinOp (const SDValue Op, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth, unsigned OpNo) static
Definition at line 9498 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits(), llvm::Depth, getDemandedSrcElements(), and llvm::KnownBits::intersectWith().
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode().
computeNumSignBitsBinOp()
unsigned computeNumSignBitsBinOp (SDValue Op, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth, unsigned OpNo) static
Definition at line 9606 of file SystemZISelLowering.cpp.
References assert(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::Depth, getDemandedSrcElements(), llvm::EVT::getScalarSizeInBits(), LHS, and RHS.
Referenced by llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode().
convertFromF16()
SDValue convertFromF16 (SDValue Op, SDLoc DL, SelectionDAG & DAG) static
Definition at line 6651 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetInsertSubreg(), and llvm::ISD::SRL.
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
convertLocVTToValVT()
SDValue convertLocVTToValVT (SelectionDAG & DAG, const SDLoc & DL, CCValAssign & VA, SDValue Chain, SDValue Value) static
Definition at line 1886 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, DL, llvm::CCValAssign::Full, llvm::SelectionDAG::getBuildVector(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::CCValAssign::isExtInLoc(), llvm::MVT::isVector(), llvm::CCValAssign::SExt, llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
convertToF16()
SDValue convertToF16 (SDValue Op, SelectionDAG & DAG) static
Definition at line 6638 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), and llvm::ISD::SHL.
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
convertValVTToLocVT()
SDValue convertValVTToLocVT (SelectionDAG & DAG, const SDLoc & DL, CCValAssign & VA, SDValue Value) static
Definition at line 1915 of file SystemZISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, assert(), llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FP_EXTEND, llvm::CCValAssign::Full, llvm::SelectionDAG::getConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::CCValAssign::getValVT(), llvm::MVT::isVector(), llvm_unreachable, llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
createPHIsForSelects()
void createPHIsForSelects (SmallVector< MachineInstr *, 8 > & Selects, MachineBasicBlock * TrueMBB, MachineBasicBlock * FalseMBB, MachineBasicBlock * SinkMBB) static
Definition at line 9788 of file SystemZISelLowering.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), DL, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getSubtarget(), MI, std::swap(), and TII.
detectEvenOddMultiplyOperand()
unsigned detectEvenOddMultiplyOperand (const SelectionDAG & DAG, const SystemZSubtarget & Subtarget, SDValue & Op) static
Definition at line 9254 of file SystemZISelLowering.cpp.
References llvm::cast(), llvm::ISD::Constant, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::EVT::getVectorNumElements(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
dumpBytes()
void dumpBytes (const SmallVectorImpl< int > & Bytes, std::string Msg) static
Definition at line 6148 of file SystemZISelLowering.cpp.
References llvm::dbgs(), I, and llvm::SmallVectorTemplateCommon< T, typename >::size().
earlyUseOperand()
MachineOperand earlyUseOperand (MachineOperand Op) static
Definition at line 87 of file SystemZISelLowering.cpp.
emitCmp()
SDValue emitCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 3612 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::SystemZ::CCMASK_TM_MIXED_MSB_0, llvm::SystemZ::CCMASK_TM_MIXED_MSB_1, DL, emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, and llvm_unreachable.
emitIntrinsicWithCC()
SDNode * emitIntrinsicWithCC (SelectionDAG & DAG, SDValue Op, unsigned Opcode) static
Definition at line 2869 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, assert(), DL, llvm::SelectionDAG::getFPExtendOrRound(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and I.
Referenced by emitCmp().
emitIntrinsicWithCCAndChain()
SDNode * emitIntrinsicWithCCAndChain (SelectionDAG & DAG, SDValue Op, unsigned Opcode) static
Definition at line 2849 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVTList(), I, and llvm::SelectionDAG::ReplaceAllUsesOfValueWith().
Referenced by emitCmp().
emitSETCC()
SDValue emitSETCC (SelectionDAG & DAG, const SDLoc & DL, SDValue CCReg, unsigned CCValid, unsigned CCMask) static
Definition at line 3684 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), and llvm::SelectionDAG::getTargetConstant().
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
expandBitCastF128ToI128()
SDValue expandBitCastF128ToI128 (SelectionDAG & DAG, SDValue Src, const SDLoc & SL) static
Definition at line 7350 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getRepRegClassFor(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Hi, llvm::TargetLoweringBase::isTypeLegal(), and llvm::Lo.
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
expandBitCastI128ToF128()
SDValue expandBitCastI128ToF128 (SelectionDAG & DAG, SDValue Src, const SDLoc & SL) static
Definition at line 7326 of file SystemZISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getMachineNode(), llvm::TargetLoweringBase::getRepRegClassFor(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Hi, llvm::TargetLoweringBase::isTypeLegal(), llvm::Lo, and llvm::SelectionDAG::SplitScalar().
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
expandV4F32ToV2F64()
SDValue expandV4F32ToV2F64 (SelectionDAG & DAG, int Start, const SDLoc & DL, SDValue Op, SDValue Chain) static
Definition at line 3766 of file SystemZISelLowering.cpp.
References DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), and llvm::SelectionDAG::getVTList().
findCCUse()
std::pair< SDValue, int > findCCUse (const SDValue & Val) static
Definition at line 8708 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_ICMP, llvm::SystemZ::CCMASK_NONE, llvm::dyn_cast(), findCCUse(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::OR, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::XOR.
Referenced by combineCCMask(), and findCCUse().
findZeroVectorIdx()
uint32_t findZeroVectorIdx (SDValue * Ops, unsigned Num) static
Definition at line 5877 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, I, and isZeroVector().
Referenced by getGeneralPermuteNode().
forceReg()
Register forceReg (MachineInstr & MI, MachineOperand & Base, const SystemZInstrInfo * TII) static
Definition at line 9716 of file SystemZISelLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::sampleprof::Base, llvm::BuildMI(), llvm::MachineFunction::getRegInfo(), MBB, MI, MRI, Reg, and TII.
getAbsolute()
SDValue getAbsolute (SelectionDAG & DAG, const SDLoc & DL, SDValue Op, bool IsNegative) static
Definition at line 3974 of file SystemZISelLowering.cpp.
References llvm::ISD::ABS, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), and llvm::ISD::SUB.
getADAEntry() [1/2]
SDValue getADAEntry (SelectionDAG & DAG, const GlobalValue * GV, SDLoc DL, EVT PtrVT) static
Definition at line 2268 of file SystemZISelLowering.cpp.
References DL, llvm::dyn_cast(), getADAEntry(), llvm::GlobalAlias::getAliaseeObject(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::GlobalValue::hasInternalLinkage(), llvm::GlobalValue::hasPrivateLinkage(), llvm::isa(), llvm::SystemZII::MO_ADA_DATA_SYMBOL_ADDR, llvm::SystemZII::MO_ADA_DIRECT_FUNC_DESC, and llvm::SystemZII::MO_ADA_INDIRECT_FUNC_DESC.
getADAEntry() [2/2]
SDValue getADAEntry (SelectionDAG & DAG, SDValue Val, SDLoc DL, unsigned Offset, bool LoadAdr = false) static
Definition at line 2247 of file SystemZISelLowering.cpp.
References DL, llvm::SystemZMachineFunctionInfo::getADAVirtualRegister(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, llvm::Offset, and Reg.
Referenced by getADAEntry(), and getzOSCalleeAndADA().
getCCResult()
SDValue getCCResult (SelectionDAG & DAG, SDValue CCReg) static
Definition at line 1789 of file SystemZISelLowering.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SystemZ::IPM_CC, and llvm::ISD::SRL.
Referenced by llvm::SystemZTargetLowering::LowerAsmOutputForConstraint().
getCmp()
Comparison getCmp (SelectionDAG & DAG, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, const SDLoc & DL, SDValue Chain = SDValue(), bool IsSignaling = false) static
Definition at line 3546 of file SystemZISelLowering.cpp.
References adjustForFNeg(), adjustForLTGFR(), adjustForRedundantAnd(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmp128(), adjustICmpTruncate(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SystemZICMP::Any, assert(), llvm::CallingConv::C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_CMP_UO, llvm::SystemZ::CCMASK_FCMP, llvm::SystemZ::CCMASK_ICMP, CCMaskForCondCode(), Cond, llvm::ISD::Constant, DL, llvm::SDNode::getAsZExtVal(), getIntrinsicCmp(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::SDNode::hasNUsesOfValue(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isIntrinsicWithCC(), isIntrinsicWithCCAndChain(), llvm::SystemZ::reverseCCMask(), shouldSwapCmpOperands(), llvm::SelectionDAG::SignBitIsZero(), llvm::SystemZICMP::SignedOnly, std::swap(), and llvm::SystemZICMP::UnsignedOnly.
getCSAddressAndShifts()
void getCSAddressAndShifts (SDValue Addr, SelectionDAG & DAG, SDLoc DL, SDValue & AlignedAddr, SDValue & BitShift, SDValue & NegBitShift) static
Definition at line 5152 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSignedConstant(), llvm::SDValue::getValueType(), llvm::ISD::SHL, llvm::ISD::SUB, and llvm::ISD::TRUNCATE.
getDemandedSrcElements()
APInt getDemandedSrcElements (SDValue Op, const APInt & DemandedElts, unsigned OpNo) static
Definition at line 9401 of file SystemZISelLowering.cpp.
References assert(), llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isVector(), llvm_unreachable, llvm::APInt::lshr(), llvm::APInt::lshrInPlace(), llvm::APInt::setBit(), and llvm::APInt::trunc().
Referenced by computeKnownBitsBinOp(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), computeNumSignBitsBinOp(), and llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode().
getGeneralPermuteNode()
SDValue getGeneralPermuteNode (SelectionDAG & DAG, const SDLoc & DL, SDValue * Ops, const SmallVectorImpl< int > & Bytes) static
Definition at line 5887 of file SystemZISelLowering.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::BITCAST, DL, findZeroVectorIdx(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), I, isShlDoublePermute(), isUndef(), and llvm::SystemZ::VectorBytes.
getI128Select()
SDValue getI128Select (SelectionDAG & DAG, const SDLoc & DL, Comparison C, SDValue TrueOp, SDValue FalseOp) static
Definition at line 3983 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::CallingConv::C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm_unreachable, llvm::ISD::OR, std::swap(), and llvm::SystemZICMP::UnsignedOnly.
getIntrinsicCmp()
Comparison getIntrinsicCmp (SelectionDAG & DAG, unsigned Opcode, SDValue Call, unsigned CCValid, uint64_t CC, ISD::CondCode Cond) static
Definition at line 3513 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, Cond, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
Referenced by getCmp().
getLoadStoreAddrMode()
AddressingMode getLoadStoreAddrMode (bool HasVector, Type * Ty) static
Definition at line 1361 of file SystemZISelLowering.cpp.
Referenced by supportedAddressingMode().
getPermuteNode()
SDValue getPermuteNode (SelectionDAG & DAG, const SDLoc & DL, const Permute & P, SDValue Op0, SDValue Op1) static
Definition at line 5841 of file SystemZISelLowering.cpp.
References llvm::ISD::BITCAST, DL, llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorVT(), Op0, P, and llvm::SystemZ::VectorBytes.
getShuffleInput()
bool getShuffleInput (const SmallVectorImpl< int > & Bytes, unsigned Start, unsigned BytesPerElement, int & Base) static
Definition at line 5790 of file SystemZISelLowering.cpp.
References llvm::sampleprof::Base, I, and llvm::SmallVectorTemplateCommon< T, typename >::size().
getTestUnderMaskCond()
unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType) static
Definition at line 3208 of file SystemZISelLowering.cpp.
References assert(), llvm::bit_floor(), llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_TM_ALL_0, llvm::SystemZ::CCMASK_TM_ALL_1, llvm::SystemZ::CCMASK_TM_MIXED_MSB_0, llvm::SystemZ::CCMASK_TM_MIXED_MSB_1, llvm::SystemZ::CCMASK_TM_MSB_0, llvm::SystemZ::CCMASK_TM_MSB_1, llvm::SystemZ::CCMASK_TM_SOME_0, llvm::SystemZ::CCMASK_TM_SOME_1, llvm::countr_zero(), High, llvm::SystemZ::isImmHH(), llvm::SystemZ::isImmHL(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), llvm::Low, and llvm::SystemZICMP::SignedOnly.
Referenced by adjustForTestUnderMask().
getVectorComparison()
unsigned getVectorComparison (ISD::CondCode CC, CmpMode Mode) static
Definition at line 3699 of file SystemZISelLowering.cpp.
References FP, Int, llvm_unreachable, Mode, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETUGT, SignalingFP, and StrictFP.
Referenced by getVectorComparisonOrInvert().
getVectorComparisonOrInvert()
unsigned getVectorComparisonOrInvert (ISD::CondCode CC, CmpMode Mode, bool & Invert) static
Definition at line 3748 of file SystemZISelLowering.cpp.
References llvm::ISD::getSetCCInverse(), getVectorComparison(), Int, and Mode.
getVPermMask()
bool getVPermMask (SDValue ShuffleOp, SmallVectorImpl< int > & Bytes) static
Definition at line 5758 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), I, llvm::isa(), and llvm::SmallVectorImpl< T >::resize().
getzOSCalleeAndADA()
bool getzOSCalleeAndADA (SelectionDAG & DAG, SDValue & Callee, SDValue & ADA, SDLoc & DL, SDValue & Chain) static
Definition at line 2291 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, DL, llvm::dyn_cast(), E(), G, getADAEntry(), llvm::SystemZMachineFunctionInfo::getADAVirtualRegister(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getGOT(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTargetLoweringInfo(), and llvm::SystemZII::MO_ADA_DIRECT_FUNC_DESC.
Referenced by llvm::SystemZTargetLowering::LowerCall().
is32Bit()
bool is32Bit (EVT VT) static
Definition at line 74 of file SystemZISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm_unreachable, and llvm::MVT::SimpleTy.
Referenced by lowerGR128Binary().
isAbsolute()
bool isAbsolute (SDValue CmpOp, SDValue Pos, SDValue Neg) static
Definition at line 3965 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::SUB.
isAddCarryChain()
bool isAddCarryChain (SDValue Carry) static
Definition at line 4916 of file SystemZISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getValueType(), llvm::ISD::UADDO, and llvm::ISD::UADDO_CARRY.
isF128MovedFromParts()
bool isF128MovedFromParts (SDValue Val, SDValue & LoPart, SDValue & HiPart) static
Definition at line 8077 of file SystemZISelLowering.cpp.
References llvm::SDNode::getAsZExtVal(), llvm::SDValue::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDNode::hasOneUse(), and llvm::SDValue::isMachineOpcode().
isF128MovedToParts()
bool isF128MovedToParts (LoadSDNode * LD, SDNode *& LoPart, SDNode *& HiPart) static
Definition at line 7883 of file SystemZISelLowering.cpp.
References llvm::Use::getUser(), and llvm::Value::hasOneUse().
isI128MovedFromParts()
bool isI128MovedFromParts (SDValue Val, SDValue & LoPart, SDValue & HiPart) static
Definition at line 8049 of file SystemZISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::Constant, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), Op0, llvm::ISD::OR, llvm::ISD::SHL, std::swap(), and llvm::ISD::ZERO_EXTEND.
isI128MovedToParts()
bool isI128MovedToParts (LoadSDNode * LD, SDNode *& LoPart, SDNode *& HiPart) static
Definition at line 7848 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::User::getOperand(), llvm::Use::getUser(), llvm::Value::hasOneUse(), llvm::ISD::SRL, llvm::ISD::TRUNCATE, and llvm::Value::user_begin().
isIntrinsicWithCC()
bool isIntrinsicWithCC (SDValue Op, unsigned & Opcode, unsigned & CCValid) static
Definition at line 2688 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_0, llvm::SystemZ::CCMASK_3, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_TDC, and llvm::SystemZ::CCMASK_VCMP.
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), and getCmp().
isIntrinsicWithCCAndChain()
bool isIntrinsicWithCCAndChain (SDValue Op, unsigned & Opcode, unsigned & CCValid) static
Definition at line 2661 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_TBEGIN, and llvm::SystemZ::CCMASK_TEND.
Referenced by getCmp().
isNaturalMemoryOperand()
bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType) static
Definition at line 3016 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
Referenced by shouldSwapCmpOperands().
isOnlyUsedByStores()
bool isOnlyUsedByStores (SDValue StoredVal, SelectionDAG & DAG) static
Definition at line 8032 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::EVT::getStoreSize(), llvm::isa(), isOnlyUsedByStores(), llvm::EVT::isRound(), llvm::SelectionDAG::isSplatValue(), and llvm::SDNode::users().
Referenced by isOnlyUsedByStores().
isScalarToVector()
bool isScalarToVector (SDValue Op) static
Definition at line 6265 of file SystemZISelLowering.cpp.
References E(), and I.
isSelectPseudo()
bool isSelectPseudo (MachineInstr & MI) static
Definition at line 9767 of file SystemZISelLowering.cpp.
References MI.
isShlDoublePermute()
bool isShlDoublePermute (const SmallVectorImpl< int > & Bytes, unsigned & StartIndex, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 5813 of file SystemZISelLowering.cpp.
References chooseShuffleOpNos(), I, and llvm::SystemZ::VectorBytes.
Referenced by getGeneralPermuteNode().
isSimpleShift()
bool isSimpleShift (SDValue N, unsigned & ShiftVal) static
Definition at line 3189 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), and N.
Referenced by adjustForTestUnderMask().
isSubBorrowChain()
bool isSubBorrowChain (SDValue Carry) static
Definition at line 4924 of file SystemZISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getValueType(), llvm::ISD::USUBO, and llvm::ISD::USUBO_CARRY.
isVectorElementSwap()
bool isVectorElementSwap (ArrayRef< int > M, EVT VT) static
Definition at line 8016 of file SystemZISelLowering.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::isSimple(), and llvm::EVT::isVector().
isZeroVector()
bool isZeroVector (SDValue N) static
Definition at line 5867 of file SystemZISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::ISD::isBuildVectorAllZeros(), N, and llvm::ISD::SPLAT_VECTOR.
joinDwords()
SDValue joinDwords (SelectionDAG & DAG, const SDLoc & DL, SDValue Op0, SDValue Op1) static
Definition at line 6306 of file SystemZISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::isUndef(), and Op0.
lowerAddrSpaceCast()
SDValue lowerAddrSpaceCast (SDValue Op, SelectionDAG & DAG) static
Definition at line 6947 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::cast(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), N, llvm::SYSTEMZAS::PTR32, llvm::report_fatal_error(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::AMDGPUAsmPrinter::lowerConstant(), llvm::R600AsmPrinter::lowerConstant(), and llvm::SystemZTargetLowering::LowerOperation().
lowerGR128Binary()
void lowerGR128Binary (SelectionDAG & DAG, const SDLoc & DL, EVT VT, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue & Even, SDValue & Odd) static
Definition at line 3672 of file SystemZISelLowering.cpp.
References DL, llvm::SystemZ::even128(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), is32Bit(), llvm::SystemZ::odd128(), and Op0.
lowerGR128ToI128()
SDValue lowerGR128ToI128 (SelectionDAG & DAG, SDValue In) static
Definition at line 1969 of file SystemZISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Hi, llvm::TargetLoweringBase::isTypeLegal(), llvm::Lo, llvm::ISD::OR, llvm::ISD::SHL, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::SystemZTargetLowering::joinRegisterPartsIntoValue(), and llvm::SystemZTargetLowering::LowerOperationWrapper().
lowerI128ToGR128()
SDValue lowerI128ToGR128 (SelectionDAG & DAG, SDValue In) static
Definition at line 1950 of file SystemZISelLowering.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Hi, llvm::TargetLoweringBase::isTypeLegal(), llvm::Lo, llvm::SelectionDAG::SplitScalar(), llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
Referenced by llvm::SystemZTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerOperationWrapper(), and llvm::SystemZTargetLowering::splitValueIntoRegisterParts().
lowerMUL_LOHI32()
void lowerMUL_LOHI32 (SelectionDAG & DAG, const SDLoc & DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue & Hi, SDValue & Lo) static
Definition at line 3656 of file SystemZISelLowering.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::Hi, llvm::Lo, llvm::ISD::MUL, Mul, Op0, llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
matchDoublePermute() [1/2]
bool matchDoublePermute (const SmallVectorImpl< int > & Bytes, const Permute & P, SmallVectorImpl< int > & Transform) static
Definition at line 5726 of file SystemZISelLowering.cpp.
References P, and llvm::SystemZ::VectorBytes.
Referenced by matchDoublePermute().
matchDoublePermute() [2/2]
const Permute * matchDoublePermute (const SmallVectorImpl< int > & Bytes, SmallVectorImpl< int > & Transform) static
Definition at line 5748 of file SystemZISelLowering.cpp.
References matchDoublePermute(), P, and PermuteForms.
matchPermute() [1/2]
bool matchPermute (const SmallVectorImpl< int > & Bytes, const Permute & P, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 5689 of file SystemZISelLowering.cpp.
References chooseShuffleOpNos(), I, P, and llvm::SystemZ::VectorBytes.
Referenced by matchPermute().
matchPermute() [2/2]
const Permute * matchPermute (const SmallVectorImpl< int > & Bytes, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 5713 of file SystemZISelLowering.cpp.
References matchPermute(), P, and PermuteForms.
mergeHighParts()
SDValue mergeHighParts (SelectionDAG & DAG, const SDLoc & DL, unsigned MergedBits, EVT VT, SDValue Op0, SDValue Op1) static
Definition at line 6387 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, DL, llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorVT(), Op0, and llvm::SystemZ::VectorBits.
Referenced by buildFPVecFromScalars4().
MergeInputChains()
SDValue MergeInputChains (SDNode * N1, SDNode * N2) static
Definition at line 8375 of file SystemZISelLowering.cpp.
References llvm::SDNode::getOperand().
parseRegisterNumber()
std::pair< unsigned, const TargetRegisterClass * > parseRegisterNumber (StringRef Constraint, const TargetRegisterClass * RC, const unsigned * Map, unsigned Size) static
Definition at line 1637 of file SystemZISelLowering.cpp.
References assert(), llvm::StringRef::end(), llvm::Failed(), llvm::StringRef::getAsInteger(), Size, llvm::StringRef::size(), and llvm::StringRef::slice().
Referenced by llvm::SystemZTargetLowering::getRegForInlineAsmConstraint().
printFunctionArgExts()
void printFunctionArgExts (const Function * F, raw_fd_ostream & OS) static
Definition at line 11299 of file SystemZISelLowering.cpp.
References A(), E(), F, llvm::Attribute::getNameFromAttrKind(), llvm::AttributeSet::hasAttribute(), and I.
shouldSwapCmpOperands()
bool shouldSwapCmpOperands (const Comparison & C) static
Definition at line 3038 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::CallingConv::C, llvm::ISD::Constant, llvm::dyn_cast(), llvm::isa(), llvm::isInt(), isNaturalMemoryOperand(), llvm::isUInt(), llvm::ISD::SIGN_EXTEND, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZERO_EXTEND.
Referenced by getCmp().
simplifyAssumingCCVal()
SmallVector< SDValue, 4 > simplifyAssumingCCVal (SDValue & Val, SDValue & CC, SelectionDAG & DAG) static
Definition at line 8748 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, combineCCMask(), llvm::ISD::Constant, DL, llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::SystemZ::IPM_CC, Op0, llvm::ISD::OR, llvm::ISD::SHL, simplifyAssumingCCVal(), llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::XOR.
Referenced by combineCCMask(), and simplifyAssumingCCVal().
supportedAddressingMode()
AddressingMode supportedAddressingMode (Instruction * I, bool HasVector) static
Definition at line 1377 of file SystemZISelLowering.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), getLoadStoreAddrMode(), I, II, llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::isInt(), and llvm::isUInt().
Referenced by llvm::SystemZTargetLowering::isLegalAddressingMode().
tryBuildVectorShuffle()
SDValue tryBuildVectorShuffle (SelectionDAG & DAG, BuildVectorSDNode * BVN) static
Definition at line 6327 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBuildVector(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::TRUNCATE.
Variable Documentation
EnableIntArgExtCheck
cl::opt< bool > EnableIntArgExtCheck("argext-abi-check", cl::init(false), cl::desc("Verify that narrow int args are properly extended per the " "SystemZ ABI.")) ("argext-abi-check" , cl::init(false) , cl::desc("Verify that narrow int args are properly extended per the " "SystemZ ABI.")) static
PermuteForms
const Permute PermuteForms[] static
Definition at line 5617 of file SystemZISelLowering.cpp.
Referenced by matchDoublePermute(), and matchPermute().