LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp File Reference
SystemZMCTargetDesc.cpp File Reference
#include "SystemZMCTargetDesc.h"
#include "SystemZGNUInstPrinter.h"
#include "SystemZHLASMAsmStreamer.h"
#include "SystemZHLASMInstPrinter.h"
#include "SystemZMCAsmInfo.h"
#include "SystemZTargetStreamer.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "SystemZGenInstrInfo.inc"
#include "SystemZGenSubtargetInfo.inc"
#include "SystemZGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createSystemZMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createSystemZMCInstrInfo ()
static MCRegisterInfo * createSystemZMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createSystemZMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createSystemZMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint)
static MCStreamer * createSystemZAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, std::unique_ptr< MCInstPrinter > IP, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCAsmBackend > TAB)
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
static MCInstrAnalysis * createSystemZMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTargetMC ()
Variables
static cl::opt< bool > GNUAsOnzOSCL ("emit-gnuas-syntax-on-zos", cl::desc("Emit GNU Assembly Syntax on z/OS."), cl::init(true))
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 31 of file SystemZMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 30 of file SystemZMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 37 of file SystemZMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 34 of file SystemZMCTargetDesc.cpp.
Function Documentation
createAsmTargetStreamer()
MCTargetStreamer * createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint) static
Definition at line 203 of file SystemZMCTargetDesc.cpp.
References llvm::MCStreamer::getContext(), llvm::MCContext::getTargetTriple(), GNUAsOnzOSCL, and llvm::Triple::isOSzOS().
createNullTargetStreamer()
MCTargetStreamer * createNullTargetStreamer (MCStreamer & S) static
Definition at line 235 of file SystemZMCTargetDesc.cpp.
createObjectTargetStreamer()
MCTargetStreamer * createObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 227 of file SystemZMCTargetDesc.cpp.
References llvm::MCStreamer::getContext(), llvm::MCContext::getTargetTriple(), and llvm::Triple::isOSzOS().
createSystemZAsmStreamer()
MCStreamer * createSystemZAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, std::unique_ptr< MCInstPrinter > IP, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCAsmBackend > TAB) static
Definition at line 212 of file SystemZMCTargetDesc.cpp.
References llvm::createAsmStreamer(), and GNUAsOnzOSCL.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCAsmInfo()
MCAsmInfo * createSystemZMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 161 of file SystemZMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::SystemZMC::ELFCFAOffsetFromInitialSP, MRI, and Options.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstPrinter()
MCInstPrinter * createSystemZMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 192 of file SystemZMCTargetDesc.cpp.
References llvm::AD_HLASM, MRI, and T.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstrAnalysis()
MCInstrAnalysis * createSystemZMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 239 of file SystemZMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstrInfo()
MCInstrInfo * createSystemZMCInstrInfo () static
Definition at line 175 of file SystemZMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCRegisterInfo()
MCRegisterInfo * createSystemZMCRegisterInfo (const Triple & TT) static
Definition at line 181 of file SystemZMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCSubtargetInfo()
MCSubtargetInfo * createSystemZMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 188 of file SystemZMCTargetDesc.cpp.
Referenced by LLVMInitializeSystemZTargetMC().
LLVMInitializeSystemZTargetMC()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTargetMC ()
Definition at line 244 of file SystemZMCTargetDesc.cpp.
References createAsmTargetStreamer(), createNullTargetStreamer(), createObjectTargetStreamer(), createSystemZAsmStreamer(), llvm::createSystemZMCAsmBackend(), createSystemZMCAsmInfo(), llvm::createSystemZMCCodeEmitter(), createSystemZMCInstPrinter(), createSystemZMCInstrAnalysis(), createSystemZMCInstrInfo(), createSystemZMCRegisterInfo(), createSystemZMCSubtargetInfo(), llvm::getTheSystemZTarget(), llvm::TargetRegistry::RegisterAsmStreamer(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().
Variable Documentation
GNUAsOnzOSCL
cl::opt< bool > GNUAsOnzOSCL("emit-gnuas-syntax-on-zos", cl::desc("Emit GNU Assembly Syntax on z/OS."), cl::init(true)) ("emit-gnuas-syntax-on-zos" , cl::desc("Emit GNU Assembly Syntax on z/OS.") , cl::init(true)) static
Referenced by createAsmTargetStreamer(), and createSystemZAsmStreamer().