LLVM: lib/TableGen/TableGenBackendSkeleton.cpp File Reference
TableGenBackendSkeleton.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/TableGen/TableGenBackend.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "skeleton-emitter"
Functions
static void EmitSkeleton (const RecordKeeper &RK, raw_ostream &OS)
Variables
static TableGen::Emitter::OptClass< SkeletonEmitter > X ("gen-skeleton-class", "Generate example skeleton class")
static TableGen::Emitter::Opt Y ("gen-skeleton-entry", EmitSkeleton, "Generate example skeleton entry")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "skeleton-emitter"
Definition at line 16 of file TableGenBackendSkeleton.cpp.
Function Documentation
EmitSkeleton()
void EmitSkeleton (const RecordKeeper & RK, raw_ostream & OS) static
Definition at line 58 of file TableGenBackendSkeleton.cpp.
Variable Documentation
X
TableGen::Emitter::OptClass< SkeletonEmitter > X("gen-skeleton-class", "Generate example skeleton class") ("gen-skeleton-class" , "Generate example skeleton class") static
Examples
/Users/rift/code/llvm-doxygen/llvm-project-22.1.0/llvm/include/llvm/Transforms/Utils/Local.h.
Referenced by llvm::abs(), llvm::detail::abs(), llvm::detail::SlowDynamicAPInt::abs, llvm::DynamicAPInt::abs, llvm::AbsoluteDifference(), llvm::AbsoluteValue(), llvm::ConstantRange::add(), llvm::cl::parser< DataType >::addLiteralOption(), llvm::AddOverflow(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::ScheduleDAGTopologicalSort::AddPredQueued(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::AllocatorList(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::AllocatorList(), annotateNonNullAndDereferenceable(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::CombinerHelper::applyXorOfAndWithSameReg(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), buildVRegToDbgValueMap(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), llvm::capacity_in_bytes(), llvm::capacity_in_bytes(), llvm::capacity_in_bytes(), llvm::SwitchCG::SwitchLowering::caseClusterRank(), CheckAndCreateOffsetAdd(), checkForNegativeOperand(), collectBitParts(), combineAdd(), combineAddOrSubToADCOrSBB(), combineAddOrSubToADCOrSBB(), combineAnd(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndNotIntoVANDN(), combineAndNotOrIntoAndNotAnd(), combineAndShuffleNot(), combineAndXorSubWithBMI(), combineConcatVectorOps(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMADConstOne(), combineMulSelectConstOne(), combineOr(), combineOrToBitfieldInsert(), combinePTESTCC(), combineSetCC(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineSubABS(), combineUADDO_CARRYDiamond(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), combineVWADDSUBWSelect(), combineX86SubCmpForFlags(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), commuteSelect(), llvm::ScaledNumber< uint64_t >::compare(), CompareSCEVComplexity(), llvm::ComputeEditDistance(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash(), llvm::DefaultFoldingSetTrait< T >::ComputeHash(), llvm::DefaultFoldingSetTrait< SCEV >::ComputeHash(), llvm::FoldingSetTrait< SCEV >::ComputeHash(), llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash(), llvm::FoldingSetTrait< SDVTListNode >::ComputeHash(), ComputeNumSignBitsImpl(), llvm::IntrusiveBackList< T >::const_iterator::const_iterator(), llvm::DIEValueList::const_value_iterator::const_value_iterator(), llvm::DIEValueList::const_value_iterator::const_value_iterator(), llvm::codeview::consume(), llvm::Trace::contains(), convertFSqrtDivIntoFMul(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), createAArch64MCInstrInfo(), createAArch64MCRegisterInfo(), createAMDGPUMCInstrInfo(), createAMDGPUMCRegisterInfo(), createARCMCInstrInfo(), createARCMCRegisterInfo(), createARMMCInstrInfo(), createARMMCRegisterInfo(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::createAVRMCInstrInfo(), createAVRMCRegisterInfo(), createBPFMCInstrInfo(), createBPFMCRegisterInfo(), llvm::createGCNMCRegisterInfo(), llvm::createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createLanaiMCInstrInfo(), createLanaiMCRegisterInfo(), createLoongArchMCInstrInfo(), createLoongArchMCRegisterInfo(), createM68kMCInstrInfo(), createM68kMCRegisterInfo(), createMCInstrInfo(), createMCRegisterInfo(), createMipsMCInstrInfo(), createMipsMCRegisterInfo(), createMSP430MCInstrInfo(), createMSP430MCRegisterInfo(), createNodeForSelectViaUMinSeq(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createPPCMCInstrInfo(), createPPCMCRegisterInfo(), llvm::createR600MCInstrInfo(), createRISCVMCInstrInfo(), createRISCVMCRegisterInfo(), createRISCVMCSubtargetInfo(), createSparcMCInstrInfo(), createSparcMCRegisterInfo(), createSPIRVMCInstrInfo(), createSPIRVMCRegisterInfo(), createSystemZMCInstrInfo(), createSystemZMCRegisterInfo(), createVEMCInstrInfo(), createVEMCRegisterInfo(), createX86MCInstrInfo(), createX86MCRegisterInfo(), createXCoreMCInstrInfo(), createXCoreMCRegisterInfo(), createXtensaMCInstrInfo(), createXtensaMCRegisterInfo(), llvm::DebugValueUser::DebugValueUser(), llvm::DebugValueUser::DebugValueUser(), decomposeBitTest(), llvm::decomposeBitTest(), llvm::decomposeBitTestICmp(), llvm::DIEValue::DIEValue(), dropRedundantMaskingOfLeftShiftInput(), llvm::dynamicAPIntFromInt64(), llvm::MCDwarfFrameEmitter::Emit(), emitOrXorXorTree(), emitTransformedIndex(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals(), llvm::DefaultFoldingSetTrait< T >::Equals(), llvm::DefaultFoldingSetTrait< SCEV >::Equals(), llvm::FoldingSetTrait< SCEV >::Equals(), llvm::FoldingSetTrait< SCEVPredicate >::Equals(), llvm::FoldingSetTrait< SDVTListNode >::Equals(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), expandAbs(), expandAnyOrAllIntrinsic(), expandAtan2Intrinsic(), expandClampIntrinsic(), llvm::TargetLowering::expandCLMUL(), expandDegreesIntrinsic(), expandExpIntrinsic(), llvm::TargetLowering::expandFunnelShift(), expandLerpIntrinsic(), expandLog(), expandLog10(), expandLog2(), expandLogIntrinsic(), expandMul(), expandMulToAddOrSubOfShl(), expandMulToShlAddShlAdd(), expandNormalizeIntrinsic(), expandPowIntrinsic(), expandRadiansIntrinsic(), expandSignIntrinsic(), expandStepIntrinsic(), expandUDivOrURem(), expandVecReduceAdd(), expandVPFunnelShift(), llvm::RISCVSubtarget::expandVScale(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), llvm::detail::fastTwoSum(), llvm::LiveRange::find(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), findGCD(), FindInOperandList(), llvm::findValuesAffectedByCondition(), finishAdjustingBasicBlocksAndLandingPads(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldAndToUsubsat(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldBitOrderCrossLogicOp(), foldBitOrderCrossLogicOp(), foldBitwiseLogicWithIntrinsics(), foldBoxMultiply(), foldCastShuffle(), foldClampRangeOfTwo(), foldComplexAndOrPatterns(), foldCopySignIdioms(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldCtpop(), foldCttzCtlz(), foldExtendedSignBitTest(), foldFabsWithFcmpZero(), foldFCmpFSubIntoFCmp(), foldFDivConstantDividend(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithClamp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), llvm::InstCombinerImpl::foldItoFPtoI(), foldLoadsRecursive(), foldLogicCastConstant(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedMerge(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldMinMaxSharedOp(), foldMulHigh(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNotXor(), foldNoWrapAdd(), FoldOrOfSelectSmaxToAbs(), foldOrUnsignedUMulOverflowICmp(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldReversedIntrinsicOperands(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBinOpIdentity(), foldSelectBitTest(), foldSelectCmpXchg(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), foldSelectICmpLshrAshr(), foldSelectIntoAddConstant(), foldSelectOfConstantsUsingSra(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), foldSelectToCopysign(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithFCmpToFabs(), foldSelectZeroOrFixedOp(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), foldShuffleOfConcatUndefs(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldSqrtWithFcmpZero(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), foldTruncInsEltPair(), foldTruncShuffle(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), llvm::FmtAlign::format(), llvm::format_provider< T, std::enable_if_t< support::detail::use_char_formatter< T >::value > >::format(), llvm::PMDataManager::freePass(), llvm::APFloat::frexp, llvm::detail::DoubleAPFloat::frexp, llvm::frexp(), genConstMult(), genShXAddAddShift(), llvm::APSInt::get(), llvm::get_hashable_data(), llvm::Trace::getBlockIndex(), llvm::IndexedInstrProfReader::getFunctionBitmap(), llvm::DenseMapInfo< ImmutableList< T >, void >::getHashValue(), getHashValueImpl(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), getKnownBitsFromAndXorOr(), getKnownSign(), getKnownSignOrZero(), getLimitedPrecisionExp2(), llvm::objcopy::elf::IHexRecord::getLine(), getMad(), getMad(), llvm::TargetLowering::getNegatedExpression(), getShlAddShlAdd(), llvm::X86TTIImpl::getShuffleCost(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::APSInt::getUnsigned(), getUnsignedMonotonicValues(), llvm::SDNode::getVTList(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::HandleSDNode::HandleSDNode(), handleValVerMetadata(), llvm::harrisonUlp(), llvm::TargetLoweringBase::hasAndNot(), llvm::HexagonTargetLowering::hasBitTest(), llvm::MipsTargetLowering::hasBitTest(), llvm::RISCVTargetLowering::hasBitTest(), llvm::TargetLoweringBase::hasBitTest(), llvm::X86TargetLowering::hasBitTest(), llvm::detail::hash_value(), llvm::detail::SlowDynamicAPInt::hash_value, llvm::hash_value(), hoistInsEltConst(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::SetVector< EdgeType * >::insert(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::int64fromDynamicAPInt(), llvm::iterator< AliasSet >::iplist(), llvm::iterator< AliasSet >::iplist(), llvm::iplist_impl< IntrusiveListT, TraitsT >::iplist_impl(), llvm::isa_and_nonnull(), llvm::isa_and_present(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), isDivisibilityGuard(), isDivZero(), isEqualImpl(), llvm::X86MCExpr::isEqualTo(), llvm::TargetLoweringBase::isFsqrtCheap(), isFSqrtDivToFMulLegal(), llvm::HexagonBlockRanges::IndexType::isInstr(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonZeroFromOperator(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), slpvectorizer::BoUpSLP::isLoadCombineCandidate(), isMaskOrZero(), isMatchingReloc(), isMultipleOf(), isNonZeroAdd(), isNonZeroMul(), isNonZeroSub(), isOrXorXorTree(), llvm::isSplatValue(), isTruePredicate(), llvm::IVUsers::IVUsers(), llvm::detail::lcm(), llvm::DynamicAPInt::lcm, llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFExp10Unsafe(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafe(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafeImpl(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF32(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF64(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), LLVMInitializeAArch64AsmParser(), LLVMInitializeAArch64Target(), LLVMInitializeAArch64TargetInfo(), LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTarget(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCTarget(), LLVMInitializeARCTargetInfo(), LLVMInitializeARCTargetMC(), LLVMInitializeARMAsmParser(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRAsmParser(), llvm::LLVMInitializeAVRTarget(), LLVMInitializeAVRTargetInfo(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFAsmParser(), LLVMInitializeBPFTarget(), LLVMInitializeBPFTargetInfo(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYAsmParser(), LLVMInitializeCSKYAsmPrinter(), LLVMInitializeCSKYTarget(), LLVMInitializeCSKYTargetInfo(), LLVMInitializeDirectXAsmPrinter(), LLVMInitializeDirectXTarget(), LLVMInitializeDirectXTargetInfo(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonAsmParser(), LLVMInitializeHexagonTarget(), LLVMInitializeHexagonTargetInfo(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiTargetInfo(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchAsmParser(), LLVMInitializeLoongArchTarget(), LLVMInitializeLoongArchTargetInfo(), LLVMInitializeM68kAsmParser(), LLVMInitializeM68kTarget(), LLVMInitializeM68kTargetInfo(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430AsmParser(), LLVMInitializeMSP430Target(), LLVMInitializeMSP430TargetInfo(), LLVMInitializeNVPTXTarget(), LLVMInitializeNVPTXTargetInfo(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetInfo(), LLVMInitializeRISCVAsmParser(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcTarget(), LLVMInitializeSparcTargetInfo(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTarget(), LLVMInitializeSPIRVTargetInfo(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZAsmParser(), LLVMInitializeSystemZTarget(), LLVMInitializeSystemZTargetInfo(), LLVMInitializeVETarget(), LLVMInitializeVETargetInfo(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyAsmParser(), LLVMInitializeWebAssemblyTarget(), LLVMInitializeWebAssemblyTargetInfo(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86AsmParser(), LLVMInitializeX86Target(), LLVMInitializeX86TargetInfo(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreTarget(), LLVMInitializeXCoreTargetInfo(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaAsmParser(), LLVMInitializeXtensaTargetInfo(), llvm::longestCommonSequence(), LowerADDSAT_SUBSAT(), lowerAddSubToHorizontalOp(), LowerCTTZ(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafeImpl(), LowerFLDEXP(), LowerFLDEXP(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), lowerFPToIntToFP(), lowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::LegalizerHelper::lowerIntrinsicRound(), LowerPARITY(), LowerSDIV_v4i8(), llvm::VETargetLowering::lowerToVVP(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_UnOp(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapVectorN(), MatchBinaryOp(), matchBinaryOp(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCommuteShift(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchIntPart(), matchLogicBlend(), matchOrConcat(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRepeatedFPDivisor(), llvm::CombinerHelper::matchSimplifyNegMinMax(), llvm::CombinerHelper::matchSubAddSameReg(), matchVPMADD52(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), mergeEltWithShuffle(), llvm::AbstractLatticeFunction< LatticeKey, LatticeVal >::MergeValues(), MinOptional(), moveAddAfterMinMax(), llvm::MulOverflow(), narrowBitOpRMW(), narrowExtractedVectorBinOp(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), llvm::neg(), llvm::bfi_detail::BlockMass::operator!=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator!=(), llvm::DebugValueUser::operator!=(), llvm::DIExpression::expr_op_iterator::operator!=(), llvm::DIFile::ChecksumInfo< T >::operator!=(), llvm::DITypeRefArray::iterator::operator!=(), llvm::OnDiskChainedHashTable< Info >::iterator::operator!=(), llvm::ScaledNumber< uint64_t >::operator!=(), llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::operator!=(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator!=(), llvm::TrackingMDRef::operator!=(), llvm::TypedMDOperandIterator< T >::operator!=(), llvm::TypedTrackingMDRef< MDNode >::operator!=(), llvm::VersionTuple::operator!=, llvm::ScaledNumber< DigitsT >::operator*=(), llvm::ScaledNumber< uint64_t >::operator*=(), llvm::VPAllSuccessorsIterator< VPBlockBase * >::operator++(), llvm::bfi_detail::BlockMass::operator+=(), llvm::ScaledNumber< uint64_t >::operator+=(), llvm::bfi_detail::BlockMass::operator-=(), llvm::ScaledNumber< uint64_t >::operator-=(), llvm::ScaledNumber< DigitsT >::operator/=(), llvm::ScaledNumber< uint64_t >::operator/=(), llvm::bfi_detail::BlockMass::operator<(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<(), llvm::ScaledNumber< uint64_t >::operator<(), llvm::VersionTuple::operator<, llvm::bfi_detail::operator<<(), llvm::detail::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::bfi_detail::BlockMass::operator<=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<=(), llvm::ScaledNumber< uint64_t >::operator<=(), llvm::VersionTuple::operator<=, llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::operator=(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::operator=(), llvm::DebugValueUser::operator=(), llvm::DebugValueUser::operator=(), llvm::DIEValue::operator=(), llvm::DynamicAPInt::operator=(), llvm::iplist_impl< IntrusiveListT, TraitsT >::operator=(), llvm::iterator< AliasSet >::operator=(), llvm::iterator< AliasSet >::operator=(), llvm::simple_ilist< Node >::operator=(), llvm::TrackingMDRef::operator=(), llvm::TrackingMDRef::operator=(), llvm::TypedTrackingMDRef< MDNode >::operator=(), llvm::TypedTrackingMDRef< MDNode >::operator=(), llvm::bfi_detail::BlockMass::operator==(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator==(), llvm::ConstantAggrKeyType< ConstantArray >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::ConstantPtrAuthKeyType::operator==(), llvm::DebugValueUser::operator==(), llvm::DIExpression::expr_op_iterator::operator==(), llvm::DIFile::ChecksumInfo< T >::operator==(), llvm::DITypeRefArray::iterator::operator==(), llvm::InlineAsmKeyType::operator==(), llvm::IntrusiveBackList< T >::const_iterator::operator==(), llvm::IntrusiveBackList< T >::iterator::operator==(), llvm::OnDiskChainedHashTable< Info >::iterator::operator==(), llvm::ScaledNumber< uint64_t >::operator==(), llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::operator==(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator==(), llvm::TrackingMDRef::operator==(), llvm::TypedMDOperandIterator< T >::operator==(), llvm::TypedTrackingMDRef< MDNode >::operator==(), llvm::VersionTuple::operator==, llvm::bfi_detail::BlockMass::operator>(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>(), llvm::ScaledNumber< uint64_t >::operator>(), llvm::VersionTuple::operator>, llvm::bfi_detail::BlockMass::operator>=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>=(), llvm::ScaledNumber< uint64_t >::operator>=(), llvm::VersionTuple::operator>=, operator|=(), OptimizeAndOrXor(), optimizeBranch(), optimizeDivRem(), optimizeIncrementingWhile(), optimizeSymmetricCall(), llvm::GCOV::Options::Options(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::object::DirectX::PSVRuntimeInfo::parse(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformExtractEltCombine(), performMulCombine(), PerformPREDICATE_CASTCombine(), performSHLCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), performSubAddMULCombine(), PerformSubCSINCCombine(), performUzpCombine(), llvm::APIntOps::pow(), processAbsIntrinsic(), processUse(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile(), llvm::DefaultFoldingSetTrait< T >::Profile(), llvm::DefaultFoldingSetTrait< T >::Profile(), llvm::FoldingSetTrait< SCEV >::Profile(), llvm::FoldingSetTrait< SCEVPredicate >::Profile(), llvm::FoldingSetTrait< SDVTListNode >::Profile(), llvm::FoldingSetTrait< T * >::Profile(), llvm::FoldingSetTrait< T, std::enable_if_t< std::is_enum< T >::value > >::Profile(), llvm::ImutProfileInfo< T >::Profile(), llvm::ImutProfileInfo< bool >::Profile(), llvm::ImutProfileInfo< T * >::Profile(), llvm::ImutProfileInteger< T >::Profile(), pushAddIntoCmovOfConsts(), reassociateCSELOperandsForCSE(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), ReconstructTruncateFromBuildVector(), relocKindName(), llvm::SetVector< EdgeType * >::remove(), ReplaceAddWithADDP(), reverseZExtICmpCombine(), rotl64(), runNVVMIntrRange(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::SaturatingAdd(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), scalarizeBinOpOfSplats(), llvm::APFloat::scalbn, llvm::detail::DoubleAPFloat::scalbn, llvm::detail::IEEEFloat::scalbn, llvm::scalbn(), llvm::RISCVDAGToDAGISel::Select(), llvm::cl::ExpansionContext::setCurrentDir(), llvm::cl::ExpansionContext::setMarkEOLs(), llvm::cl::ExpansionContext::setRelativeNames(), llvm::cl::ExpansionContext::setSearchDirs(), llvm::cl::ExpansionContext::setVFS(), llvm::TargetLoweringBase::shouldFoldMaskToVariableShiftPair(), llvm::AArch64TargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::ARMTargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::RISCVTargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::TargetLoweringBase::shouldFoldSelectWithIdentityConstant(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::AArch64TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::RISCVTargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLoweringBase::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLowering::ShrinkDemandedOp(), llvm::SignExtend32(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::simple_ilist< Node >::simple_ilist(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmps(), simplifyAndOrOfICmpsWithCtpop(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyCastInst(), simplifyCmpSelOfMaxMin(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFNegInst(), llvm::SelectionDAG::simplifyFPBinop(), simplifyFSubInst(), simplifyICmpOfBools(), simplifyICmpWithConstant(), llvm::simplifyInstruction(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLogicOfAddSub(), llvm::simplifyLoopAfterUnroll(), simplifyLShrInst(), simplifyMulInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmps(), simplifyRecipe(), simplifySelectBitTest(), simplifySelectInst(), simplifySelectWithICmpCond(), llvm::SelectionDAG::simplifyShift(), simplifyShift(), simplifyShlInst(), simplifySRemInst(), simplifySubInst(), simplifySwitchOnSelectUsingRanges(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), simplifyXorInst(), sinkMinMaxInBB(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::stripNullTest(), strongerOrdering(), llvm::ConstantRange::sub(), llvm::SubOverflow(), llvm::simple_ilist< Node >::swap(), llvm::InstCombinerImpl::takeLog2(), toHexStr(), toOctal(), llvm::objcopy::elf::SRecord::toString(), llvm::TrackingMDRef::TrackingMDRef(), llvm::TrackingMDRef::TrackingMDRef(), translateExtract(), TruncIfPossible(), TryDistrubutionADDVecReduce(), tryLowerToSLI(), trySimplifyICmpWithAdds(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldInsertInZero(), llvm::TypedTrackingMDRef< MDNode >::TypedTrackingMDRef(), llvm::TypedTrackingMDRef< MDNode >::TypedTrackingMDRef(), llvm::VPWidenIntrinsicRecipe::usesFirstLaneOnly(), llvm::DIEValueList::value_iterator::value_iterator(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFRem(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), widenBuildVector(), and wrap().
Y
TableGen::Emitter::Opt Y("gen-skeleton-entry", EmitSkeleton, "Generate example skeleton entry") ("gen-skeleton-entry" , EmitSkeleton , "Generate example skeleton entry") static
Referenced by llvm::AbsoluteDifference(), llvm::AddOverflow(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::ScheduleDAGTopologicalSort::AddPredQueued(), annotateNonNullAndDereferenceable(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::CombinerHelper::applyXorOfAndWithSameReg(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canonicalizeBitSelect(), canonicalizeSaturatedAddUnsigned(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_or_null(), llvm::cast_or_null(), llvm::cast_or_null(), CheckAndCreateOffsetAdd(), checkForNegativeOperand(), collectBitParts(), combineAdd(), combineAddOrSubToADCOrSBB(), combineAddOrSubToADCOrSBB(), combineAnd(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndNotIntoVANDN(), combineAndNotOrIntoAndNotAnd(), combineAndShuffleNot(), combineAndXorSubWithBMI(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMADConstOne(), combineMulSelectConstOne(), combineOr(), combineShiftOfShiftedLogic(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVWADDSUBWSelect(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), commuteSelect(), computeKnownBitsFromCmp(), llvm::Constant::Constant(), llvm::codeview::consume(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), decomposeBitTest(), llvm::dyn_cast_if_present(), llvm::dyn_cast_if_present(), llvm::dyn_cast_if_present(), llvm::dyn_cast_or_null(), llvm::dyn_cast_or_null(), llvm::dyn_cast_or_null(), llvm::mdconst::dyn_extract(), llvm::mdconst::dyn_extract_or_null(), llvm::MCDwarfFrameEmitter::Emit(), emitTransformedIndex(), expandAtan2Intrinsic(), llvm::TargetLowering::expandCLMUL(), llvm::TargetLowering::expandFunnelShift(), expandLerpIntrinsic(), expandPowIntrinsic(), expandStepIntrinsic(), expandUDivOrURem(), expandVPFunnelShift(), llvm::mdconst::extract(), llvm::mdconst::extract(), llvm::mdconst::extract_or_null(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), llvm::FailureOr< T >::FailureOr(), llvm::FailureOr< T >::FailureOr(), llvm::detail::fastTwoSum(), findGCD(), llvm::findValuesAffectedByCondition(), finishAdjustingBasicBlocksAndLandingPads(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldBitCastBitwiseLogic(), foldBitOrderCrossLogicOp(), foldBitOrderCrossLogicOp(), foldBitwiseLogicWithIntrinsics(), foldBoxMultiply(), foldCastShuffle(), foldComplexAndOrPatterns(), foldCopySignIdioms(), foldCSELOfCSEL(), foldCtpop(), foldCttzCtlz(), foldFCmpFSubIntoFCmp(), foldFDivSqrtDivisor(), llvm::InstCombinerImpl::foldFMulReassoc(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpShlLHSC(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::InstCombinerImpl::foldICmpXorConstant(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldLogicOfShifts(), foldMaskedMerge(), foldMinMaxSharedOp(), foldMulHigh(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNotXor(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldPowiReassoc(), foldSelectBinOpIdentity(), foldSelectICmpAndAnd(), foldSelectICmpAndBinOp(), foldSelectICmpLshrAshr(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectZeroOrFixedOp(), foldSetCCWithFunnelShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldShuffleOfConcatUndefs(), foldShuffleOfUnaryOps(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), genShXAddAddShift(), llvm::ScalarEvolution::getAddExpr(), getHashValueImpl(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), getKnownBitsFromAndXorOr(), getKnownSign(), getKnownSignOrZero(), getMad(), getMad(), llvm::TargetLowering::getNegatedExpression(), llvm::X86TTIImpl::getShuffleCost(), getUnsignedMonotonicValues(), handleValVerMetadata(), llvm::mdconst::hasa(), llvm::mdconst::hasa(), llvm::AArch64TargetLowering::hasAndNot(), llvm::LoongArchTargetLowering::hasAndNot(), llvm::RISCVTargetLowering::hasAndNot(), llvm::SystemZTargetLowering::hasAndNot(), llvm::VETargetLowering::hasAndNot(), llvm::X86TargetLowering::hasAndNot(), llvm::LoongArchTargetLowering::hasAndNotCompare(), llvm::RISCVTargetLowering::hasAndNotCompare(), llvm::TargetLoweringBase::hasAndNotCompare(), llvm::X86TargetLowering::hasAndNotCompare(), llvm::HexagonTargetLowering::hasBitTest(), llvm::MipsTargetLowering::hasBitTest(), llvm::RISCVTargetLowering::hasBitTest(), llvm::TargetLoweringBase::hasBitTest(), llvm::X86TargetLowering::hasBitTest(), haveNoCommonBitsSetSpecialCases(), hoistInsEltConst(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::isa_and_nonnull(), llvm::isa_and_present(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::isCheckForZeroAndMulWithOverflow(), isDivisibilityGuard(), isDivZero(), llvm::Constant::isElementWiseEqual(), isEqualImpl(), llvm::isKnownInversion(), llvm::isKnownNegation(), isNonZeroAdd(), isNonZeroMul(), isNonZeroSub(), llvm::isSplatValue(), llvm::detail::lcm(), llvm::DynamicAPInt::lcm, llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), LLVMInitializeAArch64AsmParser(), LLVMInitializeAArch64Target(), LLVMInitializeAMDGPUTarget(), LLVMInitializeARMAsmParser(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeBPFAsmParser(), LLVMInitializeBPFTarget(), LLVMInitializeBPFTargetInfo(), LLVMInitializeLoongArchAsmParser(), LLVMInitializeLoongArchTarget(), LLVMInitializeLoongArchTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializeNVPTXTarget(), LLVMInitializeNVPTXTargetInfo(), LLVMInitializePowerPCTargetInfo(), LLVMInitializeRISCVAsmParser(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcTarget(), LLVMInitializeSparcTargetInfo(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVTarget(), LLVMInitializeSPIRVTargetInfo(), LLVMInitializeWebAssemblyAsmParser(), LLVMInitializeWebAssemblyTarget(), LLVMInitializeWebAssemblyTargetInfo(), LLVMInitializeX86AsmParser(), LLVMInitializeX86Target(), LLVMInitializeX86TargetInfo(), loadYAML(), llvm::longestCommonSequence(), LowerADDSAT_SUBSAT(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), lowerFREM(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), LowerSDIV_v4i8(), LowerSELECTWithCmpZero(), llvm::VETargetLowering::lowerToVVP(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchIntPart(), matchLogicBlend(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRepeatedFPDivisor(), llvm::CombinerHelper::matchSubAddSameReg(), matchVPMADD52(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), mergeEltWithShuffle(), llvm::AbstractLatticeFunction< LatticeKey, LatticeVal >::MergeValues(), MinOptional(), llvm::MulOverflow(), narrowExtractedVectorBinOp(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), llvm::VersionTuple::operator!=, llvm::VersionTuple::operator<, llvm::VersionTuple::operator<=, llvm::VersionTuple::operator==, llvm::VersionTuple::operator>, llvm::VersionTuple::operator>=, operator|=(), optimizeDivRem(), optimizeIncrementingWhile(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::object::DirectX::PSVRuntimeInfo::parse(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::SITargetLowering::passSpecialInputs(), performAddCombineSubShift(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), pushAddIntoCmovOfConsts(), reassociateCSELOperandsForCSE(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), ReconstructTruncateFromBuildVector(), runNVVMIntrRange(), llvm::SaturatingAdd(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), scalarizeBinOpOfSplats(), llvm::AArch64TargetLowering::shouldFoldMaskToVariableShiftPair(), llvm::ARMTargetLowering::shouldFoldMaskToVariableShiftPair(), llvm::RISCVTargetLowering::shouldFoldMaskToVariableShiftPair(), llvm::X86TargetLowering::shouldFoldMaskToVariableShiftPair(), llvm::AArch64TargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::ARMTargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::RISCVTargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::TargetLoweringBase::shouldFoldSelectWithIdentityConstant(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::AArch64TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::RISCVTargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLoweringBase::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), simplifyAddInst(), simplifyAndCommutative(), simplifyAndInst(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyCmpSelOfMaxMin(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::SelectionDAG::simplifyFPBinop(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyIRemMulShl(), simplifyLShrInst(), simplifyOrInst(), simplifyOrLogic(), simplifyRecipe(), simplifySelectBitTest(), simplifySelectInst(), simplifySelectWithICmpCond(), llvm::SelectionDAG::simplifyShift(), simplifySubInst(), simplifyUnsignedRangeCheck(), simplifyXorInst(), strongerOrdering(), llvm::SubOverflow(), llvm::success(), llvm::InstCombinerImpl::takeLog2(), tryLowerToSLI(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitXor(), and widenBuildVector().