LLVM: lib/CodeGen/TargetRegisterInfo.cpp File Reference
TargetRegisterInfo.cpp File Reference
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/CodeGenTypes/MachineValueType.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Printable.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <utility>
Macros
#define DEBUG_TYPE "target-reg-info"
Functions
template<typename TypeT>
static const TargetRegisterClass * getMinimalPhysRegClass (const TargetRegisterInfo *TRI, MCRegister Reg, TypeT Ty)
template<typename TypeT>
static const TargetRegisterClass * getCommonMinimalPhysRegClass (const TargetRegisterInfo *TRI, MCRegister Reg1, MCRegister Reg2, TypeT Ty)
static void getAllocatableSetForRC (const MachineFunction &MF, const TargetRegisterClass *RC, BitVector &R)
getAllocatableSetForRC - Toggle the bits that represent allocatable registers for the specific register class.
static const TargetRegisterClass * firstCommonClass (const uint32_t *A, const uint32_t *B, const TargetRegisterInfo *TRI)
Variables
static cl::opt< unsigned > HugeSizeForSplit ("huge-size-for-split", cl::Hidden, cl::desc("A threshold of live range size which may cause " "high compile time cost in global splitting."), cl::init(5000))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "target-reg-info"
Definition at line 42 of file TargetRegisterInfo.cpp.
Function Documentation
firstCommonClass()
const TargetRegisterClass * firstCommonClass (const uint32_t * A, const uint32_t * B, const TargetRegisterInfo * TRI) inline static
Definition at line 312 of file TargetRegisterInfo.cpp.
References A(), B(), llvm::countr_zero(), E(), I, and TRI.
Referenced by llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), and llvm::TargetRegisterInfo::getMatchingSuperRegClass().
getAllocatableSetForRC()
void getAllocatableSetForRC (const MachineFunction & MF, const TargetRegisterClass * RC, BitVector & R) static
getAllocatableSetForRC - Toggle the bits that represent allocatable registers for the specific register class.
Definition at line 281 of file TargetRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::getRawAllocationOrder(), and llvm::TargetRegisterClass::isAllocatable().
Referenced by llvm::TargetRegisterInfo::getAllocatableSet().
getCommonMinimalPhysRegClass()
template<typename TypeT> const TargetRegisterClass * getCommonMinimalPhysRegClass (const TargetRegisterInfo * TRI, MCRegister Reg1, MCRegister Reg2, TypeT Ty) static
Definition at line 232 of file TargetRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::hasSubClass(), llvm::MCRegister::isPhysical(), and TRI.
getMinimalPhysRegClass()
template<typename TypeT> const TargetRegisterClass * getMinimalPhysRegClass (const TargetRegisterInfo * TRI, MCRegister Reg, TypeT Ty) static
Definition at line 204 of file TargetRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::hasSubClass(), Reg, and TRI.
Referenced by llvm::PPCRegisterInfo::requiresFrameIndexScavenging().
Variable Documentation
HugeSizeForSplit
cl::opt< unsigned > HugeSizeForSplit("huge-size-for-split", cl::Hidden, cl::desc("A threshold of live range size which may cause " "high compile time cost in global splitting."), cl::init(5000)) ("huge-size-for-split" , cl::Hidden , cl::desc("A threshold of live range size which may cause " "high compile time cost in global splitting.") , cl::init(5000)) static
Referenced by llvm::TargetRegisterInfo::shouldRegionSplitForVirtReg().