LLVM: lib/Target/Target.cpp File Reference
Target.cpp File Reference
#include "llvm-c/Target.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include <cstring>
Functions
TargetLibraryInfoImpl * unwrap (LLVMTargetLibraryInfoRef P)
LLVMTargetLibraryInfoRef wrap (const TargetLibraryInfoImpl *P)
LLVMTargetDataRef LLVMGetModuleDataLayout (LLVMModuleRef M)
Obtain the data layout for a module.
void LLVMSetModuleDataLayout (LLVMModuleRef M, LLVMTargetDataRef DL)
Set the data layout for a module.
LLVMTargetDataRef LLVMCreateTargetData (const char *StringRep)
Creates target data from a target layout string.
void LLVMDisposeTargetData (LLVMTargetDataRef TD)
Deallocates a TargetData.
void LLVMAddTargetLibraryInfo (LLVMTargetLibraryInfoRef TLI, LLVMPassManagerRef PM)
Adds target library information to a pass manager.
char * LLVMCopyStringRepOfTargetData (LLVMTargetDataRef TD)
Converts target data to a target layout string.
LLVMByteOrdering LLVMByteOrder (LLVMTargetDataRef TD)
Returns the byte order of a target, either LLVMBigEndian or LLVMLittleEndian.
unsigned LLVMPointerSize (LLVMTargetDataRef TD)
Returns the pointer size in bytes for a target.
unsigned LLVMPointerSizeForAS (LLVMTargetDataRef TD, unsigned AS)
Returns the pointer size in bytes for a target for a specified address space.
LLVMTypeRef LLVMIntPtrType (LLVMTargetDataRef TD)
LLVMTypeRef LLVMIntPtrTypeForAS (LLVMTargetDataRef TD, unsigned AS)
LLVMTypeRef LLVMIntPtrTypeInContext (LLVMContextRef C, LLVMTargetDataRef TD)
Returns the integer type that is the same size as a pointer on a target.
LLVMTypeRef LLVMIntPtrTypeForASInContext (LLVMContextRef C, LLVMTargetDataRef TD, unsigned AS)
Returns the integer type that is the same size as a pointer on a target.
unsigned long long LLVMSizeOfTypeInBits (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the size of a type in bits for a target.
unsigned long long LLVMStoreSizeOfType (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the storage size of a type in bytes for a target.
unsigned long long LLVMABISizeOfType (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the ABI size of a type in bytes for a target.
unsigned LLVMABIAlignmentOfType (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the ABI alignment of a type in bytes for a target.
unsigned LLVMCallFrameAlignmentOfType (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the call frame alignment of a type in bytes for a target.
unsigned LLVMPreferredAlignmentOfType (LLVMTargetDataRef TD, LLVMTypeRef Ty)
Computes the preferred alignment of a type in bytes for a target.
unsigned LLVMPreferredAlignmentOfGlobal (LLVMTargetDataRef TD, LLVMValueRef GlobalVar)
Computes the preferred alignment of a global variable in bytes for a target.
unsigned LLVMElementAtOffset (LLVMTargetDataRef TD, LLVMTypeRef StructTy, unsigned long long Offset)
Computes the structure element that contains the byte offset for a target.
unsigned long long LLVMOffsetOfElement (LLVMTargetDataRef TD, LLVMTypeRef StructTy, unsigned Element)
Computes the byte offset of the indexed struct element for a target.
Function Documentation
LLVMIntPtrType()
LLVMTypeRef LLVMIntPtrType (LLVMTargetDataRef TD)
Definition at line 79 of file Target.cpp.
References llvm::getGlobalContextForCAPI(), llvm::unwrap(), and llvm::wrap().
LLVMIntPtrTypeForAS()
LLVMTypeRef LLVMIntPtrTypeForAS (LLVMTargetDataRef TD, unsigned AS)
Definition at line 83 of file Target.cpp.
References llvm::getGlobalContextForCAPI(), llvm::unwrap(), and llvm::wrap().
unwrap()
TargetLibraryInfoImpl * unwrap (LLVMTargetLibraryInfoRef P) inline
Definition at line 26 of file Target.cpp.
References P.
wrap()
LLVMTargetLibraryInfoRef wrap (const TargetLibraryInfoImpl * P) inline
Definition at line 30 of file Target.cpp.
References P, and X.