LLVM: lib/CodeGen/TargetLoweringBase.cpp File Reference
TargetLoweringBase.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RuntimeLibcallUtil.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/CodeGenTypes/MachineValueType.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils/SizeOpts.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <string>
#include <tuple>
#include <utility>
#include "llvm/IR/ConstrainedOps.def"
#include "llvm/IR/VPIntrinsics.def"
#include "llvm/IR/Instruction.def"
Macros
#define LCALLS(A, B)
#define LCALL5(A)
#define OP_TO_LIBCALL(Name, Enum)
#define DAG_INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN)
#define BEGIN_REGISTER_VP_SDNODE(SDOPC, ...)
#define HANDLE_INST(NUM, OPCODE, CLASS)
#define LAST_OTHER_INST(NUM)
Functions
static unsigned getVectorTypeBreakdownMVT (MVT VT, MVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT, TargetLoweringBase *TLI)
static StringRef getRecipEstimateForFunc (MachineFunction &MF)
Get the reciprocal estimate attribute string for a function that will override the target defaults.
static std::string getReciprocalOpName (bool IsSqrt, EVT VT)
Construct a string for the given reciprocal operation of the given type.
static bool parseRefinementStep (StringRef In, size_t &Position, uint8_t &Value)
Return the character position and value (a single numeric character) of a customized refinement operation in the input string if it exists.
static int getOpEnabled (bool IsSqrt, EVT VT, StringRef Override)
For the input attribute string, return one of the ReciprocalEstimate enum status values (enabled, disabled, or not specified) for this operation on the specified data type.
static int getOpRefinementSteps (bool IsSqrt, EVT VT, StringRef Override)
For the input attribute string, return the customized refinement step count for this operation on the specified data type.
Variables
static cl::opt< bool > JumpIsExpensiveOverride ("jump-is-expensive", cl::init(false), cl::desc("Do not create extra branches to split comparison logic."), cl::Hidden)
static cl::opt< unsigned > MinimumJumpTableEntries ("min-jump-table-entries", cl::init(4), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table."))
static cl::opt< unsigned > MaximumJumpTableSize ("max-jump-table-size", cl::init(UINT_MAX), cl::Hidden, cl::desc("Set maximum size of jump tables."))
static cl::opt< unsigned > JumpTableDensity ("jump-table-density", cl::init(10), cl::Hidden, cl::desc("Minimum density for building a jump table in " "a normal function"))
Minimum jump table density for normal functions.
static cl::opt< unsigned > OptsizeJumpTableDensity ("optsize-jump-table-density", cl::init(40), cl::Hidden, cl::desc("Minimum density for building a jump table in " "an optsize function"))
Minimum jump table density for -Os or -Oz functions.
static cl::opt< unsigned > MinimumBitTestCmpsOverride ("min-bit-test-cmps", cl::init(2), cl::Hidden, cl::desc("Set minimum of largest number of comparisons " "to use bit test for switch."))
static cl::opt< unsigned > MaxStoresPerMemsetOverride ("max-store-memset", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemset and " "MaxStoresPerMemsetOptSize. " "Set to 0 to use the target default."))
static cl::opt< unsigned > MaxStoresPerMemcpyOverride ("max-store-memcpy", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemcpy and " "MaxStoresPerMemcpyOptSize. " "Set to 0 to use the target default."))
static cl::opt< unsigned > MaxStoresPerMemmoveOverride ("max-store-memmove", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemmove and " "MaxStoresPerMemmoveOptSize. " "Set to 0 to use the target default."))
static cl::opt< bool > DisableStrictNodeMutation ("disable-strictnode-mutation", cl::desc("Don't mutate strict-float node to a legalize node"), cl::init(false), cl::Hidden)
Macro Definition Documentation
BEGIN_REGISTER_VP_SDNODE
#define BEGIN_REGISTER_VP_SDNODE (SDOPC, ...)
Value:
setOperationAction(ISD::SDOPC, VT, Expand);
DAG_INSTRUCTION
#define DAG_INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN)
Value:
setOperationAction(ISD::STRICT_##DAGN, VT, Expand);
HANDLE_INST
#define HANDLE_INST (NUM, OPCODE, CLASS)
Value:
OPCODE = NUM,
LAST_OTHER_INST
#define LAST_OTHER_INST (NUM)
Value:
InstructionOpcodesCount = NUM
LCALL5
#define LCALL5 (A)
Value:
LCALLS(A, 1), LCALLS(A, 2), LCALLS(A, 4), LCALLS(A, 8), LCALLS(A, 16)
Referenced by llvm::RTLIB::getOUTLINE_ATOMIC().
LCALLS
#define LCALLS (A, B)
Value:
{ A##B##_RELAX, A##B##_ACQ, A##B##_REL, A##B##_ACQ_REL }
OP_TO_LIBCALL
#define OP_TO_LIBCALL (Name, Enum)
Value:
case Name:                                                                   \
  switch (VT.SimpleTy) {                                                     \
  default:                                                                   \
    return UNKNOWN_LIBCALL;                                                  \
  case MVT::i8:                                                              \
    return Enum##_1;                                                         \
  case MVT::i16:                                                             \
    return Enum##_2;                                                         \
  case MVT::i32:                                                             \
    return Enum##_4;                                                         \
  case MVT::i64:                                                             \
    return Enum##_8;                                                         \
  case MVT::i128:                                                            \
    return Enum##_16;                                                        \
  }
Referenced by llvm::RTLIB::getSYNC().
Function Documentation
getOpEnabled()
int getOpEnabled (bool IsSqrt, EVT VT, StringRef Override) static
For the input attribute string, return one of the ReciprocalEstimate enum status values (enabled, disabled, or not specified) for this operation on the specified data type.
Definition at line 2534 of file TargetLoweringBase.cpp.
References llvm::TargetLoweringBase::Disabled, llvm::StringRef::empty(), llvm::TargetLoweringBase::Enabled, getReciprocalOpName(), parseRefinementStep(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::split(), llvm::StringRef::substr(), and llvm::TargetLoweringBase::Unspecified.
Referenced by llvm::TargetLoweringBase::getRecipEstimateDivEnabled(), and llvm::TargetLoweringBase::getRecipEstimateSqrtEnabled().
getOpRefinementSteps()
int getOpRefinementSteps (bool IsSqrt, EVT VT, StringRef Override) static
For the input attribute string, return the customized refinement step count for this operation on the specified data type.
If the step count does not exist, return the ReciprocalEstimate enum value for unspecified.
Definition at line 2594 of file TargetLoweringBase.cpp.
References assert(), llvm::StringRef::empty(), getReciprocalOpName(), parseRefinementStep(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::split(), llvm::StringRef::substr(), and llvm::TargetLoweringBase::Unspecified.
Referenced by llvm::TargetLoweringBase::getDivRefinementSteps(), and llvm::TargetLoweringBase::getSqrtRefinementSteps().
getRecipEstimateForFunc()
StringRef getRecipEstimateForFunc (MachineFunction & MF) static
Get the reciprocal estimate attribute string for a function that will override the target defaults.
Definition at line 2480 of file TargetLoweringBase.cpp.
References F, and llvm::MachineFunction::getFunction().
Referenced by llvm::TargetLoweringBase::getDivRefinementSteps(), llvm::TargetLoweringBase::getRecipEstimateDivEnabled(), llvm::TargetLoweringBase::getRecipEstimateSqrtEnabled(), and llvm::TargetLoweringBase::getSqrtRefinementSteps().
getReciprocalOpName()
std::string getReciprocalOpName (bool IsSqrt, EVT VT) static
Construct a string for the given reciprocal operation of the given type.
This string should match the corresponding option to the front-end's "-mrecip" flag assuming those strings have been passed through in an attribute string. For example, "vec-divf" for a division of a vXf32.
Definition at line 2489 of file TargetLoweringBase.cpp.
References assert(), llvm::EVT::getScalarType(), and llvm::EVT::isVector().
Referenced by getOpEnabled(), and getOpRefinementSteps().
getVectorTypeBreakdownMVT()
unsigned getVectorTypeBreakdownMVT (MVT VT, MVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT, TargetLoweringBase * TLI) static
Definition at line 1467 of file TargetLoweringBase.cpp.
References llvm::bit_ceil(), llvm::ElementCount::getFixed(), llvm::TargetLoweringBase::getRegisterType(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorElementCount(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::isPowerOf2_32(), llvm::MVT::isScalableVector(), llvm::TargetLoweringBase::isTypeLegal(), and llvm_unreachable.
Referenced by llvm::TargetLoweringBase::computeRegisterProperties().
parseRefinementStep()
bool parseRefinementStep (StringRef In, size_t & Position, uint8_t & Value) static
Return the character position and value (a single numeric character) of a customized refinement operation in the input string if it exists.
Return false if there is no customized refinement step count.
Definition at line 2511 of file TargetLoweringBase.cpp.
References isDigit(), llvm::StringRef::npos, llvm::report_fatal_error(), and llvm::StringRef::size().
Referenced by getOpEnabled(), and getOpRefinementSteps().
Variable Documentation
DisableStrictNodeMutation
cl::opt< bool > DisableStrictNodeMutation("disable-strictnode-mutation", cl::desc("Don't mutate strict-float node to a legalize node"), cl::init(false), cl::Hidden) ("disable-strictnode-mutation" , cl::desc("Don't mutate strict-float node to a legalize node") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetLoweringBase::TargetLoweringBase().
JumpIsExpensiveOverride
cl::opt< bool > JumpIsExpensiveOverride("jump-is-expensive", cl::init(false), cl::desc("Do not create extra branches to split comparison logic."), cl::Hidden) ("jump-is-expensive" , cl::init(false) , cl::desc("Do not create extra branches to split comparison logic.") , cl::Hidden) static
Referenced by llvm::TargetLoweringBase::setJumpIsExpensive(), and llvm::TargetLoweringBase::TargetLoweringBase().
JumpTableDensity
cl::opt< unsigned > JumpTableDensity("jump-table-density", cl::init(10), cl::Hidden, cl::desc("Minimum density for building a jump table in " "a normal function")) ("jump-table-density" , cl::init(10) , cl::Hidden , cl::desc("Minimum density for building a jump table in " "a normal function")) static
Minimum jump table density for normal functions.
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableDensity().
MaximumJumpTableSize
cl::opt< unsigned > MaximumJumpTableSize("max-jump-table-size", cl::init(UINT_MAX), cl::Hidden, cl::desc("Set maximum size of jump tables.")) ("max-jump-table-size" , cl::init(UINT_MAX) , cl::Hidden , cl::desc("Set maximum size of jump tables.")) static
Referenced by llvm::TargetLoweringBase::getMaximumJumpTableSize(), and llvm::TargetLoweringBase::setMaximumJumpTableSize().
MaxStoresPerMemcpyOverride
cl::opt< unsigned > MaxStoresPerMemcpyOverride("max-store-memcpy", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemcpy and " "MaxStoresPerMemcpyOptSize. " "Set to 0 to use the target default.")) ("max-store-memcpy" , cl::init(0) , cl::Hidden , cl::desc("Override target's MaxStoresPerMemcpy and " "MaxStoresPerMemcpyOptSize. " "Set to 0 to use the target default.")) static
Referenced by llvm::TargetLoweringBase::getMaxStoresPerMemcpy().
MaxStoresPerMemmoveOverride
cl::opt< unsigned > MaxStoresPerMemmoveOverride("max-store-memmove", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemmove and " "MaxStoresPerMemmoveOptSize. " "Set to 0 to use the target default.")) ("max-store-memmove" , cl::init(0) , cl::Hidden , cl::desc("Override target's MaxStoresPerMemmove and " "MaxStoresPerMemmoveOptSize. " "Set to 0 to use the target default.")) static
Referenced by llvm::TargetLoweringBase::getMaxStoresPerMemmove().
MaxStoresPerMemsetOverride
cl::opt< unsigned > MaxStoresPerMemsetOverride("max-store-memset", cl::init(0), cl::Hidden, cl::desc("Override target's MaxStoresPerMemset and " "MaxStoresPerMemsetOptSize. " "Set to 0 to use the target default.")) ("max-store-memset" , cl::init(0) , cl::Hidden , cl::desc("Override target's MaxStoresPerMemset and " "MaxStoresPerMemsetOptSize. " "Set to 0 to use the target default.")) static
Referenced by llvm::TargetLoweringBase::getMaxStoresPerMemset().
MinimumBitTestCmpsOverride
cl::opt< unsigned > MinimumBitTestCmpsOverride("min-bit-test-cmps", cl::init(2), cl::Hidden, cl::desc("Set minimum of largest number of comparisons " "to use bit test for switch.")) ("min-bit-test-cmps" , cl::init(2) , cl::Hidden , cl::desc("Set minimum of largest number of comparisons " "to use bit test for switch.")) static
Referenced by llvm::TargetLoweringBase::TargetLoweringBase().
MinimumJumpTableEntries
cl::opt< unsigned > MinimumJumpTableEntries("min-jump-table-entries", cl::init(4), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table.")) ("min-jump-table-entries" , cl::init(4) , cl::Hidden , cl::desc("Set minimum number of entries to use a jump table.")) static
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableEntries(), and llvm::TargetLoweringBase::setMinimumJumpTableEntries().
OptsizeJumpTableDensity
cl::opt< unsigned > OptsizeJumpTableDensity("optsize-jump-table-density", cl::init(40), cl::Hidden, cl::desc("Minimum density for building a jump table in " "an optsize function")) ("optsize-jump-table-density" , cl::init(40) , cl::Hidden , cl::desc("Minimum density for building a jump table in " "an optsize function")) static
Minimum jump table density for -Os or -Oz functions.
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableDensity().