LLVM: lib/TargetParser/TargetDataLayout.cpp File Reference
TargetDataLayout.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/TargetParser/ARMTargetParser.h"
#include "llvm/TargetParser/Triple.h"
#include <cstring>
Functions
static StringRef getManglingComponent (const Triple &T)
static std::string computeARMDataLayout (const Triple &TT, StringRef ABIName)
static std::string computeAArch64DataLayout (const Triple &TT)
static std::string computeBPFDataLayout (const Triple &TT)
static std::string computeCSKYDataLayout (const Triple &TT)
static std::string computeLoongArchDataLayout (const Triple &TT)
static std::string computeM68kDataLayout (const Triple &TT)
static MipsABI getMipsABI (const Triple &TT, StringRef ABIName)
static std::string computeMipsDataLayout (const Triple &TT, StringRef ABIName)
static std::string computePowerDataLayout (const Triple &T, StringRef ABIName)
static std::string computeAMDDataLayout (const Triple &TT)
static std::string computeRISCVDataLayout (const Triple &TT, StringRef ABIName)
static std::string computeSparcDataLayout (const Triple &T)
static std::string computeSystemZDataLayout (const Triple &TT)
static std::string computeX86DataLayout (const Triple &TT)
static std::string computeNVPTXDataLayout (const Triple &T, StringRef ABIName)
static std::string computeSPIRVDataLayout (const Triple &TT)
static std::string computeLanaiDataLayout ()
static std::string computeWebAssemblyDataLayout (const Triple &TT)
static std::string computeVEDataLayout (const Triple &T)
Function Documentation
computeAArch64DataLayout()
std::string computeAArch64DataLayout (const Triple & TT) static
Definition at line 83 of file TargetDataLayout.cpp.
References llvm::Triple::aarch64_32, and llvm::Triple::GNUILP32.
Referenced by llvm::Triple::computeDataLayout().
computeAMDDataLayout()
std::string computeAMDDataLayout (const Triple & TT) static
Definition at line 263 of file TargetDataLayout.cpp.
References llvm::Triple::r600.
Referenced by llvm::Triple::computeDataLayout().
computeARMDataLayout()
std::string computeARMDataLayout (const Triple & TT, StringRef ABIName) static
Definition at line 28 of file TargetDataLayout.cpp.
References llvm::ARM::ARM_ABI_AAPCS, llvm::ARM::ARM_ABI_AAPCS16, llvm::ARM::ARM_ABI_APCS, llvm::ARM::computeTargetABI(), and getManglingComponent().
Referenced by llvm::Triple::computeDataLayout().
computeBPFDataLayout()
std::string computeBPFDataLayout (const Triple & TT) static
Definition at line 102 of file TargetDataLayout.cpp.
References llvm::Triple::bpfeb.
Referenced by llvm::Triple::computeDataLayout().
computeCSKYDataLayout()
std::string computeCSKYDataLayout (const Triple & TT) static
Definition at line 109 of file TargetDataLayout.cpp.
Referenced by llvm::Triple::computeDataLayout().
computeLanaiDataLayout()
std::string computeLanaiDataLayout () static
Definition at line 486 of file TargetDataLayout.cpp.
Referenced by llvm::Triple::computeDataLayout().
computeLoongArchDataLayout()
std::string computeLoongArchDataLayout (const Triple & TT) static
Definition at line 118 of file TargetDataLayout.cpp.
References assert().
Referenced by llvm::Triple::computeDataLayout().
computeM68kDataLayout()
std::string computeM68kDataLayout (const Triple & TT) static
Definition at line 125 of file TargetDataLayout.cpp.
Referenced by llvm::Triple::computeDataLayout().
computeMipsDataLayout()
std::string computeMipsDataLayout (const Triple & TT, StringRef ABIName) static
Definition at line 177 of file TargetDataLayout.cpp.
References getMipsABI().
Referenced by llvm::Triple::computeDataLayout().
computeNVPTXDataLayout()
std::string computeNVPTXDataLayout (const Triple & T, StringRef ABIName) static
Definition at line 443 of file TargetDataLayout.cpp.
References llvm::Triple::nvptx64, and T.
Referenced by llvm::Triple::computeDataLayout().
computePowerDataLayout()
std::string computePowerDataLayout (const Triple & T, StringRef ABIName) static
Definition at line 211 of file TargetDataLayout.cpp.
References getManglingComponent(), is64Bit(), llvm::Triple::Lv2, llvm::Triple::ppc64, and T.
Referenced by llvm::Triple::computeDataLayout().
computeRISCVDataLayout()
std::string computeRISCVDataLayout (const Triple & TT, StringRef ABIName) static
Definition at line 282 of file TargetDataLayout.cpp.
References assert().
Referenced by llvm::Triple::computeDataLayout().
computeSparcDataLayout()
std::string computeSparcDataLayout (const Triple & T) static
Definition at line 321 of file TargetDataLayout.cpp.
References llvm::Triple::sparcel, and T.
Referenced by llvm::Triple::computeDataLayout().
computeSPIRVDataLayout()
std::string computeSPIRVDataLayout (const Triple & TT) static
Definition at line 462 of file TargetDataLayout.cpp.
References llvm::Triple::AMD, llvm::Triple::AMDHSA, llvm::Triple::Intel, llvm::Triple::spirv, and llvm::Triple::spirv32.
Referenced by llvm::Triple::computeDataLayout().
computeSystemZDataLayout()
std::string computeSystemZDataLayout (const Triple & TT) static
Definition at line 354 of file TargetDataLayout.cpp.
References getManglingComponent().
Referenced by llvm::Triple::computeDataLayout().
computeVEDataLayout()
std::string computeVEDataLayout (const Triple & T) static
Definition at line 509 of file TargetDataLayout.cpp.
References T.
Referenced by llvm::Triple::computeDataLayout().
computeWebAssemblyDataLayout()
std::string computeWebAssemblyDataLayout (const Triple & TT) static
Definition at line 497 of file TargetDataLayout.cpp.
References llvm::Triple::wasm64.
Referenced by llvm::Triple::computeDataLayout().
computeX86DataLayout()
std::string computeX86DataLayout (const Triple & TT) static
Definition at line 393 of file TargetDataLayout.cpp.
References getManglingComponent().
Referenced by llvm::Triple::computeDataLayout().
getManglingComponent()
StringRef getManglingComponent (const Triple & T) static
Definition at line 16 of file TargetDataLayout.cpp.
References T, and llvm::Triple::x86.
Referenced by computeARMDataLayout(), computePowerDataLayout(), computeSystemZDataLayout(), and computeX86DataLayout().
getMipsABI()
MipsABI getMipsABI (const Triple & TT, StringRef ABIName) static
Definition at line 161 of file TargetDataLayout.cpp.
References assert(), llvm::StringRef::empty(), and llvm::StringRef::starts_with().
Referenced by computeMipsDataLayout().