LLVM: lib/TargetParser/TargetParser.cpp File Reference
TargetParser.cpp File Reference
#include "llvm/TargetParser/TargetParser.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/TargetParser/Triple.h"
Functions
static const BasicSubtargetSubTypeKV * find (StringRef S, ArrayRef< BasicSubtargetSubTypeKV > A)
Find KV in array using binary search.
static void setImpliedBits (FeatureBitset &Bits, const FeatureBitset &Implies, ArrayRef< BasicSubtargetFeatureKV > FeatureTable)
For each feature that is (transitively) implied by this feature, set it.
static std::pair< FeatureError, StringRef > insertWaveSizeFeature (StringRef GPU, const Triple &T, const StringMap< bool > &DefaultFeatures, StringMap< bool > &Features)
static void fillAMDGCNFeatureMap (StringRef GPU, const Triple &T, StringMap< bool > &Features)
Fills Features map with default values for given target GPU.
Function Documentation
fillAMDGCNFeatureMap()
void fillAMDGCNFeatureMap (StringRef GPU, const Triple & T, StringMap< bool > & Features) static
Fills Features map with default values for given target GPU.
Features contains overriding target features and this function returns default target features with entries overridden by Features.
Definition at line 405 of file TargetParser.cpp.
References llvm::AMDGPU::GK_GFX1010, llvm::AMDGPU::GK_GFX1011, llvm::AMDGPU::GK_GFX1012, llvm::AMDGPU::GK_GFX1013, llvm::AMDGPU::GK_GFX1030, llvm::AMDGPU::GK_GFX1031, llvm::AMDGPU::GK_GFX1032, llvm::AMDGPU::GK_GFX1033, llvm::AMDGPU::GK_GFX1034, llvm::AMDGPU::GK_GFX1035, llvm::AMDGPU::GK_GFX1036, llvm::AMDGPU::GK_GFX10_1_GENERIC, llvm::AMDGPU::GK_GFX10_3_GENERIC, llvm::AMDGPU::GK_GFX1100, llvm::AMDGPU::GK_GFX1101, llvm::AMDGPU::GK_GFX1102, llvm::AMDGPU::GK_GFX1103, llvm::AMDGPU::GK_GFX1150, llvm::AMDGPU::GK_GFX1151, llvm::AMDGPU::GK_GFX1152, llvm::AMDGPU::GK_GFX1153, llvm::AMDGPU::GK_GFX11_GENERIC, llvm::AMDGPU::GK_GFX1200, llvm::AMDGPU::GK_GFX1201, llvm::AMDGPU::GK_GFX1250, llvm::AMDGPU::GK_GFX1251, llvm::AMDGPU::GK_GFX12_GENERIC, llvm::AMDGPU::GK_GFX600, llvm::AMDGPU::GK_GFX601, llvm::AMDGPU::GK_GFX602, llvm::AMDGPU::GK_GFX700, llvm::AMDGPU::GK_GFX701, llvm::AMDGPU::GK_GFX702, llvm::AMDGPU::GK_GFX703, llvm::AMDGPU::GK_GFX704, llvm::AMDGPU::GK_GFX705, llvm::AMDGPU::GK_GFX801, llvm::AMDGPU::GK_GFX802, llvm::AMDGPU::GK_GFX803, llvm::AMDGPU::GK_GFX805, llvm::AMDGPU::GK_GFX810, llvm::AMDGPU::GK_GFX900, llvm::AMDGPU::GK_GFX902, llvm::AMDGPU::GK_GFX904, llvm::AMDGPU::GK_GFX906, llvm::AMDGPU::GK_GFX908, llvm::AMDGPU::GK_GFX909, llvm::AMDGPU::GK_GFX90A, llvm::AMDGPU::GK_GFX90C, llvm::AMDGPU::GK_GFX942, llvm::AMDGPU::GK_GFX950, llvm::AMDGPU::GK_GFX9_4_GENERIC, llvm::AMDGPU::GK_GFX9_GENERIC, llvm::AMDGPU::GK_NONE, llvm_unreachable, llvm::AMDGPU::parseArchAMDGCN(), and T.
Referenced by llvm::AMDGPU::fillAMDGPUFeatureMap().
find()
const BasicSubtargetSubTypeKV * find (StringRef S, ArrayRef< BasicSubtargetSubTypeKV > A) static
Find KV in array using binary search.
Definition at line 23 of file TargetParser.cpp.
References A(), F, and llvm::lower_bound().
Referenced by llvm::StringMap< EmptyStringSetTag, AllocatorTy >::at(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::contains(), llvm::StringRef::contains(), llvm::StringRef::detectEOL(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::erase(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::find(), llvm::StringRef::find_first_of(), llvm::IntervalMap< IndexT, char >::insert(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::lookup(), llvm::IntervalMap< IndexT, char >::overlaps(), llvm::VPValue::removeUser(), and llvm::StringRef::split().
insertWaveSizeFeature()
std::pair< FeatureError, StringRef > insertWaveSizeFeature (StringRef GPU, const Triple & T, const StringMap< bool > & DefaultFeatures, StringMap< bool > & Features) static
Definition at line 370 of file TargetParser.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::StringRef::empty(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::AMDGPU::INVALID_FEATURE_COMBINATION, llvm::AMDGPU::NO_ERROR, T, and llvm::AMDGPU::UNSUPPORTED_TARGET_FEATURE.
Referenced by llvm::AMDGPU::fillAMDGPUFeatureMap().
setImpliedBits()
void setImpliedBits (FeatureBitset & Bits, const FeatureBitset & Implies, ArrayRef< BasicSubtargetFeatureKV > FeatureTable) static
For each feature that is (transitively) implied by this feature, set it.
Definition at line 34 of file TargetParser.cpp.
References setImpliedBits(), and llvm::FeatureBitset::test().
Referenced by llvm::getCPUDefaultTargetFeatures(), and setImpliedBits().