LLVM: lib/Support/TarWriter.cpp File Reference
TarWriter.cpp File Reference
#include "llvm/Support/TarWriter.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
Classes
struct UstarHeader
Functions
static UstarHeader makeUstarHeader ()
static std::string formatPax (StringRef Key, StringRef Val)
static void pad (raw_fd_ostream &OS)
static void computeChecksum (UstarHeader &Hdr)
static void writePaxHeader (raw_fd_ostream &OS, StringRef Path)
static bool splitUstar (StringRef Path, StringRef &Prefix, StringRef &Name)
static void writeUstarHeader (raw_fd_ostream &OS, StringRef Prefix, StringRef Name, size_t Size)
Variables
static const int BlockSize = 512
Function Documentation
computeChecksum()
void computeChecksum (UstarHeader & Hdr) static
Definition at line 88 of file TarWriter.cpp.
References UstarHeader::Checksum, and I.
Referenced by writePaxHeader(), and writeUstarHeader().
formatPax()
std::string formatPax (StringRef Key, StringRef Val) static
Definition at line 70 of file TarWriter.cpp.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::StringRef::size(), llvm::Twine::str(), and llvm::Total.
Referenced by writePaxHeader().
makeUstarHeader()
UstarHeader makeUstarHeader () static
Definition at line 56 of file TarWriter.cpp.
References UstarHeader::Magic, and UstarHeader::Version.
Referenced by writePaxHeader(), and writeUstarHeader().
pad()
void pad (raw_fd_ostream & OS) static
Definition at line 82 of file TarWriter.cpp.
References llvm::alignTo(), BlockSize, llvm::raw_fd_ostream::seek(), and llvm::raw_ostream::tell().
Referenced by llvm::TarWriter::append(), and writePaxHeader().
splitUstar()
bool splitUstar (StringRef Path, StringRef & Prefix, StringRef & Name) static
Definition at line 127 of file TarWriter.cpp.
References UstarHeader::Name, and llvm::StringRef::npos.
Referenced by llvm::TarWriter::append().
writePaxHeader()
void writePaxHeader (raw_fd_ostream & OS, StringRef Path) static
Definition at line 101 of file TarWriter.cpp.
References computeChecksum(), formatPax(), makeUstarHeader(), pad(), UstarHeader::Size, and UstarHeader::TypeFlag.
Referenced by llvm::TarWriter::append().
writeUstarHeader()
void writeUstarHeader (raw_fd_ostream & OS, StringRef Prefix, StringRef Name, size_t Size) static
Definition at line 157 of file TarWriter.cpp.
References computeChecksum(), makeUstarHeader(), UstarHeader::Mode, UstarHeader::Name, UstarHeader::Prefix, Size, and UstarHeader::Size.
Referenced by llvm::TarWriter::append().
Variable Documentation
BlockSize
const int BlockSize = 512 static
Definition at line 33 of file TarWriter.cpp.
Referenced by llvm::TarWriter::append(), assignSlotsUsingVGPRBlocks(), llvm::msf::blockToOffset(), llvm::msf::bytesToBlocks(), computeBlockRuns(), llvm::msf::WritableMappedBlockStream::createStream(), CreateVPTBlock(), llvm::MachineFunction::estimateFunctionSizeInBytes(), llvm::AMDGPU::getDynamicVGPRBlockSize(), GetInitialBlockMask(), llvm::msf::getNumFpmIntervals(), slpvectorizer::BoUpSLP::getSpillCost(), llvm::pdb::PDBFileBuilder::initialize(), llvm::isREVMask(), llvm::isVREVMask(), isWideDUPMask(), llvm::pdb::PDBFileBuilder::operator=(), pad(), and llvm::msf::WritableMappedBlockStream::WritableMappedBlockStream().