LLVM: lib/TextAPI/TextStub.cpp File Reference
TextStub.cpp File Reference
#include "TextAPIContext.h"
#include "TextStubCommon.h"
#include "llvm/ADT/BitmaskEnum.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TextAPI/Architecture.h"
#include "llvm/TextAPI/ArchitectureSet.h"
#include "llvm/TextAPI/InterfaceFile.h"
#include "llvm/TextAPI/PackedVersion.h"
#include "llvm/TextAPI/TextAPIReader.h"
#include "llvm/TextAPI/TextAPIWriter.h"
#include <set>
#include "llvm/BinaryFormat/MachO.def"
Classes
struct llvm::yaml::MappingTraits< ExportSection >
struct llvm::yaml::MappingTraits< UndefinedSection >
struct llvm::yaml::MappingTraits< SymbolSection >
struct llvm::yaml::MappingTraits< UmbrellaSection >
struct llvm::yaml::MappingTraits< UUIDv4 >
struct llvm::yaml::MappingContextTraits< MetadataSection, MetadataSection::Option >
struct llvm::yaml::ScalarBitSetTraits< TBDFlags >
struct llvm::yaml::ScalarTraits< Target >
struct llvm::yaml::MappingTraits< const InterfaceFile * >
struct llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD
struct llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4
struct llvm::yaml::DocumentListTraits< std::vector< const MachO::InterfaceFile * > >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Macros
#define PLATFORM(platform, id, name, build_name, target, tapi_target, marketing)
Functions
static void DiagHandler (const SMDiagnostic &Diag, void *Context)
Macro Definition Documentation
PLATFORM
#define PLATFORM (platform, id, name, build_name, target, tapi_target, marketing)
Value:
case PLATFORM_##platform:                                                    \
  OS << #tapi_target;                                                        \
  break;
Function Documentation
DiagHandler()
void DiagHandler (const SMDiagnostic & Diag, void * Context) static
Definition at line 1059 of file TextStub.cpp.
References llvm::SMDiagnostic::getColumnNo(), llvm::SMDiagnostic::getFixIts(), llvm::SMDiagnostic::getKind(), llvm::SMDiagnostic::getLineContents(), llvm::SMDiagnostic::getLineNo(), llvm::SMDiagnostic::getLoc(), llvm::SMDiagnostic::getMessage(), llvm::SMDiagnostic::getRanges(), llvm::SMDiagnostic::getSourceMgr(), and llvm::SMDiagnostic::print().
Referenced by llvm::vfs::RedirectingFileSystem::create(), llvm::MachO::TextAPIReader::get(), llvm::vfs::getVFSFromYAML(), llvm::yaml::Input::Input(), and llvm::yaml::Input::Input().