LLVM: lib/TableGen/TGParser.cpp File Reference
TGParser.cpp File Reference
#include "TGParser.h"
#include "TGLexer.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <limits>
Classes
struct llvm::SubClassReference
struct llvm::SubMultiClassReference
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static bool checkBitsConcrete (Record &R, const RecordVal &RV)
static void checkConcrete (Record &R)
static const Init * QualifyName (const Record &CurRec, const Init *Name)
Return an Init with a qualifier prefix referring to CurRec's name.
static const Init * QualifyName (MultiClass *MC, const Init *Name)
static const Init * QualifiedNameOfImplicitName (const Record &Rec)
Return the qualified version of the implicit 'NAME' template argument.
static const Init * QualifiedNameOfImplicitName (MultiClass *MC)
Function Documentation
checkBitsConcrete()
bool checkBitsConcrete (Record & R, const RecordVal & RV) static
Definition at line 77 of file TGParser.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::RecordVal::getValue(), and llvm::isa().
Referenced by checkConcrete().
checkConcrete()
void checkConcrete (Record & R) static
Definition at line 96 of file TGParser.cpp.
References checkBitsConcrete(), llvm::isa(), and llvm::PrintError().
QualifiedNameOfImplicitName() [1/2]
const Init * QualifiedNameOfImplicitName (const Record & Rec) static
Return the qualified version of the implicit 'NAME' template argument.
Definition at line 137 of file TGParser.cpp.
References llvm::StringInit::get(), llvm::Record::getRecords(), and QualifyName().
Referenced by QualifiedNameOfImplicitName().
QualifiedNameOfImplicitName() [2/2]
const Init * QualifiedNameOfImplicitName (MultiClass * MC) static
Definition at line 141 of file TGParser.cpp.
References QualifiedNameOfImplicitName(), and llvm::MultiClass::Rec.
QualifyName() [1/2]
const Init * QualifyName (const Record & CurRec, const Init * Name) static
Return an Init with a qualifier prefix referring to CurRec's name.
Definition at line 120 of file TGParser.cpp.
References llvm::dyn_cast(), llvm::StringInit::get(), llvm::Record::getNameInit(), llvm::Record::getRecords(), llvm::BinOpInit::getStrConcat(), and llvm::Record::isMultiClass().
Referenced by llvm::TGVarScope::getVar(), QualifiedNameOfImplicitName(), and QualifyName().
QualifyName() [2/2]
const Init * QualifyName (MultiClass * MC, const Init * Name) static
Definition at line 132 of file TGParser.cpp.
References QualifyName(), and llvm::MultiClass::Rec.