LLVM: lib/LTO/ThinLTOCodeGenerator.cpp File Reference
ThinLTOCodeGenerator.cpp File Reference
#include "llvm/LTO/legacy/ThinLTOCodeGenerator.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/Bitcode/BitcodeWriterPass.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/PassTimingInfo.h"
#include "llvm/IR/Verifier.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/LTO/LTO.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/Remarks/HotnessThresholdParser.h"
#include "llvm/Support/CachePruning.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SHA1.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/SubtargetFeature.h"
#include "llvm/Transforms/IPO/FunctionAttrs.h"
#include "llvm/Transforms/IPO/FunctionImport.h"
#include "llvm/Transforms/IPO/Internalize.h"
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
#include <unistd.h>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "thinlto"
Functions
static void saveTempBitcode (const Module &TheModule, StringRef TempDir, unsigned count, StringRef Suffix)
static const GlobalValueSummary * getFirstDefinitionForLinker (ArrayRef< std::unique_ptr< GlobalValueSummary > > GVSummaryList)
static void computePrevailingCopies (const ModuleSummaryIndex &Index, DenseMap< GlobalValue::GUID, const GlobalValueSummary * > &PrevailingCopy)
static StringMap< lto::InputFile * > generateModuleMap (std::vector< std::unique_ptr< lto::InputFile > > &Modules)
static void promoteModule (Module &TheModule, const ModuleSummaryIndex &Index, bool ClearDSOLocalOnDeclarations)
static void verifyLoadedModule (Module &TheModule)
Verify the module and strip broken debug info.
static std::unique_ptr< Module > loadModuleFromInput (lto::InputFile *Input, LLVMContext &Context, bool Lazy, bool IsImporting)
static void crossImportIntoModule (Module &TheModule, const ModuleSummaryIndex &Index, StringMap< lto::InputFile * > &ModuleMap, const FunctionImporter::ImportMapTy &ImportList, bool ClearDSOLocalOnDeclarations)
static void optimizeModule (Module &TheModule, TargetMachine &TM, unsigned OptLevel, bool Freestanding, bool DebugPassManager, ModuleSummaryIndex *Index)
static void addUsedSymbolToPreservedGUID (const lto::InputFile &File, DenseSet< GlobalValue::GUID > &PreservedGUID)
static void computeGUIDPreservedSymbols (const lto::InputFile &File, const StringSet<> &PreservedSymbols, const Triple &TheTriple, DenseSet< GlobalValue::GUID > &GUIDs)
static DenseSet< GlobalValue::GUID > computeGUIDPreservedSymbols (const lto::InputFile &File, const StringSet<> &PreservedSymbols, const Triple &TheTriple)
static std::unique_ptr< MemoryBuffer > codegenModule (Module &TheModule, TargetMachine &TM)
static std::unique_ptr< MemoryBuffer > ProcessThinLTOModule (Module &TheModule, ModuleSummaryIndex &Index, StringMap< lto::InputFile * > &ModuleMap, TargetMachine &TM, const FunctionImporter::ImportMapTy &ImportList, const FunctionImporter::ExportSetTy &ExportList, const DenseSet< GlobalValue::GUID > &GUIDPreservedSymbols, const GVSummaryMapTy &DefinedGlobals, const ThinLTOCodeGenerator::CachingOptions &CacheOptions, bool DisableCodeGen, StringRef SaveTempsDir, bool Freestanding, unsigned OptLevel, unsigned count, bool DebugPassManager)
static void resolvePrevailingInIndex (ModuleSummaryIndex &Index, StringMap< std::map< GlobalValue::GUID, GlobalValue::LinkageTypes > > &ResolvedODR, const DenseSet< GlobalValue::GUID > &GUIDPreservedSymbols, const DenseMap< GlobalValue::GUID, const GlobalValueSummary * > &PrevailingCopy)
Resolve prevailing symbols.
static void initTMBuilder (TargetMachineBuilder &TMBuilder, const Triple &TheTriple)
static void computeDeadSymbolsInIndex (ModuleSummaryIndex &Index, const DenseSet< GlobalValue::GUID > &GUIDPreservedSymbols)
Variables
static cl::opt< int > ThreadCount ("threads", cl::init(0))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "thinlto"
Definition at line 71 of file ThinLTOCodeGenerator.cpp.
Function Documentation
addUsedSymbolToPreservedGUID()
void addUsedSymbolToPreservedGUID (const lto::InputFile & File, DenseSet< GlobalValue::GUID > & PreservedGUID) static
Definition at line 291 of file ThinLTOCodeGenerator.cpp.
References llvm::GlobalValue::getGUIDAssumingExternalLinkage(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
codegenModule()
std::unique_ptr< MemoryBuffer > codegenModule (Module & TheModule, TargetMachine & TM) static
Definition at line 325 of file ThinLTOCodeGenerator.cpp.
References llvm::TargetMachine::addPassesToEmitFile(), llvm::ObjectFile, llvm::report_fatal_error(), and llvm::legacy::PassManager::run().
Referenced by ProcessThinLTOModule(), and llvm::ThinLTOCodeGenerator::run().
computeDeadSymbolsInIndex()
void computeDeadSymbolsInIndex (ModuleSummaryIndex & Index, const DenseSet< GlobalValue::GUID > & GUIDPreservedSymbols) static
Definition at line 650 of file ThinLTOCodeGenerator.cpp.
References llvm::computeDeadSymbolsWithConstProp(), G, and llvm::Unknown.
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
computeGUIDPreservedSymbols() [1/2]
DenseSet< GlobalValue::GUID > computeGUIDPreservedSymbols (const lto::InputFile & File, const StringSet<> & PreservedSymbols, const Triple & TheTriple) static
Definition at line 316 of file ThinLTOCodeGenerator.cpp.
References computeGUIDPreservedSymbols(), and llvm::StringMapImpl::size().
computeGUIDPreservedSymbols() [2/2]
void computeGUIDPreservedSymbols (const lto::InputFile & File, const StringSet<> & PreservedSymbols, const Triple & TheTriple, DenseSet< GlobalValue::GUID > & GUIDs) static
Definition at line 301 of file ThinLTOCodeGenerator.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::getGlobalIdentifier(), llvm::GlobalValue::getGUIDAssumingExternalLinkage(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by computeGUIDPreservedSymbols(), llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
computePrevailingCopies()
void computePrevailingCopies (const ModuleSummaryIndex & Index, DenseMap< GlobalValue::GUID, const GlobalValueSummary * > & PrevailingCopy) static
Definition at line 131 of file ThinLTOCodeGenerator.cpp.
References getFirstDefinitionForLinker(), and I.
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
crossImportIntoModule()
void crossImportIntoModule (Module & TheModule, const ModuleSummaryIndex & Index, StringMap< lto::InputFile * > & ModuleMap, const FunctionImporter::ImportMapTy & ImportList, bool ClearDSOLocalOnDeclarations) static
Definition at line 210 of file ThinLTOCodeGenerator.cpp.
References llvm::Module::getContext(), llvm::handleAllErrors(), llvm::FunctionImporter::importFunctions(), loadModuleFromInput(), llvm::report_fatal_error(), and verifyLoadedModule().
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), and ProcessThinLTOModule().
generateModuleMap()
StringMap< lto::InputFile * > generateModuleMap (std::vector< std::unique_ptr< lto::InputFile > > & Modules) static
Definition at line 147 of file ThinLTOCodeGenerator.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::contains(), llvm::dbgs(), and LLVM_DEBUG.
Referenced by llvm::ThinLTOCodeGenerator::crossModuleImport(), and llvm::ThinLTOCodeGenerator::run().
getFirstDefinitionForLinker()
const GlobalValueSummary * getFirstDefinitionForLinker (ArrayRef< std::unique_ptr< GlobalValueSummary > > GVSummaryList) static
Definition at line 104 of file ThinLTOCodeGenerator.cpp.
References llvm::find_if(), llvm::GlobalValue::isAvailableExternallyLinkage(), llvm::GlobalValue::isWeakForLinker(), and Linkage.
Referenced by computePrevailingCopies().
initTMBuilder()
void initTMBuilder (TargetMachineBuilder & TMBuilder, const Triple & TheTriple) static
Definition at line 535 of file ThinLTOCodeGenerator.cpp.
References llvm::lto::getThinLTODefaultCPU(), llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::MCpu, and llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::TheTriple.
Referenced by llvm::ThinLTOCodeGenerator::addModule(), llvm::ThinLTOCodeGenerator::internalize(), and llvm::ThinLTOCodeGenerator::optimize().
loadModuleFromInput()
std::unique_ptr< Module > loadModuleFromInput (lto::InputFile * Input, LLVMContext & Context, bool Lazy, bool IsImporting) static
Definition at line 186 of file ThinLTOCodeGenerator.cpp.
References llvm::Expected< T >::get(), llvm::handleAllErrors(), Mod, llvm::report_fatal_error(), llvm::Expected< T >::takeError(), and verifyLoadedModule().
Referenced by crossImportIntoModule(), and llvm::ThinLTOCodeGenerator::run().
optimizeModule()
void optimizeModule (Module & TheModule, TargetMachine & TM, unsigned OptLevel, bool Freestanding, bool DebugPassManager, ModuleSummaryIndex * Index) static
Definition at line 234 of file ThinLTOCodeGenerator.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), CGAM, FAM, llvm::Module::getContext(), llvm::TargetMachine::getTargetTriple(), LAM, llvm_unreachable, llvm::PipelineTuningOptions::LoopVectorization, MAM, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O1, llvm::OptimizationLevel::O2, llvm::OptimizationLevel::O3, llvm::TargetMachine::Options, PB(), PIC, llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PipelineTuningOptions::SLPVectorization, and llvm::TargetOptions::VecLib.
Referenced by llvm::ThinLTOCodeGenerator::optimize(), and ProcessThinLTOModule().
ProcessThinLTOModule()
std::unique_ptr< MemoryBuffer > ProcessThinLTOModule (Module & TheModule, ModuleSummaryIndex & Index, StringMap< lto::InputFile * > & ModuleMap, TargetMachine & TM, const FunctionImporter::ImportMapTy & ImportList, const FunctionImporter::ExportSetTy & ExportList, const DenseSet< GlobalValue::GUID > & GUIDPreservedSymbols, const GVSummaryMapTy & DefinedGlobals, const ThinLTOCodeGenerator::CachingOptions & CacheOptions, bool DisableCodeGen, StringRef SaveTempsDir, bool Freestanding, unsigned OptLevel, unsigned count, bool DebugPassManager) static
Definition at line 427 of file ThinLTOCodeGenerator.cpp.
References llvm::buildModuleSummaryIndex(), codegenModule(), llvm::count(), crossImportIntoModule(), llvm::PIELevel::Default, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::Module::getPIELevel(), llvm::TargetMachine::getRelocationModel(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), optimizeModule(), promoteModule(), saveTempBitcode(), llvm::StringMapImpl::size(), llvm::Reloc::Static, llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), llvm::updatePublicTypeTestCalls(), and llvm::WriteBitcodeToFile().
Referenced by llvm::ThinLTOCodeGenerator::run().
promoteModule()
void promoteModule (Module & TheModule, const ModuleSummaryIndex & Index, bool ClearDSOLocalOnDeclarations) static
Definition at line 158 of file ThinLTOCodeGenerator.cpp.
References llvm::renameModuleForThinLTO().
Referenced by llvm::ThinLTOCodeGenerator::internalize(), ProcessThinLTOModule(), and llvm::ThinLTOCodeGenerator::promote().
resolvePrevailingInIndex()
void resolvePrevailingInIndex (ModuleSummaryIndex & Index, StringMap< std::map< GlobalValue::GUID, GlobalValue::LinkageTypes > > & ResolvedODR, const DenseSet< GlobalValue::GUID > & GUIDPreservedSymbols, const DenseMap< GlobalValue::GUID, const GlobalValueSummary * > & PrevailingCopy) static
Resolve prevailing symbols.
Record resolutions in the ResolvedODR map for caching, and in the Index for application during the ThinLTO backends. This is needed for correctness for exported symbols (ensure at least one copy kept) and a compile-time optimization (to drop duplicate copies when possible).
Definition at line 506 of file ThinLTOCodeGenerator.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::thinLTOResolvePrevailingInIndex().
Referenced by llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::promote(), and llvm::ThinLTOCodeGenerator::run().
saveTempBitcode()
void saveTempBitcode (const Module & TheModule, StringRef TempDir, unsigned count, StringRef Suffix) static
Definition at line 90 of file ThinLTOCodeGenerator.cpp.
References llvm::count(), llvm::StringRef::empty(), llvm::sys::fs::OF_None, llvm::report_fatal_error(), and llvm::WriteBitcodeToFile().
Referenced by ProcessThinLTOModule(), and llvm::ThinLTOCodeGenerator::run().
verifyLoadedModule()
void verifyLoadedModule (Module & TheModule) static
Verify the module and strip broken debug info.
Definition at line 175 of file ThinLTOCodeGenerator.cpp.
References llvm::dbgs(), llvm::LLVMContext::diagnose(), llvm::DS_Warning, llvm::Module::getContext(), llvm::report_fatal_error(), llvm::StripDebugInfo(), and llvm::verifyModule().
Referenced by crossImportIntoModule(), and loadModuleFromInput().
Variable Documentation
ThreadCount
cl::opt< int > ThreadCount("threads", cl::init(0)) ("threads" , cl::init(0)) static
Referenced by llvm::hardware_concurrency(), llvm::heavyweight_hardware_concurrency(), llvm::ThinLTOCodeGenerator::run(), llvm::SingleThreadExecutor::SingleThreadExecutor(), and splitCodeGen().