LLVM: lib/Support/Timer.cpp File Reference
Timer.cpp File Reference
#include "llvm/Support/Timer.h"
#include "DebugOptions.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Config/config.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Signposts.h"
#include "llvm/Support/raw_ostream.h"
#include <limits>
#include <optional>
#include <libproc.h>
Classes
class llvm::TimerGlobals
Functions
static std::string & libSupportInfoOutputFilename ()
static bool trackSpace ()
static bool sortTimers ()
static SignpostEmitter & signposts ()
static sys::SmartMutex< true > & timerLock ()
static TimerGroup & defaultTimerGroup ()
static Name2PairMap & namedGroupedTimers ()
static bool isTimerGlobalsConstructed ()
static size_t getMemUsage ()
static uint64_t getCurInstructionsExecuted ()
static void printVal (double Val, double Total, raw_ostream &OS)
Variables
static TimerGroup * TimerGroupList = nullptr
This is the global list of TimerGroups, maintained by the TimerGroup ctor/dtor and is protected by the timerLock lock.
static ManagedStatic< TimerGlobals > ManagedTimerGlobals
Function Documentation
defaultTimerGroup()
TimerGroup & defaultTimerGroup () static
Definition at line 562 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::Timer::init().
getCurInstructionsExecuted()
uint64_t getCurInstructionsExecuted () static
Definition at line 117 of file Timer.cpp.
Referenced by llvm::TimeRecord::getCurrentTime().
getMemUsage()
size_t getMemUsage () inline static
Definition at line 111 of file Timer.cpp.
References llvm::sys::Process::GetMallocUsage(), and trackSpace().
Referenced by llvm::TimeRecord::getCurrentTime().
isTimerGlobalsConstructed()
bool isTimerGlobalsConstructed () static
Definition at line 576 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::TimerGroup::~TimerGroup().
libSupportInfoOutputFilename()
std::string & libSupportInfoOutputFilename () static
Definition at line 553 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::CreateInfoOutputFile().
namedGroupedTimers()
Name2PairMap & namedGroupedTimers () static
Definition at line 565 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::NamedRegionTimer::getNamedTimerGroup(), and llvm::NamedRegionTimer::NamedRegionTimer().
printVal()
void printVal (double Val, double Total, raw_ostream & OS) static
Definition at line 179 of file Timer.cpp.
References llvm::format(), and llvm::Total.
Referenced by llvm::TimeRecord::print().
signposts()
SignpostEmitter & signposts () static
Definition at line 558 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::Timer::startTimer(), and llvm::Timer::stopTimer().
sortTimers()
bool sortTimers () static
Definition at line 557 of file Timer.cpp.
References ManagedTimerGlobals.
timerLock()
sys::SmartMutex< true > & timerLock () static
Definition at line 559 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by llvm::TimerGroup::clear(), llvm::TimerGroup::clearAll(), llvm::TimerGroup::print(), llvm::TimerGroup::printAll(), llvm::TimerGroup::printAllJSONValues(), llvm::TimerGroup::printJSONValues(), llvm::TimerGroup::TimerGroup(), and llvm::TimerGroup::~TimerGroup().
trackSpace()
bool trackSpace () static
Definition at line 556 of file Timer.cpp.
References ManagedTimerGlobals.
Referenced by getMemUsage().
Variable Documentation
ManagedTimerGlobals
ManagedStatic<TimerGlobals> ManagedTimerGlobals static
Definition at line 551 of file Timer.cpp.
Referenced by llvm::TimerGroup::acquireTimerGlobals(), llvm::TimerGroup::constructForStatistics(), defaultTimerGroup(), llvm::initTimerOptions(), isTimerGlobalsConstructed(), libSupportInfoOutputFilename(), namedGroupedTimers(), signposts(), sortTimers(), timerLock(), and trackSpace().
TimerGroupList
TimerGroup* TimerGroupList = nullptr static
This is the global list of TimerGroups, maintained by the TimerGroup ctor/dtor and is protected by the timerLock lock.
Definition at line 271 of file Timer.cpp.
Referenced by llvm::TimerGroup::clearAll(), llvm::TimerGroup::printAll(), and llvm::TimerGroup::printAllJSONValues().