LLVM: lib/Target/VE/AsmParser/VEAsmParser.cpp File Reference
VEAsmParser.cpp File Reference
#include "MCTargetDesc/VEMCAsmInfo.h"
#include "MCTargetDesc/VEMCTargetDesc.h"
#include "TargetInfo/VETargetInfo.h"
#include "VE.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/raw_ostream.h"
#include <memory>
#include "VEGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "ve-asmparser"
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Functions
static MCRegister MatchRegisterName (StringRef Name)
Maps from the set of all register names to a register number.
static MCRegister MatchRegisterAltName (StringRef Name)
Maps from the set of all alternative registernames to a register number.
static StringRef parseCC (StringRef Name, unsigned Prefix, unsigned Suffix, bool IntegerCC, bool OmitCC, SMLoc NameLoc, OperandVector *Operands)
static StringRef parseRD (StringRef Name, unsigned Prefix, SMLoc NameLoc, OperandVector *Operands)
static void applyMnemonicAliases (StringRef &Mnemonic, const FeatureBitset &Features, unsigned VariantID)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVEAsmParser ()
Variables
static const MCPhysReg I32Regs [64]
static const MCPhysReg F32Regs [64]
static const MCPhysReg F128Regs [32]
static const MCPhysReg VM512Regs [8]
static const MCPhysReg MISCRegs [31]
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ve-asmparser"
Definition at line 34 of file VEAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 46 of file VEAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1535 of file VEAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1534 of file VEAsmParser.cpp.
Function Documentation
applyMnemonicAliases()
void applyMnemonicAliases (StringRef & Mnemonic, const FeatureBitset & Features, unsigned VariantID) static
References llvm::AsmToken::EndOfStatement, and Info.
LLVMInitializeVEAsmParser()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVEAsmParser ()
Definition at line 1530 of file VEAsmParser.cpp.
References A(), llvm::getTheVETarget(), LLVM_ABI, and LLVM_EXTERNAL_VISIBILITY.
MatchRegisterAltName()
MCRegister MatchRegisterAltName (StringRef Name) static
Maps from the set of all alternative registernames to a register number.
Note
References MatchRegisterAltName(), MatchRegisterName(), llvm::ParseStatus::NoMatch, llvm::AsmToken::Percent, Reg, and llvm::ParseStatus::Success.
MatchRegisterName()
MCRegister MatchRegisterName (StringRef Name) static
Maps from the set of all register names to a register number.
Note
parseCC()
StringRef parseCC (StringRef Name, unsigned Prefix, unsigned Suffix, bool IntegerCC, bool OmitCC, SMLoc NameLoc, OperandVector * Operands) static
Definition at line 865 of file VEAsmParser.cpp.
References llvm::VECC::CC_AF, llvm::VECC::CC_AT, Cond, llvm::StringRef::empty(), llvm::SMLoc::getFromPointer(), llvm::SMLoc::getPointer(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::stringToVEFCondCode(), llvm::stringToVEICondCode(), and llvm::VECC::UNKNOWN.
parseRD()
StringRef parseRD (StringRef Name, unsigned Prefix, SMLoc NameLoc, OperandVector * Operands) static
Definition at line 894 of file VEAsmParser.cpp.
References llvm::StringRef::data(), llvm::StringRef::end(), llvm::SMLoc::getFromPointer(), llvm::SMLoc::getPointer(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::stringToVERD(), SuffixEnd, and llvm::VERD::UNKNOWN.
Variable Documentation
F128Regs
const MCPhysReg F128Regs[32] static
Initial value:
                            = {
VE::Q0,  VE::Q1,  VE::Q2,  VE::Q3,  VE::Q4,  VE::Q5,  VE::Q6,  VE::Q7,
VE::Q8,  VE::Q9,  VE::Q10, VE::Q11, VE::Q12, VE::Q13, VE::Q14, VE::Q15,
VE::Q16, VE::Q17, VE::Q18, VE::Q19, VE::Q20, VE::Q21, VE::Q22, VE::Q23,
VE::Q24, VE::Q25, VE::Q26, VE::Q27, VE::Q28, VE::Q29, VE::Q30, VE::Q31}
Definition at line 121 of file VEAsmParser.cpp.
F32Regs
const MCPhysReg F32Regs[64] static
Initial value:
                           = {
VE::SF0,  VE::SF1,  VE::SF2,  VE::SF3,  VE::SF4,  VE::SF5,  VE::SF6,
VE::SF7,  VE::SF8,  VE::SF9,  VE::SF10, VE::SF11, VE::SF12, VE::SF13,
VE::SF14, VE::SF15, VE::SF16, VE::SF17, VE::SF18, VE::SF19, VE::SF20,
VE::SF21, VE::SF22, VE::SF23, VE::SF24, VE::SF25, VE::SF26, VE::SF27,
VE::SF28, VE::SF29, VE::SF30, VE::SF31, VE::SF32, VE::SF33, VE::SF34,
VE::SF35, VE::SF36, VE::SF37, VE::SF38, VE::SF39, VE::SF40, VE::SF41,
VE::SF42, VE::SF43, VE::SF44, VE::SF45, VE::SF46, VE::SF47, VE::SF48,
VE::SF49, VE::SF50, VE::SF51, VE::SF52, VE::SF53, VE::SF54, VE::SF55,
VE::SF56, VE::SF57, VE::SF58, VE::SF59, VE::SF60, VE::SF61, VE::SF62,
VE::SF63}
Definition at line 109 of file VEAsmParser.cpp.
Referenced by CC_MipsO32().
I32Regs
const MCPhysReg I32Regs[64] static
Initial value:
                           = {
VE::SW0,  VE::SW1,  VE::SW2,  VE::SW3,  VE::SW4,  VE::SW5,  VE::SW6,
VE::SW7,  VE::SW8,  VE::SW9,  VE::SW10, VE::SW11, VE::SW12, VE::SW13,
VE::SW14, VE::SW15, VE::SW16, VE::SW17, VE::SW18, VE::SW19, VE::SW20,
VE::SW21, VE::SW22, VE::SW23, VE::SW24, VE::SW25, VE::SW26, VE::SW27,
VE::SW28, VE::SW29, VE::SW30, VE::SW31, VE::SW32, VE::SW33, VE::SW34,
VE::SW35, VE::SW36, VE::SW37, VE::SW38, VE::SW39, VE::SW40, VE::SW41,
VE::SW42, VE::SW43, VE::SW44, VE::SW45, VE::SW46, VE::SW47, VE::SW48,
VE::SW49, VE::SW50, VE::SW51, VE::SW52, VE::SW53, VE::SW54, VE::SW55,
VE::SW56, VE::SW57, VE::SW58, VE::SW59, VE::SW60, VE::SW61, VE::SW62,
VE::SW63}
Definition at line 97 of file VEAsmParser.cpp.
MISCRegs
const MCPhysReg MISCRegs[31] static
Initial value:
                            = {
VE::USRCC,      VE::PSW,        VE::SAR,        VE::NoRegister,
VE::NoRegister, VE::NoRegister, VE::NoRegister, VE::PMMR,
VE::PMCR0,      VE::PMCR1,      VE::PMCR2,      VE::PMCR3,
VE::NoRegister, VE::NoRegister, VE::NoRegister, VE::NoRegister,
VE::PMC0,       VE::PMC1,       VE::PMC2,       VE::PMC3,
VE::PMC4,       VE::PMC5,       VE::PMC6,       VE::PMC7,
VE::PMC8,       VE::PMC9,       VE::PMC10,      VE::PMC11,
VE::PMC12,      VE::PMC13,      VE::PMC14}
Definition at line 130 of file VEAsmParser.cpp.
VM512Regs
const MCPhysReg VM512Regs[8] static
Initial value:
= {VE::VMP0, VE::VMP1, VE::VMP2, VE::VMP3,
      VE::VMP4, VE::VMP5, VE::VMP6, VE::VMP7}
Definition at line 127 of file VEAsmParser.cpp.