LLVM: lib/Support/VirtualOutputBackends.cpp File Reference
VirtualOutputBackends.cpp File Reference
This file implements the VirtualOutputBackend types, including:
#include "llvm/Support/VirtualOutputBackends.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/IOSandbox.h"
#include "llvm/Support/LockFileManager.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/VirtualOutputConfig.h"
#include "llvm/Support/VirtualOutputError.h"
Functions
static OutputConfig applySettings (std::optional< OutputConfig > &&Config, const OnDiskOutputBackend::OutputSettings &Settings)
static Error createDirectoriesOnDemand (StringRef OutputPath, OutputConfig Config, llvm::function_ref< Error()> CreateFile)
static sys::fs::OpenFlags generateFlagsFromConfig (OutputConfig Config)
static Expected< FileDifference > areFilesDifferent (const llvm::Twine &Source, const llvm::Twine &Destination)
Detailed Description
This file implements the VirtualOutputBackend types, including:
NullOutputBackend: Outputs to NullOutputBackend are discarded.
FilteringOutputBackend: Filter paths from output.
MirroringOutputBackend: Mirror the output into two different backend.
OnDiskOutputBackend: Write output files to disk.
Definition in file VirtualOutputBackends.cpp.
Function Documentation
applySettings()
OutputConfig applySettings (std::optional< OutputConfig > && Config, const OnDiskOutputBackend::OutputSettings & Settings) static
Definition at line 193 of file VirtualOutputBackends.cpp.
References llvm::vfs::OnDiskOutputBackend::OutputSettings::DefaultConfig, llvm::vfs::OnDiskOutputBackend::OutputSettings::RemoveOnSignal, and llvm::vfs::OnDiskOutputBackend::OutputSettings::UseTemporaries.
areFilesDifferent()
Expected< FileDifference > areFilesDifferent (const llvm::Twine & Source, const llvm::Twine & Destination) static
Definition at line 396 of file VirtualOutputBackends.cpp.
References llvm::sys::fs::mapped_file_region::const_data(), llvm::sys::fs::convertFDToNativeFile(), llvm::vfs::convertToOutputError(), llvm::sys::fs::equivalent(), llvm::sys::fs::basic_file_status::getSize(), memcmp, llvm::sys::fs::openFileForRead(), llvm::sys::fs::mapped_file_region::readonly, Size, and llvm::sys::fs::status().
createDirectoriesOnDemand()
Error createDirectoriesOnDemand (StringRef OutputPath, OutputConfig Config, llvm::function_ref< Error()> CreateFile) static
Definition at line 243 of file VirtualOutputBackends.cpp.
References llvm::sys::fs::create_directories(), llvm::Error, llvm::handleErrors(), llvm::make_error(), and llvm::sys::path::parent_path().
generateFlagsFromConfig()
sys::fs::OpenFlags generateFlagsFromConfig (OutputConfig Config) static
Definition at line 258 of file VirtualOutputBackends.cpp.
References llvm::vfs::OutputConfig::getTextWithCRLF(), llvm::sys::fs::OF_Append, llvm::sys::fs::OF_None, llvm::sys::fs::OF_Text, and llvm::sys::fs::OF_TextWithCRLF.