LLVM: lib/Transforms/Vectorize/VPlanUnroll.cpp File Reference
VPlanUnroll.cpp File Reference
This file implements explicit unrolling for VPlans.
#include "VPRecipeBuilder.h"
#include "VPlan.h"
#include "VPlanAnalysis.h"
#include "VPlanCFG.h"
#include "VPlanHelpers.h"
#include "VPlanPatternMatch.h"
#include "VPlanTransforms.h"
#include "VPlanUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/IR/Intrinsics.h"
Functions
static VPValue * cloneForLane (VPlan &Plan, VPBuilder &Builder, Type *IdxTy, VPSingleDefRecipe *DefR, VPLane Lane, const DenseMap< VPValue *, SmallVector< VPValue * > > &Def2LaneDefs)
Create a single-scalar clone of DefR (must be a VPReplicateRecipe or VPInstruction) for lane Lane.
Detailed Description
This file implements explicit unrolling for VPlans.
Definition in file VPlanUnroll.cpp.
Function Documentation
cloneForLane()
VPValue * cloneForLane (VPlan & Plan, VPBuilder & Builder, Type * IdxTy, VPSingleDefRecipe * DefR, VPLane Lane, const DenseMap< VPValue *, SmallVector< VPValue * > > & Def2LaneDefs) static
Create a single-scalar clone of DefR (must be a VPReplicateRecipe or VPInstruction) for lane Lane.
Use Def2LaneDefs to look up scalar definitions for operands of \DefR.
Definition at line 485 of file VPlanUnroll.cpp.
References assert(), llvm::cast(), llvm::VPSingleDefRecipe::clone(), llvm::dyn_cast(), llvm::enumerate(), llvm::VPInstruction::ExtractLastLane, llvm::VPInstruction::ExtractLastPart, llvm::VPlan::getConstantInt(), llvm::VPLane::getKind(), llvm::VPLane::getKnownLane(), llvm::isa(), llvm::vputils::isSingleScalar(), llvm::VPlanPatternMatch::m_BuildVector(), llvm::VPlanPatternMatch::m_VPInstruction(), llvm::VPlanPatternMatch::m_VPValue(), llvm::PatternMatch::match(), llvm::VPUser::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::VPLane::ScalableLast.
Referenced by llvm::VPlanTransforms::replicateByVF().