LLVM: lib/MC/WasmObjectWriter.cpp File Reference
WasmObjectWriter.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/BinaryFormat/WasmTraits.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWasmObjectWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include <vector>
Macros
#define DEBUG_TYPE "mc"
Functions
static void addData (SmallVectorImpl< char > &DataBytes, MCSectionWasm &DataSection)
static bool isInSymtab (const MCSymbolWasm &Sym)
static bool isSectionReferenced (MCAssembler &Asm, MCSectionWasm &Section)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mc"
Definition at line 35 of file WasmObjectWriter.cpp.
Function Documentation
addData()
void addData (SmallVectorImpl< char > & DataBytes, MCSectionWasm & DataSection) static
Definition at line 693 of file WasmObjectWriter.cpp.
References llvm::alignTo(), llvm::append_range(), assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::errs(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_LEB, llvm::MCSection::getAlign(), llvm::MCSection::getName(), llvm::SmallVectorImpl< T >::insert(), LLVM_DEBUG, llvm_unreachable, llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::resize(), Size, and llvm::SmallVectorTemplateCommon< T, typename >::size().
isInSymtab()
bool isInSymtab (const MCSymbolWasm & Sym) static
Definition at line 1292 of file WasmObjectWriter.cpp.
References llvm::MCSymbolWasm::isComdat(), llvm::MCSymbol::isDefined(), llvm::MCSymbolWasm::isSection(), llvm::MCSymbol::isTemporary(), llvm::MCSymbolWasm::isUsedInInitArray(), llvm::MCSymbol::isUsedInReloc(), and llvm::MCSymbolWasm::omitFromLinkingSection().
isSectionReferenced()
bool isSectionReferenced (MCAssembler & Asm, MCSectionWasm & Section) static
Definition at line 1311 of file WasmObjectWriter.cpp.