LLVM: lib/Target/WebAssembly/WebAssemblyTargetTransformInfo.cpp File Reference
WebAssemblyTargetTransformInfo.cpp File Reference
This file defines the WebAssembly-specific TargetTransformInfo implementation.
#include "WebAssemblyTargetTransformInfo.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/CodeGen/CostTable.h"
Macros
#define DEBUG_TYPE "wasmtti"
Functions
static Value * simplifyWasmSwizzle (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsRelaxed)
Attempt to convert [relaxed_]swizzle to shufflevector if the mask is constant.
Detailed Description
This file defines the WebAssembly-specific TargetTransformInfo implementation.
Definition in file WebAssemblyTargetTransformInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasmtti"
Definition at line 23 of file WebAssemblyTargetTransformInfo.cpp.
Function Documentation
simplifyWasmSwizzle()
Value * simplifyWasmSwizzle (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsRelaxed) static
Attempt to convert [relaxed_]swizzle to shufflevector if the mask is constant.
Definition at line 525 of file WebAssemblyTargetTransformInfo.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::dyn_cast(), llvm::PoisonValue::get(), llvm::Constant::getAggregateElement(), llvm::Constant::getNullValue(), I, II, and llvm::isa().
Referenced by llvm::WebAssemblyTTIImpl::instCombineIntrinsic().