LLVM: lib/Target/WebAssembly/Disassembler/WebAssemblyDisassembler.cpp File Reference
WebAssemblyDisassembler.cpp File Reference
This file is part of the WebAssembly Disassembler.
#include "MCTargetDesc/WebAssemblyMCAsmInfo.h"
#include "MCTargetDesc/WebAssemblyMCTypeUtilities.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/LEB128.h"
#include "WebAssemblyGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "wasm-disassembler"
Functions
static MCDisassembler * createWebAssemblyDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyDisassembler ()
static int nextByte (ArrayRef< uint8_t > Bytes, uint64_t &Size)
static bool nextLEB (int64_t &Val, ArrayRef< uint8_t > Bytes, uint64_t &Size, bool Signed)
static bool parseLEBImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes, bool Signed)
template<typename T>
bool parseImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes)
Variables
static constexpr int WebAssemblyInstructionTableSize = 256
Detailed Description
This file is part of the WebAssembly Disassembler.
It contains code to translate the data produced by the decoder into MCInsts.
Definition in file WebAssemblyDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-disassembler"
Definition at line 35 of file WebAssemblyDisassembler.cpp.
Function Documentation
createWebAssemblyDisassembler()
MCDisassembler * createWebAssemblyDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 62 of file WebAssemblyDisassembler.cpp.
References T.
Referenced by LLVMInitializeWebAssemblyDisassembler().
LLVMInitializeWebAssemblyDisassembler()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyDisassembler ()
Definition at line 70 of file WebAssemblyDisassembler.cpp.
References createWebAssemblyDisassembler(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), and llvm::TargetRegistry::RegisterMCDisassembler().
nextByte()
int nextByte (ArrayRef< uint8_t > Bytes, uint64_t & Size) static
Definition at line 78 of file WebAssemblyDisassembler.cpp.
References Size, and llvm::ArrayRef< T >::size().
Referenced by readPrefixes().
nextLEB()
bool nextLEB (int64_t & Val, ArrayRef< uint8_t > Bytes, uint64_t & Size, bool Signed) static
Definition at line 86 of file WebAssemblyDisassembler.cpp.
References llvm::ArrayRef< T >::data(), llvm::decodeSLEB128(), llvm::decodeULEB128(), N, Signed, Size, and llvm::ArrayRef< T >::size().
Referenced by parseLEBImmediate().
parseImmediate()
template<typename T> bool parseImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes)
Definition at line 111 of file WebAssemblyDisassembler.cpp.
References llvm::bit_cast(), llvm::MCOperand::createDFPImm(), llvm::MCOperand::createImm(), llvm::ArrayRef< T >::data(), MI, llvm::support::endian::read(), Size, llvm::ArrayRef< T >::size(), and T.
parseLEBImmediate()
bool parseLEBImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes, bool Signed) static
Definition at line 101 of file WebAssemblyDisassembler.cpp.
References llvm::MCOperand::createImm(), MI, nextLEB(), Signed, and Size.
Variable Documentation
WebAssemblyInstructionTableSize
int WebAssemblyInstructionTableSize = 256 static constexpr
Definition at line 41 of file WebAssemblyDisassembler.cpp.