LLVM: lib/Target/X86/X86FastPreTileConfig.cpp File Reference
X86FastPreTileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionAnalysisManager.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachinePassManager.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/Analysis.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "x86-fast-pre-tile-config"
Functions
STATISTIC (NumStores, "Number of stores added")
STATISTIC (NumLoads, "Number of loads added")
INITIALIZE_PASS_BEGIN (X86FastPreTileConfigLegacy, DEBUG_TYPE, "Fast Tile Register Preconfigure", false, false) INITIALIZE_PASS_END(X86FastPreTileConfigLegacy
Fast Tile Register static false bool dominates (MachineBasicBlock &MBB, MachineBasicBlock::const_iterator A, MachineBasicBlock::const_iterator B)
static bool isTileRegister (MachineRegisterInfo *MRI, Register Reg)
static bool isTileDef (MachineRegisterInfo *MRI, MachineInstr &MI)
static ShapeT getShape (MachineRegisterInfo *MRI, Register TileReg)
static bool isTileRegDef (MachineRegisterInfo *MRI, MachineInstr &MI)
Variables
DEBUG_TYPE
Fast Tile Register Preconfigure
Fast Tile Register false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-fast-pre-tile-config"
Definition at line 39 of file X86FastPreTileConfig.cpp.
Function Documentation
dominates()
Fast Tile Register static false bool dominates (MachineBasicBlock & MBB, MachineBasicBlock::const_iterator A, MachineBasicBlock::const_iterator B) static
Definition at line 111 of file X86FastPreTileConfig.cpp.
References A(), B(), dominates(), I, and MBB.
getShape()
ShapeT getShape (MachineRegisterInfo * MRI, Register TileReg) static
Definition at line 304 of file X86FastPreTileConfig.cpp.
References assert(), getShape(), isTileDef(), llvm_unreachable, MI, and MRI.
Referenced by getShape().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86FastPreTileConfigLegacy , DEBUG_TYPE , "Fast Tile Register Preconfigure" , false , false)
References DEBUG_TYPE.
isTileDef()
bool isTileDef (MachineRegisterInfo * MRI, MachineInstr & MI) static
Definition at line 292 of file X86FastPreTileConfig.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), isTileRegister(), MI, and MRI.
Referenced by getShape(), and isTileDef().
isTileRegDef()
bool isTileRegDef (MachineRegisterInfo * MRI, MachineInstr & MI) static
Definition at line 439 of file X86FastPreTileConfig.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), isTileRegister(), llvm::Register::isVirtual(), MI, and MRI.
isTileRegister()
bool isTileRegister (MachineRegisterInfo * MRI, Register Reg) static
Definition at line 280 of file X86FastPreTileConfig.cpp.
References MRI, and Reg.
Referenced by isTileDef(), and isTileRegDef().
STATISTIC() [1/2]
STATISTIC (NumLoads , "Number of loads added")
STATISTIC() [2/2]
STATISTIC (NumStores , "Number of stores added")
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 108 of file X86FastPreTileConfig.cpp.
false
Fast Tile Register false
Definition at line 109 of file X86FastPreTileConfig.cpp.
Preconfigure
Fast Tile Register Preconfigure
Definition at line 109 of file X86FastPreTileConfig.cpp.