LLVM: lib/Target/X86/X86FixupSetCC.cpp File Reference
X86FixupSetCC.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Macros
#define DEBUG_TYPE "x86-fixup-setcc"
Functions
STATISTIC (NumSubstZexts, "Number of setcc + zext pairs substituted")
static bool fixupSetCC (MachineFunction &MF)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-fixup-setcc"
Definition at line 37 of file X86FixupSetCC.cpp.
Function Documentation
fixupSetCC()
bool fixupSetCC (MachineFunction & MF) static
Definition at line 62 of file X86FixupSetCC.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineFunction::makeDebugValueSubstitution(), MBB, MI, MRI, llvm::MachineInstr::peekDebugInstrNum(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstr::readsRegister(), and TII.
Referenced by llvm::X86FixupSetCCPass::run().
STATISTIC()
STATISTIC (NumSubstZexts , "Number of setcc + zext pairs substituted")