LLVM: lib/Target/X86/X86FixupVectorConstants.cpp File Reference
X86FixupVectorConstants.cpp File Reference
#include "X86.h"
#include "X86InstrFoldTables.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineConstantPool.h"
Macros
#define DEBUG_TYPE "x86-fixup-vector-constants"
Functions
STATISTIC (NumInstChanges, "Number of instructions changes")
INITIALIZE_PASS (X86FixupVectorConstantsLegacy, DEBUG_TYPE, DEBUG_TYPE, false, false) FunctionPass *llvm
static Constant * getSplatValueAllowUndef (const ConstantVector *C)
Normally, we only allow poison in vector splats.
static std::optional< APInt > extractConstantBits (const Constant *C)
static std::optional< APInt > extractConstantBits (const Constant *C, unsigned NumBits)
static std::optional< APInt > getSplatableConstant (const Constant *C, unsigned SplatBitWidth)
static Constant * rebuildConstant (LLVMContext &Ctx, Type *SclTy, const APInt &Bits, unsigned NumSclBits)
static Constant * rebuildSplatCst (const Constant *C, unsigned, unsigned, unsigned SplatBitWidth)
static Constant * rebuildZeroUpperCst (const Constant *C, unsigned NumBits, unsigned, unsigned ScalarBitWidth)
static Constant * rebuildExtCst (const Constant *C, bool IsSExt, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth)
static Constant * rebuildSExtCst (const Constant *C, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth)
static Constant * rebuildZExtCst (const Constant *C, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-fixup-vector-constants"
Definition at line 27 of file X86FixupVectorConstants.cpp.
Function Documentation
extractConstantBits() [1/2]
std::optional< APInt > extractConstantBits (const Constant * C) static
Definition at line 91 of file X86FixupVectorConstants.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), E(), extractConstantBits(), llvm::User::getOperand(), llvm::APInt::getSplat(), getSplatValueAllowUndef(), llvm::APInt::getZero(), I, and llvm::isa().
Referenced by extractConstantBits(), extractConstantBits(), getSplatableConstant(), rebuildExtCst(), and rebuildZeroUpperCst().
extractConstantBits() [2/2]
std::optional< APInt > extractConstantBits (const Constant * C, unsigned NumBits) static
Definition at line 155 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, and extractConstantBits().
getSplatableConstant()
std::optional< APInt > getSplatableConstant (const Constant * C, unsigned SplatBitWidth) static
Definition at line 164 of file X86FixupVectorConstants.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, assert(), llvm::CallingConv::C, llvm::dyn_cast(), extractConstantBits(), llvm::Constant::getAggregateElement(), llvm::APInt::getZero(), I, llvm::APInt::insertBits(), and llvm::isa().
Referenced by rebuildSplatCst().
getSplatValueAllowUndef()
Constant * getSplatValueAllowUndef (const ConstantVector * C) static
Normally, we only allow poison in vector splats.
However, as this is part of the backend, and working with the DAG representation, which currently only natively represents undef values, we need to accept undefs here.
Definition at line 76 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, llvm::cast(), and llvm::isa().
Referenced by extractConstantBits().
INITIALIZE_PASS()
INITIALIZE_PASS (X86FixupVectorConstantsLegacy , DEBUG_TYPE , DEBUG_TYPE , false , false)
Definition at line 66 of file X86FixupVectorConstants.cpp.
References llvm::createX86FixupVectorConstantsLegacyPass(), and DEBUG_TYPE.
rebuildConstant()
Constant * rebuildConstant (LLVMContext & Ctx, Type * SclTy, const APInt & Bits, unsigned NumSclBits) static
Definition at line 217 of file X86FixupVectorConstants.cpp.
References assert(), llvm::BitWidth, llvm::ConstantDataVector::get(), llvm::ConstantDataVector::getFP(), I, llvm::Type::is16bitFPTy(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by rebuildExtCst(), rebuildSplatCst(), and rebuildZeroUpperCst().
rebuildExtCst()
Constant * rebuildExtCst (const Constant * C, bool IsSExt, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth) static
Definition at line 306 of file X86FixupVectorConstants.cpp.
References assert(), llvm::CallingConv::C, extractConstantBits(), llvm::APInt::getActiveBits(), llvm::APInt::getSignificantBits(), llvm::APInt::getZero(), I, llvm::APInt::insertBits(), rebuildConstant(), and llvm::APInt::trunc().
Referenced by rebuildSExtCst(), and rebuildZExtCst().
rebuildSExtCst()
Constant * rebuildSExtCst (const Constant * C, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth) static
Definition at line 336 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, and rebuildExtCst().
rebuildSplatCst()
Constant * rebuildSplatCst (const Constant * C, unsigned , unsigned , unsigned SplatBitWidth) static
Definition at line 258 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, llvm::Type::getPrimitiveSizeInBits(), getSplatableConstant(), rebuildConstant(), and llvm::Splat.
rebuildZeroUpperCst()
Constant * rebuildZeroUpperCst (const Constant * C, unsigned NumBits, unsigned , unsigned ScalarBitWidth) static
Definition at line 280 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, extractConstantBits(), llvm::Type::getPrimitiveSizeInBits(), and rebuildConstant().
rebuildZExtCst()
Constant * rebuildZExtCst (const Constant * C, unsigned NumBits, unsigned NumElts, unsigned SrcEltBitWidth) static
Definition at line 340 of file X86FixupVectorConstants.cpp.
References llvm::CallingConv::C, and rebuildExtCst().
STATISTIC()
STATISTIC (NumInstChanges , "Number of instructions changes")
References MBB, MI, SM(), and TII.