LLVM: lib/Target/X86/X86LowerTileCopy.cpp File Reference
X86LowerTileCopy.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/LiveRegUnits.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/DebugLoc.h"
Macros
#define DEBUG_TYPE "x86-lower-tile-copy"
#define GET_EGPR_IF_ENABLED(OPC)
Functions
INITIALIZE_PASS_BEGIN (X86LowerTileCopyLegacy, DEBUG_TYPE, "Tile Copy Lowering", false, false) INITIALIZE_PASS_END(X86LowerTileCopyLegacy
static bool lowerTileCopy (MachineFunction &MF)
Variables
DEBUG_TYPE
Tile Copy Lowering
Tile Copy false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-lower-tile-copy"
Definition at line 37 of file X86LowerTileCopy.cpp.
GET_EGPR_IF_ENABLED
#define GET_EGPR_IF_ENABLED (OPC)
Value:
(ST.hasEGPR() ? OPC##_EVEX : OPC)
Referenced by lowerTileCopy().
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86LowerTileCopyLegacy , DEBUG_TYPE , "Tile Copy Lowering" , false , false)
References DEBUG_TYPE.
lowerTileCopy()
bool lowerTileCopy (MachineFunction & MF) static
Definition at line 72 of file X86LowerTileCopy.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::LiveRegUnits::addLiveOuts(), llvm::MachineInstrBuilder::addReg(), llvm::X86::AddrIndexReg, assert(), llvm::LiveRegUnits::available(), llvm::BuildMI(), contains(), llvm::MachineFrameInfo::CreateSpillStackObject(), DL, GET_EGPR_IF_ENABLED, llvm::X86MachineFunctionInfo::getAMXProgModel(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isKill(), llvm::make_early_inc_range(), llvm::ManagedRA, MBB, MI, Opc, llvm::reverse(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setReg(), Size, llvm::LiveRegUnits::stepBackward(), TII, and TRI.
Referenced by llvm::X86LowerTileCopyPass::run().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 60 of file X86LowerTileCopy.cpp.
false
Tile Copy false
Definition at line 61 of file X86LowerTileCopy.cpp.
Lowering
Tile Copy Lowering
Definition at line 60 of file X86LowerTileCopy.cpp.