LLVM: lib/Target/X86/MCTargetDesc/X86MCAsmInfo.cpp File Reference
X86MCAsmInfo.cpp File Reference
#include "X86MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/TargetParser/Triple.h"
Enumerations
enum AsmWriterFlavorTy { ATT = 0 , Intel = 1 }
Variables
static cl::opt< AsmWriterFlavorTy > X86AsmSyntax ("x86-asm-syntax", cl::init(ATT), cl::Hidden, cl::desc("Select the assembly style for input"), cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly")))
static cl::opt< bool > MarkedJTDataRegions ("mark-data-regions", cl::init(true), cl::desc("Mark code section jump table data regions."), cl::Hidden)
const MCAsmInfo::AtSpecifier atSpecifiers []
Enumeration Type Documentation
AsmWriterFlavorTy
enum AsmWriterFlavorTy
Enumerator
ATT
Intel
Definition at line 20 of file X86MCAsmInfo.cpp.
Variable Documentation
atSpecifiers
const MCAsmInfo::AtSpecifier atSpecifiers[]
Initial value:
                                          = {
    {X86::S_ABS8, "ABS8"},
    {X86::S_DTPOFF, "DTPOFF"},
    {X86::S_DTPREL, "DTPREL"},
    {X86::S_GOT, "GOT"},
    {X86::S_GOTENT, "GOTENT"},
    {X86::S_GOTNTPOFF, "GOTNTPOFF"},
    {X86::S_GOTOFF, "GOTOFF"},
    {X86::S_GOTPCREL, "GOTPCREL"},
    {X86::S_GOTPCREL_NORELAX, "GOTPCREL_NORELAX"},
    {X86::S_GOTREL, "GOTREL"},
    {X86::S_GOTTPOFF, "GOTTPOFF"},
    {X86::S_INDNTPOFF, "INDNTPOFF"},
    {MCSymbolRefExpr::VK_COFF_IMGREL32, "IMGREL"},
    {X86::S_NTPOFF, "NTPOFF"},
    {X86::S_PCREL, "PCREL"},
    {X86::S_PLT, "PLT"},
    {X86::S_PLTOFF, "PLTOFF"},
    {X86::S_COFF_SECREL, "SECREL32"},
    {X86::S_SIZE, "SIZE"},
    {X86::S_TLSCALL, "tlscall"},
    {X86::S_TLSDESC, "tlsdesc"},
    {X86::S_TLSGD, "TLSGD"},
    {X86::S_TLSLD, "TLSLD"},
    {X86::S_TLSLDM, "TLSLDM"},
    {X86::S_TLVP, "TLVP"},
    {X86::S_TLVPPAGE, "TLVPPAGE"},
    {X86::S_TLVPPAGEOFF, "TLVPPAGEOFF"},
    {X86::S_TPOFF, "TPOFF"},
}
Definition at line 37 of file X86MCAsmInfo.cpp.
MarkedJTDataRegions
cl::opt< bool > MarkedJTDataRegions("mark-data-regions", cl::init(true), cl::desc("Mark code section jump table data regions."), cl::Hidden) ("mark-data-regions" , cl::init(true) , cl::desc("Mark code section jump table data regions.") , cl::Hidden) static
Referenced by llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
X86AsmSyntax
cl::opt< AsmWriterFlavorTy > X86AsmSyntax("x86-asm-syntax", cl::init(ATT), cl::Hidden, cl::desc("Select the assembly style for input"), cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly"))) ("x86-asm-syntax" , cl::init(ATT) , cl::Hidden , cl::desc("Select the assembly style for input") , cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly"))) static
Referenced by llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().