LLVM: lib/Target/X86/X86PreTileConfig.cpp File Reference
X86PreTileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "x86-pre-tile-config"
Functions
static void emitErrorMsg (MachineFunction &MF)
INITIALIZE_PASS_BEGIN (X86PreTileConfigLegacy, "tilepreconfig", "Tile Register Pre-configure", false, false) INITIALIZE_PASS_END(X86PreTileConfigLegacy
Variables
tilepreconfig
Tile Register Pre configure
Tile Register Pre false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-pre-tile-config"
Definition at line 46 of file X86PreTileConfig.cpp.
Function Documentation
emitErrorMsg()
void emitErrorMsg (MachineFunction & MF) static
Definition at line 48 of file X86PreTileConfig.cpp.
References llvm::LLVMContext::emitError(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), and llvm::MachineFunction::getName().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86PreTileConfigLegacy , "tilepreconfig" , "Tile Register Pre-configure" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
Variable Documentation
configure
Tile Register Pre configure
Definition at line 236 of file X86PreTileConfig.cpp.
false
Tile Register Pre false
Definition at line 236 of file X86PreTileConfig.cpp.
tilepreconfig
tilepreconfig
Definition at line 235 of file X86PreTileConfig.cpp.