LLVM: lib/Target/X86/X86PartialReduction.cpp File Reference
X86PartialReduction.cpp File Reference
#include "X86.h"
#include "X86TargetMachine.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Analysis.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Pass.h"
#include "llvm/Support/KnownBits.h"
Macros
#define DEBUG_TYPE "x86-partial-reduction"
Functions
INITIALIZE_PASS (X86PartialReductionLegacy, DEBUG_TYPE, "X86 Partial Reduction", false, false) static bool matchVPDPBUSDPattern(const X86Subtarget *ST
if ((IsFreeTruncation(LHS) &&computeKnownBits(LHS, *DL).countMaxActiveBits()<=8) &&(IsFreeTruncation(RHS) &&ComputeMaxSignificantBits(RHS, *DL)<=8)) return true
static Value * matchAddReduction (const ExtractElementInst &EE, bool &ReduceInOneBB)
static bool isReachableFromPHI (PHINode *Phi, BinaryOperator *BO)
static void collectLeaves (Value *Root, SmallVectorImpl< Instruction * > &Leaves)
Variables
BinaryOperator * Mul
BinaryOperator const DataLayout * DL
Value * LHS = Mul->getOperand(0)
Value * RHS = Mul->getOperand(1)
if(isa< SExtInst >(LHS)) std auto IsFreeTruncation
return false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-partial-reduction"
Definition at line 31 of file X86PartialReduction.cpp.
Function Documentation
collectLeaves()
void collectLeaves (Value * Root, SmallVectorImpl< Instruction * > & Leaves) static
Definition at line 439 of file X86PartialReduction.cpp.
References llvm::append_range(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::PHINode::getNumIncomingValues(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), isReachableFromPHI(), P, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
if()
if ((IsFreeTruncation(LHS) &&computeKnownBits(LHS, *DL).countMaxActiveBits()<=8) &&(IsFreeTruncation(RHS) &&ComputeMaxSignificantBits(RHS, *DL)<=8))
References DL, LHS, and RHS.
INITIALIZE_PASS()
INITIALIZE_PASS (X86PartialReductionLegacy , DEBUG_TYPE , "X86 Partial Reduction" , false , false) const
References DEBUG_TYPE.
isReachableFromPHI()
bool isReachableFromPHI (PHINode * Phi, BinaryOperator * BO) static
Definition at line 420 of file X86PartialReduction.cpp.
References llvm::cast(), and llvm::BinaryOperator::getOpcode().
Referenced by collectLeaves().
matchAddReduction()
Value * matchAddReduction (const ExtractElementInst & EE, bool & ReduceInOneBB) static
Definition at line 358 of file X86PartialReduction.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ExtractElementInst::getIndexOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::ExtractElementInst::getVectorOperand(), llvm::isPowerOf2_32(), LHS, llvm::Log2_32(), and RHS.
Variable Documentation
DL
BinaryOperator const DataLayout* DL
Initial value:
{
  if (!ST->hasVNNI() && !ST->hasAVXVNNI())
    return false
Definition at line 76 of file X86PartialReduction.cpp.
false
return false
Definition at line 106 of file X86PartialReduction.cpp.
IsFreeTruncation
if (isa<SExtInst>(LHS)) std auto IsFreeTruncation
Initial value:
                      = [&](Value *Op) {
  if (auto *Cast = dyn_cast<CastInst>(Op)) {
    if (Cast->getParent() == Mul->getParent() &&
        (Cast->getOpcode() == Instruction::SExt ||
         Cast->getOpcode() == Instruction::ZExt) &&
        Cast->getOperand(0)->getType()->getScalarSizeInBits() <= 8)
      return true;
  }
  return isa<Constant>(Op);
}
Definition at line 86 of file X86PartialReduction.cpp.
Referenced by combineTruncatedArithmetic(), and detectExtMul().
LHS
Value* LHS = Mul->getOperand(0)
Definition at line 80 of file X86PartialReduction.cpp.
Referenced by llvm::KnownBits::add(), llvm::MachO::addEntry(), llvm::addEnumValues(), llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills(), adjustCostForPairing(), llvm::PatternMatch::AnyBinaryOp_match< LHS_t, RHS_t, Commutable >::AnyBinaryOp_match(), applyDivisibilityOnMinMaxExpr(), AreMulWideOperandsDemotable(), ascii_strncasecmp(), avgComputeU(), llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::BinaryOp_match(), llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::BinaryOp_match(), llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::BinaryOpc_match(), binaryOpKnownBitsMapHelper(), llvm::PatternMatch::BinOpPred_match< LHS_t, RHS_t, Predicate, Commutable >::BinOpPred_match(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::BitmapBegin(), BitOp3_Op(), BitOp3_Op(), BrPHIToSelect(), buildClonedLoops(), BuildIntrinsicOp(), buildMul(), buildMultiplyTree(), buildNonAtomicBinOp(), BuildVSLDOI(), calculateByteProvider(), calculateByteProvider(), canConvertSETCCToXori(), canConvertToVcmpequb(), canFoldTermCondOfLoop(), canonicalizeForInvariantConditionInjection(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleWithOp(), CanProveNotTakenFirstIteration(), llvm::detail::SlowDynamicAPInt::ceilDiv, llvm::DynamicAPInt::ceilDiv, checkAndReplaceCmp(), llvm::checkedAdd(), llvm::checkedAddUnsigned(), llvm::checkedMul(), llvm::checkedMulUnsigned(), llvm::checkedSub(), checkForNegativeOperand(), checkOrAndOpImpliedByOther(), llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::ClassifyOp_match(), llvm::PatternMatch::CmpClass_match< LHS_t, RHS_t, Class, Commutable >::CmpClass_match(), llvm::PatternMatch::CmpClass_match< LHS_t, RHS_t, Class, Commutable >::CmpClass_match(), collectBitParts(), collectDivisibilityInformation(), collectMultiplyFactors(), collectSingleShuffleElements(), collectUnswitchCandidatesWithInjections(), combine_CC(), combine_CC(), combineADC(), combineAddOfPMADDWD(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineADDToSUB(), combineAnd(), CombineBaseUpdate(), combineBinOpOfExtractToReduceTree(), combineBitOpWithPACK(), combineCastedMaskArithmetic(), combineConcatVectorOps(), combineFaddCFmul(), combineFMulcFCMulc(), combineHorizOpWithShuffle(), combineMinNumMaxNumImpl(), combineOp_VLToVWOp_VL(), combineOrCmpEqZeroToCtlzSrl(), combinePExtTruncate(), combinePMULDQ(), combinePMULH(), combinePossibleConstantValues(), combinePredicateReduction(), combineSBB(), combineSelect(), combineSelectOfTwoConstants(), combineSelectToBinOp(), combineSetCC(), combineSetCCMOVMSK(), combineShiftToPMULH(), combineTargetShuffle(), combineToHorizontalAddSub(), combineVectorCompare(), combineVectorHADDSUB(), combineVectorShiftImm(), combineVPDPBUSDPattern(), combineVPMADD(), combineX86AddSub(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), combineXor(), llvm::PatternMatch::CommutativeBinaryIntrinsic_match< IntrID, LHS, RHS >::CommutativeBinaryIntrinsic_match(), commuteSelect(), llvm::PartialOrderingVisitor::compare(), llvm::sandboxir::FCmpInst::compare(), llvm::sandboxir::ICmpInst::compare(), compareByScalarFnName(), compareByVectorFnName(), CompareMBBNumbers(), CompareMBBNumbers(), compareMbbNumbers(), compareMBBPriority(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::CompareOp_match(), CompareSCEVComplexity(), compareWithScalarFnName(), computeForAddCarry(), computeForSatAddSub(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPMADDWD(), computeKnownBitsForPSADBW(), computeKnownBitsFromCmp(), computeKnownBitsFromICmpCond(), computeKnownBitsFromLerpPattern(), computeKnownBitsFromOperator(), computeKnownFPClass(), computeKnownFPClassFromCond(), computeNumSignBitsBinOp(), ComputeNumSignBitsImpl(), computeOverflowForSignedAdd(), llvm::InstCombiner::computeOverflowForSignedAdd(), llvm::InstCombiner::computeOverflowForSignedMul(), llvm::InstCombiner::computeOverflowForSignedSub(), llvm::InstCombiner::computeOverflowForUnsignedAdd(), llvm::InstCombiner::computeOverflowForUnsignedMul(), llvm::InstCombiner::computeOverflowForUnsignedSub(), computePointerDifference(), computePointerICmp(), computeShlNSW(), computeShlNUW(), ConcatListInits(), constantFoldBinOpWithSplat(), constantFoldUser(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get(), constantIntSortPredicate(), llvm::sandboxir::BinaryOperator::Context, llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo(), llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo(), ConvertSelectToConcatVector(), ConvertSETCCToXori(), countToEliminateCompares(), llvm::FixedPointBuilder< IRBuilderTy >::CreateAdd(), llvm::IRBuilderBase::CreateAdd(), llvm::MatrixBuilder::CreateAdd(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateAnd(), llvm::VPBuilder::createAnd(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateBinOpFMF(), llvm::IRBuilderBase::CreateCmp(), llvm::IRBuilderBase::CreateCopySign(), llvm::FixedPointBuilder< IRBuilderTy >::CreateDiv(), llvm::FixedPointBuilder< IRBuilderTy >::CreateEQ(), llvm::IRBuilderBase::CreateExactSDiv(), llvm::IRBuilderBase::CreateExactUDiv(), llvm::IRBuilderBase::CreateFCmp(), llvm::IRBuilderBase::CreateFCmpFMF(), llvm::IRBuilderBase::CreateFCmpOEQ(), llvm::IRBuilderBase::CreateFCmpOGE(), llvm::IRBuilderBase::CreateFCmpOGT(), llvm::IRBuilderBase::CreateFCmpOLE(), llvm::IRBuilderBase::CreateFCmpOLT(), llvm::IRBuilderBase::CreateFCmpONE(), llvm::IRBuilderBase::CreateFCmpORD(), llvm::IRBuilderBase::CreateFCmpS(), llvm::IRBuilderBase::CreateFCmpUEQ(), llvm::IRBuilderBase::CreateFCmpUGE(), llvm::IRBuilderBase::CreateFCmpUGT(), llvm::IRBuilderBase::CreateFCmpULE(), llvm::IRBuilderBase::CreateFCmpULT(), llvm::IRBuilderBase::CreateFCmpUNE(), llvm::IRBuilderBase::CreateFCmpUNO(), createFPCmp(), llvm::FixedPointBuilder< IRBuilderTy >::CreateGE(), llvm::FixedPointBuilder< IRBuilderTy >::CreateGT(), llvm::IRBuilderBase::CreateICmp(), llvm::IRBuilderBase::CreateICmpEQ(), llvm::IRBuilderBase::CreateICmpNE(), llvm::IRBuilderBase::CreateICmpSGE(), llvm::IRBuilderBase::CreateICmpSGT(), llvm::IRBuilderBase::CreateICmpSLE(), llvm::IRBuilderBase::CreateICmpSLT(), llvm::IRBuilderBase::CreateICmpUGE(), llvm::IRBuilderBase::CreateICmpUGT(), llvm::IRBuilderBase::CreateICmpULE(), llvm::IRBuilderBase::CreateICmpULT(), llvm::FixedPointBuilder< IRBuilderTy >::CreateLE(), llvm::VPBuilder::createLogicalAnd(), createLogicalOp(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateLShr(), llvm::FixedPointBuilder< IRBuilderTy >::CreateLT(), llvm::MatrixBuilder::CreateMatrixMultiply(), llvm::IRBuilderBase::CreateMaximum(), llvm::IRBuilderBase::CreateMaximumNum(), llvm::IRBuilderBase::CreateMaxNum(), llvm::IRBuilderBase::CreateMinimum(), llvm::IRBuilderBase::CreateMinimumNum(), llvm::IRBuilderBase::CreateMinNum(), llvm::FixedPointBuilder< IRBuilderTy >::CreateMul(), llvm::IRBuilderBase::CreateMul(), llvm::FixedPointBuilder< IRBuilderTy >::CreateNE(), llvm::IRBuilderBase::CreateNSWAdd(), llvm::IRBuilderBase::CreateNSWMul(), llvm::IRBuilderBase::CreateNSWSub(), llvm::IRBuilderBase::CreateNUWAdd(), llvm::IRBuilderBase::CreateNUWMul(), llvm::IRBuilderBase::CreateNUWSub(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateOr(), llvm::VPBuilder::createOr(), createReplacement(), llvm::MatrixBuilder::CreateScalarDiv(), llvm::MatrixBuilder::CreateScalarMultiply(), llvm::IRBuilderBase::CreateSDiv(), llvm::FixedPointBuilder< IRBuilderTy >::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::FixedPointBuilder< IRBuilderTy >::CreateShr(), llvm::IRBuilderBase::CreateSRem(), llvm::FixedPointBuilder< IRBuilderTy >::CreateSub(), llvm::IRBuilderBase::CreateSub(), llvm::MatrixBuilder::CreateSub(), llvm::IRBuilderBase::CreateUDiv(), llvm::IRBuilderBase::CreateURem(), createVPDPBUSD(), llvm::IRBuilderBase::CreateXor(), llvm::IRBuilderBase::CreateXor(), llvm::IRBuilderBase::CreateXor(), DAGCombineAddc(), llvm::CachedHashString::DenseMapInfo< CachedHashString >, determineLiveOperandBitsAddCarry(), llvm::PatternMatch::DisjointOr_match< LHS, RHS, Commutable >::DisjointOr_match(), divComputeLowBit(), llvm::dump(), dumpUnpackedICmp(), earlyExpandDIVFIX(), EliminateDuplicatePHINodesSetBasedImpl(), EmitAbsDifference(), EmitAVX512Test(), EmitCMP(), emitComparison(), emitConditionalComparison(), emitConjunctionRec(), emitFloatCompareMask(), emitSelectPseudo(), emitSelectPseudo(), emitStrictFPComparison(), emitVectorComparison(), equalsLoadStoreHelper(), estimateBitMaskedAndLowerBound(), evalBinaryInstruction(), EvaluateInDifferentTypeImpl(), ExpandBasePaths(), expandDivFix(), expandMemCpy(), expandPow(), ExpandPowI(), extractEquivalentCondition(), factorizeMinMaxTree(), llvm::fcmpImpliesClass(), llvm::fcmpImpliesClass(), llvm::fcmpImpliesClass(), llvm::fcmpImpliesClass(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::fcmpToClassTest(), llvm::fcmpToClassTest(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpToClassTest(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpToClassTest(), FilterHelper(), findBaseObject(), findFuncPointers(), llvm::detail::SlowDynamicAPInt::floorDiv, llvm::DynamicAPInt::floorDiv, foldADCToCINC(), foldAndOrOfICmpEqConstantAndICmp(), foldAndOrOfICmpsWithPow2AndWithZero(), foldAndOrOfSETCC(), llvm::ConstantFolder::FoldBinaryIntrinsic(), llvm::InstSimplifyFolder::FoldBinaryIntrinsic(), llvm::IRBuilderFolder::FoldBinaryIntrinsic(), llvm::NoFolder::FoldBinaryIntrinsic(), llvm::TargetFolder::FoldBinaryIntrinsic(), llvm::ConstantFolder::FoldBinOp(), llvm::InstSimplifyFolder::FoldBinOp(), llvm::IRBuilderFolder::FoldBinOp(), llvm::NoFolder::FoldBinOp(), llvm::TargetFolder::FoldBinOp(), llvm::ConstantFolder::FoldBinOpFMF(), llvm::InstSimplifyFolder::FoldBinOpFMF(), llvm::IRBuilderFolder::FoldBinOpFMF(), llvm::NoFolder::FoldBinOpFMF(), llvm::TargetFolder::FoldBinOpFMF(), llvm::ConstantFolder::FoldCmp(), llvm::InstSimplifyFolder::FoldCmp(), llvm::IRBuilderFolder::FoldCmp(), llvm::NoFolder::FoldCmp(), llvm::TargetFolder::FoldCmp(), llvm::ConstantFolder::FoldExactBinOp(), llvm::InstSimplifyFolder::FoldExactBinOp(), llvm::IRBuilderFolder::FoldExactBinOp(), llvm::NoFolder::FoldExactBinOp(), llvm::TargetFolder::FoldExactBinOp(), foldFCmpWithFloorAndCeil(), foldICmpOfCmpIntrinsicWithConstant(), foldIntrinsicUsingDistributiveLaws(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::ConstantFolder::FoldNoWrapBinOp(), llvm::InstSimplifyFolder::FoldNoWrapBinOp(), llvm::IRBuilderFolder::FoldNoWrapBinOp(), llvm::NoFolder::FoldNoWrapBinOp(), llvm::TargetFolder::FoldNoWrapBinOp(), foldReductionIdiom(), foldVectorCmp(), foldXor1SetCC(), ForeachDagApply(), ForeachHelper(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), generateComparison(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), getAArch64Cmp(), getAArch64XALUOOp(), GetAbsDifference(), llvm::ScalarEvolution::getAddExpr(), getAllDBDirs(), getBinOpsForFactorization(), getBitSelect(), getExactSDiv(), getFCmpValue(), llvm::InstrProfSymtab::getFuncOrVarName(), llvm::InstrProfSymtab::getFunction(), getHashValueImpl(), getIVIncrement(), getMaskedTypeForICmpPair(), getMul64(), llvm::ScalarEvolution::getMulExpr(), getMulHu(), getNewICmpValue(), getOperandsForBranch(), GetOptionalAbsDifference(), GetOptionalAbsDifference(), getPack(), llvm::ScaledNumbers::getProduct(), llvm::ScaledNumbers::getProduct32(), llvm::ScaledNumbers::getProduct64(), getRangeForSelectPattern(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSetCCVP(), getSortedConstantKeys(), getSplitVectorSrc(), GetSubDivExpr(), getTruncatedUSUBSAT(), llvm::getUnitForOffset(), getValueOnFirstIteration(), getX86XALUOOp(), GroupByComplexity(), hasHazard(), hasIdenticalMMOs(), hasNonZeroFPOperands(), llvm::KnownBits::haveNoCommonBitsSet(), haveNoCommonBitsSetSpecialCases(), hoistAddSub(), hoistMinMax(), hoistMulAddAssociation(), llvm::ICmpInst::ICmpInst(), llvm::ICmpInst::ICmpInst(), if(), impliesPoisonOrCond(), inferInitializes(), injectPendingInvariantConditions(), insertCandidatesWithPendingInjections(), instCombineSVELast(), llvm::FastMathFlags::intersectRewrite(), isAddSubOrSubAdd(), isDivisibilityGuard(), llvm::AnonStructTypeKeyInfo::isEqual(), llvm::AnonStructTypeKeyInfo::isEqual(), llvm::ConcurrentHashTableInfoByPtr< KeyTy, KeyDataTy, AllocatorTy >::isEqual(), llvm::DenseMapInfo< AA::ValueAndContext >::isEqual(), llvm::DenseMapInfo< AA::ValueScope >::isEqual(), llvm::DenseMapInfo< AACacheLoc >::isEqual(), llvm::DenseMapInfo< AAMDNodes >::isEqual(), llvm::DenseMapInfo< APFixedPoint >::isEqual(), llvm::DenseMapInfo< APFloat >::isEqual(), llvm::DenseMapInfo< APInt, void >::isEqual(), llvm::DenseMapInfo< APSInt, void >::isEqual(), llvm::DenseMapInfo< ArrayRef< T >, void >::isEqual(), llvm::DenseMapInfo< Attribute::AttrKind >::isEqual(), llvm::DenseMapInfo< AttributeList, void >::isEqual(), llvm::DenseMapInfo< AttributeSet, void >::isEqual(), llvm::DenseMapInfo< BasicBlock::iterator >::isEqual(), llvm::DenseMapInfo< BasicBlockEdge >::isEqual(), llvm::DenseMapInfo< BitVector >::isEqual(), llvm::DenseMapInfo< CachedHashString >::isEqual(), llvm::DenseMapInfo< cas::CASID >::isEqual(), llvm::DenseMapInfo< cas::ObjectRef >::isEqual(), llvm::DenseMapInfo< char >::isEqual(), llvm::DenseMapInfo< codeview::GloballyHashedType >::isEqual(), llvm::DenseMapInfo< codeview::LocallyHashedType >::isEqual(), llvm::DenseMapInfo< codeview::TypeIndex >::isEqual(), llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::isEqual(), llvm::DenseMapInfo< const AA::InstExclusionSetTy * >::isEqual(), llvm::DenseMapInfo< coverage::CounterExpression >::isEqual(), llvm::DenseMapInfo< ElementCount, void >::isEqual(), llvm::DenseMapInfo< Enum, std::enable_if_t< std::is_enum_v< Enum > > >::isEqual(), llvm::DenseMapInfo< FixedPointSemantics >::isEqual(), llvm::DenseMapInfo< gsym::FileEntry >::isEqual(), llvm::DenseMapInfo< hash_code, void >::isEqual(), llvm::DenseMapInfo< LLT >::isEqual(), llvm::DenseMapInfo< llvm::SmallVector< T, N > >::isEqual(), llvm::DenseMapInfo< llvm::sys::fs::UniqueID >::isEqual(), llvm::DenseMapInfo< LocationSize >::isEqual(), llvm::DenseMapInfo< MachineOperand >::isEqual(), llvm::DenseMapInfo< MBBSectionID >::isEqual(), llvm::DenseMapInfo< MCRegister >::isEqual(), llvm::DenseMapInfo< MemoryLocation >::isEqual(), llvm::DenseMapInfo< minidump::StreamType >::isEqual(), llvm::DenseMapInfo< OffsetAndUnitID >::isEqual(), llvm::DenseMapInfo< omp::TraitProperty >::isEqual(), llvm::DenseMapInfo< orc::AllocGroup >::isEqual(), llvm::DenseMapInfo< orc::ExecutorAddr >::isEqual(), llvm::DenseMapInfo< orc::MemProt >::isEqual(), llvm::DenseMapInfo< orc::NonOwningSymbolStringPtr >::isEqual(), llvm::DenseMapInfo< orc::SymbolStringPtr >::isEqual(), llvm::DenseMapInfo< PointerEmbeddedInt< IntT, Bits > >::isEqual(), llvm::DenseMapInfo< PointerIntPair< PointerTy, IntBits, IntType >, void >::isEqual(), llvm::DenseMapInfo< PointerSumType< TagT, MemberTs... > >::isEqual(), llvm::DenseMapInfo< PointerUnion< PTs... > >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< Register >::isEqual(), llvm::DenseMapInfo< SampleContext >::isEqual(), llvm::DenseMapInfo< sampleprof::FunctionId, void >::isEqual(), llvm::DenseMapInfo< sandboxir::Context::CallbackID >::isEqual(), llvm::DenseMapInfo< ScalarEvolution::FoldID >::isEqual(), llvm::DenseMapInfo< SDValue >::isEqual(), llvm::DenseMapInfo< SmallBitVector >::isEqual(), llvm::DenseMapInfo< std::optional< T > >::isEqual(), llvm::DenseMapInfo< std::pair< T, U > >::isEqual(), llvm::DenseMapInfo< std::variant< Ts... > >::isEqual(), llvm::DenseMapInfo< StringRef, void >::isEqual(), llvm::DenseMapInfo< SymbolsMapKey >::isEqual(), llvm::DenseMapInfo< T * >::isEqual(), llvm::DenseMapInfo< T, std::enable_if_t< std::is_integral_v< T > &&!std::is_same_v< T, char > > >::isEqual(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::isEqual(), llvm::DenseMapInfo< UniqueBBID >::isEqual(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::DenseMapInfo< VersionTuple >::isEqual(), llvm::DenseMapInfo< wasm::WasmGlobalType, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmLimits, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmSignature, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmTableType, void >::isEqual(), llvm::DenseMapInfo< WeakVH >::isEqual(), llvm::DIArgListInfo::isEqual(), llvm::DIArgListInfo::isEqual(), llvm::dwarf_linker::classic::DeclMapInfo::isEqual(), llvm::dwarf_linker::parallel::TypeEntryInfo::isEqual(), llvm::dwarf_linker::StringPoolEntryInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), llvm::ImutContainerInfo< T >::isEqual(), llvm::ImutContainerInfo< T * >::isEqual(), llvm::IRSimilarity::IRInstructionDataTraits::isEqual(), llvm::MachineInstrExpressionTrait::isEqual(), llvm::MDNodeInfo< NodeTy >::isEqual(), llvm::MDNodeInfo< NodeTy >::isEqual(), llvm::TargetExtTypeKeyInfo::isEqual(), llvm::TargetExtTypeKeyInfo::isEqual(), isEqualImpl(), isHorizontalBinOp(), isICmpTrue(), isImpliedCondAndOr(), isIVIncrement(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownGE(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownGT(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownLE(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownLT(), isKnownPredicateExtendIdiom(), IsKnownPredicateViaAddRecStart(), IsKnownPredicateViaMinOrMax(), isLaneMaskFromSameBlock(), isLegalToCombineMinNumMaxNum(), llvm::ImutContainerInfo< T >::isLess(), llvm::ImutContainerInfo< T * >::isLess(), isLowerSaturate(), isLowerSaturatingConditional(), isNonEscapingGlobalNoAliasWithLoad(), isProcessableCondBI(), isSameCompare(), isSameReg(), isSignedMinMaxClamp(), isSSATMinMaxPattern(), llvm::MDNodeSubsetEqualImpl< NodeTy >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< NodeTy >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual(), isTruePredicate(), ItemApply(), legalizeFCmpPredicate(), llvm::dwarf_linker::classic::DWARFLinker::link(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMBuildAdd(), LLVMBuildAnd(), LLVMBuildAShr(), LLVMBuildBinOp(), LLVMBuildExactSDiv(), LLVMBuildExactUDiv(), LLVMBuildFAdd(), LLVMBuildFCmp(), LLVMBuildFDiv(), LLVMBuildFMul(), LLVMBuildFRem(), LLVMBuildFSub(), LLVMBuildICmp(), LLVMBuildLShr(), LLVMBuildMul(), LLVMBuildNSWAdd(), LLVMBuildNSWMul(), LLVMBuildNSWSub(), LLVMBuildNUWAdd(), LLVMBuildNUWMul(), LLVMBuildNUWSub(), LLVMBuildOr(), LLVMBuildPtrDiff2(), LLVMBuildSDiv(), LLVMBuildShl(), LLVMBuildSRem(), LLVMBuildSub(), LLVMBuildUDiv(), LLVMBuildURem(), LLVMBuildXor(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::LogicalOp_match(), LookThroughSetCC(), lookupLLVMIntrinsicByName(), LookupNearestOption(), LowerABD(), lowerAddSubToHorizontalOp(), LowerAndToBTST(), lowerAtomicArith(), LowerBR_CC(), lowerBuildVectorToBitOp(), lowerConstrainedFPCmpIntrinsic(), LowerCTPOP(), llvm::TargetLoweringObjectFile::lowerDSOLocalEquivalent(), lowerICMPIntrinsic(), lowerOverflowArithmetic(), llvm::TargetLoweringObjectFile::lowerRelativeReference(), LowerSELECT_CC(), lowerSelectToBinOp(), LowerSELECTWithCmpZero(), LowerSETCCCARRY(), lowerShuffleAsLanePermuteAndSHUFP(), LowerVectorAllEqual(), lowerVSELECTtoVectorShuffle(), llvm::PatternMatch::m_Add(), llvm::SDPatternMatch::m_Add(), llvm::PatternMatch::m_AddLike(), llvm::SDPatternMatch::m_AddLike(), llvm::PatternMatch::m_And(), llvm::SDPatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_AShrOrSelf(), llvm::MIPatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::SDPatternMatch::m_BinOp(), llvm::PatternMatch::m_BitwiseLogic(), llvm::SDPatternMatch::m_BitwiseLogic(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::SDPatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_BitwiseLogic(), llvm::SDPatternMatch::m_c_ChainedBinOp(), llvm::PatternMatch::m_c_DisjointOr(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_c_FMul(), llvm::MIPatternMatch::m_c_GFCmp(), llvm::MIPatternMatch::m_c_GICmp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOp(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_c_MaxOrMin(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_c_NSWAdd(), llvm::PatternMatch::m_c_NUWAdd(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Select(), llvm::SDPatternMatch::m_c_SetCC(), llvm::PatternMatch::m_c_SMax(), llvm::PatternMatch::m_c_SMin(), llvm::PatternMatch::m_c_SpecificICmp(), llvm::PatternMatch::m_c_UMax(), llvm::PatternMatch::m_c_UMin(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_c_XorLike(), llvm::SDPatternMatch::m_ChainedBinOp(), llvm::SDPatternMatch::m_Clmul(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Cmp(), llvm::MIPatternMatch::m_CommutativeBinOp(), llvm::PatternMatch::m_DisjointOr(), llvm::SDPatternMatch::m_DisjointOr(), llvm::SDPatternMatch::m_ExactSr(), llvm::SDPatternMatch::m_ExtractElt(), llvm::SDPatternMatch::m_ExtractSubvector(), llvm::PatternMatch::m_FAdd(), llvm::SDPatternMatch::m_FAdd(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_FDiv(), llvm::SDPatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::SDPatternMatch::m_FMul(), llvm::PatternMatch::m_FRem(), llvm::SDPatternMatch::m_FRem(), llvm::PatternMatch::m_FSub(), llvm::SDPatternMatch::m_FSub(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GAddLike(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_GAShr(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GBuildVectorTrunc(), llvm::MIPatternMatch::m_GDisjointOr(), llvm::MIPatternMatch::m_GFAdd(), llvm::MIPatternMatch::m_GFCmp(), llvm::MIPatternMatch::m_GFMul(), llvm::MIPatternMatch::m_GFSub(), llvm::MIPatternMatch::m_GICmp(), llvm::MIPatternMatch::m_GIsFPClass(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GMul(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GSMax(), llvm::MIPatternMatch::m_GSMin(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_GUMax(), llvm::MIPatternMatch::m_GUMin(), llvm::MIPatternMatch::m_GXor(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_IDiv(), llvm::SDPatternMatch::m_InsertSubvector(), llvm::PatternMatch::m_IRem(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOp(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_LShrOrSelf(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Mul(), llvm::SDPatternMatch::m_Mul(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_NUWAdd(), llvm::PatternMatch::m_NUWAddLike(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_Or(), llvm::SDPatternMatch::m_Or(), llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_OrdOrUnordFMax(), llvm::PatternMatch::m_OrdOrUnordFMin(), llvm::SDPatternMatch::m_Rotl(), llvm::SDPatternMatch::m_Rotr(), llvm::SCEVPatternMatch::m_scev_URem(), llvm::PatternMatch::m_SDiv(), llvm::SDPatternMatch::m_SDiv(), llvm::PatternMatch::m_Select(), llvm::SDPatternMatch::m_SetCC(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Shl(), llvm::SDPatternMatch::m_Shl(), llvm::PatternMatch::m_ShlOrSelf(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SMax(), llvm::SDPatternMatch::m_SMax(), llvm::SDPatternMatch::m_SMaxLike(), llvm::PatternMatch::m_SMin(), llvm::SDPatternMatch::m_SMin(), llvm::SDPatternMatch::m_SMinLike(), llvm::PatternMatch::m_SpecificCmp(), llvm::PatternMatch::m_SpecificFCmp(), llvm::PatternMatch::m_SpecificICmp(), llvm::SDPatternMatch::m_Sra(), llvm::PatternMatch::m_SRem(), llvm::SDPatternMatch::m_SRem(), llvm::SDPatternMatch::m_Srl(), llvm::PatternMatch::m_Sub(), llvm::SDPatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::SDPatternMatch::m_UDiv(), llvm::PatternMatch::m_UMax(), llvm::SDPatternMatch::m_UMax(), llvm::SDPatternMatch::m_UMaxLike(), llvm::PatternMatch::m_UMin(), llvm::SDPatternMatch::m_UMin(), llvm::SDPatternMatch::m_UMinLike(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_URem(), llvm::SDPatternMatch::m_URem(), llvm::PatternMatch::m_Xor(), llvm::SDPatternMatch::m_Xor(), makeStartPlusIntExpr(), markAliveBlocks(), llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::match(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match(), llvm::SDPatternMatch::SpecificNeg_match::match(), matchAddReduction(), MatchBinarySub(), matchFastFloatClamp(), matchICmpOperand(), matchIncrement(), matchIsFiniteTest(), matchIsNotNaN(), matchMinMax(), llvm::matchSelectPattern(), matchSelectPattern(), matchSetCC(), matchSetCC(), matchSymmetricPhiNodesPair(), matchTwoInputRecurrence(), matchUnorderedInfCompare(), MatchVectorAllEqualTest(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::MaxMin_match(), mayUseP9Setb(), llvm::SMTSolver::mkAnd(), llvm::SMTSolver::mkBVAdd(), llvm::SMTSolver::mkBVAddNoOverflow(), llvm::SMTSolver::mkBVAddNoUnderflow(), llvm::SMTSolver::mkBVAnd(), llvm::SMTSolver::mkBVAshr(), llvm::SMTSolver::mkBVConcat(), llvm::SMTSolver::mkBVLshr(), llvm::SMTSolver::mkBVMul(), llvm::SMTSolver::mkBVMulNoOverflow(), llvm::SMTSolver::mkBVMulNoUnderflow(), llvm::SMTSolver::mkBVOr(), llvm::SMTSolver::mkBVSDiv(), llvm::SMTSolver::mkBVSDivNoOverflow(), llvm::SMTSolver::mkBVSge(), llvm::SMTSolver::mkBVSgt(), llvm::SMTSolver::mkBVShl(), llvm::SMTSolver::mkBVSle(), llvm::SMTSolver::mkBVSlt(), llvm::SMTSolver::mkBVSRem(), llvm::SMTSolver::mkBVSub(), llvm::SMTSolver::mkBVSubNoOverflow(), llvm::SMTSolver::mkBVSubNoUnderflow(), llvm::SMTSolver::mkBVUDiv(), llvm::SMTSolver::mkBVUge(), llvm::SMTSolver::mkBVUgt(), llvm::SMTSolver::mkBVUle(), llvm::SMTSolver::mkBVUlt(), llvm::SMTSolver::mkBVURem(), llvm::SMTSolver::mkBVXor(), llvm::SMTSolver::mkEqual(), llvm::SMTSolver::mkFPAdd(), llvm::SMTSolver::mkFPDiv(), llvm::SMTSolver::mkFPEqual(), llvm::SMTSolver::mkFPGe(), llvm::SMTSolver::mkFPGt(), llvm::SMTSolver::mkFPLe(), llvm::SMTSolver::mkFPLt(), llvm::SMTSolver::mkFPMul(), llvm::SMTSolver::mkFPRem(), llvm::SMTSolver::mkFPSub(), llvm::SMTSolver::mkOr(), llvm::DynamicAPInt::mod, narrowSDivOrSRem(), narrowUDivOrURem(), needsLFTR(), NegateCC(), llvm::cas::CASID::operator!=, llvm::cas::ObjectHandle::operator!=, llvm::cas::ObjectRef::operator!=, llvm::cas::ondisk::ObjectHandle::operator!=, llvm::cas::ondisk::ObjectID::operator!=, llvm::codeview::operator!=(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator!=, llvm::detail::operator!=(), llvm::fallible_iterator< ChildFallibleIterator >::operator!=, llvm::gsym::operator!=(), llvm::gsym::operator!=(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator!=, llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator!=, llvm::IntervalTree< PointT, ValueT, DataT >::find_iterator::operator!=, llvm::json::operator!=(), llvm::line_iterator::operator!=, llvm::MachineMemOperand::operator!=, llvm::MachO::operator!=(), llvm::MachO::operator!=(), llvm::MemoryBufferRef::operator!=, llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::opt::arg_iterator< arglist_type::iterator >::operator!=, llvm::orc::AllocGroup::operator!=, llvm::orc::ExecutorAddr::operator!=, llvm::orc::ExecutorAddrRange::operator!=, llvm::orc::ExecutorSymbolDef::operator!=, llvm::orc::SymbolStringPtrBase::operator!=, llvm::PagedVector< T, PageSize >::MaterializedIterator::operator!=, llvm::remarks::operator!=(), llvm::remarks::operator!=(), llvm::remarks::operator!=(), llvm::sampleprof::operator!=(), llvm::StringMapIterBase< ValueTy, true >::operator!=, llvm::StringTable::Offset::operator!=, llvm::wasm::operator!=(), llvm::wasm::operator!=(), llvm::orc::operator%(), llvm::BitmaskEnumDetail::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::BitmaskEnumDetail::operator&=(), llvm::operator&=(), llvm::operator&=(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertionInfo::Compare::operator()(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::LessRecordByID::operator()(), llvm::RISCVISAUtils::ExtensionComparator::operator()(), llvm::sampleprof::SampleRecord::CallTargetComparator::operator()(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator*, llvm::operator*(), llvm::operator*(), llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator*=, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator+, llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::orc::operator+(), llvm::orc::operator+(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator+=, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-, llvm::operator-(), llvm::operator-(), llvm::operator-(), llvm::orc::operator-(), llvm::orc::operator-(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-=, llvm::operator/(), llvm::at::VarRecord::operator<, llvm::Bitset< AEK_NUM_EXTENSIONS >::operator<(), llvm::codeview::operator<(), llvm::coverage::Counter::operator<, llvm::EntryValueInfo::operator<, llvm::FeatureBitset::operator<(), llvm::FrameIndexExpr::operator<, llvm::gsym::operator<(), llvm::gsym::operator<(), llvm::IntrinsicData::operator<, llvm::iterator_adaptor_base< IteratorImpl< ValueT, IteratorBase >, IteratorBase, std::bidirectional_iterator_tag, ValueT >::operator<, llvm::MachO::operator<(), llvm::object::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::orc::AllocGroup::operator<, llvm::orc::ExecutorAddr::operator<, llvm::orc::ExecutorAddrRange::operator<, llvm::orc::SymbolStringPtrBase::operator<, llvm::reassociate::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::sampleprof::operator<(), operator<(), operator<(), operator<(), llvm::BitmaskEnumDetail::operator<<(), llvm::codeview::operator<=(), llvm::operator<=(), llvm::operator<=(), llvm::orc::ExecutorAddr::operator<=, llvm::orc::ExecutorAddrRange::operator<=, llvm::sampleprof::operator<=(), llvm::GVNPass::ValueTable::operator=(), llvm::SPIRV::ConvergenceRegionInfo::operator=(), llvm::SPIRV::ConvergenceRegionInfo::operator=(), llvm::at::VarRecord::operator==, llvm::BinaryStreamRefBase< RefType, StreamType >::operator==, llvm::cas::CASID::operator==, llvm::cas::ObjectHandle::operator==, llvm::cas::ObjectRef::operator==, llvm::cas::ondisk::InternalRef::operator==, llvm::cas::ondisk::ObjectHandle::operator==, llvm::cas::ondisk::ObjectID::operator==, llvm::codeview::operator==(), llvm::coverage::Counter::operator==, llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator==, llvm::detail::operator==(), llvm::DWARFDebugNames::AttributeEncoding::operator==, llvm::DWARFDie::attribute_iterator::operator==, llvm::DWARFDie::iterator::operator==, llvm::DWARFExpression::iterator::operator==, llvm::early_inc_iterator_impl< WrappedIteratorT >::operator==, llvm::fallible_iterator< ChildFallibleIterator >::operator==, llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator==, llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator==, llvm::IntervalTree< PointT, ValueT, DataT >::find_iterator::operator==, llvm::iterator_adaptor_base< IteratorImpl< ValueT, IteratorBase >, IteratorBase, std::bidirectional_iterator_tag, ValueT >::operator==, llvm::json::Object::operator==, llvm::line_iterator::operator==, llvm::MachineMemOperand::operator==, llvm::MachO::operator==(), llvm::MachO::operator==(), llvm::MemoryBufferRef::operator==, llvm::minidump::operator==(), llvm::object::operator==(), llvm::object::SFrameParser< E >::FallibleFREIterator::operator==, llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::opt::arg_iterator< arglist_type::iterator >::operator==, llvm::orc::AllocGroup::operator==, llvm::orc::ExecutorAddr::operator==, llvm::orc::ExecutorAddrRange::operator==, llvm::orc::ExecutorSymbolDef::operator==, llvm::orc::SymbolStringPtrBase::operator==, llvm::PagedVector< T, PageSize >::MaterializedIterator::operator==, llvm::remarks::operator==(), llvm::remarks::operator==(), llvm::remarks::operator==(), llvm::sampleprof::operator==(), llvm::SMTExpr::operator==, llvm::SMTSort::operator==, llvm::StringMapIterBase< ValueTy, true >::operator==, llvm::StringTable::Offset::operator==, llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::yaml::BinaryRef::operator==, operator==(), llvm::codeview::operator>(), llvm::operator>(), llvm::operator>(), llvm::orc::ExecutorAddr::operator>, llvm::orc::ExecutorAddrRange::operator>, llvm::sampleprof::operator>(), llvm::codeview::operator>=(), llvm::operator>=(), llvm::operator>=(), llvm::orc::ExecutorAddr::operator>=, llvm::orc::ExecutorAddrRange::operator>=, llvm::sampleprof::operator>=(), llvm::BitmaskEnumDetail::operator>>(), llvm::BitmaskEnumDetail::operator^(), llvm::operator^(), llvm::operator^(), llvm::operator^(), llvm::operator^(), llvm::BitmaskEnumDetail::operator^=(), llvm::BitmaskEnumDetail::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::BitmaskEnumDetail::operator|=(), llvm::operator|=(), llvm::operator|=(), optimizeLoopExitWithUnknownExitCount(), optimizeMaskToEVL(), optimizeMemCmpConstantSize(), optimizeMemCmpVarSize(), OptimizeNonTrivialIFuncs(), OptNameCompare(), llvm::DWARFDebugLine::Row::orderByAddress(), llvm::DWARFDebugLine::Sequence::orderByHighPC(), llvm::PatternMatch::OverflowingBinaryOp_match< LHS_t, RHS_t, Opcode, WrapFlags, Commutable >::OverflowingBinaryOp_match(), AbstractManglingParser< Derived, Alloc >::parseBinaryExpr(), parseCondition(), AbstractManglingParser< Derived, Alloc >::parseExpr(), llvm::PartialOrderingVisitor::PartialOrderingVisitor(), performAddCombineForShiftedOperands(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), performAddSubLongCombine(), performAddUADDVCombine(), performANDCombine(), performAnyAllCombine(), performBR_CCCombine(), performBRCONDCombine(), performFADDCombine(), PerformFADDVCMLACombine(), performFlagSettingCombine(), performINSERT_VECTOR_ELTCombine(), performMulCombine(), performOrXorChainCombine(), performSELECT_CCCombine(), PerformSELECTCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), performSETCCCombine(), performSetccMergeZeroCombine(), performSetCCPunpkCombine(), performSHLCombine(), performVP_TRUNCATECombine(), PerformVQDMULHCombine(), PerformVSELECTCombine(), populateReductionFunction(), processAnd(), processUMulZExtIdiom(), ProfileBinOpInit(), ProfileTernOpInit(), reassociateMinMaxWithConstants(), rebuildLoopAfterUnswitch(), reduceVSXSwap(), llvm::PatternMatch::ShiftLike_match< LHS_t, Opcode >::ShiftLike_match(), shorter_filter(), shouldBeAdjustedToZero(), shouldTryInjectInvariantCondition(), simplifyAndOrOfFCmps(), simplifyAssociativeBinOp(), simplifyBinOp(), simplifyBinOp(), simplifyCmpInst(), simplifyCmpSelCase(), simplifyCmpSelFalseCase(), simplifyCmpSelTrueCase(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpUsingMonotonicValues(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyICmpWithDominatingAssume(), simplifyICmpWithIntrinsicOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), simplifyMul24(), simplifySetCCIntoEq(), SimplifyValuePattern(), simplifyX86pmulh(), sinkMinMaxInBB(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), SortAuthStubPair(), llvm::orc::SymbolLookupSet::sortByName(), llvm::IntervalTree< LVAddress, LVScope * >::sortIntervals(), SortSymbolPair(), llvm::PatternMatch::SpecificBinaryOp_match< LHS_t, RHS_t, Commutable >::SpecificBinaryOp_match(), llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::SpecificCmp_match(), llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::SpecificCmpClass_match(), splitVSETCC(), STATISTIC(), strictCompare(), llvm::KnownBits::sub(), SubNameCompare(), llvm::CachedHashString::swap, llvm::CGSCCToFunctionPassAdaptor::swap, llvm::detail::AnalysisPassModel< IRUnitT, PassT, InvalidatorT, ExtraArgTs >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, false >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::swap, llvm::detail::PassModel< IRUnitT, PassT, AnalysisManagerT, ExtraArgTs >::swap, llvm::ModuleToPostOrderCGSCCPassAdaptor::swap, std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), SwapN(), TargetArraySortFn(), threadBinOpOverPHI(), threadBinOpOverSelect(), threadCmpOverPHI(), threadCmpOverSelect(), TranslateM68kCC(), translateSetCCForBranch(), translateSetCCForBranch(), TranslateX86CC(), truncateAVX512SetCCNoBWI(), truncateVectorWithPACK(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryCombineLongOpWithDup(), tryCombineMULLWithUZP1(), tryFactorization(), tryFoldHelper(), tryGetSecondaryReductionRoot(), TryMatchTrue(), TryMULWIDECombine(), trySimplifyICmpWithAdds(), TryWideExtMulCombine(), llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::UnaryOp_match(), llvm::FastMathFlags::unionValue(), upgradePMULDQ(), upgradeX86IntrinsicCall(), upgradeX86vpcom(), useInversedSetcc(), visitMaskedMerge(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitUDivExpr(), llvm::PatternMatch::XorLike_match< LHS, RHS >::XorLike_match(), zeroExtendToMatch(), llvm::InstCombinerImpl::~InstCombinerImpl(), llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF(), and llvm::TargetLoweringObjectFileELF::~TargetLoweringObjectFileELF().
Mul
BinaryOperator* Mul
Definition at line 75 of file X86PartialReduction.cpp.
Referenced by AddCombineTo64BitSMLAL16(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPULegalizerInfo::buildMultiply(), CollectAddOperandsWithScales(), combineMADConstOne(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::ScalarEvolution::computeConstantDifference(), llvm::VPExpressionRecipe::computeCost(), convertFSqrtDivIntoFMul(), ConvertOmodMul(), ConvertShiftToMul(), llvm::VPlanTransforms::convertToConcreteRecipes(), detectExtMul(), DoInitialMatch(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::VPScalarIVStepsRecipe::execute(), llvm::TargetLowering::expandCLMUL(), expandFPToI(), llvm::TargetLowering::expandMULO(), expandPowIntrinsic(), llvm::TargetLowering::expandREM(), llvm::InstCombinerImpl::foldICmpMulConstant(), foldIDivShl(), foldMulHigh(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), llvm::SCEVExpander::generateOverflowCheck(), getAArch64XALUOOp(), llvm::ScalarEvolution::getAddExpr(), getExactSDiv(), llvm::getLCMType(), getMad(), llvm::ScalarEvolution::getMulExpr(), llvm::SelectionDAG::getNode(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::LegalizerHelper::getVectorElementPointer(), hoistMulAddAssociation(), instCombineSVEVectorFuseMulAddSub(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), isCTTZTable(), llvm::ScalarEvolution::isKnownToBeAPowerOfTwo(), llvm::SCEV::isNonConstantNegative(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafeImpl(), llvm::AMDGPULegalizerInfo::legalizeFlogUnsafe(), llvm::AMDGPULegalizerInfo::legalizeFPow(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), LinearizeExprTree(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafeImpl(), llvm::AMDGPUTargetLowering::LowerFLOGUnsafe(), llvm::LegalizerHelper::lowerFMad(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFREM(), lowerMUL_LOHI32(), LowerMULH(), LowerMULO(), LowerSMELdrStr(), llvm::LegalizerHelper::lowerSMULH_UMULH(), LowerSVEIntrinsicIndex(), llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match(), llvm::CombinerHelper::matchMulOfVScale(), matchPMADDWD(), optimizeDivRem(), PerformADDCombineWithOperands(), llvm::AMDGPUTargetLowering::performMulCombine(), performMulRdsvlCombine(), performMulVectorExtendCombine(), PerformVECREDUCE_ADDCombine(), PerformVQDMULHCombine(), llvm::VPExpressionRecipe::printRecipe(), processUMulZExtIdiom(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDivRem(), simplifyX86pmulh(), trySQDMULHCombine(), tryToMatchAndCreateMulAccumulateReduction(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSub(), llvm::VPExpressionRecipe::VPExpressionRecipe(), llvm::VPExpressionRecipe::VPExpressionRecipe(), and llvm::VPExpressionRecipe::VPExpressionRecipe().
RHS
Value* RHS = Mul->getOperand(1)
Definition at line 81 of file X86PartialReduction.cpp.
Referenced by llvm::APFloat::add(), llvm::KnownBits::add(), llvm::MachO::addEntry(), llvm::addEnumValues(), llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills(), adjustCostForPairing(), llvm::PatternMatch::AnyBinaryOp_match< LHS_t, RHS_t, Commutable >::AnyBinaryOp_match(), llvm::BitVector::anyCommon(), llvm::SmallBitVector::anyCommon(), llvm::APFloat::APFloat(), llvm::APFloat::APFloat(), llvm::const_iterator< MemoryLocation >::append(), llvm::RegsForValue::append(), llvm::SmallString< 0 >::append(), applyDivisibilityOnMinMaxExpr(), AreMulWideOperandsDemotable(), llvm::opt::ArgList::ArgList(), ascii_strncasecmp(), llvm::const_iterator< MemoryLocation >::assign(), llvm::SmallString< 0 >::assign(), llvm::const_iterator< MemoryLocation >::assignRemote(), avgComputeU(), llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::BinaryOp_match(), llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::BinaryOp_match(), llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::BinaryOpc_match(), binaryOpKnownBitsMapHelper(), llvm::PatternMatch::BinOpPred_match< LHS_t, RHS_t, Predicate, Commutable >::BinOpPred_match(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::BitmapBegin(), BitOp3_Op(), BitOp3_Op(), llvm::APFloat::bitwiseIsEqual(), BrPHIToSelect(), buildClonedLoops(), BuildIntrinsicOp(), buildMul(), buildNonAtomicBinOp(), BuildVSLDOI(), calculateByteProvider(), calculateByteProvider(), canConvertSETCCToXori(), canConvertToVcmpequb(), canFoldTermCondOfLoop(), canonicalizeForInvariantConditionInjection(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleWithOp(), CanProveNotTakenFirstIteration(), llvm::detail::SlowDynamicAPInt::ceilDiv, llvm::DynamicAPInt::ceilDiv, changeICMPPredToAArch64CC(), changeIntCCToAArch64CC(), checkAndReplaceCmp(), llvm::checkedAdd(), llvm::checkedAddUnsigned(), llvm::checkedMul(), llvm::checkedMulUnsigned(), llvm::checkedSub(), checkForNegativeOperand(), checkOrAndOpImpliedByOther(), llvm::PatternMatch::CmpClass_match< LHS_t, RHS_t, Class, Commutable >::CmpClass_match(), llvm::PatternMatch::CmpClass_match< LHS_t, RHS_t, Class, Commutable >::CmpClass_match(), cmpExcludesZero(), collectBitParts(), collectDivisibilityInformation(), collectMultiplyFactors(), collectShuffleElements(), collectSingleShuffleElements(), collectUnswitchCandidatesWithInjections(), combine_CC(), combine_CC(), combineADC(), combineAddOfPMADDWD(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineADDToSUB(), combineAnd(), CombineBaseUpdate(), combineBinOpOfExtractToReduceTree(), combineBitOpWithPACK(), combineCastedMaskArithmetic(), combineConcatVectorOps(), combineFaddCFmul(), combineFMulcFCMulc(), combineHorizOpWithShuffle(), combineMinNumMaxNumImpl(), combineMulWide(), combineOp_VLToVWOp_VL(), combineOrCmpEqZeroToCtlzSrl(), combinePExtTruncate(), combinePMULDQ(), combinePMULH(), combinePossibleConstantValues(), combinePredicateReduction(), combineSBB(), combineSelect(), combineSelectOfTwoConstants(), combineSelectToBinOp(), combineSetCC(), combineSetCCMOVMSK(), combineShiftToPMULH(), combineTargetShuffle(), combineToHorizontalAddSub(), combineVectorCompare(), combineVectorHADDSUB(), combineVectorShiftImm(), combineVPDPBUSDPattern(), combineVPMADD(), combineX86AddSub(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), combineXor(), llvm::PatternMatch::CommutativeBinaryIntrinsic_match< IntrID, LHS, RHS >::CommutativeBinaryIntrinsic_match(), commuteSelect(), llvm::APFloat::compare(), llvm::PartialOrderingVisitor::compare(), llvm::sandboxir::FCmpInst::compare(), llvm::sandboxir::ICmpInst::compare(), llvm::SmallString< 0 >::compare(), llvm::StringRef::compare(), llvm::SmallString< 0 >::compare_insensitive(), llvm::SmallString< 0 >::compare_numeric(), compareByScalarFnName(), compareByVectorFnName(), CompareMBBNumbers(), CompareMBBNumbers(), compareMbbNumbers(), compareMBBPriority(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::CompareOp_match(), llvm::MDNodeOpsKey::compareOps(), llvm::NodeSet::compareRecMII(), CompareSCEVComplexity(), computeFlagsForAddressComputation(), computeForAddCarry(), computeForSatAddSub(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPMADDWD(), computeKnownBitsForPSADBW(), computeKnownBitsFromCmp(), computeKnownBitsFromICmpCond(), computeKnownBitsFromLerpPattern(), computeKnownBitsFromOperator(), computeKnownFPClass(), computeKnownFPClassFromCond(), computeNumSignBitsBinOp(), ComputeNumSignBitsImpl(), computeOverflowForSignedAdd(), llvm::InstCombiner::computeOverflowForSignedAdd(), llvm::InstCombiner::computeOverflowForSignedMul(), llvm::InstCombiner::computeOverflowForSignedSub(), llvm::InstCombiner::computeOverflowForUnsignedAdd(), llvm::InstCombiner::computeOverflowForUnsignedMul(), llvm::InstCombiner::computeOverflowForUnsignedSub(), computePointerDifference(), computePointerICmp(), computeShlNSW(), computeShlNUW(), ConcatListInits(), constantFoldBinOpWithSplat(), constantFoldUser(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get(), constantIntSortPredicate(), llvm::SparseBitVector< 128 >::contains(), llvm::sandboxir::BinaryOperator::Context, ConvertSelectToConcatVector(), ConvertSETCCToXori(), llvm::APFloat::copySign(), countToEliminateCompares(), llvm::coverage::CoverageData::CoverageData(), llvm::FixedPointBuilder< IRBuilderTy >::CreateAdd(), llvm::IRBuilderBase::CreateAdd(), llvm::MatrixBuilder::CreateAdd(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateAnd(), llvm::VPBuilder::createAnd(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateBinOpFMF(), llvm::IRBuilderBase::CreateCmp(), llvm::IRBuilderBase::CreateCopySign(), llvm::FixedPointBuilder< IRBuilderTy >::CreateDiv(), llvm::FixedPointBuilder< IRBuilderTy >::CreateEQ(), llvm::IRBuilderBase::CreateExactSDiv(), llvm::IRBuilderBase::CreateExactUDiv(), llvm::IRBuilderBase::CreateFCmp(), llvm::IRBuilderBase::CreateFCmpFMF(), llvm::IRBuilderBase::CreateFCmpOEQ(), llvm::IRBuilderBase::CreateFCmpOGE(), llvm::IRBuilderBase::CreateFCmpOGT(), llvm::IRBuilderBase::CreateFCmpOLE(), llvm::IRBuilderBase::CreateFCmpOLT(), llvm::IRBuilderBase::CreateFCmpONE(), llvm::IRBuilderBase::CreateFCmpORD(), llvm::IRBuilderBase::CreateFCmpS(), llvm::IRBuilderBase::CreateFCmpUEQ(), llvm::IRBuilderBase::CreateFCmpUGE(), llvm::IRBuilderBase::CreateFCmpUGT(), llvm::IRBuilderBase::CreateFCmpULE(), llvm::IRBuilderBase::CreateFCmpULT(), llvm::IRBuilderBase::CreateFCmpUNE(), llvm::IRBuilderBase::CreateFCmpUNO(), createFPCmp(), llvm::FixedPointBuilder< IRBuilderTy >::CreateGE(), llvm::FixedPointBuilder< IRBuilderTy >::CreateGT(), llvm::IRBuilderBase::CreateICmp(), llvm::IRBuilderBase::CreateICmpEQ(), llvm::IRBuilderBase::CreateICmpNE(), llvm::IRBuilderBase::CreateICmpSGE(), llvm::IRBuilderBase::CreateICmpSGT(), llvm::IRBuilderBase::CreateICmpSLE(), llvm::IRBuilderBase::CreateICmpSLT(), llvm::IRBuilderBase::CreateICmpUGE(), llvm::IRBuilderBase::CreateICmpUGT(), llvm::IRBuilderBase::CreateICmpULE(), llvm::IRBuilderBase::CreateICmpULT(), llvm::FixedPointBuilder< IRBuilderTy >::CreateLE(), llvm::VPBuilder::createLogicalAnd(), createLogicalOp(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateLShr(), llvm::FixedPointBuilder< IRBuilderTy >::CreateLT(), llvm::MatrixBuilder::CreateMatrixMultiply(), llvm::IRBuilderBase::CreateMaximum(), llvm::IRBuilderBase::CreateMaximumNum(), llvm::IRBuilderBase::CreateMaxNum(), llvm::IRBuilderBase::CreateMinimum(), llvm::IRBuilderBase::CreateMinimumNum(), llvm::IRBuilderBase::CreateMinNum(), llvm::FixedPointBuilder< IRBuilderTy >::CreateMul(), llvm::IRBuilderBase::CreateMul(), llvm::FixedPointBuilder< IRBuilderTy >::CreateNE(), llvm::IRBuilderBase::CreateNSWAdd(), llvm::IRBuilderBase::CreateNSWMul(), llvm::IRBuilderBase::CreateNSWSub(), llvm::IRBuilderBase::CreateNUWAdd(), llvm::IRBuilderBase::CreateNUWMul(), llvm::IRBuilderBase::CreateNUWSub(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateOr(), llvm::VPBuilder::createOr(), createReplacement(), llvm::MatrixBuilder::CreateScalarDiv(), llvm::MatrixBuilder::CreateScalarMultiply(), llvm::IRBuilderBase::CreateSDiv(), llvm::FixedPointBuilder< IRBuilderTy >::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateShl(), llvm::FixedPointBuilder< IRBuilderTy >::CreateShr(), llvm::IRBuilderBase::CreateSRem(), llvm::FixedPointBuilder< IRBuilderTy >::CreateSub(), llvm::IRBuilderBase::CreateSub(), llvm::MatrixBuilder::CreateSub(), llvm::IRBuilderBase::CreateUDiv(), llvm::IRBuilderBase::CreateURem(), createVPDPBUSD(), llvm::IRBuilderBase::CreateXor(), llvm::IRBuilderBase::CreateXor(), llvm::IRBuilderBase::CreateXor(), DAGCombineAddc(), llvm::CachedHashString::DenseMapInfo< CachedHashString >, llvm::LLT::DenseMapInfo< LLT >, determineLiveOperandBitsAddCarry(), llvm::DIE::DIE(), llvm::DIE::DIE(), llvm::DIEUnit::DIEUnit(), llvm::DIEUnit::DIEUnit(), llvm::PatternMatch::DisjointOr_match< LHS, RHS, Commutable >::DisjointOr_match(), divComputeLowBit(), llvm::APFloat::divide(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::divideCoefficientBy(), dumpUnpackedICmp(), earlyExpandDIVFIX(), llvm::EquivalenceClasses< ElemTy >::ECValue::ECValue(), EliminateDuplicatePHINodesSetBasedImpl(), EmitAbsDifference(), EmitAVX512Test(), EmitCMP(), emitComparison(), emitConditionalComparison(), emitConjunctionRec(), emitFloatCompareMask(), emitSelectPseudo(), emitSelectPseudo(), emitStrictFPComparison(), emitVectorComparison(), llvm::APInt::eq(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::equals(), llvm::SmallString< 0 >::equals(), std::reverse_iterator< llvm::DWARFDie::iterator >::equals(), llvm::SmallString< 0 >::equals_insensitive(), llvm::StringRef::equals_insensitive(), equalsLoadStoreHelper(), llvm::EquivalenceClasses< BasicBlock * >::EquivalenceClasses(), estimateBitMaskedAndLowerBound(), evalBinaryInstruction(), EvaluateInDifferentTypeImpl(), expandDivFix(), expandMemCpy(), expandPow(), ExpandPowI(), extractEquivalentCondition(), factorizeMinMaxTree(), llvm::ImmutableSet< ValT, ValInfo >::Factory::Factory(), llvm::fcmpImpliesClass(), llvm::fcmpImpliesClass(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::fcmpToClassTest(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpToClassTest(), FilterHelper(), findBaseObject(), findFuncPointers(), findLoopComponents(), findMoreOptimalIndexType(), llvm::detail::SlowDynamicAPInt::floorDiv, llvm::DynamicAPInt::floorDiv, foldADCToCINC(), foldAndOrOfICmpEqConstantAndICmp(), foldAndOrOfICmpsWithPow2AndWithZero(), foldAndOrOfSETCC(), llvm::ConstantFolder::FoldBinaryIntrinsic(), llvm::InstSimplifyFolder::FoldBinaryIntrinsic(), llvm::IRBuilderFolder::FoldBinaryIntrinsic(), llvm::NoFolder::FoldBinaryIntrinsic(), llvm::TargetFolder::FoldBinaryIntrinsic(), llvm::ConstantFolder::FoldBinOp(), llvm::InstSimplifyFolder::FoldBinOp(), llvm::IRBuilderFolder::FoldBinOp(), llvm::NoFolder::FoldBinOp(), llvm::TargetFolder::FoldBinOp(), llvm::ConstantFolder::FoldBinOpFMF(), llvm::InstSimplifyFolder::FoldBinOpFMF(), llvm::IRBuilderFolder::FoldBinOpFMF(), llvm::NoFolder::FoldBinOpFMF(), llvm::TargetFolder::FoldBinOpFMF(), llvm::ConstantFolder::FoldCmp(), llvm::InstSimplifyFolder::FoldCmp(), llvm::IRBuilderFolder::FoldCmp(), llvm::NoFolder::FoldCmp(), llvm::TargetFolder::FoldCmp(), llvm::ConstantFolder::FoldExactBinOp(), llvm::InstSimplifyFolder::FoldExactBinOp(), llvm::IRBuilderFolder::FoldExactBinOp(), llvm::NoFolder::FoldExactBinOp(), llvm::TargetFolder::FoldExactBinOp(), foldFCmpWithFloorAndCeil(), foldFPToIntToFP(), foldICmpEqualityWithOffset(), foldICmpOfCmpIntrinsicWithConstant(), foldIntrinsicUsingDistributiveLaws(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::ConstantFolder::FoldNoWrapBinOp(), llvm::InstSimplifyFolder::FoldNoWrapBinOp(), llvm::IRBuilderFolder::FoldNoWrapBinOp(), llvm::NoFolder::FoldNoWrapBinOp(), llvm::TargetFolder::FoldNoWrapBinOp(), foldReductionIdiom(), foldVectorCmp(), ForeachDagApply(), ForeachHelper(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), generateComparison(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), getAArch64Cmp(), getAArch64XALUOOp(), GetAbsDifference(), llvm::ScalarEvolution::getAddExpr(), getAllDBDirs(), getARMIndexedAddressParts(), getBinOpsForFactorization(), getBitSelect(), getBranchCondString(), getDemandedBitsLHSMask(), getExactSDiv(), getFCmpValue(), llvm::InstrProfSymtab::getFuncOrVarName(), llvm::InstrProfSymtab::getFunction(), getHashValueImpl(), llvm::SetState< BaseTy >::getIntersection(), llvm::SetState< BaseTy >::SetContents::getIntersection(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownScalarFactor(), GetLinearExpression(), getMaskedTypeForICmpPair(), getMul64(), llvm::ScalarEvolution::getMulExpr(), getMulHu(), getMVEIndexedAddressParts(), getNewICmpValue(), getOperandsForBranch(), GetOptionalAbsDifference(), GetOptionalAbsDifference(), getPack(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), getPredicateResult(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), llvm::ScaledNumbers::getProduct(), llvm::ScaledNumbers::getProduct32(), llvm::ScaledNumbers::getProduct64(), getRangeForSelectPattern(), getRangeViaSLT(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSetCCVP(), getSortedConstantKeys(), getSplitVectorSrc(), GetSubDivExpr(), getT2IndexedAddressParts(), getTruncatedUSUBSAT(), llvm::SetState< BaseTy >::getUnion(), llvm::SetState< BaseTy >::SetContents::getUnion(), llvm::getUnitForOffset(), getValueFromICmpCtpop(), getValueOnFirstIteration(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getWithIncrement(), getX86XALUOOp(), GroupByComplexity(), llvm::gsym::GsymReader::GsymReader(), hasHazard(), hasIdenticalMMOs(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::hasKnownScalarFactor(), hasNonZeroFPOperands(), llvm::cas::ReferenceBase::hasSameInternalRef(), llvm::KnownBits::haveNoCommonBitsSet(), haveNoCommonBitsSetSpecialCases(), hoistAddSub(), hoistMinMax(), hoistMulAddAssociation(), llvm::ICmpInst::ICmpInst(), llvm::ICmpInst::ICmpInst(), if(), llvm::ilist_iterator< OptionsT, false, IsConst >::ilist_iterator(), llvm::ilist_iterator< OptionsT, false, IsConst >::ilist_iterator(), llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::ilist_iterator_w_bits(), llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::ilist_iterator_w_bits(), inferInitializes(), injectPendingInvariantConditions(), llvm::opt::InputArgList::InputArgList(), insertCandidatesWithPendingInjections(), instCombineSVELast(), llvm::InstrProfRecord::InstrProfRecord(), IntCondCCodeToICC(), llvm::FastMathFlags::intersectRewrite(), llvm::APInt::intersects(), llvm::DWARFAddressRange::intersects(), llvm::SparseBitVector< 128 >::intersects(), llvm::SparseBitVector< 128 >::intersects(), llvm::SparseBitVectorElement< ElementSize >::intersects(), llvm::KnownBits::intersectWith(), llvm::KnownFPClass::intersectWith(), llvm::SparseBitVectorElement< ElementSize >::intersectWith(), llvm::SparseBitVector< 128 >::intersectWithComplement(), llvm::SparseBitVector< 128 >::intersectWithComplement(), llvm::SparseBitVectorElement< ElementSize >::intersectWithComplement(), llvm::IntervalMap< IndexT, char >::IntervalMap(), llvm::IntervalMap< IndexT, char >::IntervalMap(), isAddSubOrSubAdd(), llvm::MDNodeSubsetEqualImpl< DISubprogram >::isDeclarationOfODRMember(), isDivisibilityGuard(), llvm::ImutAVLTree< ValInfo >::isElementEqual(), llvm::AnonStructTypeKeyInfo::isEqual(), llvm::AnonStructTypeKeyInfo::isEqual(), llvm::ConcurrentHashTableInfoByPtr< KeyTy, KeyDataTy, AllocatorTy >::isEqual(), llvm::DenseMapInfo< AA::ValueAndContext >::isEqual(), llvm::DenseMapInfo< AA::ValueScope >::isEqual(), llvm::DenseMapInfo< AACacheLoc >::isEqual(), llvm::DenseMapInfo< AAMDNodes >::isEqual(), llvm::DenseMapInfo< APFixedPoint >::isEqual(), llvm::DenseMapInfo< APFloat >::isEqual(), llvm::DenseMapInfo< APInt, void >::isEqual(), llvm::DenseMapInfo< APSInt, void >::isEqual(), llvm::DenseMapInfo< ArrayRef< T >, void >::isEqual(), llvm::DenseMapInfo< Attribute::AttrKind >::isEqual(), llvm::DenseMapInfo< AttributeList, void >::isEqual(), llvm::DenseMapInfo< AttributeSet, void >::isEqual(), llvm::DenseMapInfo< BasicBlock::iterator >::isEqual(), llvm::DenseMapInfo< BasicBlockEdge >::isEqual(), llvm::DenseMapInfo< BitVector >::isEqual(), llvm::DenseMapInfo< CachedHashString >::isEqual(), llvm::DenseMapInfo< cas::CASID >::isEqual(), llvm::DenseMapInfo< cas::ObjectRef >::isEqual(), llvm::DenseMapInfo< char >::isEqual(), llvm::DenseMapInfo< codeview::GloballyHashedType >::isEqual(), llvm::DenseMapInfo< codeview::LocallyHashedType >::isEqual(), llvm::DenseMapInfo< codeview::TypeIndex >::isEqual(), llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::isEqual(), llvm::DenseMapInfo< const AA::InstExclusionSetTy * >::isEqual(), llvm::DenseMapInfo< coverage::CounterExpression >::isEqual(), llvm::DenseMapInfo< ElementCount, void >::isEqual(), llvm::DenseMapInfo< Enum, std::enable_if_t< std::is_enum_v< Enum > > >::isEqual(), llvm::DenseMapInfo< FixedPointSemantics >::isEqual(), llvm::DenseMapInfo< gsym::FileEntry >::isEqual(), llvm::DenseMapInfo< hash_code, void >::isEqual(), llvm::DenseMapInfo< LLT >::isEqual(), llvm::DenseMapInfo< llvm::SmallVector< T, N > >::isEqual(), llvm::DenseMapInfo< llvm::sys::fs::UniqueID >::isEqual(), llvm::DenseMapInfo< LocationSize >::isEqual(), llvm::DenseMapInfo< MachineOperand >::isEqual(), llvm::DenseMapInfo< MBBSectionID >::isEqual(), llvm::DenseMapInfo< MCRegister >::isEqual(), llvm::DenseMapInfo< MemoryLocation >::isEqual(), llvm::DenseMapInfo< minidump::StreamType >::isEqual(), llvm::DenseMapInfo< OffsetAndUnitID >::isEqual(), llvm::DenseMapInfo< omp::TraitProperty >::isEqual(), llvm::DenseMapInfo< orc::AllocGroup >::isEqual(), llvm::DenseMapInfo< orc::ExecutorAddr >::isEqual(), llvm::DenseMapInfo< orc::MemProt >::isEqual(), llvm::DenseMapInfo< orc::NonOwningSymbolStringPtr >::isEqual(), llvm::DenseMapInfo< orc::SymbolStringPtr >::isEqual(), llvm::DenseMapInfo< PointerEmbeddedInt< IntT, Bits > >::isEqual(), llvm::DenseMapInfo< PointerIntPair< PointerTy, IntBits, IntType >, void >::isEqual(), llvm::DenseMapInfo< PointerSumType< TagT, MemberTs... > >::isEqual(), llvm::DenseMapInfo< PointerUnion< PTs... > >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< Register >::isEqual(), llvm::DenseMapInfo< SampleContext >::isEqual(), llvm::DenseMapInfo< sampleprof::FunctionId, void >::isEqual(), llvm::DenseMapInfo< sandboxir::Context::CallbackID >::isEqual(), llvm::DenseMapInfo< ScalarEvolution::FoldID >::isEqual(), llvm::DenseMapInfo< SDValue >::isEqual(), llvm::DenseMapInfo< SmallBitVector >::isEqual(), llvm::DenseMapInfo< std::optional< T > >::isEqual(), llvm::DenseMapInfo< std::pair< T, U > >::isEqual(), llvm::DenseMapInfo< std::variant< Ts... > >::isEqual(), llvm::DenseMapInfo< StringRef, void >::isEqual(), llvm::DenseMapInfo< SymbolsMapKey >::isEqual(), llvm::DenseMapInfo< T * >::isEqual(), llvm::DenseMapInfo< T, std::enable_if_t< std::is_integral_v< T > &&!std::is_same_v< T, char > > >::isEqual(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::isEqual(), llvm::DenseMapInfo< UniqueBBID >::isEqual(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::DenseMapInfo< VersionTuple >::isEqual(), llvm::DenseMapInfo< wasm::WasmGlobalType, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmLimits, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmSignature, void >::isEqual(), llvm::DenseMapInfo< wasm::WasmTableType, void >::isEqual(), llvm::DenseMapInfo< WeakVH >::isEqual(), llvm::DIArgListInfo::isEqual(), llvm::DIArgListInfo::isEqual(), llvm::dwarf_linker::classic::DeclMapInfo::isEqual(), llvm::dwarf_linker::parallel::TypeEntryInfo::isEqual(), llvm::dwarf_linker::StringPoolEntryInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), llvm::ImutAVLTree< ValInfo >::isEqual(), llvm::ImutContainerInfo< T >::isEqual(), llvm::ImutContainerInfo< T * >::isEqual(), llvm::IRSimilarity::IRInstructionDataTraits::isEqual(), llvm::MachineInstrExpressionTrait::isEqual(), llvm::MDNodeInfo< NodeTy >::isEqual(), llvm::MDNodeInfo< NodeTy >::isEqual(), llvm::TargetExtTypeKeyInfo::isEqual(), llvm::TargetExtTypeKeyInfo::isEqual(), isEqualImpl(), isHorizontalBinOp(), isICmpTrue(), llvm::DIArgListKeyInfo::isKeyOf(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DICommonBlock >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DIEnumerator >::isKeyOf(), llvm::MDNodeKeyImpl< DIExpression >::isKeyOf(), llvm::MDNodeKeyImpl< DIFile >::isKeyOf(), llvm::MDNodeKeyImpl< DIFixedPointType >::isKeyOf(), llvm::MDNodeKeyImpl< DIGenericSubrange >::isKeyOf(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::isKeyOf(), llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf(), llvm::MDNodeKeyImpl< DILabel >::isKeyOf(), llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf(), llvm::MDNodeKeyImpl< DILexicalBlockFile >::isKeyOf(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), llvm::MDNodeKeyImpl< DILocation >::isKeyOf(), llvm::MDNodeKeyImpl< DIMacro >::isKeyOf(), llvm::MDNodeKeyImpl< DIMacroFile >::isKeyOf(), llvm::MDNodeKeyImpl< DIModule >::isKeyOf(), llvm::MDNodeKeyImpl< DINamespace >::isKeyOf(), llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf(), llvm::MDNodeKeyImpl< DIStringType >::isKeyOf(), llvm::MDNodeKeyImpl< DISubprogram >::isKeyOf(), llvm::MDNodeKeyImpl< DISubrange >::isKeyOf(), llvm::MDNodeKeyImpl< DISubrangeType >::isKeyOf(), llvm::MDNodeKeyImpl< DISubroutineType >::isKeyOf(), llvm::MDNodeKeyImpl< DITemplateTypeParameter >::isKeyOf(), llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf(), llvm::MDNodeKeyImpl< GenericDINode >::isKeyOf(), llvm::MDNodeKeyImpl< MDTuple >::isKeyOf(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownGE(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownGT(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownLE(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownLT(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownMultipleOf(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownMultipleOf(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), isKnownPredicateExtendIdiom(), IsKnownPredicateViaAddRecStart(), IsKnownPredicateViaMinOrMax(), isLaneMaskFromSameBlock(), isLegalToCombineMinNumMaxNum(), llvm::ImutContainerInfo< T >::isLess(), llvm::ImutContainerInfo< T * >::isLess(), isLowerSaturate(), isLowerSaturatingConditional(), isNeutralValue(), isNonEscapingGlobalNoAliasWithLoad(), llvm::ImutAVLTree< ValInfo >::isNotEqual(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isODRMember(), isProcessableCondBI(), isSameCompare(), isSameReg(), isSignedMinMaxClamp(), isSSATMinMaxPattern(), llvm::MDNodeSubsetEqualImpl< NodeTy >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< NodeTy >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual(), llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual(), llvm::APInt::isSubsetOf(), isTruePredicate(), ItemApply(), llvm::StringTable::Iterator::Iterator(), llvm::StringTable::Iterator::Iterator(), llvm::LazyAtomicPointer< TrieNode >::LazyAtomicPointer(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::LazyValueConstructor(), legalizeFCmpPredicate(), llvm::dwarf_linker::classic::DWARFLinker::link(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMBuildAdd(), LLVMBuildAnd(), LLVMBuildAShr(), LLVMBuildBinOp(), LLVMBuildExactSDiv(), LLVMBuildExactUDiv(), LLVMBuildFAdd(), LLVMBuildFCmp(), LLVMBuildFDiv(), LLVMBuildFMul(), LLVMBuildFRem(), LLVMBuildFSub(), LLVMBuildICmp(), LLVMBuildLShr(), LLVMBuildMul(), LLVMBuildNSWAdd(), LLVMBuildNSWMul(), LLVMBuildNSWSub(), LLVMBuildNUWAdd(), LLVMBuildNUWMul(), LLVMBuildNUWSub(), LLVMBuildOr(), LLVMBuildPtrDiff2(), LLVMBuildSDiv(), LLVMBuildShl(), LLVMBuildSRem(), LLVMBuildSub(), LLVMBuildUDiv(), LLVMBuildURem(), LLVMBuildXor(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::LogicalOp_match(), LookThroughSetCC(), lookupLLVMIntrinsicByName(), LookupNearestOption(), LowerABD(), lowerAddSubToHorizontalOp(), LowerAndToBTST(), lowerAtomicArith(), LowerBR_CC(), lowerBuildVectorToBitOp(), lowerConstrainedFPCmpIntrinsic(), LowerCTPOP(), llvm::TargetLoweringObjectFile::lowerDSOLocalEquivalent(), lowerICMPIntrinsic(), lowerOverflowArithmetic(), llvm::TargetLoweringObjectFile::lowerRelativeReference(), LowerSELECT_CC(), lowerSelectToBinOp(), LowerSELECTWithCmpZero(), LowerSETCCCARRY(), lowerShuffleAsLanePermuteAndSHUFP(), LowerVectorAllEqual(), lowerVSELECTtoVectorShuffle(), llvm::PatternMatch::m_Add(), llvm::SDPatternMatch::m_Add(), llvm::PatternMatch::m_AddLike(), llvm::SDPatternMatch::m_AddLike(), llvm::PatternMatch::m_And(), llvm::SDPatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::MIPatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::SDPatternMatch::m_BinOp(), llvm::PatternMatch::m_BitwiseLogic(), llvm::SDPatternMatch::m_BitwiseLogic(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::SDPatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_BitwiseLogic(), llvm::SDPatternMatch::m_c_ChainedBinOp(), llvm::PatternMatch::m_c_DisjointOr(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_c_FMul(), llvm::MIPatternMatch::m_c_GFCmp(), llvm::MIPatternMatch::m_c_GICmp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOp(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_c_MaxOrMin(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_c_NSWAdd(), llvm::PatternMatch::m_c_NUWAdd(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Select(), llvm::SDPatternMatch::m_c_SetCC(), llvm::PatternMatch::m_c_SMax(), llvm::PatternMatch::m_c_SMin(), llvm::PatternMatch::m_c_SpecificICmp(), llvm::PatternMatch::m_c_UMax(), llvm::PatternMatch::m_c_UMin(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_c_XorLike(), llvm::SDPatternMatch::m_ChainedBinOp(), llvm::SDPatternMatch::m_Clmul(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Cmp(), llvm::MIPatternMatch::m_CommutativeBinOp(), llvm::PatternMatch::m_DisjointOr(), llvm::SDPatternMatch::m_DisjointOr(), llvm::SDPatternMatch::m_ExactSr(), llvm::SDPatternMatch::m_ExtractElt(), llvm::SDPatternMatch::m_ExtractSubvector(), llvm::PatternMatch::m_FAdd(), llvm::SDPatternMatch::m_FAdd(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_FDiv(), llvm::SDPatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::SDPatternMatch::m_FMul(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_FRem(), llvm::SDPatternMatch::m_FRem(), llvm::PatternMatch::m_FSub(), llvm::SDPatternMatch::m_FSub(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GAddLike(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_GAShr(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GBuildVectorTrunc(), llvm::MIPatternMatch::m_GDisjointOr(), llvm::MIPatternMatch::m_GFAdd(), llvm::MIPatternMatch::m_GFCmp(), llvm::MIPatternMatch::m_GFMul(), llvm::MIPatternMatch::m_GFSub(), llvm::MIPatternMatch::m_GICmp(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GMul(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GSMax(), llvm::MIPatternMatch::m_GSMin(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_GUMax(), llvm::MIPatternMatch::m_GUMin(), llvm::MIPatternMatch::m_GXor(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_IDiv(), llvm::SDPatternMatch::m_InsertSubvector(), llvm::PatternMatch::m_IRem(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOp(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Mul(), llvm::SDPatternMatch::m_Mul(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_NUWAdd(), llvm::PatternMatch::m_NUWAddLike(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_Or(), llvm::SDPatternMatch::m_Or(), llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_OrdOrUnordFMax(), llvm::PatternMatch::m_OrdOrUnordFMin(), llvm::SDPatternMatch::m_Rotl(), llvm::SDPatternMatch::m_Rotr(), llvm::SCEVPatternMatch::m_scev_URem(), llvm::PatternMatch::m_SDiv(), llvm::SDPatternMatch::m_SDiv(), llvm::PatternMatch::m_Select(), llvm::SDPatternMatch::m_SetCC(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Shl(), llvm::SDPatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SMax(), llvm::SDPatternMatch::m_SMax(), llvm::SDPatternMatch::m_SMaxLike(), llvm::PatternMatch::m_SMin(), llvm::SDPatternMatch::m_SMin(), llvm::SDPatternMatch::m_SMinLike(), llvm::PatternMatch::m_SpecificCmp(), llvm::PatternMatch::m_SpecificFCmp(), llvm::PatternMatch::m_SpecificICmp(), llvm::SDPatternMatch::m_Sra(), llvm::PatternMatch::m_SRem(), llvm::SDPatternMatch::m_SRem(), llvm::SDPatternMatch::m_Srl(), llvm::PatternMatch::m_Sub(), llvm::SDPatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::SDPatternMatch::m_UDiv(), llvm::PatternMatch::m_UMax(), llvm::SDPatternMatch::m_UMax(), llvm::SDPatternMatch::m_UMaxLike(), llvm::PatternMatch::m_UMin(), llvm::SDPatternMatch::m_UMin(), llvm::SDPatternMatch::m_UMinLike(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_URem(), llvm::SDPatternMatch::m_URem(), llvm::PatternMatch::m_Xor(), llvm::SDPatternMatch::m_Xor(), makeEndMinusStartExpr(), makeStartPlusIntExpr(), llvm::cas::MappedFileRegionArena::MappedFileRegionArena(), markAliveBlocks(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match(), llvm::SDPatternMatch::SpecificNeg_match::match(), matchAddReduction(), MatchBinarySub(), matchFastFloatClamp(), matchIsFiniteTest(), matchIsNotNaN(), matchMinMax(), llvm::matchSelectPattern(), matchSelectPattern(), matchSetCC(), matchSetCC(), matchSymmetricPhiNodesPair(), matchTwoInputRecurrence(), matchUnorderedInfCompare(), MatchVectorAllEqualTest(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::MaxMin_match(), mayUseP9Setb(), llvm::MCParsedAsmOperand::MCParsedAsmOperand(), llvm::AAPointerInfo::RangeList::merge(), llvm::DWARFAddressRange::merge(), llvm::simple_ilist< T, Options >::merge(), llvm::simple_ilist< Node >::merge(), llvm::simple_ilist< Node >::merge(), llvm::ValueLatticeElement::mergeIn(), llvm::SMTSolver::mkAnd(), llvm::SMTSolver::mkBVAdd(), llvm::SMTSolver::mkBVAddNoOverflow(), llvm::SMTSolver::mkBVAddNoUnderflow(), llvm::SMTSolver::mkBVAnd(), llvm::SMTSolver::mkBVAshr(), llvm::SMTSolver::mkBVConcat(), llvm::SMTSolver::mkBVLshr(), llvm::SMTSolver::mkBVMul(), llvm::SMTSolver::mkBVMulNoOverflow(), llvm::SMTSolver::mkBVMulNoUnderflow(), llvm::SMTSolver::mkBVOr(), llvm::SMTSolver::mkBVSDiv(), llvm::SMTSolver::mkBVSDivNoOverflow(), llvm::SMTSolver::mkBVSge(), llvm::SMTSolver::mkBVSgt(), llvm::SMTSolver::mkBVShl(), llvm::SMTSolver::mkBVSle(), llvm::SMTSolver::mkBVSlt(), llvm::SMTSolver::mkBVSRem(), llvm::SMTSolver::mkBVSub(), llvm::SMTSolver::mkBVSubNoOverflow(), llvm::SMTSolver::mkBVSubNoUnderflow(), llvm::SMTSolver::mkBVUDiv(), llvm::SMTSolver::mkBVUge(), llvm::SMTSolver::mkBVUgt(), llvm::SMTSolver::mkBVUle(), llvm::SMTSolver::mkBVUlt(), llvm::SMTSolver::mkBVURem(), llvm::SMTSolver::mkBVXor(), llvm::SMTSolver::mkEqual(), llvm::SMTSolver::mkFPAdd(), llvm::SMTSolver::mkFPDiv(), llvm::SMTSolver::mkFPEqual(), llvm::SMTSolver::mkFPGe(), llvm::SMTSolver::mkFPGt(), llvm::SMTSolver::mkFPLe(), llvm::SMTSolver::mkFPLt(), llvm::SMTSolver::mkFPMul(), llvm::SMTSolver::mkFPRem(), llvm::SMTSolver::mkFPSub(), llvm::SMTSolver::mkOr(), llvm::APFloat::mod(), llvm::DynamicAPInt::mod, llvm::APFloat::multiply(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::multiplyCoefficientBy(), narrowSDivOrSRem(), narrowUDivOrURem(), llvm::APInt::ne(), needsLFTR(), NegateCC(), llvm::cas::OnDiskDataAllocator::OnDiskDataAllocator(), llvm::cas::OnDiskTrieRawHashMap::OnDiskTrieRawHashMap(), llvm::AAPointerInfo::OffsetInfo::operator!=(), llvm::APFloat::operator!=(), llvm::APInt::operator!=(), llvm::APSInt::operator!=(), llvm::APSInt::operator!=(), llvm::bf_iterator< GraphT, SetType, GT >::operator!=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator!=(), llvm::BitVector::operator!=(), llvm::BlockFrequency::operator!=(), llvm::BranchProbability::operator!=(), llvm::cas::CASID::operator!=, llvm::cas::ObjectHandle::operator!=, llvm::cas::ObjectRef::operator!=, llvm::cas::ondisk::ObjectHandle::operator!=, llvm::cas::ondisk::ObjectID::operator!=, llvm::CoalescingBitVector< IndexT >::const_iterator::operator!=(), llvm::CoalescingBitVector< IndexT >::operator!=(), llvm::codeview::operator!=(), llvm::const_iterator< MemoryLocation >::operator!=(), llvm::coverage::CoverageMappingIterator::operator!=(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator!=, llvm::detail::operator!=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator!=(), llvm::DILineInfo::operator!=(), llvm::dxil::ResourceInfo::operator!=(), llvm::dxil::ResourceInfo::ResourceBinding::operator!=(), llvm::dxil::ResourceTypeInfo::operator!=(), llvm::dxil::ResourceTypeInfo::StructInfo::operator!=(), llvm::dxil::ResourceTypeInfo::TypedInfo::operator!=(), llvm::dxil::ResourceTypeInfo::UAVInfo::operator!=(), llvm::EquivalenceClasses< ElemTy >::member_iterator::operator!=(), llvm::fallible_iterator< ChildFallibleIterator >::operator!=, llvm::FeatureBitset::operator!=(), llvm::FoldingSetBucketIteratorImpl::operator!=(), llvm::FoldingSetIteratorImpl::operator!=(), llvm::FoldingSetNodeID::operator!=(), llvm::FoldingSetNodeID::operator!=(), llvm::FoldingSetNodeIDRef::operator!=(), llvm::GenericSchedulerBase::CandPolicy::operator!=(), llvm::GenericSchedulerBase::SchedResourceDelta::operator!=(), llvm::gsym::CallSiteInfo::operator!=(), llvm::gsym::FileEntry::operator!=(), llvm::gsym::LineTable::operator!=(), llvm::gsym::operator!=(), llvm::gsym::operator!=(), llvm::hlsl::Binding::operator!=(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator!=, llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator!=, llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator!=(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator!=(), llvm::ImmutableSet< ValT, ValInfo >::operator!=(), llvm::ImmutableSetRef< ValT, ValInfo >::operator!=(), llvm::InstrProfIterator< GuidMemProfRecordPair, MemProfReader >::operator!=(), llvm::InstructionCost::operator!=(), llvm::InstructionCost::operator!=(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator!=(), llvm::IntervalMapImpl::NodeRef::operator!=(), llvm::IntervalTree< PointT, ValueT, DataT >::find_iterator::operator!=, llvm::IRPosition::operator!=(), llvm::iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >, ReferenceTupleType, typename std::iterator_traits< std::tuple_element_t< 0, std::tuple< Iters... > > >::difference_type, ReferenceTupleType *, ReferenceTupleType >::operator!=(), llvm::json::operator!=(), llvm::line_iterator::operator!=, llvm::MachineBasicBlock::liveout_iterator::operator!=(), llvm::MachineMemOperand::operator!=, llvm::MachO::operator!=(), llvm::MachO::operator!=(), llvm::MemoryBufferRef::operator!=, llvm::NodeSet::operator!=(), llvm::object::DXContainer::PartIterator::operator!=(), llvm::OffsetSpan::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::opt::arg_iterator< arglist_type::iterator >::operator!=, llvm::orc::AllocGroup::operator!=, llvm::orc::ExecutorAddr::operator!=, llvm::orc::ExecutorAddrRange::operator!=, llvm::orc::ExecutorSymbolDef::operator!=, llvm::orc::SymbolStringPtrBase::operator!=, llvm::PackedVector< unsigned, BitsPerField, std::bitset< BitsPerField *NumFields > >::operator!=(), llvm::PagedVector< T, PageSize >::MaterializedIterator::operator!=, llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator!=(), llvm::RegPressureDelta::operator!=(), llvm::remarks::operator!=(), llvm::remarks::operator!=(), llvm::remarks::operator!=(), llvm::RopePieceBTreeIterator::operator!=(), llvm::sampleprof::operator!=(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator!=(), llvm::SizeOffsetType< T, C >::operator!=(), llvm::SmallBitVector::operator!=(), llvm::SmallPtrSetIteratorImpl::operator!=(), llvm::SMLoc::operator!=(), llvm::SparseBitVector< 128 >::operator!=(), llvm::SparseBitVectorElement< ElementSize >::operator!=(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator!=(), llvm::StackOffset::operator!=(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::operator!=(), llvm::StringMapIterBase< ValueTy, true >::operator!=, llvm::StringTable::Offset::operator!=, llvm::sys::fs::directory_entry::operator!=(), llvm::sys::fs::directory_iterator::operator!=(), llvm::sys::fs::recursive_directory_iterator::operator!=(), llvm::ValueMapIteratorImpl< MapT, KeyT, false >::operator!=(), llvm::vfs::directory_iterator::operator!=(), llvm::vfs::OutputConfig::operator!=(), llvm::vfs::recursive_directory_iterator::operator!=(), llvm::wasm::operator!=(), llvm::wasm::operator!=(), llvm::APSInt::operator%(), llvm::orc::operator%(), llvm::APSInt::operator%=(), llvm::APSInt::operator&(), llvm::BitmaskEnumDetail::operator&(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator&(), llvm::FeatureBitset::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::operator&(), llvm::APInt::operator&=(), llvm::APInt::operator&=(), llvm::APSInt::operator&=(), llvm::BitmaskEnumDetail::operator&=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator&=(), llvm::BitVector::operator&=(), llvm::CoalescingBitVector< IndexT >::operator&=(), llvm::FeatureBitset::operator&=(), llvm::FunctionSummary::FFlags::operator&=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator&=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator&=(), llvm::JITSymbolFlags::operator&=(), llvm::operator&=(), llvm::operator&=(), llvm::SmallBitVector::operator&=(), llvm::SparseBitVector< 128 >::operator&=(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertionInfo::Compare::operator()(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::LessRecordByID::operator()(), llvm::RISCVISAUtils::ExtensionComparator::operator()(), llvm::sampleprof::SampleRecord::CallTargetComparator::operator()(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator()(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator()(), llvm::APFloat::operator*(), llvm::APSInt::operator*(), llvm::BranchProbability::operator*(), llvm::BranchProbability::operator*(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator*, llvm::operator*(), llvm::operator*(), llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::TypeSize::operator*, llvm::APSInt::operator*=(), llvm::BranchProbability::operator*=(), llvm::BranchProbability::operator*=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator*=, llvm::InstructionCost::operator*=(), llvm::InstructionCost::operator*=(), llvm::APFloat::operator+(), llvm::APSInt::operator+(), llvm::BranchProbability::operator+(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator+, llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::operator+(), llvm::orc::operator+(), llvm::orc::operator+(), llvm::StackOffset::operator+(), llvm::APSInt::operator+=(), llvm::BranchProbability::operator+=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator+=, llvm::GCNRegPressure::operator+=(), llvm::InstructionCost::operator+=(), llvm::InstructionCost::operator+=(), llvm::mca::ReleaseAtCycles::operator+=(), llvm::Register::operator+=(), llvm::SmallString< 0 >::operator+=(), llvm::StackOffset::operator+=(), llvm::SuccIterator< Instruction, BasicBlock >::operator+=(), llvm::TimeRecord::operator+=(), llvm::APFloat::operator-(), llvm::APSInt::operator-(), llvm::BranchProbability::operator-(), llvm::cas::ondisk::InternalRefArrayRef::iterator::operator-(), llvm::cas::ondisk::object_refs_iterator::operator-(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-, llvm::iterator_adaptor_base< IteratorImpl< ValueT, IteratorBase >, IteratorBase, std::bidirectional_iterator_tag, ValueT >::operator-(), llvm::operator-(), llvm::operator-(), llvm::operator-(), llvm::orc::operator-(), llvm::orc::operator-(), llvm::StackOffset::operator-(), llvm::SuccIterator< Instruction, BasicBlock >::operator-(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator-(), llvm::TimeRecord::operator-(), llvm::APSInt::operator-=(), llvm::BranchProbability::operator-=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-=, llvm::GCNRegPressure::operator-=(), llvm::InstructionCost::operator-=(), llvm::InstructionCost::operator-=(), llvm::StackOffset::operator-=(), llvm::SuccIterator< Instruction, BasicBlock >::operator-=(), llvm::TimeRecord::operator-=(), llvm::APFloat::operator/(), llvm::APSInt::operator/(), llvm::BranchProbability::operator/(), llvm::BranchProbability::operator/(), llvm::operator/(), llvm::APSInt::operator/=(), llvm::BranchProbability::operator/=(), llvm::BranchProbability::operator/=(), llvm::InstructionCost::operator/=(), llvm::InstructionCost::operator/=(), llvm::APFloat::operator<(), llvm::APSInt::operator<(), llvm::APSInt::operator<(), llvm::at::VarRecord::operator<, llvm::Bitset< AEK_NUM_EXTENSIONS >::operator<(), llvm::BlockFrequency::operator<(), llvm::BranchProbability::operator<(), llvm::cas::ondisk::InternalRefArrayRef::iterator::operator<(), llvm::cas::ondisk::object_refs_iterator::operator<(), llvm::codeview::operator<(), llvm::const_iterator< MemoryLocation >::operator<(), llvm::coverage::Counter::operator<, llvm::DILineInfo::operator<(), llvm::dxil::ResourceInfo::operator<(), llvm::dxil::ResourceInfo::ResourceBinding::operator<(), llvm::dxil::ResourceTypeInfo::StructInfo::operator<(), llvm::dxil::ResourceTypeInfo::TypedInfo::operator<(), llvm::dxil::ResourceTypeInfo::UAVInfo::operator<(), llvm::EntryValueInfo::operator<, llvm::FeatureBitset::operator<(), llvm::FileLoc::operator<(), llvm::FixedStreamArrayIterator< T >::operator<(), llvm::FrameIndexExpr::operator<, llvm::gsym::LineTable::operator<(), llvm::gsym::operator<(), llvm::gsym::operator<(), llvm::hlsl::Binding::operator<(), llvm::ifs::IFSSymbol::operator<(), llvm::ILPValue::operator<(), llvm::InstructionCost::operator<(), llvm::InstructionCost::operator<(), llvm::IntrinsicData::operator<(), llvm::IRSimilarity::IRSimilarityCandidate::operator<(), llvm::iterator_adaptor_base< IteratorImpl< ValueT, IteratorBase >, IteratorBase, std::bidirectional_iterator_tag, ValueT >::operator<, llvm::MachO::operator<(), llvm::MCRegisterInfo::DwarfLLVMRegPair::operator<(), llvm::NonLocalDepEntry::operator<(), llvm::object::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::operator<(), llvm::orc::AllocGroup::operator<, llvm::orc::ExecutorAddr::operator<, llvm::orc::ExecutorAddrRange::operator<, llvm::orc::SymbolStringPtrBase::operator<, llvm::outliner::Candidate::operator<(), llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator<(), llvm::reassociate::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::remarks::operator<(), llvm::sampleprof::operator<(), llvm::SuccIterator< Instruction, BasicBlock >::operator<(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator<(), llvm::sys::fs::directory_entry::operator<(), llvm::TargetRegionEntryInfo::operator<(), llvm::ValID::operator<(), llvm::X86FoldTableEntry::operator<(), llvm::X86InstrFMA3Group::operator<(), operator<(), operator<(), llvm::BitmaskEnumDetail::operator<<(), llvm::operator<<(), llvm::APFloat::operator<=(), llvm::APSInt::operator<=(), llvm::APSInt::operator<=(), llvm::BlockFrequency::operator<=(), llvm::BranchProbability::operator<=(), llvm::codeview::operator<=(), llvm::const_iterator< MemoryLocation >::operator<=(), llvm::FileLoc::operator<=(), llvm::ILPValue::operator<=(), llvm::InstructionCost::operator<=(), llvm::InstructionCost::operator<=(), llvm::iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >, ReferenceTupleType, typename std::iterator_traits< std::tuple_element_t< 0, std::tuple< Iters... > > >::difference_type, ReferenceTupleType *, ReferenceTupleType >::operator<=(), llvm::operator<=(), llvm::operator<=(), llvm::orc::ExecutorAddr::operator<=, llvm::orc::ExecutorAddrRange::operator<=, llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator<=(), llvm::sampleprof::operator<=(), llvm::sys::fs::directory_entry::operator<=(), llvm::AllocaHolder::operator=(), llvm::APFloat::operator=(), llvm::APFloat::operator=(), llvm::APInt::operator=(), llvm::APInt::operator=(), llvm::APSInt::operator=(), llvm::APSInt::operator=(), llvm::AssertingVH< const BasicBlock >::operator=(), llvm::AssertingVH< const BasicBlock >::operator=(), llvm::BlockFrequencyInfo::operator=(), llvm::BranchProbabilityInfo::operator=(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::operator=(), llvm::cas::MappedFileRegionArena::operator=(), llvm::cas::MappedFileRegionArena::operator=(), llvm::cas::OnDiskDataAllocator::operator=(), llvm::cas::OnDiskTrieRawHashMap::operator=(), llvm::CGSCCToFunctionPassAdaptor::operator=(), llvm::const_iterator< MemoryLocation >::operator=(), llvm::const_iterator< MemoryLocation >::operator=(), llvm::detail::AnalysisPassModel< IRUnitT, PassT, InvalidatorT, ExtraArgTs >::operator=(), llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, false >::operator=(), llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::operator=(), llvm::detail::DoubleAPFloat::operator=(), llvm::detail::PassModel< IRUnitT, PassT, AnalysisManagerT, ExtraArgTs >::operator=(), llvm::detail::UniqueFunctionBase< R, P... >::operator=(), llvm::DIE::operator=(), llvm::DIE::operator=(), llvm::DIEUnit::operator=(), llvm::DIEUnit::operator=(), llvm::DominatorTreeBase< BlockT, false >::operator=(), llvm::dwarf_linker::parallel::TypeEntryBody::operator=(), llvm::dwarf_linker::parallel::TypeEntryBody::operator=(), llvm::EquivalenceClasses< BasicBlock * >::operator=(), llvm::FoldingSet< ListTy >::operator=(), llvm::FoldingSetImpl< FoldingSet, T >::operator=(), llvm::FunctionAnalysisManagerMachineFunctionProxy::Result::operator=(), llvm::GVNPass::ValueTable::operator=(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator=(), llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator=(), llvm::ImmutableSet< ValT, ValInfo >::Factory::operator=(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::operator=(), llvm::InstrProfRecord::operator=(), llvm::IntervalMap< IndexT, char >::operator=(), llvm::IntervalMap< IndexT, char >::operator=(), llvm::LazyAtomicPointer< TrieNode >::operator=(), llvm::LazyAtomicPointer< TrieNode >::operator=(), llvm::LoopAnalysisManagerFunctionProxy::Result::operator=(), llvm::LoopInfo::operator=(), llvm::LoopInfoBase< BasicBlock, Loop >::operator=(), llvm::ModuleToPostOrderCGSCCPassAdaptor::operator=(), llvm::opt::ArgList::operator=(), llvm::opt::InputArgList::operator=(), llvm::OptimizationRemarkEmitter::operator=(), llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::operator=(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::operator=(), llvm::RegionInfo::operator=(), llvm::SmallBitVector::operator=(), llvm::SmallBitVector::operator=(), llvm::SmallPtrSet< NodeRef, SmallSize >::operator=(), llvm::SmallPtrSet< NodeRef, SmallSize >::operator=(), llvm::SmallString< 0 >::operator=(), llvm::SmallVector< BitWord >::operator=(), llvm::SmallVector< BitWord >::operator=(), llvm::SmallVector< BitWord >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SparseBitVector< 128 >::operator=(), llvm::SparseBitVector< 128 >::operator=(), llvm::SpecificBumpPtrAllocator< T >::operator=(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::operator=(), llvm::StringTable::Iterator::operator=(), llvm::StringTable::Iterator::operator=(), llvm::TargetIRAnalysis::operator=(), llvm::TargetIRAnalysis::operator=(), llvm::ThreadSafeTrieRawHashMapBase::operator=(), llvm::TinyPtrVector< ReachingDef >::operator=(), llvm::TinyPtrVector< ReachingDef >::operator=(), llvm::TrackingVH< ValueTy >::operator=(), llvm::Use::operator=(), llvm::Use::operator=(), llvm::ValueHandleBase::operator=(), llvm::ValueHandleBase::operator=(), llvm::WeakTrackingVH::operator=(), llvm::WeakTrackingVH::operator=(), llvm::WeakTrackingVH::operator=(), llvm::WeakVH::operator=(), llvm::WeakVH::operator=(), llvm::WeakVH::operator=(), llvm::AAPointerInfo::OffsetInfo::operator==(), llvm::AddressRangesBase< T >::operator==(), llvm::AMDGPU::ClusterDimsAttr::operator==(), llvm::APFloat::operator==(), llvm::APInt::operator==(), llvm::APSInt::operator==(), llvm::APSInt::operator==(), llvm::at::VarRecord::operator==, llvm::bf_iterator< GraphT, SetType, GT >::operator==(), llvm::BinaryStreamRefBase< RefType, StreamType >::operator==, llvm::Bitset< AEK_NUM_EXTENSIONS >::operator==(), llvm::BitVector::operator==(), llvm::BlockFrequency::operator==(), llvm::BranchProbability::operator==(), llvm::cas::CASID::operator==, llvm::cas::ObjectHandle::operator==, llvm::cas::ObjectRef::operator==, llvm::cas::ondisk::InternalRef::operator==, llvm::cas::ondisk::InternalRefArrayRef::iterator::operator==(), llvm::cas::ondisk::InternalRefArrayRef::operator==(), llvm::cas::ondisk::object_refs_iterator::operator==(), llvm::cas::ondisk::ObjectHandle::operator==, llvm::cas::ondisk::ObjectID::operator==, llvm::cfg::Update< BasicBlock * >::operator==(), llvm::CoalescingBitVector< IndexT >::const_iterator::operator==(), llvm::CoalescingBitVector< IndexT >::operator==(), llvm::codeview::operator==(), llvm::concat_iterator< ValueT, decltype(adl_begin(std::declval< RangeTs & >()))... >::operator==(), llvm::const_iterator< MemoryLocation >::operator==(), llvm::coverage::Counter::operator==, llvm::coverage::CoverageMappingIterator::operator==(), llvm::coverage::FunctionRecordIterator::operator==(), llvm::DbgVariableRecord::location_op_iterator::operator==(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator==, llvm::detail::operator==(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator==(), llvm::DILineInfo::operator==(), llvm::DILineInfoSpecifier::operator==(), llvm::dwarf::RegisterLocations::operator==(), llvm::DWARFDebugNames::AttributeEncoding::operator==, llvm::DWARFDie::attribute_iterator::operator==, llvm::DWARFDie::iterator::operator==, llvm::DWARFExpression::iterator::operator==, llvm::dxil::ResourceInfo::operator==(), llvm::dxil::ResourceInfo::ResourceBinding::operator==(), llvm::dxil::ResourceTypeInfo::StructInfo::operator==(), llvm::dxil::ResourceTypeInfo::TypedInfo::operator==(), llvm::dxil::ResourceTypeInfo::UAVInfo::operator==(), llvm::early_inc_iterator_impl< WrappedIteratorT >::operator==, llvm::EquivalenceClasses< ElemTy >::member_iterator::operator==(), llvm::fallible_iterator< ChildFallibleIterator >::operator==, llvm::FeatureBitset::operator==(), llvm::FileLoc::operator==(), llvm::FoldingSetBucketIteratorImpl::operator==(), llvm::FoldingSetIteratorImpl::operator==(), llvm::GenericSchedulerBase::CandPolicy::operator==(), llvm::GenericSchedulerBase::SchedResourceDelta::operator==(), llvm::gsym::CallSiteInfo::operator==(), llvm::gsym::FileEntry::operator==(), llvm::gsym::LineTable::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::gsym::operator==(), llvm::hlsl::Binding::operator==(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator==, llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator==, llvm::ImmutableMap< KeyT, ValT, ValInfo >::operator==(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator==(), llvm::ImmutableSet< ValT, ValInfo >::operator==(), llvm::ImmutableSetRef< ValT, ValInfo >::operator==(), llvm::InstrAspect::operator==(), llvm::InstrProfIterator< GuidMemProfRecordPair, MemProfReader >::operator==(), llvm::InstructionCost::operator==(), llvm::InstructionCost::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::IntervalMapImpl::NodeRef::operator==(), llvm::IntervalTree< PointT, ValueT, DataT >::find_iterator::operator==, llvm::IntrinsicData::operator==(), llvm::IRPosition::operator==(), llvm::iterator_adaptor_base< IteratorImpl< ValueT, IteratorBase >, IteratorBase, std::bidirectional_iterator_tag, ValueT >::operator==, llvm::jitlink::LinkGraph::nested_collection_iterator< section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols >::operator==(), llvm::JITSymbolFlags::operator==(), llvm::json::Object::operator==, llvm::LegacyLegalizeActionStep::operator==(), llvm::LegalizeActionStep::operator==(), llvm::line_iterator::operator==, llvm::LLT::operator==(), llvm::location_op_iterator::operator==(), llvm::MachineBasicBlock::liveout_iterator::operator==(), llvm::MachineMemOperand::operator==, llvm::MachO::operator==(), llvm::MachO::operator==(), llvm::MemoryBufferRef::operator==, llvm::minidump::operator==(), llvm::NodeSet::operator==(), llvm::object::DXContainer::PartIterator::operator==(), llvm::object::operator==(), llvm::object::SFrameParser< E >::FallibleFREIterator::operator==, llvm::OffsetSpan::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::opt::arg_iterator< arglist_type::iterator >::operator==, llvm::orc::AllocGroup::operator==, llvm::orc::ExecutorAddr::operator==, llvm::orc::ExecutorAddrRange::operator==, llvm::orc::ExecutorSymbolDef::operator==, llvm::orc::SymbolStringPtrBase::operator==, llvm::PackedVector< unsigned, BitsPerField, std::bitset< BitsPerField *NumFields > >::operator==(), llvm::PagedVector< T, PageSize >::MaterializedIterator::operator==, llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator==(), llvm::PotentialValuesState< APInt >::operator==(), llvm::PressureChange::operator==(), llvm::RegPressureDelta::operator==(), llvm::remarks::operator==(), llvm::remarks::operator==(), llvm::remarks::operator==(), llvm::RopePieceBTreeIterator::operator==(), llvm::sampleprof::operator==(), llvm::ScalarEvolution::FoldID::operator==(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator==(), llvm::SizeOffsetType< T, C >::operator==(), llvm::SmallBitVector::operator==(), llvm::SmallPtrSetIteratorImpl::operator==(), llvm::SmallSetIterator< T, N, C >::operator==(), llvm::SMLoc::operator==(), llvm::SMTExpr::operator==, llvm::SMTSort::operator==, llvm::SparseBitVector< 128 >::operator==(), llvm::SparseBitVectorElement< ElementSize >::operator==(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator==(), llvm::StackOffset::operator==(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::operator==(), llvm::StringMapIterBase< ValueTy, true >::operator==, llvm::StringTable::Iterator::operator==(), llvm::StringTable::Offset::operator==, llvm::SwitchInst::CaseHandleImpl< const SwitchInst, const ConstantInt, const BasicBlock >::operator==(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator==(), llvm::sys::fs::directory_entry::operator==(), llvm::sys::fs::directory_iterator::operator==(), llvm::sys::fs::recursive_directory_iterator::operator==(), llvm::ValueMapIteratorImpl< MapT, KeyT, false >::operator==(), llvm::ValueSimplifyStateType::operator==(), llvm::vfs::directory_iterator::operator==(), llvm::vfs::OutputConfig::operator==(), llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::wasm::operator==(), llvm::X86FoldTableEntry::operator==(), llvm::yaml::BinaryRef::operator==, operator==(), llvm::APFloat::operator>(), llvm::APSInt::operator>(), llvm::APSInt::operator>(), llvm::BlockFrequency::operator>(), llvm::BranchProbability::operator>(), llvm::codeview::operator>(), llvm::const_iterator< MemoryLocation >::operator>(), llvm::ILPValue::operator>(), llvm::InstructionCost::operator>(), llvm::InstructionCost::operator>(), llvm::iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >, ReferenceTupleType, typename std::iterator_traits< std::tuple_element_t< 0, std::tuple< Iters... > > >::difference_type, ReferenceTupleType *, ReferenceTupleType >::operator>(), llvm::NodeSet::operator>(), llvm::operator>(), llvm::operator>(), llvm::orc::ExecutorAddr::operator>, llvm::orc::ExecutorAddrRange::operator>, llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator>(), llvm::sampleprof::operator>(), llvm::sys::fs::directory_entry::operator>(), llvm::APFloat::operator>=(), llvm::APSInt::operator>=(), llvm::APSInt::operator>=(), llvm::BlockFrequency::operator>=(), llvm::BranchProbability::operator>=(), llvm::codeview::operator>=(), llvm::const_iterator< MemoryLocation >::operator>=(), llvm::ILPValue::operator>=(), llvm::InstructionCost::operator>=(), llvm::InstructionCost::operator>=(), llvm::iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >, ReferenceTupleType, typename std::iterator_traits< std::tuple_element_t< 0, std::tuple< Iters... > > >::difference_type, ReferenceTupleType *, ReferenceTupleType >::operator>=(), llvm::operator>=(), llvm::operator>=(), llvm::orc::ExecutorAddr::operator>=, llvm::orc::ExecutorAddrRange::operator>=, llvm::PointerIntPair< PointerTy, IntBits, IntType >::operator>=(), llvm::sampleprof::operator>=(), llvm::sys::fs::directory_entry::operator>=(), llvm::BitmaskEnumDetail::operator>>(), llvm::APSInt::operator^(), llvm::BitmaskEnumDetail::operator^(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator^(), llvm::FeatureBitset::operator^(), llvm::operator^(), llvm::operator^(), llvm::operator^(), llvm::operator^(), llvm::APInt::operator^=(), llvm::APInt::operator^=(), llvm::APSInt::operator^=(), llvm::BitmaskEnumDetail::operator^=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator^=(), llvm::BitVector::operator^=(), llvm::FeatureBitset::operator^=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator^=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator^=(), llvm::SmallBitVector::operator^=(), llvm::APSInt::operator|(), llvm::BitmaskEnumDetail::operator|(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator|(), llvm::FeatureBitset::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::operator|(), llvm::APInt::operator|=(), llvm::APInt::operator|=(), llvm::APSInt::operator|=(), llvm::BitmaskEnumDetail::operator|=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator|=(), llvm::BitVector::operator|=(), llvm::CoalescingBitVector< IndexT >::operator|=(), llvm::FeatureBitset::operator|=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator|=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator|=(), llvm::JITSymbolFlags::operator|=(), llvm::KnownFPClass::operator|=(), llvm::operator|=(), llvm::operator|=(), llvm::PackedVector< unsigned, BitsPerField, std::bitset< BitsPerField *NumFields > >::operator|=(), llvm::SmallBitVector::operator|=(), llvm::SparseBitVector< 128 >::operator|=(), optimizeLoopExitWithUnknownExitCount(), optimizeMaskToEVL(), optimizeMemCmpConstantSize(), optimizeMemCmpVarSize(), OptimizeNonTrivialIFuncs(), OptNameCompare(), llvm::DWARFDebugLine::Row::orderByAddress(), llvm::DWARFDebugLine::Sequence::orderByHighPC(), llvm::PatternMatch::OverflowingBinaryOp_match< LHS_t, RHS_t, Opcode, WrapFlags, Commutable >::OverflowingBinaryOp_match(), llvm::dxil::ResourceInfo::ResourceBinding::overlapsWith(), AbstractManglingParser< Derived, Alloc >::parseBinaryExpr(), parseCondition(), AbstractManglingParser< Derived, Alloc >::parseExpr(), llvm::PartialOrderingVisitor::PartialOrderingVisitor(), performAddCombineForShiftedOperands(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), performAddUADDVCombine(), performANDCombine(), performBR_CCCombine(), performBRCONDCombine(), performConcatVectorsCombine(), performFADDCombine(), PerformFADDVCMLACombine(), performFlagSettingCombine(), performINSERT_VECTOR_ELTCombine(), performMulCombine(), performMulCombine(), performOrXorChainCombine(), performSELECT_CCCombine(), PerformSELECTCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), performSetccMergeZeroCombine(), performSetCCPunpkCombine(), performSHLCombine(), PerformVQDMULHCombine(), PerformVSELECTCombine(), populateReductionFunction(), processAnd(), processUMulZExtIdiom(), ProfileBinOpInit(), ProfileTernOpInit(), rebuildLoopAfterUnswitch(), reduceVSXSwap(), llvm::APFloat::remainder(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::RewriteRope::RewriteRope(), llvm::APInt::sge(), llvm::APInt::sge(), llvm::APInt::sgt(), llvm::APInt::sgt(), llvm::PatternMatch::ShiftLike_match< LHS_t, Opcode >::ShiftLike_match(), shorter_filter(), shouldTryInjectInvariantCondition(), simplifyAndOrOfFCmps(), simplifyAssociativeBinOp(), simplifyBinOp(), simplifyBinOp(), simplifyCmpInst(), simplifyCmpSelCase(), simplifyCmpSelFalseCase(), simplifyCmpSelTrueCase(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpUsingMonotonicValues(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), simplifyICmpWithDominatingAssume(), simplifyICmpWithIntrinsicOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), simplifyMul24(), simplifySetCCIntoEq(), simplifySetCCWithCTPOP(), SimplifyValuePattern(), simplifyX86pmulh(), sinkMinMaxInBB(), llvm::APInt::sle(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::APInt::slt(), llvm::SmallBitVector::SmallBitVector(), llvm::SmallBitVector::SmallBitVector(), llvm::SmallVector< BitWord >::SmallVector(), llvm::SmallVector< BitWord >::SmallVector(), llvm::SmallVector< BitWord >::SmallVector(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), llvm::simple_ilist< T, Options >::sort(), SortAuthStubPair(), llvm::orc::SymbolLookupSet::sortByName(), llvm::IntervalTree< LVAddress, LVScope * >::sortIntervals(), SortSymbolPair(), llvm::SparseBitVector< 128 >::SparseBitVector(), llvm::SparseBitVector< 128 >::SparseBitVector(), llvm::PatternMatch::SpecificBinaryOp_match< LHS_t, RHS_t, Commutable >::SpecificBinaryOp_match(), llvm::VPlanPatternMatch::SpecificCmp_match< Op0_t, Op1_t, Opcodes >::SpecificCmp_match(), llvm::PatternMatch::SpecificCmpClass_match< LHS_t, RHS_t, Class, Commutable >::SpecificCmpClass_match(), splitVSETCC(), startsWithGlobalOffsetTable(), STATISTIC(), strictCompare(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::StringMap(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::StringMap(), llvm::StringMapImpl::StringMapImpl(), llvm::KnownBits::sub(), SubNameCompare(), llvm::BitVector::subsetOf(), llvm::SmallBitVector::subsetOf(), llvm::APFloat::subtract(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::swap(), llvm::BitVector::swap(), llvm::CachedHashString::swap, llvm::CGSCCToFunctionPassAdaptor::swap, llvm::const_iterator< MemoryLocation >::swap(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::swap(), llvm::detail::AnalysisPassModel< IRUnitT, PassT, InvalidatorT, ExtraArgTs >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, false >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::swap, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, DenseSetEmpty, ValueInfoT, DenseSetPair< ValueT > >, ValueInfoT >< ValueT, ValueInfoT >::swap(), llvm::detail::PassModel< IRUnitT, PassT, AnalysisManagerT, ExtraArgTs >::swap, llvm::iplist_impl< IntrusiveListT, TraitsT >::swap(), llvm::MapVector< StringRef, HashData >::swap(), llvm::ModuleToPostOrderCGSCCPassAdaptor::swap, llvm::SetVector< EdgeType * >::swap(), llvm::SmallBitVector::swap(), llvm::SmallPtrSet< NodeRef, SmallSize >::swap(), llvm::SmallVectorImpl< T >::swap(), std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), std::swap(), SwapN(), TargetArraySortFn(), llvm::BitVector::test(), llvm::SmallBitVector::test(), threadBinOpOverPHI(), threadBinOpOverSelect(), threadCmpOverPHI(), threadCmpOverSelect(), llvm::ThreadSafeTrieRawHashMapBase::ThreadSafeTrieRawHashMapBase(), llvm::Timer::Timer(), llvm::TinyPtrVector< ReachingDef >::TinyPtrVector(), llvm::TinyPtrVector< ReachingDef >::TinyPtrVector(), transformToIndexedCompare(), TranslateM68kCC(), translateSetCCForBranch(), translateSetCCForBranch(), TranslateX86CC(), truncateAVX512SetCCNoBWI(), truncateVectorWithPACK(), tryCombineLongOpWithDup(), tryCombineMULLWithUZP1(), tryFactorization(), tryFoldHelper(), tryGetSecondaryReductionRoot(), TryMatchTrue(), TryMULWIDECombine(), trySimplifyICmpWithAdds(), TryWideExtMulCombine(), llvm::dwarf_linker::parallel::TypeEntryBody::TypeEntryBody(), llvm::dwarf_linker::parallel::TypeEntryBody::TypeEntryBody(), llvm::APInt::uge(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ugt(), llvm::APInt::ule(), llvm::APInt::ule(), llvm::APInt::ult(), llvm::APInt::ult(), llvm::FastMathFlags::unionValue(), llvm::KnownBits::unionWith(), llvm::SparseBitVectorElement< ElementSize >::unionWith(), llvm::detail::UniqueFunctionBase< R, P... >::UniqueFunctionBase(), upgradePMULDQ(), upgradeX86IntrinsicCall(), upgradeX86vpcom(), llvm::Use::Use(), useInversedSetcc(), llvm::ValID::ValID(), llvm::ValueHandleBase::ValueHandleBase(), llvm::ValueHandleBase::ValueHandleBase(), verifyTripCount(), visitMaskedMerge(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitUDivExpr(), llvm::WeakTrackingVH::WeakTrackingVH(), llvm::WeakVH::WeakVH(), llvm::PatternMatch::XorLike_match< LHS, RHS >::XorLike_match(), zeroExtendToMatch(), llvm::InstCombinerImpl::~InstCombinerImpl(), llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF(), and llvm::TargetLoweringObjectFileELF::~TargetLoweringObjectFileELF().