LLVM: lib/Target/X86/X86TargetTransformInfo.cpp File Reference
X86TargetTransformInfo.cpp File Reference
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
#include "X86TargetTransformInfo.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include <optional>
Classes
struct CostKindCosts
Macros
#define DEBUG_TYPE "x86tti"
Typedefs
using CostKindTblEntry = CostTblEntryT<CostKindCosts>
using TypeConversionCostKindTblEntry = TypeConversionCostTblEntryT<CostKindCosts>
Enumerations
enum ClassIDEnum { GPRClass = 0 , VectorClass = 1 , ScalarFPClass = 2 }
Functions
static bool isLegalMaskedLoadStore (Type *ScalarTy, const X86Subtarget *ST)
Detailed Description
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
It uses the target's detailed information to provide more precise answers to certain TTI queries, while letting the target independent and default TTI implementations handle the rest.
Definition in file X86TargetTransformInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86tti"
Definition at line 63 of file X86TargetTransformInfo.cpp.
Typedef Documentation
CostKindTblEntry
using CostKindTblEntry = CostTblEntryT<CostKindCosts>
Definition at line 101 of file X86TargetTransformInfo.cpp.
TypeConversionCostKindTblEntry
using TypeConversionCostKindTblEntry = TypeConversionCostTblEntryT<CostKindCosts>
Definition at line 102 of file X86TargetTransformInfo.cpp.
Enumeration Type Documentation
ClassIDEnum
enum ClassIDEnum
Enumerator
GPRClass
VectorClass
ScalarFPClass
Definition at line 164 of file X86TargetTransformInfo.cpp.
Function Documentation
isLegalMaskedLoadStore()
bool isLegalMaskedLoadStore (Type * ScalarTy, const X86Subtarget * ST) static
Definition at line 6318 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isBFloatTy(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by llvm::X86TTIImpl::isLegalMaskedLoad(), and llvm::X86TTIImpl::isLegalMaskedStore().