LLVM: lib/Target/XCore/XCoreTargetMachine.cpp File Reference
XCoreTargetMachine.cpp File Reference
#include "XCoreTargetMachine.h"
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCore.h"
#include "XCoreMachineFunctionInfo.h"
#include "XCoreTargetObjectFile.h"
#include "XCoreTargetTransformInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include <optional>
Functions
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveXCoreCodeModel (std::optional< CodeModel::Model > CM)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Function Documentation
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 28 of file XCoreTargetMachine.cpp.
References llvm::Reloc::Static.
getEffectiveXCoreCodeModel()
CodeModel::Model getEffectiveXCoreCodeModel (std::optional< CodeModel::Model > CM) static
Definition at line 33 of file XCoreTargetMachine.cpp.
References llvm::CodeModel::Large, llvm::report_fatal_error(), and llvm::CodeModel::Small.
Referenced by llvm::XCoreTargetMachine::XCoreTargetMachine().
LLVMInitializeXCoreTarget()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Definition at line 105 of file XCoreTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheXCoreTarget(), llvm::initializeXCoreAsmPrinterPass(), llvm::initializeXCoreDAGToDAGISelLegacyPass(), llvm::initializeXCoreLowerThreadLocalPass(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, and X.