LLVM: lib/Target/Xtensa/XtensaAsmPrinter.cpp File Reference
XtensaAsmPrinter.cpp File Reference
#include "XtensaAsmPrinter.h"
#include "MCTargetDesc/XtensaInstPrinter.h"
#include "MCTargetDesc/XtensaMCAsmInfo.h"
#include "MCTargetDesc/XtensaTargetStreamer.h"
#include "TargetInfo/XtensaTargetInfo.h"
#include "XtensaConstantPoolValue.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/TargetRegistry.h"
Functions
static Xtensa::Specifier getModifierSpecifier (XtensaCP::XtensaCPModifier Modifier)
INITIALIZE_PASS (XtensaAsmPrinter, "xtensa-asm-printer", "Xtensa Assembly Printer", false, false) extern "C" LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXtensaAsmPrinter()
Function Documentation
getModifierSpecifier()
Xtensa::Specifier getModifierSpecifier (XtensaCP::XtensaCPModifier Modifier) static
Definition at line 36 of file XtensaAsmPrinter.cpp.
References llvm::XtensaCP::no_modifier, llvm::report_fatal_error(), llvm::Xtensa::S_None, llvm::Xtensa::S_TPOFF, and llvm::XtensaCP::TPOFF.
INITIALIZE_PASS()
INITIALIZE_PASS (XtensaAsmPrinter , "xtensa-asm-printer" , "Xtensa Assembly Printer" , false , false)
Definition at line 316 of file XtensaAsmPrinter.cpp.
References A(), llvm::getTheXtensaTarget(), and LLVM_EXTERNAL_VISIBILITY.