LLVM: lib/Target/Xtensa/XtensaISelLowering.cpp File Reference
XtensaISelLowering.cpp File Reference
#include "XtensaISelLowering.h"
#include "XtensaConstantPoolValue.h"
#include "XtensaInstrInfo.h"
#include "XtensaMachineFunctionInfo.h"
#include "XtensaSelectionDAGInfo.h"
#include "XtensaSubtarget.h"
#include "XtensaTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <deque>
#include "XtensaGenCallingConv.inc"
Macros
#define DEBUG_TYPE "xtensa-lower"
Functions
static bool isLongCall (const char *str)
static unsigned toCallerWindow (unsigned Reg)
static bool CC_Xtensa_Custom (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Type *OrigTy, CCState &State)
static unsigned getBranchOpcode (ISD::CondCode Cond)
static std::pair< unsigned, unsigned > getFPBranchKind (ISD::CondCode Cond)
Variables
static const MCPhysReg IntRegs []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xtensa-lower"
Definition at line 36 of file XtensaISelLowering.cpp.
Function Documentation
CC_Xtensa_Custom()
bool CC_Xtensa_Custom (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Type * OrigTy, CCState & State) static
Definition at line 349 of file XtensaISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CCValAssign::getMem(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::ISD::ArgFlagsTy::getNonZeroOrigAlign(), llvm::CCValAssign::getReg(), llvm::MVT::getStoreSize(), IntRegs, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::ISD::ArgFlagsTy::isZExt(), llvm::Offset, llvm::report_fatal_error(), llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
getBranchOpcode()
unsigned getBranchOpcode (ISD::CondCode Cond) static
Definition at line 829 of file XtensaISelLowering.cpp.
References Cond, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
getFPBranchKind()
std::pair< unsigned, unsigned > getFPBranchKind (ISD::CondCode Cond) static
Definition at line 856 of file XtensaISelLowering.cpp.
References Cond, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by llvm::XtensaTargetLowering::EmitInstrWithCustomInserter().
isLongCall()
bool isLongCall (const char * str) static
Definition at line 41 of file XtensaISelLowering.cpp.
Referenced by llvm::XtensaTargetLowering::LowerCall().
toCallerWindow()
unsigned toCallerWindow (unsigned Reg) static
Definition at line 49 of file XtensaISelLowering.cpp.
References Reg.
Variable Documentation
IntRegs
const MCPhysReg IntRegs[] static
Initial value:
= {Xtensa::A2, Xtensa::A3, Xtensa::A4,
     Xtensa::A5, Xtensa::A6, Xtensa::A7}
Definition at line 346 of file XtensaISelLowering.cpp.