LLVM: lib/Target/AArch64/AArch64PointerAuth.cpp File Reference
AArch64PointerAuth.cpp File Reference
#include "AArch64PointerAuth.h"
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
Macros
#define AARCH64_POINTER_AUTH_NAME "AArch64 Pointer Authentication"
Functions
INITIALIZE_PASS (AArch64PointerAuth, "aarch64-ptrauth", AARCH64_POINTER_AUTH_NAME, false, false) FunctionPass *llvm
static void emitPACSymOffsetIntoX16 (const TargetInstrInfo &TII, MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, MCSymbol *PACSym)
static void BuildPACM (const AArch64Subtarget &Subtarget, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, MachineInstr::MIFlag Flags, MCSymbol *PACSym=nullptr)
static void emitPACCFI (const AArch64Subtarget &Subtarget, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, MachineInstr::MIFlag Flags, bool EmitCFI)
Macro Definition Documentation
AARCH64_POINTER_AUTH_NAME
#define AARCH64_POINTER_AUTH_NAME "AArch64 Pointer Authentication"
Definition at line 22 of file AArch64PointerAuth.cpp.
Referenced by INITIALIZE_PASS().
Function Documentation
BuildPACM()
static void BuildPACM (const AArch64Subtarget & Subtarget, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, MachineInstr::MIFlag Flags, MCSymbol * PACSym = nullptr) static
Definition at line 82 of file AArch64PointerAuth.cpp.
References assert(), llvm::BuildMI(), DL, emitPACSymOffsetIntoX16(), llvm::MachineInstr::FrameDestroy, llvm::AArch64Subtarget::getInstrInfo(), MBB, MBBI, llvm::MachineInstrBuilder::setMIFlag(), and TII.
emitPACCFI()
static void emitPACCFI (const AArch64Subtarget & Subtarget, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, MachineInstr::MIFlag Flags, bool EmitCFI) static
Definition at line 100 of file AArch64PointerAuth.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::AArch64FunctionInfo::branchProtectionPAuthLR(), llvm::BuildMI(), llvm::MCCFIInstruction::createNegateRAState(), llvm::MCCFIInstruction::createNegateRAStateWithPC(), DL, llvm::AArch64Subtarget::getInstrInfo(), MBB, MBBI, llvm::MachineInstrBuilder::setMIFlags(), and TII.
emitPACSymOffsetIntoX16()
static void emitPACSymOffsetIntoX16 (const TargetInstrInfo & TII, MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, MCSymbol * PACSym) static
Definition at line 66 of file AArch64PointerAuth.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addSym(), llvm::BuildMI(), DL, I, MBB, llvm::AArch64II::MO_NC, llvm::AArch64II::MO_PAGE, llvm::AArch64II::MO_PAGEOFF, and TII.
Referenced by BuildPACM().
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64PointerAuth , "aarch64-ptrauth" , AARCH64_POINTER_AUTH_NAME , false , false)
Definition at line 57 of file AArch64PointerAuth.cpp.
References AARCH64_POINTER_AUTH_NAME, and llvm::createAArch64PointerAuthPass().