LLVM: lib/Target/AArch64/AArch64FrameLowering.cpp File Reference
AArch64FrameLowering.cpp File Reference
#include "AArch64FrameLowering.h"
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64RegisterInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "MCTargetDesc/AArch64MCTargetDesc.h"
#include "Utils/AArch64SMEAttributes.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <optional>
#include <vector>
Classes
struct ScopedScavengeOrSpill
RAII helper class for scavenging or spilling a register.
struct EmergencyStackSlots
Emergency stack slots for expanding SPILL_PPR_TO_ZPR_SLOT_PSEUDO and FILL_PPR_FROM_ZPR_SLOT_PSEUDO.
struct ScavengeableRegs
Registers available for scavenging (ZPR, PPR3b, GPR).
struct StackAccess
Macros
#define DEBUG_TYPE "frame-info"
#define CASE(n)
#define CASE(n)
Functions
STATISTIC (NumRedZoneFunctions, "Number of functions using red zone")
static int64_t getArgumentStackToRestore (MachineFunction &MF, MachineBasicBlock &MBB)
Returns how much of the incoming argument stack area (in bytes) we should clean up in an epilogue.
static bool produceCompactUnwindFrame (MachineFunction &MF)
static bool needsWinCFI (const MachineFunction &MF)
static StackOffset getSVEStackSize (const MachineFunction &MF)
Returns the size of the entire SVE stackframe (calleesaves + spills).
static Register findScratchNonCalleeSaveRegister (MachineBasicBlock *MBB)
static unsigned estimateRSStackSizeLimit (MachineFunction &MF)
Look at each instruction that references stack frames and return the stack size limit beyond which some of these instructions will require a scratch register during their expansion later.
static unsigned getFixedObjectSize (const MachineFunction &MF, const AArch64FunctionInfo *AFI, bool IsWin64, bool IsFunclet)
Returns the size of the fixed object area (allocated next to sp on entry) On Win64 this may include a var args area and an UnwindHelp object for EH.
static void insertCFISameValue (const MCInstrDesc &Desc, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator InsertPt, unsigned DwarfReg)
static void emitCalleeSavedRestores (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, bool SVE)
static int64_t upperBound (StackOffset Size)
static MCRegister getRegisterOrZero (MCRegister Reg, bool HasSVE)
static void getLiveRegsForEntryMBB (LivePhysRegs &LiveRegs, const MachineBasicBlock &MBB)
static bool windowsRequiresStackProbe (MachineFunction &MF, uint64_t StackSizeInBytes)
static MachineBasicBlock::iterator InsertSEH (MachineBasicBlock::iterator MBBI, const TargetInstrInfo &TII, MachineInstr::MIFlag Flag)
static void fixupSEHOpcode (MachineBasicBlock::iterator MBBI, unsigned LocalStackSize)
bool requiresGetVGCall (MachineFunction &MF)
static bool requiresSaveVG (MachineFunction &MF)
bool isVGInstruction (MachineBasicBlock::iterator MBBI)
static MachineBasicBlock::iterator convertCalleeSaveRestoreToSPPrePostIncDec (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, const TargetInstrInfo *TII, int CSStackSizeInc, bool NeedsWinCFI, bool *HasWinCFI, bool EmitCFI, MachineInstr::MIFlag FrameFlag=MachineInstr::FrameSetup, int CFAOffset=0)
static void fixupCalleeSaveRestoreStackOffset (MachineInstr &MI, uint64_t LocalStackSize, bool NeedsWinCFI, bool *HasWinCFI)
static bool isTargetWindows (const MachineFunction &MF)
static unsigned getStackHazardSize (const MachineFunction &MF)
static bool IsSVECalleeSave (MachineBasicBlock::iterator I)
static void emitShadowCallStackPrologue (const TargetInstrInfo &TII, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, bool NeedsWinCFI, bool NeedsUnwindInfo)
static void emitShadowCallStackEpilogue (const TargetInstrInfo &TII, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL)
static void emitDefineCFAWithFP (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, unsigned FixedObject)
static void getLivePhysRegsUpTo (MachineInstr &MI, const TargetRegisterInfo &TRI, LivePhysRegs &LiveRegs)
Collect live registers from the end of MI's parent up to (including) MI in LiveRegs.
static bool isFuncletReturnInstr (const MachineInstr &MI)
static StackOffset getFPOffset (const MachineFunction &MF, int64_t ObjectOffset)
static StackOffset getStackOffset (const MachineFunction &MF, int64_t ObjectOffset)
static unsigned getPrologueDeath (MachineFunction &MF, unsigned Reg)
static bool invalidateWindowsRegisterPairing (unsigned Reg1, unsigned Reg2, bool NeedsWinCFI, bool IsFirst, const TargetRegisterInfo *TRI)
static bool invalidateRegisterPairing (unsigned Reg1, unsigned Reg2, bool UsesWinAAPCS, bool NeedsWinCFI, bool NeedsFrameRecord, bool IsFirst, const TargetRegisterInfo *TRI)
Returns true if Reg1 and Reg2 cannot be paired using a ldp/stp instruction.
unsigned findFreePredicateReg (BitVector &SavedRegs)
bool enableMultiVectorSpillFill (const AArch64Subtarget &Subtarget, MachineFunction &MF)
static void computeCalleeSaveRegisterPairs (MachineFunction &MF, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI, SmallVectorImpl< RegPairInfo > &RegPairs, bool NeedsFrameRecord)
static std::optional< int > getMMOFrameID (MachineMemOperand *MMO, const MachineFrameInfo &MFI)
static std::optional< int > getLdStFrameID (const MachineInstr &MI, const MachineFrameInfo &MFI)
static bool getSVECalleeSaveSlotRange (const MachineFrameInfo &MFI, int &Min, int &Max)
returns true if there are any SVE callee saves.
static int64_t determineSVEStackObjectOffsets (MachineFrameInfo &MFI, int &MinCSFrameIndex, int &MaxCSFrameIndex, bool AssignOffsets)
static Register tryScavengeRegister (LiveRegUnits const &UsedRegs, BitVector const &ScavengeableRegs, Register PreferredReg)
Attempts to scavenge a register from ScavengeableRegs given the used registers in UsedRegs.
static void propagateFrameFlags (MachineInstr &SourceMI, ArrayRef< MachineInstr * > MachineInstrs)
Propagates frame-setup/destroy flags from SourceMI to all instructions in MachineInstrs.
static bool isInPrologueOrEpilogue (const MachineInstr &MI)
static void expandSpillPPRToZPRSlotPseudo (MachineBasicBlock &MBB, MachineInstr &MI, const TargetRegisterInfo &TRI, LiveRegUnits const &UsedRegs, ScavengeableRegs const &SR, EmergencyStackSlots &SpillSlots)
Expands:
static bool expandFillPPRFromZPRSlotPseudo (MachineBasicBlock &MBB, MachineInstr &MI, const TargetRegisterInfo &TRI, LiveRegUnits const &UsedRegs, ScavengeableRegs const &SR, MachineInstr *&LastPTrue, EmergencyStackSlots &SpillSlots)
Expands:
static bool expandSMEPPRToZPRSpillPseudos (MachineBasicBlock &MBB, const TargetRegisterInfo &TRI, ScavengeableRegs const &SR, EmergencyStackSlots &SpillSlots)
Expands all FILL_PPR_FROM_ZPR_SLOT_PSEUDO and SPILL_PPR_TO_ZPR_SLOT_PSEUDO operations within the MachineBasicBlock MBB.
MachineBasicBlock::iterator emitVGSaveRestore (MachineBasicBlock::iterator II, const AArch64FrameLowering *TFI)
static raw_ostream & operator<< (raw_ostream &OS, const StackAccess &SA)
Variables
static cl::opt< bool > EnableRedZone ("aarch64-redzone", cl::desc("enable use of redzone on AArch64"), cl::init(false), cl::Hidden)
static cl::opt< bool > StackTaggingMergeSetTag ("stack-tagging-merge-settag", cl::desc("merge settag instruction in function epilog"), cl::init(true), cl::Hidden)
static cl::opt< bool > OrderFrameObjects ("aarch64-order-frame-objects", cl::desc("sort stack allocations"), cl::init(true), cl::Hidden)
cl::opt< bool > EnableHomogeneousPrologEpilog ("homogeneous-prolog-epilog", cl::Hidden, cl::desc("Emit homogeneous prologue and epilogue for the size " "optimization (default = off)"))
static cl::opt< unsigned > StackHazardRemarkSize ("aarch64-stack-hazard-remark-size", cl::init(0), cl::Hidden)
static cl::opt< bool > StackHazardInNonStreaming ("aarch64-stack-hazard-in-non-streaming", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableMultiVectorSpillFill ("aarch64-disable-multivector-spill-fill", cl::desc("Disable use of LD/ST pairs for SME2 or SVE2p1"), cl::init(false), cl::Hidden)
static const unsigned DefaultSafeSPDisplacement = 255
This is the biggest offset to the stack pointer we can encode in aarch64 instructions (without using a separate calculation and a temp register).
Macro Definition Documentation
CASE [1/2]
#define CASE (n)
Value:
  case AArch64::W##n:                                                          \
  case AArch64::X##n:                                                          \
    return AArch64::X##n
CASE [2/2]
#define CASE (n)
Value:
  case AArch64::B##n:                                                          \
  case AArch64::H##n:                                                          \
  case AArch64::S##n:                                                          \
  case AArch64::D##n:                                                          \
  case AArch64::Q##n:                                                          \
    return HasSVE ? AArch64::Z##n : AArch64::Q##n
DEBUG_TYPE
#define DEBUG_TYPE "frame-info"
Definition at line 257 of file AArch64FrameLowering.cpp.
Function Documentation
computeCalleeSaveRegisterPairs()
static void computeCalleeSaveRegisterPairs (MachineFunction & MF, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI, SmallVectorImpl< RegPairInfo > & RegPairs, bool NeedsFrameRecord) static
Definition at line 2973 of file AArch64FrameLowering.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), CC, contains(), llvm::Count, llvm::CallingConv::CXX_FAST_TLS, llvm::ArrayRef< T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectAlign(), llvm::AArch64FunctionInfo::getPredicateRegForFillSpill(), getStackHazardSize(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), llvm::AArch64FunctionInfo::hasCalleeSaveStackFreeSpace(), llvm::AArch64FunctionInfo::hasStackHazardSlotIndex(), llvm::AArch64FunctionInfo::hasSwiftAsyncContext(), invalidateRegisterPairing(), invalidateWindowsRegisterPairing(), llvm::AArch64InstrInfo::isFpOrNEON(), isTargetWindows(), llvm_unreachable, needsWinCFI(), llvm::Offset, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, produceCompactUnwindFrame(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AArch64FunctionInfo::setCalleeSaveBaseToFrameRecordOffset(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::ArrayRef< T >::size(), TRI, and llvm::CallingConv::Win64.
Referenced by llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
convertCalleeSaveRestoreToSPPrePostIncDec()
static MachineBasicBlock::iterator convertCalleeSaveRestoreToSPPrePostIncDec (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, const TargetInstrInfo * TII, int CSStackSizeInc, bool NeedsWinCFI, bool * HasWinCFI, bool EmitCFI, MachineInstr::MIFlag FrameFlag = MachineInstr::FrameSetup, int CFAOffset = 0) static
Definition at line 1437 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfaOffset(), llvm::RegState::Define, DL, llvm::emitFrameOffset(), llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, llvm::StackOffset::getFixed(), llvm::TypeSize::getFixed(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), InsertSEH(), isVGInstruction(), llvm_unreachable, MBB, MBBI, requiresSaveVG(), llvm::MachineInstrBuilder::setMemRefs(), llvm::MachineInstrBuilder::setMIFlags(), Success, and TII.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
determineSVEStackObjectOffsets()
static int64_t determineSVEStackObjectOffsets (MachineFrameInfo & MFI, int & MinCSFrameIndex, int & MaxCSFrameIndex, bool AssignOffsets) static
Definition at line 4087 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), assert(), llvm::dbgs(), E(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFrameInfo::getStackProtectorIndex(), getSVECalleeSaveSlotRange(), llvm::MachineFrameInfo::hasStackProtectorIndex(), I, llvm::MachineFrameInfo::isDeadObjectIndex(), LLVM_DEBUG, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::TargetStackID::ScalableVector, and llvm::MachineFrameInfo::setObjectOffset().
emitCalleeSavedRestores()
static void emitCalleeSavedRestores (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, bool SVE) static
Definition at line 727 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::createRestore(), DL, llvm::MachineInstr::FrameDestroy, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFunction::getSubtarget(), Info, MBB, MBBI, Reg, llvm::TargetStackID::ScalableVector, llvm::MachineInstrBuilder::setMIFlags(), llvm::SVE, TII, and TRI.
emitDefineCFAWithFP()
static void emitDefineCFAWithFP (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, unsigned FixedObject) static
Definition at line 1707 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfa(), DL, FramePtr, llvm::MachineInstr::FrameSetup, llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::MachineFunction::getInfo(), llvm::AArch64Subtarget::getInstrInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MBB, MBBI, Reg, llvm::MachineInstrBuilder::setMIFlags(), TII, and TRI.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
emitShadowCallStackEpilogue()
static void emitShadowCallStackEpilogue (const TargetInstrInfo & TII, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL) static
Definition at line 1684 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MCCFIInstruction::createRestore(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameDestroy, llvm::MachineFunction::getInfo(), MBB, MBBI, llvm::AArch64FunctionInfo::needsAsyncDwarfUnwindInfo(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineInstrBuilder::setMIFlags(), and TII.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
emitShadowCallStackPrologue()
static void emitShadowCallStackPrologue (const TargetInstrInfo & TII, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, bool NeedsWinCFI, bool NeedsUnwindInfo) static
Definition at line 1645 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MCCFIInstruction::createEscape(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameSetup, MBB, MBBI, llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
emitVGSaveRestore()
MachineBasicBlock::iterator emitVGSaveRestore (MachineBasicBlock::iterator II, const AArch64FrameLowering * TFI)
Definition at line 4964 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), assert(), llvm::BuildMI(), llvm::MCCFIInstruction::createOffset(), llvm::MCCFIInstruction::createRestore(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::AArch64FunctionInfo::getStreamingVGIdx(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getVGIdx(), llvm::SMEAttrs::hasStreamingBody(), llvm::SMEAttrs::hasStreamingInterface(), II, MBB, MI, llvm::Offset, TII, and TRI.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameIndicesReplaced().
enableMultiVectorSpillFill()
bool enableMultiVectorSpillFill (const AArch64Subtarget & Subtarget, MachineFunction & MF)
Definition at line 2956 of file AArch64FrameLowering.cpp.
References DisableMultiVectorSpillFill, llvm::MachineFunction::getFunction(), llvm::SMEAttrs::hasStreamingBody(), llvm::SMEAttrs::hasStreamingInterface(), and llvm::AArch64Subtarget::isStreaming().
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
estimateRSStackSizeLimit()
static unsigned estimateRSStackSizeLimit (MachineFunction & MF) static
Look at each instruction that references stack frames and return the stack size limit beyond which some of these instructions will require a scratch register during their expansion later.
Definition at line 396 of file AArch64FrameLowering.cpp.
References llvm::AArch64FrameOffsetCannotUpdate, DefaultSafeSPDisplacement, llvm::isAArch64FrameOffsetLegal(), MBB, MI, and llvm::Offset.
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), and llvm::CSKYFrameLowering::determineCalleeSaves().
expandFillPPRFromZPRSlotPseudo()
static bool expandFillPPRFromZPRSlotPseudo (MachineBasicBlock & MBB, MachineInstr & MI, const TargetRegisterInfo & TRI, LiveRegUnits const & UsedRegs, ScavengeableRegs const & SR, MachineInstr *& LastPTrue, EmergencyStackSlots & SpillSlots) static
Expands:
$p0 = FILL_PPR_FROM_ZPR_SLOT_PSEUDO %stack.0, 0
To:
$z0 = LDR_ZXI %stack.0, 0
$p0 = PTRUE_B 31, implicit $vg
$p0 = CMPNE_PPzZI_B $p0, $z0, 0, implicit-def $nzcv, implicit-def $nzcv
While ensuring a ZPR ($z0 in this example) is free for the predicate (spilling if necessary). If the status flags are in use at the point of expansion they are preserved (by moving them to/from a GPR). This may cause an additional spill if no GPR is free at the expansion point.
Definition at line 4338 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::LiveRegUnits::available(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstrBuilder::getInstr(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), ScavengeableRegs::GPRRegs, EmergencyStackSlots::GPRSpillFI, ScopedScavengeOrSpill::hasSpilled(), llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, isInPrologueOrEpilogue(), MBB, MI, llvm::MachineInstr::moveBefore(), ScavengeableRegs::PPR3bRegs, EmergencyStackSlots::PPRSpillFI, propagateFrameFlags(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstrBuilder::setMemRefs(), TII, TRI, ScavengeableRegs::ZPRRegs, and EmergencyStackSlots::ZPRSpillFI.
Referenced by expandSMEPPRToZPRSpillPseudos().
expandSMEPPRToZPRSpillPseudos()
static bool expandSMEPPRToZPRSpillPseudos (MachineBasicBlock & MBB, const TargetRegisterInfo & TRI, ScavengeableRegs const & SR, EmergencyStackSlots & SpillSlots) static
Expands all FILL_PPR_FROM_ZPR_SLOT_PSEUDO and SPILL_PPR_TO_ZPR_SLOT_PSEUDO operations within the MachineBasicBlock MBB.
Definition at line 4410 of file AArch64FrameLowering.cpp.
References llvm::LiveRegUnits::addLiveOuts(), expandFillPPRFromZPRSlotPseudo(), expandSpillPPRToZPRSlotPseudo(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::make_early_inc_range(), MBB, MI, llvm::reverse(), llvm::LiveRegUnits::stepBackward(), and TRI.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized().
expandSpillPPRToZPRSlotPseudo()
static void expandSpillPPRToZPRSlotPseudo (MachineBasicBlock & MBB, MachineInstr & MI, const TargetRegisterInfo & TRI, LiveRegUnits const & UsedRegs, ScavengeableRegs const & SR, EmergencyStackSlots & SpillSlots) static
Expands:
SPILL_PPR_TO_ZPR_SLOT_PSEUDO $p0, %stack.0, 0
To:
$z0 = CPY_ZPzI_B $p0, 1, 0
STR_ZXI $z0, $stack.0, 0
While ensuring a ZPR ($z0 in this example) is free for the predicate (spilling if necessary).
Definition at line 4293 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstrBuilder::getInstr(), llvm::MachineFunction::getSubtarget(), isInPrologueOrEpilogue(), MBB, MI, propagateFrameFlags(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstrBuilder::setMemRefs(), TII, TRI, ScavengeableRegs::ZPRRegs, and EmergencyStackSlots::ZPRSpillFI.
Referenced by expandSMEPPRToZPRSpillPseudos().
findFreePredicateReg()
unsigned findFreePredicateReg (BitVector & SavedRegs)
Definition at line 2945 of file AArch64FrameLowering.cpp.
References llvm::BitVector::test().
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves().
findScratchNonCalleeSaveRegister()
static Register findScratchNonCalleeSaveRegister (MachineBasicBlock * MBB) static
Definition at line 1069 of file AArch64FrameLowering.cpp.
References llvm::LivePhysRegs::available(), llvm::MachineFunction::front(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), getLiveRegsForEntryMBB(), llvm::MachineFunction::getRegInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MBB, MRI, llvm::CallingConv::PreserveNone, Reg, and TRI.
Referenced by buildScratchExecCopy(), llvm::AArch64FrameLowering::canUseAsPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
fixupCalleeSaveRestoreStackOffset()
static void fixupCalleeSaveRestoreStackOffset (MachineInstr & MI, uint64_t LocalStackSize, bool NeedsWinCFI, bool * HasWinCFI) static
Definition at line 1568 of file AArch64FrameLowering.cpp.
References assert(), fixupSEHOpcode(), llvm::MachineOperand::getImm(), llvm_unreachable, MBBI, MI, and llvm::MachineOperand::setImm().
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
fixupSEHOpcode()
static void fixupSEHOpcode (MachineBasicBlock::iterator MBBI, unsigned LocalStackSize) static
Definition at line 1375 of file AArch64FrameLowering.cpp.
References llvm::MachineOperand::getImm(), llvm_unreachable, MBBI, and llvm::MachineOperand::setImm().
Referenced by fixupCalleeSaveRestoreStackOffset().
getArgumentStackToRestore()
static int64_t getArgumentStackToRestore (MachineFunction & MF, MachineBasicBlock & MBB) static
Returns how much of the incoming argument stack area (in bytes) we should clean up in an epilogue.
For the C calling convention this will be 0, for guaranteed tail call conventions it can be positive (a normal return or a tail call to a function that uses less stack space for arguments) or negative (for a tail call to a function that needs more stack space than us for arguments).
Definition at line 299 of file AArch64FrameLowering.cpp.
References llvm::AArch64FunctionInfo::getArgumentStackToRestore(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::AArch64InstrInfo::isTailCallReturnInst(), MBB, and MBBI.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::ARMFrameLowering::emitEpilogue().
getFixedObjectSize()
static unsigned getFixedObjectSize (const MachineFunction & MF, const AArch64FunctionInfo * AFI, bool IsWin64, bool IsFunclet) static
Returns the size of the fixed object area (allocated next to sp on entry) On Win64 this may include a var args area and an UnwindHelp object for EH.
Definition at line 428 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::AArch64FunctionInfo::getTailCallReservedStack(), llvm::AArch64FunctionInfo::getVarArgsGPRSize(), llvm::MachineFunction::hasEHFunclets(), and llvm::report_fatal_error().
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), getFPOffset(), and llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized().
getFPOffset()
static StackOffset getFPOffset (const MachineFunction & MF, int64_t ObjectOffset) static
Definition at line 2683 of file AArch64FrameLowering.cpp.
References F, llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::StackOffset::getFixed(), getFixedObjectSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), and llvm::MachineFunction::getSubtarget().
Referenced by llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getLdStFrameID()
static std::optional< int > getLdStFrameID (const MachineInstr & MI, const MachineFrameInfo & MFI) static
Definition at line 3599 of file AArch64FrameLowering.cpp.
References getMMOFrameID(), and MI.
Referenced by llvm::AArch64FrameLowering::orderFrameObjects().
getLivePhysRegsUpTo()
static void getLivePhysRegsUpTo (MachineInstr & MI, const TargetRegisterInfo & TRI, LivePhysRegs & LiveRegs) static
Collect live registers from the end of MI's parent up to (including) MI in LiveRegs.
Definition at line 1730 of file AArch64FrameLowering.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::make_range(), MBB, MI, llvm::reverse(), llvm::LivePhysRegs::stepBackward(), and TRI.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
getLiveRegsForEntryMBB()
static void getLiveRegsForEntryMBB (LivePhysRegs & LiveRegs, const MachineBasicBlock & MBB) static
Definition at line 1048 of file AArch64FrameLowering.cpp.
References llvm::LivePhysRegs::addLiveIns(), llvm::LivePhysRegs::addReg(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getRegInfo(), and MBB.
Referenced by llvm::AArch64FrameLowering::canUseAsPrologue(), and findScratchNonCalleeSaveRegister().
getMMOFrameID()
static std::optional< int > getMMOFrameID (MachineMemOperand * MMO, const MachineFrameInfo & MFI) static
Definition at line 3579 of file AArch64FrameLowering.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineMemOperand::getPseudoValue(), llvm::getUnderlyingObject(), and llvm::MachineMemOperand::getValue().
Referenced by getLdStFrameID().
getPrologueDeath()
static unsigned getPrologueDeath (MachineFunction & MF, unsigned Reg) static
Definition at line 2858 of file AArch64FrameLowering.cpp.
References llvm::getKillRegState(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::isLiveIn(), and Reg.
Referenced by llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
getRegisterOrZero()
static MCRegister getRegisterOrZero (MCRegister Reg, bool HasSVE) static
Definition at line 920 of file AArch64FrameLowering.cpp.
References CASE, and Reg.
getStackHazardSize()
static unsigned getStackHazardSize (const MachineFunction & MF) static
Definition at line 1621 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
Referenced by llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), computeCalleeSaveRegisterPairs(), and llvm::AArch64FrameLowering::determineCalleeSaves().
getStackOffset()
static StackOffset getStackOffset (const MachineFunction & MF, int64_t ObjectOffset) static
Definition at line 2697 of file AArch64FrameLowering.cpp.
References llvm::StackOffset::getFixed(), and llvm::MachineFunction::getFrameInfo().
Referenced by llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getSVECalleeSaveSlotRange()
static bool getSVECalleeSaveSlotRange (const MachineFrameInfo & MFI, int & Min, int & Max) static
returns true if there are any SVE callee saves.
Definition at line 4059 of file AArch64FrameLowering.cpp.
References assert(), contains(), llvm::MachineFrameInfo::getCalleeSavedInfo(), and llvm::MachineFrameInfo::isCalleeSavedInfoValid().
Referenced by determineSVEStackObjectOffsets().
getSVEStackSize()
static StackOffset getSVEStackSize (const MachineFunction & MF) static
Returns the size of the entire SVE stackframe (calleesaves + spills).
Definition at line 448 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::StackOffset::getScalable(), and llvm::AArch64FunctionInfo::getStackSizeSVE().
Referenced by llvm::AArch64FrameLowering::canUseRedZone(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::getFrameIndexReferenceFromSP(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
insertCFISameValue()
static void insertCFISameValue (const MCInstrDesc & Desc, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator InsertPt, unsigned DwarfReg) static
Definition at line 673 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::createSameValue(), llvm::dwarf_linker::DebugLoc, and MBB.
Referenced by llvm::AArch64FrameLowering::resetCFIToInitialState().
InsertSEH()
static MachineBasicBlock::iterator InsertSEH (MachineBasicBlock::iterator MBBI, const TargetInstrInfo & TII, MachineInstr::MIFlag Flag) static
Definition at line 1231 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), DL, llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm_unreachable, MBB, MBBI, Reg, llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
invalidateRegisterPairing()
static bool invalidateRegisterPairing (unsigned Reg1, unsigned Reg2, bool UsesWinAAPCS, bool NeedsWinCFI, bool NeedsFrameRecord, bool IsFirst, const TargetRegisterInfo * TRI) static
Returns true if Reg1 and Reg2 cannot be paired using a ldp/stp instruction.
WindowsCFI requires that only consecutive registers can be paired. LR and FP need to be allocated together when the frame needs to save the frame-record. This means any other register pairing with LR is invalid.
Definition at line 2910 of file AArch64FrameLowering.cpp.
References invalidateWindowsRegisterPairing(), and TRI.
Referenced by computeCalleeSaveRegisterPairs().
invalidateWindowsRegisterPairing()
static bool invalidateWindowsRegisterPairing (unsigned Reg1, unsigned Reg2, bool NeedsWinCFI, bool IsFirst, const TargetRegisterInfo * TRI) static
Definition at line 2879 of file AArch64FrameLowering.cpp.
References TRI.
Referenced by computeCalleeSaveRegisterPairs(), and invalidateRegisterPairing().
isFuncletReturnInstr()
static bool isFuncletReturnInstr (const MachineInstr & MI) static
Definition at line 2272 of file AArch64FrameLowering.cpp.
References MI.
Referenced by llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), and llvm::X86FrameLowering::restoreCalleeSavedRegisters().
isInPrologueOrEpilogue()
static bool isInPrologueOrEpilogue (const MachineInstr & MI) static
Definition at line 4277 of file AArch64FrameLowering.cpp.
References llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, and MI.
Referenced by expandFillPPRFromZPRSlotPseudo(), and expandSpillPPRToZPRSlotPseudo().
IsSVECalleeSave()
static bool IsSVECalleeSave (MachineBasicBlock::iterator I) static
Definition at line 1626 of file AArch64FrameLowering.cpp.
References llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, and I.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
isTargetWindows()
static bool isTargetWindows (const MachineFunction & MF) static
Definition at line 1617 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getSubtarget(), and isTargetWindows().
Referenced by llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), computeCalleeSaveRegisterPairs(), and isTargetWindows().
isVGInstruction()
bool isVGInstruction (MachineBasicBlock::iterator MBBI)
Definition at line 1414 of file AArch64FrameLowering.cpp.
References MBBI, and requiresGetVGCall().
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), and llvm::AArch64FrameLowering::emitPrologue().
needsWinCFI()
static bool needsWinCFI (const MachineFunction & MF) static
Definition at line 1142 of file AArch64FrameLowering.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by areCandidatesToMergeOrPair(), llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), computeCalleeSaveRegisterPairs(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
operator<<()
static raw_ostream & operator<< (raw_ostream & OS, const StackAccess & SA) inline static
Definition at line 5474 of file AArch64FrameLowering.cpp.
References StackAccess::print().
produceCompactUnwindFrame()
static bool produceCompactUnwindFrame (MachineFunction & MF) static
Definition at line 2868 of file AArch64FrameLowering.cpp.
References llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), llvm::AArch64Subtarget::getTargetLowering(), llvm::AArch64Subtarget::isTargetMachO(), requiresSaveVG(), and llvm::CallingConv::SwiftTail.
Referenced by computeCalleeSaveRegisterPairs(), and llvm::AArch64FrameLowering::determineCalleeSaves().
propagateFrameFlags()
static void propagateFrameFlags (MachineInstr & SourceMI, ArrayRef< MachineInstr * > MachineInstrs) static
Propagates frame-setup/destroy flags from SourceMI to all instructions in MachineInstrs.
Definition at line 4191 of file AArch64FrameLowering.cpp.
References llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, llvm::MachineInstr::getFlag(), and MI.
Referenced by expandFillPPRFromZPRSlotPseudo(), and expandSpillPPRToZPRSlotPseudo().
requiresGetVGCall()
bool requiresGetVGCall (MachineFunction & MF)
Definition at line 1396 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), and llvm::AArch64FunctionInfo::hasStreamingModeChanges().
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and isVGInstruction().
requiresSaveVG()
static bool requiresSaveVG (MachineFunction & MF) static
Definition at line 1402 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), and llvm::AArch64FunctionInfo::hasStreamingModeChanges().
Referenced by llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::processFunctionBeforeFrameIndicesReplaced(), and produceCompactUnwindFrame().
STATISTIC()
STATISTIC (NumRedZoneFunctions , "Number of functions using red zone")
tryScavengeRegister()
static Register tryScavengeRegister (LiveRegUnits const & UsedRegs, BitVector const & ScavengeableRegs, Register PreferredReg) static
Attempts to scavenge a register from ScavengeableRegs given the used registers in UsedRegs.
Definition at line 4177 of file AArch64FrameLowering.cpp.
References llvm::LiveRegUnits::available(), and Reg.
Referenced by ScopedScavengeOrSpill::ScopedScavengeOrSpill().
upperBound()
static int64_t upperBound (StackOffset Size) static
Definition at line 775 of file AArch64FrameLowering.cpp.
References Size.
windowsRequiresStackProbe()
static bool windowsRequiresStackProbe (MachineFunction & MF, uint64_t StackSizeInBytes) static
Definition at line 1132 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), and llvm::AArch64Subtarget::isTargetWindows().
Referenced by llvm::AArch64FrameLowering::determineCalleeSaves(), and llvm::AArch64FrameLowering::emitPrologue().
Variable Documentation
DefaultSafeSPDisplacement
const unsigned DefaultSafeSPDisplacement = 255 static
This is the biggest offset to the stack pointer we can encode in aarch64 instructions (without using a separate calculation and a temp register).
Note that the exception here are vector stores/loads which cannot encode any displacements (see estimateRSStackSizeLimit(), isAArch64FrameOffsetLegal()).
Definition at line 391 of file AArch64FrameLowering.cpp.
Referenced by estimateRSStackSizeLimit(), and llvm::AArch64FrameLowering::hasFPImpl().
DisableMultiVectorSpillFill
cl::opt< bool > DisableMultiVectorSpillFill("aarch64-disable-multivector-spill-fill", cl::desc("Disable use of LD/ST pairs for SME2 or SVE2p1"), cl::init(false), cl::Hidden) ("aarch64-disable-multivector-spill-fill" , cl::desc("Disable use of LD/ST pairs for SME2 or SVE2p1") , cl::init(false) , cl::Hidden) static
Referenced by enableMultiVectorSpillFill().
EnableHomogeneousPrologEpilog
cl::opt< bool > EnableHomogeneousPrologEpilog("homogeneous-prolog-epilog", cl::Hidden, cl::desc("Emit homogeneous prologue and epilogue for the size " "optimization (default = off)")) ("homogeneous-prolog-epilog" , cl::Hidden , cl::desc("Emit homogeneous prologue and epilogue for the size " "optimization (default = off)"))
EnableRedZone
cl::opt< bool > EnableRedZone("aarch64-redzone", cl::desc("enable use of redzone on AArch64"), cl::init(false), cl::Hidden) ("aarch64-redzone" , cl::desc("enable use of redzone on AArch64") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AArch64FrameLowering::canUseRedZone().
OrderFrameObjects
cl::opt< bool > OrderFrameObjects("aarch64-order-frame-objects", cl::desc("sort stack allocations"), cl::init(true), cl::Hidden) ("aarch64-order-frame-objects" , cl::desc("sort stack allocations") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AArch64FrameLowering::orderFrameObjects().
StackHazardInNonStreaming
cl::opt< bool > StackHazardInNonStreaming("aarch64-stack-hazard-in-non-streaming", cl::init(false), cl::Hidden) ("aarch64-stack-hazard-in-non-streaming" , cl::init(false) , cl::Hidden) static
StackHazardRemarkSize
cl::opt< unsigned > StackHazardRemarkSize("aarch64-stack-hazard-remark-size", cl::init(0), cl::Hidden) ("aarch64-stack-hazard-remark-size" , cl::init(0) , cl::Hidden) static
StackTaggingMergeSetTag
cl::opt< bool > StackTaggingMergeSetTag("stack-tagging-merge-settag", cl::desc("merge settag instruction in function epilog"), cl::init(true), cl::Hidden) ("stack-tagging-merge-settag" , cl::desc("merge settag instruction in function epilog") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameIndicesReplaced().