LLVM: lib/Analysis/DXILResource.cpp File Reference
DXILResource.cpp File Reference
#include "llvm/Analysis/DXILResource.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "dxil-resource"
Functions
static StringRef getResourceClassName (ResourceClass RC)
static StringRef getResourceKindName (ResourceKind RK)
static StringRef getElementTypeName (ElementType ET)
static StringRef getSamplerTypeName (SamplerType ST)
static StringRef getSamplerFeedbackTypeName (SamplerFeedbackType SFT)
static dxil::ElementType toDXILElementType (Type *Ty, bool IsSigned)
static void formatTypeName (SmallString< 64 > &Dest, StringRef Name, bool isWriteable, bool isROV)
static bool isROV (dxil::ResourceKind Kind, TargetExtType *Ty)
static std::pair< Type *, bool > getTypedElementType (dxil::ResourceKind Kind, TargetExtType *Ty)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-resource"
Definition at line 23 of file DXILResource.cpp.
Function Documentation
formatTypeName()
static void formatTypeName (SmallString< 64 > & Dest, StringRef Name, bool isWriteable, bool isROV) static
Definition at line 219 of file DXILResource.cpp.
References isROV().
Referenced by llvm::dxil::ResourceTypeInfo::createElementStruct().
getElementTypeName()
static StringRef getElementTypeName (ElementType ET) static
Definition at line 87 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getResourceClassName()
static StringRef getResourceClassName (ResourceClass RC) static
Definition at line 28 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getResourceKindName()
static StringRef getResourceKindName (ResourceKind RK) static
Definition at line 42 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::createElementStruct(), and llvm::dxil::ResourceTypeInfo::print().
getSamplerFeedbackTypeName()
static StringRef getSamplerFeedbackTypeName (SamplerFeedbackType SFT) static
Definition at line 143 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getSamplerTypeName()
static StringRef getSamplerTypeName (SamplerType ST) static
Definition at line 131 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getTypedElementType()
static std::pair< Type *, bool > getTypedElementType (dxil::ResourceKind Kind, TargetExtType * Ty) static
Definition at line 407 of file DXILResource.cpp.
References llvm::cast(), llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::dxil::ResourceTypeInfo::getTyped().
isROV()
static bool isROV (dxil::ResourceKind Kind, TargetExtType * Ty) static
Definition at line 347 of file DXILResource.cpp.
References llvm::cast(), llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by formatTypeName(), and llvm::dxil::ResourceTypeInfo::getUAV().
toDXILElementType()
static dxil::ElementType toDXILElementType (Type * Ty, bool IsSigned) static
Definition at line 153 of file DXILResource.cpp.
Referenced by llvm::dxil::ResourceTypeInfo::getTyped().