LLVM: lib/Analysis/BasicAliasAnalysis.cpp File Reference
BasicAliasAnalysis.cpp File Reference
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/SaveAndRestore.h"
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <utility>
Classes
struct llvm::BasicAAResult::DecomposedGEP
Macros
#define DEBUG_TYPE "basicaa"
Functions
STATISTIC (SearchLimitReached, "Number of times the limit to " "decompose GEPs is reached")
SearchLimitReached / SearchTimes shows how often the limit of to decompose GEPs is reached.
STATISTIC (SearchTimes, "Number of times a GEP is decomposed")
static std::optional< TypeSize > getObjectSize (const Value *V, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc, bool RoundToAlign=false)
Returns the size of the object specified by V or UnknownSize if unknown.
static bool isObjectSmallerThan (const Value *V, TypeSize Size, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc)
Returns true if we can prove that the object specified by V is smaller than Size.
static TypeSize getMinimalExtentFrom (const Value &V, const LocationSize &LocSize, const DataLayout &DL, bool NullIsValidLoc)
Return the minimal extent from V to the end of the underlying object, assuming the result is used in an aliasing query.
static bool isObjectSize (const Value *V, TypeSize Size, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc)
Returns true if we can prove that the object specified by V has size Size.
static bool areBothVScale (const Value *V1, const Value *V2)
Return true if both V1 and V2 are VScale.
static bool isNotInCycle (const Instruction *I, const DominatorTree *DT, const LoopInfo *LI)
static LinearExpression GetLinearExpression (const CastedValue &Val, const DataLayout &DL, unsigned Depth, AssumptionCache *AC, DominatorTree *DT)
Analyzes the specified value as a linear expression: "A*V + B", where A and B are constant integers.
static bool isIntrinsicCall (const CallBase *Call, Intrinsic::ID IID)
static const Function * getParent (const Value *V)
static bool notDifferentParent (const Value *O1, const Value *O2)
static AliasResult MergeAliasResults (AliasResult A, AliasResult B)
INITIALIZE_PASS_BEGIN (BasicAAWrapperPass, "basic-aa", "Basic Alias Analysis (stateless AA impl)", true, true) INITIALIZE_PASS_END(BasicAAWrapperPass
basic Basic Alias Analysis (stateless AA impl)"
Variables
static cl::opt< bool > EnableRecPhiAnalysis ("basic-aa-recphi", cl::Hidden, cl::init(true))
Enable analysis of recursive PHI nodes.
static cl::opt< bool > EnableSeparateStorageAnalysis ("basic-aa-separate-storage", cl::Hidden, cl::init(true))
static const unsigned MaxLookupSearchDepth = 6
basic aa
basic Basic Alias true
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "basicaa"
Definition at line 64 of file BasicAliasAnalysis.cpp.
Function Documentation
Analysis()
basic Basic Alias Analysis (stateless AA impl)
References true.
areBothVScale()
static bool areBothVScale (const Value * V1, const Value * V2) static
Return true if both V1 and V2 are VScale.
Definition at line 188 of file BasicAliasAnalysis.cpp.
References llvm::PatternMatch::m_VScale(), and llvm::PatternMatch::match().
GetLinearExpression()
static LinearExpression GetLinearExpression (const CastedValue & Val, const DataLayout & DL, unsigned Depth, AssumptionCache * AC, DominatorTree * DT) static
Analyzes the specified value as a linear expression: "A*V + B", where A and B are constant integers.
Definition at line 401 of file BasicAliasAnalysis.cpp.
References llvm::cast(), llvm::Depth, DL, llvm::dyn_cast(), E(), GetLinearExpression(), llvm::isa(), and RHS.
Referenced by GetLinearExpression().
getMinimalExtentFrom()
static TypeSize getMinimalExtentFrom (const Value & V, const LocationSize & LocSize, const DataLayout & DL, bool NullIsValidLoc) static
Return the minimal extent from V to the end of the underlying object, assuming the result is used in an aliasing query.
E.g., we do use the query location size and the fact that null pointers cannot alias here.
Definition at line 160 of file BasicAliasAnalysis.cpp.
References DL, llvm::TypeSize::getFixed(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::LocationSize::getValue(), and llvm::LocationSize::isPrecise().
getObjectSize()
static std::optional< TypeSize > getObjectSize (const Value * V, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc, bool RoundToAlign = false) static
Returns the size of the object specified by V or UnknownSize if unknown.
Definition at line 105 of file BasicAliasAnalysis.cpp.
References DL, llvm::TypeSize::getFixed(), llvm::getObjectSize(), llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::ObjectSizeOpts::RoundToAlign, and Size.
getParent()
static const Function * getParent (const Value * V) static
Definition at line 863 of file BasicAliasAnalysis.cpp.
References llvm::dyn_cast(), and llvm::GlobalValue::getParent().
Referenced by llvm::CanonicalLoopInfo::assertOK(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::CloneAndPruneIntoFromInst(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::DataDependenceGraph::DataDependenceGraph(), detectPopcountIdiom(), llvm::DiagnosticInfoMIROptimization::DiagnosticInfoMIROptimization(), llvm::DiagnosticInfoMisExpect::DiagnosticInfoMisExpect(), llvm::DiagnosticInfoOptimizationFailure::DiagnosticInfoOptimizationFailure(), ensureValueAvailableInSuccessor(), llvm::VPBasicBlock::execute(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldURemOfLoopIncrement(), llvm::FunctionPropertiesUpdater::FunctionPropertiesUpdater(), llvm::RegionBase< Tr >::getDepth(), llvm::VPBasicBlock::getEnclosingLoopRegion(), llvm::VPBasicBlock::getEnclosingLoopRegion(), getLocalFunctionMetadata(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::LazyValueInfo::getPredicateAt(), llvm::slpvectorizer::BoUpSLP::getReorderingData(), llvm::InlineAdvice::InlineAdvice(), ARMInstructionSelector::InsertInfo::InsertInfo(), llvm::InstrEmitter::InstrEmitter(), isBlockValidForExtraction(), llvm::PHINode::isComplete(), llvm::VPBasicBlock::isExiting(), isOnlyUsedInEntryBlock(), isUsedOutsideOfDefiningBlock(), LLVMGetBasicBlockParent(), LLVMGetGlobalParent(), LLVMGetInstructionParent(), LLVMGetParamParent(), llvm::LoopConstrainer::LoopConstrainer(), llvm::MachineIRBuilder::MachineIRBuilder(), llvm::MachineModuleSlotTracker::MachineModuleSlotTracker(), llvm::MachineOptimizationRemarkAnalysis::MachineOptimizationRemarkAnalysis(), llvm::MIBundleBuilder::MIBundleBuilder(), notDifferentParent(), llvm::OptimizationRemark::OptimizationRemark(), llvm::OptimizationRemark::OptimizationRemark(), llvm::OptimizationRemarkAnalysis::OptimizationRemarkAnalysis(), llvm::OptimizationRemarkAnalysis::OptimizationRemarkAnalysis(), llvm::OptimizationRemarkAnalysis::OptimizationRemarkAnalysis(), llvm::OptimizationRemarkMissed::OptimizationRemarkMissed(), llvm::OptimizationRemarkMissed::OptimizationRemarkMissed(), llvm::BasicBlock::print(), llvm::DbgMarker::print(), llvm::Function::print(), llvm::MachineFunction::print(), llvm::NamedMDNode::print(), llvm::NamedMDNode::print(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), redirectValuesFromPredecessorsToPhi(), llvm::AssumptionCache::registerAssumption(), llvm::VerifyInstrumentation::registerCallbacks(), RemarkInfo::RemarkInfo(), llvm::LoopRotatePass::run(), llvm::ScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::SIScheduleDAGMI::schedule(), llvm::VLIWMachineScheduler::schedule(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), llvm::SlotTracker::SlotTracker(), splitCallSite(), llvm::GenericCycle< ContextT >::verifyCycle(), and llvm::slpvectorizer::BoUpSLP::VLOperands::VLOperands().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (BasicAAWrapperPass , "basic-aa" , "Basic Alias Analysis (stateless AA impl)" , true , true)
References INITIALIZE_PASS_DEPENDENCY.
isIntrinsicCall()
static bool isIntrinsicCall (const CallBase * Call, Intrinsic::ID IID) static
Definition at line 809 of file BasicAliasAnalysis.cpp.
References Call, llvm::dyn_cast(), and II.
Referenced by llvm::BasicAAResult::getModRefInfo(), llvm::BasicAAResult::getModRefInfo(), isPreserveArrayIndex(), isPreserveStructIndex(), and isPreserveUnionIndex().
isNotInCycle()
static bool isNotInCycle (const Instruction * I, const DominatorTree * DT, const LoopInfo * LI) static
Definition at line 205 of file BasicAliasAnalysis.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::empty(), I, llvm::isPotentiallyReachableFromMany(), and llvm::successors().
Referenced by llvm::EarliestEscapeAnalysis::isNotCapturedBefore().
isObjectSize()
static bool isObjectSize (const Value * V, TypeSize Size, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc) static
Returns true if we can prove that the object specified by V has size Size.
Definition at line 180 of file BasicAliasAnalysis.cpp.
References DL, llvm::getObjectSize(), and Size.
isObjectSmallerThan()
static bool isObjectSmallerThan (const Value * V, TypeSize Size, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc) static
Returns true if we can prove that the object specified by V is smaller than Size.
Bails out early unless the root object is passed as the first parameter.
Definition at line 122 of file BasicAliasAnalysis.cpp.
References DL, llvm::getObjectSize(), llvm::isIdentifiedObject(), llvm::details::FixedOrScalableQuantity< TypeSize, uint64_t >::isKnownLT(), and Size.
MergeAliasResults()
static AliasResult MergeAliasResults (AliasResult A, AliasResult B) static
Definition at line 1376 of file BasicAliasAnalysis.cpp.
References A(), B(), llvm::AliasResult::MayAlias, llvm::AliasResult::MustAlias, and llvm::AliasResult::PartialAlias.
notDifferentParent()
static bool notDifferentParent (const Value * O1, const Value * O2) static
Definition at line 876 of file BasicAliasAnalysis.cpp.
References getParent().
Referenced by llvm::BasicAAResult::alias(), and llvm::BasicAAResult::getModRefInfo().
STATISTIC() [1/2]
STATISTIC (SearchLimitReached , "Number of times the limit to " "decompose GEPs is reached")
SearchLimitReached / SearchTimes shows how often the limit of to decompose GEPs is reached.
It will affect the precision of basic alias analysis.
STATISTIC() [2/2]
STATISTIC (SearchTimes , "Number of times a GEP is decomposed")
Variable Documentation
aa
basic aa
Definition at line 1980 of file BasicAliasAnalysis.cpp.
EnableRecPhiAnalysis
cl::opt< bool > EnableRecPhiAnalysis("basic-aa-recphi", cl::Hidden, cl::init(true)) ("basic-aa-recphi" , cl::Hidden , cl::init(true)) static
Enable analysis of recursive PHI nodes.
EnableSeparateStorageAnalysis
cl::opt< bool > EnableSeparateStorageAnalysis("basic-aa-separate-storage", cl::Hidden, cl::init(true)) ("basic-aa-separate-storage" , cl::Hidden , cl::init(true)) static
MaxLookupSearchDepth
const unsigned MaxLookupSearchDepth = 6 static
Definition at line 84 of file BasicAliasAnalysis.cpp.
true
print machine Print Machine Uniformity Info true
Definition at line 1981 of file BasicAliasAnalysis.cpp.
Referenced by llvm::AArch64FrameLowering::AArch64FrameLowering(), llvm::AArch64leTargetMachine::AArch64leTargetMachine(), llvm::jitlink::Addressable::Addressable(), llvm::User::AllocInfo::AllocInfo(), Analysis(), llvm::APFixedPoint::APFixedPoint(), llvm::ARMLETargetMachine::ARMLETargetMachine(), llvm::AsmToken::AsmToken(), llvm::AVRELFObjectWriter::AVRELFObjectWriter(), llvm::BasicBlockSectionsProfileReader::BasicBlockSectionsProfileReader(), llvm::BitCodeAbbrevOp::BitCodeAbbrevOp(), llvm::BTFDebug::BTFDebug(), llvm::FastISel::CallLoweringInfo::CallLoweringInfo(), llvm::TargetLowering::CallLoweringInfo::CallLoweringInfo(), llvm::CGDataOStream::CGDataOStream(), llvm::circular_raw_ostream::circular_raw_ostream(), COFFOptTable::COFFOptTable(), llvm::PotentialValuesState< APInt >::contains(), llvm::coverage::CountedRegion::CountedRegion(), llvm::coverage::CoverageSegment::CoverageSegment(), llvm::IRBuilderBase::CreateGlobalStringPtr(), LiveDebugValues::DbgOp::DbgOp(), llvm::DbgValueLoc::DbgValueLoc(), llvm::orc::DebugObjectManagerPlugin::DebugObjectManagerPlugin(), llvm::df_ext_iterator< T, SetTy >::df_ext_iterator(), llvm::DomTreeNodeBase< BlockT >::DominatorTreeBase< NodeT, false >, llvm::DomOnlyPrinter::DomOnlyPrinter(), llvm::DomOnlyViewer::DomOnlyViewer(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DomTreeUpdate::DomTreeUpdate(), llvm::Dependence::DVEntry::DVEntry(), llvm::ErrorOr< T >::ErrorOr(), llvm::ErrorOr< T >::ErrorOr(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::Expected(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::Expected(), file(), llvm::FoldingSetBucketIterator< T >::FoldingSetBucketIterator(), function(), llvm::GCNScheduleDAGMILive::GCNScheduleDAGMILive(), llvm::PPCInstrInfo::getFMAPatterns(), llvm::HexagonFrameLowering::HexagonFrameLowering(), llvm::IdentifyingPassPtr::IdentifyingPassPtr(), llvm::idf_ext_iterator< T, SetTy >::idf_ext_iterator(), llvm::idf_ext_iterator< T, SetTy >::idf_ext_iterator(), llvm::CallLowering::IncomingValueAssigner::IncomingValueAssigner(), llvm::CallLowering::IncomingValueHandler::IncomingValueHandler(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY(), llvm::InstCombiner::InstCombiner(), llvm::RecurrenceDescriptor::InstDesc::InstDesc(), llvm::mca::InstrBuilder::InstrBuilder(), llvm::IntrusiveBackListNode::IntrusiveBackListNode(), llvm::ipo_ext_iterator< T, SetType >::ipo_ext_iterator(), llvm::ipo_ext_iterator< T, SetType >::ipo_ext_iterator(), llvm::IRChangedTester::IRChangedTester(), llvm::LICMOptions::LICMOptions(), llvm::jitlink::Block::LinkGraph, llvm::FunctionLoweringInfo::LiveOutInfo::LiveOutInfo(), llvm::X86CallLowering::lowerCall(), llvm::LowerTypeTestsPass::LowerTypeTestsPass(), llvm::MachineConstantPoolEntry::MachineConstantPoolEntry(), llvm::TargetLowering::MakeLibCallOptions::MakeLibCallOptions(), llvm::MIPatternMatch::GCstAndRegMatch::match(), llvm::MIPatternMatch::GFCstAndRegMatch::match(), matchIntrinsicType(), llvm::MCSectionSPIRV::MCContext, llvm::MCObjectStreamer::MCObjectStreamer(), llvm::MCRelaxableFragment::MCRelaxableFragment(), llvm::MCTargetOptions::MCTargetOptions(), llvm::MipselTargetMachine::MipselTargetMachine(), llvm::MipsSubtarget::MipsSubtarget(), llvm::MipsTargetStreamer::MipsTargetStreamer(), llvm::pdb::NativeTypeFunctionSig::NativeTypeFunctionSig(), llvm::NodeSet::NodeSet(), llvm::NVPTXTargetMachine64::NVPTXTargetMachine64(), llvm::ScopedHandle< CommonHandleTraits >::operator bool(), llvm::orc::BlockFreqQuery::operator()(), llvm::OProfileWrapper::OProfileWrapper(), llvm::reassociate::OverflowTracking::OverflowTracking(), llvm::PagedVector< T, PageSize >::PagedVector(), llvm::po_ext_iterator< T, SetType >::po_ext_iterator(), llvm::PostDomOnlyPrinter::PostDomOnlyPrinter(), llvm::PostDomOnlyViewer::PostDomOnlyViewer(), llvm::PotentialValuesState< APInt >::PotentialValuesState(), llvm::ProfOStream::ProfOStream(), llvm::raw_fd_ostream::raw_fd_ostream(), llvm::raw_fd_stream::raw_fd_stream(), llvm::raw_socket_stream::raw_socket_stream(), llvm::mca::ReadState::ReadState(), llvm::detail::RecordKeeperImpl::RecordKeeperImpl(), llvm::RegOrConstant::RegOrConstant(), llvm::RegPressureTracker::RegPressureTracker(), llvm::SPIRV::Requirements::Requirements(), LiveDebugValues::ResolvedDbgOp::ResolvedDbgOp(), llvm::SCEVExpander::SCEVExpander(), llvm::SetState< BaseTy >::SetState(), llvm::SetState< BaseTy >::SetState(), llvm::SIModeRegisterDefaults::SIModeRegisterDefaults(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::detail::SlowDynamicAPInt::SlowDynamicAPInt(), llvm::SmallPtrSetImplBase::SmallPtrSetImplBase(), llvm::SmallSetIterator< T, N, C >::SmallSetIterator(), llvm::SparcV9TargetMachine::SparcV9TargetMachine(), llvm::splitLoopBound(), llvm::object::WindowsResourceParser::StringOrID::StringOrID(), llvm::SUnit::SUnit(), llvm::SUnit::SUnit(), llvm::SymbolInfoTy::SymbolInfoTy(), llvm::SymbolInfoTy::SymbolInfoTy(), llvm::pdb::SymbolListWrapper::SymbolListWrapper(), llvm::TargetOptions::TargetOptions(), llvm::TextCodeGenDataReader::TextCodeGenDataReader(), llvm::TextInstrProfReader::TextInstrProfReader(), llvm::DWARFDebugNames::ValueIterator::ValueIterator(), llvm::VersionTuple::VersionTuple(), llvm::VersionTuple::VersionTuple(), llvm::VersionTuple::VersionTuple(), llvm::WebAssemblyFrameLowering::WebAssemblyFrameLowering(), llvm::WholeProgramDevirtPass::WholeProgramDevirtPass(), llvm::WithCache< Arg >::WithCache(), llvm::X86RegisterInfo::X86RegisterInfo(), and llvm::XtensaTargetMachine::XtensaTargetMachine().