LLVM: llvm::GCNDPPCombinePass Class Reference
llvm::GCNDPPCombinePass Class Reference
#include "Target/AMDGPU/GCNDPPCombine.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MAM)
MachineFunctionProperties getRequiredProperties () const
Public Member Functions inherited from llvm::PassInfoMixin< GCNDPPCombinePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GCNDPPCombinePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 15 of file GCNDPPCombine.h.
Member Function Documentation
getRequiredProperties()
MachineFunctionProperties llvm::GCNDPPCombinePass::getRequiredProperties () const inline
Definition at line 20 of file GCNDPPCombine.h.
References llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::set().
run()
PreservedAnalyses GCNDPPCombinePass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MAM)
Definition at line 796 of file GCNDPPCombine.cpp.
References _, llvm::PreservedAnalyses::all(), Changed, llvm::MachineFunction::getFunction(), llvm::getMachineFunctionPassPreservedAnalyses(), and llvm::Function::hasOptNone().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNDPPCombine.h
lib/Target/AMDGPU/GCNDPPCombine.cpp