LLVM: llvm::GraphTraits< BoUpSLP * >::nodes_iterator Class Reference
llvm::GraphTraits< BoUpSLP * >::nodes_iterator Class Reference
For the node iterator we just need to turn the TreeEntry iterator into a TreeEntry* iterator so that it dereferences to NodeRef.
Public Types
using NodeRef
Public Member Functions
nodes_iterator (const ItTy &It2)
NodeRef operator* ()
nodes_iterator operator++ ()
bool operator!= (const nodes_iterator &N2) const
Detailed Description
For the node iterator we just need to turn the TreeEntry iterator into a TreeEntry* iterator so that it dereferences to NodeRef.
Definition at line 4467 of file SLPVectorizer.cpp.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< BoUpSLP * >::NodeRef
Definition at line 95 of file GraphTraits.h.
Constructor & Destructor Documentation
nodes_iterator()
llvm::GraphTraits< BoUpSLP * >::nodes_iterator::nodes_iterator (const ItTy & It2) inline
Definition at line 4472 of file SLPVectorizer.cpp.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
bool llvm::GraphTraits< BoUpSLP * >::nodes_iterator::operator!= (const nodes_iterator & N2) const inline
Definition at line 4478 of file SLPVectorizer.cpp.
References nodes_iterator().
operator*()
NodeRef llvm::GraphTraits< BoUpSLP * >::nodes_iterator::operator* () inline
Definition at line 4473 of file SLPVectorizer.cpp.
operator++()
nodes_iterator llvm::GraphTraits< BoUpSLP * >::nodes_iterator::operator++ () inline
Definition at line 4474 of file SLPVectorizer.cpp.
References nodes_iterator().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp