LLVM: llvm::cl::generic_parser_base Class Reference
llvm::cl::generic_parser_base Class Reference abstract
#include "llvm/Support/CommandLine.h"
Classes
class GenericOptionInfo
Public Member Functions
generic_parser_base (Option &O)
virtual ~generic_parser_base ()=default
virtual unsigned getNumOptions () const =0
virtual StringRef getOption (unsigned N) const =0
virtual StringRef getDescription (unsigned N) const =0
virtual size_t getOptionWidth (const Option &O) const
virtual const GenericOptionValue & getOptionValue (unsigned N) const =0
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue>
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize ()
void getExtraOptionNames (SmallVectorImpl< StringRef > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (StringRef Name)
Protected Attributes
Option & Owner
Detailed Description
Definition at line 727 of file CommandLine.h.
Constructor & Destructor Documentation
generic_parser_base()
llvm::cl::generic_parser_base::generic_parser_base (Option & O) inline
Definition at line 738 of file CommandLine.h.
References Owner.
Referenced by llvm::cl::parser< DataType >::parser().
~generic_parser_base()
virtual llvm::cl::generic_parser_base::~generic_parser_base () virtual default
Member Function Documentation
findOption()
unsigned generic_parser_base::findOption (StringRef Name)
Definition at line 2069 of file CommandLine.cpp.
References getNumOptions(), and getOption().
Referenced by llvm::cl::parser< DataType >::addLiteralOption(), llvm::PassNameParser::passRegistered(), and llvm::cl::parser< DataType >::removeLiteralOption().
getDescription()
virtual StringRef llvm::cl::generic_parser_base::getDescription (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< bool >, llvm::cl::parser< boolOrDefault >, llvm::cl::parser< char >, llvm::cl::parser< const PassInfo * >, llvm::cl::parser< double >, llvm::cl::parser< float >, llvm::cl::parser< int >, llvm::cl::parser< long >, llvm::cl::parser< long long >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< std::optional< uint64_t > >, llvm::cl::parser< std::set< SPIRV::Extension::Extension > >, llvm::cl::parser< std::string >, llvm::cl::parser< unsigned >, llvm::cl::parser< unsigned long >, and llvm::cl::parser< unsigned long long >.
References N.
Referenced by getOptionWidth(), and printOptionInfo().
getExtraOptionNames()
void llvm::cl::generic_parser_base::getExtraOptionNames (SmallVectorImpl< StringRef > & OptionNames) inline
Definition at line 781 of file CommandLine.h.
References getNumOptions(), getOption(), Owner, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getNumOptions()
virtual unsigned llvm::cl::generic_parser_base::getNumOptions () const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< bool >, llvm::cl::parser< boolOrDefault >, llvm::cl::parser< char >, llvm::cl::parser< const PassInfo * >, llvm::cl::parser< double >, llvm::cl::parser< float >, llvm::cl::parser< int >, llvm::cl::parser< long >, llvm::cl::parser< long long >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< std::optional< uint64_t > >, llvm::cl::parser< std::set< SPIRV::Extension::Extension > >, llvm::cl::parser< std::string >, llvm::cl::parser< unsigned >, llvm::cl::parser< unsigned long >, and llvm::cl::parser< unsigned long long >.
Referenced by findOption(), getExtraOptionNames(), getOptionWidth(), printGenericOptionDiff(), and printOptionInfo().
getOption()
virtual StringRef llvm::cl::generic_parser_base::getOption (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< bool >, llvm::cl::parser< boolOrDefault >, llvm::cl::parser< char >, llvm::cl::parser< const PassInfo * >, llvm::cl::parser< double >, llvm::cl::parser< float >, llvm::cl::parser< int >, llvm::cl::parser< long >, llvm::cl::parser< long long >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< std::optional< uint64_t > >, llvm::cl::parser< std::set< SPIRV::Extension::Extension > >, llvm::cl::parser< std::string >, llvm::cl::parser< unsigned >, llvm::cl::parser< unsigned long >, and llvm::cl::parser< unsigned long long >.
References N.
Referenced by findOption(), getExtraOptionNames(), getOptionWidth(), printGenericOptionDiff(), and printOptionInfo().
getOptionValue()
virtual const GenericOptionValue & llvm::cl::generic_parser_base::getOptionValue (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< bool >, llvm::cl::parser< boolOrDefault >, llvm::cl::parser< char >, llvm::cl::parser< const PassInfo * >, llvm::cl::parser< double >, llvm::cl::parser< float >, llvm::cl::parser< int >, llvm::cl::parser< long >, llvm::cl::parser< long long >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< std::optional< uint64_t > >, llvm::cl::parser< std::set< SPIRV::Extension::Extension > >, llvm::cl::parser< std::string >, llvm::cl::parser< unsigned >, llvm::cl::parser< unsigned long >, and llvm::cl::parser< unsigned long long >.
References llvm::Default, and N.
Referenced by printGenericOptionDiff().
getOptionWidth()
size_t generic_parser_base::getOptionWidth (const Option & O) const virtual
Definition at line 2093 of file CommandLine.cpp.
References argPlusPrefixesSize(), EmptyOption, EqValue, getDescription(), getNumOptions(), getOption(), getOptionPrefixesSize(), llvm::XCOFF::NameSize, shouldPrintOption(), Size, and size().
getValueExpectedFlagDefault()
enum ValueExpected llvm::cl::generic_parser_base::getValueExpectedFlagDefault () const inline
Definition at line 790 of file CommandLine.h.
References Owner, llvm::cl::ValueDisallowed, and llvm::cl::ValueRequired.
initialize()
void llvm::cl::generic_parser_base::initialize () inline
Definition at line 779 of file CommandLine.h.
Referenced by llvm::PassNameParser::initialize(), and llvm::RegisterPassParser< RegistryClass >::initialize().
printGenericOptionDiff()
void generic_parser_base::printGenericOptionDiff (const Option & O, const GenericOptionValue & V, const GenericOptionValue & Default, size_t GlobalWidth) const
Definition at line 2169 of file CommandLine.cpp.
References llvm::Default, getNumOptions(), getOption(), getOptionValue(), llvm::raw_ostream::indent(), MaxOptWidth, llvm::outs(), and llvm::StringRef::size().
Referenced by printOptionDiff().
printOptionDiff()
template<class AnyOptionValue> void llvm::cl::generic_parser_base::printOptionDiff (const Option & O, const AnyOptionValue & V, const AnyOptionValue & Default, size_t GlobalWidth) const inline
Definition at line 773 of file CommandLine.h.
References llvm::Default, and printGenericOptionDiff().
printOptionInfo()
void generic_parser_base::printOptionInfo (const Option & O, size_t GlobalWidth) const virtual
Reimplemented in llvm::PassNameParser.
Definition at line 2116 of file CommandLine.cpp.
References argPlusPrefixesSize(), assert(), llvm::StringRef::empty(), EmptyOption, EqValue, getDescription(), getNumOptions(), getOption(), getOptionPrefixesSize(), OptionPrefix, llvm::outs(), llvm::cl::Option::printEnumValHelpStr(), llvm::cl::Option::printHelpStr(), shouldPrintOption(), llvm::StringRef::size(), and llvm::cl::ValueOptional.
Referenced by llvm::PassNameParser::printOptionInfo().
Member Data Documentation
Owner
Option& llvm::cl::generic_parser_base::Owner protected
Definition at line 814 of file CommandLine.h.
Referenced by llvm::cl::parser< DataType >::addLiteralOption(), generic_parser_base(), getExtraOptionNames(), getValueExpectedFlagDefault(), and llvm::cl::parser< DataType >::parse().
The documentation for this class was generated from the following files:
include/llvm/Support/CommandLine.h
lib/Support/CommandLine.cpp