LLVM: llvm::sandboxir::Context Class Reference
llvm::sandboxir::Context Class Reference
#include "llvm/SandboxIR/Context.h"
Classes
class CallbackID
An ID for a registered callback.
struct TypeDeleter
Type has a protected destructor to prohibit the user from managing the lifetime of the Type objects.
Public Types
using EraseInstrCallback = std::function<void(Instruction *)>
using CreateInstrCallback = std::function<void(Instruction *)>
using MoveInstrCallback
Public Member Functions
Context (LLVMContext &LLVMCtx)
~Context ()
void clear ()
Clears function-level state.
Tracker & getTracker ()
void save ()
Convenience function for getTracker().save()
void revert ()
Convenience function for getTracker().revert()
void accept ()
Convenience function for getTracker().accept()
sandboxir::Value * getValue (llvm::Value *V) const
const sandboxir::Value * getValue (const llvm::Value *V) const
Module * getModule (llvm::Module *LLVMM) const
Module * getOrCreateModule (llvm::Module *LLVMM)
Type * getType (llvm::Type *LLVMTy)
Function * createFunction (llvm::Function *F)
Create a sandboxir::Function for an existing LLVM IR F, including all blocks and instructions.
Module * createModule (llvm::Module *LLVMM)
Create a sandboxir::Module corresponding to LLVMM.
size_t getNumValues () const
\Returns the number of values registered with Context.
CallbackID registerEraseInstrCallback (EraseInstrCallback CB)
Register a callback that gets called when a SandboxIR instruction is about to be removed from its parent.
void unregisterEraseInstrCallback (CallbackID ID)
CallbackID registerCreateInstrCallback (CreateInstrCallback CB)
Register a callback that gets called right after a SandboxIR instruction is created.
void unregisterCreateInstrCallback (CallbackID ID)
CallbackID registerMoveInstrCallback (MoveInstrCallback CB)
Register a callback that gets called when a SandboxIR instruction is about to be moved.
void unregisterMoveInstrCallback (CallbackID ID)
Protected Member Functions
std::unique_ptr< Value > detachLLVMValue (llvm::Value *V)
Remove V from the maps and returns the unique_ptr.
std::unique_ptr< Value > detach (Value *V)
Remove SBV from all SandboxIR maps and stop owning it.
Value * registerValue (std::unique_ptr< Value > &&VPtr)
Take ownership of VPtr and store it in LLVMValueToValueMap.
Value * getOrCreateValueInternal (llvm::Value *V, llvm::User *U=nullptr)
This is the actual function that creates sandboxir values for V, and among others handles all instruction types.
Argument * getOrCreateArgument (llvm::Argument *LLVMArg)
Get or create a sandboxir::Argument for an existing LLVM IR LLVMArg.
Value * getOrCreateValue (llvm::Value *LLVMV)
Get or create a sandboxir::Value for an existing LLVM IR LLVMV.
Constant * getOrCreateConstant (llvm::Constant *LLVMC)
Get or create a sandboxir::Constant from an existing LLVM IR LLVMC.
void runEraseInstrCallbacks (Instruction *I)
void runCreateInstrCallbacks (Instruction *I)
void runMoveInstrCallbacks (Instruction *I, const BBIterator &Where)
BasicBlock * createBasicBlock (llvm::BasicBlock *BB)
Create a sandboxir::BasicBlock for an existing LLVM IR BB.
auto & getLLVMIRBuilder ()
VAArgInst * createVAArgInst (llvm::VAArgInst *SI)
FreezeInst * createFreezeInst (llvm::FreezeInst *SI)
FenceInst * createFenceInst (llvm::FenceInst *SI)
SelectInst * createSelectInst (llvm::SelectInst *SI)
InsertElementInst * createInsertElementInst (llvm::InsertElementInst *IEI)
ExtractElementInst * createExtractElementInst (llvm::ExtractElementInst *EEI)
ShuffleVectorInst * createShuffleVectorInst (llvm::ShuffleVectorInst *SVI)
ExtractValueInst * createExtractValueInst (llvm::ExtractValueInst *IVI)
InsertValueInst * createInsertValueInst (llvm::InsertValueInst *IVI)
BranchInst * createBranchInst (llvm::BranchInst *I)
LoadInst * createLoadInst (llvm::LoadInst *LI)
StoreInst * createStoreInst (llvm::StoreInst *SI)
ReturnInst * createReturnInst (llvm::ReturnInst *I)
CallInst * createCallInst (llvm::CallInst *I)
InvokeInst * createInvokeInst (llvm::InvokeInst *I)
CallBrInst * createCallBrInst (llvm::CallBrInst *I)
LandingPadInst * createLandingPadInst (llvm::LandingPadInst *I)
CatchPadInst * createCatchPadInst (llvm::CatchPadInst *I)
CleanupPadInst * createCleanupPadInst (llvm::CleanupPadInst *I)
CatchReturnInst * createCatchReturnInst (llvm::CatchReturnInst *I)
CleanupReturnInst * createCleanupReturnInst (llvm::CleanupReturnInst *I)
GetElementPtrInst * createGetElementPtrInst (llvm::GetElementPtrInst *I)
CatchSwitchInst * createCatchSwitchInst (llvm::CatchSwitchInst *I)
ResumeInst * createResumeInst (llvm::ResumeInst *I)
SwitchInst * createSwitchInst (llvm::SwitchInst *I)
UnaryOperator * createUnaryOperator (llvm::UnaryOperator *I)
BinaryOperator * createBinaryOperator (llvm::BinaryOperator *I)
AtomicRMWInst * createAtomicRMWInst (llvm::AtomicRMWInst *I)
AtomicCmpXchgInst * createAtomicCmpXchgInst (llvm::AtomicCmpXchgInst *I)
AllocaInst * createAllocaInst (llvm::AllocaInst *I)
CastInst * createCastInst (llvm::CastInst *I)
PHINode * createPHINode (llvm::PHINode *I)
UnreachableInst * createUnreachableInst (llvm::UnreachableInst *UI)
CmpInst * createCmpInst (llvm::CmpInst *I)
ICmpInst * createICmpInst (llvm::ICmpInst *I)
FCmpInst * createFCmpInst (llvm::FCmpInst *I)
Protected Attributes
LLVMContext & LLVMCtx
Tracker IRTracker
DenseMap< llvm::Value *, std::unique_ptr< Value > > LLVMValueToValueMap
Maps LLVM Value to the corresponding sandboxir::Value.
DenseMap< llvm::Module *, std::unique_ptr< Module > > LLVMModuleToModuleMap
Maps an LLVM Module to the corresponding sandboxir::Module.
DenseMap< llvm::Type *, std::unique_ptr< Type, TypeDeleter > > LLVMTypeToTypeMap
Maps LLVM Type to the corresonding sandboxir::Type.
MapVector< CallbackID, EraseInstrCallback > EraseInstrCallbacks
Callbacks called when an IR instruction is about to get erased.
MapVector< CallbackID, CreateInstrCallback > CreateInstrCallbacks
Callbacks called when an IR instruction is about to get created.
MapVector< CallbackID, MoveInstrCallback > MoveInstrCallbacks
Callbacks called when an IR instruction is about to get moved.
CallbackID::ValTy NextCallbackID = 1
A counter used for assigning callback IDs during registration.
IRBuilder< ConstantFolder > LLVMIRBuilder
friend VAArgInst
friend FreezeInst
friend FenceInst
friend SelectInst
friend InsertElementInst
friend ExtractElementInst
friend ShuffleVectorInst
friend ExtractValueInst
friend InsertValueInst
friend BranchInst
friend LoadInst
friend StoreInst
friend ReturnInst
friend CallInst
friend InvokeInst
friend CallBrInst
friend LandingPadInst
friend CatchPadInst
friend CleanupPadInst
friend CatchReturnInst
friend CleanupReturnInst
friend GetElementPtrInst
friend CatchSwitchInst
friend ResumeInst
friend SwitchInst
friend UnaryOperator
friend BinaryOperator
friend AtomicRMWInst
friend AtomicCmpXchgInst
friend AllocaInst
friend CastInst
friend PHINode
friend UnreachableInst
friend CmpInst
friend ICmpInst
friend FCmpInst
Friends
class Type
MessagePack types as defined in the standard, with the exception of Integer being divided into a signed Int and unsigned UInt variant in order to map directly to C++ types.
class PointerType
class IntegerType
class StructType
class Region
class IRSnapshotChecker
class Instruction
Iterator for Instructions in a `BasicBlock.
class EraseFromParent
class Utils
class BasicBlock
Various leaf nodes.
Detailed Description
Definition at line 30 of file Context.h.
Member Typedef Documentation
CreateInstrCallback
using llvm::sandboxir::Context::CreateInstrCallback = std::function<void(Instruction *)>
Definition at line 35 of file Context.h.
EraseInstrCallback
using llvm::sandboxir::Context::EraseInstrCallback = std::function<void(Instruction *)>
Definition at line 33 of file Context.h.
MoveInstrCallback
using llvm::sandboxir::Context::MoveInstrCallback
Initial value:
      std::function<void(Instruction *, const BBIterator &)>
Definition at line 38 of file Context.h.
Constructor & Destructor Documentation
Context()
llvm::sandboxir::Context::Context (LLVMContext & LLVMCtx)
Definition at line 608 of file Context.cpp.
References IRTracker, LLVMCtx, and LLVMIRBuilder.
~Context()
llvm::sandboxir::Context::~Context ()
Definition at line 612 of file Context.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::Context::accept () inline
Convenience function for getTracker().accept()
Definition at line 230 of file Context.h.
References IRTracker.
clear()
void llvm::sandboxir::Context::clear ()
Clears function-level state.
Definition at line 614 of file Context.cpp.
References LLVMValueToValueMap.
createAllocaInst()
AllocaInst * llvm::sandboxir::Context::createAllocaInst (llvm::AllocaInst * I) protected
Definition at line 581 of file Context.cpp.
References AllocaInst, llvm::cast(), I, and registerValue().
createAtomicCmpXchgInst()
AtomicCmpXchgInst * llvm::sandboxir::Context::createAtomicCmpXchgInst (llvm::AtomicCmpXchgInst * I) protected
Definition at line 576 of file Context.cpp.
References AtomicCmpXchgInst, llvm::cast(), I, and registerValue().
createAtomicRMWInst()
AtomicRMWInst * llvm::sandboxir::Context::createAtomicRMWInst (llvm::AtomicRMWInst * I) protected
Definition at line 571 of file Context.cpp.
References AtomicRMWInst, llvm::cast(), I, and registerValue().
createBasicBlock()
BasicBlock * llvm::sandboxir::Context::createBasicBlock (llvm::BasicBlock * BB) protected
Create a sandboxir::BasicBlock for an existing LLVM IR BB.
This will also create all contents of the block.
Definition at line 421 of file Context.cpp.
References assert(), BasicBlock, llvm::cast(), getValue(), and registerValue().
Referenced by createFunction().
createBinaryOperator()
BinaryOperator * llvm::sandboxir::Context::createBinaryOperator (llvm::BinaryOperator * I) protected
Definition at line 567 of file Context.cpp.
References BinaryOperator, llvm::cast(), I, and registerValue().
createBranchInst()
BranchInst * llvm::sandboxir::Context::createBranchInst (llvm::BranchInst * I) protected
Definition at line 483 of file Context.cpp.
References BranchInst, llvm::cast(), and registerValue().
createCallBrInst()
CallBrInst * llvm::sandboxir::Context::createCallBrInst (llvm::CallBrInst * I) protected
Definition at line 513 of file Context.cpp.
References CallBrInst, llvm::cast(), I, and registerValue().
createCallInst()
CallInst * llvm::sandboxir::Context::createCallInst (llvm::CallInst * I) protected
Definition at line 503 of file Context.cpp.
References CallInst, llvm::cast(), I, and registerValue().
createCastInst()
CastInst * llvm::sandboxir::Context::createCastInst (llvm::CastInst * I) protected
Definition at line 585 of file Context.cpp.
References llvm::cast(), CastInst, I, and registerValue().
createCatchPadInst()
CatchPadInst * llvm::sandboxir::Context::createCatchPadInst (llvm::CatchPadInst * I) protected
Definition at line 527 of file Context.cpp.
References llvm::cast(), CatchPadInst, I, and registerValue().
createCatchReturnInst()
CatchReturnInst * llvm::sandboxir::Context::createCatchReturnInst (llvm::CatchReturnInst * I) protected
Definition at line 535 of file Context.cpp.
References llvm::cast(), CatchReturnInst, I, and registerValue().
createCatchSwitchInst()
CatchSwitchInst * llvm::sandboxir::Context::createCatchSwitchInst (llvm::CatchSwitchInst * I) protected
Definition at line 551 of file Context.cpp.
References llvm::cast(), CatchSwitchInst, I, and registerValue().
createCleanupPadInst()
CleanupPadInst * llvm::sandboxir::Context::createCleanupPadInst (llvm::CleanupPadInst * I) protected
Definition at line 531 of file Context.cpp.
References llvm::cast(), CleanupPadInst, I, and registerValue().
createCleanupReturnInst()
CleanupReturnInst * llvm::sandboxir::Context::createCleanupReturnInst (llvm::CleanupReturnInst * I) protected
Definition at line 540 of file Context.cpp.
References llvm::cast(), CleanupReturnInst, I, and registerValue().
createCmpInst()
CmpInst * llvm::sandboxir::Context::createCmpInst (llvm::CmpInst * I) protected
References CmpInst, and I.
createExtractElementInst()
ExtractElementInst * llvm::sandboxir::Context::createExtractElementInst (llvm::ExtractElementInst * EEI) protected
Definition at line 451 of file Context.cpp.
References llvm::cast(), ExtractElementInst, and registerValue().
createExtractValueInst()
ExtractValueInst * llvm::sandboxir::Context::createExtractValueInst (llvm::ExtractValueInst * IVI) protected
Definition at line 471 of file Context.cpp.
References llvm::cast(), ExtractValueInst, and registerValue().
createFCmpInst()
FCmpInst * llvm::sandboxir::Context::createFCmpInst (llvm::FCmpInst * I) protected
Definition at line 597 of file Context.cpp.
References llvm::cast(), FCmpInst, I, and registerValue().
createFenceInst()
FenceInst * llvm::sandboxir::Context::createFenceInst (llvm::FenceInst * SI) protected
Definition at line 440 of file Context.cpp.
References llvm::cast(), FenceInst, and registerValue().
createFreezeInst()
FreezeInst * llvm::sandboxir::Context::createFreezeInst (llvm::FreezeInst * SI) protected
Definition at line 435 of file Context.cpp.
References llvm::cast(), FreezeInst, and registerValue().
createFunction()
Function * llvm::sandboxir::Context::createFunction (llvm::Function * F)
Create a sandboxir::Function for an existing LLVM IR F, including all blocks and instructions.
This is the main API function for creating Sandbox IR. Note: this will not fully populate its parent module. The only globals that will be available are those used within the function.
Definition at line 636 of file Context.cpp.
References llvm::cast(), llvm::cast_or_null(), createBasicBlock(), detach(), F, getOrCreateArgument(), getOrCreateModule(), getValue(), and registerValue().
Referenced by createModule().
createGetElementPtrInst()
GetElementPtrInst * llvm::sandboxir::Context::createGetElementPtrInst (llvm::GetElementPtrInst * I) protected
Definition at line 546 of file Context.cpp.
References llvm::cast(), GetElementPtrInst, I, and registerValue().
createICmpInst()
ICmpInst * llvm::sandboxir::Context::createICmpInst (llvm::ICmpInst * I) protected
Definition at line 593 of file Context.cpp.
References llvm::cast(), I, ICmpInst, and registerValue().
createInsertElementInst()
InsertElementInst * llvm::sandboxir::Context::createInsertElementInst (llvm::InsertElementInst * IEI) protected
Definition at line 458 of file Context.cpp.
References llvm::cast(), InsertElementInst, and registerValue().
createInsertValueInst()
InsertValueInst * llvm::sandboxir::Context::createInsertValueInst (llvm::InsertValueInst * IVI) protected
Definition at line 477 of file Context.cpp.
References llvm::cast(), InsertValueInst, and registerValue().
createInvokeInst()
InvokeInst * llvm::sandboxir::Context::createInvokeInst (llvm::InvokeInst * I) protected
Definition at line 508 of file Context.cpp.
References llvm::cast(), I, InvokeInst, and registerValue().
createLandingPadInst()
LandingPadInst * llvm::sandboxir::Context::createLandingPadInst (llvm::LandingPadInst * I) protected
Definition at line 523 of file Context.cpp.
References llvm::cast(), I, LandingPadInst, and registerValue().
createLoadInst()
LoadInst * llvm::sandboxir::Context::createLoadInst (llvm::LoadInst * LI) protected
Definition at line 488 of file Context.cpp.
References llvm::cast(), LoadInst, and registerValue().
createModule()
Module * llvm::sandboxir::Context::createModule (llvm::Module * LLVMM)
Create a sandboxir::Module corresponding to LLVMM.
Definition at line 657 of file Context.cpp.
References llvm::Module::aliases(), createFunction(), getOrCreateModule(), getOrCreateValue(), llvm::Global, llvm::Module::globals(), and llvm::Module::ifuncs().
createPHINode()
PHINode * llvm::sandboxir::Context::createPHINode (llvm::PHINode * I) protected
Definition at line 589 of file Context.cpp.
References llvm::cast(), I, PHINode, and registerValue().
createResumeInst()
ResumeInst * llvm::sandboxir::Context::createResumeInst (llvm::ResumeInst * I) protected
Definition at line 555 of file Context.cpp.
References llvm::cast(), I, registerValue(), and ResumeInst.
createReturnInst()
ReturnInst * llvm::sandboxir::Context::createReturnInst (llvm::ReturnInst * I) protected
Definition at line 498 of file Context.cpp.
References llvm::cast(), I, registerValue(), and ReturnInst.
createSelectInst()
SelectInst * llvm::sandboxir::Context::createSelectInst (llvm::SelectInst * SI) protected
Definition at line 445 of file Context.cpp.
References llvm::cast(), registerValue(), and SelectInst.
createShuffleVectorInst()
ShuffleVectorInst * llvm::sandboxir::Context::createShuffleVectorInst (llvm::ShuffleVectorInst * SVI) protected
Definition at line 465 of file Context.cpp.
References llvm::cast(), registerValue(), and ShuffleVectorInst.
createStoreInst()
StoreInst * llvm::sandboxir::Context::createStoreInst (llvm::StoreInst * SI) protected
Definition at line 493 of file Context.cpp.
References llvm::cast(), registerValue(), and StoreInst.
createSwitchInst()
SwitchInst * llvm::sandboxir::Context::createSwitchInst (llvm::SwitchInst * I) protected
Definition at line 559 of file Context.cpp.
References llvm::cast(), I, registerValue(), and SwitchInst.
createUnaryOperator()
UnaryOperator * llvm::sandboxir::Context::createUnaryOperator (llvm::UnaryOperator * I) protected
Definition at line 563 of file Context.cpp.
References llvm::cast(), I, registerValue(), and UnaryOperator.
createUnreachableInst()
UnreachableInst * llvm::sandboxir::Context::createUnreachableInst (llvm::UnreachableInst * UI) protected
Definition at line 518 of file Context.cpp.
References llvm::cast(), registerValue(), and UnreachableInst.
createVAArgInst()
VAArgInst * llvm::sandboxir::Context::createVAArgInst (llvm::VAArgInst * SI) protected
Definition at line 430 of file Context.cpp.
References llvm::cast(), registerValue(), and VAArgInst.
detach()
std::unique_ptr< Value > llvm::sandboxir::Context::detach (Value * V) protected
Remove SBV from all SandboxIR maps and stop owning it.
This effectively detaches V from the underlying IR.
Definition at line 27 of file Context.cpp.
References assert(), and detachLLVMValue().
Referenced by createFunction().
detachLLVMValue()
std::unique_ptr< Value > llvm::sandboxir::Context::detachLLVMValue (llvm::Value * V) protected
Remove V from the maps and returns the unique_ptr.
Definition at line 16 of file Context.cpp.
References LLVMValueToValueMap.
Referenced by detach().
getLLVMIRBuilder()
auto & llvm::sandboxir::Context::getLLVMIRBuilder () inline protected
Definition at line 143 of file Context.h.
References LLVMIRBuilder.
getModule()
Module * llvm::sandboxir::Context::getModule (llvm::Module * LLVMM) const
Definition at line 620 of file Context.cpp.
References LLVMModuleToModuleMap.
getNumValues()
size_t llvm::sandboxir::Context::getNumValues () const inline
\Returns the number of values registered with Context.
Definition at line 262 of file Context.h.
References LLVMValueToValueMap.
getOrCreateArgument()
Argument * llvm::sandboxir::Context::getOrCreateArgument (llvm::Argument * LLVMArg) protected
Get or create a sandboxir::Argument for an existing LLVM IR LLVMArg.
Definition at line 407 of file Context.cpp.
References llvm::cast(), and LLVMValueToValueMap.
Referenced by createFunction().
getOrCreateConstant()
Constant * llvm::sandboxir::Context::getOrCreateConstant (llvm::Constant * LLVMC) protected
Get or create a sandboxir::Constant from an existing LLVM IR LLVMC.
Definition at line 417 of file Context.cpp.
References llvm::cast(), and getOrCreateValueInternal().
Referenced by llvm::sandboxir::ShuffleVectorInst::convertShuffleMaskForBitcode(), and llvm::sandboxir::NoCFIValue::get().
getOrCreateModule()
Module * llvm::sandboxir::Context::getOrCreateModule (llvm::Module * LLVMM)
Definition at line 627 of file Context.cpp.
References LLVMModuleToModuleMap, and Module.
Referenced by createFunction(), and createModule().
getOrCreateValue()
Value * llvm::sandboxir::Context::getOrCreateValue (llvm::Value * LLVMV) inline protected
Get or create a sandboxir::Value for an existing LLVM IR LLVMV.
Definition at line 122 of file Context.h.
References getOrCreateValueInternal().
Referenced by createModule(), and llvm::sandboxir::Utils::getMemInstructionBase().
getOrCreateValueInternal()
Value * llvm::sandboxir::Context::getOrCreateValueInternal (llvm::Value * V, llvm::User * U = nullptr) protected
This is the actual function that creates sandboxir values for V, and among others handles all instruction types.
Definition at line 55 of file Context.cpp.
References AllocaInst, assert(), AtomicCmpXchgInst, AtomicRMWInst, BinaryOperator, BranchInst, llvm::CallingConv::C, CallBrInst, CallInst, llvm::cast(), CastInst, CatchPadInst, CatchReturnInst, CatchSwitchInst, CleanupPadInst, CleanupReturnInst, llvm::dyn_cast(), ExtractElementInst, ExtractValueInst, FCmpInst, FenceInst, FreezeInst, GetElementPtrInst, getOpcode(), getOrCreateValueInternal(), getValue(), ICmpInst, InsertElementInst, InsertValueInst, InvokeInst, llvm::isa(), LandingPadInst, LLVMAlloca, LLVMAtomicCmpXchg, LLVMAtomicRMW, LLVMBr, LLVMCall, LLVMCallBr, LLVMFCmp, LLVMFence, LLVMFreeze, LLVMICmp, LLVMInvoke, LLVMRet, LLVMUnreachable, LLVMVAArg, LLVMValueToValueMap, LoadInst, PHINode, ResumeInst, ReturnInst, SelectInst, llvm::seq(), ShuffleVectorInst, StoreInst, SwitchInst, UnaryOperator, UnreachableInst, and VAArgInst.
Referenced by getOrCreateConstant(), getOrCreateValue(), and getOrCreateValueInternal().
getTracker()
Tracker & llvm::sandboxir::Context::getTracker () inline
Definition at line 224 of file Context.h.
References IRTracker.
Referenced by registerValue().
getType()
Type * llvm::sandboxir::Context::getType (llvm::Type * LLVMTy) inline
Definition at line 241 of file Context.h.
References LLVMTypeToTypeMap, and Type.
Referenced by llvm::Type::containsNonLocalTargetExtType(), llvm::sandboxir::VectorType::getExtendedElementVectorType(), llvm::sandboxir::VectorType::getHalfElementsVectorType(), llvm::sandboxir::ExtractValueInst::getIndexedType(), llvm::sandboxir::VectorType::getInteger(), and llvm::sandboxir::CmpInst::makeCmpResultType().
getValue() [1/2]
const sandboxir::Value * llvm::sandboxir::Context::getValue (const llvm::Value * V) const inline
Definition at line 233 of file Context.h.
References getValue().
getValue() [2/2]
Value * llvm::sandboxir::Context::getValue (llvm::Value * V) const
Definition at line 601 of file Context.cpp.
References LLVMValueToValueMap.
Referenced by createBasicBlock(), createFunction(), llvm::sandboxir::DSOLocalEquivalent::get(), getOrCreateValueInternal(), and getValue().
registerCreateInstrCallback()
Context::CallbackID llvm::sandboxir::Context::registerCreateInstrCallback (CreateInstrCallback CB)
Register a callback that gets called right after a SandboxIR instruction is created.
Note that this will also be called when reverting the removal of an instruction. \Returns a callback ID for later deregistration.
Definition at line 709 of file Context.cpp.
References assert(), CreateInstrCallbacks, llvm::sandboxir::MaxRegisteredCallbacks, and NextCallbackID.
registerEraseInstrCallback()
Context::CallbackID llvm::sandboxir::Context::registerEraseInstrCallback (EraseInstrCallback CB)
Register a callback that gets called when a SandboxIR instruction is about to be removed from its parent.
Note that this will also be called when reverting the creation of an instruction. \Returns a callback ID for later deregistration.
Definition at line 695 of file Context.cpp.
References assert(), EraseInstrCallbacks, llvm::sandboxir::MaxRegisteredCallbacks, and NextCallbackID.
registerMoveInstrCallback()
Context::CallbackID llvm::sandboxir::Context::registerMoveInstrCallback (MoveInstrCallback CB)
Register a callback that gets called when a SandboxIR instruction is about to be moved.
Note that this will also be called when reverting a move. \Returns a callback ID for later deregistration.
Definition at line 722 of file Context.cpp.
References assert(), llvm::sandboxir::MaxRegisteredCallbacks, MoveInstrCallbacks, and NextCallbackID.
registerValue()
Value * llvm::sandboxir::Context::registerValue (std::unique_ptr< Value > && VPtr) protected
Take ownership of VPtr and store it in LLVMValueToValueMap.
Definition at line 34 of file Context.cpp.
References assert(), llvm::dyn_cast(), llvm::sandboxir::Tracker::emplaceIfTracking(), getTracker(), I, LLVMValueToValueMap, and runCreateInstrCallbacks().
Referenced by createAllocaInst(), createAtomicCmpXchgInst(), createAtomicRMWInst(), createBasicBlock(), createBinaryOperator(), createBranchInst(), createCallBrInst(), createCallInst(), createCastInst(), createCatchPadInst(), createCatchReturnInst(), createCatchSwitchInst(), createCleanupPadInst(), createCleanupReturnInst(), createExtractElementInst(), createExtractValueInst(), createFCmpInst(), createFenceInst(), createFreezeInst(), createFunction(), createGetElementPtrInst(), createICmpInst(), createInsertElementInst(), createInsertValueInst(), createInvokeInst(), createLandingPadInst(), createLoadInst(), createPHINode(), createResumeInst(), createReturnInst(), createSelectInst(), createShuffleVectorInst(), createStoreInst(), createSwitchInst(), createUnaryOperator(), createUnreachableInst(), and createVAArgInst().
revert()
void llvm::sandboxir::Context::revert () inline
Convenience function for getTracker().revert()
Definition at line 228 of file Context.h.
References IRTracker.
runCreateInstrCallbacks()
void llvm::sandboxir::Context::runCreateInstrCallbacks (Instruction * I) protected
Definition at line 680 of file Context.cpp.
References CreateInstrCallbacks, I, and Instruction.
Referenced by registerValue().
runEraseInstrCallbacks()
void llvm::sandboxir::Context::runEraseInstrCallbacks (Instruction * I) protected
Definition at line 675 of file Context.cpp.
References EraseInstrCallbacks, I, and Instruction.
runMoveInstrCallbacks()
void llvm::sandboxir::Context::runMoveInstrCallbacks (Instruction * I, const BBIterator & Where) protected
Definition at line 685 of file Context.cpp.
References I, Instruction, and MoveInstrCallbacks.
save()
void llvm::sandboxir::Context::save () inline
Convenience function for getTracker().save()
Definition at line 226 of file Context.h.
References IRTracker.
unregisterCreateInstrCallback()
void llvm::sandboxir::Context::unregisterCreateInstrCallback (CallbackID ID)
Definition at line 716 of file Context.cpp.
References assert(), and CreateInstrCallbacks.
unregisterEraseInstrCallback()
void llvm::sandboxir::Context::unregisterEraseInstrCallback (CallbackID ID)
Definition at line 702 of file Context.cpp.
References assert(), and EraseInstrCallbacks.
unregisterMoveInstrCallback()
void llvm::sandboxir::Context::unregisterMoveInstrCallback (CallbackID ID)
Definition at line 729 of file Context.cpp.
References assert(), and MoveInstrCallbacks.
Friends And Related Symbol Documentation
BasicBlock
friend class BasicBlock friend
Various leaf nodes.
Definition at line 140 of file Context.h.
References BasicBlock.
Referenced by BasicBlock, and createBasicBlock().
EraseFromParent
friend class EraseFromParent friend
Definition at line 115 of file Context.h.
References EraseFromParent.
Referenced by EraseFromParent.
Instruction
friend class Instruction friend
Iterator for Instructions in a `BasicBlock.
/ \Returns an sandboxir::Instruction & when derereferenced. class BBIterator { public: using difference_type = std::ptrdiff_t; using value_type = Instruction; using pointer = value_type *; using reference = value_type &; using iterator_category = std::bidirectional_iterator_tag;
private: llvm::BasicBlock *BB; llvm::BasicBlock::iterator It; Context *Ctx; pointer getInstr(llvm::BasicBlock::iterator It) const;
public: BBIterator() : BB(nullptr), Ctx(nullptr) {} BBIterator(llvm::BasicBlock <em>BB, llvm::BasicBlock::iterator It, Context *Ctx) : BB(BB), It(It), Ctx(Ctx) {} reference operator() const { return *getInstr(It); } BBIterator &operator++(); BBIterator operator++(int) { auto Copy = *this; ++*this; return Copy; } BBIterator &operator--(); BBIterator operator--(int) { auto Copy = *this; –*this; return Copy; } bool operator==(const BBIterator &Other) const { assert(Ctx == Other.Ctx && "BBIterators in different context!"); return It == Other.It; } bool operator!=(const BBIterator &Other) const { return !(*this == Other); } / \Returns the SBInstruction that corresponds to this iterator, or null if / the instruction is not found in the IR-to-SandboxIR tables. pointer get() const { return getInstr(It); } / \Returns the parent BB. BasicBlock *getNodeParent() const; };
/ Contains a list of sandboxir::Instruction's. class BasicBlock : public Value { / Builds a graph that contains all values in BB in their original form / i.e., no vectorization is taking place here. void buildBasicBlockFromLLVMIR(llvm::BasicBlock *LLVMBB); friend class Context; // For buildBasicBlockFromIR
Definition at line 112 of file Context.h.
References Instruction.
Referenced by Instruction, runCreateInstrCallbacks(), runEraseInstrCallbacks(), runMoveInstrCallbacks(), and Utils.
IntegerType
friend class IntegerType friend
Definition at line 68 of file Context.h.
References IntegerType.
Referenced by IntegerType.
IRSnapshotChecker
friend class IRSnapshotChecker friend
Definition at line 71 of file Context.h.
References IRSnapshotChecker.
Referenced by IRSnapshotChecker.
PointerType
friend class PointerType friend
Definition at line 67 of file Context.h.
References PointerType.
Referenced by PointerType.
Region
friend class Region friend
Definition at line 70 of file Context.h.
References Region.
Referenced by Region.
StructType
friend class StructType friend
Definition at line 69 of file Context.h.
References StructType.
Referenced by StructType.
Type
friend class Type friend
MessagePack types as defined in the standard, with the exception of Integer being divided into a signed Int and unsigned UInt variant in order to map directly to C++ types.
The types map onto corresponding union members of the Object struct.
Definition at line 66 of file Context.h.
References Type.
Referenced by getType(), llvm::sandboxir::Context::TypeDeleter::operator()(), and Type.
Utils
friend class Utils friend
Definition at line 127 of file Context.h.
References I, Instruction, and Utils.
Referenced by Utils.
Member Data Documentation
AllocaInst
friend llvm::sandboxir::Context::AllocaInst protected
Definition at line 204 of file Context.h.
Referenced by createAllocaInst(), and getOrCreateValueInternal().
AtomicCmpXchgInst
friend llvm::sandboxir::Context::AtomicCmpXchgInst protected
Definition at line 202 of file Context.h.
Referenced by createAtomicCmpXchgInst(), and getOrCreateValueInternal().
AtomicRMWInst
friend llvm::sandboxir::Context::AtomicRMWInst protected
Definition at line 200 of file Context.h.
Referenced by createAtomicRMWInst(), and getOrCreateValueInternal().
BinaryOperator
friend llvm::sandboxir::Context::BinaryOperator protected
Definition at line 198 of file Context.h.
Referenced by createBinaryOperator(), and getOrCreateValueInternal().
BranchInst
friend llvm::sandboxir::Context::BranchInst protected
Definition at line 164 of file Context.h.
Referenced by createBranchInst(), and getOrCreateValueInternal().
CallBrInst
friend llvm::sandboxir::Context::CallBrInst protected
Definition at line 176 of file Context.h.
Referenced by createCallBrInst(), and getOrCreateValueInternal().
CallInst
friend llvm::sandboxir::Context::CallInst protected
Definition at line 172 of file Context.h.
Referenced by createCallInst(), and getOrCreateValueInternal().
CastInst
friend llvm::sandboxir::Context::CastInst protected
Definition at line 206 of file Context.h.
Referenced by createCastInst(), and getOrCreateValueInternal().
CatchPadInst
friend llvm::sandboxir::Context::CatchPadInst protected
Definition at line 180 of file Context.h.
Referenced by createCatchPadInst(), and getOrCreateValueInternal().
CatchReturnInst
friend llvm::sandboxir::Context::CatchReturnInst protected
Definition at line 184 of file Context.h.
Referenced by createCatchReturnInst(), and getOrCreateValueInternal().
CatchSwitchInst
friend llvm::sandboxir::Context::CatchSwitchInst protected
Definition at line 190 of file Context.h.
Referenced by createCatchSwitchInst(), and getOrCreateValueInternal().
CleanupPadInst
friend llvm::sandboxir::Context::CleanupPadInst protected
Definition at line 182 of file Context.h.
Referenced by createCleanupPadInst(), and getOrCreateValueInternal().
CleanupReturnInst
friend llvm::sandboxir::Context::CleanupReturnInst protected
Definition at line 186 of file Context.h.
Referenced by createCleanupReturnInst(), and getOrCreateValueInternal().
CmpInst
friend llvm::sandboxir::Context::CmpInst protected
Definition at line 212 of file Context.h.
Referenced by createCmpInst().
CreateInstrCallbacks
MapVector<CallbackID, CreateInstrCallback> llvm::sandboxir::Context::CreateInstrCallbacks protected
Callbacks called when an IR instruction is about to get created.
Keys are used as IDs for deregistration.
Definition at line 97 of file Context.h.
Referenced by registerCreateInstrCallback(), runCreateInstrCallbacks(), and unregisterCreateInstrCallback().
EraseInstrCallbacks
MapVector<CallbackID, EraseInstrCallback> llvm::sandboxir::Context::EraseInstrCallbacks protected
Callbacks called when an IR instruction is about to get erased.
Keys are used as IDs for deregistration.
Definition at line 94 of file Context.h.
Referenced by registerEraseInstrCallback(), runEraseInstrCallbacks(), and unregisterEraseInstrCallback().
ExtractElementInst
friend llvm::sandboxir::Context::ExtractElementInst protected
Definition at line 156 of file Context.h.
Referenced by createExtractElementInst(), and getOrCreateValueInternal().
ExtractValueInst
friend llvm::sandboxir::Context::ExtractValueInst protected
Definition at line 160 of file Context.h.
Referenced by createExtractValueInst(), and getOrCreateValueInternal().
FCmpInst
friend llvm::sandboxir::Context::FCmpInst protected
Definition at line 216 of file Context.h.
Referenced by createFCmpInst(), and getOrCreateValueInternal().
FenceInst
friend llvm::sandboxir::Context::FenceInst protected
Definition at line 150 of file Context.h.
Referenced by createFenceInst(), and getOrCreateValueInternal().
FreezeInst
friend llvm::sandboxir::Context::FreezeInst protected
Definition at line 148 of file Context.h.
Referenced by createFreezeInst(), and getOrCreateValueInternal().
GetElementPtrInst
friend llvm::sandboxir::Context::GetElementPtrInst protected
Definition at line 188 of file Context.h.
Referenced by createGetElementPtrInst(), and getOrCreateValueInternal().
ICmpInst
friend llvm::sandboxir::Context::ICmpInst protected
Definition at line 214 of file Context.h.
Referenced by createICmpInst(), and getOrCreateValueInternal().
InsertElementInst
friend llvm::sandboxir::Context::InsertElementInst protected
Definition at line 154 of file Context.h.
Referenced by createInsertElementInst(), and getOrCreateValueInternal().
InsertValueInst
friend llvm::sandboxir::Context::InsertValueInst protected
Definition at line 162 of file Context.h.
Referenced by createInsertValueInst(), and getOrCreateValueInternal().
InvokeInst
friend llvm::sandboxir::Context::InvokeInst protected
Definition at line 174 of file Context.h.
Referenced by createInvokeInst(), and getOrCreateValueInternal().
IRTracker
Tracker llvm::sandboxir::Context::IRTracker protected
Definition at line 73 of file Context.h.
Referenced by accept(), Context(), getTracker(), revert(), and save().
LandingPadInst
friend llvm::sandboxir::Context::LandingPadInst protected
Definition at line 178 of file Context.h.
Referenced by createLandingPadInst(), and getOrCreateValueInternal().
LLVMCtx
LLVMContext& llvm::sandboxir::Context::LLVMCtx protected
Definition at line 65 of file Context.h.
Referenced by Context(), and llvm::sandboxir::CmpInst::makeCmpResultType().
LLVMIRBuilder
IRBuilder<ConstantFolder> llvm::sandboxir::Context::LLVMIRBuilder protected
Definition at line 142 of file Context.h.
Referenced by Context(), and getLLVMIRBuilder().
LLVMModuleToModuleMap
DenseMap<llvm::Module *, std::unique_ptr<Module> > llvm::sandboxir::Context::LLVMModuleToModuleMap protected
Maps an LLVM Module to the corresponding sandboxir::Module.
Definition at line 80 of file Context.h.
Referenced by getModule(), and getOrCreateModule().
LLVMTypeToTypeMap
DenseMap<llvm::Type *, std::unique_ptr<Type, TypeDeleter> > llvm::sandboxir::Context::LLVMTypeToTypeMap protected
Maps LLVM Type to the corresonding sandboxir::Type.
Owns all Sandbox IR Type objects.
Definition at line 90 of file Context.h.
Referenced by getType().
LLVMValueToValueMap
DenseMap<llvm::Value *, std::unique_ptr<Value> > llvm::sandboxir::Context::LLVMValueToValueMap protected
Maps LLVM Value to the corresponding sandboxir::Value.
Owns all SandboxIR objects.
Definition at line 77 of file Context.h.
Referenced by clear(), detachLLVMValue(), getNumValues(), getOrCreateArgument(), getOrCreateValueInternal(), getValue(), and registerValue().
LoadInst
friend llvm::sandboxir::Context::LoadInst protected
Definition at line 166 of file Context.h.
Referenced by createLoadInst(), and getOrCreateValueInternal().
MoveInstrCallbacks
MapVector<CallbackID, MoveInstrCallback> llvm::sandboxir::Context::MoveInstrCallbacks protected
Callbacks called when an IR instruction is about to get moved.
Keys are used as IDs for deregistration.
Definition at line 100 of file Context.h.
Referenced by registerMoveInstrCallback(), runMoveInstrCallbacks(), and unregisterMoveInstrCallback().
NextCallbackID
CallbackID::ValTy llvm::sandboxir::Context::NextCallbackID = 1 protected
A counter used for assigning callback IDs during registration.
The same counter is used for all kinds of callbacks so we can detect mismatched registration/deregistration.
Definition at line 105 of file Context.h.
Referenced by registerCreateInstrCallback(), registerEraseInstrCallback(), and registerMoveInstrCallback().
PHINode
friend llvm::sandboxir::Context::PHINode protected
Definition at line 208 of file Context.h.
Referenced by createPHINode(), and getOrCreateValueInternal().
ResumeInst
friend llvm::sandboxir::Context::ResumeInst protected
Definition at line 192 of file Context.h.
Referenced by createResumeInst(), and getOrCreateValueInternal().
ReturnInst
friend llvm::sandboxir::Context::ReturnInst protected
Definition at line 170 of file Context.h.
Referenced by createReturnInst(), and getOrCreateValueInternal().
SelectInst
friend llvm::sandboxir::Context::SelectInst protected
Definition at line 152 of file Context.h.
Referenced by createSelectInst(), and getOrCreateValueInternal().
ShuffleVectorInst
friend llvm::sandboxir::Context::ShuffleVectorInst protected
Definition at line 158 of file Context.h.
Referenced by createShuffleVectorInst(), and getOrCreateValueInternal().
StoreInst
friend llvm::sandboxir::Context::StoreInst protected
Definition at line 168 of file Context.h.
Referenced by createStoreInst(), and getOrCreateValueInternal().
SwitchInst
friend llvm::sandboxir::Context::SwitchInst protected
Definition at line 194 of file Context.h.
Referenced by createSwitchInst(), and getOrCreateValueInternal().
UnaryOperator
friend llvm::sandboxir::Context::UnaryOperator protected
Definition at line 196 of file Context.h.
Referenced by createUnaryOperator(), and getOrCreateValueInternal().
UnreachableInst
friend llvm::sandboxir::Context::UnreachableInst protected
Definition at line 210 of file Context.h.
Referenced by createUnreachableInst(), and getOrCreateValueInternal().
VAArgInst
friend llvm::sandboxir::Context::VAArgInst protected
Definition at line 146 of file Context.h.
Referenced by createVAArgInst(), and getOrCreateValueInternal().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Context.h
lib/SandboxIR/Context.cpp