LLVM: llvm::coro::SwitchCloner Class Reference
llvm::coro::SwitchCloner Class Reference
#include "Transforms/Coroutines/CoroCloner.h"
Static Public Member Functions
static Function * createClone (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, CloneKind FKind, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a clone for a switch lowering.
Static Public Member Functions inherited from llvm::coro::BaseCloner
static Function * createClone (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, Function *NewF, AnyCoroSuspendInst *ActiveSuspend, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a clone for a continuation lowering.
Protected Member Functions
SwitchCloner (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, CloneKind FKind, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a cloner for a switch lowering.
void create () override
Clone the body of the original function into a resume function of some sort.
Protected Member Functions inherited from llvm::coro::BaseCloner
BaseCloner (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, Function *NewF, AnyCoroSuspendInst *ActiveSuspend, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a cloner for a continuation lowering.
bool isSwitchDestroyFunction ()
void replaceEntryBlock ()
Value * deriveNewFramePointer ()
Derive the value of the new frame pointer.
void replaceRetconOrAsyncSuspendUses ()
Replace uses of the active llvm.coro.suspend.retcon/async call with the arguments to the continuation function.
void replaceCoroSuspends ()
void replaceCoroEnds ()
void replaceSwiftErrorOps ()
void salvageDebugInfo ()
void handleFinalSuspend ()
Additional Inherited Members
Public Member Functions inherited from llvm::coro::BaseCloner
BaseCloner (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, CloneKind FKind, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
virtual ~BaseCloner ()
Function * getFunction () const
Protected Attributes inherited from llvm::coro::BaseCloner
Function & OrigF
const Twine & Suffix
coro::Shape & Shape
CloneKind FKind
IRBuilder Builder
TargetTransformInfo & TTI
const MetadataSetTy & CommonDebugInfo
ValueToValueMapTy VMap
Function * NewF = nullptr
Value * NewFramePtr = nullptr
AnyCoroSuspendInst * ActiveSuspend = nullptr
The active suspend instruction; meaningful only for continuation and async ABIs.
Detailed Description
Definition at line 135 of file CoroCloner.h.
Constructor & Destructor Documentation
SwitchCloner()
llvm::coro::SwitchCloner::SwitchCloner (Function & OrigF, const Twine & Suffix, coro::Shape & Shape, CloneKind FKind, TargetTransformInfo & TTI, const MetadataSetTy & CommonDebugInfo) inline protected
Create a cloner for a switch lowering.
Definition at line 138 of file CoroCloner.h.
References llvm::coro::BaseCloner::BaseCloner(), llvm::coro::BaseCloner::CommonDebugInfo, llvm::coro::BaseCloner::FKind, llvm::coro::BaseCloner::OrigF, llvm::coro::BaseCloner::Shape, llvm::coro::BaseCloner::Suffix, and llvm::coro::BaseCloner::TTI.
Referenced by createClone().
Member Function Documentation
create()
void coro::SwitchCloner::create () override protected virtual
Clone the body of the original function into a resume function of some sort.
FIXME: Is it really good to add the NoAlias attribute?
Reimplemented from llvm::coro::BaseCloner.
Definition at line 1127 of file CoroSplit.cpp.
References llvm::coro::BaseCloner::ActiveSuspend, llvm::cast(), llvm::coro::BaseCloner::create(), createCloneDeclaration(), llvm::coro::BaseCloner::FKind, llvm::coro::BaseCloner::NewF, llvm::coro::BaseCloner::OrigF, llvm::coro::replaceCoroFree(), llvm::coro::BaseCloner::Shape, llvm::coro::BaseCloner::Suffix, llvm::coro::SwitchCleanup, and llvm::coro::BaseCloner::VMap.
Referenced by createClone().
createClone()
static Function * llvm::coro::SwitchCloner::createClone (Function & OrigF, const Twine & Suffix, coro::Shape & Shape, CloneKind FKind, TargetTransformInfo & TTI, const MetadataSetTy & CommonDebugInfo) inline static
Create a clone for a switch lowering.
Definition at line 147 of file CoroCloner.h.
References assert(), llvm::coro::BaseCloner::CommonDebugInfo, create(), llvm::coro::BaseCloner::FKind, llvm::coro::BaseCloner::getFunction(), llvm::coro::BaseCloner::OrigF, llvm::coro::BaseCloner::Shape, llvm::coro::BaseCloner::Suffix, llvm::coro::Switch, SwitchCloner(), and llvm::coro::BaseCloner::TTI.
The documentation for this class was generated from the following files:
lib/Transforms/Coroutines/CoroCloner.h
lib/Transforms/Coroutines/CoroSplit.cpp