LLVM: llvm::orc::SimpleRemoteEPC Class Reference
llvm::orc::SimpleRemoteEPC Class Reference
#include "llvm/ExecutionEngine/Orc/SimpleRemoteEPC.h"
Classes
struct Setup
A setup object containing callbacks to construct a memory manager and memory access object.
Public Member Functions
SimpleRemoteEPC (const SimpleRemoteEPC &)=delete
SimpleRemoteEPC & operator= (const SimpleRemoteEPC &)=delete
SimpleRemoteEPC (SimpleRemoteEPC &&)=delete
SimpleRemoteEPC & operator= (SimpleRemoteEPC &&)=delete
~SimpleRemoteEPC ()
Expected< int32_t > runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
Expected< int32_t > runAsVoidFunction (ExecutorAddr VoidFnAddr) override
Run function with a int (*)(void) signature.
Expected< int32_t > runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override
Run function with a int (*)(int) signature.
void callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override
Run a wrapper function in the executor.
Error disconnect () override
Disconnect from the target process.
Expected< HandleMessageAction > handleMessage (SimpleRemoteEPCOpcode OpC, uint64_t SeqNo, ExecutorAddr TagAddr, SimpleRemoteEPCArgBytesVector ArgBytes) override
Handle receipt of a message.
void handleDisconnect (Error Err) override
Handle a disconnection from the underlying transport.
Public Member Functions inherited from llvm::orc::ExecutorProcessControl
ExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< TaskDispatcher > D)
virtual ~ExecutorProcessControl ()
ExecutionSession & getExecutionSession ()
Return the ExecutionSession associated with this instance.
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
TaskDispatcher & getDispatcher ()
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
const JITDispatchInfo & getJITDispatchInfo () const
Get the JIT dispatch function and context address for the executor.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
DylibManager & getDylibMgr () const
Return the DylibManager for the target process.
const StringMap< std::vector< char > > & getBootstrapMap () const
Returns the bootstrap map.
template<typename T, typename SPSTagT>
Error getBootstrapMapValue (StringRef Key, std::optional< T > &Val) const
Look up and SPS-deserialize a bootstrap map value.
const StringMap< ExecutorAddr > & getBootstrapSymbolsMap () const
Returns the bootstrap symbol map.
Error getBootstrapSymbols (ArrayRef< std::pair< ExecutorAddr &, StringRef > > Pairs) const
For each (ExecutorAddr&, StringRef) pair, looks up the string in the bootstrap symbols map and writes its address to the ExecutorAddr if found.
template<typename RunPolicyT, typename FnT>
void callWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor using the given Runner to dispatch OnComplete when the result is ready.
template<typename FnT>
void callWrapperAsync (ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
shared::WrapperFunctionResult callWrapper (ExecutorAddr WrapperFnAddr, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
template<typename SPSSignature, typename RunPolicyT, typename SendResultT, typename... ArgTs>
void callSPSWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature, typename SendResultT, typename... ArgTs>
void callSPSWrapperAsync (ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature, typename... WrapperCallArgTs>
Error callSPSWrapper (ExecutorAddr WrapperFnAddr, WrapperCallArgTs &&...WrapperCallArgs)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
Public Member Functions inherited from llvm::orc::SimpleRemoteEPCTransportClient
virtual ~SimpleRemoteEPCTransportClient ()
Static Public Member Functions
template<typename TransportT, typename... TransportTCtorArgTs>
static Expected< std::unique_ptr< SimpleRemoteEPC > > Create (std::unique_ptr< TaskDispatcher > D, Setup S, TransportTCtorArgTs &&...TransportTCtorArgs)
Create a SimpleRemoteEPC using the given transport type and args.
Additional Inherited Members
Public Types inherited from llvm::orc::SimpleRemoteEPCTransportClient
enum HandleMessageAction { ContinueSession , EndSession }
Protected Attributes inherited from llvm::orc::ExecutorProcessControl
std::shared_ptr< SymbolStringPool > SSP
std::unique_ptr< TaskDispatcher > D
ExecutionSession * ES = nullptr
Triple TargetTriple
unsigned PageSize = 0
JITDispatchInfo JDI
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
DylibManager * DylibMgr = nullptr
StringMap< std::vector< char > > BootstrapMap
StringMap< ExecutorAddr > BootstrapSymbols
Detailed Description
Definition at line 31 of file SimpleRemoteEPC.h.
Constructor & Destructor Documentation
SimpleRemoteEPC() [1/2]
llvm::orc::SimpleRemoteEPC::SimpleRemoteEPC (const SimpleRemoteEPC &) delete
References SimpleRemoteEPC().
Referenced by Create(), operator=(), operator=(), SimpleRemoteEPC(), and SimpleRemoteEPC().
SimpleRemoteEPC() [2/2]
llvm::orc::SimpleRemoteEPC::SimpleRemoteEPC (SimpleRemoteEPC &&) delete
References SimpleRemoteEPC().
~SimpleRemoteEPC()
llvm::orc::SimpleRemoteEPC::~SimpleRemoteEPC ()
Definition at line 19 of file SimpleRemoteEPC.cpp.
References assert().
Member Function Documentation
callWrapperAsync()
void llvm::orc::SimpleRemoteEPC::callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override virtual
Run a wrapper function in the executor.
The given WFRHandler will be called on the result when it is returned.
The wrapper function should be callable as:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implements llvm::orc::ExecutorProcessControl.
Definition at line 90 of file SimpleRemoteEPC.cpp.
References assert(), llvm::orc::CallWrapper, callWrapperAsync(), llvm::orc::shared::WrapperFunctionResult::createOutOfBandError(), llvm::orc::ExecutorProcessControl::getExecutionSession(), H, and I.
Referenced by callWrapperAsync().
Create()
template<typename TransportT, typename... TransportTCtorArgTs> static Expected< std::unique_ptr< SimpleRemoteEPC > > llvm::orc::SimpleRemoteEPC::Create (std::unique_ptr< TaskDispatcher > D, Setup S, TransportTCtorArgTs &&... TransportTCtorArgs) inline static
Create a SimpleRemoteEPC using the given transport type and args.
Definition at line 52 of file SimpleRemoteEPC.h.
References llvm::orc::ExecutorProcessControl::D, llvm::joinErrors(), and SimpleRemoteEPC().
disconnect()
Error llvm::orc::SimpleRemoteEPC::disconnect () override virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 126 of file SimpleRemoteEPC.cpp.
References llvm::orc::ExecutorProcessControl::D, and disconnect().
Referenced by disconnect().
handleDisconnect()
void llvm::orc::SimpleRemoteEPC::handleDisconnect (Error Err) override virtual
Handle a disconnection from the underlying transport.
No further messages should be sent to handleMessage after this is called. Err may contain an Error value indicating unexpected disconnection. This allows clients to log such errors, but no attempt should be made at recovery (which should be handled inside the transport class, if it is supported at all).
Implements llvm::orc::SimpleRemoteEPCTransportClient.
Definition at line 191 of file SimpleRemoteEPC.cpp.
References llvm::orc::shared::WrapperFunctionResult::createOutOfBandError(), llvm::dbgs(), handleDisconnect(), llvm::joinErrors(), LLVM_DEBUG, and std::swap().
Referenced by handleDisconnect().
handleMessage()
Expected< SimpleRemoteEPCTransportClient::HandleMessageAction > llvm::orc::SimpleRemoteEPC::handleMessage (SimpleRemoteEPCOpcode OpC, uint64_t SeqNo, ExecutorAddr TagAddr, SimpleRemoteEPCArgBytesVector ArgBytes) override virtual
Handle receipt of a message.
Returns an Error if the message cannot be handled, 'EndSession' if the client will not accept any further messages, and 'ContinueSession' otherwise.
Implements llvm::orc::SimpleRemoteEPCTransportClient.
Definition at line 135 of file SimpleRemoteEPC.cpp.
References assert(), llvm::orc::CallWrapper, llvm::orc::SimpleRemoteEPCTransportClient::ContinueSession, llvm::dbgs(), llvm::orc::SimpleRemoteEPCTransportClient::EndSession, llvm::formatv(), handleMessage(), llvm::orc::Hangup, llvm::inconvertibleErrorCode(), llvm::orc::LastOpC, LLVM_DEBUG, llvm::make_error(), llvm::orc::Result, llvm::orc::Setup, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by handleMessage().
operator=() [1/2]
SimpleRemoteEPC & llvm::orc::SimpleRemoteEPC::operator= (const SimpleRemoteEPC &) delete
References SimpleRemoteEPC().
operator=() [2/2]
SimpleRemoteEPC & llvm::orc::SimpleRemoteEPC::operator= (SimpleRemoteEPC &&) delete
References llvm::orc::ExecutorProcessControl::D, llvm::orc::ExecutorProcessControl::DylibMgr, llvm::orc::ExecutorProcessControl::ExecutorProcessControl(), llvm::move(), SimpleRemoteEPC(), and llvm::orc::ExecutorProcessControl::SSP.
runAsIntFunction()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override virtual
Run function with a int (*)(int) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 81 of file SimpleRemoteEPC.cpp.
References llvm::orc::ExecutorProcessControl::callSPSWrapper(), llvm::orc::Result, and runAsIntFunction().
Referenced by runAsIntFunction().
runAsMain()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override virtual
Run function with a main-like signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 64 of file SimpleRemoteEPC.cpp.
References llvm::orc::ExecutorProcessControl::callSPSWrapper(), llvm::orc::Result, and runAsMain().
Referenced by runAsMain().
runAsVoidFunction()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsVoidFunction (ExecutorAddr VoidFnAddr) override virtual
Run function with a int (*)(void) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 73 of file SimpleRemoteEPC.cpp.
References llvm::orc::ExecutorProcessControl::callSPSWrapper(), llvm::orc::Result, and runAsVoidFunction().
Referenced by runAsVoidFunction().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SimpleRemoteEPC.h
lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp