LLVM: llvm::sandboxir::MemDGNode Class Reference
llvm::sandboxir::MemDGNode Class Reference final
A DependencyGraph Node for instructions that may read/write memory, or have some ordering constraints, like with stacksave/stackrestore and alloca/inalloca.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Public Member Functions
MemDGNode (Instruction *I)
iterator preds_begin (DependencyGraph &DAG) override
iterator preds_end (DependencyGraph &DAG) override
MemDGNode * getPrevNode () const
\Returns the previous Mem DGNode in instruction order.
MemDGNode * getNextNode () const
\Returns the next Mem DGNode in instruction order.
void addMemPred (MemDGNode *PredN)
Adds the mem dependency edge PredN->this.
bool hasMemPred (DGNode *N) const
\Returns true if there is a memory dependency N->this.
iterator_range< DenseSet< MemDGNode * >::const_iterator > memPreds () const
\Returns all memory dependency predecessors. Used by tests.
virtual void print (raw_ostream &OS, bool PrintDeps=true) const override
Public Member Functions inherited from llvm::sandboxir::DGNode
DGNode (Instruction *I)
DGNode (const DGNode &Other)=delete
virtual ~DGNode ()
unsigned getNumUnscheduledSuccs () const
\Returns the number of unscheduled successors.
void decrUnscheduledSuccs ()
bool ready () const
\Returns true if all dependent successors have been scheduled.
bool scheduled () const
\Returns true if this node has been scheduled.
void setScheduled (bool NewVal)
SchedBundle * getSchedBundle () const
\Returns the scheduling bundle that this node belongs to, or nullptr.
bool comesBefore (const DGNode *Other)
\Returns true if this is before Other in program order.
iterator preds_begin (DependencyGraph &DAG) const
iterator preds_end (DependencyGraph &DAG) const
iterator_range< iterator > preds (DependencyGraph &DAG) const
\Returns a range of DAG predecessors nodes.
Instruction * getInstruction () const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const DGNode *Other)
Static Public Member Functions inherited from llvm::sandboxir::DGNode
static bool isStackSaveOrRestoreIntrinsic (Instruction *I)
static bool isMemIntrinsic (IntrinsicInst *I)
\Returns true if intrinsic I touches memory.
static bool isMemDepCandidate (Instruction *I)
We consider I as a Memory Dependency Candidate instruction if it reads/write memory or if it has side-effects.
static bool isFenceLike (Instruction *I)
\Returns true if I is fence like. It excludes non-mem intrinsics.
static bool isMemDepNodeCandidate (Instruction *I)
\Returns true if I is a memory dependency candidate instruction.
Friends
class PredIterator
class DependencyGraph
Additional Inherited Members
Public Types inherited from llvm::sandboxir::DGNode
using iterator = PredIterator
Protected Member Functions inherited from llvm::sandboxir::DGNode
void setSchedBundle (SchedBundle &SB)
void clearSchedBundle ()
DGNode (Instruction *I, DGNodeID ID)
Protected Attributes inherited from llvm::sandboxir::DGNode
Instruction * I
DGNodeID SubclassID
For isa/dyn_cast etc.
unsigned UnscheduledSuccs = 0
The number of unscheduled successors.
bool Scheduled = false
This is true if this node has been scheduled.
SchedBundle * SB = nullptr
The scheduler bundle that this node belongs to.
Detailed Description
A DependencyGraph Node for instructions that may read/write memory, or have some ordering constraints, like with stacksave/stackrestore and alloca/inalloca.
Definition at line 213 of file DependencyGraph.h.
Constructor & Destructor Documentation
MemDGNode()
llvm::sandboxir::MemDGNode::MemDGNode (Instruction * I) inline
Definition at line 244 of file DependencyGraph.h.
References assert(), llvm::sandboxir::DGNode::DGNode(), llvm::sandboxir::DGNode::I, llvm::sandboxir::DGNode::isMemDepNodeCandidate(), and MemDGNode().
Referenced by addMemPred(), getNextNode(), getPrevNode(), MemDGNode(), and PredIterator.
Member Function Documentation
addMemPred()
void llvm::sandboxir::MemDGNode::addMemPred (MemDGNode * PredN) inline
Adds the mem dependency edge PredN->this.
This also increments the UnscheduledSuccs counter of the predecessor if this node has not been scheduled.
Definition at line 265 of file DependencyGraph.h.
References assert(), MemDGNode(), llvm::sandboxir::DGNode::Scheduled, and llvm::sandboxir::DGNode::UnscheduledSuccs.
classof()
static bool llvm::sandboxir::MemDGNode::classof (const DGNode * Other) inline static
Definition at line 247 of file DependencyGraph.h.
References llvm::sandboxir::DGNode::DGNode(), llvm::sandboxir::MemDGNode, and llvm::Other.
getNextNode()
MemDGNode * llvm::sandboxir::MemDGNode::getNextNode () const inline
\Returns the next Mem DGNode in instruction order.
Definition at line 261 of file DependencyGraph.h.
References MemDGNode().
getPrevNode()
MemDGNode * llvm::sandboxir::MemDGNode::getPrevNode () const inline
\Returns the previous Mem DGNode in instruction order.
Definition at line 259 of file DependencyGraph.h.
References MemDGNode().
hasMemPred()
bool llvm::sandboxir::MemDGNode::hasMemPred (DGNode * N) const inline
\Returns true if there is a memory dependency N->this.
Definition at line 273 of file DependencyGraph.h.
References llvm::sandboxir::DGNode::DGNode(), llvm::dyn_cast(), and N.
memPreds()
iterator_range< DenseSet< MemDGNode * >::const_iterator > llvm::sandboxir::MemDGNode::memPreds () const inline
\Returns all memory dependency predecessors. Used by tests.
Definition at line 279 of file DependencyGraph.h.
References llvm::make_range().
preds_begin()
iterator llvm::sandboxir::MemDGNode::preds_begin (DependencyGraph & DAG) inline override virtual
Reimplemented from llvm::sandboxir::DGNode.
Definition at line 250 of file DependencyGraph.h.
References DependencyGraph, llvm::sandboxir::DGNode::I, PredIterator, and llvm::sandboxir::skipNonInstr().
preds_end()
iterator llvm::sandboxir::MemDGNode::preds_end (DependencyGraph & DAG) inline override virtual
Reimplemented from llvm::sandboxir::DGNode.
Definition at line 255 of file DependencyGraph.h.
References DependencyGraph, llvm::sandboxir::DGNode::I, and PredIterator.
print()
void llvm::sandboxir::MemDGNode::print (raw_ostream & OS, bool PrintDeps = true) const override virtual
Reimplemented from llvm::sandboxir::DGNode.
Definition at line 73 of file DependencyGraph.cpp.
References llvm::raw_ostream::indent(), and llvm::sandboxir::DGNode::print().
Friends And Related Symbol Documentation
DependencyGraph
friend class DependencyGraph friend
Definition at line 233 of file DependencyGraph.h.
References DependencyGraph.
Referenced by DependencyGraph, preds_begin(), and preds_end().
PredIterator
friend class PredIterator friend
Definition at line 218 of file DependencyGraph.h.
References MemDGNode(), N, and PredIterator.
Referenced by PredIterator, preds_begin(), and preds_end().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp