LLVM: llvm::sandboxir::ConstantFP Class Reference
llvm::sandboxir::ConstantFP Class Reference final
#include "llvm/SandboxIR/Constant.h"
Public Member Functions
const APFloat & getValueAPF () const
const APFloat & getValue () const
bool isZero () const
Return true if the value is positive or negative zero.
bool isNegative () const
Return true if the sign bit is set.
bool isInfinity () const
Return true if the value is infinity.
bool isNaN () const
Return true if the value is a NaN.
bool isExactlyValue (const APFloat &V) const
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
bool isExactlyValue (double V) const
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
Type * getType () const
Context & getContext () const
void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static Constant * get (Type *Ty, double V)
This returns a ConstantFP, or a vector containing a splat of a ConstantFP, for the specified value in the specified type.
static Constant * get (Type *Ty, const APFloat &V)
If Ty is a vector type, return a Constant with a splat of the given value.
static Constant * get (Type *Ty, StringRef Str)
static ConstantFP * get (const APFloat &V, Context &Ctx)
static Constant * getNaN (Type *Ty, bool Negative=false, uint64_t Payload=0)
static Constant * getQNaN (Type *Ty, bool Negative=false, APInt *Payload=nullptr)
static Constant * getSNaN (Type *Ty, bool Negative=false, APInt *Payload=nullptr)
static Constant * getZero (Type *Ty, bool Negative=false)
static Constant * getNegativeZero (Type *Ty)
static Constant * getInfinity (Type *Ty, bool Negative=false)
static bool isValueValidForType (Type *Ty, const APFloat &V)
Return true if Ty is big enough to represent V.
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class Context
Additional Inherited Members
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned { DEF_VALUE , DEF_USER , DEF_CONST , DEF_INSTR }
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const override
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 257 of file Constant.h.
Member Function Documentation
classof()
static bool llvm::sandboxir::ConstantFP::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 325 of file Constant.h.
References llvm::sandboxir::Value::getSubclassID().
dumpOS()
void llvm::sandboxir::ConstantFP::dumpOS (raw_ostream & OS) const inline override virtual
Reimplemented from llvm::sandboxir::Constant.
Definition at line 337 of file Constant.h.
References llvm::sandboxir::Value::dumpCommonPrefix(), and llvm::sandboxir::Value::dumpCommonSuffix().
get() [1/4]
ConstantFP * llvm::sandboxir::ConstantFP::get (const APFloat & V, Context & Ctx) static
Definition at line 106 of file Constant.cpp.
References llvm::cast(), Context, and llvm::sandboxir::Value::Ctx.
get() [2/4]
Constant * llvm::sandboxir::ConstantFP::get (Type * Ty, const APFloat & V) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantFP for the given value.
Definition at line 96 of file Constant.cpp.
References llvm::sandboxir::Constant::Constant().
get() [3/4]
Constant * llvm::sandboxir::ConstantFP::get (Type * Ty, double V) static
This returns a ConstantFP, or a vector containing a splat of a ConstantFP, for the specified value in the specified type.
This should only be used for simple constant values like 2.0/1.0 etc, that are known-valid both as host double and as the target format.
Definition at line 91 of file Constant.cpp.
References llvm::sandboxir::Constant::Constant().
get() [4/4]
Constant * llvm::sandboxir::ConstantFP::get (Type * Ty, StringRef Str) static
Definition at line 101 of file Constant.cpp.
References llvm::sandboxir::Constant::Constant().
getInfinity()
Constant * llvm::sandboxir::ConstantFP::getInfinity (Type * Ty, bool Negative = false) static
Definition at line 131 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getInfinity().
getNaN()
Constant * llvm::sandboxir::ConstantFP::getNaN (Type * Ty, bool Negative = false, uint64_t Payload = 0) static
Definition at line 111 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getNaN().
getNegativeZero()
Constant * llvm::sandboxir::ConstantFP::getNegativeZero (Type * Ty) static
Definition at line 127 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getNegativeZero().
getQNaN()
Constant * llvm::sandboxir::ConstantFP::getQNaN (Type * Ty, bool Negative = false, APInt * Payload = nullptr) static
Definition at line 115 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getQNaN().
getSNaN()
Constant * llvm::sandboxir::ConstantFP::getSNaN (Type * Ty, bool Negative = false, APInt * Payload = nullptr) static
Definition at line 119 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getSNaN().
getUseOperandNo()
unsigned llvm::sandboxir::ConstantFP::getUseOperandNo (const Use & Use) const inline final virtual
\Returns the operand index of Use.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 330 of file Constant.h.
References llvm_unreachable.
getValue()
const APFloat & llvm::sandboxir::ConstantFP::getValue () const inline
Definition at line 294 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getValueAPF()
const APFloat & llvm::sandboxir::ConstantFP::getValueAPF () const inline
Definition at line 291 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getZero()
Constant * llvm::sandboxir::ConstantFP::getZero (Type * Ty, bool Negative = false) static
Definition at line 123 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Constant::Constant(), and llvm::ConstantFP::getZero().
isExactlyValue() [1/2]
bool llvm::sandboxir::ConstantFP::isExactlyValue (const APFloat & V) const inline
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
As such, this method can be used to do an exact bit-for-bit comparison of two floating point values. The version with a double operand is retained because it's so convenient to write isExactlyValue(2.0), but please use it only for simple constants.
Definition at line 316 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isExactlyValue() [2/2]
bool llvm::sandboxir::ConstantFP::isExactlyValue (double V) const inline
Definition at line 320 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isInfinity()
bool llvm::sandboxir::ConstantFP::isInfinity () const inline
Return true if the value is infinity.
Definition at line 305 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isNaN()
bool llvm::sandboxir::ConstantFP::isNaN () const inline
Return true if the value is a NaN.
Definition at line 308 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isNegative()
bool llvm::sandboxir::ConstantFP::isNegative () const inline
Return true if the sign bit is set.
Definition at line 302 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isValueValidForType()
bool llvm::sandboxir::ConstantFP::isValueValidForType (Type * Ty, const APFloat & V) static
Return true if Ty is big enough to represent V.
Definition at line 135 of file Constant.cpp.
References llvm::ConstantFP::isValueValidForType().
isZero()
bool llvm::sandboxir::ConstantFP::isZero () const inline
Return true if the value is positive or negative zero.
Definition at line 299 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
verify()
void llvm::sandboxir::ConstantFP::verify () const inline override virtual
Should crash if there is something wrong with the instruction.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 334 of file Constant.h.
References assert(), llvm::isa(), and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 260 of file Constant.h.
References llvm::sandboxir::Constant::Constant(), Context, and llvm::sandboxir::Value::Ctx.
Referenced by Context, and get().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Constant.h
lib/SandboxIR/Constant.cpp