LLVM: llvm::MCPseudoProbeInlineTree Class Reference
llvm::MCPseudoProbeInlineTree Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCPseudoProbeInlineTree ()=default
MCPseudoProbeInlineTree (uint64_t Guid)
MCPseudoProbeInlineTree (const InlineSite &Site)
void addPseudoProbe (const MCPseudoProbe &Probe, const MCPseudoProbeInlineStack &InlineStack)
void emit (MCObjectStreamer *MCOS, const MCPseudoProbe *&LastProbe)
Public Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >
bool isRoot () const
std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > & getChildren ()
const std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > & getChildren () const
const std::vector< MCPseudoProbe > & getProbes () const
MCPseudoProbeInlineTree * getOrAddNode (const InlineSite &Site)
Additional Inherited Members
Public Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >
uint64_t Guid
MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > > * Parent
Protected Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >
MCPseudoProbeInlineTreeBase ()
Protected Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >
std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > Children
std::vector< MCPseudoProbe > Probes
Detailed Description
Definition at line 291 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCPseudoProbeInlineTree() [1/3]
llvm::MCPseudoProbeInlineTree::MCPseudoProbeInlineTree () default
MCPseudoProbeInlineTree() [2/3]
llvm::MCPseudoProbeInlineTree::MCPseudoProbeInlineTree (uint64_t Guid) inline
Definition at line 299 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Guid.
MCPseudoProbeInlineTree() [3/3]
llvm::MCPseudoProbeInlineTree::MCPseudoProbeInlineTree (const InlineSite & Site) inline
Definition at line 300 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Guid.
Member Function Documentation
addPseudoProbe()
void MCPseudoProbeInlineTree::addPseudoProbe (const MCPseudoProbe & Probe, const MCPseudoProbeInlineStack & InlineStack)
Definition at line 103 of file MCPseudoProbe.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::MCPseudoProbe::getGuid(), llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::getOrAddNode(), and llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::isRoot().
emit()
void MCPseudoProbeInlineTree::emit (MCObjectStreamer * MCOS, const MCPseudoProbe *& LastProbe)
Definition at line 146 of file MCPseudoProbe.cpp.
References assert(), llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Children, llvm::dbgs(), llvm::MCPseudoProbeTable::DdgPrintIndent, llvm::MCPseudoProbe::emit(), llvm::MCStreamer::emitInt64(), llvm::MCStreamer::emitULEB128IntValue(), llvm::MCPseudoProbeBase::getAttributes(), llvm::MCPseudoProbe::getGuid(), llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Guid, llvm::raw_ostream::indent(), llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::isRoot(), llvm::isSentinelProbe(), LLVM_DEBUG, llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Parent, llvm::MCPseudoProbeInlineTreeBase< std::vector< MCPseudoProbe >, MCPseudoProbeInlineTree, std::unordered_map< InlineSite, std::unique_ptr< MCPseudoProbeInlineTree >, InlineSiteHash > >::Probes, and llvm::sort().
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp