LLVM: llvm::DXILBindingMap Class Reference
llvm::DXILBindingMap Class Reference
#include "llvm/Analysis/DXILResource.h"
Public Types
using iterator = SmallVector<dxil::ResourceBindingInfo>::iterator
using const_iterator = SmallVector<dxil::ResourceBindingInfo>::const_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool empty () const
iterator find (const CallInst *Key)
const_iterator find (const CallInst *Key) const
iterator srv_begin ()
const_iterator srv_begin () const
iterator srv_end ()
const_iterator srv_end () const
iterator_range< iterator > srvs ()
iterator_range< const_iterator > srvs () const
iterator uav_begin ()
const_iterator uav_begin () const
iterator uav_end ()
const_iterator uav_end () const
iterator_range< iterator > uavs ()
iterator_range< const_iterator > uavs () const
iterator cbuffer_begin ()
const_iterator cbuffer_begin () const
iterator cbuffer_end ()
const_iterator cbuffer_end () const
iterator_range< iterator > cbuffers ()
iterator_range< const_iterator > cbuffers () const
iterator sampler_begin ()
const_iterator sampler_begin () const
iterator sampler_end ()
const_iterator sampler_end () const
iterator_range< iterator > samplers ()
iterator_range< const_iterator > samplers () const
void print (raw_ostream &OS, DXILResourceTypeMap &DRTM, const DataLayout &DL) const
Friends
class DXILResourceBindingAnalysis
class DXILResourceBindingWrapperPass
Detailed Description
Definition at line 423 of file DXILResource.h.
Member Typedef Documentation
const_iterator
using llvm::DXILBindingMap::const_iterator = SmallVector<dxil::ResourceBindingInfo>::const_iterator
Definition at line 435 of file DXILResource.h.
iterator
using llvm::DXILBindingMap::iterator = SmallVector<dxil::ResourceBindingInfo>::iterator
Definition at line 434 of file DXILResource.h.
Member Function Documentation
begin() [1/2]
iterator llvm::DXILBindingMap::begin () inline
Definition at line 437 of file DXILResource.h.
Referenced by cbuffer_begin(), cbuffer_begin(), cbuffer_end(), cbuffer_end(), sampler_begin(), sampler_begin(), srv_begin(), srv_begin(), srv_end(), srv_end(), uav_begin(), uav_begin(), uav_end(), and uav_end().
begin() [2/2]
const_iterator llvm::DXILBindingMap::begin () const inline
Definition at line 438 of file DXILResource.h.
cbuffer_begin() [1/2]
iterator llvm::DXILBindingMap::cbuffer_begin () inline
Definition at line 472 of file DXILResource.h.
References begin().
Referenced by cbuffers(), and cbuffers().
cbuffer_begin() [2/2]
const_iterator llvm::DXILBindingMap::cbuffer_begin () const inline
Definition at line 473 of file DXILResource.h.
References begin().
cbuffer_end() [1/2]
iterator llvm::DXILBindingMap::cbuffer_end () inline
Definition at line 474 of file DXILResource.h.
References begin().
Referenced by cbuffers(), and cbuffers().
cbuffer_end() [2/2]
const_iterator llvm::DXILBindingMap::cbuffer_end () const inline
Definition at line 475 of file DXILResource.h.
References begin().
cbuffers() [1/2]
iterator_range< iterator > llvm::DXILBindingMap::cbuffers () inline
Definition at line 476 of file DXILResource.h.
References cbuffer_begin(), cbuffer_end(), and llvm::make_range().
Referenced by emitResourceMetadata().
cbuffers() [2/2]
iterator_range< const_iterator > llvm::DXILBindingMap::cbuffers () const inline
Definition at line 479 of file DXILResource.h.
References cbuffer_begin(), cbuffer_end(), and llvm::make_range().
empty()
bool llvm::DXILBindingMap::empty () const inline
Definition at line 442 of file DXILResource.h.
Referenced by emitResourceMetadata().
end() [1/2]
iterator llvm::DXILBindingMap::end () inline
Definition at line 439 of file DXILResource.h.
Referenced by sampler_end(), and sampler_end().
end() [2/2]
const_iterator llvm::DXILBindingMap::end () const inline
Definition at line 440 of file DXILResource.h.
find() [1/2]
iterator llvm::DXILBindingMap::find (const CallInst * Key) inline
Definition at line 444 of file DXILResource.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
find() [2/2]
const_iterator llvm::DXILBindingMap::find (const CallInst * Key) const inline
Definition at line 449 of file DXILResource.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
print()
void DXILBindingMap::print (raw_ostream & OS, DXILResourceTypeMap & DRTM, const DataLayout & DL) const
Definition at line 757 of file DXILResource.cpp.
References DL, llvm::dxil::ResourceBindingInfo::getHandleTy(), I, and llvm::dxil::ResourceBindingInfo::print().
Referenced by llvm::DXILResourceBindingPrinterPass::run().
sampler_begin() [1/2]
iterator llvm::DXILBindingMap::sampler_begin () inline
Definition at line 483 of file DXILResource.h.
References begin().
Referenced by samplers(), and samplers().
sampler_begin() [2/2]
const_iterator llvm::DXILBindingMap::sampler_begin () const inline
Definition at line 484 of file DXILResource.h.
References begin().
sampler_end() [1/2]
iterator llvm::DXILBindingMap::sampler_end () inline
Definition at line 485 of file DXILResource.h.
References end().
Referenced by samplers(), and samplers().
sampler_end() [2/2]
const_iterator llvm::DXILBindingMap::sampler_end () const inline
Definition at line 486 of file DXILResource.h.
References end().
samplers() [1/2]
iterator_range< iterator > llvm::DXILBindingMap::samplers () inline
Definition at line 487 of file DXILResource.h.
References llvm::make_range(), sampler_begin(), and sampler_end().
Referenced by emitResourceMetadata().
samplers() [2/2]
iterator_range< const_iterator > llvm::DXILBindingMap::samplers () const inline
Definition at line 490 of file DXILResource.h.
References llvm::make_range(), sampler_begin(), and sampler_end().
srv_begin() [1/2]
iterator llvm::DXILBindingMap::srv_begin () inline
Definition at line 454 of file DXILResource.h.
References begin().
Referenced by srvs(), and srvs().
srv_begin() [2/2]
const_iterator llvm::DXILBindingMap::srv_begin () const inline
Definition at line 455 of file DXILResource.h.
References begin().
srv_end() [1/2]
iterator llvm::DXILBindingMap::srv_end () inline
Definition at line 456 of file DXILResource.h.
References begin().
Referenced by srvs(), and srvs().
srv_end() [2/2]
const_iterator llvm::DXILBindingMap::srv_end () const inline
Definition at line 457 of file DXILResource.h.
References begin().
srvs() [1/2]
iterator_range< iterator > llvm::DXILBindingMap::srvs () inline
Definition at line 458 of file DXILResource.h.
References llvm::make_range(), srv_begin(), and srv_end().
Referenced by emitResourceMetadata().
srvs() [2/2]
iterator_range< const_iterator > llvm::DXILBindingMap::srvs () const inline
Definition at line 459 of file DXILResource.h.
References llvm::make_range(), srv_begin(), and srv_end().
uav_begin() [1/2]
iterator llvm::DXILBindingMap::uav_begin () inline
Definition at line 463 of file DXILResource.h.
References begin().
Referenced by uavs(), and uavs().
uav_begin() [2/2]
const_iterator llvm::DXILBindingMap::uav_begin () const inline
Definition at line 464 of file DXILResource.h.
References begin().
uav_end() [1/2]
iterator llvm::DXILBindingMap::uav_end () inline
Definition at line 465 of file DXILResource.h.
References begin().
Referenced by uavs(), and uavs().
uav_end() [2/2]
const_iterator llvm::DXILBindingMap::uav_end () const inline
Definition at line 466 of file DXILResource.h.
References begin().
uavs() [1/2]
iterator_range< iterator > llvm::DXILBindingMap::uavs () inline
Definition at line 467 of file DXILResource.h.
References llvm::make_range(), uav_begin(), and uav_end().
Referenced by emitResourceMetadata().
uavs() [2/2]
iterator_range< const_iterator > llvm::DXILBindingMap::uavs () const inline
Definition at line 468 of file DXILResource.h.
References llvm::make_range(), uav_begin(), and uav_end().
Friends And Related Symbol Documentation
DXILResourceBindingAnalysis
friend class DXILResourceBindingAnalysis friend
Definition at line 497 of file DXILResource.h.
References DXILResourceBindingAnalysis.
Referenced by DXILResourceBindingAnalysis.
DXILResourceBindingWrapperPass
friend class DXILResourceBindingWrapperPass friend
Definition at line 498 of file DXILResource.h.
References DXILResourceBindingWrapperPass.
Referenced by DXILResourceBindingWrapperPass.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp