LLVM: llvm::object::Arm64XRelocRef Class Reference
llvm::object::Arm64XRelocRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
Arm64XRelocRef ()=default
Arm64XRelocRef (const coff_base_reloc_block_header *Header, uint32_t Index=0)
bool operator== (const Arm64XRelocRef &Other) const
void moveNext ()
COFF::Arm64XFixupType getType () const
uint32_t getRVA () const
uint8_t getSize () const
uint64_t getValue () const
Friends
class DynamicRelocRef
Detailed Description
Definition at line 1375 of file COFF.h.
Constructor & Destructor Documentation
Arm64XRelocRef() [1/2]
llvm::object::Arm64XRelocRef::Arm64XRelocRef () default
Referenced by operator==().
Arm64XRelocRef() [2/2]
llvm::object::Arm64XRelocRef::Arm64XRelocRef (const coff_base_reloc_block_header * Header, uint32_t Index = 0) inline
Definition at line 1378 of file COFF.h.
Member Function Documentation
getRVA()
uint32_t llvm::object::Arm64XRelocRef::getRVA () const inline
Definition at line 1387 of file COFF.h.
getSize()
uint8_t Arm64XRelocRef::getSize () const
Definition at line 2107 of file COFFObjectFile.cpp.
References getType(), llvm::COFF::IMAGE_DVRT_ARM64X_FIXUP_TYPE_DELTA, llvm::COFF::IMAGE_DVRT_ARM64X_FIXUP_TYPE_VALUE, llvm::COFF::IMAGE_DVRT_ARM64X_FIXUP_TYPE_ZEROFILL, and llvm_unreachable.
Referenced by getValue().
getType()
COFF::Arm64XFixupType llvm::object::Arm64XRelocRef::getType () const inline
Definition at line 1384 of file COFF.h.
Referenced by getSize(), and getValue().
getValue()
uint64_t Arm64XRelocRef::getValue () const
Definition at line 2118 of file COFFObjectFile.cpp.
References getSize(), getType(), llvm::COFF::IMAGE_DVRT_ARM64X_FIXUP_TYPE_DELTA, llvm::COFF::IMAGE_DVRT_ARM64X_FIXUP_TYPE_VALUE, Ptr, and llvm::Value.
moveNext()
void Arm64XRelocRef::moveNext ()
Definition at line 2094 of file COFFObjectFile.cpp.
operator==()
bool Arm64XRelocRef::operator== (const Arm64XRelocRef & Other) const
Definition at line 2079 of file COFFObjectFile.cpp.
References Arm64XRelocRef(), and llvm::Other.
Friends And Related Symbol Documentation
DynamicRelocRef
friend class DynamicRelocRef friend
Definition at line 1404 of file COFF.h.
References DynamicRelocRef.
Referenced by DynamicRelocRef.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp