LLVM: llvm::RISCVVectorMaskDAGMutation Class Reference
llvm::RISCVVectorMaskDAGMutation Class Reference
Public Member Functions
RISCVVectorMaskDAGMutation (const TargetRegisterInfo *TRI)
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Detailed Description
Definition at line 108 of file RISCVVectorMaskDAGMutation.cpp.
Constructor & Destructor Documentation
RISCVVectorMaskDAGMutation()
llvm::RISCVVectorMaskDAGMutation::RISCVVectorMaskDAGMutation (const TargetRegisterInfo * TRI) inline
Definition at line 113 of file RISCVVectorMaskDAGMutation.cpp.
Member Function Documentation
apply()
void llvm::RISCVVectorMaskDAGMutation::apply (ScheduleDAGInstrs * DAG) inline override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 115 of file RISCVVectorMaskDAGMutation.cpp.
References llvm::ScheduleDAGInstrs::addEdge(), llvm::SDep::Artificial, llvm::SUnit::getInstr(), llvm::RISCVII::getLMul(), llvm::isVectorMaskProducer(), llvm::RISCVII::LMUL_8, MI, and llvm::ScheduleDAG::SUnits.
The documentation for this class was generated from the following file:
lib/Target/RISCV/RISCVVectorMaskDAGMutation.cpp