LLVM: llvm::sandboxir::ScoreBoard Class Reference
llvm::sandboxir::ScoreBoard Class Reference
#include "llvm/SandboxIR/Region.h"
Public Member Functions
ScoreBoard (Region &Rgn, TargetTransformInfo &TTI)
void add (Instruction *I)
Mark I as a newly added instruction to the region.
void remove (Instruction *I)
Mark I as a deleted instruction from the region.
InstructionCost getAfterCost () const
\Returns the cost of the newly added instructions.
InstructionCost getBeforeCost () const
\Returns the cost of the Removed instructions.
void dump (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 24 of file Region.h.
Constructor & Destructor Documentation
ScoreBoard()
llvm::sandboxir::ScoreBoard::ScoreBoard (Region & Rgn, TargetTransformInfo & TTI) inline
Definition at line 39 of file Region.h.
Member Function Documentation
add()
void llvm::sandboxir::ScoreBoard::add (Instruction * I) inline
Mark I as a newly added instruction to the region.
Definition at line 41 of file Region.h.
References I.
dump() [1/2]
void llvm::sandboxir::ScoreBoard::dump () const
Definition at line 32 of file Region.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::ScoreBoard::dump (raw_ostream & OS) const inline
Definition at line 50 of file Region.h.
getAfterCost()
InstructionCost llvm::sandboxir::ScoreBoard::getAfterCost () const inline
\Returns the cost of the newly added instructions.
Definition at line 45 of file Region.h.
getBeforeCost()
InstructionCost llvm::sandboxir::ScoreBoard::getBeforeCost () const inline
\Returns the cost of the Removed instructions.
Definition at line 47 of file Region.h.
remove()
void llvm::sandboxir::ScoreBoard::remove (Instruction * I)
Mark I as a deleted instruction from the region.
Definition at line 20 of file Region.cpp.
References I.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Region.h
lib/SandboxIR/Region.cpp