LLVM: llvm::object::DynamicRelocRef Class Reference
llvm::object::DynamicRelocRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
DynamicRelocRef ()=default
DynamicRelocRef (const void *Header, const COFFObjectFile *Owner)
bool operator== (const DynamicRelocRef &Other) const
void moveNext ()
uint32_t getType () const
void getContents (ArrayRef< uint8_t > &Ref) const
arm64x_reloc_iterator arm64x_reloc_begin () const
arm64x_reloc_iterator arm64x_reloc_end () const
iterator_range< arm64x_reloc_iterator > arm64x_relocs () const
Friends
class COFFObjectFile
Detailed Description
Definition at line 1351 of file COFF.h.
Constructor & Destructor Documentation
DynamicRelocRef() [1/2]
llvm::object::DynamicRelocRef::DynamicRelocRef () default
Referenced by operator==().
DynamicRelocRef() [2/2]
llvm::object::DynamicRelocRef::DynamicRelocRef (const void * Header, const COFFObjectFile * Owner) inline
Definition at line 1354 of file COFF.h.
References COFFObjectFile, and const.
Member Function Documentation
arm64x_reloc_begin()
arm64x_reloc_iterator DynamicRelocRef::arm64x_reloc_begin () const
Definition at line 2057 of file COFFObjectFile.cpp.
References assert(), llvm::ArrayRef< T >::begin(), getContents(), getType(), and llvm::COFF::IMAGE_DYNAMIC_RELOCATION_ARM64X.
Referenced by arm64x_relocs().
arm64x_reloc_end()
arm64x_reloc_iterator DynamicRelocRef::arm64x_reloc_end () const
Definition at line 2066 of file COFFObjectFile.cpp.
References assert(), llvm::ArrayRef< T >::end(), getContents(), getType(), and llvm::COFF::IMAGE_DYNAMIC_RELOCATION_ARM64X.
Referenced by arm64x_relocs().
arm64x_relocs()
iterator_range< arm64x_reloc_iterator > DynamicRelocRef::arm64x_relocs () const
Definition at line 2075 of file COFFObjectFile.cpp.
References arm64x_reloc_begin(), arm64x_reloc_end(), and llvm::make_range().
getContents()
void DynamicRelocRef::getContents (ArrayRef< uint8_t > & Ref) const
Definition at line 1986 of file COFFObjectFile.cpp.
References llvm::ArrayRef(), H, and llvm::Ref.
Referenced by arm64x_reloc_begin(), and arm64x_reloc_end().
getType()
uint32_t DynamicRelocRef::getType () const
Definition at line 1961 of file COFFObjectFile.cpp.
References H, and llvm_unreachable.
Referenced by arm64x_reloc_begin(), and arm64x_reloc_end().
moveNext()
void DynamicRelocRef::moveNext ()
Definition at line 1938 of file COFFObjectFile.cpp.
References H.
operator==()
bool DynamicRelocRef::operator== (const DynamicRelocRef & Other) const
Definition at line 1934 of file COFFObjectFile.cpp.
References DynamicRelocRef(), and llvm::Other.
Friends And Related Symbol Documentation
COFFObjectFile
friend class COFFObjectFile friend
Definition at line 1372 of file COFF.h.
References COFFObjectFile.
Referenced by COFFObjectFile, and DynamicRelocRef().
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp