LLVM: llvm::sandboxir::UseSwap Class Reference
llvm::sandboxir::UseSwap Class Reference
Tracks swapping a Use with another Use.
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
UseSwap (const Use &ThisUse, const Use &OtherUse)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Tracks swapping a Use with another Use.
Definition at line 196 of file Tracker.h.
Constructor & Destructor Documentation
UseSwap()
llvm::sandboxir::UseSwap::UseSwap (const Use & ThisUse, const Use & OtherUse) inline
Definition at line 201 of file Tracker.h.
References assert().
Member Function Documentation
accept()
void llvm::sandboxir::UseSwap::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 206 of file Tracker.h.
dump() [1/2]
void UseSwap::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 87 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::UseSwap::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 208 of file Tracker.h.
revert()
void llvm::sandboxir::UseSwap::revert (Tracker & Tracker) inline final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 205 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp