LLVM: llvm::Attribute Class Reference
llvm::Attribute Class Reference
Functions, function parameters, and return types can have attributes to indicate how they should be treated by optimizations and code generation.
#include "llvm/IR/Attributes.h"
Public Types
enum AttrKind { None , EndAttrKinds , EmptyKey , TombstoneKey }
This enumeration lists the attributes that can be associated with parameters, function results, or the function itself.
Public Member Functions
Attribute ()=default
Attribute getWithNewType (LLVMContext &Context, Type *ReplacementTy)
For a typed attribute, return the equivalent attribute with the type changed to ReplacementTy.
bool isEnumAttribute () const
Return true if the attribute is an Attribute::AttrKind type.
bool isIntAttribute () const
Return true if the attribute is an integer attribute.
bool isStringAttribute () const
Return true if the attribute is a string (target-dependent) attribute.
bool isTypeAttribute () const
Return true if the attribute is a type attribute.
bool isConstantRangeAttribute () const
Return true if the attribute is a ConstantRange attribute.
bool isConstantRangeListAttribute () const
Return true if the attribute is a ConstantRangeList attribute.
bool isValid () const
Return true if the attribute is any kind of attribute.
bool hasAttribute (AttrKind Val) const
Return true if the attribute is present.
bool hasAttribute (StringRef Val) const
Return true if the target-dependent attribute is present.
bool hasKindAsEnum () const
Returns true if the attribute's kind can be represented as an enum (Enum, Integer, Type, ConstantRange, or ConstantRangeList attribute).
Attribute::AttrKind getKindAsEnum () const
Return the attribute's kind as an enum (Attribute::AttrKind).
uint64_t getValueAsInt () const
Return the attribute's value as an integer.
bool getValueAsBool () const
Return the attribute's value as a boolean.
StringRef getKindAsString () const
Return the attribute's kind as a string.
StringRef getValueAsString () const
Return the attribute's value as a string.
Type * getValueAsType () const
Return the attribute's value as a Type.
const ConstantRange & getValueAsConstantRange () const
Return the attribute's value as a ConstantRange.
ArrayRef< ConstantRange > getValueAsConstantRangeList () const
Return the attribute's value as a ConstantRange array.
MaybeAlign getAlignment () const
Returns the alignment field of an attribute as a byte alignment value.
MaybeAlign getStackAlignment () const
Returns the stack alignment field of an attribute as a byte alignment value.
uint64_t getDereferenceableBytes () const
Returns the number of dereferenceable bytes from the dereferenceable attribute.
uint64_t getDereferenceableOrNullBytes () const
Returns the number of dereferenceable_or_null bytes from the dereferenceable_or_null attribute.
std::pair< unsigned, std::optional< unsigned > > getAllocSizeArgs () const
Returns the argument numbers for the allocsize attribute.
unsigned getVScaleRangeMin () const
Returns the minimum value for the vscale_range attribute.
std::optional< unsigned > getVScaleRangeMax () const
Returns the maximum value for the vscale_range attribute or std::nullopt when unknown.
UWTableKind getUWTableKind () const
AllocFnKind getAllocKind () const
MemoryEffects getMemoryEffects () const
Returns memory effects.
CaptureInfo getCaptureInfo () const
Returns information from captures attribute.
FPClassTest getNoFPClass () const
Return the FPClassTest for nofpclass.
const ConstantRange & getRange () const
Returns the value of the range attribute.
ArrayRef< ConstantRange > getInitializes () const
Returns the value of the initializes attribute.
std::string getAsString (bool InAttrGrp=false) const
The Attribute is converted to a string of equivalent mnemonic.
bool hasParentContext (LLVMContext &C) const
Return true if this attribute belongs to the LLVMContext.
bool operator== (Attribute A) const
Equality and non-equality operators.
bool operator!= (Attribute A) const
int cmpKind (Attribute A) const
Used to sort attribute by kind.
bool operator< (Attribute A) const
Less-than operator. Useful for sorting the attributes list.
void Profile (FoldingSetNodeID &ID) const
void * getRawPointer () const
Return a raw pointer that uniquely identifies this attribute.
Static Public Member Functions
static bool isEnumAttrKind (AttrKind Kind)
static bool isIntAttrKind (AttrKind Kind)
static bool isTypeAttrKind (AttrKind Kind)
static bool isConstantRangeAttrKind (AttrKind Kind)
static bool isConstantRangeListAttrKind (AttrKind Kind)
static bool canUseAsFnAttr (AttrKind Kind)
static bool canUseAsParamAttr (AttrKind Kind)
static bool canUseAsRetAttr (AttrKind Kind)
static bool intersectMustPreserve (AttrKind Kind)
static bool intersectWithAnd (AttrKind Kind)
static bool intersectWithMin (AttrKind Kind)
static bool intersectWithCustom (AttrKind Kind)
static Attribute get (LLVMContext &Context, AttrKind Kind, uint64_t Val=0)
Return a uniquified Attribute object.
static Attribute get (LLVMContext &Context, StringRef Kind, StringRef Val=StringRef())
static Attribute get (LLVMContext &Context, AttrKind Kind, Type *Ty)
static Attribute get (LLVMContext &Context, AttrKind Kind, const ConstantRange &CR)
static Attribute get (LLVMContext &Context, AttrKind Kind, ArrayRef< ConstantRange > Val)
static Attribute getWithAlignment (LLVMContext &Context, Align Alignment)
Return a uniquified Attribute object that has the specific alignment set.
static Attribute getWithStackAlignment (LLVMContext &Context, Align Alignment)
static Attribute getWithDereferenceableBytes (LLVMContext &Context, uint64_t Bytes)
static Attribute getWithDereferenceableOrNullBytes (LLVMContext &Context, uint64_t Bytes)
static Attribute getWithAllocSizeArgs (LLVMContext &Context, unsigned ElemSizeArg, const std::optional< unsigned > &NumElemsArg)
static Attribute getWithVScaleRangeArgs (LLVMContext &Context, unsigned MinValue, unsigned MaxValue)
static Attribute getWithByValType (LLVMContext &Context, Type *Ty)
static Attribute getWithStructRetType (LLVMContext &Context, Type *Ty)
static Attribute getWithByRefType (LLVMContext &Context, Type *Ty)
static Attribute getWithPreallocatedType (LLVMContext &Context, Type *Ty)
static Attribute getWithInAllocaType (LLVMContext &Context, Type *Ty)
static Attribute getWithUWTableKind (LLVMContext &Context, UWTableKind Kind)
static Attribute getWithMemoryEffects (LLVMContext &Context, MemoryEffects ME)
static Attribute getWithNoFPClass (LLVMContext &Context, FPClassTest Mask)
static Attribute::AttrKind getAttrKindFromName (StringRef AttrName)
static StringRef getNameFromAttrKind (Attribute::AttrKind AttrKind)
static bool isExistingAttribute (StringRef Name)
Return true if the provided string matches the IR name of an attribute.
static Attribute fromRawPointer (void *RawPtr)
Get an attribute from a raw pointer created by getRawPointer.
Static Public Attributes
static const unsigned NumIntAttrKinds = LastIntAttr - FirstIntAttr + 1
static const unsigned NumTypeAttrKinds = LastTypeAttr - FirstTypeAttr + 1
Detailed Description
Functions, function parameters, and return types can have attributes to indicate how they should be treated by optimizations and code generation.
This class represents one of those attributes. It's light-weight and should be passed around by-value.
Definition at line 67 of file Attributes.h.
Member Enumeration Documentation
AttrKind
enum llvm::Attribute::AttrKind
This enumeration lists the attributes that can be associated with parameters, function results, or the function itself.
Note: The ‘uwtable’ attribute is about the ABI or the user mandating an / entry in the unwind table. The ‘nounwind’ attribute is about an exception passing by the function.
In a theoretical system that uses tables for profiling and SjLj for exceptions, they would be fully independent. In a normal system that uses tables for both, the semantics are:
nil = Needs an entry because an exception might pass by. nounwind = No need for an entry uwtable = Needs an entry because the ABI says so and because an exception might pass by. uwtable + nounwind = Needs an entry because the ABI says so.
Enumerator
None
No attributes have been set.
EndAttrKinds
Sentinel value useful for loops.
EmptyKey
Use as Empty key for DenseMap of AttrKind.
TombstoneKey
Use as Tombstone key for DenseMap of AttrKind.
Definition at line 86 of file Attributes.h.
Constructor & Destructor Documentation
Attribute()
llvm::Attribute::Attribute () default
Referenced by fromRawPointer(), get(), get(), get(), get(), and get().
Member Function Documentation
canUseAsFnAttr()
bool Attribute::canUseAsFnAttr (AttrKind Kind) static
Definition at line 774 of file Attributes.cpp.
References FnAttr, and hasAttributeProperty().
Referenced by forceAttributes(), and llvm::ForceFunctionAttrsPass::run().
canUseAsParamAttr()
bool Attribute::canUseAsParamAttr (AttrKind Kind) static
Definition at line 778 of file Attributes.cpp.
References hasAttributeProperty(), and ParamAttr.
canUseAsRetAttr()
bool Attribute::canUseAsRetAttr (AttrKind Kind) static
Definition at line 782 of file Attributes.cpp.
References hasAttributeProperty(), and RetAttr.
cmpKind()
int Attribute::cmpKind (Attribute A) const
Used to sort attribute by kind.
Definition at line 728 of file Attributes.cpp.
References A().
fromRawPointer()
static Attribute llvm::Attribute::fromRawPointer (void * RawPtr) inline static
Get an attribute from a raw pointer created by getRawPointer.
Definition at line 324 of file Attributes.h.
References Attribute().
Referenced by llvm::unwrap().
get() [1/5]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, ArrayRef< ConstantRange > Val) static
Definition at line 197 of file Attributes.cpp.
References assert(), Attribute(), isConstantRangeListAttrKind(), llvm::ArrayRef< T >::size(), and llvm::ConstantRangeListAttributeImpl::totalSizeToAlloc().
get() [2/5]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, const ConstantRange & CR) static
Definition at line 171 of file Attributes.cpp.
References assert(), Attribute(), llvm::ConstantRange::getLower(), llvm::ConstantRange::getUpper(), isConstantRangeAttrKind(), llvm::ConstantRange::isFullSet(), and llvm::APInt::Profile().
get() [3/5]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, Type * Ty) static
Definition at line 149 of file Attributes.cpp.
References assert(), Attribute(), and isTypeAttrKind().
get() [4/5]
Attribute Attribute::get (LLVMContext & Context, Attribute::AttrKind Kind, uint64_t Val = 0) static
Return a uniquified Attribute object.
Definition at line 95 of file Attributes.cpp.
References assert(), Attribute(), get(), isEnumAttrKind(), and isIntAttrKind().
Referenced by addAllocTypeAttribute(), adjustByValArgAlignment(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), get(), llvm::Attributor::getAttrsFromAssumes(), llvm::IRAttribute< AK, BaseType, AAType >::getDeducedAttributes(), getWithAlignment(), getWithAllocSizeArgs(), getWithByRefType(), getWithByValType(), getWithDereferenceableBytes(), getWithDereferenceableOrNullBytes(), getWithInAllocaType(), getWithMemoryEffects(), getWithNewType(), getWithNoFPClass(), getWithPreallocatedType(), getWithStackAlignment(), getWithStructRetType(), getWithUWTableKind(), getWithVScaleRangeArgs(), llvm::Attributor::hasAttr(), llvm::inferAttribute(), inferInitializes(), llvm::AANoCapture::isImpliedByIR(), llvm::AANoSync::isImpliedByIR(), llvm::AANoUndef::isImpliedByIR(), llvm::AAWillReturn::isImpliedByIR(), LLVMAddTargetDependentFunctionAttr(), LLVMCreateConstantRangeAttribute(), LLVMCreateEnumAttribute(), LLVMCreateStringAttribute(), LLVMCreateTypeAttribute(), LLVMDIBuilderGetOrCreateArray(), LLVMDIBuilderGetOrCreateTypeArray(), processCallSite(), llvm::InlinerPass::run(), setAllocKind(), llvm::codegen::setFunctionAttributes(), llvm::setInlineRemark(), setParamElementType(), setParamReadNone(), setParamReadOnly(), setParamWriteOnly(), and llvm::VFABI::setVectorVariantNames().
get() [5/5]
Attribute Attribute::get (LLVMContext & Context, StringRef Kind, StringRef Val = StringRef()) static
Definition at line 126 of file Attributes.cpp.
References Attribute(), llvm::StringRef::empty(), and llvm::StringAttributeImpl::totalSizeToAlloc().
getAlignment()
MaybeAlign Attribute::getAlignment () const
Returns the alignment field of an attribute as a byte alignment value.
Definition at line 427 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by llvm::AttributeSet::intersectWith().
getAllocKind()
AllocFnKind Attribute::getAllocKind () const
Definition at line 478 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by getAsString().
getAllocSizeArgs()
std::pair< unsigned, std::optional< unsigned > > Attribute::getAllocSizeArgs () const
Returns the argument numbers for the allocsize attribute.
Definition at line 454 of file Attributes.cpp.
References assert(), hasAttribute(), and unpackAllocSizeArgs().
Referenced by getAllocationSize(), and getAsString().
getAsString()
std::string Attribute::getAsString (bool InAttrGrp = false) const
The Attribute is converted to a string of equivalent mnemonic.
This is, presumably, for writing out the mnemonics for the assembly writer.
Definition at line 528 of file Attributes.cpp.
References llvm::Aligned, llvm::Alloc, llvm::ArgMem, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::Default, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::First, llvm::raw_ostream::flush(), llvm::Free, getAllocKind(), getAllocSizeArgs(), llvm::ConstantRange::getBitWidth(), getCaptureInfo(), getInitializes(), getKindAsEnum(), getKindAsString(), llvm::ConstantRange::getLower(), getMemoryEffects(), llvm::MemoryEffectsBase< LocationEnum >::getModRef(), getModRefStr(), getNameFromAttrKind(), getNoFPClass(), llvm::ConstantRange::getUpper(), getUWTableKind(), getValueAsConstantRange(), getValueAsInt(), getValueAsType(), getVScaleRangeMax(), getVScaleRangeMin(), hasAttribute(), llvm::InaccessibleMem, isEnumAttribute(), isStringAttribute(), isTypeAttribute(), llvm::join(), llvm_unreachable, llvm::MemoryEffectsBase< IRMemLocation >::locations(), llvm::NoModRef, llvm::None, llvm::Other, llvm::ConstantRangeList::print(), llvm::Type::print(), llvm::printEscapedString(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Realloc, llvm::StringRef::str(), llvm::Uninitialized, llvm::Unknown, and llvm::Zeroed.
Referenced by LLVMGetAsString().
getAttrKindFromName()
Attribute::AttrKind Attribute::getAttrKindFromName (StringRef AttrName) static
Definition at line 305 of file Attributes.cpp.
References llvm::StringSwitch< T, R >::Default(), and None.
Referenced by llvm::fillMapFromAssume(), forceAttributes(), llvm::getKnowledgeFromBundle(), llvm::hasAttributeInAssume(), LLVMGetEnumAttributeKindForName(), and llvm::ForceFunctionAttrsPass::run().
getCaptureInfo()
CaptureInfo Attribute::getCaptureInfo () const
Returns information from captures attribute.
Definition at line 490 of file Attributes.cpp.
References assert(), llvm::CaptureInfo::createFromIntValue(), and hasAttribute().
Referenced by getAsString(), and llvm::AttributeSet::intersectWith().
getDereferenceableBytes()
uint64_t Attribute::getDereferenceableBytes () const
Returns the number of dereferenceable bytes from the dereferenceable attribute.
Definition at line 439 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by tryToMoveFreeBeforeNullTest().
getDereferenceableOrNullBytes()
uint64_t Attribute::getDereferenceableOrNullBytes () const
Returns the number of dereferenceable_or_null bytes from the dereferenceable_or_null attribute.
Definition at line 446 of file Attributes.cpp.
References assert(), and hasAttribute().
getInitializes()
ArrayRef< ConstantRange > Attribute::getInitializes () const
Returns the value of the initializes attribute.
Definition at line 508 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by getAsString().
getKindAsEnum()
Attribute::AttrKind Attribute::getKindAsEnum () const
Return the attribute's kind as an enum (Attribute::AttrKind).
This requires the attribute be representable as an enum (see: hasKindAsEnum).
Definition at line 364 of file Attributes.cpp.
References assert(), hasKindAsEnum(), and None.
Referenced by addIfNotExistent(), getAsString(), getWithNewType(), llvm::AttributeSet::intersectWith(), LLVMGetEnumAttributeKind(), AttributeComparator::operator()(), and AttributeComparator::operator()().
getKindAsString()
StringRef Attribute::getKindAsString () const
Return the attribute's kind as a string.
This requires the attribute to be a string attribute.
Definition at line 385 of file Attributes.cpp.
References assert(), and isStringAttribute().
Referenced by addIfNotExistent(), getAsString(), LLVMGetStringAttributeKind(), AttributeComparator::operator()(), and AttributeComparator::operator()().
getMemoryEffects()
MemoryEffects Attribute::getMemoryEffects () const
Returns memory effects.
Definition at line 484 of file Attributes.cpp.
References assert(), llvm::MemoryEffectsBase< IRMemLocation >::createFromIntValue(), and hasAttribute().
Referenced by addIfNotExistent(), getAsString(), and llvm::AttributeSet::intersectWith().
getNameFromAttrKind()
StringRef Attribute::getNameFromAttrKind (Attribute::AttrKind AttrKind) static
Definition at line 314 of file Attributes.cpp.
References llvm_unreachable, and None.
Referenced by getAsString(), llvm::hasAttributeInAssume(), and printFunctionArgExts().
getNoFPClass()
FPClassTest Attribute::getNoFPClass () const
Return the FPClassTest for nofpclass.
Definition at line 496 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by getAsString(), and llvm::AttributeSet::intersectWith().
getRange()
const ConstantRange & Attribute::getRange () const
Returns the value of the range attribute.
Definition at line 502 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by addNoUndefAttrs(), AddReturnAttributes(), llvm::CallBase::getRange(), llvm::inferAttribute(), llvm::AttributeSet::intersectWith(), runImpl(), and llvm::typeIncompatible().
getRawPointer()
void * llvm::Attribute::getRawPointer () const inline
Return a raw pointer that uniquely identifies this attribute.
Definition at line 319 of file Attributes.h.
Referenced by llvm::wrap().
getStackAlignment()
MaybeAlign Attribute::getStackAlignment () const
Returns the stack alignment field of an attribute as a byte alignment value.
Definition at line 433 of file Attributes.cpp.
References assert(), and hasAttribute().
getUWTableKind()
UWTableKind Attribute::getUWTableKind () const
Definition at line 472 of file Attributes.cpp.
References assert(), and hasAttribute().
Referenced by getAsString().
getValueAsBool()
bool Attribute::getValueAsBool () const
Return the attribute's value as a boolean.
This requires that the attribute be a string attribute.
Definition at line 378 of file Attributes.cpp.
References assert(), and isStringAttribute().
Referenced by llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::TargetLoweringBase::areJTsAllowed(), atomicIgnoresDenormalModeOrFPModeIsFTZ(), and switchToLookupTable().
getValueAsConstantRange()
const ConstantRange & Attribute::getValueAsConstantRange () const
Return the attribute's value as a ConstantRange.
This requires the attribute to be a ConstantRange attribute.
Definition at line 406 of file Attributes.cpp.
References assert(), and isConstantRangeAttribute().
Referenced by getAsString().
getValueAsConstantRangeList()
ArrayRef< ConstantRange > Attribute::getValueAsConstantRangeList () const
Return the attribute's value as a ConstantRange array.
This requires the attribute to be a ConstantRangeList attribute.
Definition at line 412 of file Attributes.cpp.
References assert(), and isConstantRangeListAttribute().
getValueAsInt()
uint64_t Attribute::getValueAsInt () const
Return the attribute's value as an integer.
This requires that the attribute be an integer attribute.
Definition at line 371 of file Attributes.cpp.
References assert(), and isIntAttribute().
Referenced by adjustByValArgAlignment(), getAllocFnKind(), getAsString(), llvm::AttributeSet::intersectWith(), and isEqualOrWorse().
getValueAsString()
StringRef Attribute::getValueAsString () const
Return the attribute's value as a string.
This requires the attribute to be a string attribute.
Definition at line 392 of file Attributes.cpp.
References assert(), and isStringAttribute().
Referenced by addIfNotExistent(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), collectMetadataInfo(), llvm::getAllocationFamily(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::getStringFnAttrAsInt(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::XtensaTargetMachine::getSubtargetImpl(), llvm::VFABI::getVectorVariantNames(), llvm::PPCTargetLowering::hasInlineStackProbe(), llvm::RISCVTargetLowering::hasInlineStackProbe(), llvm::SystemZTargetLowering::hasInlineStackProbe(), llvm::X86TargetLowering::hasInlineStackProbe(), isThumbFunction(), LLVMGetStringAttributeValue(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerReturn(), llvm::parseStatepointDirectivesFromAttrs(), and llvm::updateMinLegalVectorWidthAttr().
getValueAsType()
Type * Attribute::getValueAsType () const
Return the attribute's value as a Type.
This requires the attribute to be a type attribute.
Definition at line 399 of file Attributes.cpp.
References assert(), and isTypeAttribute().
Referenced by getAsString().
getVScaleRangeMax()
std::optional< unsigned > Attribute::getVScaleRangeMax () const
Returns the maximum value for the vscale_range attribute or std::nullopt when unknown.
Definition at line 466 of file Attributes.cpp.
References assert(), hasAttribute(), and unpackVScaleRangeArgs().
Referenced by getAsString(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::getVScaleRange(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitZExt().
getVScaleRangeMin()
unsigned Attribute::getVScaleRangeMin () const
Returns the minimum value for the vscale_range attribute.
Definition at line 460 of file Attributes.cpp.
References assert(), hasAttribute(), and unpackVScaleRangeArgs().
Referenced by getAsString(), llvm::RISCVTargetMachine::getSubtargetImpl(), getVScaleForTuning(), and llvm::getVScaleRange().
getWithAlignment()
Attribute Attribute::getWithAlignment (LLVMContext & Context, Align Alignment) static
Return a uniquified Attribute object that has the specific alignment set.
Definition at line 234 of file Attributes.cpp.
References A(), assert(), get(), and llvm::Value::MaximumAlignment.
Referenced by llvm::MatrixBuilder::CreateColumnMajorLoad(), llvm::MatrixBuilder::CreateColumnMajorStore(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateThreadLocalAddress(), llvm::VPWidenLoadEVLRecipe::execute(), llvm::VPWidenStoreEVLRecipe::execute(), llvm::ARMTTIImpl::instCombineIntrinsic(), LLVMSetInstrParamAlignment(), LLVMSetParamAlignment(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedStore(), lowerKernelArguments(), llvm::MemIntrinsicBase< Derived >::setDestAlignment(), llvm::MemIntrinsicBase< Derived >::setDestAlignment(), llvm::MemTransferBase< BaseCL >::setSourceAlignment(), llvm::MemTransferBase< BaseCL >::setSourceAlignment(), and llvm::InstCombinerImpl::visitCallInst().
getWithAllocSizeArgs()
Attribute Attribute::getWithAllocSizeArgs (LLVMContext & Context, unsigned ElemSizeArg, const std::optional< unsigned > & NumElemsArg) static
Definition at line 292 of file Attributes.cpp.
References assert(), get(), and packAllocSizeArgs().
Referenced by doPromotion(), and setAllocSize().
getWithByRefType()
Attribute Attribute::getWithByRefType (LLVMContext & Context, Type * Ty) static
Definition at line 264 of file Attributes.cpp.
References get().
getWithByValType()
Attribute Attribute::getWithByValType (LLVMContext & Context, Type * Ty) static
Definition at line 256 of file Attributes.cpp.
References get().
getWithDereferenceableBytes()
Attribute Attribute::getWithDereferenceableBytes (LLVMContext & Context, uint64_t Bytes) static
Definition at line 244 of file Attributes.cpp.
References assert(), and get().
Referenced by annotateDereferenceableBytes(), and lowerKernelArguments().
getWithDereferenceableOrNullBytes()
Attribute Attribute::getWithDereferenceableOrNullBytes (LLVMContext & Context, uint64_t Bytes) static
Definition at line 250 of file Attributes.cpp.
References assert(), and get().
getWithInAllocaType()
Attribute Attribute::getWithInAllocaType (LLVMContext & Context, Type * Ty) static
Definition at line 272 of file Attributes.cpp.
References get().
getWithMemoryEffects()
Attribute Attribute::getWithMemoryEffects (LLVMContext & Context, MemoryEffects ME) static
Definition at line 281 of file Attributes.cpp.
References get(), and llvm::MemoryEffectsBase< LocationEnum >::toIntValue().
Referenced by fixupFPReturnAndCall(), llvm::AMDGPULibFunc::getOrInsertFunction(), runIPSCCP(), and llvm::CallBase::setMemoryEffects().
getWithNewType()
Attribute llvm::Attribute::getWithNewType (LLVMContext & Context, Type * ReplacementTy) inline
For a typed attribute, return the equivalent attribute with the type changed to ReplacementTy.
Definition at line 171 of file Attributes.h.
References assert(), get(), getKindAsEnum(), and isTypeAttribute().
getWithNoFPClass()
Attribute Attribute::getWithNoFPClass (LLVMContext & Context, FPClassTest Mask) static
Definition at line 286 of file Attributes.cpp.
References get().
getWithPreallocatedType()
Attribute Attribute::getWithPreallocatedType (LLVMContext & Context, Type * Ty) static
Definition at line 268 of file Attributes.cpp.
References get().
getWithStackAlignment()
Attribute Attribute::getWithStackAlignment (LLVMContext & Context, Align Alignment) static
Definition at line 239 of file Attributes.cpp.
References A(), assert(), and get().
getWithStructRetType()
Attribute Attribute::getWithStructRetType (LLVMContext & Context, Type * Ty) static
Definition at line 260 of file Attributes.cpp.
References get().
getWithUWTableKind()
Attribute Attribute::getWithUWTableKind (LLVMContext & Context, UWTableKind Kind) static
Definition at line 276 of file Attributes.cpp.
References get().
Referenced by llvm::Function::setUWTableKind().
getWithVScaleRangeArgs()
Attribute Attribute::getWithVScaleRangeArgs (LLVMContext & Context, unsigned MinValue, unsigned MaxValue) static
Definition at line 299 of file Attributes.cpp.
References get(), and packVScaleRangeArgs().
hasAttribute() [1/2]
bool Attribute::hasAttribute (AttrKind Val) const
Return true if the attribute is present.
Definition at line 418 of file Attributes.cpp.
References None.
Referenced by getAlignment(), getAllocKind(), getAllocSizeArgs(), getAsString(), getCaptureInfo(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getInitializes(), getMemoryEffects(), getNoFPClass(), getRange(), getStackAlignment(), getUWTableKind(), getVScaleRangeMax(), getVScaleRangeMin(), and llvm::isStatepointDirectiveAttr().
hasAttribute() [2/2]
bool Attribute::hasAttribute (StringRef Val) const
Return true if the target-dependent attribute is present.
Definition at line 422 of file Attributes.cpp.
References isStringAttribute().
hasKindAsEnum()
bool llvm::Attribute::hasKindAsEnum () const inline
Returns true if the attribute's kind can be represented as an enum (Enum, Integer, Type, ConstantRange, or ConstantRangeList attribute).
Definition at line 218 of file Attributes.h.
References isStringAttribute().
Referenced by getKindAsEnum(), and llvm::AttributeSet::intersectWith().
hasParentContext()
bool Attribute::hasParentContext (LLVMContext & C) const
Return true if this attribute belongs to the LLVMContext.
Definition at line 720 of file Attributes.cpp.
References assert(), llvm::CallingConv::C, and isValid().
intersectMustPreserve()
bool Attribute::intersectMustPreserve (AttrKind Kind) static
Definition at line 797 of file Attributes.cpp.
References hasIntersectProperty(), and IntersectPreserve.
Referenced by llvm::AttributeSet::intersectWith().
intersectWithAnd()
bool Attribute::intersectWithAnd (AttrKind Kind) static
Definition at line 800 of file Attributes.cpp.
References hasIntersectProperty(), and IntersectAnd.
Referenced by llvm::AttributeSet::intersectWith().
intersectWithCustom()
bool Attribute::intersectWithCustom (AttrKind Kind) static
Definition at line 806 of file Attributes.cpp.
References hasIntersectProperty(), and IntersectCustom.
Referenced by llvm::AttributeSet::intersectWith().
intersectWithMin()
bool Attribute::intersectWithMin (AttrKind Kind) static
Definition at line 803 of file Attributes.cpp.
References hasIntersectProperty(), and IntersectMin.
Referenced by llvm::AttributeSet::intersectWith().
isConstantRangeAttribute()
bool Attribute::isConstantRangeAttribute () const
Return true if the attribute is a ConstantRange attribute.
Definition at line 356 of file Attributes.cpp.
Referenced by getValueAsConstantRange().
isConstantRangeAttrKind()
static bool llvm::Attribute::isConstantRangeAttrKind (AttrKind Kind) inline static
Definition at line 108 of file Attributes.h.
Referenced by get().
isConstantRangeListAttribute()
bool Attribute::isConstantRangeListAttribute () const
Return true if the attribute is a ConstantRangeList attribute.
Definition at line 360 of file Attributes.cpp.
Referenced by getValueAsConstantRangeList().
isConstantRangeListAttrKind()
static bool llvm::Attribute::isConstantRangeListAttrKind (AttrKind Kind) inline static
Definition at line 111 of file Attributes.h.
Referenced by get().
isEnumAttribute()
bool Attribute::isEnumAttribute () const
Return true if the attribute is an Attribute::AttrKind type.
Definition at line 340 of file Attributes.cpp.
Referenced by addIfNotExistent(), and getAsString().
isEnumAttrKind()
static bool llvm::Attribute::isEnumAttrKind (AttrKind Kind) inline static
Definition at line 99 of file Attributes.h.
Referenced by clampReturnedValueStates(), get(), llvm::IRAttribute< AK, BaseType, AAType >::hasTrivialInitializer(), llvm::AttributeSet::intersectWith(), and llvm::AttributeImpl::Profile().
isExistingAttribute()
bool Attribute::isExistingAttribute (StringRef Name) static
Return true if the provided string matches the IR name of an attribute.
example: "noalias" return true but not "NoAlias"
Definition at line 328 of file Attributes.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::hasAttributeInAssume().
isIntAttribute()
bool Attribute::isIntAttribute () const
Return true if the attribute is an integer attribute.
Definition at line 344 of file Attributes.cpp.
Referenced by addIfNotExistent(), getValueAsInt(), and isEqualOrWorse().
isIntAttrKind()
static bool llvm::Attribute::isIntAttrKind (AttrKind Kind) inline static
Definition at line 102 of file Attributes.h.
Referenced by get(), llvm::hasAttributeInAssume(), llvm::IntAttributeImpl::IntAttributeImpl(), llvm::AttributeSet::intersectWith(), and llvm::AttributeImpl::Profile().
isStringAttribute()
bool Attribute::isStringAttribute () const
Return true if the attribute is a string (target-dependent) attribute.
Definition at line 348 of file Attributes.cpp.
Referenced by addIfNotExistent(), getAsString(), getKindAsString(), getValueAsBool(), getValueAsString(), hasAttribute(), hasKindAsEnum(), LLVMIsStringAttribute(), AttributeComparator::operator()(), AttributeComparator::operator()(), AttributeComparator::operator()(), and llvm::parseStatepointDirectivesFromAttrs().
isTypeAttribute()
bool Attribute::isTypeAttribute () const
Return true if the attribute is a type attribute.
Definition at line 352 of file Attributes.cpp.
Referenced by getAsString(), getValueAsType(), getWithNewType(), and LLVMIsTypeAttribute().
isTypeAttrKind()
static bool llvm::Attribute::isTypeAttrKind (AttrKind Kind) inline static
Definition at line 105 of file Attributes.h.
Referenced by addRawAttributeValue(), and get().
isValid()
bool llvm::Attribute::isValid () const inline
Return true if the attribute is any kind of attribute.
Definition at line 208 of file Attributes.h.
Referenced by addNoUndefAttrs(), AddParamAndFnBasicAttributes(), AddReturnAttributes(), adjustCallerStackProbeSize(), adjustMinLegalVectorWidth(), collectMetadataInfo(), llvm::getAllocationFamily(), getAllocFnKind(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::CallBase::getFnAttr(), llvm::AMDGPUTargetMachine::getGPUName(), getParameterABIAttributes(), llvm::CallBase::getRange(), llvm::getStringFnAttrAsInt(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::XtensaTargetMachine::getSubtargetImpl(), llvm::getVScaleRange(), hasParentContext(), llvm::inferAttribute(), llvm::AttributeSet::intersectWith(), isThumbFunction(), llvm::SPIRVCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerReturn(), runImpl(), tryToMoveFreeBeforeNullTest(), llvm::typeIncompatible(), and llvm::updateMinLegalVectorWidthAttr().
operator!=()
bool llvm::Attribute::operator!= (Attribute A) const inline
Definition at line 308 of file Attributes.h.
References A().
operator<()
bool Attribute::operator< (Attribute A) const
Less-than operator. Useful for sorting the attributes list.
Definition at line 738 of file Attributes.cpp.
References A().
operator==()
bool llvm::Attribute::operator== (Attribute A) const inline
Equality and non-equality operators.
Definition at line 307 of file Attributes.h.
References A().
Profile()
void Attribute::Profile (FoldingSetNodeID & ID) const
Definition at line 745 of file Attributes.cpp.
Member Data Documentation
NumIntAttrKinds
const unsigned llvm::Attribute::NumIntAttrKinds = LastIntAttr - FirstIntAttr + 1 static
Definition at line 96 of file Attributes.h.
NumTypeAttrKinds
const unsigned llvm::Attribute::NumTypeAttrKinds = LastTypeAttr - FirstTypeAttr + 1 static
Definition at line 97 of file Attributes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp