LLVM: llvm::OpenMPIRBuilder Class Reference
llvm::OpenMPIRBuilder Class Reference
An interface to create LLVM-IR for OpenMP directives.
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Classes
class AtomicInfo
struct DependData
A struct to pack the relevant information for an OpenMP depend clause.
struct FinalizationInfo
struct LocationDescription
Description of a LLVM-IR insertion point (IP) and a debug/source location (filename, line, column, ...).
Public Types
using InsertPointTy = IRBuilder<>::InsertPoint
Type used throughout for insertion points.
using InsertPointOrErrorTy = Expected<InsertPointTy>
Type used to represent an insertion point or an error value.
using FinalizeCallbackTy = std::function<Error(InsertPointTy CodeGenIP)>
Callback type for variable finalization (think destructors).
using BodyGenCallbackTy
Callback type for body (=inner region) code generation.
using StorableBodyGenCallbackTy
using LoopBodyGenCallbackTy
Callback type for loop body code generation.
using PrivatizeCallbackTy
Callback type for variable privatization (think copy & default constructor).
Public Member Functions
OpenMPIRBuilder (Module &M)
Create a new OpenMPIRBuilder operating on the given module M.
~OpenMPIRBuilder ()
void initialize ()
Initialize the internal state, this will put structures types and potentially other helpers into the underlying module.
void setConfig (OpenMPIRBuilderConfig C)
void finalize (Function *Fn=nullptr)
Finalize the underlying module, e.g., by outlining regions.
void addAttributes (omp::RuntimeFunction FnID, Function &Fn)
Add attributes known for FnID to Fn.
std::string createPlatformSpecificName (ArrayRef< StringRef > Parts) const
Get the create a name using the platform specific separators.
void pushFinalizationCB (const FinalizationInfo &FI)
Push a finalization callback on the finalization stack.
void popFinalizationCB ()
Pop the last finalization callback from the finalization stack.
InsertPointOrErrorTy createBarrier (const LocationDescription &Loc, omp::Directive Kind, bool ForceSimpleCall=false, bool CheckCancelFlag=true)
Emitter methods for OpenMP directives.
InsertPointOrErrorTy createCancel (const LocationDescription &Loc, Value *IfCondition, omp::Directive CanceledDirective)
Generator for 'omp cancel'.
InsertPointOrErrorTy createParallel (const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, Value *IfCondition, Value *NumThreads, omp::ProcBindKind ProcBind, bool IsCancellable)
Generator for 'omp parallel'.
Expected< CanonicalLoopInfo * > createCanonicalLoop (const LocationDescription &Loc, LoopBodyGenCallbackTy BodyGenCB, Value *TripCount, const Twine &Name="loop")
Generator for the control flow structure of an OpenMP canonical loop.
Expected< CanonicalLoopInfo * > createCanonicalLoop (const LocationDescription &Loc, LoopBodyGenCallbackTy BodyGenCB, Value *Start, Value *Stop, Value *Step, bool IsSigned, bool InclusiveStop, InsertPointTy ComputeIP={}, const Twine &Name="loop")
Generator for the control flow structure of an OpenMP canonical loop.
CanonicalLoopInfo * collapseLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, InsertPointTy ComputeIP)
Collapse a loop nest into a single loop.
Constant * getAddrOfDeclareTargetVar (OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind CaptureClause, OffloadEntriesInfoManager::OMPTargetDeviceClauseKind DeviceClause, bool IsDeclaration, bool IsExternallyVisible, TargetRegionEntryInfo EntryInfo, StringRef MangledName, std::vector< GlobalVariable * > &GeneratedRefs, bool OpenMPSIMD, std::vector< Triple > TargetTriple, Type *LlvmPtrTy, std::function< Constant *()> GlobalInitializer, std::function< GlobalValue::LinkageTypes()> VariableLinkage)
Retrieve (or create if non-existent) the address of a declare target variable, used in conjunction with registerTargetGlobalVariable to create declare target global variables.
void registerTargetGlobalVariable (OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind CaptureClause, OffloadEntriesInfoManager::OMPTargetDeviceClauseKind DeviceClause, bool IsDeclaration, bool IsExternallyVisible, TargetRegionEntryInfo EntryInfo, StringRef MangledName, std::vector< GlobalVariable * > &GeneratedRefs, bool OpenMPSIMD, std::vector< Triple > TargetTriple, std::function< Constant *()> GlobalInitializer, std::function< GlobalValue::LinkageTypes()> VariableLinkage, Type *LlvmPtrTy, Constant *Addr)
Registers a target variable for device or host.
unsigned getFlagMemberOffset ()
Get the offset of the OMP_MAP_MEMBER_OF field.
omp::OpenMPOffloadMappingFlags getMemberOfFlag (unsigned Position)
Get OMP_MAP_MEMBER_OF flag with extra bits reserved based on the position given.
void setCorrectMemberOfFlag (omp::OpenMPOffloadMappingFlags &Flags, omp::OpenMPOffloadMappingFlags MemberOfFlag)
Given an initial flag set, this function modifies it to contain the passed in MemberOfFlag generated from the getMemberOfFlag function.
InsertPointOrErrorTy applyWorkshareLoop (DebugLoc DL, CanonicalLoopInfo *CLI, InsertPointTy AllocaIP, bool NeedsBarrier, llvm::omp::ScheduleKind SchedKind=llvm::omp::OMP_SCHEDULE_Default, Value *ChunkSize=nullptr, bool HasSimdModifier=false, bool HasMonotonicModifier=false, bool HasNonmonotonicModifier=false, bool HasOrderedClause=false, omp::WorksharingLoopType LoopType=omp::WorksharingLoopType::ForStaticLoop)
Modifies the canonical loop to be a workshare loop.
std::vector< CanonicalLoopInfo * > tileLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, ArrayRef< Value * > TileSizes)
Tile a loop nest.
void unrollLoopFull (DebugLoc DL, CanonicalLoopInfo *Loop)
Fully unroll a loop.
void unrollLoopHeuristic (DebugLoc DL, CanonicalLoopInfo *Loop)
Fully or partially unroll a loop.
void unrollLoopPartial (DebugLoc DL, CanonicalLoopInfo *Loop, int32_t Factor, CanonicalLoopInfo **UnrolledCLI)
Partially unroll a loop.
void applySimd (CanonicalLoopInfo *Loop, MapVector< Value *, Value * > AlignedVars, Value *IfCond, omp::OrderKind Order, ConstantInt *Simdlen, ConstantInt *Safelen)
Add metadata to simd-ize a loop.
void createFlush (const LocationDescription &Loc)
Generator for 'omp flush'.
void createTaskwait (const LocationDescription &Loc)
Generator for 'omp taskwait'.
void createTaskyield (const LocationDescription &Loc)
Generator for 'omp taskyield'.
InsertPointOrErrorTy createAtomicUpdate (const LocationDescription &Loc, InsertPointTy AllocaIP, AtomicOpValue &X, Value *Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy &UpdateOp, bool IsXBinopExpr)
Generator for #omp task
InsertPointOrErrorTy createAtomicCapture (const LocationDescription &Loc, InsertPointTy AllocaIP, AtomicOpValue &X, AtomicOpValue &V, Value *Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy &UpdateOp, bool UpdateExpr, bool IsPostfixUpdate, bool IsXBinopExpr)
Emit atomic update for constructs: — Only Scalar data types V = X; X = X BinOp Expr , X = X BinOp Expr; V = X, V = X; X = Expr BinOp X, X = Expr BinOp X; V = X, V = X; X = UpdateOp(X), X = UpdateOp(X); V = X,.
InsertPointTy createAtomicCompare (const LocationDescription &Loc, AtomicOpValue &X, AtomicOpValue &V, AtomicOpValue &R, Value *E, Value *D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly)
Emit atomic compare for constructs: — Only scalar data types cond-expr-stmt: x = x ordop expr ?
InsertPointTy createAtomicCompare (const LocationDescription &Loc, AtomicOpValue &X, AtomicOpValue &V, AtomicOpValue &R, Value *E, Value *D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly, AtomicOrdering Failure)
CanonicalLoopInfo * createLoopSkeleton (DebugLoc DL, Value *TripCount, Function *F, BasicBlock *PreInsertBefore, BasicBlock *PostInsertBefore, const Twine &Name={})
Create the control flow structure of a canonical OpenMP loop.
void loadOffloadInfoMetadata (Module &M)
Loads all the offload entries information from the host IR metadata.
void loadOffloadInfoMetadata (StringRef HostFilePath)
Loads all the offload entries information from the host IR metadata read from the file passed in as the HostFilePath argument.
GlobalVariable * getOrCreateInternalVariable (Type *Ty, const StringRef &Name, unsigned AddressSpace=0)
Gets (if variable with the given name already exist) or creates internal global variable with the specified Name.
Static Public Member Functions
static unsigned getOpenMPDefaultSimdAlign (const Triple &TargetTriple, const StringMap< bool > &Features)
Get the default alignment value for given target.
Public Attributes
const std::string ompOffloadInfoName = "omp_offload.info"
OMP Offload Info Metadata name string.
Detailed Description
An interface to create LLVM-IR for OpenMP directives.
Each OpenMP directive has a corresponding public generator method.
Definition at line 474 of file OMPIRBuilder.h.
Member Typedef Documentation
BodyGenCallbackTy
using llvm::OpenMPIRBuilder::BodyGenCallbackTy
Initial value:
      function_ref<Error(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
Callback type for body (=inner region) code generation.
The callback takes code locations as arguments, each describing a location where additional instructions can be inserted.
The CodeGenIP may be in the middle of a basic block or point to the end of it. The basic block may have a terminator or be degenerate. The callback function may just insert instructions at that position, but also split the block (without the Before argument of BasicBlock::splitBasicBlock such that the identify of the split predecessor block is preserved) and insert additional control flow, including branches that do not lead back to what follows the CodeGenIP. Note that since the callback is allowed to split the block, callers must assume that InsertPoints to positions in the BasicBlock after CodeGenIP including CodeGenIP itself are invalidated. If such InsertPoints need to be preserved, it can split the block itself before calling the callback.
AllocaIP and CodeGenIP must not point to the same position.
Parameters
AllocaIP is the insertion point at which new alloca instructions should be placed. The BasicBlock it is pointing to must not be split.
CodeGenIP is the insertion point at which the body code should be placed.
Returns
an error, if any were triggered during execution.
Definition at line 596 of file OMPIRBuilder.h.
FinalizeCallbackTy
using llvm::OpenMPIRBuilder::FinalizeCallbackTy = std::function<Error(InsertPointTy CodeGenIP)>
Callback type for variable finalization (think destructors).
Parameters
CodeGenIP is the insertion point at which the finalization code should be placed.
A finalize callback knows about all objects that need finalization, e.g. destruction, when the scope of the currently generated construct is left at the time, and location, the callback is invoked.
Definition at line 543 of file OMPIRBuilder.h.
InsertPointOrErrorTy
using llvm::OpenMPIRBuilder::InsertPointOrErrorTy = Expected<InsertPointTy>
Type used to represent an insertion point or an error value.
Definition at line 523 of file OMPIRBuilder.h.
InsertPointTy
using llvm::OpenMPIRBuilder::InsertPointTy = IRBuilder<>::InsertPoint
Type used throughout for insertion points.
Definition at line 520 of file OMPIRBuilder.h.
LoopBodyGenCallbackTy
using llvm::OpenMPIRBuilder::LoopBodyGenCallbackTy
Initial value:
      function_ref<Error(InsertPointTy CodeGenIP, Value *IndVar)>
Callback type for loop body code generation.
Parameters
CodeGenIP is the insertion point where the loop's body code must be placed. This will be a dedicated BasicBlock with a conditional branch from the loop condition check and terminated with an unconditional branch to the loop latch.
IndVar is the induction variable usable at the insertion point.
Returns
an error, if any were triggered during execution.
Definition at line 618 of file OMPIRBuilder.h.
PrivatizeCallbackTy
using llvm::OpenMPIRBuilder::PrivatizeCallbackTy
Initial value:
 function_ref<InsertPointOrErrorTy(
      InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Value &Original,
      Value &Inner, Value *&ReplVal)>
Callback type for variable privatization (think copy & default constructor).
Parameters
AllocaIP is the insertion point at which new alloca instructions should be placed.
CodeGenIP is the insertion point at which the privatization code should be placed.
Original The value being copied/created, should not be used in the generated IR.
Inner The equivalent of Original that should be used in the generated IR; this is equal to Original if the value is a pointer and can thus be passed directly, otherwise it is an equivalent but different value.
ReplVal The replacement value, thus a copy or new created version of Inner.
Returns
The new insertion point where code generation continues and ReplVal the replacement value.
Definition at line 639 of file OMPIRBuilder.h.
StorableBodyGenCallbackTy
using llvm::OpenMPIRBuilder::StorableBodyGenCallbackTy
Initial value:
      std::function<Error(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
Returns
an error, if any were triggered during execution.
Definition at line 605 of file OMPIRBuilder.h.
Constructor & Destructor Documentation
OpenMPIRBuilder()
llvm::OpenMPIRBuilder::OpenMPIRBuilder (Module & M) inline
Create a new OpenMPIRBuilder operating on the given module M.
This will not have an effect on M (see initialize)
Definition at line 478 of file OMPIRBuilder.h.
References T.
~OpenMPIRBuilder()
OpenMPIRBuilder::~OpenMPIRBuilder ()
Definition at line 845 of file OMPIRBuilder.cpp.
References assert().
Member Function Documentation
addAttributes()
void OpenMPIRBuilder::addAttributes (omp::RuntimeFunction FnID, Function & Fn)
Add attributes known for FnID to Fn.
Definition at line 562 of file OMPIRBuilder.cpp.
References llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::Function::arg_size(), assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::Function::getAttributes(), llvm::Function::getContext(), and T.
applySimd()
void OpenMPIRBuilder::applySimd (CanonicalLoopInfo * Loop, MapVector< Value *, Value * > AlignedVars, Value * IfCond, omp::OrderKind Order, ConstantInt * Simdlen, ConstantInt * Safelen)
Add metadata to simd-ize a loop.
If IfCond is not nullptr, the loop is cloned. The metadata which prevents vectorization is added to to the cloned loop. The cloned loop is executed when ifCond is evaluated to false.
Parameters
Loop The loop to simd-ize.
AlignedVars The map which containts pairs of the pointer and its corresponding alignment.
IfCond The value which corresponds to the if clause condition.
Order The enum to map order clause.
Simdlen The Simdlen length to apply to the simd loop.
Safelen The Safelen length to apply to the simd loop.
Definition at line 5342 of file OMPIRBuilder.cpp.
References addBasicBlockMetadata(), addLoopMetadata(), addSimdMetadata(), assert(), llvm::Block, llvm::dyn_cast(), F, FAM, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::CanonicalLoopInfo::getCond(), llvm::MDNode::getDistinct(), llvm::ConstantInt::getFalse(), llvm::CanonicalLoopInfo::getFunction(), llvm::CanonicalLoopInfo::getHeader(), llvm::Type::getInt1Ty(), llvm::CanonicalLoopInfo::getLatch(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::ConstantInt::getTrue(), llvm::isa(), llvm::ValueMap< KeyT, ValueT, Config >::lookup(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LoopAnalysis::run(), and llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size().
applyWorkshareLoop()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::applyWorkshareLoop (DebugLoc DL, CanonicalLoopInfo * CLI, InsertPointTy AllocaIP, bool NeedsBarrier, llvm::omp::ScheduleKind SchedKind = llvm::omp::OMP_SCHEDULE_Default, Value * ChunkSize = nullptr, bool HasSimdModifier = false, bool HasMonotonicModifier = false, bool HasNonmonotonicModifier = false, bool HasOrderedClause = false, omp::WorksharingLoopType LoopType = omp::WorksharingLoopType::ForStaticLoop)
Modifies the canonical loop to be a workshare loop.
This takes a LoopInfo representing a canonical loop, such as the one created by createCanonicalLoop and emits additional instructions to turn it into a workshare loop. In particular, it calls to an OpenMP runtime function in the preheader to obtain the loop bounds to be used in the current thread, updates the relevant instructions in the canonical loop and calls to an OpenMP runtime finalization function after the loop.
The concrete transformation is done by applyStaticWorkshareLoop, applyStaticChunkedWorkshareLoop, or applyDynamicWorkshareLoop, depending on the value of SchedKind and ChunkSize.
Parameters
DL Debug location for instructions added for the workshare-loop construct itself.
CLI A descriptor of the canonical loop to workshare.
AllocaIP An insertion point for Alloca instructions usable in the preheader of the loop.
NeedsBarrier Indicates whether a barrier must be insterted after the loop.
SchedKind Scheduling algorithm to use.
ChunkSize The chunk size for the inner loop.
HasSimdModifier Whether the simd modifier is present in the schedule clause.
HasMonotonicModifier Whether the monotonic modifier is present in the schedule clause.
HasNonmonotonicModifier Whether the nonmonotonic modifier is present in the schedule clause.
HasOrderedClause Whether the (parameterless) ordered clause is present.
LoopType Information about type of loop worksharing. It corresponds to type of loop workshare OpenMP pragma.
Returns
Point where to insert code after the workshare construct.
Definition at line 4621 of file OMPIRBuilder.cpp.
References assert(), computeOpenMPScheduleType(), DL, and llvm_unreachable.
collapseLoops()
CanonicalLoopInfo * OpenMPIRBuilder::collapseLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, InsertPointTy ComputeIP)
Collapse a loop nest into a single loop.
Merges loops of a loop nest into a single CanonicalLoopNest representation that has the same number of innermost loop iterations as the origin loop nest. The induction variables of the input loops are derived from the collapsed loop's induction variable. This is intended to be used to implement OpenMP's collapse clause. Before applying a directive, collapseLoops normalizes a loop nest to contain only a single loop and the directive's implementation does not need to handle multiple loops itself. This does not remove the need to handle all loop nest handling by directives, such as the ordered(<n>) clause or the simd schedule-clause modifier of the worksharing-loop directive.
Example:
for (int i = 0; i < 7; ++i) // Canonical loop "i"
  for (int j = 0; j < 9; ++j) // Canonical loop "j"
    body(i, j);
After collapsing with Loops={i,j}, the loop is changed to
for (int ij = 0; ij < 63; ++ij) {
  int i = ij / 9;
  int j = ij % 9;
  body(i, j);
}
In the current implementation, the following limitations apply:
All input loops have an induction variable of the same type.
The collapsed loop will have the same trip count integer type as the input loops. Therefore it is possible that the collapsed loop cannot represent all iterations of the input loops. For instance, assuming a 32 bit integer type, and two input loops both iterating 2^16 times, the theoretical trip count of the collapsed loop would be 2^32 iteration, which cannot be represented in an 32-bit integer. Behavior is undefined in this case.
The trip counts of every input loop must be available at ComputeIP. Non-rectangular loops are not yet supported.
At each nest level, code between a surrounding loop and its nested loop is hoisted into the loop body, and such code will be executed more often than before collapsing (or not at all if any inner loop iteration has a trip count of 0). This is permitted by the OpenMP specification.
Parameters
DL Debug location for instructions added for collapsing, such as instructions to compute/derive the input loop's induction variables.
Loops Loops in the loop nest to collapse. Loops are specified from outermost-to-innermost and every control flow of a loop's body must pass through its directly nested loop.
ComputeIP Where additional instruction that compute the collapsed trip count. If not set, defaults to before the generated loop.
Returns
The CanonicalLoopInfo object representing the collapsed loop.
Definition at line 4887 of file OMPIRBuilder.cpp.
References assert(), createLoopSkeleton(), DL, F, llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getLatch(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), llvm::IRBuilderBase::InsertPoint::isSet(), Loops, redirectAllPredecessorsTo(), redirectTo(), removeUnusedBlocksFromParent(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorImpl< T >::resize().
createAtomicCapture()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createAtomicCapture (const LocationDescription & Loc, InsertPointTy AllocaIP, AtomicOpValue & X, AtomicOpValue & V, Value * Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy & UpdateOp, bool UpdateExpr, bool IsPostfixUpdate, bool IsXBinopExpr)
Emit atomic update for constructs: — Only Scalar data types V = X; X = X BinOp Expr , X = X BinOp Expr; V = X, V = X; X = Expr BinOp X, X = Expr BinOp X; V = X, V = X; X = UpdateOp(X), X = UpdateOp(X); V = X,.
Parameters
Loc The insert and source location description.
AllocaIP The insertion point to be used for alloca instructions.
X The target atomic pointer to be updated
V Memory address where to store captured value
Expr The value to update X with.
AO Atomic ordering of the generated atomic instructions
RMWOp The binary operation used for update. If operation is not supported by atomicRMW, or belong to {FADD, FSUB, BAD_BINOP}. Then a cmpExch based atomic will be generated.
UpdateOp Code generator for complex expressions that cannot be expressed through atomicrmw instruction.
UpdateExpr true if X is an in place update of the form X = X BinOp Expr or X = Expr BinOp X
IsXBinopExpr true if X is Left H.S. in Right H.S. part of the update expression, false otherwise. (e.g. true for X = X BinOp Expr)
IsPostfixUpdate true if original value of 'x' must be stored in 'v', not an updated one.
Returns
Insertion point after generated atomic capture IR.
Definition at line 8793 of file OMPIRBuilder.cpp.
References assert(), emitImplicitCast(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), LLVM_DEBUG, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::Expected< T >::takeError(), X, and llvm::AtomicRMWInst::Xchg.
createAtomicCompare() [1/2]
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicCompare (const LocationDescription & Loc, AtomicOpValue & X, AtomicOpValue & V, AtomicOpValue & R, Value * E, Value * D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly)
Emit atomic compare for constructs: — Only scalar data types cond-expr-stmt: x = x ordop expr ?
expr : x; x = expr ordop x ? expr : x; x = x == e ? d : x; x = e == x ? d : x; (this one is not in the spec) cond-update-stmt: if (x ordop expr) { x = expr; } if (expr ordop x) { x = expr; } if (x == e) { x = d; } if (e == x) { x = d; } (this one is not in the spec) conditional-update-capture-atomic: v = x; cond-update-stmt; (IsPostfixUpdate=true, IsFailOnly=false) cond-update-stmt; v = x; (IsPostfixUpdate=false, IsFailOnly=false) if (x == e) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true) r = x == e; if (r) { x = d; } (IsPostfixUpdate=false, IsFailOnly=false) r = x == e; if (r) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true)
Parameters
Loc The insert and source location description.
X The target atomic pointer to be updated.
V Memory address where to store captured value (for compare capture only).
R Memory address where to store comparison result (for compare capture with '==' only).
E The expected value ('e') for forms that use an equality comparison or an expression ('expr') for forms that use 'ordop' (logically an atomic maximum or minimum).
D The desired value for forms that use an equality comparison. If forms that use 'ordop', it should be nullptr.
AO Atomic ordering of the generated atomic instructions.
Op Atomic compare operation. It can only be ==, <, or >.
IsXBinopExpr True if the conditional statement is in the form where x is on LHS. It only matters for < or >.
IsPostfixUpdate True if original value of 'x' must be stored in 'v', not an updated one (for compare capture only).
IsFailOnly True if the original value of 'x' is stored to 'v' only when the comparison fails. This is only valid for the case the comparison is '=='.
Returns
Insertion point after generated atomic capture IR.
Definition at line 8831 of file OMPIRBuilder.cpp.
References createAtomicCompare(), D(), llvm::AtomicCmpXchgInst::getStrongestFailureOrdering(), and X.
Referenced by createAtomicCompare().
createAtomicCompare() [2/2]
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicCompare (const LocationDescription & Loc, AtomicOpValue & X, AtomicOpValue & V, AtomicOpValue & R, Value * E, Value * D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly, AtomicOrdering Failure)
Definition at line 8842 of file OMPIRBuilder.cpp.
References assert(), D(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLT, llvm::AtomicRMWInst::FMax, llvm::AtomicRMWInst::FMin, llvm::IntegerType::get(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::BasicBlock::splitBasicBlock(), llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, and X.
createAtomicUpdate()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createAtomicUpdate (const LocationDescription & Loc, InsertPointTy AllocaIP, AtomicOpValue & X, Value * Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy & UpdateOp, bool IsXBinopExpr)
Generator for #omp task
Parameters
Loc The location where the task construct was encountered.
AllocaIP The insertion point to be used for alloca instructions.
BodyGenCB Callback that will generate the region code.
Tied True if the task is tied, false if the task is untied.
Final i1 value which is true if the task is final, false if the task is not final.
IfCondition i1 value. If it evaluates to false, an undeferred task is generated, and the encountering thread must suspend the current task region, for which execution cannot be resumed until execution of the structured block that is associated with the generated task is completed.
EventHandle If present, signifies the event handle as part of the detach clause
Mergeable If the given task is mergeable
priority ‘priority-value’ specifies the execution order of the / tasks that is generated by the construct InsertPointOrErrorTy createTask(const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, bool Tied = true, Value *Final = nullptr, Value *IfCondition = nullptr, SmallVector<DependData> Dependencies = {}, bool Mergeable = false, Value *EventHandle = nullptr, Value *Priority = nullptr);
/ Generator for the taskgroup construct / /
Parameters
Loc The location where the taskgroup construct was encountered. /
AllocaIP The insertion point to be used for alloca instructions. /
BodyGenCB Callback that will generate the region code. InsertPointOrErrorTy createTaskgroup(const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB);
using FileIdentifierInfoCallbackTy = std::function<std::tuple<std::string, uint64_t>()>;
/ Creates a unique info for a target entry when provided a filename and / line number from. / /
Parameters
CallBack A callback function which should return filename the entry / resides in as well as the line number for the target entry /
ParentName The name of the parent the target entry resides in, if / any. static TargetRegionEntryInfo getTargetEntryUniqueInfo(FileIdentifierInfoCallbackTy CallBack, StringRef ParentName = "");
/ Enum class for the RedctionGen CallBack type to be used. enum class ReductionGenCBKind { Clang, MLIR };
/ ReductionGen CallBack for Clang / /
Parameters
CodeGenIP InsertPoint for CodeGen. /
Index Index of the ReductionInfo to generate code for. /
LHSPtr Optionally used by Clang to return the LHSPtr it used for / codegen, used for fixup later. /
RHSPtr Optionally used by Clang to / return the RHSPtr it used for codegen, used for fixup later. /
CurFn Optionally used by Clang to pass in the Current Function as / Clang context may be old. using ReductionGenClangCBTy = std::function<InsertPointTy(InsertPointTy CodeGenIP, unsigned Index, Value **LHS, Value **RHS, Function *CurFn)>;
/ ReductionGen CallBack for MLIR / /
Parameters
CodeGenIP InsertPoint for CodeGen. /
LHS Pass in the LHS Value to be used for CodeGen. /
RHS Pass in the RHS Value to be used for CodeGen. using ReductionGenCBTy = std::function<InsertPointOrErrorTy(InsertPointTy CodeGenIP, Value *LHS, Value *RHS, Value *&Res)>;
/ Functions used to generate atomic reductions. Such functions take two / Values representing pointers to LHS and RHS of the reduction, as well as / the element type of these pointers. They are expected to atomically / update the LHS to the reduced value. using ReductionGenAtomicCBTy = std::function<InsertPointOrErrorTy(InsertPointTy, Type *, Value *, Value *)>;
/ Enum class for reduction evaluation types scalar, complex and aggregate. enum class EvalKind { Scalar, Complex, Aggregate };
/ Information about an OpenMP reduction. struct ReductionInfo { ReductionInfo(Type *ElementType, Value *Variable, Value *PrivateVariable, EvalKind EvaluationKind, ReductionGenCBTy ReductionGen, ReductionGenClangCBTy ReductionGenClang, ReductionGenAtomicCBTy AtomicReductionGen) : ElementType(ElementType), Variable(Variable), PrivateVariable(PrivateVariable), EvaluationKind(EvaluationKind), ReductionGen(ReductionGen), ReductionGenClang(ReductionGenClang), AtomicReductionGen(AtomicReductionGen) {} ReductionInfo(Value *PrivateVariable) : ElementType(nullptr), Variable(nullptr), PrivateVariable(PrivateVariable), EvaluationKind(EvalKind::Scalar), ReductionGen(), ReductionGenClang(), AtomicReductionGen() {}
/ Reduction element type, must match pointee type of variable. Type *ElementType;
/ Reduction variable of pointer type. Value *Variable;
/ Thread-private partial reduction variable. Value *PrivateVariable;
/ Reduction evaluation kind - scalar, complex or aggregate. EvalKind EvaluationKind;
/ Callback for generating the reduction body. The IR produced by this will / be used to combine two values in a thread-safe context, e.g., under / lock or within the same thread, and therefore need not be atomic. ReductionGenCBTy ReductionGen;
/ Clang callback for generating the reduction body. The IR produced by / this will be used to combine two values in a thread-safe context, e.g., / under lock or within the same thread, and therefore need not be atomic. ReductionGenClangCBTy ReductionGenClang;
/ Callback for generating the atomic reduction body, may be null. The IR / produced by this will be used to atomically combine two values during / reduction. If null, the implementation will use the non-atomic version / along with the appropriate synchronization mechanisms. ReductionGenAtomicCBTy AtomicReductionGen; };
enum class CopyAction : unsigned { RemoteLaneToThread: Copy over a Reduce list from a remote lane in the warp using shuffle instructions. RemoteLaneToThread, ThreadCopy: Make a copy of a Reduce list on the thread's stack. ThreadCopy, };
struct CopyOptionsTy { Value *RemoteLaneOffset = nullptr; Value *ScratchpadIndex = nullptr; Value *ScratchpadWidth = nullptr; };
/ Supporting functions for Reductions CodeGen. private: / Get the id of the current thread on the GPU. Value *getGPUThreadID();
/ Get the GPU warp size. Value *getGPUWarpSize();
/ Get the id of the warp in the block. / We assume that the warp size is 32, which is always the case / on the NVPTX device, to generate more efficient code. Value *getNVPTXWarpID();
/ Get the id of the current lane in the Warp. / We assume that the warp size is 32, which is always the case / on the NVPTX device, to generate more efficient code. Value *getNVPTXLaneID();
/ Cast value to the specified type. Value *castValueToType(InsertPointTy AllocaIP, Value *From, Type *ToType);
/ This function creates calls to one of two shuffle functions to copy / variables between lanes in a warp. Value *createRuntimeShuffleFunction(InsertPointTy AllocaIP, Value *Element, Type *ElementType, Value *Offset);
/ Function to shuffle over the value from the remote lane. void shuffleAndStore(InsertPointTy AllocaIP, Value *SrcAddr, Value *DstAddr, Type *ElementType, Value *Offset, Type *ReductionArrayTy);
/ Emit instructions to copy a Reduce list, which contains partially / aggregated values, in the specified direction. void emitReductionListCopy(InsertPointTy AllocaIP, CopyAction Action, Type *ReductionArrayTy, ArrayRef<ReductionInfo> ReductionInfos, Value *SrcBase, Value *DestBase, CopyOptionsTy CopyOptions = {nullptr, nullptr, nullptr});
/ Emit a helper that reduces data across two OpenMP threads (lanes) / in the same warp. It uses shuffle instructions to copy over data from / a remote lane's stack. The reduction algorithm performed is specified / by the fourth parameter. / / Algorithm Versions. / Full Warp Reduce (argument value 0): / This algorithm assumes that all 32 lanes are active and gathers / data from these 32 lanes, producing a single resultant value. / Contiguous Partial Warp Reduce (argument value 1): / This algorithm assumes that only a contiguous subset of lanes / are active. This happens for the last warp in a parallel region / when the user specified num_threads is not an integer multiple of / 32. This contiguous subset always starts with the zeroth lane. / Partial Warp Reduce (argument value 2): / This algorithm gathers data from any number of lanes at any position. / All reduced values are stored in the lowest possible lane. The set / of problems every algorithm addresses is a super set of those / addressable by algorithms with a lower version number. Overhead / increases as algorithm version increases. / / Terminology / Reduce element: / Reduce element refers to the individual data field with primitive / data types to be combined and reduced across threads. / Reduce list: / Reduce list refers to a collection of local, thread-private / reduce elements. / Remote Reduce list: / Remote Reduce list refers to a collection of remote (relative to / the current thread) reduce elements. / / We distinguish between three states of threads that are important to / the implementation of this function. / Alive threads: / Threads in a warp executing the SIMT instruction, as distinguished from / threads that are inactive due to divergent control flow. / Active threads: / The minimal set of threads that has to be alive upon entry to this / function. The computation is correct iff active threads are alive. / Some threads are alive but they are not active because they do not / contribute to the computation in any useful manner. Turning them off / may introduce control flow overheads without any tangible benefits. / Effective threads: / In order to comply with the argument requirements of the shuffle / function, we must keep all lanes holding data alive. But at most / half of them perform value aggregation; we refer to this half of / threads as effective. The other half is simply handing off their / data. / / Procedure / Value shuffle: / In this step active threads transfer data from higher lane positions / in the warp to lower lane positions, creating Remote Reduce list. / Value aggregation: / In this step, effective threads combine their thread local Reduce list / with Remote Reduce list and store the result in the thread local / Reduce list. / Value copy: / In this step, we deal with the assumption made by algorithm 2 / (i.e. contiguity assumption). When we have an odd number of lanes / active, say 2k+1, only k threads will be effective and therefore k / new values will be produced. However, the Reduce list owned by the / (2k+1)th thread is ignored in the value aggregation. Therefore / we copy the Reduce list from the (2k+1)th lane to (k+1)th lane so / that the contiguity assumption still holds. / /
Parameters
ReductionInfos Array type containing the ReductionOps. /
ReduceFn The reduction function. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The ShuffleAndReduce function. Function *emitShuffleAndReduceFunction(ArrayRef<OpenMPIRBuilder::ReductionInfo> ReductionInfos, Function *ReduceFn, AttributeList FuncAttrs);
/ This function emits a helper that gathers Reduce lists from the first / lane of every active warp to lanes in the first warp. / / void inter_warp_copy_func(void* reduce_data, num_warps) / shared smem[warp_size]; / For all data entries D in reduce_data: / sync / If (I am the first lane in each warp) / Copy my local D to smem[warp_id] / sync / if (I am the first warp) / Copy smem[thread_id] to my local D / /
Parameters
Loc The insert and source location description. /
ReductionInfos Array type containing the ReductionOps. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The InterWarpCopy function. Expected<Function *> emitInterWarpCopyFunction(const LocationDescription &Loc, ArrayRef<ReductionInfo> ReductionInfos, AttributeList FuncAttrs);
/ This function emits a helper that copies all the reduction variables from / the team into the provided global buffer for the reduction variables. / / void list_to_global_copy_func(void *buffer, int Idx, void *reduce_data) / For all data entries D in reduce_data: / Copy local D to buffer.D[Idx] / /
Parameters
ReductionInfos Array type containing the ReductionOps. /
ReductionsBufferTy The StructTy for the reductions buffer. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The ListToGlobalCopy function. Function *emitListToGlobalCopyFunction(ArrayRef<ReductionInfo> ReductionInfos, Type *ReductionsBufferTy, AttributeList FuncAttrs);
/ This function emits a helper that copies all the reduction variables from / the team into the provided global buffer for the reduction variables. / / void list_to_global_copy_func(void *buffer, int Idx, void *reduce_data) / For all data entries D in reduce_data: / Copy buffer.D[Idx] to local D; / /
Parameters
ReductionInfos Array type containing the ReductionOps. /
ReductionsBufferTy The StructTy for the reductions buffer. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The GlobalToList function. Function *emitGlobalToListCopyFunction(ArrayRef<ReductionInfo> ReductionInfos, Type *ReductionsBufferTy, AttributeList FuncAttrs);
/ This function emits a helper that reduces all the reduction variables from / the team into the provided global buffer for the reduction variables. / / void list_to_global_reduce_func(void <em>buffer, int Idx, void *reduce_data) / void *GlobPtrs[]; / GlobPtrs[0] = (void)&buffer.D0[Idx]; / ... / GlobPtrs[N] = (void*)&buffer.DN[Idx]; / reduce_function(GlobPtrs, reduce_data); / /
Parameters
ReductionInfos Array type containing the ReductionOps. /
ReduceFn The reduction function. /
ReductionsBufferTy The StructTy for the reductions buffer. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The ListToGlobalReduce function. Function * emitListToGlobalReduceFunction(ArrayRef<ReductionInfo> ReductionInfos, Function *ReduceFn, Type *ReductionsBufferTy, AttributeList FuncAttrs);
/ This function emits a helper that reduces all the reduction variables from / the team into the provided global buffer for the reduction variables. / / void global_to_list_reduce_func(void <em>buffer, int Idx, void *reduce_data) / void *GlobPtrs[]; / GlobPtrs[0] = (void)&buffer.D0[Idx]; / ... / GlobPtrs[N] = (void*)&buffer.DN[Idx]; / reduce_function(reduce_data, GlobPtrs); / /
Parameters
ReductionInfos Array type containing the ReductionOps. /
ReduceFn The reduction function. /
ReductionsBufferTy The StructTy for the reductions buffer. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The GlobalToListReduce function. Function * emitGlobalToListReduceFunction(ArrayRef<ReductionInfo> ReductionInfos, Function *ReduceFn, Type *ReductionsBufferTy, AttributeList FuncAttrs);
/ Get the function name of a reduction function. std::string getReductionFuncName(StringRef Name) const;
/ Emits reduction function. /
Parameters
ReducerName Name of the function calling the reduction. /
ReductionInfos Array type containing the ReductionOps. /
ReductionGenCBKind Optional param to specify Clang or MLIR / CodeGenCB kind. /
FuncAttrs Optional param to specify any function attributes that / need to be copied to the new function. / /
Returns
The reduction function. Expected<Function *> createReductionFunction(StringRef ReducerName, ArrayRef<ReductionInfo> ReductionInfos, ReductionGenCBKind ReductionGenCBKind = ReductionGenCBKind::MLIR, AttributeList FuncAttrs = {});
public: / / Design of OpenMP reductions on the GPU / / Consider a typical OpenMP program with one or more reduction / clauses: / / float foo; / double bar; / #pragma omp target teams distribute parallel for \ / reduction(+:foo) reduction(*:bar) / for (int i = 0; i < N; i++) { / foo += A[i]; bar *= B[i]; / } / / where 'foo' and 'bar' are reduced across all OpenMP threads in / all teams. In our OpenMP implementation on the NVPTX device an / OpenMP team is mapped to a CUDA threadblock and OpenMP threads / within a team are mapped to CUDA threads within a threadblock. / Our goal is to efficiently aggregate values across all OpenMP / threads such that: / / - the compiler and runtime are logically concise, and / - the reduction is performed efficiently in a hierarchical / manner as follows: within OpenMP threads in the same warp, / across warps in a threadblock, and finally across teams on / the NVPTX device. / / Introduction to Decoupling / / We would like to decouple the compiler and the runtime so that the / latter is ignorant of the reduction variables (number, data types) / and the reduction operators. This allows a simpler interface / and implementation while still attaining good performance. / / Pseudocode for the aforementioned OpenMP program generated by the / compiler is as follows: / / 1. Create private copies of reduction variables on each OpenMP / thread: 'foo_private', 'bar_private' / 2. Each OpenMP thread reduces the chunk of 'A' and 'B' assigned / to it and writes the result in 'foo_private' and 'bar_private' / respectively. / 3. Call the OpenMP runtime on the GPU to reduce within a team / and store the result on the team master: / / __kmpc_nvptx_parallel_reduce_nowait_v2(..., / reduceData, shuffleReduceFn, interWarpCpyFn) / / where: / struct ReduceData { / double *foo; / double *bar; / } reduceData / reduceData.foo = &foo_private / reduceData.bar = &bar_private / / 'shuffleReduceFn' and 'interWarpCpyFn' are pointers to two / auxiliary functions generated by the compiler that operate on / variables of type 'ReduceData'. They aid the runtime perform / algorithmic steps in a data agnostic manner. / / 'shuffleReduceFn' is a pointer to a function that reduces data / of type 'ReduceData' across two OpenMP threads (lanes) in the / same warp. It takes the following arguments as input: / / a. variable of type 'ReduceData' on the calling lane, / b. its lane_id, / c. an offset relative to the current lane_id to generate a / remote_lane_id. The remote lane contains the second / variable of type 'ReduceData' that is to be reduced. / d. an algorithm version parameter determining which reduction / algorithm to use. / / 'shuffleReduceFn' retrieves data from the remote lane using / efficient GPU shuffle intrinsics and reduces, using the / algorithm specified by the 4th parameter, the two operands / element-wise. The result is written to the first operand. / / Different reduction algorithms are implemented in different / runtime functions, all calling 'shuffleReduceFn' to perform / the essential reduction step. Therefore, based on the 4th / parameter, this function behaves slightly differently to / cooperate with the runtime to ensure correctness under / different circumstances. / / 'InterWarpCpyFn' is a pointer to a function that transfers / reduced variables across warps. It tunnels, through CUDA / shared memory, the thread-private data of type 'ReduceData' / from lane 0 of each warp to a lane in the first warp. / 4. Call the OpenMP runtime on the GPU to reduce across teams. / The last team writes the global reduced value to memory. / / ret = __kmpc_nvptx_teams_reduce_nowait(..., / reduceData, shuffleReduceFn, interWarpCpyFn, / scratchpadCopyFn, loadAndReduceFn) / / 'scratchpadCopyFn' is a helper that stores reduced / data from the team master to a scratchpad array in / global memory. / / 'loadAndReduceFn' is a helper that loads data from / the scratchpad array and reduces it with the input / operand. / / These compiler generated functions hide address / calculation and alignment information from the runtime. / 5. if ret == 1: / The team master of the last team stores the reduced / result to the globals in memory. / foo += reduceData.foo; bar *= reduceData.bar / / / Warp Reduction Algorithms / / On the warp level, we have three algorithms implemented in the / OpenMP runtime depending on the number of active lanes: / / Full Warp Reduction / / The reduce algorithm within a warp where all lanes are active / is implemented in the runtime as follows: / / full_warp_reduce(void *reduce_data, / kmp_ShuffleReductFctPtr ShuffleReduceFn) { / for (int offset = WARPSIZE/2; offset > 0; offset /= 2) / ShuffleReduceFn(reduce_data, 0, offset, 0); / } / / The algorithm completes in log(2, WARPSIZE) steps. / / 'ShuffleReduceFn' is used here with lane_id set to 0 because it is / not used therefore we save instructions by not retrieving lane_id / from the corresponding special registers. The 4th parameter, which / represents the version of the algorithm being used, is set to 0 to / signify full warp reduction. / / In this version, 'ShuffleReduceFn' behaves, per element, as follows: / / #reduce_elem refers to an element in the local lane's data structure / #remote_elem is retrieved from a remote lane / remote_elem = shuffle_down(reduce_elem, offset, WARPSIZE); / reduce_elem = reduce_elem REDUCE_OP remote_elem; / / Contiguous Partial Warp Reduction / / This reduce algorithm is used within a warp where only the first / 'n' (n <= WARPSIZE) lanes are active. It is typically used when the / number of OpenMP threads in a parallel region is not a multiple of / WARPSIZE. The algorithm is implemented in the runtime as follows: / / void / contiguous_partial_reduce(void *reduce_data, / kmp_ShuffleReductFctPtr ShuffleReduceFn, / int size, int lane_id) { / int curr_size; / int offset; / curr_size = size; / mask = curr_size/2; / while (offset>0) { / ShuffleReduceFn(reduce_data, lane_id, offset, 1); / curr_size = (curr_size+1)/2; / offset = curr_size/2; / } / } / / In this version, 'ShuffleReduceFn' behaves, per element, as follows: / / remote_elem = shuffle_down(reduce_elem, offset, WARPSIZE); / if (lane_id < offset) / reduce_elem = reduce_elem REDUCE_OP remote_elem / else / reduce_elem = remote_elem / / This algorithm assumes that the data to be reduced are located in a / contiguous subset of lanes starting from the first. When there is / an odd number of active lanes, the data in the last lane is not / aggregated with any other lane's dat but is instead copied over. / / Dispersed Partial Warp Reduction / / This algorithm is used within a warp when any discontiguous subset of / lanes are active. It is used to implement the reduction operation / across lanes in an OpenMP simd region or in a nested parallel region. / / void / dispersed_partial_reduce(void *reduce_data, / kmp_ShuffleReductFctPtr ShuffleReduceFn) { / int size, remote_id; / int logical_lane_id = number_of_active_lanes_before_me() * 2; / do { / remote_id = next_active_lane_id_right_after_me(); / # the above function returns 0 of no active lane / # is present right after the current lane. / size = number_of_active_lanes_in_this_warp(); / logical_lane_id /= 2; / ShuffleReduceFn(reduce_data, logical_lane_id, / remote_id-1-threadIdx.x, 2); / } while (logical_lane_id % 2 == 0 && size > 1); / } / / There is no assumption made about the initial state of the reduction. / Any number of lanes (>=1) could be active at any position. The reduction / result is returned in the first active lane. / / In this version, 'ShuffleReduceFn' behaves, per element, as follows: / / remote_elem = shuffle_down(reduce_elem, offset, WARPSIZE); / if (lane_id % 2 == 0 && offset > 0) / reduce_elem = reduce_elem REDUCE_OP remote_elem / else / reduce_elem = remote_elem / / / Intra-Team Reduction / / This function, as implemented in the runtime call / '__kmpc_nvptx_parallel_reduce_nowait_v2', aggregates data across OpenMP / threads in a team. It first reduces within a warp using the / aforementioned algorithms. We then proceed to gather all such / reduced values at the first warp. / / The runtime makes use of the function 'InterWarpCpyFn', which copies / data from each of the "warp master" (zeroth lane of each warp, where / warp-reduced data is held) to the zeroth warp. This step reduces (in / a mathematical sense) the problem of reduction across warp masters in / a block to the problem of warp reduction. / / / Inter-Team Reduction / / Once a team has reduced its data to a single value, it is stored in / a global scratchpad array. Since each team has a distinct slot, this / can be done without locking. / / The last team to write to the scratchpad array proceeds to reduce the / scratchpad array. One or more workers in the last team use the helper / 'loadAndReduceDataFn' to load and reduce values from the array, i.e., / the k'th worker reduces every k'th element. / / Finally, a call is made to '__kmpc_nvptx_parallel_reduce_nowait_v2' to / reduce across workers and compute a globally reduced value. / /
Parameters
Loc The location where the reduction was / encountered. Must be within the associate / directive and after the last local access to the / reduction variables. /
AllocaIP An insertion point suitable for allocas usable / in reductions. /
CodeGenIP An insertion point suitable for code / generation.
ReductionInfos A list of info on each reduction / variable.
IsNoWait Optional flag set if the reduction is / marked as / nowait. /
IsTeamsReduction Optional flag set if it is a teams / reduction. /
HasDistribute Optional flag set if it is a / distribute reduction. /
GridValue Optional GPU grid value. /
ReductionBufNum Optional OpenMPCUDAReductionBufNumValue to be / used for teams reduction. /
SrcLocInfo Source location information global. InsertPointOrErrorTy createReductionsGPU(const LocationDescription &Loc, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, ArrayRef<ReductionInfo> ReductionInfos, bool IsNoWait = false, bool IsTeamsReduction = false, bool HasDistribute = false, ReductionGenCBKind ReductionGenCBKind = ReductionGenCBKind::MLIR, std::optional<omp::GV> GridValue = {}, unsigned ReductionBufNum = 1024, Value *SrcLocInfo = nullptr);
TODO: provide atomic and non-atomic reduction generators for reduction operators defined by the OpenMP specification.
/ Generator for 'omp reduction'. / / Emits the IR instructing the runtime to perform the specific kind of / reductions. Expects reduction variables to have been privatized and / initialized to reduction-neutral values separately. Emits the calls to / runtime functions as well as the reduction function and the basic blocks / performing the reduction atomically and non-atomically. / / The code emitted for the following: / /
///   type var_1;
///   type var_2;
///   #pragma omp <directive> reduction(reduction-op:var_1,var_2)
///   /* body */;
///
/ / corresponds to the following sketch. / /
/// void _outlined_par() {
///   // N is the number of different reductions.
///   void *red_array[] = {privatized_var_1, privatized_var_2, ...};
///   switch(__kmpc_reduce(..., N, /*size of data in red array*/, red_array,
///                        _omp_reduction_func,
///                        _gomp_critical_user.reduction.var)) {
///   case 1: {
///     var_1 = var_1 <reduction-op> privatized_var_1;
///     var_2 = var_2 <reduction-op> privatized_var_2;
///     // ...
///    __kmpc_end_reduce(...);
///     break;
///   }
///   case 2: {
///     _Atomic<ReductionOp>(var_1, privatized_var_1);
///     _Atomic<ReductionOp>(var_2, privatized_var_2);
///     // ...
///     break;
///   }
///   default: break;
///   }
/// }
///
/// void _omp_reduction_func(void **lhs, void **rhs) {
///   *(type *)lhs[0] = *(type *)lhs[0] <reduction-op> *(type *)rhs[0];
///   *(type *)lhs[1] = *(type *)lhs[1] <reduction-op> *(type *)rhs[1];
///   // ...
/// }
///
/ /
Parameters
Loc The location where the reduction was / encountered. Must be within the associate / directive and after the last local access to the / reduction variables. /
AllocaIP An insertion point suitable for allocas usable / in reductions. /
ReductionInfos A list of info on each reduction variable. /
IsNoWait A flag set if the reduction is marked as nowait. /
IsByRef A flag set if the reduction is using reference / or direct value. InsertPointOrErrorTy createReductions(const LocationDescription &Loc, InsertPointTy AllocaIP, ArrayRef<ReductionInfo> ReductionInfos, ArrayRef<bool> IsByRef, bool IsNoWait = false);
/}
/ Return the insertion point used by the underlying IRBuilder. InsertPointTy getInsertionPoint() { return Builder.saveIP(); }
/ Update the internal location to Loc. bool updateToLocation(const LocationDescription &Loc) { Builder.restoreIP(Loc.IP); Builder.SetCurrentDebugLocation(Loc.DL); return Loc.IP.getBlock() != nullptr; }
/ Return the function declaration for the runtime function with FnID. FunctionCallee getOrCreateRuntimeFunction(Module &M, omp::RuntimeFunction FnID);
Function *getOrCreateRuntimeFunctionPtr(omp::RuntimeFunction FnID);
/ Return the (LLVM-IR) string describing the source location LocStr. Constant *getOrCreateSrcLocStr(StringRef LocStr, uint32_t &SrcLocStrSize);
/ Return the (LLVM-IR) string describing the default source location. Constant *getOrCreateDefaultSrcLocStr(uint32_t &SrcLocStrSize);
/ Return the (LLVM-IR) string describing the source location identified by / the arguments. Constant *getOrCreateSrcLocStr(StringRef FunctionName, StringRef FileName, unsigned Line, unsigned Column, uint32_t &SrcLocStrSize);
/ Return the (LLVM-IR) string describing the DebugLoc DL. Use F as / fallback if DL does not specify the function name. Constant *getOrCreateSrcLocStr(DebugLoc DL, uint32_t &SrcLocStrSize, Function *F = nullptr);
/ Return the (LLVM-IR) string describing the source location Loc. Constant *getOrCreateSrcLocStr(const LocationDescription &Loc, uint32_t &SrcLocStrSize);
/ Return an ident_t* encoding the source location SrcLocStr and Flags. / TODO: Create a enum class for the Reserve2Flags Constant *getOrCreateIdent(Constant *SrcLocStr, uint32_t SrcLocStrSize, omp::IdentFlag Flags = omp::IdentFlag(0), unsigned Reserve2Flags = 0);
/ Create a hidden global flag Name in the module with initial value / Value. GlobalValue *createGlobalFlag(unsigned Value, StringRef Name);
/ Emit the llvm.used metadata. void emitUsed(StringRef Name, ArrayRef<llvm::WeakTrackingVH> List);
/ Emit the kernel execution mode. GlobalVariable *emitKernelExecutionMode(StringRef KernelName, omp::OMPTgtExecModeFlags Mode);
/ Generate control flow and cleanup for cancellation. / /
Parameters
CancelFlag Flag indicating if the cancellation is performed. /
CanceledDirective The kind of directive that is cancled. /
ExitCB Extra code to be generated in the exit block. / /
Returns
an error, if any were triggered during execution. Error emitCancelationCheckImpl(Value *CancelFlag, omp::Directive CanceledDirective, FinalizeCallbackTy ExitCB = {});
/ Generate a target region entry call. / /
Parameters
Loc The location at which the request originated and is fulfilled. /
AllocaIP The insertion point to be used for alloca instructions. /
Return Return value of the created function returned by reference. /
DeviceID Identifier for the device via the 'device' clause. /
NumTeams Numer of teams for the region via the 'num_teams' clause / or 0 if unspecified and -1 if there is no 'teams' clause. /
NumThreads Number of threads via the 'thread_limit' clause. /
HostPtr Pointer to the host-side pointer of the target kernel. /
KernelArgs Array of arguments to the kernel. InsertPointTy emitTargetKernel(const LocationDescription &Loc, InsertPointTy AllocaIP, Value *&Return, Value *Ident, Value *DeviceID, Value *NumTeams, Value *NumThreads, Value *HostPtr, ArrayRef<Value *> KernelArgs);
/ Generate a flush runtime call. / /
Parameters
Loc The location at which the request originated and is fulfilled. void emitFlush(const LocationDescription &Loc);
/ The finalization stack made up of finalize callbacks currently in-flight, / wrapped into FinalizationInfo objects that reference also the finalization / target block and the kind of cancellable directive. SmallVector<FinalizationInfo, 8> FinalizationStack;
/ Return true if the last entry in the finalization stack is of kind DK / and cancellable. bool isLastFinalizationInfoCancellable(omp::Directive DK) { return !FinalizationStack.empty() && FinalizationStack.back().IsCancellable && FinalizationStack.back().DK == DK; }
/ Generate a taskwait runtime call. / /
Parameters
Loc The location at which the request originated and is fulfilled. void emitTaskwaitImpl(const LocationDescription &Loc);
/ Generate a taskyield runtime call. / /
Parameters
Loc The location at which the request originated and is fulfilled. void emitTaskyieldImpl(const LocationDescription &Loc);
/ Return the current thread ID. / /
Parameters
Ident The ident (ident_t*) describing the query origin. Value *getOrCreateThreadID(Value *Ident);
/ The OpenMPIRBuilder Configuration OpenMPIRBuilderConfig Config;
/ The underlying LLVM-IR module Module &M;
/ The LLVM-IR Builder used to create IR. IRBuilder<> Builder;
/ Map to remember source location strings StringMap<Constant *> SrcLocStrMap;
/ Map to remember existing ident_t*. DenseMap<std::pair<Constant *, uint64_t>, Constant *> IdentMap;
/ Info manager to keep track of target regions. OffloadEntriesInfoManager OffloadInfoManager;
/ The target triple of the underlying module. const Triple T;
/ Helper that contains information about regions we need to outline / during finalization. struct OutlineInfo { using PostOutlineCBTy = std::function<void(Function &)>; PostOutlineCBTy PostOutlineCB; BasicBlock *EntryBB, *ExitBB, *OuterAllocaBB; SmallVector<Value *, 2> ExcludeArgsFromAggregate;
/ Collect all blocks in between EntryBB and ExitBB in both the given / vector and set. void collectBlocks(SmallPtrSetImpl<BasicBlock *> &BlockSet, SmallVectorImpl<BasicBlock *> &BlockVector);
/ Return the function that contains the region to be outlined. Function *getFunction() const { return EntryBB->getParent(); } };
/ Collection of regions that need to be outlined during finalization. SmallVector<OutlineInfo, 16> OutlineInfos;
/ A collection of candidate target functions that's constant allocas will / attempt to be raised on a call of finalize after all currently enqueued / outline info's have been processed. SmallVector<llvm::Function *, 16> ConstantAllocaRaiseCandidates;
/ Collection of owned canonical loop objects that eventually need to be / free'd. std::forward_list<CanonicalLoopInfo> LoopInfos;
/ Add a new region that will be outlined later. void addOutlineInfo(OutlineInfo &&OI) { OutlineInfos.emplace_back(OI); }
/ An ordered map of auto-generated variables to their unique names. / It stores variables with the following names: 1) ".gomp_critical_user_" + / <critical_section_name> + ".var" for "omp critical" directives; 2) / <mangled_name_for_global_var> + ".cache." for cache for threadprivate / variables. StringMap<GlobalVariable *, BumpPtrAllocator> InternalVars;
/ Computes the size of type in bytes. Value *getSizeInBytes(Value *BasePtr);
Emit a branch from the current block to the Target block only if the current block has a terminator. void emitBranch(BasicBlock *Target);
If BB has no use then delete it and return. Else place BB after the current block, if possible, or else at the end of the function. Also add a branch from current block to BB if current block does not have a terminator. void emitBlock(BasicBlock *BB, Function *CurFn, bool IsFinished = false);
/ Emits code for OpenMP 'if' clause using specified BodyGenCallbackTy / Here is the logic: / if (Cond) { / ThenGen(); / } else { / ElseGen(); / } / /
Returns
an error, if any were triggered during execution. Error emitIfClause(Value *Cond, BodyGenCallbackTy ThenGen, BodyGenCallbackTy ElseGen, InsertPointTy AllocaIP = {});
/ Create the global variable holding the offload mappings information. GlobalVariable *createOffloadMaptypes(SmallVectorImpl<uint64_t> &Mappings, std::string VarName);
/ Create the global variable holding the offload names information. GlobalVariable * createOffloadMapnames(SmallVectorImpl<llvm::Constant *> &Names, std::string VarName);
struct MapperAllocas { AllocaInst *ArgsBase = nullptr; AllocaInst *Args = nullptr; AllocaInst *ArgSizes = nullptr; };
/ Create the allocas instruction used in call to mapper functions. void createMapperAllocas(const LocationDescription &Loc, InsertPointTy AllocaIP, unsigned NumOperands, struct MapperAllocas &MapperAllocas);
/ Create the call for the target mapper function. /
Parameters
Loc The source location description. /
MapperFunc Function to be called. /
SrcLocInfo Source location information global. /
MaptypesArg The argument types. /
MapnamesArg The argument names. /
MapperAllocas The AllocaInst used for the call. /
DeviceID Device ID for the call. /
NumOperands Number of operands in the call. void emitMapperCall(const LocationDescription &Loc, Function *MapperFunc, Value *SrcLocInfo, Value *MaptypesArg, Value *MapnamesArg, struct MapperAllocas &MapperAllocas, int64_t DeviceID, unsigned NumOperands);
/ Container for the arguments used to pass data to the runtime library. struct TargetDataRTArgs { / The array of base pointer passed to the runtime library. Value *BasePointersArray = nullptr; / The array of section pointers passed to the runtime library. Value *PointersArray = nullptr; / The array of sizes passed to the runtime library. Value *SizesArray = nullptr; / The array of map types passed to the runtime library for the beginning / of the region or for the entire region if there are no separate map / types for the region end. Value *MapTypesArray = nullptr; / The array of map types passed to the runtime library for the end of the / region, or nullptr if there are no separate map types for the region / end. Value *MapTypesArrayEnd = nullptr; / The array of user-defined mappers passed to the runtime library. Value *MappersArray = nullptr; / The array of original declaration names of mapped pointers sent to the / runtime library for debugging Value *MapNamesArray = nullptr;
explicit TargetDataRTArgs() {} explicit TargetDataRTArgs(Value *BasePointersArray, Value *PointersArray, Value *SizesArray, Value *MapTypesArray, Value *MapTypesArrayEnd, Value *MappersArray, Value *MapNamesArray) : BasePointersArray(BasePointersArray), PointersArray(PointersArray), SizesArray(SizesArray), MapTypesArray(MapTypesArray), MapTypesArrayEnd(MapTypesArrayEnd), MappersArray(MappersArray), MapNamesArray(MapNamesArray) {} };
/ Container to pass the default attributes with which a kernel must be / launched, used to set kernel attributes and populate associated static / structures. / / For max values, < 0 means unset, == 0 means set but unknown at compile / time. The number of max values will be 1 except for the case where / ompx_bare is set. struct TargetKernelDefaultAttrs { omp::OMPTgtExecModeFlags ExecFlags = omp::OMPTgtExecModeFlags::OMP_TGT_EXEC_MODE_GENERIC; SmallVector<int32_t, 3> MaxTeams = {-1}; int32_t MinTeams = 1; SmallVector<int32_t, 3> MaxThreads = {-1}; int32_t MinThreads = 1; };
/ Container to pass LLVM IR runtime values or constants related to the / number of teams and threads with which the kernel must be launched, as / well as the trip count of the loop, if it is an SPMD or Generic-SPMD / kernel. These must be defined in the host prior to the call to the kernel / launch OpenMP RTL function. struct TargetKernelRuntimeAttrs { SmallVector<Value *, 3> MaxTeams = {nullptr}; Value *MinTeams = nullptr; SmallVector<Value *, 3> TargetThreadLimit = {nullptr}; SmallVector<Value *, 3> TeamsThreadLimit = {nullptr};
/ 'parallel' construct 'num_threads' clause value, if present and it is an / SPMD kernel. Value *MaxThreads = nullptr;
/ Total number of iterations of the SPMD or Generic-SPMD kernel or null if / it is a generic kernel. Value *LoopTripCount = nullptr; };
/ Data structure that contains the needed information to construct the / kernel args vector. struct TargetKernelArgs { / Number of arguments passed to the runtime library. unsigned NumTargetItems = 0; / Arguments passed to the runtime library TargetDataRTArgs RTArgs; / The number of iterations Value *NumIterations = nullptr; / The number of teams. ArrayRef<Value *> NumTeams; / The number of threads. ArrayRef<Value *> NumThreads; / The size of the dynamic shared memory. Value *DynCGGroupMem = nullptr; / True if the kernel has 'no wait' clause. bool HasNoWait = false;
Constructors for TargetKernelArgs. TargetKernelArgs() {} TargetKernelArgs(unsigned NumTargetItems, TargetDataRTArgs RTArgs, Value *NumIterations, ArrayRef<Value *> NumTeams, ArrayRef<Value *> NumThreads, Value *DynCGGroupMem, bool HasNoWait) : NumTargetItems(NumTargetItems), RTArgs(RTArgs), NumIterations(NumIterations), NumTeams(NumTeams), NumThreads(NumThreads), DynCGGroupMem(DynCGGroupMem), HasNoWait(HasNoWait) {} };
/ Create the kernel args vector used by emitTargetKernel. This function / creates various constant values that are used in the resulting args / vector. static void getKernelArgsVector(TargetKernelArgs &KernelArgs, IRBuilderBase &Builder, SmallVector<Value *> &ArgsVector);
/ Struct that keeps the information that should be kept throughout / a 'target data' region. class TargetDataInfo { / Set to true if device pointer information have to be obtained. bool RequiresDevicePointerInfo = false; / Set to true if Clang emits separate runtime calls for the beginning and / end of the region. These calls might have separate map type arrays. bool SeparateBeginEndCalls = false;
public: TargetDataRTArgs RTArgs;
SmallMapVector<const Value *, std::pair<Value *, Value *>, 4> DevicePtrInfoMap;
/ Indicate whether any user-defined mapper exists. bool HasMapper = false; / The total number of pointers passed to the runtime library. unsigned NumberOfPtrs = 0u;
bool EmitDebug = false;
/ Whether the target ... data directive has a nowait clause. bool HasNoWait = false;
explicit TargetDataInfo() {} explicit TargetDataInfo(bool RequiresDevicePointerInfo, bool SeparateBeginEndCalls) : RequiresDevicePointerInfo(RequiresDevicePointerInfo), SeparateBeginEndCalls(SeparateBeginEndCalls) {} / Clear information about the data arrays. void clearArrayInfo() { RTArgs = TargetDataRTArgs(); HasMapper = false; NumberOfPtrs = 0u; } / Return true if the current target data information has valid arrays. bool isValid() { return RTArgs.BasePointersArray && RTArgs.PointersArray && RTArgs.SizesArray && RTArgs.MapTypesArray && (!HasMapper || RTArgs.MappersArray) && NumberOfPtrs; } bool requiresDevicePointerInfo() { return RequiresDevicePointerInfo; } bool separateBeginEndCalls() { return SeparateBeginEndCalls; } };
enum class DeviceInfoTy { None, Pointer, Address }; using MapValuesArrayTy = SmallVector<Value *, 4>; using MapDeviceInfoArrayTy = SmallVector<DeviceInfoTy, 4>; using MapFlagsArrayTy = SmallVector<omp::OpenMPOffloadMappingFlags, 4>; using MapNamesArrayTy = SmallVector<Constant *, 4>; using MapDimArrayTy = SmallVector<uint64_t, 4>; using MapNonContiguousArrayTy = SmallVector<MapValuesArrayTy, 4>;
/ This structure contains combined information generated for mappable / clauses, including base pointers, pointers, sizes, map types, user-defined / mappers, and non-contiguous information. struct MapInfosTy { struct StructNonContiguousInfo { bool IsNonContiguous = false; MapDimArrayTy Dims; MapNonContiguousArrayTy Offsets; MapNonContiguousArrayTy Counts; MapNonContiguousArrayTy Strides; }; MapValuesArrayTy BasePointers; MapValuesArrayTy Pointers; MapDeviceInfoArrayTy DevicePointers; MapValuesArrayTy Sizes; MapFlagsArrayTy Types; MapNamesArrayTy Names; StructNonContiguousInfo NonContigInfo;
/ Append arrays in CurInfo. void append(MapInfosTy &CurInfo) { BasePointers.append(CurInfo.BasePointers.begin(), CurInfo.BasePointers.end()); Pointers.append(CurInfo.Pointers.begin(), CurInfo.Pointers.end()); DevicePointers.append(CurInfo.DevicePointers.begin(), CurInfo.DevicePointers.end()); Sizes.append(CurInfo.Sizes.begin(), CurInfo.Sizes.end()); Types.append(CurInfo.Types.begin(), CurInfo.Types.end()); Names.append(CurInfo.Names.begin(), CurInfo.Names.end()); NonContigInfo.Dims.append(CurInfo.NonContigInfo.Dims.begin(), CurInfo.NonContigInfo.Dims.end()); NonContigInfo.Offsets.append(CurInfo.NonContigInfo.Offsets.begin(), CurInfo.NonContigInfo.Offsets.end()); NonContigInfo.Counts.append(CurInfo.NonContigInfo.Counts.begin(), CurInfo.NonContigInfo.Counts.end()); NonContigInfo.Strides.append(CurInfo.NonContigInfo.Strides.begin(), CurInfo.NonContigInfo.Strides.end()); } };
/ Callback function type for functions emitting the host fallback code that / is executed when the kernel launch fails. It takes an insertion point as / parameter where the code should be emitted. It returns an insertion point / that points right after after the emitted code. using EmitFallbackCallbackTy = function_ref<InsertPointOrErrorTy(InsertPointTy)>;
/ Generate a target region entry call and host fallback call. / /
Parameters
Loc The location at which the request originated and is fulfilled. /
OutlinedFnID The ooulined function ID. /
EmitTargetCallFallbackCB Call back function to generate host / fallback code. /
Args Data structure holding information about the kernel arguments. /
DeviceID Identifier for the device via the 'device' clause. /
RTLoc Source location identifier /
AllocaIP The insertion point to be used for alloca instructions. InsertPointOrErrorTy emitKernelLaunch(const LocationDescription &Loc, Value *OutlinedFnID, EmitFallbackCallbackTy EmitTargetCallFallbackCB, TargetKernelArgs &Args, Value *DeviceID, Value *RTLoc, InsertPointTy AllocaIP);
/ Callback type for generating the bodies of device directives that require / outer target tasks (e.g. in case of having nowait or depend clauses). / /
Parameters
DeviceID The ID of the device on which the target region will / execute. /
RTLoc Source location identifier / \Param TargetTaskAllocaIP Insertion point for the alloca block of the / generated task. / /
Returns
an error, if any were triggered during execution. using TargetTaskBodyCallbackTy = function_ref<Error(Value *DeviceID, Value *RTLoc, IRBuilderBase::InsertPoint TargetTaskAllocaIP)>;
/ Generate a target-task for the target construct / /
Parameters
TaskBodyCB Callback to generate the actual body of the target task. /
DeviceID Identifier for the device via the 'device' clause. /
RTLoc Source location identifier /
AllocaIP The insertion point to be used for alloca instructions. /
Dependencies Vector of DependData objects holding information of / dependencies as specified by the 'depend' clause. /
HasNoWait True if the target construct had 'nowait' on it, false / otherwise InsertPointOrErrorTy emitTargetTask(TargetTaskBodyCallbackTy TaskBodyCB, Value *DeviceID, Value *RTLoc, OpenMPIRBuilder::InsertPointTy AllocaIP, const SmallVector<llvm::OpenMPIRBuilder::DependData> &Dependencies, bool HasNoWait);
/ Emit the arguments to be passed to the runtime library based on the / arrays of base pointers, pointers, sizes, map types, and mappers. If / ForEndCall, emit map types to be passed for the end of the region instead / of the beginning. void emitOffloadingArraysArgument(IRBuilderBase &Builder, OpenMPIRBuilder::TargetDataRTArgs &RTArgs, OpenMPIRBuilder::TargetDataInfo &Info, bool ForEndCall = false);
/ Emit an array of struct descriptors to be assigned to the offload args. void emitNonContiguousDescriptor(InsertPointTy AllocaIP, InsertPointTy CodeGenIP, MapInfosTy &CombinedInfo, TargetDataInfo &Info);
/ Emit the arrays used to pass the captures and map information to the / offloading runtime library. If there is no map or capture information, / return nullptr by reference. Accepts a reference to a MapInfosTy object / that contains information generated for mappable clauses, / including base pointers, pointers, sizes, map types, user-defined mappers. void emitOffloadingArrays(InsertPointTy AllocaIP, InsertPointTy CodeGenIP, MapInfosTy &CombinedInfo, TargetDataInfo &Info, bool IsNonContiguous = false, function_ref<void(unsigned int, Value *)> DeviceAddrCB = nullptr, function_ref<Value *(unsigned int)> CustomMapperCB = nullptr);
/ Allocates memory for and populates the arrays required for offloading / (offload_{baseptrs|ptrs|mappers|sizes|maptypes|mapnames}). Then, it / emits their base addresses as arguments to be passed to the runtime / library. In essence, this function is a combination of / emitOffloadingArrays and emitOffloadingArraysArgument and should arguably / be preferred by clients of OpenMPIRBuilder. void emitOffloadingArraysAndArgs(InsertPointTy AllocaIP, InsertPointTy CodeGenIP, TargetDataInfo &Info, TargetDataRTArgs &RTArgs, MapInfosTy &CombinedInfo, bool IsNonContiguous = false, bool ForEndCall = false, function_ref<void(unsigned int, Value *)> DeviceAddrCB = nullptr, function_ref<Value *(unsigned int)> CustomMapperCB = nullptr);
/ Creates offloading entry for the provided entry ID ID, address / Addr, size Size, and flags Flags. void createOffloadEntry(Constant *ID, Constant *Addr, uint64_t Size, int32_t Flags, GlobalValue::LinkageTypes, StringRef Name = "");
/ The kind of errors that can occur when emitting the offload entries and / metadata. enum EmitMetadataErrorKind { EMIT_MD_TARGET_REGION_ERROR, EMIT_MD_DECLARE_TARGET_ERROR, EMIT_MD_GLOBAL_VAR_LINK_ERROR };
/ Callback function type using EmitMetadataErrorReportFunctionTy = std::function<void(EmitMetadataErrorKind, TargetRegionEntryInfo)>;
Emit the offloading entries and metadata so that the device codegen side can easily figure out what to emit. The produced metadata looks like this:
!omp_offload.info = !{!1, ...}
We only generate metadata for function that contain target regions. void createOffloadEntriesAndInfoMetadata(EmitMetadataErrorReportFunctionTy &ErrorReportFunction);
public: / Generator for __kmpc_copyprivate / /
Parameters
Loc The source location description. /
BufSize Number of elements in the buffer. /
CpyBuf List of pointers to data to be copied. /
CpyFn function to call for copying data. /
DidIt flag variable; 1 for 'single' thread, 0 otherwise. / /
Returns
The insertion position after the CopyPrivate call.
InsertPointTy createCopyPrivate(const LocationDescription &Loc, llvm::Value *BufSize, llvm::Value *CpyBuf, llvm::Value *CpyFn, llvm::Value *DidIt);
/ Generator for 'omp single' / /
Parameters
Loc The source location description. /
BodyGenCB Callback that will generate the region code. /
FiniCB Callback to finalize variable copies. /
IsNowait If false, a barrier is emitted. /
CPVars copyprivate variables. /
CPFuncs copy functions to use for each copyprivate variable. / /
Returns
The insertion position after the single call. InsertPointOrErrorTy createSingle(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsNowait, ArrayRef<llvm::Value *> CPVars = {}, ArrayRef<llvm::Function *> CPFuncs = {});
/ Generator for 'omp master' / /
Parameters
Loc The insert and source location description. /
BodyGenCB Callback that will generate the region code. /
FiniCB Callback to finalize variable copies. / /
Returns
The insertion position after the master. InsertPointOrErrorTy createMaster(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB);
/ Generator for 'omp masked' / /
Parameters
Loc The insert and source location description. /
BodyGenCB Callback that will generate the region code. /
FiniCB Callback to finialize variable copies. / /
Returns
The insertion position after the masked. InsertPointOrErrorTy createMasked(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, Value *Filter);
/ Generator for 'omp critical' / /
Parameters
Loc The insert and source location description. /
BodyGenCB Callback that will generate the region body code. /
FiniCB Callback to finalize variable copies. /
CriticalName name of the lock used by the critical directive /
HintInst Hint Instruction for hint clause associated with critical / /
Returns
The insertion position after the critical. InsertPointOrErrorTy createCritical(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, StringRef CriticalName, Value *HintInst);
/ Generator for 'omp ordered depend (source | sink)' / /
Parameters
Loc The insert and source location description. /
AllocaIP The insertion point to be used for alloca instructions. /
NumLoops The number of loops in depend clause. /
StoreValues The value will be stored in vector address. /
Name The name of alloca instruction. /
IsDependSource If true, depend source; otherwise, depend sink. / /
Returns
The insertion position after the ordered. InsertPointTy createOrderedDepend(const LocationDescription &Loc, InsertPointTy AllocaIP, unsigned NumLoops, ArrayRef<llvm::Value *> StoreValues, const Twine &Name, bool IsDependSource);
/ Generator for 'omp ordered [threads | simd]' / /
Parameters
Loc The insert and source location description. /
BodyGenCB Callback that will generate the region code. /
FiniCB Callback to finalize variable copies. /
IsThreads If true, with threads clause or without clause; / otherwise, with simd clause; / /
Returns
The insertion position after the ordered. InsertPointOrErrorTy createOrderedThreadsSimd(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsThreads);
/ Generator for 'omp sections' / /
Parameters
Loc The insert and source location description. /
AllocaIP The insertion points to be used for alloca instructions. /
SectionCBs Callbacks that will generate body of each section. /
PrivCB Callback to copy a given variable (think copy constructor). /
FiniCB Callback to finalize variable copies. /
IsCancellable Flag to indicate a cancellable parallel region. /
IsNowait If true, barrier - to ensure all sections are executed / before moving forward will not be generated. /
Returns
The insertion position after the sections. InsertPointOrErrorTy createSections(const LocationDescription &Loc, InsertPointTy AllocaIP, ArrayRef<StorableBodyGenCallbackTy> SectionCBs, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, bool IsCancellable, bool IsNowait);
/ Generator for 'omp section' / /
Parameters
Loc The insert and source location description. /
BodyGenCB Callback that will generate the region body code. /
FiniCB Callback to finalize variable copies. /
Returns
The insertion position after the section. InsertPointOrErrorTy createSection(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB);
/ Generator for #omp teams / /
Parameters
Loc The location where the teams construct was encountered. /
BodyGenCB Callback that will generate the region code. /
NumTeamsLower Lower bound on number of teams. If this is nullptr, / it is as if lower bound is specified as equal to upperbound. If / this is non-null, then upperbound must also be non-null. /
NumTeamsUpper Upper bound on the number of teams. /
ThreadLimit on the number of threads that may participate in a / contention group created by each team. /
IfExpr is the integer argument value of the if condition on the / teams clause. InsertPointOrErrorTy createTeams(const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, Value *NumTeamsLower = nullptr, Value *NumTeamsUpper = nullptr, Value *ThreadLimit = nullptr, Value *IfExpr = nullptr);
/ Generate conditional branch and relevant BasicBlocks through which private / threads copy the 'copyin' variables from Master copy to threadprivate / copies. / /
Parameters
IP insertion block for copyin conditional /
MasterVarPtr a pointer to the master variable /
PrivateVarPtr a pointer to the threadprivate variable /
IntPtrTy Pointer size type /
BranchtoEnd Create a branch between the copyin.not.master blocks and copy.in.end block / /
Returns
The insertion point where copying operation to be emitted. InsertPointTy createCopyinClauseBlocks(InsertPointTy IP, Value *MasterAddr, Value *PrivateAddr, llvm::IntegerType *IntPtrTy, bool BranchtoEnd = true);
/ Create a runtime call for kmpc_Alloc / /
Parameters
Loc The insert and source location description. /
Size Size of allocated memory space /
Allocator Allocator information instruction /
Name Name of call Instruction for OMP_alloc / /
Returns
CallInst to the OMP_Alloc call CallInst *createOMPAlloc(const LocationDescription &Loc, Value *Size, Value *Allocator, std::string Name = "");
/ Create a runtime call for kmpc_free / /
Parameters
Loc The insert and source location description. /
Addr Address of memory space to be freed /
Allocator Allocator information instruction /
Name Name of call Instruction for OMP_Free / /
Returns
CallInst to the OMP_Free call CallInst *createOMPFree(const LocationDescription &Loc, Value *Addr, Value *Allocator, std::string Name = "");
/ Create a runtime call for kmpc_threadprivate_cached / /
Parameters
Loc The insert and source location description. /
Pointer pointer to data to be cached /
Size size of data to be cached /
Name Name of call Instruction for callinst / /
Returns
CallInst to the thread private cache call. CallInst *createCachedThreadPrivate(const LocationDescription &Loc, llvm::Value *Pointer, llvm::ConstantInt *Size, const llvm::Twine &Name = Twine(""));
/ Create a runtime call for __tgt_interop_init / /
Parameters
Loc The insert and source location description. /
InteropVar variable to be allocated /
InteropType type of interop operation /
Device devide to which offloading will occur /
NumDependences number of dependence variables /
DependenceAddress pointer to dependence variables /
HaveNowaitClause does nowait clause exist / /
Returns
CallInst to the __tgt_interop_init call CallInst *createOMPInteropInit(const LocationDescription &Loc, Value *InteropVar, omp::OMPInteropType InteropType, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause);
/ Create a runtime call for __tgt_interop_destroy / /
Parameters
Loc The insert and source location description. /
InteropVar variable to be allocated /
Device devide to which offloading will occur /
NumDependences number of dependence variables /
DependenceAddress pointer to dependence variables /
HaveNowaitClause does nowait clause exist / /
Returns
CallInst to the __tgt_interop_destroy call CallInst *createOMPInteropDestroy(const LocationDescription &Loc, Value *InteropVar, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause);
/ Create a runtime call for __tgt_interop_use / /
Parameters
Loc The insert and source location description. /
InteropVar variable to be allocated /
Device devide to which offloading will occur /
NumDependences number of dependence variables /
DependenceAddress pointer to dependence variables /
HaveNowaitClause does nowait clause exist / /
Returns
CallInst to the __tgt_interop_use call CallInst *createOMPInteropUse(const LocationDescription &Loc, Value *InteropVar, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause);
/ The omp target interface / / For more information about the usage of this interface, /
See also
openmp/libomptarget/deviceRTLs/common/include/target.h / /{
/ Create a runtime call for kmpc_target_init / /
Parameters
Loc The insert and source location description. /
Attrs Structure containing the default attributes, including / numbers of threads and teams to launch the kernel with. InsertPointTy createTargetInit(const LocationDescription &Loc, const llvm::OpenMPIRBuilder::TargetKernelDefaultAttrs &Attrs);
/ Create a runtime call for kmpc_target_deinit / /
Parameters
Loc The insert and source location description. /
TeamsReductionDataSize The maximal size of all the reduction data / for teams reduction. /
TeamsReductionBufferLength The number of elements (each of up to / TeamsReductionDataSize size), in the teams reduction buffer. void createTargetDeinit(const LocationDescription &Loc, int32_t TeamsReductionDataSize = 0, int32_t TeamsReductionBufferLength = 1024);
/}
/ Helpers to read/write kernel annotations from the IR. / /{
/ Read/write a bounds on threads for Kernel. Read will return 0 if none / is set. static std::pair<int32_t, int32_t> readThreadBoundsForKernel(const Triple &T, Function &Kernel); static void writeThreadBoundsForKernel(const Triple &T, Function &Kernel, int32_t LB, int32_t UB);
/ Read/write a bounds on teams for Kernel. Read will return 0 if none / is set. static std::pair<int32_t, int32_t> readTeamBoundsForKernel(const Triple &T, Function &Kernel); static void writeTeamsForKernel(const Triple &T, Function &Kernel, int32_t LB, int32_t UB); /}
private: Sets the function attributes expected for the outlined function void setOutlinedTargetRegionFunctionAttributes(Function *OutlinedFn);
Creates the function ID/Address for the given outlined function. In the case of an embedded device function the address of the function is used, in the case of a non-offload function a constant is created. Constant *createOutlinedFunctionID(Function *OutlinedFn, StringRef EntryFnIDName);
Creates the region entry address for the outlined function Constant *createTargetRegionEntryAddr(Function *OutlinedFunction, StringRef EntryFnName);
public: / Functions used to generate a function with the given name. using FunctionGenCallback = std::function<Expected<Function *>(StringRef FunctionName)>;
/ Create a unique name for the entry function using the source location / information of the current target region. The name will be something like: / / __omp_offloading_DD_FFFF_PP_lBB[_CC] / / where DD_FFFF is an ID unique to the file (device and file IDs), PP is the / mangled name of the function that encloses the target region and BB is the / line number of the target region. CC is a count added when more than one / region is located at the same location. / / If this target outline function is not an offload entry, we don't need to / register it. This may happen if it is guarded by an if clause that is / false at compile time, or no target archs have been specified. / / The created target region ID is used by the runtime library to identify / the current target region, so it only has to be unique and not / necessarily point to anything. It could be the pointer to the outlined / function that implements the target region, but we aren't using that so / that the compiler doesn't need to keep that, and could therefore inline / the host function if proven worthwhile during optimization. In the other / hand, if emitting code for the device, the ID has to be the function / address so that it can retrieved from the offloading entry and launched / by the runtime library. We also mark the outlined function to have / external linkage in case we are emitting code for the device, because / these functions will be entry points to the device. / /
Parameters
InfoManager The info manager keeping track of the offload entries /
EntryInfo The entry information about the function /
GenerateFunctionCallback The callback function to generate the code /
OutlinedFunction Pointer to the outlined function /
EntryFnIDName Name of the ID o be created Error emitTargetRegionFunction(TargetRegionEntryInfo &EntryInfo, FunctionGenCallback &GenerateFunctionCallback, bool IsOffloadEntry, Function *&OutlinedFn, Constant *&OutlinedFnID);
/ Registers the given function and sets up the attribtues of the function / Returns the FunctionID. / /
Parameters
InfoManager The info manager keeping track of the offload entries /
EntryInfo The entry information about the function /
OutlinedFunction Pointer to the outlined function /
EntryFnName Name of the outlined function /
EntryFnIDName Name of the ID o be created Constant *registerTargetRegionFunction(TargetRegionEntryInfo &EntryInfo, Function *OutlinedFunction, StringRef EntryFnName, StringRef EntryFnIDName);
/ Type of BodyGen to use for region codegen / / Priv: If device pointer privatization is required, emit the body of the / region here. It will have to be duplicated: with and without / privatization. / DupNoPriv: If we need device pointer privatization, we need / to emit the body of the region with no privatization in the 'else' branch / of the conditional. / NoPriv: If we don't require privatization of device / pointers, we emit the body in between the runtime calls. This avoids / duplicating the body code. enum BodyGenTy { Priv, DupNoPriv, NoPriv };
/ Callback type for creating the map infos for the kernel parameters. /
Parameters
CodeGenIP is the insertion point where code should be generated, / if any. using GenMapInfoCallbackTy = function_ref<MapInfosTy &(InsertPointTy CodeGenIP)>;
private: / Emit the array initialization or deletion portion for user-defined mapper / code generation. First, it evaluates whether an array section is mapped / and whether the MapType instructs to delete this section. If IsInit / is true, and MapType indicates to not delete this array, array / initialization code is generated. If IsInit is false, and MapType / indicates to delete this array, array deletion code is generated. void emitUDMapperArrayInitOrDel(Function *MapperFn, llvm::Value *MapperHandle, llvm::Value *Base, llvm::Value *Begin, llvm::Value *Size, llvm::Value *MapType, llvm::Value *MapName, TypeSize ElementSize, llvm::BasicBlock *ExitBB, bool IsInit);
public: / Emit the user-defined mapper function. The code generation follows the / pattern in the example below. /
/// void .omp_mapper.<type_name>.<mapper_id>.(void *rt_mapper_handle,
///                                           void *base, void *begin,
///                                           int64_t size, int64_t type,
///                                           void *name = nullptr) {
///   // Allocate space for an array section first or add a base/begin for
///   // pointer dereference.
///   if ((size > 1 || (base != begin && maptype.IsPtrAndObj)) &&
///       !maptype.IsDelete)
///     __tgt_push_mapper_component(rt_mapper_handle, base, begin,
///                                 size*sizeof(Ty), clearToFromMember(type));
///   // Map members.
///   for (unsigned i = 0; i < size; i++) {
///     // For each component specified by this mapper:
///     for (auto c : begin[i]->all_components) {
///       if (c.hasMapper())
///         (*c.Mapper())(rt_mapper_handle, c.arg_base, c.arg_begin,
///         c.arg_size,
///                       c.arg_type, c.arg_name);
///       else
///         __tgt_push_mapper_component(rt_mapper_handle, c.arg_base,
///                                     c.arg_begin, c.arg_size, c.arg_type,
///                                     c.arg_name);
///     }
///   }
///   // Delete the array section.
///   if (size > 1 && maptype.IsDelete)
///     __tgt_push_mapper_component(rt_mapper_handle, base, begin,
///                                 size*sizeof(Ty), clearToFromMember(type));
/// }
///
/ /
Parameters
PrivAndGenMapInfoCB Callback that privatizes code and populates the / MapInfos and returns. /
ElemTy DeclareMapper element type. /
FuncName Optional param to specify mapper function name. /
CustomMapperCB Optional callback to generate code related to / custom mappers. Function *emitUserDefinedMapper(function_ref<MapInfosTy &(InsertPointTy CodeGenIP, llvm::Value *PtrPHI, llvm::Value *BeginArg)> PrivAndGenMapInfoCB, llvm::Type *ElemTy, StringRef FuncName, function_ref<bool(unsigned int, Function **)> CustomMapperCB = nullptr);
/ Generator for 'omp target data' / /
Parameters
Loc The location where the target data construct was encountered. /
AllocaIP The insertion points to be used for alloca instructions. /
CodeGenIP The insertion point at which the target directive code / should be placed. /
IsBegin If true then emits begin mapper call otherwise emits / end mapper call. /
DeviceID Stores the DeviceID from the device clause. /
IfCond Value which corresponds to the if clause condition. /
Info Stores all information realted to the Target Data directive. /
GenMapInfoCB Callback that populates the MapInfos and returns. /
BodyGenCB Optional Callback to generate the region code. /
DeviceAddrCB Optional callback to generate code related to / use_device_ptr and use_device_addr. /
CustomMapperCB Optional callback to generate code related to / custom mappers. InsertPointOrErrorTy createTargetData(const LocationDescription &Loc, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Value *DeviceID, Value *IfCond, TargetDataInfo &Info, GenMapInfoCallbackTy GenMapInfoCB, omp::RuntimeFunction *MapperFunc = nullptr, function_ref<InsertPointOrErrorTy(InsertPointTy CodeGenIP, BodyGenTy BodyGenType)> BodyGenCB = nullptr, function_ref<void(unsigned int, Value *)> DeviceAddrCB = nullptr, function_ref<Value *(unsigned int)> CustomMapperCB = nullptr, Value *SrcLocInfo = nullptr);
using TargetBodyGenCallbackTy = function_ref<InsertPointOrErrorTy(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>;
using TargetGenArgAccessorsCallbackTy = function_ref<InsertPointOrErrorTy(Argument &Arg, Value *Input, Value *&RetVal, InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>;
/ Generator for 'omp target' / /
Parameters
Loc where the target data construct was encountered. /
IsOffloadEntry whether it is an offload entry. /
CodeGenIP The insertion point where the call to the outlined / function should be emitted. /
EntryInfo The entry information about the function. /
DefaultAttrs Structure containing the default attributes, including / numbers of threads and teams to launch the kernel with. /
RuntimeAttrs Structure containing the runtime numbers of threads / and teams to launch the kernel with. /
IfCond value of the if clause. /
Inputs The input values to the region that will be passed. / as arguments to the outlined function. /
BodyGenCB Callback that will generate the region code. /
ArgAccessorFuncCB Callback that will generate accessors / instructions for passed in target arguments where neccessary /
Dependencies A vector of DependData objects that carry / dependency information as passed in the depend clause /
HasNowait Whether the target construct has a nowait clause or / not. InsertPointOrErrorTy createTarget(const LocationDescription &Loc, bool IsOffloadEntry, OpenMPIRBuilder::InsertPointTy AllocaIP, OpenMPIRBuilder::InsertPointTy CodeGenIP, TargetRegionEntryInfo &EntryInfo, const TargetKernelDefaultAttrs &DefaultAttrs, const TargetKernelRuntimeAttrs &RuntimeAttrs, Value *IfCond, SmallVectorImpl<Value *> &Inputs, GenMapInfoCallbackTy GenMapInfoCB, TargetBodyGenCallbackTy BodyGenCB, TargetGenArgAccessorsCallbackTy ArgAccessorFuncCB, SmallVector<DependData> Dependencies = {}, bool HasNowait = false);
/ Returns __kmpc_for_static_init_* runtime function for the specified / size IVSize and sign IVSigned. Will create a distribute call / __kmpc_distribute_static_init* if IsGPUDistribute is set. FunctionCallee createForStaticInitFunction(unsigned IVSize, bool IVSigned, bool IsGPUDistribute);
/ Returns __kmpc_dispatch_init_* runtime function for the specified / size IVSize and sign IVSigned. FunctionCallee createDispatchInitFunction(unsigned IVSize, bool IVSigned);
/ Returns __kmpc_dispatch_next_* runtime function for the specified / size IVSize and sign IVSigned. FunctionCallee createDispatchNextFunction(unsigned IVSize, bool IVSigned);
/ Returns __kmpc_dispatch_fini_* runtime function for the specified / size IVSize and sign IVSigned. FunctionCallee createDispatchFiniFunction(unsigned IVSize, bool IVSigned);
/ Returns __kmpc_dispatch_deinit runtime function. FunctionCallee createDispatchDeinitFunction();
/ Declarations for LLVM-IR types (simple, array, function and structure) are / generated below. Their names are defined and used in OpenMPKinds.def. Here / we provide the declarations, the initializeTypes function will provide the / values. / /{ #define OMP_TYPE(VarName, InitValue)
#define OMP_ARRAY_TYPE(VarName, ElemTy, ArraySize) \ \
#define OMP_FUNCTION_TYPE(VarName, IsVarArg, ReturnType, ...) \ \
#define OMP_STRUCT_TYPE(VarName, StrName, ...) \ \
/}
private: / Create all simple and struct types exposed by the runtime and remember / the llvm::PointerTypes of them for easy access later. void initializeTypes(Module &M);
/ Common interface for generating entry calls for OMP Directives. / if the directive has a region/body, It will set the insertion / point to the body / /
Parameters
OMPD Directive to generate entry blocks for /
EntryCall Call to the entry OMP Runtime Function /
ExitBB block where the region ends. /
Conditional indicate if the entry call result will be used / to evaluate a conditional of whether a thread will execute / body code or not. / /
Returns
The insertion position in exit block InsertPointTy emitCommonDirectiveEntry(omp::Directive OMPD, Value *EntryCall, BasicBlock *ExitBB, bool Conditional = false);
/ Common interface to finalize the region / /
Parameters
OMPD Directive to generate exiting code for /
FinIP Insertion point for emitting Finalization code and exit call /
ExitCall Call to the ending OMP Runtime Function /
HasFinalize indicate if the directive will require finalization / and has a finalization callback in the stack that / should be called. / /
Returns
The insertion position in exit block InsertPointOrErrorTy emitCommonDirectiveExit(omp::Directive OMPD, InsertPointTy FinIP, Instruction *ExitCall, bool HasFinalize = true);
/ Common Interface to generate OMP inlined regions / /
Parameters
OMPD Directive to generate inlined region for /
EntryCall Call to the entry OMP Runtime Function /
ExitCall Call to the ending OMP Runtime Function /
BodyGenCB Body code generation callback. /
FiniCB Finalization Callback. Will be called when finalizing region /
Conditional indicate if the entry call result will be used / to evaluate a conditional of whether a thread will execute / body code or not. /
HasFinalize indicate if the directive will require finalization / and has a finalization callback in the stack that / should be called. /
IsCancellable if HasFinalize is set to true, indicate if the / the directive should be cancellable. /
Returns
The insertion point after the region InsertPointOrErrorTy EmitOMPInlinedRegion(omp::Directive OMPD, Instruction *EntryCall, Instruction *ExitCall, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool Conditional = false, bool HasFinalize = true, bool IsCancellable = false);
/ Get the platform-specific name separator. /
Parameters
Parts different parts of the final name that needs separation /
FirstSeparator First separator used between the initial two / parts of the name. /
Separator separator used between all of the rest consecutive / parts of the name static std::string getNameWithSeparators(ArrayRef<StringRef> Parts, StringRef FirstSeparator, StringRef Separator);
/ Returns corresponding lock object for the specified critical region / name. If the lock object does not exist it is created, otherwise the / reference to the existing copy is returned. /
Parameters
CriticalName Name of the critical region. / Value *getOMPCriticalRegionLock(StringRef CriticalName);
/ Callback type for Atomic Expression update / ex: /
/// unsigned x = 0;
/// #pragma omp atomic update
/// x = Expr(x_old);  //Expr() is any legal operation
///
/ /
Parameters
XOld the value of the atomic memory address to use for update /
IRB reference to the IRBuilder to use / /
Returns
Value to update X to. using AtomicUpdateCallbackTy = const function_ref<Expected<Value *>(Value *XOld, IRBuilder<> &IRB)>;
private: enum AtomicKind { Read, Write, Update, Capture, Compare };
/ Determine whether to emit flush or not / /
Parameters
Loc The insert and source location description. /
AO The required atomic ordering /
AK The OpenMP atomic operation kind used. / /
Returns
wether a flush was emitted or not bool checkAndEmitFlushAfterAtomic(const LocationDescription &Loc, AtomicOrdering AO, AtomicKind AK);
/ Emit atomic update for constructs: X = X BinOp Expr ,or X = Expr BinOp X / For complex Operations: X = UpdateOp(X) => CmpExch X, old_X, UpdateOp(X) / Only Scalar data types. / /
Parameters
AllocaIP The insertion point to be used for alloca / instructions. /
X The target atomic pointer to be updated /
XElemTy The element type of the atomic pointer. /
Expr The value to update X with. /
AO Atomic ordering of the generated atomic / instructions. /
RMWOp The binary operation used for update. If / operation is not supported by atomicRMW, / or belong to {FADD, FSUB, BAD_BINOP}. / Then a cmpExch based atomic will be generated. /
UpdateOp Code generator for complex expressions that cannot be / expressed through atomicrmw instruction. /
VolatileX true if X volatile? /
IsXBinopExpr true if X is Left H.S. in Right H.S. part of the / update expression, false otherwise. / (e.g. true for X = X BinOp Expr) / /
Returns
A pair of the old value of X before the update, and the value / used for the update. Expected<std::pair<Value *, Value *>> emitAtomicUpdate(InsertPointTy AllocaIP, Value *X, Type *XElemTy, Value *Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy &UpdateOp, bool VolatileX, bool IsXBinopExpr);
/ Emit the binary op. described by RMWOp, using Src1 and Src2 . / / \Return The instruction Value *emitRMWOpAsInstruction(Value *Src1, Value *Src2, AtomicRMWInst::BinOp RMWOp);
public: / a struct to pack relevant information while generating atomic Ops struct AtomicOpValue { Value *Var = nullptr; Type *ElemTy = nullptr; bool IsSigned = false; bool IsVolatile = false; };
/ Emit atomic Read for : V = X — Only Scalar data types. / /
Parameters
Loc The insert and source location description. /
X The target pointer to be atomically read /
V Memory address where to store atomically read / value /
AO Atomic ordering of the generated atomic / instructions. / /
Returns
Insertion point after generated atomic read IR. InsertPointTy createAtomicRead(const LocationDescription &Loc, AtomicOpValue &X, AtomicOpValue &V, AtomicOrdering AO);
/ Emit atomic write for : X = Expr — Only Scalar data types. / /
Parameters
Loc The insert and source location description. /
X The target pointer to be atomically written to /
Expr The value to store. /
AO Atomic ordering of the generated atomic / instructions. / /
Returns
Insertion point after generated atomic Write IR. InsertPointTy createAtomicWrite(const LocationDescription &Loc, AtomicOpValue &X, Value *Expr, AtomicOrdering AO);
/ Emit atomic update for constructs: X = X BinOp Expr ,or X = Expr BinOp X / For complex Operations: X = UpdateOp(X) => CmpExch X, old_X, UpdateOp(X) / Only Scalar data types. / /
Parameters
Loc The insert and source location description. /
AllocaIP The insertion point to be used for alloca instructions. /
X The target atomic pointer to be updated /
Expr The value to update X with. /
AO Atomic ordering of the generated atomic instructions. /
RMWOp The binary operation used for update. If operation / is not supported by atomicRMW, or belong to / {FADD, FSUB, BAD_BINOP}. Then a cmpExch based atomic will be generated.
UpdateOp Code generator for complex expressions that cannot be expressed through atomicrmw instruction.
IsXBinopExpr true if X is Left H.S. in Right H.S. part of the update expression, false otherwise. (e.g. true for X = X BinOp Expr)
Returns
Insertion point after generated atomic update IR.
Definition at line 8574 of file OMPIRBuilder.cpp.
References assert(), isConflictIP(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), LLVM_DEBUG, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, and X.
createBarrier()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createBarrier (const LocationDescription & Loc, omp::Directive Kind, bool ForceSimpleCall = false, bool CheckCancelFlag = true)
Emitter methods for OpenMP directives.
{ Generator for 'omp barrier'
Parameters
Loc The location where the barrier directive was encountered.
Kind The kind of directive that caused the barrier.
ForceSimpleCall Flag to force a simple (=non-cancellation) barrier.
CheckCancelFlag Flag to indicate a cancel barrier return value should be checked and acted upon.
ThreadID Optional parameter to pass in any existing ThreadID value.
Returns
The insertion point after the barrier.
Definition at line 1007 of file OMPIRBuilder.cpp.
Referenced by createCancel().
createCancel()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createCancel (const LocationDescription & Loc, Value * IfCondition, omp::Directive CanceledDirective)
Generator for 'omp cancel'.
Parameters
Loc The location where the directive was encountered.
IfCondition The evaluated 'if' clause expression, if any.
CanceledDirective The kind of directive that is cancled.
Returns
The insertion point after the barrier.
Definition at line 1060 of file OMPIRBuilder.cpp.
References createBarrier(), llvm_unreachable, llvm::SplitBlockAndInsertIfThenElse(), llvm::Error::success(), and llvm::Expected< T >::takeError().
createCanonicalLoop() [1/2]
Expected< CanonicalLoopInfo * > OpenMPIRBuilder::createCanonicalLoop (const LocationDescription & Loc, LoopBodyGenCallbackTy BodyGenCB, Value * Start, Value * Stop, Value * Step, bool IsSigned, bool InclusiveStop, InsertPointTy ComputeIP = {}, const Twine & Name = "loop")
Generator for the control flow structure of an OpenMP canonical loop.
Instead of a logical iteration space, this allows specifying user-defined loop counter values using increment, upper- and lower bounds. To disambiguate the terminology when counting downwards, instead of lower bounds we use Start for the loop counter value in the first body iteration.
Consider the following limitations:
A loop counter space over all integer values of its bit-width cannot be represented. E.g using uint8_t, its loop trip count of 256 cannot be stored into an 8 bit integer):
DO I = 0, 255, 1
Unsigned wrapping is only supported when wrapping only "once"; E.g. effectively counting downwards:
for (uint8_t i = 100u; i > 0; i += 127u)
TODO: May need to add additional parameters to represent:
Allow representing downcounting with unsigned integers.
Sign of the step and the comparison operator might disagree:
for (int i = 0; i < 42; i -= 1u)
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the loop body code.
Start Value of the loop counter for the first iterations.
Stop Loop counter values past this will stop the loop.
Step Loop counter increment after each iteration; negative means counting down.
IsSigned Whether Start, Stop and Step are signed integers.
InclusiveStop Whether Stop itself is a valid value for the loop counter.
ComputeIP Insertion point for instructions computing the trip count. Can be used to ensure the trip count is available at the outermost loop of a loop nest. If not set, defaults to the preheader of the generated loop.
Name Base name used to derive BB and instruction names.
Returns
An object representing the created control flow structure which can be used for loop-associated directives.
A Step of INT_MIN cannot not be normalized to a positive direction:
Definition at line 4055 of file OMPIRBuilder.cpp.
References assert(), llvm::cast(), createCanonicalLoop(), llvm::Value::getType(), llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::IRBuilderBase::InsertPoint::isSet(), and IV.
createCanonicalLoop() [2/2]
Expected< CanonicalLoopInfo * > OpenMPIRBuilder::createCanonicalLoop (const LocationDescription & Loc, LoopBodyGenCallbackTy BodyGenCB, Value * TripCount, const Twine & Name = "loop")
Generator for the control flow structure of an OpenMP canonical loop.
This generator operates on the logical iteration space of the loop, i.e. the caller only has to provide a loop trip count of the loop as defined by base language semantics. The trip count is interpreted as an unsigned integer. The induction variable passed to BodyGenCB will be of the same type and run from 0 to TripCount - 1. It is up to the callback to convert the logical iteration variable to the loop counter variable in the loop body.
Parameters
Loc The insert and source location description. The insert location can be between two instructions or the end of a degenerate block (e.g. a BB under construction).
BodyGenCB Callback that will generate the loop body code.
TripCount Number of iterations the loop body is executed.
Name Base name used to derive BB and instruction names.
Returns
An object representing the created control flow structure which can be used for loop-associated directives.
Definition at line 4025 of file OMPIRBuilder.cpp.
References After, llvm::CanonicalLoopInfo::assertOK(), createLoopSkeleton(), llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBodyIP(), llvm::CanonicalLoopInfo::getIndVar(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::CanonicalLoopInfo::getPreheader(), and llvm::spliceBB().
Referenced by createCanonicalLoop().
createFlush()
void OpenMPIRBuilder::createFlush (const LocationDescription & Loc)
Generator for 'omp flush'.
Parameters
Loc The location where the flush directive was encountered
Definition at line 1766 of file OMPIRBuilder.cpp.
createLoopSkeleton()
CanonicalLoopInfo * OpenMPIRBuilder::createLoopSkeleton (DebugLoc DL, Value * TripCount, Function * F, BasicBlock * PreInsertBefore, BasicBlock * PostInsertBefore, const Twine & Name = {})
Create the control flow structure of a canonical OpenMP loop.
The emitted loop will be disconnected, i.e. no edge to the loop's preheader and no terminator in the AfterBB. The OpenMPIRBuilder's IRBuilder location is not preserved.
Parameters
DL DebugLoc used for the instructions in the skeleton.
TripCount Value to be used for the trip count.
F Function in which to insert the BasicBlocks.
PreInsertBefore Where to insert BBs that execute before the body, typically the body itself.
PostInsertBefore Where to insert BBs that execute after the body.
Name Base name used to derive BB and instruction names.
Returns
The CanonicalLoopInfo that represents the emitted loop.
Definition at line 3958 of file OMPIRBuilder.cpp.
References llvm::PHINode::addIncoming(), After, llvm::CanonicalLoopInfo::assertOK(), Cond, llvm::BasicBlock::Create(), DL, F, llvm::Value::getType(), and llvm::Next.
Referenced by collapseLoops(), createCanonicalLoop(), and tileLoops().
createParallel()
OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createParallel (const LocationDescription & Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, Value * IfCondition, Value * NumThreads, omp::ProcBindKind ProcBind, bool IsCancellable)
Generator for 'omp parallel'.
Parameters
Loc The insert and source location description.
AllocaIP The insertion points to be used for alloca instructions.
BodyGenCB Callback that will generate the region code.
PrivCB Callback to copy a given variable (think copy constructor).
FiniCB Callback to finalize variable copies.
IfCondition The evaluated 'if' clause expression, if any.
NumThreads The evaluated 'num_threads' clause expression, if any.
ProcBind The value of the 'proc_bind' clause (see ProcBindKind).
IsCancellable Flag to indicate a cancellable parallel region.
Returns
The insertion position after the parallel.
Definition at line 1427 of file OMPIRBuilder.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::dyn_cast(), llvm::dyn_cast_if_present(), llvm::SetVector< T, Vector, Set, N >::empty(), llvm::IRBuilderBase::InsertPoint::getBlock(), llvm::CallBase::getCalledFunction(), llvm::FunctionCallee::getCallee(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), hostParallelCallback(), I, llvm::Instruction::insertAfter(), Int32, isConflictIP(), LLVM_DEBUG, Ptr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SetVector< T, Vector, Set, N >::remove_if(), llvm::Value::setName(), llvm::BasicBlock::splitBasicBlock(), llvm::SplitBlock(), llvm::Error::success(), llvm::Expected< T >::takeError(), targetParallelCallback(), and Uses.
createPlatformSpecificName()
std::string OpenMPIRBuilder::createPlatformSpecificName (ArrayRef< StringRef > Parts) const
Get the create a name using the platform specific separators.
Parameters
Parts parts of the final name that needs separation The created name has a first separator between the first and second part and a second separator between all other parts. E.g. with FirstSeparator "$" and Separator "." and parts: "p1", "p2", "p3", "p4" The resulting name is "p1$p2.p3.p4" The separators are retrieved from the OpenMPIRBuilderConfig.
Definition at line 7636 of file OMPIRBuilder.cpp.
Referenced by registerTargetGlobalVariable().
createTaskwait()
void OpenMPIRBuilder::createTaskwait (const LocationDescription & Loc)
Generator for 'omp taskwait'.
Parameters
Loc The location where the taskwait directive was encountered.
Definition at line 1785 of file OMPIRBuilder.cpp.
createTaskyield()
void OpenMPIRBuilder::createTaskyield (const LocationDescription & Loc)
Generator for 'omp taskyield'.
Parameters
Loc The location where the taskyield directive was encountered.
Definition at line 1803 of file OMPIRBuilder.cpp.
finalize()
void OpenMPIRBuilder::finalize (Function * Fn = nullptr)
Finalize the underlying module, e.g., by outlining regions.
Parameters
Fn The function to be finalized. If not used, all functions are finalized.
Definition at line 701 of file OMPIRBuilder.cpp.
References llvm::Function::addFnAttr(), assert(), llvm::SmallPtrSetImplBase::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::BasicBlock::empty(), llvm::BasicBlock::eraseFromParent(), llvm::errs(), F, llvm::Function::getEntryBlock(), llvm::Function::getFnAttribute(), llvm::Function::getFunction(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getNumUses(), llvm::Function::getReturnType(), llvm::BasicBlock::getUniqueSuccessor(), I, llvm::Type::isVoidTy(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), raiseUserConstantDataAllocasToEntryBlock(), llvm::BasicBlock::rbegin(), llvm::Function::removeFromParent(), and llvm::BasicBlock::rend().
getAddrOfDeclareTargetVar()
Constant * OpenMPIRBuilder::getAddrOfDeclareTargetVar (OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind CaptureClause, OffloadEntriesInfoManager::OMPTargetDeviceClauseKind DeviceClause, bool IsDeclaration, bool IsExternallyVisible, TargetRegionEntryInfo EntryInfo, StringRef MangledName, std::vector< GlobalVariable * > & GeneratedRefs, bool OpenMPSIMD, std::vector< Triple > TargetTriple, Type * LlvmPtrTy, std::function< Constant *()> GlobalInitializer, std::function< GlobalValue::LinkageTypes()> VariableLinkage)
Retrieve (or create if non-existent) the address of a declare target variable, used in conjunction with registerTargetGlobalVariable to create declare target global variables.
Parameters
CaptureClause - enumerator corresponding to the OpenMP capture clause used in conjunction with the variable being registered (link, to, enter).
DeviceClause - enumerator corresponding to the OpenMP capture clause used in conjunction with the variable being registered (nohost, host, any)
IsDeclaration - boolean stating if the variable being registered is a declaration-only and not a definition
IsExternallyVisible - boolean stating if the variable is externally visible
EntryInfo - Unique entry information for the value generated using getTargetEntryUniqueInfo, used to name generated pointer references to the declare target variable
MangledName - the mangled name of the variable being registered
GeneratedRefs - references generated by invocations of registerTargetGlobalVariable invoked from getAddrOfDeclareTargetVar, these are required by Clang for book keeping.
OpenMPSIMD - if OpenMP SIMD mode is currently enabled
TargetTriple - The OpenMP device target triple we are compiling for
LlvmPtrTy - The type of the variable we are generating or retrieving an address for
GlobalInitializer - a lambda function which creates a constant used for initializing a pointer reference to the variable in certain cases. If a nullptr is passed, it will default to utilising the original variable to initialize the pointer reference.
VariableLinkage - a lambda function which returns the variables linkage type, if unspecified and a nullptr is given, it will instead utilise the linkage stored on the existing global variable in the LLVMModule.
Definition at line 9475 of file OMPIRBuilder.cpp.
References llvm::cast(), llvm::TargetRegionEntryInfo::FileID, llvm::format(), getOrCreateInternalVariable(), llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryEnter, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryLink, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryTo, Ptr, registerTargetGlobalVariable(), and llvm::GlobalValue::WeakAnyLinkage.
Referenced by registerTargetGlobalVariable().
getFlagMemberOffset()
unsigned OpenMPIRBuilder::getFlagMemberOffset ()
Get the offset of the OMP_MAP_MEMBER_OF field.
Definition at line 9439 of file OMPIRBuilder.cpp.
References llvm::Offset, and llvm::omp::OMP_MAP_MEMBER_OF.
Referenced by getMemberOfFlag().
getMemberOfFlag()
omp::OpenMPOffloadMappingFlags OpenMPIRBuilder::getMemberOfFlag (unsigned Position)
Get OMP_MAP_MEMBER_OF flag with extra bits reserved based on the position given.
Parameters
Position - A value indicating the position of the parent of the member in the kernel argument structure, often retrieved by the parents position in the combined information vectors used to generate the structure itself. Multiple children (member's of) with the same parent will use the same returned member flag.
Definition at line 9450 of file OMPIRBuilder.cpp.
References getFlagMemberOffset().
getOpenMPDefaultSimdAlign()
unsigned OpenMPIRBuilder::getOpenMPDefaultSimdAlign (const Triple & TargetTriple, const StringMap< bool > & Features) static
Get the default alignment value for given target.
Parameters
TargetTriple Target triple
Features StringMap which describes extra CPU features
Definition at line 5326 of file OMPIRBuilder.cpp.
References llvm::Triple::isPPC(), llvm::Triple::isWasm(), llvm::Triple::isX86(), and llvm::StringMap< ValueTy, AllocatorTy >::lookup().
getOrCreateInternalVariable()
GlobalVariable * OpenMPIRBuilder::getOrCreateInternalVariable (Type * Ty, const StringRef & Name, unsigned AddressSpace = 0)
Gets (if variable with the given name already exist) or creates internal global variable with the specified Name.
The created variable has linkage CommonLinkage by default and is initialized by null value.
Parameters
Ty Type of the global variable. If it is exist already the type must be the same.
Name Name of the variable.
Definition at line 7642 of file OMPIRBuilder.cpp.
References assert(), llvm::GlobalValue::CommonLinkage, DL, llvm::Constant::getNullValue(), llvm::Module::getTargetTriple(), llvm::GlobalValue::InternalLinkage, and llvm::GlobalValue::NotThreadLocal.
Referenced by getAddrOfDeclareTargetVar(), and registerTargetGlobalVariable().
initialize()
void OpenMPIRBuilder::initialize ()
Initialize the internal state, this will put structures types and potentially other helpers into the underlying module.
Must be called before any other method and only once! This internal state includes types used in the OpenMPIRBuilder generated from OMPKinds.def.
Definition at line 676 of file OMPIRBuilder.cpp.
loadOffloadInfoMetadata() [1/2]
void OpenMPIRBuilder::loadOffloadInfoMetadata (Module & M)
Loads all the offload entries information from the host IR metadata.
This function is only meant to be used with device code generation.
Parameters
M Module to load Metadata info from. Module passed maybe loaded from bitcode file, i.e, different from OpenMPIRBuilder::M module.
Definition at line 9612 of file OMPIRBuilder.cpp.
References llvm::cast(), llvm_unreachable, ompOffloadInfoName, and llvm::NamedMDNode::operands().
Referenced by loadOffloadInfoMetadata().
loadOffloadInfoMetadata() [2/2]
void OpenMPIRBuilder::loadOffloadInfoMetadata (StringRef HostFilePath)
Loads all the offload entries information from the host IR metadata read from the file passed in as the HostFilePath argument.
This function is only meant to be used with device code generation.
Parameters
HostFilePath The path to the host IR file, used to load in offload metadata for the device, allowing host and device to maintain the same metadata mapping.
Definition at line 9658 of file OMPIRBuilder.cpp.
References llvm::StringRef::empty(), llvm::expectedToErrorOrAndEmitErrors(), llvm::MemoryBuffer::getFile(), loadOffloadInfoMetadata(), llvm::parseBitcodeFile(), and llvm::report_fatal_error().
popFinalizationCB()
void llvm::OpenMPIRBuilder::popFinalizationCB () inline
Pop the last finalization callback from the finalization stack.
NOTE: Temporary solution until Clang CG is gone.
Definition at line 568 of file OMPIRBuilder.h.
pushFinalizationCB()
void llvm::OpenMPIRBuilder::pushFinalizationCB (const FinalizationInfo & FI) inline
Push a finalization callback on the finalization stack.
NOTE: Temporary solution until Clang CG is gone.
Definition at line 561 of file OMPIRBuilder.h.
registerTargetGlobalVariable()
void OpenMPIRBuilder::registerTargetGlobalVariable (OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind CaptureClause, OffloadEntriesInfoManager::OMPTargetDeviceClauseKind DeviceClause, bool IsDeclaration, bool IsExternallyVisible, TargetRegionEntryInfo EntryInfo, StringRef MangledName, std::vector< GlobalVariable * > & GeneratedRefs, bool OpenMPSIMD, std::vector< Triple > TargetTriple, std::function< Constant *()> GlobalInitializer, std::function< GlobalValue::LinkageTypes()> VariableLinkage, Type * LlvmPtrTy, Constant * Addr)
Registers a target variable for device or host.
Parameters
CaptureClause - enumerator corresponding to the OpenMP capture clause used in conjunction with the variable being registered (link, to, enter).
DeviceClause - enumerator corresponding to the OpenMP capture clause used in conjunction with the variable being registered (nohost, host, any)
IsDeclaration - boolean stating if the variable being registered is a declaration-only and not a definition
IsExternallyVisible - boolean stating if the variable is externally visible
EntryInfo - Unique entry information for the value generated using getTargetEntryUniqueInfo, used to name generated pointer references to the declare target variable
MangledName - the mangled name of the variable being registered
GeneratedRefs - references generated by invocations of registerTargetGlobalVariable these are required by Clang for book keeping.
OpenMPSIMD - if OpenMP SIMD mode is currently enabled
TargetTriple - The OpenMP device target triple we are compiling for
GlobalInitializer - a lambda function which creates a constant used for initializing a pointer reference to the variable in certain cases. If a nullptr is passed, it will default to utilising the original variable to initialize the pointer reference.
VariableLinkage - a lambda function which returns the variables linkage type, if unspecified and a nullptr is given, it will instead utilise the linkage stored on the existing global variable in the LLVMModule.
LlvmPtrTy - The type of the variable we are generating or retrieving an address for
Addr - the original llvm value (addr) of the variable to be registered
Definition at line 9531 of file OMPIRBuilder.cpp.
References llvm::cast(), createPlatformSpecificName(), llvm::divideCeil(), getAddrOfDeclareTargetVar(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), getOrCreateInternalVariable(), llvm::Value::getType(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::OffloadEntriesInfoManager::OMPTargetDeviceClauseAny, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryEnter, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryLink, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryTo, and llvm::GlobalValue::WeakAnyLinkage.
Referenced by getAddrOfDeclareTargetVar().
setConfig()
void llvm::OpenMPIRBuilder::setConfig (OpenMPIRBuilderConfig C) inline
Definition at line 509 of file OMPIRBuilder.h.
References llvm::CallingConv::C.
setCorrectMemberOfFlag()
void OpenMPIRBuilder::setCorrectMemberOfFlag (omp::OpenMPOffloadMappingFlags & Flags, omp::OpenMPOffloadMappingFlags MemberOfFlag)
Given an initial flag set, this function modifies it to contain the passed in MemberOfFlag generated from the getMemberOfFlag function.
The results are dependent on the existing flag bits set in the original flag set.
Parameters
Flags - The original set of flags to be modified with the passed in MemberOfFlag.
MemberOfFlag - A modified OMP_MAP_MEMBER_OF flag, adjusted slightly based on the getMemberOfFlag which adjusts the flag bits based on the members position in its parent.
Definition at line 9456 of file OMPIRBuilder.cpp.
References llvm::omp::OMP_MAP_MEMBER_OF, and llvm::omp::OMP_MAP_PTR_AND_OBJ.
tileLoops()
std::vector< CanonicalLoopInfo * > OpenMPIRBuilder::tileLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, ArrayRef< Value * > TileSizes)
Tile a loop nest.
Tiles the loops of Loops by the tile sizes in TileSizes. Loops in / Loops must be perfectly nested, from outermost to innermost loop (i.e. Loops.front() is the outermost loop). The trip count llvm::Value of every loop and every tile sizes must be usable in the outermost loop's preheader. This implies that the loop nest is rectangular.
Example:
for (int i = 0; i < 15; ++i) // Canonical loop "i"
  for (int j = 0; j < 14; ++j) // Canonical loop "j"
      body(i, j);
After tiling with Loops={i,j} and TileSizes={5,7}, the loop is changed to
for (int i1 = 0; i1 < 3; ++i1)
  for (int j1 = 0; j1 < 2; ++j1)
    for (int i2 = 0; i2 < 5; ++i2)
      for (int j2 = 0; j2 < 7; ++j2)
        body(i1*3+i2, j1*3+j2);
The returned vector are the loops {i1,j1,i2,j2}. The loops i1 and j1 are referred to the floor, and the loops i2 and j2 are the tiles. Tiling also handles non-constant trip counts, non-constant tile sizes and trip counts that are not multiples of the tile size. In the latter case the tile loop of the last floor-loop iteration will have fewer iterations than specified as its tile size.
Parameters
DL Debug location for instructions added by tiling, for instance the floor- and tile trip count computation.
Loops Loops to tile. The CanonicalLoopInfo objects are invalidated by this method, i.e. should not used after tiling.
TileSizes For each loop in Loops, the tile size for that dimensions.
Returns
A list of generated loops. Contains twice as many loops as the input loop nest; the first half are the floor loops and the second half are the tile loops.
Definition at line 5015 of file OMPIRBuilder.cpp.
References assert(), llvm::Continue, createLoopSkeleton(), DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), F, llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getExit(), llvm::CanonicalLoopInfo::getIndVar(), llvm::CanonicalLoopInfo::getLatch(), llvm::BasicBlock::getParent(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), Loops, P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), redirectAllPredecessorsTo(), redirectTo(), removeUnusedBlocksFromParent(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::reserve(), Size, llvm::ArrayRef< T >::size(), and TileSize.
Referenced by unrollLoopPartial().
unrollLoopFull()
void OpenMPIRBuilder::unrollLoopFull (DebugLoc DL, CanonicalLoopInfo * Loop)
Fully unroll a loop.
Instead of unrolling the loop immediately (and duplicating its body instructions), it is deferred to LLVM's LoopUnrollPass by adding loop metadata.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Definition at line 5254 of file OMPIRBuilder.cpp.
References addLoopMetadata(), llvm::MDNode::get(), and llvm::MDString::get().
unrollLoopHeuristic()
void OpenMPIRBuilder::unrollLoopHeuristic (DebugLoc DL, CanonicalLoopInfo * Loop)
Fully or partially unroll a loop.
How the loop is unrolled is determined using LLVM's LoopUnrollPass.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Definition at line 5261 of file OMPIRBuilder.cpp.
References addLoopMetadata(), llvm::MDNode::get(), and llvm::MDString::get().
unrollLoopPartial()
void OpenMPIRBuilder::unrollLoopPartial (DebugLoc DL, CanonicalLoopInfo * Loop, int32_t Factor, CanonicalLoopInfo ** UnrolledCLI)
Partially unroll a loop.
The CanonicalLoopInfo of the unrolled loop for use with chained loop-associated directive can be requested using UnrolledCLI. Not needing the CanonicalLoopInfo allows more efficient code generation by deferring the actual unrolling to the LoopUnrollPass using loop metadata. A loop-associated directive applied to the unrolled loop needs to know the new trip count which means that if using a heuristically determined unroll factor (Factor == 0), that factor must be computed immediately. We are using the same logic as the LoopUnrollPass to derived the unroll factor, but which assumes that some canonicalization has taken place (e.g. Mem2Reg, LICM, GVN, Inlining, etc.). That is, the heuristic will perform better when the unrolled loop's CanonicalLoopInfo is not needed.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Factor The factor to unroll the loop by. A factor of 0 indicates that a heuristic should be used to determine the unroll-factor.
UnrolledCLI If non-null, receives the CanonicalLoopInfo of the partially unrolled loop. Otherwise, uses loop metadata to defer unrolling to the LoopUnrollPass.
Definition at line 5612 of file OMPIRBuilder.cpp.
References addLoopMetadata(), assert(), computeHeuristicUnrollFactor(), DL, F, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::Type::getInt32Ty(), llvm::Type::getIntegerBitWidth(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and tileLoops().
Member Data Documentation
ompOffloadInfoName
const std::string llvm::OpenMPIRBuilder::ompOffloadInfoName = "omp_offload.info"
OMP Offload Info Metadata name string.
Definition at line 3385 of file OMPIRBuilder.h.
Referenced by loadOffloadInfoMetadata().
The documentation for this class was generated from the following files:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h
lib/Frontend/OpenMP/OMPIRBuilder.cpp