LLVM: llvm::parallel::TaskGroup Class Reference
llvm::parallel::TaskGroup Class Reference
#include "llvm/Support/Parallel.h"
Public Member Functions
TaskGroup ()
~TaskGroup ()
void spawn (std::function< void()> f)
void sync () const
bool isParallel () const
Detailed Description
Definition at line 89 of file Parallel.h.
Constructor & Destructor Documentation
TaskGroup()
llvm::parallel::TaskGroup::TaskGroup ()
Definition at line 181 of file Parallel.cpp.
References llvm::parallel::strategy, and TaskGroup().
Referenced by TaskGroup().
~TaskGroup()
llvm::parallel::TaskGroup::~TaskGroup ()
Definition at line 188 of file Parallel.cpp.
References ~TaskGroup().
Referenced by ~TaskGroup().
Member Function Documentation
isParallel()
bool llvm::parallel::TaskGroup::isParallel () const inline
Definition at line 104 of file Parallel.h.
spawn()
void llvm::parallel::TaskGroup::spawn (std::function< void()> f)
Definition at line 194 of file Parallel.cpp.
References F, and spawn().
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::assignOffsets(), llvm::dwarf_linker::parallel::TypeUnit::createDIETree(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitCommonSectionsAndWriteCompileUnitsToTheOutput(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::parallelFor(), and spawn().
sync()
void llvm::parallel::TaskGroup::sync () const inline
Definition at line 102 of file Parallel.h.
The documentation for this class was generated from the following files:
include/llvm/Support/Parallel.h
lib/Support/Parallel.cpp