LLVM: llvm::LoongArchTargetStreamer Class Reference
llvm::LoongArchTargetStreamer Class Reference
#include "Target/LoongArch/MCTargetDesc/LoongArchTargetStreamer.h"
Public Member Functions
LoongArchTargetStreamer (MCStreamer &S)
void setTargetABI (LoongArchABI::ABI ABI)
LoongArchABI::ABI getTargetABI () const
virtual void emitDirectiveOptionPush ()
virtual void emitDirectiveOptionPop ()
virtual void emitDirectiveOptionRelax ()
virtual void emitDirectiveOptionNoRelax ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 18 of file LoongArchTargetStreamer.h.
Constructor & Destructor Documentation
LoongArchTargetStreamer()
LoongArchTargetStreamer::LoongArchTargetStreamer (MCStreamer & S)
Definition at line 17 of file LoongArchTargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::LoongArchTargetAsmStreamer::LoongArchTargetAsmStreamer(), and llvm::LoongArchTargetELFStreamer::LoongArchTargetELFStreamer().
Member Function Documentation
emitDirectiveOptionNoRelax()
void LoongArchTargetStreamer::emitDirectiveOptionNoRelax () virtual
Reimplemented in llvm::LoongArchTargetAsmStreamer, and llvm::LoongArchTargetELFStreamer.
Definition at line 29 of file LoongArchTargetStreamer.cpp.
emitDirectiveOptionPop()
void LoongArchTargetStreamer::emitDirectiveOptionPop () virtual
Reimplemented in llvm::LoongArchTargetAsmStreamer, and llvm::LoongArchTargetELFStreamer.
Definition at line 27 of file LoongArchTargetStreamer.cpp.
emitDirectiveOptionPush()
void LoongArchTargetStreamer::emitDirectiveOptionPush () virtual
Reimplemented in llvm::LoongArchTargetAsmStreamer, and llvm::LoongArchTargetELFStreamer.
Definition at line 26 of file LoongArchTargetStreamer.cpp.
emitDirectiveOptionRelax()
void LoongArchTargetStreamer::emitDirectiveOptionRelax () virtual
Reimplemented in llvm::LoongArchTargetAsmStreamer, and llvm::LoongArchTargetELFStreamer.
Definition at line 28 of file LoongArchTargetStreamer.cpp.
getTargetABI()
LoongArchABI::ABI llvm::LoongArchTargetStreamer::getTargetABI () const inline
Definition at line 24 of file LoongArchTargetStreamer.h.
Referenced by llvm::LoongArchTargetELFStreamer::finish().
setTargetABI()
void LoongArchTargetStreamer::setTargetABI (LoongArchABI::ABI ABI)
Definition at line 20 of file LoongArchTargetStreamer.cpp.
References llvm::LoongArchABI::ABI_Unknown, and assert().
Referenced by llvm::LoongArchTargetELFStreamer::LoongArchTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/MCTargetDesc/LoongArchTargetStreamer.h
lib/Target/LoongArch/MCTargetDesc/LoongArchTargetStreamer.cpp