LLVM: llvm::RecordRecTy Class Reference
llvm::RecordRecTy Class Reference final
'[classname]' - Type of record values that have zero or more superclasses.
#include "llvm/TableGen/Record.h"
Public Types
using const_record_iterator = const Record *const *
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Public Member Functions
RecordRecTy (const RecordRecTy &)=delete
RecordRecTy & operator= (const RecordRecTy &)=delete
void operator delete (void *p)
void Profile (FoldingSetNodeID &ID) const
ArrayRef< const Record * > getClasses () const
const_record_iterator classes_begin () const
const_record_iterator classes_end () const
std::string getAsString () const override
bool isSubClassOf (const Record *Class) const
bool typeIsConvertibleTo (const RecTy *RHS) const override
Return true if all values of 'this' type can be converted to the specified type.
bool typeIsA (const RecTy *RHS) const override
Return true if 'this' type is equal to or a subtype of RHS.
Public Member Functions inherited from llvm::RecTy
RecTy (RecTyKind K, RecordKeeper &RK)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
RecordKeeper & getRecordKeeper () const
Return the RecordKeeper that uniqued this Type.
void print (raw_ostream &OS) const
void dump () const
const ListRecTy * getListTy () const
Returns the type representing list<thistype>.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< RecordRecTy, const Record * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
TrailingObjects ()=default
TrailingObjects (const TrailingObjects &)=delete
TrailingObjects (TrailingObjects &&)=delete
TrailingObjects & operator= (const TrailingObjects &)=delete
TrailingObjects & operator= (TrailingObjects &&)=delete
Static Public Member Functions
static bool classof (const RecTy *RT)
static const RecordRecTy * get (RecordKeeper &RK, ArrayRef< const Record * > Classes)
Get the record type with the given non-redundant list of superclasses.
static const RecordRecTy * get (const Record *Class)
Static Public Member Functions inherited from llvm::TrailingObjects< RecordRecTy, const Record * >
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Friends
class Record
Detailed Description
'[classname]' - Type of record values that have zero or more superclasses.
The list of superclasses is non-redundant, i.e. only contains classes that are not the superclass of some other listed class.
Definition at line 231 of file Record.h.
Member Typedef Documentation
const_record_iterator
using llvm::RecordRecTy::const_record_iterator = const Record *const *
Definition at line 264 of file Record.h.
Constructor & Destructor Documentation
RecordRecTy()
llvm::RecordRecTy::RecordRecTy (const RecordRecTy &) delete
Member Function Documentation
classes_begin()
const_record_iterator llvm::RecordRecTy::classes_begin () const inline
Definition at line 266 of file Record.h.
References getClasses().
classes_end()
const_record_iterator llvm::RecordRecTy::classes_end () const inline
Definition at line 267 of file Record.h.
References getClasses().
classof()
static bool llvm::RecordRecTy::classof (const RecTy * RT) inline static
Definition at line 249 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::RecordRecTyKind, and llvm::RecTy::RecTy().
get() [1/2]
const RecordRecTy * RecordRecTy::get (const Record * Class) static
Definition at line 278 of file Record.cpp.
References assert(), get(), and Record.
get() [2/2]
const RecordRecTy * RecordRecTy::get (RecordKeeper & RK, ArrayRef< const Record * > Classes) static
Get the record type with the given non-redundant list of superclasses.
Definition at line 239 of file Record.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::detail::RecordKeeperImpl::Allocator, llvm::detail::RecordKeeperImpl::AnyRecord, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::FoldingSetImpl< Derived, T >::FindNodeOrInsertPos(), llvm::FoldingSetImpl< Derived, T >::InsertNode(), isSubClassOf(), ProfileRecordRecTy(), Record, llvm::detail::RecordKeeperImpl::RecordTypePool, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::sort(), and llvm::TrailingObjects< RecordRecTy, const Record * >::totalSizeToAlloc().
Referenced by get(), llvm::Record::getType(), and resolveRecordTypes().
getAsString()
std::string RecordRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 287 of file Record.cpp.
References llvm::First, getClasses(), and Record.
getClasses()
ArrayRef< const Record * > llvm::RecordRecTy::getClasses () const inline
Definition at line 260 of file Record.h.
References llvm::ArrayRef(), and llvm::TrailingObjects< RecordRecTy, const Record * >::getTrailingObjects().
Referenced by classes_begin(), classes_end(), getAsString(), isSubClassOf(), and Profile().
isSubClassOf()
bool RecordRecTy::isSubClassOf (const Record * Class) const
Definition at line 303 of file Record.cpp.
References llvm::any_of(), getClasses(), llvm::Record::isSubClassOf(), and Record.
Referenced by get().
operator delete()
void llvm::RecordRecTy::operator delete (void * p) inline
Definition at line 247 of file Record.h.
operator=()
RecordRecTy & llvm::RecordRecTy::operator= (const RecordRecTy &) delete
Profile()
void RecordRecTy::Profile (FoldingSetNodeID & ID) const
Definition at line 283 of file Record.cpp.
References getClasses(), and ProfileRecordRecTy().
typeIsA()
bool RecordRecTy::typeIsA (const RecTy * RHS) const override virtual
Return true if 'this' type is equal to or a subtype of RHS.
For example, a bit set is not an int, but they are convertible.
Reimplemented from llvm::RecTy.
Definition at line 322 of file Record.cpp.
References llvm::RecTy::RecTy(), and typeIsConvertibleTo().
Referenced by llvm::ExistsOpInit::Fold().
typeIsConvertibleTo()
bool RecordRecTy::typeIsConvertibleTo (const RecTy * RHS) const override virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 309 of file Record.cpp.
References llvm::all_of(), llvm::dyn_cast(), Record, and llvm::RecTy::RecTy().
Referenced by typeIsA().
Friends And Related Symbol Documentation
Record
friend class Record friend
Definition at line 234 of file Record.h.
References Record, llvm::RecTy::RecordRecTyKind, and llvm::RecTy::RecTy().
Referenced by get(), get(), getAsString(), isSubClassOf(), Record, and typeIsConvertibleTo().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp