LLVM: llvm::GenericCycleInfoCompute< ContextT > Class Template Reference
llvm::GenericCycleInfoCompute< ContextT > Class Template Reference
Helper class for computing cycle information.
#include "llvm/ADT/GenericCycleImpl.h"
Public Member Functions
GenericCycleInfoCompute (CycleInfoT &Info)
void run (BlockT *EntryBlock)
Main function of the cycle info computations.
Static Public Member Functions
static void updateDepth (CycleT *SubTree)
Recompute depth values of SubTree and all descendants.
Detailed Description
template<typename ContextT>
class llvm::GenericCycleInfoCompute< ContextT >
Helper class for computing cycle information.
Definition at line 228 of file GenericCycleImpl.h.
Constructor & Destructor Documentation
GenericCycleInfoCompute()
template<typename ContextT> llvm::GenericCycleInfoCompute< ContextT >::GenericCycleInfoCompute (CycleInfoT & Info) inline
Definition at line 258 of file GenericCycleImpl.h.
Member Function Documentation
run()
template<typename ContextT> void llvm::GenericCycleInfoCompute< ContextT >::run (BlockT * EntryBlock)
Main function of the cycle info computations.
Definition at line 332 of file GenericCycleImpl.h.
References assert(), llvm::Block, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::errs(), llvm::is_contained(), LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), and updateDepth().
Referenced by llvm::GenericCycleInfo< ContextT >::compute().
updateDepth()
template<typename ContextT> void llvm::GenericCycleInfoCompute< ContextT >::updateDepth (CycleT * SubTree) static
Recompute depth values of SubTree and all descendants.
Definition at line 438 of file GenericCycleImpl.h.
References llvm::depth_first().
Referenced by run().
The documentation for this class was generated from the following file:
include/llvm/ADT/GenericCycleImpl.h