LLVM: llvm::GenericSchedulerBase Class Reference
llvm::GenericSchedulerBase Class Reference
Base class for GenericScheduler.
#include "llvm/CodeGen/MachineScheduler.h"
Classes
struct CandPolicy
Policy for scheduling the next instruction in the candidate's zone.
struct SchedCandidate
Store the state used by GenericScheduler heuristics, required for the lifetime of one invocation of pickNode().
struct SchedResourceDelta
Status of an instruction's critical resource consumption.
Public Types
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NextDefUse ,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Protected Member Functions
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
MachineSchedPolicy getPolicy () const override
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
MachineSchedPolicy RegionPolicy
SchedRemainder Rem
Additional Inherited Members
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual SUnit * pickNode (bool &IsTopNode)=0
Pick the next node to schedule, or return NULL.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
virtual void releaseTopNode (SUnit *SU)=0
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
virtual void releaseBottomNode (SUnit *SU)=0
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Detailed Description
Base class for GenericScheduler.
This class maintains information about scheduling candidates based on TargetSchedModel making it easy to implement heuristics for either preRA or postRA scheduling.
Definition at line 1076 of file MachineScheduler.h.
Member Enumeration Documentation
CandReason
enum llvm::GenericSchedulerBase::CandReason : uint8_t
Represent the type of SchedCandidate found within a single queue.
pickNodeBidirectional depends on these listed by decreasing priority.
Enumerator
NoCand
Only1
PhysReg
RegExcess
RegCritical
Stall
Cluster
Weak
RegMax
ResourceReduce
ResourceDemand
BotHeightReduce
BotPathReduce
TopDepthReduce
TopPathReduce
NextDefUse
NodeOrder
Definition at line 1080 of file MachineScheduler.h.
Constructor & Destructor Documentation
GenericSchedulerBase()
llvm::GenericSchedulerBase::GenericSchedulerBase (const MachineSchedContext * C) inline protected
Definition at line 1183 of file MachineScheduler.h.
References llvm::CallingConv::C, and Context.
Referenced by llvm::GenericScheduler::GenericScheduler(), and llvm::PostGenericScheduler::PostGenericScheduler().
Member Function Documentation
getPolicy()
MachineSchedPolicy llvm::GenericSchedulerBase::getPolicy () const inline override protected virtual
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1188 of file MachineScheduler.h.
References RegionPolicy.
getReasonStr()
const char * GenericSchedulerBase::getReasonStr (GenericSchedulerBase::CandReason Reason) static
Definition at line 3089 of file MachineScheduler.cpp.
References BotHeightReduce, BotPathReduce, Cluster, llvm_unreachable, NextDefUse, NoCand, NodeOrder, Only1, PhysReg, RegCritical, RegExcess, RegMax, ResourceDemand, ResourceReduce, Stall, TopDepthReduce, TopPathReduce, and Weak.
Referenced by traceCandidate(), and tracePick().
setPolicy()
void GenericSchedulerBase::setPolicy (CandPolicy & Policy, bool IsPostRA, SchedBoundary & CurrZone, SchedBoundary * OtherZone) protected
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
Definition at line 3034 of file MachineScheduler.cpp.
References llvm::SchedBoundary::Available, checkResourceLimit(), computeRemLatency(), llvm::dbgs(), llvm::GenericSchedulerBase::CandPolicy::DemandResIdx, llvm::SchedBoundary::getCurrCycle(), llvm::ReadyQueue::getName(), llvm::SchedBoundary::getOtherResourceCount(), llvm::SchedBoundary::getZoneCritResIdx(), if(), llvm::SchedBoundary::isResourceLimited(), LLVM_DEBUG, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::CandPolicy::ReduceResIdx, Rem, and SchedModel.
Referenced by llvm::PostGenericScheduler::pickNode(), llvm::GCNSchedStrategy::pickNodeBidirectional(), llvm::GenericScheduler::pickNodeBidirectional(), and llvm::PostGenericScheduler::pickNodeBidirectional().
traceCandidate()
void GenericSchedulerBase::traceCandidate (const SchedCandidate & Cand) protected
Definition at line 3113 of file MachineScheduler.cpp.
References BotHeightReduce, BotPathReduce, llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::dbgs(), llvm::GenericSchedulerBase::CandPolicy::DemandResIdx, llvm::RegPressureDelta::Excess, llvm::SUnit::getDepth(), llvm::SUnit::getHeight(), getReasonStr(), llvm::Latency, llvm::SUnit::NodeNum, P, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceResIdx, RegCritical, RegExcess, RegMax, ResourceDemand, ResourceReduce, llvm::GenericSchedulerBase::SchedCandidate::RPDelta, SchedModel, llvm::GenericSchedulerBase::SchedCandidate::SU, TopDepthReduce, TopPathReduce, and TRI.
Referenced by llvm::GCNSchedStrategy::pickNodeBidirectional(), llvm::GenericScheduler::pickNodeBidirectional(), llvm::PostGenericScheduler::pickNodeBidirectional(), llvm::GCNSchedStrategy::pickNodeFromQueue(), llvm::GenericScheduler::pickNodeFromQueue(), and llvm::PostGenericScheduler::pickNodeFromQueue().
Member Data Documentation
Context
const MachineSchedContext* llvm::GenericSchedulerBase::Context protected
Definition at line 1175 of file MachineScheduler.h.
Referenced by GenericSchedulerBase(), llvm::GCNSchedStrategy::initialize(), and llvm::GenericScheduler::initPolicy().
RegionPolicy
MachineSchedPolicy llvm::GenericSchedulerBase::RegionPolicy protected
Definition at line 1179 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::dumpPolicy(), getPolicy(), llvm::GenericScheduler::initialize(), llvm::GenericScheduler::initPolicy(), llvm::PostGenericScheduler::initPolicy(), llvm::GCNSchedStrategy::pickNode(), llvm::GenericScheduler::pickNode(), llvm::PostGenericScheduler::pickNode(), llvm::GenericScheduler::shouldTrackLaneMasks(), llvm::GenericScheduler::shouldTrackPressure(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::GenericScheduler::tryCandidate(), and llvm::PPCPreRASchedStrategy::tryCandidate().
Rem
SchedRemainder llvm::GenericSchedulerBase::Rem protected
Definition at line 1181 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::checkAcyclicLatency(), llvm::GenericScheduler::initialize(), llvm::PostGenericScheduler::initialize(), llvm::GenericScheduler::registerRoots(), llvm::PostGenericScheduler::registerRoots(), setPolicy(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::GenericScheduler::tryCandidate(), and llvm::PPCPreRASchedStrategy::tryCandidate().
SchedModel
const TargetSchedModel* llvm::GenericSchedulerBase::SchedModel = nullptr protected
Definition at line 1176 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::checkAcyclicLatency(), llvm::GenericScheduler::initialize(), llvm::PostGenericScheduler::initialize(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::GCNSchedStrategy::pickNodeFromQueue(), llvm::GenericScheduler::pickNodeFromQueue(), llvm::PostGenericScheduler::pickNodeFromQueue(), llvm::GenericScheduler::registerRoots(), setPolicy(), traceCandidate(), llvm::GCNMaxILPSchedStrategy::tryCandidate(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::GenericScheduler::tryCandidate(), and llvm::PPCPreRASchedStrategy::tryCandidate().
TRI
const TargetRegisterInfo* llvm::GenericSchedulerBase::TRI = nullptr protected
Definition at line 1177 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::initCandidate(), llvm::GenericScheduler::initialize(), llvm::PostGenericScheduler::initialize(), llvm::GCNSchedStrategy::pickNodeFromQueue(), traceCandidate(), llvm::GCNMaxILPSchedStrategy::tryCandidate(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::GenericScheduler::tryCandidate(), and llvm::PPCPreRASchedStrategy::tryCandidate().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp