LLVM: llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64 Class Reference
llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64 Class Reference
#include "llvm/ProfileData/MemProfYAML.h"
Public Member Functions
FrameWithHex64 (IO &)
FrameWithHex64 (IO &, const memprof::Frame &F)
memprof::Frame denormalize (IO &)
Public Attributes
memprof::GUIDHex64 Function = 0
decltype(memprof::Frame::LineOffset) LineOffset = 0
decltype(memprof::Frame::Column) Column = 0
decltype(memprof::Frame::IsInlineFrame) IsInlineFrame = false
Detailed Description
Definition at line 60 of file MemProfYAML.h.
Constructor & Destructor Documentation
FrameWithHex64() [1/2]
llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::FrameWithHex64 (IO &) inline
Definition at line 62 of file MemProfYAML.h.
FrameWithHex64() [2/2]
llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::FrameWithHex64 (IO & , const memprof::Frame & F) inline
Definition at line 63 of file MemProfYAML.h.
References Column, F, Function, IsInlineFrame, and LineOffset.
Member Function Documentation
denormalize()
memprof::Frame llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::denormalize (IO &) inline
Definition at line 66 of file MemProfYAML.h.
References Column, Function, IsInlineFrame, and LineOffset.
Member Data Documentation
Column
decltype(memprof::Frame::Column) llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::Column = 0
Definition at line 74 of file MemProfYAML.h.
Referenced by denormalize(), and FrameWithHex64().
Function
memprof::GUIDHex64 llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::Function = 0
Definition at line 70 of file MemProfYAML.h.
Referenced by denormalize(), and FrameWithHex64().
IsInlineFrame
decltype(memprof::Frame::IsInlineFrame) llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::IsInlineFrame = false
Definition at line 75 of file MemProfYAML.h.
Referenced by denormalize(), and FrameWithHex64().
LineOffset
decltype(memprof::Frame::LineOffset) llvm::yaml::MappingTraits< memprof::Frame >::FrameWithHex64::LineOffset = 0
Definition at line 73 of file MemProfYAML.h.
Referenced by denormalize(), and FrameWithHex64().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProfYAML.h