LLVM: llvm::sandboxir::BottomUpVec Class Reference
llvm::sandboxir::BottomUpVec Class Reference final
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Passes/BottomUpVec.h"
Public Member Functions
BottomUpVec (StringRef Pipeline)
bool runOnFunction (Function &F, const Analyses &A) final
\Returns true if it modifies F.
void printPipeline (raw_ostream &OS) const final
Similar to print() but adds a newline. Used for testing.
Public Member Functions inherited from llvm::sandboxir::FunctionPass
FunctionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
virtual LLVM_DUMP_METHOD void dump () const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
Definition at line 26 of file BottomUpVec.h.
Constructor & Destructor Documentation
BottomUpVec()
llvm::sandboxir::BottomUpVec::BottomUpVec (StringRef Pipeline)
Definition at line 39 of file BottomUpVec.cpp.
References llvm::sandboxir::FunctionPass::FunctionPass().
Member Function Documentation
printPipeline()
void llvm::sandboxir::BottomUpVec::printPipeline (raw_ostream & OS) const inline final virtual
Similar to print() but adds a newline. Used for testing.
Reimplemented from llvm::sandboxir::Pass.
Definition at line 64 of file BottomUpVec.h.
References llvm::sandboxir::Pass::getName().
runOnFunction()
bool llvm::sandboxir::BottomUpVec::runOnFunction (Function & F, const Analyses & A) final virtual
\Returns true if it modifies F.
Implements llvm::sandboxir::FunctionPass.
Definition at line 397 of file BottomUpVec.cpp.
References A(), llvm::AllowNonPow2, assert(), DL, F, llvm::sandboxir::VecUtils::getElementType(), llvm::sandboxir::Utils::getExpectedType(), llvm::sandboxir::VecUtils::getFloorPowerOf2(), llvm::sandboxir::Utils::getNumBits(), llvm::Offset, llvm::OverrideVecRegBits, and llvm::TargetTransformInfo::RGK_FixedWidthVector.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Passes/BottomUpVec.h
lib/Transforms/Vectorize/SandboxVectorizer/Passes/BottomUpVec.cpp