LLVM: llvm::VPDerivedIVRecipe Class Reference
llvm::VPDerivedIVRecipe Class Reference
A recipe for converting the input value IV value to the corresponding value of an IV with different start and step values, using Start + IV * Step.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPDerivedIVRecipe (const InductionDescriptor &IndDesc, VPValue *Start, VPCanonicalIVPHIRecipe *CanonicalIV, VPValue *Step, const Twine &Name="")
VPDerivedIVRecipe (InductionDescriptor::InductionKind Kind, const FPMathOperator *FPBinOp, VPValue *Start, VPValue *IV, VPValue *Step, const Twine &Name="")
~VPDerivedIVRecipe () override=default
VPDerivedIVRecipe * clone () override
Clone the current recipe.
void execute (VPTransformState &State) override
Generate the transformed value of the induction at offset StartValue (1.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this VPDerivedIVRecipe.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
Type * getScalarType () const
VPValue * getStartValue () const
VPValue * getStepValue () const
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
Public Member Functions inherited from llvm::VPSingleDefRecipe
template<typename IterT>
VPSingleDefRecipe (const unsigned char SC, IterT Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT>
VPSingleDefRecipe (const unsigned char SC, IterT Operands, Value *UV, DebugLoc DL={})
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
LLVM_DUMP_METHOD void dump () const
Print this VPSingleDefRecipe to dbgs() (for debugging).
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT>
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop region.
void setUnderlyingValue (Value *Val)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
VPUser (std::initializer_list< VPValue * > Operands)
template<typename IterT>
VPUser (iterator_range< IterT > Operands)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A recipe for converting the input value IV value to the corresponding value of an IV with different start and step values, using Start + IV * Step.
Definition at line 3413 of file VPlan.h.
Constructor & Destructor Documentation
VPDerivedIVRecipe() [1/2]
llvm::VPDerivedIVRecipe::VPDerivedIVRecipe (const InductionDescriptor & IndDesc, VPValue * Start, VPCanonicalIVPHIRecipe * CanonicalIV, VPValue * Step, const Twine & Name = "") inline
Definition at line 3424 of file VPlan.h.
References llvm::dyn_cast_or_null(), and VPDerivedIVRecipe().
Referenced by clone(), and VPDerivedIVRecipe().
VPDerivedIVRecipe() [2/2]
llvm::VPDerivedIVRecipe::VPDerivedIVRecipe (InductionDescriptor::InductionKind Kind, const FPMathOperator * FPBinOp, VPValue * Start, VPValue * IV, VPValue * Step, const Twine & Name = "") inline
Definition at line 3432 of file VPlan.h.
References IV, and llvm::VPSingleDefRecipe::VPSingleDefRecipe().
~VPDerivedIVRecipe()
llvm::VPDerivedIVRecipe::~VPDerivedIVRecipe () override default
Member Function Documentation
clone()
VPDerivedIVRecipe * llvm::VPDerivedIVRecipe::clone () inline override virtual
Clone the current recipe.
Implements llvm::VPSingleDefRecipe.
Definition at line 3440 of file VPlan.h.
References llvm::VPUser::getOperand(), getStartValue(), getStepValue(), and VPDerivedIVRecipe().
computeCost()
InstructionCost llvm::VPDerivedIVRecipe::computeCost (ElementCount VF, VPCostContext & Ctx) const inline override virtual
Return the cost of this VPDerivedIVRecipe.
Reimplemented from llvm::VPRecipeBase.
Definition at line 3452 of file VPlan.h.
execute()
void VPDerivedIVRecipe::execute (VPTransformState & State) override virtual
Generate the transformed value of the induction at offset StartValue (1.
operand) + IV (2. operand) * StepValue (3, operand).
Implements llvm::VPRecipeBase.
Definition at line 9815 of file LoopVectorize.cpp.
References assert(), llvm::cast_if_present(), emitTransformedIndex(), llvm::VPValue::getLiveInIRValue(), llvm::VPUser::getOperand(), llvm::VPRecipeBase::getParent(), getStartValue(), getStepValue(), and llvm::Value::setName().
getScalarType()
Type * llvm::VPDerivedIVRecipe::getScalarType () const inline
Definition at line 3464 of file VPlan.h.
References llvm::VPValue::getLiveInIRValue(), getStartValue(), and llvm::Value::getType().
getStartValue()
VPValue * llvm::VPDerivedIVRecipe::getStartValue () const inline
Definition at line 3468 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by clone(), execute(), getScalarType(), and print().
getStepValue()
VPValue * llvm::VPDerivedIVRecipe::getStepValue () const inline
Definition at line 3469 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by clone(), execute(), and print().
onlyFirstLaneUsed()
bool llvm::VPDerivedIVRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPUser.
Definition at line 3472 of file VPlan.h.
References assert(), llvm::is_contained(), and llvm::VPUser::operands().
print()
void VPDerivedIVRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 1886 of file VPlanRecipes.cpp.
References llvm::VPUser::getOperand(), getStartValue(), getStepValue(), and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlanRecipes.cpp