LLVM: llvm::orc::UnwindInfoRegistrationPlugin Class Reference
llvm::orc::UnwindInfoRegistrationPlugin Class Reference
#include "llvm/ExecutionEngine/Orc/UnwindInfoRegistrationPlugin.h"
Public Member Functions
UnwindInfoRegistrationPlugin (ExecutionSession &ES, ExecutorAddr Register, ExecutorAddr Deregister)
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &PassConfig) override
Error notifyEmitted (MaterializationResponsibility &MR) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::LinkGraphLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
Static Public Member Functions
static Expected< std::shared_ptr< UnwindInfoRegistrationPlugin > > Create (ExecutionSession &ES, ExecutorAddr Register, ExecutorAddr Deregister)
static Expected< std::shared_ptr< UnwindInfoRegistrationPlugin > > Create (ExecutionSession &ES)
Detailed Description
Definition at line 20 of file UnwindInfoRegistrationPlugin.h.
Constructor & Destructor Documentation
UnwindInfoRegistrationPlugin()
llvm::orc::UnwindInfoRegistrationPlugin::UnwindInfoRegistrationPlugin (ExecutionSession & ES, ExecutorAddr Register, ExecutorAddr Deregister) inline
Definition at line 22 of file UnwindInfoRegistrationPlugin.h.
Member Function Documentation
Create() [1/2]
Expected< std::shared_ptr< UnwindInfoRegistrationPlugin > > llvm::orc::UnwindInfoRegistrationPlugin::Create (ExecutionSession & ES) static
Definition at line 24 of file UnwindInfoRegistrationPlugin.cpp.
Create() [2/2]
static Expected< std::shared_ptr< UnwindInfoRegistrationPlugin > > llvm::orc::UnwindInfoRegistrationPlugin::Create (ExecutionSession & ES, ExecutorAddr Register, ExecutorAddr Deregister) static
References G.
Referenced by llvm::orc::LLJIT::setUpGenericLLVMIRPlatform.
modifyPassConfig()
void llvm::orc::UnwindInfoRegistrationPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & PassConfig) override virtual
Reimplemented from llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 38 of file UnwindInfoRegistrationPlugin.cpp.
References G, modifyPassConfig(), and llvm::jitlink::PassConfiguration::PostFixupPasses.
Referenced by modifyPassConfig().
notifyEmitted()
Error llvm::orc::UnwindInfoRegistrationPlugin::notifyEmitted (MaterializationResponsibility & MR) inline override virtual
Reimplemented from llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 38 of file UnwindInfoRegistrationPlugin.h.
References llvm::Error::success().
notifyFailed()
Error llvm::orc::UnwindInfoRegistrationPlugin::notifyFailed (MaterializationResponsibility & MR) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 42 of file UnwindInfoRegistrationPlugin.h.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::UnwindInfoRegistrationPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 46 of file UnwindInfoRegistrationPlugin.h.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::UnwindInfoRegistrationPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 50 of file UnwindInfoRegistrationPlugin.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/UnwindInfoRegistrationPlugin.h
lib/ExecutionEngine/Orc/UnwindInfoRegistrationPlugin.cpp