LLVM: llvm::SystemZHLASMInstPrinter Class Reference
llvm::SystemZHLASMInstPrinter Class Reference
#include "Target/SystemZ/MCTargetDesc/SystemZHLASMInstPrinter.h"
Public Member Functions
SystemZHLASMInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
Public Member Functions inherited from llvm::SystemZInstPrinterCommon
SystemZInstPrinterCommon (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printAddress (const MCAsmInfo *MAI, MCRegister Base, const MCOperand &DispMO, MCRegister Index, raw_ostream &O)
void printOperand (const MCOperand &MO, const MCAsmInfo *MAI, raw_ostream &O)
void printRegName (raw_ostream &O, MCRegister Reg) override
Print the assembler register name.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::SystemZInstPrinterCommon
template<unsigned N>
void printUImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
template<unsigned N>
void printSImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printOperand (const MCInst *MI, uint64_t, unsigned OpNum, raw_ostream &O)
void printBDAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printBDXAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printBDLAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printBDRAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printBDVAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printLXAAddrOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU1ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU2ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU3ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU4ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printS8ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU8ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU12ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printS16ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU16ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printS32ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU32ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printU48ImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printPCRelOperand (const MCInst *MI, int OpNum, raw_ostream &O)
void printPCRelOperand (const MCInst *MI, uint64_t, int OpNum, raw_ostream &O)
void printPCRelTLSOperand (const MCInst *MI, uint64_t Address, int OpNum, raw_ostream &O)
void printCond4Operand (const MCInst *MI, int OpNum, raw_ostream &O)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Definition at line 24 of file SystemZHLASMInstPrinter.h.
Constructor & Destructor Documentation
SystemZHLASMInstPrinter()
llvm::SystemZHLASMInstPrinter::SystemZHLASMInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 26 of file SystemZHLASMInstPrinter.h.
References llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MII, llvm::MCInstPrinter::MRI, and llvm::SystemZInstPrinterCommon::SystemZInstPrinterCommon().
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::SystemZHLASMInstPrinter::getMnemonic (const MCInst & MI) const override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
References MI.
getRegisterName()
static const char * llvm::SystemZHLASMInstPrinter::getRegisterName (MCRegister Reg) static
References llvm::Address, llvm::MCInstPrinter::MAI, MI, and Reg.
Referenced by printFormattedRegName().
printInst()
void SystemZHLASMInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 29 of file SystemZHLASMInstPrinter.cpp.
References llvm::Address, MI, llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::SystemZHLASMInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
References llvm::Address, and MI.
Referenced by printInst().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/MCTargetDesc/SystemZHLASMInstPrinter.h
lib/Target/SystemZ/MCTargetDesc/SystemZHLASMInstPrinter.cpp