LLVM: llvm::jitlink::CompactUnwindManager< CURecTraits > Class Template Reference
llvm::jitlink::CompactUnwindManager< CURecTraits > Class Template Reference
Architecture specific implementation of CompactUnwindManager.
#include "ExecutionEngine/JITLink/CompactUnwindSupport.h"
Public Member Functions
CompactUnwindManager (StringRef CompactUnwindSectionName, StringRef UnwindInfoSectionName, StringRef EHFrameSectionName)
Error prepareForPrune (LinkGraph &G)
Error processAndReserveUnwindInfo (LinkGraph &G)
Process all __compact_unwind records and reserve space for __unwind_info.
Error writeUnwindInfo (LinkGraph &G)
Detailed Description
template<typename CURecTraits>
class llvm::jitlink::CompactUnwindManager< CURecTraits >
Architecture specific implementation of CompactUnwindManager.
Definition at line 75 of file CompactUnwindSupport.h.
Constructor & Destructor Documentation
CompactUnwindManager()
template<typename CURecTraits> llvm::jitlink::CompactUnwindManager< CURecTraits >::CompactUnwindManager (StringRef CompactUnwindSectionName, StringRef UnwindInfoSectionName, StringRef EHFrameSectionName) inline
Definition at line 77 of file CompactUnwindSupport.h.
Member Function Documentation
prepareForPrune()
template<typename CURecTraits> Error llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune (LinkGraph & G) inline
Definition at line 91 of file CompactUnwindSupport.h.
References B(), llvm::jitlink::Section::blocks(), llvm::jitlink::Section::blocks_size(), llvm::dbgs(), E(), llvm::jitlink::Section::empty(), llvm::formatv(), G, llvm::jitlink::Symbol::getName(), llvm::jitlink::Edge::getTarget(), llvm::jitlink::Symbol::isDefined(), llvm::jitlink::Edge::KeepAlive, LLVM_DEBUG, llvm::make_error(), llvm::jitlink::Edge::setTarget(), llvm::jitlink::splitCompactUnwindBlocks(), and llvm::Error::success().
processAndReserveUnwindInfo()
template<typename CURecTraits> Error llvm::jitlink::CompactUnwindManager< CURecTraits >::processAndReserveUnwindInfo (LinkGraph & G) inline
Process all __compact_unwind records and reserve space for __unwind_info.
Definition at line 215 of file CompactUnwindSupport.h.
References B(), llvm::dbgs(), llvm::formatv(), G, llvm::jitlink::Edge::KeepAlive, LLVM_DEBUG, llvm::make_error(), llvm::orc::NoAlloc, llvm::orc::Read, llvm::jitlink::Section::setMemLifetime(), and llvm::Error::success().
writeUnwindInfo()
template<typename CURecTraits> Error llvm::jitlink::CompactUnwindManager< CURecTraits >::writeUnwindInfo (LinkGraph & G) inline
Definition at line 273 of file CompactUnwindSupport.h.
References llvm::iterator_range< IteratorT >::begin(), llvm::jitlink::Section::blocks(), llvm::jitlink::Section::blocks_size(), llvm::dbgs(), llvm::jitlink::Section::empty(), llvm::formatv(), G, llvm::BinaryStreamWriter::getOffset(), LLVM_DEBUG, llvm::make_error(), and llvm::Error::success().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/CompactUnwindSupport.h