LLVM: llvm::dxil::ResourceBase Class Reference
llvm::dxil::ResourceBase Class Reference
#include "Target/DirectX/DXILResource.h"
Classes
struct ExtendedProperties
Protected Member Functions
ResourceBase (uint32_t I, hlsl::FrontendResource R)
void write (LLVMContext &Ctx, MutableArrayRef< Metadata * > Entries) const
void print (raw_ostream &O, StringRef IDPrefix, StringRef BindingPrefix) const
Static Protected Member Functions
static StringRef getKindName (dxil::ResourceKind Kind)
static void printKind (dxil::ResourceKind Kind, unsigned Alignment, raw_ostream &OS, bool SRV=false, bool HasCounter=false, uint32_t SampleCount=0)
static StringRef getElementTypeName (dxil::ElementType CompType)
static void printElementType (dxil::ResourceKind Kind, dxil::ElementType CompType, unsigned Alignment, raw_ostream &OS)
Protected Attributes
uint32_t ID
GlobalVariable * GV
StringRef Name
uint32_t Space
uint32_t LowerBound
uint32_t RangeSize
Detailed Description
Definition at line 31 of file DXILResource.h.
Constructor & Destructor Documentation
ResourceBase()
ResourceBase::ResourceBase (uint32_t I, hlsl::FrontendResource R) protected
Definition at line 58 of file DXILResource.cpp.
References llvm::dyn_cast(), getGlobalVariable(), GV, I, ID, LowerBound, Name, RangeSize, and Space.
Referenced by llvm::dxil::ConstantBuffer::ConstantBuffer(), and llvm::dxil::UAVResource::UAVResource().
Member Function Documentation
getElementTypeName()
StringRef ResourceBase::getElementTypeName (dxil::ElementType CompType) static protected
Definition at line 65 of file DXILResource.cpp.
References llvm::dxil::F16, llvm::dxil::F32, llvm::dxil::F64, llvm::dxil::I1, llvm::dxil::I16, llvm::dxil::I32, llvm::dxil::I64, llvm::dxil::Invalid, llvm::dxil::PackedS8x32, llvm::dxil::PackedU8x32, llvm::dxil::SNormF16, llvm::dxil::SNormF32, llvm::dxil::SNormF64, llvm::dxil::U16, llvm::dxil::U32, llvm::dxil::U64, llvm::dxil::UNormF16, llvm::dxil::UNormF32, and llvm::dxil::UNormF64.
Referenced by printElementType().
getKindName()
StringRef ResourceBase::getKindName (dxil::ResourceKind Kind) static protected
Definition at line 132 of file DXILResource.cpp.
References llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by printKind().
print()
void ResourceBase::print (raw_ostream & O, StringRef IDPrefix, StringRef BindingPrefix) const protected
Definition at line 216 of file DXILResource.cpp.
References ID, LowerBound, RangeSize, llvm::right_justify(), Space, and llvm::StringRef::str().
Referenced by llvm::dxil::ConstantBuffer::print(), and llvm::dxil::UAVResource::print().
printElementType()
void ResourceBase::printElementType (dxil::ResourceKind Kind, dxil::ElementType CompType, unsigned Alignment, raw_ostream & OS) static protected
Definition at line 109 of file DXILResource.cpp.
References llvm::dxil::CBuffer, getElementTypeName(), llvm::dxil::Invalid, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::right_justify(), llvm::dxil::Sampler, and llvm::dxil::StructuredBuffer.
Referenced by llvm::dxil::ConstantBuffer::print(), and llvm::dxil::UAVResource::print().
printKind()
void ResourceBase::printKind (dxil::ResourceKind Kind, unsigned Alignment, raw_ostream & OS, bool SRV = false, bool HasCounter = false, uint32_t SampleCount = 0) static protected
Definition at line 177 of file DXILResource.cpp.
References llvm::dxil::CBuffer, getKindName(), llvm::dxil::Invalid, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::right_justify(), llvm::dxil::Sampler, llvm::dxil::SRV, llvm::StringRef::str(), llvm::dxil::StructuredBuffer, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::dxil::ConstantBuffer::print(), and llvm::dxil::UAVResource::print().
write()
void ResourceBase::write (LLVMContext & Ctx, MutableArrayRef< Metadata * > Entries) const protected
Definition at line 287 of file DXILResource.cpp.
References B(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), GV, ID, LowerBound, Name, RangeSize, and Space.
Referenced by llvm::dxil::ConstantBuffer::write(), and llvm::dxil::UAVResource::write().
Member Data Documentation
GV
GlobalVariable* llvm::dxil::ResourceBase::GV protected
Definition at line 34 of file DXILResource.h.
Referenced by ResourceBase(), llvm::dxil::ConstantBuffer::setSize(), llvm::dxil::ConstantBuffer::write(), write(), and llvm::dxil::UAVResource::write().
ID
uint32_t llvm::dxil::ResourceBase::ID protected
Definition at line 33 of file DXILResource.h.
Referenced by print(), ResourceBase(), and write().
LowerBound
uint32_t llvm::dxil::ResourceBase::LowerBound protected
Definition at line 37 of file DXILResource.h.
Referenced by print(), ResourceBase(), and write().
Name
StringRef llvm::dxil::ResourceBase::Name protected
Definition at line 35 of file DXILResource.h.
Referenced by llvm::dxil::ConstantBuffer::print(), llvm::dxil::UAVResource::print(), ResourceBase(), and write().
RangeSize
uint32_t llvm::dxil::ResourceBase::RangeSize protected
Definition at line 38 of file DXILResource.h.
Referenced by print(), ResourceBase(), and write().
Space
uint32_t llvm::dxil::ResourceBase::Space protected
Definition at line 36 of file DXILResource.h.
Referenced by print(), ResourceBase(), and write().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResource.h
lib/Target/DirectX/DXILResource.cpp