LLVM: llvm::ImmutablePass Class Reference
llvm::ImmutablePass Class Reference
ImmutablePass class - This class is used to provide information that does not need to be run.
#include "llvm/Pass.h"
Public Member Functions
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
ImmutablePass class - This class is used to provide information that does not need to be run.
This is useful for things like target information.
Definition at line 281 of file Pass.h.
Constructor & Destructor Documentation
ImmutablePass()
llvm::ImmutablePass::ImmutablePass (char & pid) inline explicit
Definition at line 283 of file Pass.h.
References llvm::ModulePass::ModulePass().
Referenced by llvm::AMDGPUAAWrapperPass::AMDGPUAAWrapperPass(), llvm::AMDGPUArgumentUsageInfo::AMDGPUArgumentUsageInfo(), llvm::AssumptionCacheTracker::AssumptionCacheTracker(), llvm::BasicBlockSectionsProfileReaderWrapperPass::BasicBlockSectionsProfileReaderWrapperPass(), llvm::BasicBlockSectionsProfileReaderWrapperPass::BasicBlockSectionsProfileReaderWrapperPass(), llvm::DXILResourceTypeWrapperPass::DXILResourceTypeWrapperPass(), llvm::ExternalAAWrapperPass::ExternalAAWrapperPass(), llvm::ExternalAAWrapperPass::ExternalAAWrapperPass(), llvm::GCModuleInfo::GCModuleInfo(), getAsImmutablePass(), llvm::ImmutableModuleSummaryIndexWrapperPass::ImmutableModuleSummaryIndexWrapperPass(), llvm::MachineBranchProbabilityInfoWrapperPass::MachineBranchProbabilityInfoWrapperPass(), llvm::MachineModuleInfoWrapperPass::MachineModuleInfoWrapperPass(), llvm::MachineModuleInfoWrapperPass::MachineModuleInfoWrapperPass(), llvm::NVPTXAAWrapperPass::NVPTXAAWrapperPass(), llvm::PhysicalRegisterUsageInfoWrapperLegacy::PhysicalRegisterUsageInfoWrapperLegacy(), llvm::RegAllocEvictionAdvisorAnalysis::RegAllocEvictionAdvisorAnalysis(), llvm::RegAllocPriorityAdvisorAnalysis::RegAllocPriorityAdvisorAnalysis(), llvm::ScopedNoAliasAAWrapperPass::ScopedNoAliasAAWrapperPass(), llvm::TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass(), llvm::TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass(), llvm::TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass(), llvm::TargetPassConfig::TargetPassConfig(), llvm::TargetPassConfig::TargetPassConfig(), llvm::TargetTransformInfoWrapperPass::TargetTransformInfoWrapperPass(), llvm::TargetTransformInfoWrapperPass::TargetTransformInfoWrapperPass(), and llvm::TypeBasedAAWrapperPass::TypeBasedAAWrapperPass().
~ImmutablePass()
ImmutablePass::~ImmutablePass () override default
Member Function Documentation
getAsImmutablePass()
ImmutablePass * llvm::ImmutablePass::getAsImmutablePass () inline override virtual
Reimplemented from llvm::Pass.
Definition at line 295 of file Pass.h.
References ImmutablePass().
initializePass()
void ImmutablePass::initializePass () virtual
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
This is primarily because an ImmutablePass can "require" another ImmutablePass, and if it does, the overloaded version of initializePass may get access to these passes with getAnalysis<>.
Definition at line 157 of file Pass.cpp.
runOnModule()
bool llvm::ImmutablePass::runOnModule (Module &) inline override virtual
ImmutablePasses are never run.
Implements llvm::ModulePass.
Definition at line 298 of file Pass.h.
The documentation for this class was generated from the following files:
include/llvm/Pass.h
lib/SandboxIR/Pass.cpp