LLVM: llvm::DXILResourceMDWrapper Class Reference
llvm::DXILResourceMDWrapper Class Reference
The legacy pass manager's analysis pass to compute DXIL resource information.
#include "Target/DirectX/DXILResourceAnalysis.h"
Public Member Functions
DXILResourceMDWrapper ()
dxil::Resources & getDXILResource ()
const dxil::Resources & getDXILResource () const
bool runOnModule (Module &M) override
Calculate the DXILResource for the module.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
The legacy pass manager's analysis pass to compute DXIL resource information.
Definition at line 35 of file DXILResourceAnalysis.h.
Constructor & Destructor Documentation
DXILResourceMDWrapper()
DXILResourceMDWrapper::DXILResourceMDWrapper ()
Definition at line 41 of file DXILResourceAnalysis.cpp.
References ID, and llvm::ModulePass::ModulePass().
Referenced by runOnModule().
Member Function Documentation
getAnalysisUsage()
void llvm::DXILResourceMDWrapper::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 49 of file DXILResourceAnalysis.h.
References llvm::AnalysisUsage::setPreservesAll().
getDXILResource() [1/2]
dxil::Resources & llvm::DXILResourceMDWrapper::getDXILResource () inline
Definition at line 43 of file DXILResourceAnalysis.h.
getDXILResource() [2/2]
const dxil::Resources & llvm::DXILResourceMDWrapper::getDXILResource () const inline
Definition at line 44 of file DXILResourceAnalysis.h.
runOnModule()
DXIL resource true bool DXILResourceMDWrapper::runOnModule (Module & M) override virtual
Calculate the DXILResource for the module.
Implements llvm::ModulePass.
Definition at line 36 of file DXILResourceAnalysis.cpp.
References DXILResourceMDWrapper(), and runOnModule().
Referenced by runOnModule().
Member Data Documentation
ID
char DXILResourceMDWrapper::ID = 0 static
Definition at line 39 of file DXILResourceAnalysis.h.
Referenced by DXILResourceMDWrapper().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResourceAnalysis.h
lib/Target/DirectX/DXILResourceAnalysis.cpp