LLVM: llvm::sandboxir::SwitchAddCase Class Reference
llvm::sandboxir::SwitchAddCase Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
SwitchAddCase (SwitchInst *Switch, ConstantInt *Val)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 347 of file Tracker.h.
Constructor & Destructor Documentation
SwitchAddCase()
llvm::sandboxir::SwitchAddCase::SwitchAddCase (SwitchInst * Switch, ConstantInt * Val) inline
Definition at line 352 of file Tracker.h.
Member Function Documentation
accept()
void llvm::sandboxir::SwitchAddCase::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 355 of file Tracker.h.
dump() [1/2]
void SwitchAddCase::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 268 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::SwitchAddCase::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 357 of file Tracker.h.
revert()
void SwitchAddCase::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 262 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp