LLVM: llvm::ErrataWorkaround Class Reference
llvm::ErrataWorkaround Class Reference
#include "Target/Sparc/LeonPasses.h"
Public Member Functions
ErrataWorkaround ()
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Protected Member Functions
bool checkSeqTN0009A (MachineBasicBlock::iterator I)
bool checkSeqTN0009B (MachineBasicBlock::iterator I)
bool checkSeqTN0010First (MachineBasicBlock &MBB)
bool checkSeqTN0010 (MachineBasicBlock::iterator I)
bool checkSeqTN0012 (MachineBasicBlock::iterator I)
bool checkSeqTN0013 (MachineBasicBlock::iterator I)
bool moveNext (MachineBasicBlock::iterator &I)
bool isFloat (MachineBasicBlock::iterator I)
bool isDivSqrt (MachineBasicBlock::iterator I)
void insertNop (MachineBasicBlock::iterator I)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
const SparcSubtarget * ST
const TargetInstrInfo * TII
const TargetRegisterInfo * TRI
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 40 of file LeonPasses.h.
Constructor & Destructor Documentation
ErrataWorkaround()
ErrataWorkaround::ErrataWorkaround ()
Definition at line 24 of file LeonPasses.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeErrataWorkaroundPass(), and llvm::MachineFunctionPass::MachineFunctionPass().
Member Function Documentation
checkSeqTN0009A()
bool ErrataWorkaround::checkSeqTN0009A (MachineBasicBlock::iterator I) protected
Definition at line 86 of file LeonPasses.cpp.
References I, insertNop(), MI, and moveNext().
Referenced by runOnMachineFunction().
checkSeqTN0009B()
bool ErrataWorkaround::checkSeqTN0009B (MachineBasicBlock::iterator I) protected
Definition at line 124 of file LeonPasses.cpp.
References I, insertNop(), MI, and moveNext().
Referenced by runOnMachineFunction().
checkSeqTN0010()
bool ErrataWorkaround::checkSeqTN0010 (MachineBasicBlock::iterator I) protected
Definition at line 151 of file LeonPasses.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, insertNop(), MI, and moveNext().
Referenced by runOnMachineFunction().
checkSeqTN0010First()
bool ErrataWorkaround::checkSeqTN0010First (MachineBasicBlock & MBB) protected
Definition at line 197 of file LeonPasses.cpp.
References I, insertNop(), and MBB.
Referenced by runOnMachineFunction().
checkSeqTN0012()
bool ErrataWorkaround::checkSeqTN0012 (MachineBasicBlock::iterator I) protected
Definition at line 215 of file LeonPasses.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, insertNop(), isFloat(), and MI.
Referenced by runOnMachineFunction().
checkSeqTN0013()
bool ErrataWorkaround::checkSeqTN0013 (MachineBasicBlock::iterator I) protected
Definition at line 245 of file LeonPasses.cpp.
References I, insertNop(), isDivSqrt(), isFloat(), MI, moveNext(), and TRI.
Referenced by runOnMachineFunction().
getPassName()
StringRef llvm::ErrataWorkaround::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 64 of file LeonPasses.h.
insertNop()
void ErrataWorkaround::insertNop (MachineBasicBlock::iterator I) protected
Definition at line 52 of file LeonPasses.cpp.
References llvm::BuildMI(), I, and TII.
Referenced by checkSeqTN0009A(), checkSeqTN0009B(), checkSeqTN0010(), checkSeqTN0010First(), checkSeqTN0012(), checkSeqTN0013(), and moveNext().
isDivSqrt()
bool ErrataWorkaround::isDivSqrt (MachineBasicBlock::iterator I) protected
Definition at line 71 of file LeonPasses.cpp.
References I.
Referenced by checkSeqTN0013(), and moveNext().
isFloat()
bool ErrataWorkaround::isFloat (MachineBasicBlock::iterator I) protected
Definition at line 56 of file LeonPasses.cpp.
References contains(), and I.
Referenced by checkSeqTN0012(), checkSeqTN0013(), and moveNext().
moveNext()
bool llvm::ErrataWorkaround::moveNext (MachineBasicBlock::iterator & I) protected
References I, insertNop(), isDivSqrt(), and isFloat().
Referenced by checkSeqTN0009A(), checkSeqTN0009B(), checkSeqTN0010(), and checkSeqTN0013().
runOnMachineFunction()
bool ErrataWorkaround::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 295 of file LeonPasses.cpp.
References Changed, checkSeqTN0009A(), checkSeqTN0009B(), checkSeqTN0010(), checkSeqTN0010First(), checkSeqTN0012(), checkSeqTN0013(), llvm::MachineFunction::front(), llvm::MachineFunction::getSubtarget(), I, MBB, ST, TII, and TRI.
Member Data Documentation
ID
char ErrataWorkaround::ID = 0 static
Definition at line 59 of file LeonPasses.h.
Referenced by ErrataWorkaround().
ST
const SparcSubtarget* llvm::ErrataWorkaround::ST protected
Definition at line 42 of file LeonPasses.h.
Referenced by runOnMachineFunction().
TII
const TargetInstrInfo* llvm::ErrataWorkaround::TII protected
Definition at line 43 of file LeonPasses.h.
Referenced by insertNop(), and runOnMachineFunction().
TRI
const TargetRegisterInfo* llvm::ErrataWorkaround::TRI protected
Definition at line 44 of file LeonPasses.h.
Referenced by checkSeqTN0013(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/Target/Sparc/LeonPasses.h
lib/Target/Sparc/LeonPasses.cpp