LLVM: llvm::coro::BaseCloner Class Reference
llvm::coro::BaseCloner Class Reference
#include "Transforms/Coroutines/CoroCloner.h"
Public Member Functions
BaseCloner (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, CloneKind FKind, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
virtual ~BaseCloner ()
Function * getFunction () const
virtual void create ()
Clone the body of the original function into a resume function of some sort.
Static Public Member Functions
static Function * createClone (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, Function *NewF, AnyCoroSuspendInst *ActiveSuspend, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a clone for a continuation lowering.
Protected Member Functions
BaseCloner (Function &OrigF, const Twine &Suffix, coro::Shape &Shape, Function *NewF, AnyCoroSuspendInst *ActiveSuspend, TargetTransformInfo &TTI, const MetadataSetTy &CommonDebugInfo)
Create a cloner for a continuation lowering.
bool isSwitchDestroyFunction ()
void replaceEntryBlock ()
Value * deriveNewFramePointer ()
Derive the value of the new frame pointer.
void replaceRetconOrAsyncSuspendUses ()
Replace uses of the active llvm.coro.suspend.retcon/async call with the arguments to the continuation function.
void replaceCoroSuspends ()
void replaceCoroEnds ()
void replaceSwiftErrorOps ()
void salvageDebugInfo ()
void handleFinalSuspend ()
Protected Attributes
Function & OrigF
const Twine & Suffix
coro::Shape & Shape
CloneKind FKind
IRBuilder Builder
TargetTransformInfo & TTI
const MetadataSetTy & CommonDebugInfo
ValueToValueMapTy VMap
Function * NewF = nullptr
Value * NewFramePtr = nullptr
AnyCoroSuspendInst * ActiveSuspend = nullptr
The active suspend instruction; meaningful only for continuation and async ABIs.
Detailed Description
Definition at line 43 of file CoroCloner.h.
Constructor & Destructor Documentation
BaseCloner() [1/2]
llvm::coro::BaseCloner::BaseCloner (Function & OrigF, const Twine & Suffix, coro::Shape & Shape, Function * NewF, AnyCoroSuspendInst * ActiveSuspend, TargetTransformInfo & TTI, const MetadataSetTy & CommonDebugInfo) inline protected
Create a cloner for a continuation lowering.
Definition at line 64 of file CoroCloner.h.
References ActiveSuspend, assert(), llvm::coro::Async, Builder, CommonDebugInfo, llvm::coro::Continuation, FKind, NewF, OrigF, llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, Suffix, and TTI.
Referenced by createClone(), and llvm::coro::SwitchCloner::SwitchCloner().
BaseCloner() [2/2]
llvm::coro::BaseCloner::BaseCloner (Function & OrigF, const Twine & Suffix, coro::Shape & Shape, CloneKind FKind, TargetTransformInfo & TTI, const MetadataSetTy & CommonDebugInfo) inline
Definition at line 79 of file CoroCloner.h.
References Builder, CommonDebugInfo, FKind, OrigF, Shape, Suffix, and TTI.
~BaseCloner()
virtual llvm::coro::BaseCloner::~BaseCloner () inline virtual
Definition at line 86 of file CoroCloner.h.
Member Function Documentation
create()
void coro::BaseCloner::create () virtual
Clone the body of the original function into a resume function of some sort.
FIXME: Is it really good to add the NoAlias attribute?
Reimplemented in llvm::coro::SwitchCloner.
Definition at line 897 of file CoroSplit.cpp.
References A(), ActiveSuspend, addAsyncContextAttrs(), addFramePointerAttrs(), addSwiftSelfAttrs(), assert(), llvm::coro::Async, llvm::SmallVectorTemplateCommon< T, typename >::back(), Builder, llvm::cast(), llvm::changeToUnreachable(), llvm::CloneFunctionAttributesInto(), llvm::CloneFunctionBodyInto(), llvm::CloneFunctionMetadataInto(), CommonDebugInfo, deriveNewFramePointer(), llvm::Instruction::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, llvm::MDNode::get(), llvm::MDString::get(), llvm::PoisonValue::get(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::PointerType::getUnqual(), handleFinalSuspend(), NewF, NewFramePtr, OrigF, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), replaceCoroEnds(), replaceCoroSuspends(), replaceEntryBlock(), replaceRetconOrAsyncSuspendUses(), replaceSwiftErrorOps(), llvm::coro::Retcon, llvm::coro::RetconOnce, llvm::RF_None, llvm::coro::salvageDebugInfo(), Shape, llvm::BasicBlock::splitBasicBlock(), llvm::coro::Switch, llvm::CallInst::TCK_MustTail, TTI, updateScopeLine(), and VMap.
Referenced by llvm::coro::SwitchCloner::create(), and createClone().
createClone()
static Function * llvm::coro::BaseCloner::createClone (Function & OrigF, const Twine & Suffix, coro::Shape & Shape, Function * NewF, AnyCoroSuspendInst * ActiveSuspend, TargetTransformInfo & TTI, const MetadataSetTy & CommonDebugInfo) inline static
Create a clone for a continuation lowering.
Definition at line 89 of file CoroCloner.h.
References ActiveSuspend, assert(), llvm::coro::Async, BaseCloner(), CommonDebugInfo, create(), getFunction(), NewF, OrigF, llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, Suffix, and TTI.
Referenced by llvm::coro::AnyRetconABI::splitCoroutine(), and llvm::coro::AsyncABI::splitCoroutine().
deriveNewFramePointer()
Value * coro::BaseCloner::deriveNewFramePointer () protected
Derive the value of the new frame pointer.
Definition at line 762 of file CoroSplit.cpp.
References ActiveSuspend, assert(), llvm::coro::Async, Builder, llvm::cast(), llvm::Type::getInt8Ty(), llvm::PointerType::getUnqual(), llvm::InlineFunction(), InlineInfo, llvm_unreachable, NewF, llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, llvm::coro::Switch, and VMap.
Referenced by create().
getFunction()
Function * llvm::coro::BaseCloner::getFunction () const inline
Definition at line 104 of file CoroCloner.h.
References assert(), and NewF.
Referenced by createClone(), and llvm::coro::SwitchCloner::createClone().
handleFinalSuspend()
void coro::BaseCloner::handleFinalSuspend () protected
Definition at line 424 of file CoroSplit.cpp.
References assert(), Builder, llvm::cast(), Cond, llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getTerminator(), isSwitchDestroyFunction(), NewF, NewFramePtr, llvm::coro::Shape::SwitchFieldIndex::Resume, Shape, llvm::BasicBlock::splitBasicBlock(), llvm::coro::Switch, and VMap.
Referenced by create().
isSwitchDestroyFunction()
bool llvm::coro::BaseCloner::isSwitchDestroyFunction () inline protected
Definition at line 112 of file CoroCloner.h.
References llvm::coro::Async, llvm::coro::Continuation, FKind, llvm_unreachable, llvm::coro::SwitchCleanup, llvm::coro::SwitchResume, and llvm::coro::SwitchUnwind.
Referenced by handleFinalSuspend(), and replaceCoroSuspends().
replaceCoroEnds()
void coro::BaseCloner::replaceCoroEnds () protected
Definition at line 573 of file CoroSplit.cpp.
References llvm::cast(), NewFramePtr, replaceCoroEnd(), Shape, and VMap.
Referenced by create().
replaceCoroSuspends()
void coro::BaseCloner::replaceCoroSuspends () protected
Definition at line 536 of file CoroSplit.cpp.
References ActiveSuspend, llvm::coro::Async, Builder, llvm::cast(), isSwitchDestroyFunction(), llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, llvm::coro::Switch, and VMap.
Referenced by create().
replaceEntryBlock()
void coro::BaseCloner::replaceEntryBlock () protected
Definition at line 694 of file CoroSplit.cpp.
References ActiveSuspend, assert(), llvm::coro::Async, Builder, llvm::cast(), llvm::dyn_cast(), F, I, instructions, llvm::isa(), llvm::make_early_inc_range(), NewF, llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, Suffix, llvm::coro::Switch, and VMap.
Referenced by create().
replaceRetconOrAsyncSuspendUses()
void coro::BaseCloner::replaceRetconOrAsyncSuspendUses () protected
Replace uses of the active llvm.coro.suspend.retcon/async call with the arguments to the continuation function.
This assumes that the builder has a meaningful insertion point.
Definition at line 488 of file CoroSplit.cpp.
References ActiveSuspend, assert(), llvm::coro::Async, Builder, llvm::dyn_cast(), llvm::enumerate(), llvm::PoisonValue::get(), I, llvm::isa(), llvm::make_early_inc_range(), NewF, llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, and VMap.
Referenced by create().
replaceSwiftErrorOps()
void coro::BaseCloner::replaceSwiftErrorOps () protected
Definition at line 653 of file CoroSplit.cpp.
References NewF, replaceSwiftErrorOps(), Shape, and VMap.
salvageDebugInfo()
void coro::BaseCloner::salvageDebugInfo () protected
Definition at line 657 of file CoroSplit.cpp.
References collectDbgVariableIntrinsics(), llvm::dyn_cast(), llvm::for_each(), I, llvm::isa(), llvm::isa_and_nonnull(), llvm::Triple::isArch64Bit(), llvm::isPotentiallyReachable(), NewF, OrigF, llvm::coro::salvageDebugInfo(), llvm::Value::users(), and Uses.
Member Data Documentation
ActiveSuspend
AnyCoroSuspendInst* llvm::coro::BaseCloner::ActiveSuspend = nullptr protected
The active suspend instruction; meaningful only for continuation and async ABIs.
Definition at line 61 of file CoroCloner.h.
Referenced by BaseCloner(), create(), llvm::coro::SwitchCloner::create(), createClone(), deriveNewFramePointer(), replaceCoroSuspends(), replaceEntryBlock(), and replaceRetconOrAsyncSuspendUses().
Builder
IRBuilder llvm::coro::BaseCloner::Builder protected
Definition at line 49 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), create(), deriveNewFramePointer(), handleFinalSuspend(), replaceCoroSuspends(), replaceEntryBlock(), and replaceRetconOrAsyncSuspendUses().
CommonDebugInfo
const MetadataSetTy& llvm::coro::BaseCloner::CommonDebugInfo protected
Definition at line 53 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), create(), createClone(), llvm::coro::SwitchCloner::createClone(), and llvm::coro::SwitchCloner::SwitchCloner().
FKind
CloneKind llvm::coro::BaseCloner::FKind protected
Definition at line 48 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), llvm::coro::SwitchCloner::create(), llvm::coro::SwitchCloner::createClone(), isSwitchDestroyFunction(), and llvm::coro::SwitchCloner::SwitchCloner().
NewF
Function* llvm::coro::BaseCloner::NewF = nullptr protected
Definition at line 56 of file CoroCloner.h.
Referenced by BaseCloner(), create(), llvm::coro::SwitchCloner::create(), createClone(), deriveNewFramePointer(), getFunction(), handleFinalSuspend(), replaceEntryBlock(), replaceRetconOrAsyncSuspendUses(), replaceSwiftErrorOps(), and salvageDebugInfo().
NewFramePtr
Value* llvm::coro::BaseCloner::NewFramePtr = nullptr protected
Definition at line 57 of file CoroCloner.h.
Referenced by create(), handleFinalSuspend(), and replaceCoroEnds().
OrigF
Function& llvm::coro::BaseCloner::OrigF protected
Definition at line 45 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), create(), llvm::coro::SwitchCloner::create(), createClone(), llvm::coro::SwitchCloner::createClone(), salvageDebugInfo(), and llvm::coro::SwitchCloner::SwitchCloner().
Shape
coro::Shape& llvm::coro::BaseCloner::Shape protected
Definition at line 47 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), create(), llvm::coro::SwitchCloner::create(), createClone(), llvm::coro::SwitchCloner::createClone(), deriveNewFramePointer(), handleFinalSuspend(), replaceCoroEnds(), replaceCoroSuspends(), replaceEntryBlock(), replaceRetconOrAsyncSuspendUses(), replaceSwiftErrorOps(), and llvm::coro::SwitchCloner::SwitchCloner().
Suffix
const Twine& llvm::coro::BaseCloner::Suffix protected
Definition at line 46 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), llvm::coro::SwitchCloner::create(), createClone(), llvm::coro::SwitchCloner::createClone(), replaceEntryBlock(), and llvm::coro::SwitchCloner::SwitchCloner().
TTI
TargetTransformInfo& llvm::coro::BaseCloner::TTI protected
Definition at line 50 of file CoroCloner.h.
Referenced by BaseCloner(), BaseCloner(), create(), createClone(), llvm::coro::SwitchCloner::createClone(), and llvm::coro::SwitchCloner::SwitchCloner().
VMap
ValueToValueMapTy llvm::coro::BaseCloner::VMap protected
Definition at line 55 of file CoroCloner.h.
Referenced by create(), llvm::coro::SwitchCloner::create(), deriveNewFramePointer(), handleFinalSuspend(), replaceCoroEnds(), replaceCoroSuspends(), replaceEntryBlock(), replaceRetconOrAsyncSuspendUses(), and replaceSwiftErrorOps().
The documentation for this class was generated from the following files:
lib/Transforms/Coroutines/CoroCloner.h
lib/Transforms/Coroutines/CoroSplit.cpp