LLVM: llvm::sandboxir::SchedBundle Class Reference
llvm::sandboxir::SchedBundle Class Reference
The nodes that need to be scheduled back-to-back in a single scheduling cycle form a SchedBundle.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h"
Public Types
using ContainerTy = SmallVector<DGNode *, 4>
using iterator = ContainerTy::iterator
using const_iterator = ContainerTy::const_iterator
Public Member Functions
SchedBundle ()=default
SchedBundle (ContainerTy &&Nodes)
SchedBundle (const SchedBundle &Other)=delete
Copy CTOR (unimplemented).
SchedBundle & operator= (const SchedBundle &Other)=delete
Copy Assignment (unimplemented).
~SchedBundle ()
bool empty () const
DGNode * back () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
DGNode * getTop () const
\Returns the bundle node that comes before the others in program order.
DGNode * getBot () const
\Returns the bundle node that comes after the others in program order.
void cluster (BasicBlock::iterator Where)
Move all bundle instructions to Where back-to-back.
void dump (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
The nodes that need to be scheduled back-to-back in a single scheduling cycle form a SchedBundle.
Definition at line 65 of file Scheduler.h.
Member Typedef Documentation
const_iterator
using llvm::sandboxir::SchedBundle::const_iterator = ContainerTy::const_iterator
Definition at line 93 of file Scheduler.h.
ContainerTy
using llvm::sandboxir::SchedBundle::ContainerTy = SmallVector<DGNode *, 4>
Definition at line 67 of file Scheduler.h.
iterator
using llvm::sandboxir::SchedBundle::iterator = ContainerTy::iterator
Definition at line 92 of file Scheduler.h.
Constructor & Destructor Documentation
SchedBundle() [1/3]
llvm::sandboxir::SchedBundle::SchedBundle () default
Referenced by operator=(), and SchedBundle().
SchedBundle() [2/3]
llvm::sandboxir::SchedBundle::SchedBundle (ContainerTy && Nodes) inline
Definition at line 78 of file Scheduler.h.
References llvm::move(), and N.
SchedBundle() [3/3]
llvm::sandboxir::SchedBundle::SchedBundle (const SchedBundle & Other) delete
Copy CTOR (unimplemented).
References llvm::Other, and SchedBundle().
~SchedBundle()
llvm::sandboxir::SchedBundle::~SchedBundle () inline
Definition at line 86 of file Scheduler.h.
References N.
Member Function Documentation
back()
DGNode * llvm::sandboxir::SchedBundle::back () const inline
Definition at line 91 of file Scheduler.h.
begin() [1/2]
iterator llvm::sandboxir::SchedBundle::begin () inline
Definition at line 94 of file Scheduler.h.
begin() [2/2]
const_iterator llvm::sandboxir::SchedBundle::begin () const inline
Definition at line 96 of file Scheduler.h.
cluster()
void llvm::sandboxir::SchedBundle::cluster (BasicBlock::iterator Where)
Move all bundle instructions to Where back-to-back.
Definition at line 33 of file Scheduler.cpp.
References I, and N.
dump() [1/2]
void llvm::sandboxir::SchedBundle::dump () const
Definition at line 48 of file Scheduler.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::SchedBundle::dump (raw_ostream & OS) const
Definition at line 43 of file Scheduler.cpp.
References N.
empty()
bool llvm::sandboxir::SchedBundle::empty () const inline
Definition at line 90 of file Scheduler.h.
end() [1/2]
iterator llvm::sandboxir::SchedBundle::end () inline
Definition at line 95 of file Scheduler.h.
end() [2/2]
const_iterator llvm::sandboxir::SchedBundle::end () const inline
Definition at line 97 of file Scheduler.h.
getBot()
DGNode * llvm::sandboxir::SchedBundle::getBot () const
\Returns the bundle node that comes after the others in program order.
Definition at line 24 of file Scheduler.cpp.
References llvm::sandboxir::Instruction::comesBefore(), llvm::drop_begin(), llvm::sandboxir::DGNode::getInstruction(), and N.
getTop()
DGNode * llvm::sandboxir::SchedBundle::getTop () const
\Returns the bundle node that comes before the others in program order.
Definition at line 15 of file Scheduler.cpp.
References llvm::drop_begin(), llvm::sandboxir::DGNode::getInstruction(), and N.
operator=()
SchedBundle & llvm::sandboxir::SchedBundle::operator= (const SchedBundle & Other) delete
Copy Assignment (unimplemented).
References llvm::Other, and SchedBundle().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h
lib/Transforms/Vectorize/SandboxVectorizer/Scheduler.cpp