LLVM: llvm::orc::shared::detail::ResultDeserializer< SPSError, Error > Class Reference
llvm::orc::shared::detail::ResultDeserializer< SPSError, Error > Class Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Static Public Member Functions
static Error makeValue ()
static void makeSafe (Error &Err)
static Error deserialize (Error &Err, const char *ArgData, size_t ArgSize)
static Error makeValue ()
static void makeSafe (Error &Result)
static Error deserialize (Error &Result, const char *ArgData, size_t ArgSize)
Detailed Description
Definition at line 392 of file WrapperFunctionUtils.h.
Member Function Documentation
deserialize() [1/2]
static Error llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::deserialize (Error & Err, const char * ArgData, size_t ArgSize) inline static
Definition at line 397 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::fromSPSSerializable(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
deserialize() [2/2]
static Error llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::deserialize (Error & Result, const char * ArgData, size_t ArgSize) inline static
Definition at line 382 of file WrapperFunctionUtils.h.
makeSafe() [1/2]
static void llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeSafe (Error & Err) inline static
Definition at line 395 of file WrapperFunctionUtils.h.
References llvm::cantFail().
makeSafe() [2/2]
static void llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeSafe (Error & Result) inline static
Definition at line 380 of file WrapperFunctionUtils.h.
makeValue() [1/2]
static Error llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeValue () inline static
Definition at line 379 of file WrapperFunctionUtils.h.
makeValue() [2/2]
static Error llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeValue () inline static
Definition at line 394 of file WrapperFunctionUtils.h.
References llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h