LLVM: llvm::MCDecodedPseudoProbeInlineTree Class Reference
llvm::MCDecodedPseudoProbeInlineTree Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCDecodedPseudoProbeInlineTree ()=default
MCDecodedPseudoProbeInlineTree (const InlineSite &Site, MCDecodedPseudoProbeInlineTree *Parent)
bool hasInlineSite () const
InlineSite getInlineSite () const
void setProbes (MutableArrayRef< MCDecodedPseudoProbe > ProbesRef)
auto getProbes () const
Public Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >
bool isRoot () const
MutableArrayRef< MCDecodedPseudoProbeInlineTree > & getChildren ()
const MutableArrayRef< MCDecodedPseudoProbeInlineTree > & getChildren () const
const MCDecodedPseudoProbe *& getProbes () const
MCDecodedPseudoProbeInlineTree * getOrAddNode (const InlineSite &Site)
Additional Inherited Members
Public Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >
uint64_t Guid
MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > > * Parent
Protected Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >
MCPseudoProbeInlineTreeBase ()
Protected Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >
MutableArrayRef< MCDecodedPseudoProbeInlineTree > Children
MCDecodedPseudoProbe * Probes
Detailed Description
Definition at line 311 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCDecodedPseudoProbeInlineTree() [1/2]
llvm::MCDecodedPseudoProbeInlineTree::MCDecodedPseudoProbeInlineTree () default
Referenced by MCDecodedPseudoProbeInlineTree().
MCDecodedPseudoProbeInlineTree() [2/2]
llvm::MCDecodedPseudoProbeInlineTree::MCDecodedPseudoProbeInlineTree (const InlineSite & Site, MCDecodedPseudoProbeInlineTree * Parent) inline
Definition at line 320 of file MCPseudoProbe.h.
References llvm::get(), llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Guid, MCDecodedPseudoProbeInlineTree(), and llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Parent.
Member Function Documentation
getInlineSite()
InlineSite llvm::MCDecodedPseudoProbeInlineTree::getInlineSite () const inline
Definition at line 329 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Guid.
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext().
getProbes()
auto llvm::MCDecodedPseudoProbeInlineTree::getProbes () const inline
Definition at line 334 of file MCPseudoProbe.h.
References llvm::MutableArrayRef(), and llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Probes.
hasInlineSite()
bool llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite () const inline
Definition at line 328 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::isRoot(), and llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Parent.
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext(), and llvm::MCPseudoProbeDecoder::getInlinerDescForProbe().
setProbes()
void llvm::MCDecodedPseudoProbeInlineTree::setProbes (MutableArrayRef< MCDecodedPseudoProbe > ProbesRef) inline
Definition at line 330 of file MCPseudoProbe.h.
References llvm::MutableArrayRef< T >::data(), llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree, MutableArrayRef< MCDecodedPseudoProbeInlineTree > >::Probes, and llvm::ArrayRef< T >::size().
The documentation for this class was generated from the following file:
include/llvm/MC/MCPseudoProbe.h