LLVM: llvm::ObjectSizeOffsetVisitor Class Reference
llvm::ObjectSizeOffsetVisitor Class Reference
Evaluate the size and offset of an object pointed to by a Value* statically.
#include "llvm/Analysis/MemoryBuiltins.h"
Public Member Functions
ObjectSizeOffsetVisitor (const DataLayout &DL, const TargetLibraryInfo *TLI, LLVMContext &Context, ObjectSizeOpts Options={})
SizeOffsetAPInt compute (Value *V)
OffsetSpan visitAllocaInst (AllocaInst &I)
OffsetSpan visitArgument (Argument &A)
OffsetSpan visitCallBase (CallBase &CB)
OffsetSpan visitConstantPointerNull (ConstantPointerNull &)
OffsetSpan visitExtractElementInst (ExtractElementInst &I)
OffsetSpan visitExtractValueInst (ExtractValueInst &I)
OffsetSpan visitGlobalAlias (GlobalAlias &GA)
OffsetSpan visitGlobalVariable (GlobalVariable &GV)
OffsetSpan visitIntToPtrInst (IntToPtrInst &)
OffsetSpan visitLoadInst (LoadInst &I)
OffsetSpan visitPHINode (PHINode &)
OffsetSpan visitSelectInst (SelectInst &I)
OffsetSpan visitUndefValue (UndefValue &)
OffsetSpan visitInstruction (Instruction &I)
Public Member Functions inherited from llvm::InstVisitor< ObjectSizeOffsetVisitor, OffsetSpan >
void visit (Iterator Start, Iterator End)
void visit (Module &M)
void visit (Function &F)
void visit (BasicBlock &BB)
void visit (Module *M)
void visit (Function *F)
void visit (BasicBlock *BB)
OffsetSpan visit (Instruction *I)
OffsetSpan visit (Instruction &I)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
OffsetSpan visitICmpInst (ICmpInst &I)
OffsetSpan visitFCmpInst (FCmpInst &I)
OffsetSpan visitAllocaInst (AllocaInst &I)
OffsetSpan visitLoadInst (LoadInst &I)
OffsetSpan visitStoreInst (StoreInst &I)
OffsetSpan visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
OffsetSpan visitAtomicRMWInst (AtomicRMWInst &I)
OffsetSpan visitFenceInst (FenceInst &I)
OffsetSpan visitGetElementPtrInst (GetElementPtrInst &I)
OffsetSpan visitPHINode (PHINode &I)
OffsetSpan visitTruncInst (TruncInst &I)
OffsetSpan visitZExtInst (ZExtInst &I)
OffsetSpan visitSExtInst (SExtInst &I)
OffsetSpan visitFPTruncInst (FPTruncInst &I)
OffsetSpan visitFPExtInst (FPExtInst &I)
OffsetSpan visitFPToUIInst (FPToUIInst &I)
OffsetSpan visitFPToSIInst (FPToSIInst &I)
OffsetSpan visitUIToFPInst (UIToFPInst &I)
OffsetSpan visitSIToFPInst (SIToFPInst &I)
OffsetSpan visitPtrToIntInst (PtrToIntInst &I)
OffsetSpan visitIntToPtrInst (IntToPtrInst &I)
OffsetSpan visitBitCastInst (BitCastInst &I)
OffsetSpan visitAddrSpaceCastInst (AddrSpaceCastInst &I)
OffsetSpan visitSelectInst (SelectInst &I)
OffsetSpan visitVAArgInst (VAArgInst &I)
OffsetSpan visitExtractElementInst (ExtractElementInst &I)
OffsetSpan visitInsertElementInst (InsertElementInst &I)
OffsetSpan visitShuffleVectorInst (ShuffleVectorInst &I)
OffsetSpan visitExtractValueInst (ExtractValueInst &I)
OffsetSpan visitInsertValueInst (InsertValueInst &I)
OffsetSpan visitLandingPadInst (LandingPadInst &I)
OffsetSpan visitFuncletPadInst (FuncletPadInst &I)
OffsetSpan visitCleanupPadInst (CleanupPadInst &I)
OffsetSpan visitCatchPadInst (CatchPadInst &I)
OffsetSpan visitFreezeInst (FreezeInst &I)
OffsetSpan visitDbgDeclareInst (DbgDeclareInst &I)
OffsetSpan visitDbgValueInst (DbgValueInst &I)
OffsetSpan visitDbgVariableIntrinsic (DbgVariableIntrinsic &I)
OffsetSpan visitDbgLabelInst (DbgLabelInst &I)
OffsetSpan visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
OffsetSpan visitMemSetInst (MemSetInst &I)
OffsetSpan visitMemSetInlineInst (MemSetInlineInst &I)
OffsetSpan visitMemSetPatternInst (MemSetPatternInst &I)
OffsetSpan visitMemCpyInst (MemCpyInst &I)
OffsetSpan visitMemCpyInlineInst (MemCpyInlineInst &I)
OffsetSpan visitMemMoveInst (MemMoveInst &I)
OffsetSpan visitMemTransferInst (MemTransferInst &I)
OffsetSpan visitMemIntrinsic (MemIntrinsic &I)
OffsetSpan visitVAStartInst (VAStartInst &I)
OffsetSpan visitVAEndInst (VAEndInst &I)
OffsetSpan visitVACopyInst (VACopyInst &I)
OffsetSpan visitIntrinsicInst (IntrinsicInst &I)
OffsetSpan visitCallInst (CallInst &I)
OffsetSpan visitInvokeInst (InvokeInst &I)
OffsetSpan visitCallBrInst (CallBrInst &I)
OffsetSpan visitReturnInst (ReturnInst &I)
OffsetSpan visitBranchInst (BranchInst &I)
OffsetSpan visitSwitchInst (SwitchInst &I)
OffsetSpan visitIndirectBrInst (IndirectBrInst &I)
OffsetSpan visitResumeInst (ResumeInst &I)
OffsetSpan visitUnreachableInst (UnreachableInst &I)
OffsetSpan visitCleanupReturnInst (CleanupReturnInst &I)
OffsetSpan visitCatchReturnInst (CatchReturnInst &I)
OffsetSpan visitCatchSwitchInst (CatchSwitchInst &I)
OffsetSpan visitTerminator (Instruction &I)
OffsetSpan visitCastInst (CastInst &I)
OffsetSpan visitUnaryOperator (UnaryOperator &I)
OffsetSpan visitBinaryOperator (BinaryOperator &I)
OffsetSpan visitCmpInst (CmpInst &I)
OffsetSpan visitUnaryInstruction (UnaryInstruction &I)
OffsetSpan visitCallBase (CallBase &I)
void visitInstruction (Instruction &I)
Detailed Description
Evaluate the size and offset of an object pointed to by a Value* statically.
Fails if size or offset are not known at compile time.
Definition at line 252 of file MemoryBuiltins.h.
Constructor & Destructor Documentation
ObjectSizeOffsetVisitor()
ObjectSizeOffsetVisitor::ObjectSizeOffsetVisitor (const DataLayout & DL, const TargetLibraryInfo * TLI, LLVMContext & Context, ObjectSizeOpts Options = {})
Definition at line 742 of file MemoryBuiltins.cpp.
Member Function Documentation
compute()
SizeOffsetAPInt ObjectSizeOffsetVisitor::compute (Value * V)
Definition at line 751 of file MemoryBuiltins.cpp.
References llvm::OffsetSpan::After, llvm::OffsetSpan::Before, llvm::OffsetSpan::bothKnown(), llvm::ObjectSizeOpts::ExactSizeFromOffset, llvm::APInt::getBitWidth(), llvm::APInt::getZero(), llvm::OffsetSpan::knownAfter(), and llvm::OffsetSpan::knownBefore().
Referenced by llvm::getObjectSize().
visitAllocaInst()
OffsetSpan ObjectSizeOffsetVisitor::visitAllocaInst (AllocaInst & I)
Definition at line 891 of file MemoryBuiltins.cpp.
References aggregatePossibleConstantValues(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), I, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::isUIntN(), llvm::ObjectSizeOpts::Min, and Size.
visitArgument()
OffsetSpan ObjectSizeOffsetVisitor::visitArgument (Argument & A)
Definition at line 918 of file MemoryBuiltins.cpp.
References A(), llvm::Type::isSized(), and Size.
visitCallBase()
OffsetSpan ObjectSizeOffsetVisitor::visitCallBase (CallBase & CB)
Definition at line 930 of file MemoryBuiltins.cpp.
References aggregatePossibleConstantValues(), llvm::getAllocSize(), and Size.
visitConstantPointerNull()
OffsetSpan ObjectSizeOffsetVisitor::visitConstantPointerNull (ConstantPointerNull & CPN)
Definition at line 952 of file MemoryBuiltins.cpp.
References llvm::PointerType::getAddressSpace(), and llvm::ConstantPointerNull::getType().
visitExtractElementInst()
OffsetSpan ObjectSizeOffsetVisitor::visitExtractElementInst (ExtractElementInst & I)
Definition at line 966 of file MemoryBuiltins.cpp.
visitExtractValueInst()
OffsetSpan ObjectSizeOffsetVisitor::visitExtractValueInst (ExtractValueInst & I)
Definition at line 970 of file MemoryBuiltins.cpp.
visitGlobalAlias()
OffsetSpan ObjectSizeOffsetVisitor::visitGlobalAlias (GlobalAlias & GA)
Definition at line 975 of file MemoryBuiltins.cpp.
References llvm::GlobalAlias::getAliasee(), and llvm::GlobalValue::isInterposable().
visitGlobalVariable()
OffsetSpan ObjectSizeOffsetVisitor::visitGlobalVariable (GlobalVariable & GV)
Definition at line 981 of file MemoryBuiltins.cpp.
References llvm::GlobalObject::getAlign(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::isInterposable(), llvm::Type::isSized(), llvm::ObjectSizeOpts::Min, and Size.
visitInstruction()
OffsetSpan ObjectSizeOffsetVisitor::visitInstruction (Instruction & I)
Definition at line 1167 of file MemoryBuiltins.cpp.
References llvm::dbgs(), I, and LLVM_DEBUG.
visitIntToPtrInst()
OffsetSpan ObjectSizeOffsetVisitor::visitIntToPtrInst (IntToPtrInst &)
Definition at line 991 of file MemoryBuiltins.cpp.
visitLoadInst()
OffsetSpan ObjectSizeOffsetVisitor::visitLoadInst (LoadInst & I)
Definition at line 1109 of file MemoryBuiltins.cpp.
References llvm::OffsetSpan::bothKnown(), and llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent().
visitPHINode()
OffsetSpan ObjectSizeOffsetVisitor::visitPHINode (PHINode & PN)
Definition at line 1147 of file MemoryBuiltins.cpp.
References llvm::PHINode::getNumIncomingValues(), and llvm::PHINode::incoming_values().
visitSelectInst()
OffsetSpan ObjectSizeOffsetVisitor::visitSelectInst (SelectInst & I)
Definition at line 1158 of file MemoryBuiltins.cpp.
References I.
visitUndefValue()
OffsetSpan ObjectSizeOffsetVisitor::visitUndefValue (UndefValue &)
Definition at line 1163 of file MemoryBuiltins.cpp.
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemoryBuiltins.h
lib/Analysis/MemoryBuiltins.cpp