LLVM: llvm::SmallVectorTemplateBase< T, true > Class Template Reference
llvm::SmallVectorTemplateBase< T, true > Class Template Reference
SmallVectorTemplateBase<TriviallyCopyable = true> - This is where we put method implementations that are designed to work with trivially copyable T's.
#include "llvm/ADT/SmallVector.h"
Public Member Functions
void push_back (ValueParamT Elt)
void pop_back ()
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
size_t capacity () const
bool empty () const
size_t size () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = std::conditional_t<TakesParamByValue, T, const T &>
Either const T& or T, depending on whether it's cheap enough to take parameters by value.
using ValueParamT
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, T Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (T *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const T &Elt)
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy, std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy, std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
static void destroy_range (T *, T *)
template<typename It1, typename It2>
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
template<typename It1, typename It2>
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
template<typename T1, typename T2>
static void uninitialized_copy (T1 *I, T1 *E, T2 *Dest, std::enable_if_t< std::is_same< std::remove_const_t< T1 >, T2 >::value > *=nullptr)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
static ValueParamT forward_value_param (ValueParamT V)
Copy V or return a reference, depending on ValueParamT.
static void destroy_range (T *S, T *E)
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U>
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Static Protected Attributes
static constexpr bool TakesParamByValue = sizeof(T) <= 2 * sizeof(void *)
True if it's cheap enough to take parameters by value.
static constexpr bool TakesParamByValue
Friends
class SmallVectorTemplateCommon< T >
class SmallVectorTemplateCommon< T >
Additional Inherited Members
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = std::reverse_iterator<iterator>
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T>
class llvm::SmallVectorTemplateBase< T, true >
SmallVectorTemplateBase<TriviallyCopyable = true> - This is where we put method implementations that are designed to work with trivially copyable T's.
This allows using memcpy in place of copy/move construction and skipping destruction.
Definition at line 475 of file SmallVector.h.
Member Typedef Documentation
ValueParamT [1/2]
using llvm::SmallVectorTemplateBase< T, bool >::ValueParamT protected
Definition at line 334 of file SmallVector.h.
ValueParamT [2/2]
template<typename T> using llvm::SmallVectorTemplateBase< T, true >::ValueParamT = std::conditional_t<TakesParamByValue, T, const T &> protected
Either const T& or T, depending on whether it's cheap enough to take parameters by value.
Definition at line 485 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase() [1/2]
template<typename T> llvm::SmallVectorTemplateBase< T, true >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 487 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size, llvm::SmallVectorTemplateCommon< T, typename >::SmallVectorTemplateCommon(), and T.
SmallVectorTemplateBase() [2/2]
llvm::SmallVectorTemplateBase< T, bool >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 336 of file SmallVector.h.
Member Function Documentation
destroy_range() [1/2]
template<typename T> static void llvm::SmallVectorTemplateBase< T, true >::destroy_range (T * , T *) inline static protected
Definition at line 490 of file SmallVector.h.
References T.
destroy_range() [2/2]
static void llvm::SmallVectorTemplateBase< T, bool >::destroy_range (T * S, T * E) inline static protected
Definition at line 338 of file SmallVector.h.
forward_value_param() [1/3]
static const T & llvm::SmallVectorTemplateBase< T, bool >::forward_value_param (const T & V) inline static protected
Definition at line 389 of file SmallVector.h.
forward_value_param() [2/3]
static T && llvm::SmallVectorTemplateBase< T, bool >::forward_value_param (T && V) inline static protected
Definition at line 388 of file SmallVector.h.
forward_value_param() [3/3]
template<typename T> static ValueParamT llvm::SmallVectorTemplateBase< T, true >::forward_value_param (ValueParamT V) inline static protected
Copy V or return a reference, depending on ValueParamT.
Definition at line 541 of file SmallVector.h.
grow() [1/2]
void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::grow (size_t MinSize = 0) protected
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 362 of file SmallVector.h.
grow() [2/2]
template<typename T> void llvm::SmallVectorTemplateBase< T, true >::grow (size_t MinSize = 0) inline protected
Double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
Definition at line 525 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::grow_pod(), and T.
growAndAssign() [1/2]
void llvm::SmallVectorTemplateBase< T, bool >::growAndAssign (size_t NumElts, const T & Elt) inline protected
Definition at line 391 of file SmallVector.h.
growAndAssign() [2/2]
template<typename T> void llvm::SmallVectorTemplateBase< T, true >::growAndAssign (size_t NumElts, T Elt) inline protected
Definition at line 543 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::grow(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and T.
growAndEmplaceBack() [1/2]
T & llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 401 of file SmallVector.h.
growAndEmplaceBack() [2/2]
template<typename T> template<typename... ArgTypes> T & llvm::SmallVectorTemplateBase< T, true >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 552 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and T.
mallocForGrow()
T * llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::mallocForGrow (size_t MinSize, size_t & NewCapacity) protected
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
This is the first section of grow().
Definition at line 366 of file SmallVector.h.
moveElementsForGrow()
void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::moveElementsForGrow (T * NewElts) protected
Move existing elements over to the new allocation NewElts, the middle section of grow().
Definition at line 370 of file SmallVector.h.
pop_back() [1/2]
void llvm::SmallVectorTemplateBase< T, bool >::pop_back () inline
Definition at line 425 of file SmallVector.h.
pop_back() [2/2]
template<typename T> void llvm::SmallVectorTemplateBase< T, true >::pop_back () inline
Definition at line 567 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
push_back() [1/3]
void llvm::SmallVectorTemplateBase< T, bool >::push_back (const T & Elt) inline
Definition at line 413 of file SmallVector.h.
push_back() [2/3]
void llvm::SmallVectorTemplateBase< T, bool >::push_back (T && Elt) inline
Definition at line 419 of file SmallVector.h.
push_back() [3/3]
template<typename T> void llvm::SmallVectorTemplateBase< T, true >::push_back (ValueParamT Elt) inline
Definition at line 561 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and T.
reserveForParamAndGetAddress() [1/4]
const T * llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 377 of file SmallVector.h.
reserveForParamAndGetAddress() [2/4]
template<typename T> const T * llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 529 of file SmallVector.h.
References N, llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl(), and T.
reserveForParamAndGetAddress() [3/4]
T * llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 383 of file SmallVector.h.
reserveForParamAndGetAddress() [4/4]
template<typename T> T * llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 535 of file SmallVector.h.
References N, llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl(), and T.
takeAllocationForGrow()
void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::takeAllocationForGrow (T * NewElts, size_t NewCapacity) protected
Transfer ownership of the allocation, finishing up grow().
Definition at line 373 of file SmallVector.h.
uninitialized_copy() [1/3]
static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 355 of file SmallVector.h.
uninitialized_copy() [2/3]
template<typename T> template<typename It1, typename It2> static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 503 of file SmallVector.h.
References E(), and I.
uninitialized_copy() [3/3]
template<typename T> template<typename T1, typename T2> static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy (T1 * I, T1 * E, T2 * Dest, std::enable_if_t< std::is_same< std::remove_const_t< T1 >, T2 >::value > * = nullptr) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 511 of file SmallVector.h.
References E(), I, T, and T1.
uninitialized_move() [1/2]
static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 348 of file SmallVector.h.
uninitialized_move() [2/2]
template<typename T> template<typename It1, typename It2> static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 495 of file SmallVector.h.
References E(), I, and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Friends And Related Symbol Documentation
SmallVectorTemplateCommon< T > [1/2]
friend class SmallVectorTemplateCommon< T > friend
Definition at line 312 of file SmallVector.h.
SmallVectorTemplateCommon< T > [2/2]
template<typename T> friend class SmallVectorTemplateCommon< T > friend
Definition at line 425 of file SmallVector.h.
Member Data Documentation
TakesParamByValue [1/2]
bool llvm::SmallVectorTemplateBase< T, bool >::TakesParamByValue static constexpr protected
Definition at line 333 of file SmallVector.h.
TakesParamByValue [2/2]
template<typename T> bool llvm::SmallVectorTemplateBase< T, true >::TakesParamByValue = sizeof(T) <= 2 * sizeof(void *) static constexpr protected
True if it's cheap enough to take parameters by value.
Doing so avoids overhead related to mitigations for reference invalidation.
Definition at line 481 of file SmallVector.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h