LLVM: llvm::DiagnosticInfo Class Reference
llvm::DiagnosticInfo Class Reference abstract
This is the base abstract class for diagnostic reporting in the backend.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
virtual void print (DiagnosticPrinter &DP) const =0
Print using the given DP a user-friendly message.
Detailed Description
This is the base abstract class for diagnostic reporting in the backend.
The print method must be overloaded by the subclasses to print a user-friendly message in the client of the backend (let us call it a frontend).
Definition at line 112 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfo()
llvm::DiagnosticInfo::DiagnosticInfo (int Kind, DiagnosticSeverity Severity) inline
Definition at line 121 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoDebugMetadataVersion::classof(), llvm::DiagnosticInfoDontCall::classof(), llvm::DiagnosticInfoGeneric::classof(), llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::classof(), llvm::DiagnosticInfoInlineAsm::classof(), llvm::DiagnosticInfoInstrumentation::classof(), llvm::DiagnosticInfoISelFallback::classof(), llvm::DiagnosticInfoMIRParser::classof(), llvm::DiagnosticInfoPGOProfile::classof(), llvm::DiagnosticInfoSampleProfile::classof(), llvm::DiagnosticInfoSrcMgr::classof(), llvm::DiagnosticInfoDebugMetadataVersion::DiagnosticInfoDebugMetadataVersion(), llvm::DiagnosticInfoDontCall::DiagnosticInfoDontCall(), llvm::DiagnosticInfoGeneric::DiagnosticInfoGeneric(), llvm::DiagnosticInfoGeneric::DiagnosticInfoGeneric(), llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::DiagnosticInfoIgnoringInvalidDebugMetadata(), llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm(), llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm(), llvm::DiagnosticInfoInstrumentation::DiagnosticInfoInstrumentation(), llvm::DiagnosticInfoISelFallback::DiagnosticInfoISelFallback(), llvm::DiagnosticInfoMIRParser::DiagnosticInfoMIRParser(), llvm::DiagnosticInfoPGOProfile::DiagnosticInfoPGOProfile(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), llvm::DiagnosticInfoSrcMgr::DiagnosticInfoSrcMgr(), llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), and llvm::LinkDiagnosticInfo::LinkDiagnosticInfo().
~DiagnosticInfo()
virtual llvm::DiagnosticInfo::~DiagnosticInfo () virtual default
Member Function Documentation
getKind()
int llvm::DiagnosticInfo::getKind () const inline
Definition at line 126 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoDebugMetadataVersion::classof(), llvm::DiagnosticInfoDontCall::classof(), llvm::DiagnosticInfoGeneric::classof(), llvm::DiagnosticInfoGenericWithLoc::classof(), llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::classof(), llvm::DiagnosticInfoInlineAsm::classof(), llvm::DiagnosticInfoInstrumentation::classof(), llvm::DiagnosticInfoIROptimization::classof(), llvm::DiagnosticInfoISelFallback::classof(), llvm::DiagnosticInfoMIROptimization::classof(), llvm::DiagnosticInfoMIRParser::classof(), llvm::DiagnosticInfoMisExpect::classof(), llvm::DiagnosticInfoOptimizationBase::classof(), llvm::DiagnosticInfoOptimizationFailure::classof(), llvm::DiagnosticInfoPGOProfile::classof(), llvm::DiagnosticInfoRegAllocFailure::classof(), llvm::DiagnosticInfoResourceLimit::classof(), llvm::DiagnosticInfoSampleProfile::classof(), llvm::DiagnosticInfoSrcMgr::classof(), llvm::DiagnosticInfoStackSize::classof(), llvm::DiagnosticInfoUnsupported::classof(), llvm::MachineOptimizationRemark::classof(), llvm::MachineOptimizationRemarkAnalysis::classof(), llvm::MachineOptimizationRemarkMissed::classof(), llvm::OptimizationRemark::classof(), llvm::OptimizationRemarkAnalysis::classof(), llvm::OptimizationRemarkAnalysisAliasing::classof(), llvm::OptimizationRemarkAnalysisFPCommute::classof(), llvm::OptimizationRemarkMissed::classof(), llvm::DiagnosticInfoIROptimization::DiagnosticInfoIROptimization(), llvm::DiagnosticInfoSrcMgr::DiagnosticInfoSrcMgr(), llvm::DiagnosticInfoOptimizationBase::isAnalysis(), llvm::DiagnosticInfoOptimizationBase::isMissed(), and llvm::DiagnosticInfoOptimizationBase::isPassed().
getSeverity()
DiagnosticSeverity llvm::DiagnosticInfo::getSeverity () const inline
Definition at line 127 of file DiagnosticInfo.h.
Referenced by llvm::LLVMContext::diagnose(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::DiagnosticInfoIROptimization::DiagnosticInfoIROptimization(), llvm::DiagnosticInfoOptimizationFailure::isEnabled(), and llvm::DiagnosticInfoDontCall::print().
print()
virtual void llvm::DiagnosticInfo::print (DiagnosticPrinter & DP) const pure virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implemented in llvm::DiagnosticInfoDebugMetadataVersion, llvm::DiagnosticInfoDontCall, llvm::DiagnosticInfoGeneric, llvm::DiagnosticInfoGenericWithLoc, llvm::DiagnosticInfoIgnoringInvalidDebugMetadata, llvm::DiagnosticInfoInlineAsm, llvm::DiagnosticInfoInstrumentation, llvm::DiagnosticInfoISelFallback, llvm::DiagnosticInfoMIRParser, llvm::DiagnosticInfoMisExpect, llvm::DiagnosticInfoOptimizationBase, llvm::DiagnosticInfoPGOProfile, llvm::DiagnosticInfoRegAllocFailure, llvm::DiagnosticInfoResourceLimit, llvm::DiagnosticInfoSampleProfile, llvm::DiagnosticInfoSrcMgr, llvm::DiagnosticInfoUnsupported, and llvm::LinkDiagnosticInfo.
Referenced by llvm::LLVMContext::diagnose(), and llvm::LTOCodeGenerator::DiagnosticHandler().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp