LLVM: llvm::sandboxir::FunctionPassManager Class Reference
llvm::sandboxir::FunctionPassManager Class Reference final
#include "llvm/SandboxIR/PassManager.h"
Public Member Functions
FunctionPassManager (StringRef Name)
FunctionPassManager (StringRef Name, StringRef Pipeline, CreatePassFunc CreatePass)
bool runOnFunction (Function &F, const Analyses &A) final
\Returns true if it modifies F.
Public Member Functions inherited from llvm::sandboxir::PassManager< FunctionPass, FunctionPass >
void addPass (std::unique_ptr< FunctionPass > Pass)
Adds Pass to the pass pipeline.
void setPassPipeline (StringRef Pipeline, CreatePassFunc CreatePass)
Parses Pipeline as a comma-separated sequence of pass names and sets the pass pipeline, using CreatePass to instantiate passes by name.
void print (raw_ostream &OS) const override
LLVM_DUMP_METHOD void dump () const override
void printPipeline (raw_ostream &OS) const override
Similar to print() but prints one pass per line. Used for testing.
Public Member Functions inherited from llvm::sandboxir::FunctionPass
FunctionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
Additional Inherited Members
Public Types inherited from llvm::sandboxir::PassManager< FunctionPass, FunctionPass >
using CreatePassFunc
Protected Member Functions inherited from llvm::sandboxir::PassManager< FunctionPass, FunctionPass >
PassManager (StringRef Name)
PassManager (StringRef Name, StringRef Pipeline, CreatePassFunc CreatePass)
PassManager (const PassManager &)=delete
PassManager (PassManager &&)=default
virtual ~PassManager ()=default
PassManager & operator= (const PassManager &)=delete
Protected Attributes inherited from llvm::sandboxir::PassManager< FunctionPass, FunctionPass >
SmallVector< std::unique_ptr< FunctionPass > > Passes
The list of passes that this pass manager will run.
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
Definition at line 204 of file PassManager.h.
Constructor & Destructor Documentation
FunctionPassManager() [1/2]
llvm::sandboxir::FunctionPassManager::FunctionPassManager (StringRef Name) inline
Definition at line 207 of file PassManager.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::PassManager< FunctionPass, FunctionPass >::PassManager().
FunctionPassManager() [2/2]
llvm::sandboxir::FunctionPassManager::FunctionPassManager (StringRef Name, StringRef Pipeline, CreatePassFunc CreatePass) inline
Definition at line 208 of file PassManager.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::PassManager< FunctionPass, FunctionPass >::PassManager().
Member Function Documentation
runOnFunction()
bool llvm::sandboxir::FunctionPassManager::runOnFunction (Function & F, const Analyses & A) final virtual
\Returns true if it modifies F.
Implements llvm::sandboxir::FunctionPass.
Definition at line 13 of file PassManager.cpp.
References A(), F, and llvm::sandboxir::PassManager< FunctionPass, FunctionPass >::Passes.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/PassManager.h
lib/SandboxIR/PassManager.cpp