LLVM: llvm::PhysicalRegisterUsageInfo Class Reference
llvm::PhysicalRegisterUsageInfo Class Reference
#include "llvm/CodeGen/RegisterUsageInfo.h"
Public Member Functions
void setTargetMachine (const TargetMachine &TM)
Set TargetMachine which is used to print analysis.
bool doInitialization (Module &M)
bool doFinalization (Module &M)
void storeUpdateRegUsageInfo (const Function &FP, ArrayRef< uint32_t > RegMask)
To store RegMask for given Function *.
ArrayRef< uint32_t > getRegUsageInfo (const Function &FP)
To query stored RegMask for given Function *, it will returns ane empty array if function is not known.
void print (raw_ostream &OS, const Module *M=nullptr) const
bool invalidate (Module &M, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &Inv)
Detailed Description
Definition at line 35 of file RegisterUsageInfo.h.
Member Function Documentation
doFinalization()
bool PhysicalRegisterUsageInfo::doFinalization (Module & M)
Definition at line 51 of file RegisterUsageInfo.cpp.
References DumpRegUsage, llvm::errs(), and print().
doInitialization()
bool PhysicalRegisterUsageInfo::doInitialization (Module & M)
Definition at line 46 of file RegisterUsageInfo.cpp.
Referenced by llvm::PhysicalRegisterUsageAnalysis::run().
getRegUsageInfo()
ArrayRef< uint32_t > PhysicalRegisterUsageInfo::getRegUsageInfo (const Function & FP)
To query stored RegMask for given Function *, it will returns ane empty array if function is not known.
Definition at line 65 of file RegisterUsageInfo.cpp.
References FP.
invalidate()
bool PhysicalRegisterUsageInfo::invalidate (Module & M, const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator & Inv)
Definition at line 103 of file RegisterUsageInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
print()
void PhysicalRegisterUsageInfo::print (raw_ostream & OS, const Module * M = nullptr) const
Definition at line 72 of file RegisterUsageInfo.cpp.
References A(), B(), llvm::MachineOperand::clobbersPhysReg(), llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::sort(), and TRI.
Referenced by doFinalization().
setTargetMachine()
void llvm::PhysicalRegisterUsageInfo::setTargetMachine (const TargetMachine & TM)
Set TargetMachine which is used to print analysis.
References FP.
storeUpdateRegUsageInfo()
void PhysicalRegisterUsageInfo::storeUpdateRegUsageInfo (const Function & FP, ArrayRef< uint32_t > RegMask)
To store RegMask for given Function *.
Definition at line 59 of file RegisterUsageInfo.cpp.
References FP.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterUsageInfo.h
lib/CodeGen/RegisterUsageInfo.cpp