LLVM: llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > > Class Template Reference
llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Static Public Member Functions
static WrapperFunctionResult serialize (Expected< T > E)
static WrapperFunctionResult serialize (Expected< T > Result)
Detailed Description
template<typename SPSRetTagT, typename T>
class llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >
Definition at line 369 of file WrapperFunctionUtils.h.
Member Function Documentation
serialize() [1/2]
template<typename SPSRetTagT, typename T> static WrapperFunctionResult llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize (Expected< T > E) inline static
Definition at line 371 of file WrapperFunctionUtils.h.
References E(), llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult(), and llvm::orc::shared::detail::toSPSSerializable().
serialize() [2/2]
static WrapperFunctionResult llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize (Expected< T > Result) inline static
Definition at line 345 of file WrapperFunctionUtils.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h