LLVM: llvm::orc::GenericNamedTaskImpl< FnT > Class Template Reference
llvm::orc::GenericNamedTaskImpl< FnT > Class Template Reference
Generic task implementation.
#include "llvm/ExecutionEngine/Orc/TaskDispatch.h"
Public Member Functions
GenericNamedTaskImpl (FnT &&Fn, std::string DescBuffer)
GenericNamedTaskImpl (FnT &&Fn, const char *Desc)
void printDescription (raw_ostream &OS) override
void run () override
Public Member Functions inherited from llvm::RTTIExtends< GenericNamedTask, Task >
const void * dynamicClassID () const override
bool isA () const
Check whether this instance is a subclass of QueryT.
bool isA (const void *const ClassID) const override
Additional Inherited Members
Static Public Member Functions inherited from llvm::RTTIExtends< GenericNamedTask, Task >
static const void * classID ()
static bool classof (const T *R)
Static Public Attributes inherited from llvm::orc::GenericNamedTask
static char ID = 0
static const char * DefaultDescription = "Generic Task"
Detailed Description
template<typename FnT>
class llvm::orc::GenericNamedTaskImpl< FnT >
Generic task implementation.
Definition at line 59 of file TaskDispatch.h.
Constructor & Destructor Documentation
GenericNamedTaskImpl() [1/2]
template<typename FnT> llvm::orc::GenericNamedTaskImpl< FnT >::GenericNamedTaskImpl (FnT && Fn, std::string DescBuffer) inline
Definition at line 61 of file TaskDispatch.h.
References llvm::c_str(), and llvm::move().
GenericNamedTaskImpl() [2/2]
template<typename FnT> llvm::orc::GenericNamedTaskImpl< FnT >::GenericNamedTaskImpl (FnT && Fn, const char * Desc) inline
Definition at line 64 of file TaskDispatch.h.
References assert().
Member Function Documentation
printDescription()
template<typename FnT> void llvm::orc::GenericNamedTaskImpl< FnT >::printDescription (raw_ostream & OS) inline override
Definition at line 68 of file TaskDispatch.h.
run()
template<typename FnT> void llvm::orc::GenericNamedTaskImpl< FnT >::run () inline override
Definition at line 69 of file TaskDispatch.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TaskDispatch.h