LLVM: llvm::sandboxir::DiamondReuseMultiInput Class Reference
llvm::sandboxir::DiamondReuseMultiInput Class Reference final
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h"
Public Member Functions
const CollectDescr & getCollectDescr () const
Public Member Functions inherited from llvm::sandboxir::LegalityResult
virtual ~LegalityResult ()
LegalityResultID getSubclassID () const
virtual void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const LegalityResult *From)
Friends
class LegalityAnalysis
Additional Inherited Members
Protected Member Functions inherited from llvm::sandboxir::LegalityResult
LegalityResult (LegalityResultID ID)
Only Legality can create LegalityResults.
LegalityResult (const LegalityResult &)=delete
We shouldn't need copies.
LegalityResult & operator= (const LegalityResult &)=delete
Protected Attributes inherited from llvm::sandboxir::LegalityResult
LegalityResultID ID
Detailed Description
Definition at line 296 of file Legality.h.
Member Function Documentation
classof()
static bool llvm::sandboxir::DiamondReuseMultiInput::classof (const LegalityResult * From) inline static
Definition at line 304 of file Legality.h.
References llvm::sandboxir::DiamondReuseMultiInput, llvm::sandboxir::LegalityResult::getSubclassID(), and llvm::sandboxir::LegalityResult::LegalityResult().
getCollectDescr()
const CollectDescr & llvm::sandboxir::DiamondReuseMultiInput::getCollectDescr () const inline
Definition at line 307 of file Legality.h.
Friends And Related Symbol Documentation
LegalityAnalysis
friend class LegalityAnalysis friend
Definition at line 297 of file Legality.h.
References LegalityAnalysis, llvm::sandboxir::LegalityResult::LegalityResult(), and llvm::move().
Referenced by LegalityAnalysis.
The documentation for this class was generated from the following file:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h