LLVM: llvm::SelectionDAGTargetInfo Class Reference
llvm::SelectionDAGTargetInfo Class Reference
Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
Public Member Functions
SelectionDAGTargetInfo ()=default
SelectionDAGTargetInfo (const SelectionDAGTargetInfo &)=delete
SelectionDAGTargetInfo & operator= (const SelectionDAGTargetInfo &)=delete
virtual ~SelectionDAGTargetInfo ()
virtual bool isTargetMemoryOpcode (unsigned Opcode) const
Returns true if a node with the given target-specific opcode has a memory operand.
virtual bool isTargetStrictFPOpcode (unsigned Opcode) const
Returns true if a node with the given target-specific opcode has strict floating-point semantics.
virtual bool mayRaiseFPException (unsigned Opcode) const
Returns true if a node with the given target-specific opcode may raise a floating-point exception.
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memcpy.
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memmove.
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const
Emit target-specific code that performs a memset.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const
virtual bool disableGenericCombines (CodeGenOptLevel OptLevel) const
Detailed Description
Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
Definition at line 31 of file SelectionDAGTargetInfo.h.
Constructor & Destructor Documentation
SelectionDAGTargetInfo() [1/2]
llvm::SelectionDAGTargetInfo::SelectionDAGTargetInfo () explicit default
Referenced by operator=(), and SelectionDAGTargetInfo().
SelectionDAGTargetInfo() [2/2]
llvm::SelectionDAGTargetInfo::SelectionDAGTargetInfo (const SelectionDAGTargetInfo &) delete
References SelectionDAGTargetInfo().
~SelectionDAGTargetInfo()
SelectionDAGTargetInfo::~SelectionDAGTargetInfo () virtual default
Member Function Documentation
disableGenericCombines()
virtual bool llvm::SelectionDAGTargetInfo::disableGenericCombines (CodeGenOptLevel OptLevel) const inline virtual
Definition at line 174 of file SelectionDAGTargetInfo.h.
EmitTargetCodeForMemchr()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemchr (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memchr and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 120 of file SelectionDAGTargetInfo.h.
References llvm::Length, and SDValue().
EmitTargetCodeForMemcmp()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const inline virtual
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 108 of file SelectionDAGTargetInfo.h.
References SDValue().
EmitTargetCodeForMemcpy()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented in llvm::AArch64SelectionDAGInfo, llvm::ARMSelectionDAGInfo, llvm::BPFSelectionDAGInfo, llvm::HexagonSelectionDAGInfo, llvm::LanaiSelectionDAGInfo, llvm::SystemZSelectionDAGInfo, llvm::WebAssemblySelectionDAGInfo, llvm::X86SelectionDAGInfo, and llvm::XCoreSelectionDAGInfo.
Definition at line 64 of file SelectionDAGTargetInfo.h.
References SDValue().
EmitTargetCodeForMemmove()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemmove (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const inline virtual
Emit target-specific code that performs a memmove.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented in llvm::AArch64SelectionDAGInfo, llvm::ARMSelectionDAGInfo, and llvm::WebAssemblySelectionDAGInfo.
Definition at line 80 of file SelectionDAGTargetInfo.h.
References SDValue().
EmitTargetCodeForMemset()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const inline virtual
Emit target-specific code that performs a memset.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used. Note that if AlwaysInline is true the function has to return a valid SDValue.
Reimplemented in llvm::AArch64SelectionDAGInfo, llvm::ARMSelectionDAGInfo, llvm::SystemZSelectionDAGInfo, llvm::WebAssemblySelectionDAGInfo, and llvm::X86SelectionDAGInfo.
Definition at line 94 of file SelectionDAGTargetInfo.h.
References SDValue().
EmitTargetCodeForSetTag()
virtual SDValue llvm::SelectionDAGTargetInfo::EmitTargetCodeForSetTag (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const inline virtual
Reimplemented in llvm::AArch64SelectionDAGInfo.
Definition at line 165 of file SelectionDAGTargetInfo.h.
References SDValue(), and Size.
EmitTargetCodeForStrcmp()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const inline virtual
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the strcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 145 of file SelectionDAGTargetInfo.h.
References SDValue().
EmitTargetCodeForStrcpy()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrcpy (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const inline virtual
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
The first returned SDValue is the result of the copy (the start of the destination string for strcpy, a pointer to the null terminator for stpcpy) and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 133 of file SelectionDAGTargetInfo.h.
References DL, and SDValue().
EmitTargetCodeForStrlen()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const inline virtual
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 153 of file SelectionDAGTargetInfo.h.
References DL, and SDValue().
EmitTargetCodeForStrnlen()
virtual std::pair< SDValue, SDValue > llvm::SelectionDAGTargetInfo::EmitTargetCodeForStrnlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const inline virtual
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 159 of file SelectionDAGTargetInfo.h.
References DL, and SDValue().
isTargetMemoryOpcode()
virtual bool llvm::SelectionDAGTargetInfo::isTargetMemoryOpcode (unsigned Opcode) const inline virtual
Returns true if a node with the given target-specific opcode has a memory operand.
Nodes with such opcodes can only be created with SelectionDAG::getMemIntrinsicNode.
Reimplemented in llvm::AArch64SelectionDAGInfo, llvm::AMDGPUSelectionDAGInfo, llvm::ARMSelectionDAGInfo, llvm::MipsSelectionDAGInfo, llvm::NVPTXSelectionDAGInfo, llvm::PPCSelectionDAGInfo, llvm::RISCVSelectionDAGInfo, llvm::SystemZSelectionDAGInfo, llvm::WebAssemblySelectionDAGInfo, and llvm::X86SelectionDAGInfo.
Definition at line 41 of file SelectionDAGTargetInfo.h.
Referenced by mayRaiseFPException().
isTargetStrictFPOpcode()
virtual bool llvm::SelectionDAGTargetInfo::isTargetStrictFPOpcode (unsigned Opcode) const inline virtual
Returns true if a node with the given target-specific opcode has strict floating-point semantics.
Reimplemented in llvm::AArch64SelectionDAGInfo, llvm::PPCSelectionDAGInfo, llvm::RISCVSelectionDAGInfo, llvm::SystemZSelectionDAGInfo, and llvm::X86SelectionDAGInfo.
Definition at line 45 of file SelectionDAGTargetInfo.h.
Referenced by combineCVTP2I_CVTTP2I(), combineFMA(), combineVFMADD_VLWithVFNEG_VL(), mayRaiseFPException(), and performVFMADD_VLCombine().
mayRaiseFPException()
bool SelectionDAGTargetInfo::mayRaiseFPException (unsigned Opcode) const virtual
Returns true if a node with the given target-specific opcode may raise a floating-point exception.
Definition at line 19 of file SelectionDAGTargetInfo.cpp.
References isTargetMemoryOpcode(), and isTargetStrictFPOpcode().
Referenced by llvm::SelectionDAGISel::mayRaiseFPException().
operator=()
SelectionDAGTargetInfo & llvm::SelectionDAGTargetInfo::operator= (const SelectionDAGTargetInfo &) delete
References SelectionDAGTargetInfo().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGTargetInfo.h
lib/CodeGen/SelectionDAG/SelectionDAGTargetInfo.cpp