LLVM: llvm::formatv_object_base Class Reference
llvm::formatv_object_base Class Reference
#include "llvm/Support/FormatVariadic.h"
Public Member Functions
void format (raw_ostream &S) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Static Public Member Functions
static SmallVector< ReplacementItem, 2 > parseFormatString (StringRef Fmt, size_t NumArgs, bool Validate)
Protected Member Functions
formatv_object_base (StringRef Fmt, ArrayRef< support::detail::format_adapter * > Adapters, bool Validate)
formatv_object_base (formatv_object_base const &rhs)=delete
formatv_object_base (formatv_object_base &&rhs)=default
Protected Attributes
StringRef Fmt
ArrayRef< support::detail::format_adapter * > Adapters
bool Validate
Detailed Description
Definition at line 65 of file FormatVariadic.h.
Constructor & Destructor Documentation
formatv_object_base() [1/3]
llvm::formatv_object_base::formatv_object_base (StringRef Fmt, ArrayRef< support::detail::format_adapter * > Adapters, bool Validate) inline protected
Definition at line 71 of file FormatVariadic.h.
References Adapters, Fmt, and Validate.
Referenced by llvm::formatv_object< Tuple >::formatv_object(), llvm::formatv_object< Tuple >::formatv_object(), formatv_object_base(), and formatv_object_base().
formatv_object_base() [2/3]
llvm::formatv_object_base::formatv_object_base (formatv_object_base const & rhs) protected delete
References formatv_object_base().
formatv_object_base() [3/3]
llvm::formatv_object_base::formatv_object_base (formatv_object_base && rhs) protected default
References formatv_object_base().
Member Function Documentation
format()
void llvm::formatv_object_base::format (raw_ostream & S) const inline
Definition at line 80 of file FormatVariadic.h.
References Adapters, Fmt, llvm::Literal, parseFormatString(), and Validate.
Referenced by llvm::raw_ostream::operator<<().
operator SmallString< N >()
template<unsigned N> llvm::formatv_object_base::operator SmallString< N > () const inline
Definition at line 118 of file FormatVariadic.h.
References sstr().
operator std::string()
llvm::formatv_object_base::operator std::string () const inline
Definition at line 120 of file FormatVariadic.h.
References str().
parseFormatString()
SmallVector< ReplacementItem, 2 > formatv_object_base::parseFormatString (StringRef Fmt, size_t NumArgs, bool Validate) static
Definition at line 142 of file FormatVariadic.cpp.
References assert(), llvm::Count, llvm::SmallVectorImpl< T >::emplace_back(), llvm::errs(), Fmt, llvm::Format, llvm::formatv(), I, splitLiteralAndReplacement(), and Validate.
Referenced by format().
sstr()
template<unsigned N> SmallString< N > llvm::formatv_object_base::sstr () const inline
Definition at line 111 of file FormatVariadic.h.
Referenced by operator SmallString< N >().
str()
std::string llvm::formatv_object_base::str () const inline
Definition at line 103 of file FormatVariadic.h.
References llvm::raw_ostream::flush().
Referenced by operator std::string().
Member Data Documentation
Adapters
ArrayRef<support::detail::format_adapter *> llvm::formatv_object_base::Adapters protected
Definition at line 68 of file FormatVariadic.h.
Referenced by format(), llvm::formatv_object< Tuple >::formatv_object(), and formatv_object_base().
Fmt
StringRef llvm::formatv_object_base::Fmt protected
Definition at line 67 of file FormatVariadic.h.
Referenced by format(), llvm::formatv_object< Tuple >::formatv_object(), formatv_object_base(), and parseFormatString().
Validate
bool llvm::formatv_object_base::Validate protected
Definition at line 69 of file FormatVariadic.h.
Referenced by format(), llvm::formatv_object< Tuple >::formatv_object(), formatv_object_base(), and parseFormatString().
The documentation for this class was generated from the following files:
include/llvm/Support/FormatVariadic.h
lib/Support/FormatVariadic.cpp