LLVM: llvm::object::Binary Class Reference
llvm::object::Binary Class Reference
#include "llvm/Object/Binary.h"
Public Member Functions
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isGOFF () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Types
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_TapiUniversal , ID_TapiFile , ID_Minidump , ID_WinRes ,
ID_Offload , ID_StartObjects , ID_COFF , ID_XCOFF32 ,
ID_XCOFF64 , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_GOFF , ID_Wasm , ID_EndObjects
}
Protected Member Functions
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes
MemoryBufferRef Data
Detailed Description
Definition at line 32 of file Binary.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
ID_Archive
ID_MachOUniversalBinary
ID_COFFImportFile
ID_IR
ID_TapiUniversal
ID_TapiFile
ID_Minidump
ID_WinRes
ID_Offload
ID_StartObjects
ID_COFF
ID_XCOFF32
ID_XCOFF64
ID_ELF32L
ID_ELF32B
ID_ELF64L
ID_ELF64B
ID_MachO32L
ID_MachO32B
ID_MachO64L
ID_MachO64B
ID_GOFF
ID_Wasm
ID_EndObjects
Definition at line 41 of file Binary.h.
Constructor & Destructor Documentation
Binary() [1/3]
Binary::Binary (unsigned int Type, MemoryBufferRef Source) protected
Definition at line 36 of file Binary.cpp.
References Data.
Referenced by llvm::object::Archive::Archive(), Binary(), llvm::object::Archive::classof(), llvm::object::MachOUniversalBinary::classof(), llvm::object::MinidumpFile::classof(), llvm::object::OffloadBinary::classof(), llvm::object::SymbolicFile::classof(), llvm::object::TapiUniversal::classof(), llvm::object::WindowsResource::classof(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::object::SymbolicFile::SymbolicFile(), and llvm::object::TapiUniversal::TapiUniversal().
Binary() [2/3]
llvm::object::Binary::Binary () delete
Binary() [3/3]
llvm::object::Binary::Binary (const Binary & other) delete
References Binary().
~Binary()
Binary::~Binary () virtual default
Member Function Documentation
checkOffset()
static Error llvm::object::Binary::checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size) inline static
Definition at line 175 of file Binary.h.
References llvm::errorCodeToError(), Size, llvm::Error::success(), and llvm::object::unexpected_eof.
Referenced by getFirstReloc(), getObject(), llvm::object::getObject(), llvm::object::XCOFFObjectFile::getRawData(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionContents(), and llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData().
getData()
StringRef Binary::getData () const
Definition at line 39 of file Binary.cpp.
References Data.
Referenced by checkDyldInfoCommand(), checkDysymtabCommand(), checkEncryptCommand(), checkLinkeditDataCommand(), checkNoteCommand(), checkSymtabCommand(), checkTwoLevelHintsCommand(), createMemberHeaderParseError(), getLoadCommandInfo(), getNextLoadCommandInfo(), llvm::object::MachOObjectFile::getSectionContents(), llvm::object::MachOObjectFile::getSectionSize(), llvm::object::MachOObjectFile::getStringTableData(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::MCJIT::notifyFreeingObject(), llvm::MCJIT::notifyObjectLoaded(), parseHeader(), parseSegmentLoadCommand(), llvm::object::MachOObjectFile::ReadULEB128s(), and llvm::object::WasmObjectFile::WasmObjectFile().
getELFType()
static unsigned int llvm::object::Binary::getELFType (bool isLE, bool is64Bits) inline static protected
Definition at line 78 of file Binary.h.
References ID_ELF32B, ID_ELF32L, ID_ELF64B, and ID_ELF64L.
Referenced by llvm::object::ELFObjectFile< ELF32LE >::classof().
getFileName()
StringRef Binary::getFileName () const
Definition at line 41 of file Binary.cpp.
References Data.
Referenced by llvm::objcopy::createNewArchiveMembers(), llvm::object::IRObjectFile::findBitcodeInObject(), llvm::orc::getCOFFObjectFileSymbolInfo(), llvm::orc::getELFObjectFileSymbolInfo(), llvm::pdb::InputFile::getFilePath(), llvm::orc::getMachOObjectFileSymbolInfo(), llvm::orc::getMachOSliceRangeForTriple(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::object::WindowsResourceParser::parse(), and llvm::object::writeUniversalBinary().
getMachOType()
static unsigned int llvm::object::Binary::getMachOType (bool isLE, bool is64Bits) inline static protected
Definition at line 85 of file Binary.h.
References ID_MachO32B, ID_MachO32L, ID_MachO64B, and ID_MachO64L.
Referenced by llvm::object::MachOObjectFile::is64Bit().
getMemoryBufferRef()
MemoryBufferRef Binary::getMemoryBufferRef () const
Definition at line 43 of file Binary.cpp.
References Data.
Referenced by llvm::object::BigArchive::BigArchive(), llvm::object::Archive::Child::getAsBinary(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), isAnyArm64COFF(), and isECObject().
getTripleObjectFormat()
Triple::ObjectFormatType llvm::object::Binary::getTripleObjectFormat () const inline
Definition at line 163 of file Binary.h.
References llvm::Triple::COFF, llvm::Triple::ELF, llvm::Triple::GOFF, isCOFF(), isELF(), isGOFF(), isMachO(), llvm::Triple::MachO, and llvm::Triple::UnknownObjectFormat.
Referenced by llvm::InstrProfCorrelator::Context::get(), getInstrProfSection(), lookupAllocatableSection(), and lookupSections().
getType()
unsigned int llvm::object::Binary::getType () const inline
Definition at line 104 of file Binary.h.
Referenced by llvm::object::MachOObjectFile::is64Bit(), and llvm::object::XCOFFObjectFile::is64Bit().
initContent()
virtual Error llvm::object::Binary::initContent () inline virtual
Reimplemented in ELFObjectFile< ELFT >, llvm::objcopy::elf::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32BE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF32LE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64BE >, llvm::object::ELFObjectFile< ELF64LE >, llvm::object::ELFObjectFile< ELF64LE >, llvm::object::ELFObjectFile< ELF64LE >, llvm::object::ELFObjectFile< ELF64LE >, llvm::object::ELFObjectFile< ELF64LE >, and llvm::object::ELFObjectFile< ELF64LE >.
Definition at line 97 of file Binary.h.
References llvm::Error::success().
isArchive()
bool llvm::object::Binary::isArchive () const inline
Definition at line 115 of file Binary.h.
References ID_Archive.
isCOFF()
bool llvm::object::Binary::isCOFF () const inline
Definition at line 131 of file Binary.h.
References ID_COFF.
Referenced by llvm::InstrProfCorrelatorImpl< IntPtrT >::get(), llvm::object::getRelocationResolver(), getTripleObjectFormat(), isAnyArm64COFF(), llvm::RuntimeDyldCOFF::isCompatibleFile(), isECObject(), llvm::RuntimeDyld::loadObject(), and llvm::object::ObjectFile::makeTriple().
isCOFFImportFile()
bool llvm::object::Binary::isCOFFImportFile () const inline
Definition at line 141 of file Binary.h.
References ID_COFFImportFile.
Referenced by isAnyArm64COFF(), isECObject(), and isSymbolic().
isELF()
bool llvm::object::Binary::isELF () const inline
Definition at line 123 of file Binary.h.
References ID_ELF32L, and ID_ELF64B.
Referenced by llvm::InstrProfCorrelatorImpl< IntPtrT >::get(), llvm::object::getRelocationResolver(), getTripleObjectFormat(), llvm::RuntimeDyldELF::isCompatibleFile(), and llvm::RuntimeDyld::loadObject().
isGOFF()
bool llvm::object::Binary::isGOFF () const inline
Definition at line 149 of file Binary.h.
References ID_GOFF.
Referenced by getTripleObjectFormat(), and llvm::object::ObjectFile::makeTriple().
isIR()
bool llvm::object::Binary::isIR () const inline
Definition at line 145 of file Binary.h.
References ID_IR.
Referenced by isAnyArm64COFF(), isECObject(), and isSymbolic().
isLittleEndian()
bool llvm::object::Binary::isLittleEndian () const inline
Definition at line 155 of file Binary.h.
References ID_ELF32B, ID_ELF64B, ID_MachO32B, ID_MachO64B, ID_XCOFF32, and ID_XCOFF64.
Referenced by checkThreadCommand(), llvm::symbolize::SymbolizableObjectFile::create(), extractSections(), llvm::InstrProfCorrelator::Context::get(), llvm::object::MachOObjectFile::getChainedFixupsSegments(), llvm::object::MachOObjectFile::getDyldChainedFixupTargets(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::MachOObjectFile::getPlainRelocationSymbolNum(), llvm::RuntimeDyldImpl::loadObjectImpl(), readMachOHeader(), and llvm::object::ELFObjectFileBase::setARMSubArch().
isMachO()
bool llvm::object::Binary::isMachO () const inline
Definition at line 127 of file Binary.h.
References ID_MachO32L, and ID_MachO64B.
Referenced by llvm::InstrProfCorrelatorImpl< IntPtrT >::get(), llvm::object::getRelocationResolver(), getRemarksSectionName(), getTripleObjectFormat(), llvm::RuntimeDyldMachO::isCompatibleFile(), llvm::RuntimeDyld::loadObject(), and llvm::object::ObjectFile::makeTriple().
isMachOUniversalBinary()
bool llvm::object::Binary::isMachOUniversalBinary () const inline
Definition at line 117 of file Binary.h.
References ID_MachOUniversalBinary.
isMinidump()
bool llvm::object::Binary::isMinidump () const inline
Definition at line 151 of file Binary.h.
References ID_Minidump.
isObject()
bool llvm::object::Binary::isObject () const inline
Definition at line 107 of file Binary.h.
References ID_EndObjects, and ID_StartObjects.
Referenced by isSymbolic().
isOffloadFile()
bool llvm::object::Binary::isOffloadFile () const inline
Definition at line 139 of file Binary.h.
References ID_Offload.
isSymbolic()
bool llvm::object::Binary::isSymbolic () const inline
Definition at line 111 of file Binary.h.
References isCOFFImportFile(), isIR(), isObject(), and isTapiFile().
isTapiFile()
bool llvm::object::Binary::isTapiFile () const inline
Definition at line 153 of file Binary.h.
References ID_TapiFile.
Referenced by isSymbolic().
isTapiUniversal()
bool llvm::object::Binary::isTapiUniversal () const inline
Definition at line 121 of file Binary.h.
References ID_TapiUniversal.
isWasm()
bool llvm::object::Binary::isWasm () const inline
Definition at line 137 of file Binary.h.
References ID_Wasm.
Referenced by llvm::object::getRelocationResolver(), and llvm::logicalview::LVBinaryReader::mapVirtualAddress().
isWinRes()
bool llvm::object::Binary::isWinRes () const inline
Definition at line 161 of file Binary.h.
References ID_WinRes.
isXCOFF()
bool llvm::object::Binary::isXCOFF () const inline
Definition at line 135 of file Binary.h.
References ID_XCOFF32, and ID_XCOFF64.
Referenced by llvm::object::ObjectFile::makeTriple().
Member Data Documentation
Data
MemoryBufferRef llvm::object::Binary::Data protected
Definition at line 37 of file Binary.h.
Referenced by llvm::object::Archive::Archive(), llvm::object::ObjectFile::base(), llvm::object::BigArchive::BigArchive(), Binary(), llvm::object::Archive::child_begin(), llvm::object::MinidumpFile::create(), llvm::object::ObjectFile::createObjectFile(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::ELFObjectFile< ELFT >::ELFObjectFile(), llvm::object::COFFImportFile::getCOFFImportHeader(), llvm::object::ELFObjectFileBase::getCrelDecodeProblem(), getData(), llvm::object::COFFImportFile::getExportName(), getFileName(), llvm::object::COFFObjectFile::getHybridObjectView(), llvm::object::XCOFFObjectFile::getImportFileTable(), getMemoryBufferRef(), llvm::object::MinidumpFile::getMemoryInfoList(), llvm::object::XCOFFObjectFile::getRawData(), llvm::object::COFFObjectFile::getRelocations(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData(), llvm::object::GOFFObjectFile::GOFFObjectFile(), llvm::object::Archive::isEmpty(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::object::COFFImportFile::printSymbolName(), llvm::object::XCOFFObjectFile::relocations(), llvm::object::COFFObjectFile::section_rel_begin(), llvm::object::COFFObjectFile::section_rel_end(), and llvm::object::OffloadBinary::write().
The documentation for this class was generated from the following files:
include/llvm/Object/Binary.h
lib/Object/Binary.cpp