LLVM: llvm::SpecialCaseList::Matcher Class Reference
llvm::SpecialCaseList::Matcher Class Reference
Represents a set of globs and their line numbers.
#include "llvm/Support/SpecialCaseList.h"
Public Member Functions
Error insert (StringRef Pattern, unsigned LineNumber, bool UseRegex)
unsigned match (StringRef Query) const
Public Attributes
StringMap< std::pair< GlobPattern, unsigned > > Globs
std::vector< std::pair< std::unique_ptr< Regex >, unsigned > > RegExes
Detailed Description
Represents a set of globs and their line numbers.
Definition at line 118 of file SpecialCaseList.h.
Member Function Documentation
insert()
Error llvm::SpecialCaseList::Matcher::insert (StringRef Pattern, unsigned LineNumber, bool UseRegex)
Definition at line 27 of file SpecialCaseList.cpp.
References llvm::GlobPattern::create(), llvm::createStringError(), Globs, llvm::invalid_argument, llvm::Regex::isValid(), RegExes, and llvm::Error::success().
match()
unsigned llvm::SpecialCaseList::Matcher::match (StringRef Query) const
Definition at line 70 of file SpecialCaseList.cpp.
References Globs, llvm::Regex::match(), and RegExes.
Member Data Documentation
Globs
StringMap<std::pair<GlobPattern, unsigned> > llvm::SpecialCaseList::Matcher::Globs
Definition at line 125 of file SpecialCaseList.h.
Referenced by insert(), and match().
RegExes
std::vector<std::pair<std::unique_ptr<Regex>, unsigned> > llvm::SpecialCaseList::Matcher::RegExes
Definition at line 126 of file SpecialCaseList.h.
Referenced by insert(), and match().
The documentation for this class was generated from the following files:
include/llvm/Support/SpecialCaseList.h
lib/Support/SpecialCaseList.cpp