LLVM: llvm::PredicateBase Class Reference
llvm::PredicateBase Class Reference
#include "llvm/Transforms/Utils/PredicateInfo.h"
Public Member Functions
PredicateBase (const PredicateBase &)=delete
PredicateBase & operator= (const PredicateBase &)=delete
PredicateBase ()=delete
virtual ~PredicateBase ()=default
std::optional< PredicateConstraint > getConstraint () const
Fetch condition in the form of PredicateConstraint, if possible.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< PredicateBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< PredicateBase, Options... >::type >, ilist_detail::compute_node_options< PredicateBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< PredicateBase, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< PredicateBase, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< PredicateBase, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static bool classof (const PredicateBase *PB)
Public Attributes
PredicateType Type
Value * OriginalOp
Value * RenamedOp
Value * Condition
Protected Member Functions
PredicateBase (PredicateType PT, Value *Op, Value *Condition)
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< PredicateBase, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< PredicateBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
Definition at line 81 of file PredicateInfo.h.
Constructor & Destructor Documentation
PredicateBase() [1/3]
llvm::PredicateBase::PredicateBase (const PredicateBase &) delete
References PredicateBase().
Referenced by llvm::PredicateAssume::classof(), classof(), llvm::PredicateWithEdge::classof(), operator=(), llvm::PredicateAssume::PredicateAssume(), PredicateBase(), and llvm::PredicateWithEdge::PredicateWithEdge().
PredicateBase() [2/3]
llvm::PredicateBase::PredicateBase () delete
~PredicateBase()
virtual llvm::PredicateBase::~PredicateBase () virtual default
PredicateBase() [3/3]
llvm::PredicateBase::PredicateBase (PredicateType PT, Value * Op, Value * Condition) inline protected
Definition at line 108 of file PredicateInfo.h.
References Condition, OriginalOp, and Type.
Member Function Documentation
classof()
static bool llvm::PredicateBase::classof (const PredicateBase * PB) inline static
Definition at line 99 of file PredicateInfo.h.
References PB(), PredicateBase(), llvm::PT_Assume, llvm::PT_Branch, and llvm::PT_Switch.
getConstraint()
std::optional< PredicateConstraint > llvm::PredicateBase::getConstraint () const
Fetch condition in the form of PredicateConstraint, if possible.
Definition at line 776 of file PredicateInfo.cpp.
References llvm::cast(), Condition, llvm::dyn_cast(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getInversePredicate(), llvm::ConstantInt::getTrue(), llvm::CmpInst::ICMP_EQ, llvm_unreachable, llvm::PT_Assume, llvm::PT_Branch, llvm::PT_Switch, RenamedOp, and Type.
operator=()
PredicateBase & llvm::PredicateBase::operator= (const PredicateBase &) delete
References PredicateBase().
Member Data Documentation
Condition
Value* llvm::PredicateBase::Condition
Definition at line 93 of file PredicateInfo.h.
Referenced by getConstraint(), llvm::PredicateAssume::PredicateAssume(), PredicateBase(), and llvm::PredicateBranch::PredicateBranch().
OriginalOp
Value* llvm::PredicateBase::OriginalOp
Definition at line 87 of file PredicateInfo.h.
Referenced by PredicateBase().
RenamedOp
Value* llvm::PredicateBase::RenamedOp
Definition at line 91 of file PredicateInfo.h.
Referenced by getConstraint().
Type
PredicateType llvm::PredicateBase::Type
Definition at line 83 of file PredicateInfo.h.
Referenced by getConstraint(), and PredicateBase().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/PredicateInfo.h
lib/Transforms/Utils/PredicateInfo.cpp