LLVM: llvm::dxil::ResourceTypeInfo Class Reference
llvm::dxil::ResourceTypeInfo Class Reference
#include "llvm/Analysis/DXILResource.h"
Classes
struct StructInfo
struct TypedInfo
struct UAVInfo
Public Member Functions
ResourceTypeInfo (TargetExtType *HandleTy, const dxil::ResourceClass RC, const dxil::ResourceKind Kind, bool GloballyCoherent=false, bool HasCounter=false)
ResourceTypeInfo (TargetExtType *HandleTy, bool GloballyCoherent=false, bool HasCounter=false)
TargetExtType * getHandleTy () const
StructType * createElementStruct ()
bool isUAV () const
bool isCBuffer () const
bool isSampler () const
bool isStruct () const
bool isTyped () const
bool isFeedback () const
bool isMultiSample () const
UAVInfo getUAV () const
uint32_t getCBufferSize (const DataLayout &DL) const
dxil::SamplerType getSamplerType () const
StructInfo getStruct (const DataLayout &DL) const
TypedInfo getTyped () const
dxil::SamplerFeedbackType getFeedbackType () const
uint32_t getMultiSampleCount () const
dxil::ResourceClass getResourceClass () const
dxil::ResourceKind getResourceKind () const
void setGloballyCoherent (bool V)
void setHasCounter (bool V)
bool operator== (const ResourceTypeInfo &RHS) const
bool operator!= (const ResourceTypeInfo &RHS) const
bool operator< (const ResourceTypeInfo &RHS) const
void print (raw_ostream &OS, const DataLayout &DL) const
Detailed Description
Definition at line 202 of file DXILResource.h.
Constructor & Destructor Documentation
ResourceTypeInfo() [1/2]
ResourceTypeInfo::ResourceTypeInfo (TargetExtType * HandleTy, const dxil::ResourceClass RC, const dxil::ResourceKind Kind, bool GloballyCoherent = false, bool HasCounter = false)
Definition at line 180 of file DXILResource.cpp.
References llvm::dxil::CBuffer, llvm::dyn_cast(), llvm::dxil::Invalid, llvm::isa(), llvm_unreachable, llvm::dxil::RawBuffer, llvm::dxil::Sampler, llvm::dxil::SRV, llvm::dxil::StructuredBuffer, llvm::dxil::TypedBuffer, and llvm::dxil::UAV.
Referenced by operator!=(), operator<(), operator==(), and ResourceTypeInfo().
ResourceTypeInfo() [2/2]
llvm::dxil::ResourceTypeInfo::ResourceTypeInfo (TargetExtType * HandleTy, bool GloballyCoherent = false, bool HasCounter = false) inline
Definition at line 268 of file DXILResource.h.
References ResourceTypeInfo().
Member Function Documentation
createElementStruct()
StructType * ResourceTypeInfo::createElementStruct ()
Definition at line 225 of file DXILResource.cpp.
References llvm::cast(), llvm::dxil::CBuffer, llvm::StructType::create(), llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, formatTypeName(), llvm::formatv(), llvm::Type::getInt32Ty(), getResourceKindName(), llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, llvm::to_underlying(), and llvm::dxil::TypedBuffer.
getCBufferSize()
uint32_t ResourceTypeInfo::getCBufferSize (const DataLayout & DL) const
Definition at line 383 of file DXILResource.cpp.
References assert(), llvm::cast(), DL, and isCBuffer().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
getFeedbackType()
dxil::SamplerFeedbackType ResourceTypeInfo::getFeedbackType () const
Definition at line 455 of file DXILResource.cpp.
References assert(), llvm::cast(), and isFeedback().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
getHandleTy()
TargetExtType * llvm::dxil::ResourceTypeInfo::getHandleTy () const inline
Definition at line 273 of file DXILResource.h.
Referenced by calculateGEPOffset(), createTypedBufferLoad(), and createTypedBufferStore().
getMultiSampleCount()
uint32_t ResourceTypeInfo::getMultiSampleCount () const
Definition at line 459 of file DXILResource.cpp.
References assert(), llvm::cast(), and isMultiSample().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
getResourceClass()
dxil::ResourceClass llvm::dxil::ResourceTypeInfo::getResourceClass () const inline
Definition at line 294 of file DXILResource.h.
Referenced by prettyPrintResources().
getResourceKind()
dxil::ResourceKind llvm::dxil::ResourceTypeInfo::getResourceKind () const inline
Definition at line 295 of file DXILResource.h.
Referenced by createLoadIntrinsic(), createStoreIntrinsic(), llvm::dxil::ResourceBindingInfo::getAnnotateProps(), and llvm::dxil::ResourceBindingInfo::getAsMetadata().
getSamplerType()
dxil::SamplerType ResourceTypeInfo::getSamplerType () const
Definition at line 388 of file DXILResource.cpp.
References assert(), llvm::cast(), and isSampler().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
getStruct()
ResourceTypeInfo::StructInfo ResourceTypeInfo::getStruct (const DataLayout & DL) const
Definition at line 394 of file DXILResource.cpp.
References assert(), llvm::cast(), DL, llvm::dyn_cast(), isStruct(), and llvm::Log2().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
getTyped()
ResourceTypeInfo::TypedInfo ResourceTypeInfo::getTyped () const
Definition at line 444 of file DXILResource.cpp.
References assert(), llvm::Count, llvm::dyn_cast(), getTypedElementType(), isTyped(), and toDXILElementType().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getFormatName(), operator<(), and print().
getUAV()
ResourceTypeInfo::UAVInfo ResourceTypeInfo::getUAV () const
Definition at line 378 of file DXILResource.cpp.
References assert(), isROV(), and isUAV().
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), operator<(), and print().
isCBuffer()
bool ResourceTypeInfo::isCBuffer () const
Definition at line 296 of file DXILResource.cpp.
References llvm::dxil::CBuffer.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getCBufferSize(), getFormatName(), operator<(), and print().
isFeedback()
bool ResourceTypeInfo::isFeedback () const
Definition at line 337 of file DXILResource.cpp.
References llvm::dxil::FeedbackTexture2D, and llvm::dxil::FeedbackTexture2DArray.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getFeedbackType(), operator<(), and print().
isMultiSample()
bool ResourceTypeInfo::isMultiSample () const
Definition at line 342 of file DXILResource.cpp.
References llvm::dxil::Texture2DMS, and llvm::dxil::Texture2DMSArray.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getMultiSampleCount(), operator<(), and print().
isSampler()
bool ResourceTypeInfo::isSampler () const
Definition at line 300 of file DXILResource.cpp.
References llvm::dxil::Sampler.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getFormatName(), getSamplerType(), operator<(), and print().
isStruct()
bool ResourceTypeInfo::isStruct () const
Definition at line 304 of file DXILResource.cpp.
References llvm::dxil::StructuredBuffer.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getFormatName(), getStruct(), operator<(), and print().
isTyped()
bool ResourceTypeInfo::isTyped () const
Definition at line 308 of file DXILResource.cpp.
References llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by calculateGEPOffset(), llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getFormatName(), getTyped(), operator<(), and print().
isUAV()
bool ResourceTypeInfo::isUAV () const
Definition at line 294 of file DXILResource.cpp.
References llvm::dxil::UAV.
Referenced by llvm::dxil::ResourceBindingInfo::getAnnotateProps(), llvm::dxil::ResourceBindingInfo::getAsMetadata(), getUAV(), operator<(), and print().
operator!=()
bool llvm::dxil::ResourceTypeInfo::operator!= (const ResourceTypeInfo & RHS) const inline
Definition at line 301 of file DXILResource.h.
References ResourceTypeInfo(), and RHS.
operator<()
bool ResourceTypeInfo::operator< (const ResourceTypeInfo & RHS) const
Definition at line 469 of file DXILResource.cpp.
References getCBufferSize(), getFeedbackType(), getMultiSampleCount(), getSamplerType(), getStruct(), getTyped(), getUAV(), isCBuffer(), isFeedback(), isMultiSample(), isSampler(), isStruct(), isTyped(), isUAV(), and ResourceTypeInfo().
operator==()
bool ResourceTypeInfo::operator== (const ResourceTypeInfo & RHS) const
Definition at line 464 of file DXILResource.cpp.
References ResourceTypeInfo().
print()
void ResourceTypeInfo::print (raw_ostream & OS, const DataLayout & DL) const
Definition at line 495 of file DXILResource.cpp.
References DL, llvm::dxil::ResourceTypeInfo::TypedInfo::ElementCount, llvm::dxil::ResourceTypeInfo::TypedInfo::ElementTy, getCBufferSize(), getElementTypeName(), getFeedbackType(), getMultiSampleCount(), getResourceClassName(), getResourceKindName(), getSamplerFeedbackTypeName(), getSamplerType(), getSamplerTypeName(), getStruct(), getTyped(), getUAV(), llvm::dxil::ResourceTypeInfo::UAVInfo::GloballyCoherent, llvm::dxil::ResourceTypeInfo::UAVInfo::HasCounter, isCBuffer(), isFeedback(), isMultiSample(), llvm::dxil::ResourceTypeInfo::UAVInfo::IsROV, isSampler(), isStruct(), isTyped(), isUAV(), and Struct.
Referenced by llvm::dxil::ResourceBindingInfo::print().
setGloballyCoherent()
void llvm::dxil::ResourceTypeInfo::setGloballyCoherent (bool V) inline
Definition at line 297 of file DXILResource.h.
setHasCounter()
void llvm::dxil::ResourceTypeInfo::setHasCounter (bool V) inline
Definition at line 298 of file DXILResource.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp