LLVM: llvm::MCExpr Class Reference
llvm::MCExpr Class Reference
Base class for the full range of assembler expressions which are needed for parsing.
#include "llvm/MC/MCExpr.h"
Public Types
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
Accessors
ExprKind getKind () const
SMLoc getLoc () const
Utility Methods
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool isSymbolUsedInExpression (const MCSymbol *Sym) const
Returns whether the given symbol is used anywhere in the expression or subexpressions.
Expression Evaluation
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAssembler &Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
bool evaluateAsRelocatable (MCValue &Res, const MCAssembler *Asm, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAssembler &Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Protected Member Functions
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Base class for the full range of assembler expressions which are needed for parsing.
Definition at line 34 of file MCExpr.h.
Member Enumeration Documentation
ExprKind
enum llvm::MCExpr::ExprKind : uint8_t
Enumerator
Binary
Binary expressions.
Constant
Constant expressions.
SymbolRef
References to labels and assigned expressions.
Unary
Unary expressions.
Target
Target specific expression.
Definition at line 36 of file MCExpr.h.
Constructor & Destructor Documentation
MCExpr() [1/2]
llvm::MCExpr::MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData = 0) inline explicit protected
Definition at line 59 of file MCExpr.h.
References assert().
Referenced by llvm::MCBinaryExpr::classof(), llvm::MCConstantExpr::classof(), llvm::MCSymbolRefExpr::classof(), llvm::MCTargetExpr::classof(), llvm::MCUnaryExpr::classof(), llvm::MCBinaryExpr::create(), llvm::MCUnaryExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createAnd(), llvm::MCBinaryExpr::createAShr(), llvm::MCBinaryExpr::createDiv(), llvm::MCBinaryExpr::createEQ(), llvm::MCBinaryExpr::createGT(), llvm::MCBinaryExpr::createGTE(), llvm::MCBinaryExpr::createLAnd(), llvm::MCUnaryExpr::createLNot(), llvm::MCBinaryExpr::createLOr(), llvm::MCBinaryExpr::createLShr(), llvm::MCBinaryExpr::createLT(), llvm::MCBinaryExpr::createLTE(), llvm::MCUnaryExpr::createMinus(), llvm::MCBinaryExpr::createMod(), llvm::MCBinaryExpr::createMul(), llvm::MCBinaryExpr::createNE(), llvm::MCUnaryExpr::createNot(), llvm::MCBinaryExpr::createOr(), llvm::MCUnaryExpr::createPlus(), llvm::MCBinaryExpr::createShl(), llvm::MCBinaryExpr::createSub(), llvm::MCBinaryExpr::createXor(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCTargetExpr::isEqualTo(), isSymbolUsedInExpression(), MCExpr(), llvm::MCTargetExpr::MCTargetExpr(), and operator=().
MCExpr() [2/2]
llvm::MCExpr::MCExpr (const MCExpr &) delete
References MCExpr().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void MCExpr::dump () const
Definition at line 174 of file MCExpr.cpp.
References llvm::dbgs(), and LLVM_DUMP_METHOD.
evaluateAsAbsolute() [1/4]
bool MCExpr::evaluateAsAbsolute (int64_t & Res) const
Definition at line 577 of file MCExpr.cpp.
evaluateAsAbsolute() [2/4]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAssembler & Asm) const
Definition at line 588 of file MCExpr.cpp.
evaluateAsAbsolute() [3/4]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAssembler & Asm, const SectionAddrMap & Addrs) const
Try to evaluate the expression to an absolute value.
Parameters
Res - The absolute value, if evaluation succeeds.
Returns
- True on success.
Definition at line 581 of file MCExpr.cpp.
Referenced by targetOpKnownBitsMapHelper().
evaluateAsAbsolute() [4/4]
bool MCExpr::evaluateAsAbsolute (int64_t & Res, const MCAssembler * Asm) const
Definition at line 592 of file MCExpr.cpp.
evaluateAsRelocatable()
bool MCExpr::evaluateAsRelocatable (MCValue & Res, const MCAssembler * Asm, const MCFixup * Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
an expression of the fixed form (a - b + constant).
Parameters
Res - The relocatable value, if evaluation succeeds.
Asm - The assembler object to use for evaluating values.
Fixup - The Fixup object if available.
Returns
- True on success.
Definition at line 819 of file MCExpr.cpp.
References evaluateAsRelocatableImpl(), and Fixup.
Referenced by llvm::DelayedMCExprs::assignDocNode(), llvm::AVRMCExpr::evaluateAsConstant(), llvm::PPCMCExpr::evaluateAsConstant(), llvm::RISCVMCExpr::evaluateAsConstant(), llvm::AArch64AuthMCExpr::evaluateAsRelocatableImpl(), llvm::AArch64MCExpr::evaluateAsRelocatableImpl(), llvm::AMDGPUMCExpr::evaluateAsRelocatableImpl(), llvm::CSKYMCExpr::evaluateAsRelocatableImpl(), llvm::LanaiMCExpr::evaluateAsRelocatableImpl(), llvm::LoongArchMCExpr::evaluateAsRelocatableImpl(), llvm::MipsMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVMCExpr::evaluateAsRelocatableImpl(), llvm::SparcMCExpr::evaluateAsRelocatableImpl(), llvm::SystemZMCExpr::evaluateAsRelocatableImpl(), llvm::VEMCExpr::evaluateAsRelocatableImpl(), llvm::XtensaMCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateTargetFixup(), getOffsetAndDataFragment(), llvm::RISCVMCExpr::getPCRelHiFixup(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAssembler::isThumbFunc(), and llvm::DelayedMCExprs::resolveDelayedExpressions().
evaluateAsRelocatableImpl()
bool MCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm, const MCFixup * Fixup, const SectionAddrMap * Addrs, bool InSet) const protected
-(a - b + const) ==> (b - a - const)
Definition at line 844 of file MCExpr.cpp.
References A(), llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, llvm::MCBinaryExpr::AShr, B(), Binary, canExpand(), llvm::cast(), Constant, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::Div, llvm::dyn_cast(), llvm::MCBinaryExpr::EQ, evaluateAsRelocatableImpl(), evaluateSymbolicAdd(), Fixup, llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getOpcode(), llvm::MCUnaryExpr::getOpcode(), llvm::MCValue::getRefKind(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isVariable(), llvm::MCBinaryExpr::LAnd, llvm_unreachable, llvm::MCUnaryExpr::LNot, llvm::MCBinaryExpr::LOr, llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, llvm::MCUnaryExpr::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCUnaryExpr::Not, llvm::MCBinaryExpr::Or, llvm::MCBinaryExpr::OrNot, llvm::MCUnaryExpr::Plus, llvm::MCBinaryExpr::Shl, llvm::MCBinaryExpr::Sub, SymbolRef, Target, Unary, llvm::MCSymbolRefExpr::VK_None, and llvm::MCBinaryExpr::Xor.
Referenced by evaluateAsRelocatable(), evaluateAsRelocatableImpl(), and evaluateAsValue().
evaluateAsValue()
bool MCExpr::evaluateAsValue (MCValue & Res, const MCAssembler & Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
This is a more aggressive variant of evaluateAsRelocatable. The intended use is for when relocations are not available, like the .size directive.
Definition at line 824 of file MCExpr.cpp.
References evaluateAsRelocatableImpl().
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::MCAssembler::getBaseSymbol(), and getSymbolOffsetImpl().
evaluateKnownAbsolute()
bool MCExpr::evaluateKnownAbsolute (int64_t & Res, const MCAssembler & Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
.fill). Expects callers to handle errors when true is returned.
Definition at line 596 of file MCExpr.cpp.
Referenced by computeLabelDiff(), llvm::LoongArchAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::LoongArchAsmBackend::relaxDwarfLineAddr(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::LoongArchAsmBackend::relaxLEB128(), and llvm::RISCVAsmBackend::relaxLEB128().
findAssociatedFragment()
MCFragment * MCExpr::findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Definition at line 1060 of file MCExpr.cpp.
References llvm::MCSymbol::AbsolutePseudoFragment, Binary, llvm::cast(), Constant, findAssociatedFragment(), llvm::MCSymbol::getFragment(), getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCBinaryExpr::Sub, SymbolRef, Target, and Unary.
Referenced by llvm::AMDGPUMCExpr::findAssociatedFragment(), llvm::ARMMCExpr::findAssociatedFragment(), llvm::AVRMCExpr::findAssociatedFragment(), llvm::CSKYMCExpr::findAssociatedFragment(), llvm::LanaiMCExpr::findAssociatedFragment(), llvm::LoongArchMCExpr::findAssociatedFragment(), findAssociatedFragment(), llvm::MipsMCExpr::findAssociatedFragment(), llvm::PPCMCExpr::findAssociatedFragment(), llvm::RISCVMCExpr::findAssociatedFragment(), llvm::SparcMCExpr::findAssociatedFragment(), llvm::SystemZMCExpr::findAssociatedFragment(), llvm::VEMCExpr::findAssociatedFragment(), llvm::XtensaMCExpr::findAssociatedFragment(), and llvm::MCSymbol::getFragment().
getKind()
ExprKind llvm::MCExpr::getKind () const inline
Definition at line 78 of file MCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), getAccessVariant(), llvm::CSKYMCCodeEmitter::getBareSymbolOpValue(), llvm::CSKYMCCodeEmitter::getBranchSymbolOpValue(), llvm::CSKYMCCodeEmitter::getCallSymbolOpValue(), llvm::CSKYMCCodeEmitter::getConstpoolSymbolOpValue(), llvm::CSKYMCCodeEmitter::getDataSymbolOpValue(), llvm::PPCMCCodeEmitter::getDispRI34PCRelEncoding(), llvm::MipsMCCodeEmitter::getExprOpValue(), hasGOTReference(), hasSecRelSymbolRef(), hasVariantSymbol(), llvm::MCOperand::isBareSymbolRef(), isEvaluated(), isSymbolUsedInExpression(), knownBitsMapHelper(), needsExpandMemInst(), needsPCRel(), print(), llvm::X86Operand::print(), llvm::ARMInstPrinter::printOperand(), startsWithGlobalOffsetTable(), tryFoldHelper(), and llvm::MCStreamer::visitUsedExpr().
getLoc()
SMLoc llvm::MCExpr::getLoc () const inline
Definition at line 79 of file MCExpr.h.
Referenced by llvm::MCAssembler::getBaseSymbol(), llvm::MipsMCCodeEmitter::getExprOpValue(), llvm::LoongArchAsmBackend::relaxLEB128(), llvm::RISCVAsmBackend::relaxLEB128(), llvm::MCStreamer::switchSection(), and tryFoldHelper().
getSubclassData()
unsigned llvm::MCExpr::getSubclassData () const inline protected
Definition at line 69 of file MCExpr.h.
Referenced by llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getOpcode(), llvm::MCUnaryExpr::getOpcode(), llvm::MCConstantExpr::getSizeInBytes(), llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols(), and llvm::MCConstantExpr::useHexFormat().
isSymbolUsedInExpression()
bool MCExpr::isSymbolUsedInExpression (const MCSymbol * Sym) const
Returns whether the given symbol is used anywhere in the expression or subexpressions.
Definition at line 180 of file MCExpr.cpp.
References Binary, Constant, getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbol::getVariableValue(), isSymbolUsedInExpression(), llvm::MCSymbol::isVariable(), llvm::MCSymbol::isWeakExternal(), llvm_unreachable, MCExpr(), SymbolRef, Target, and Unary.
Referenced by llvm::MCResourceInfo::gatherResourceInfo(), and isSymbolUsedInExpression().
operator=()
MCExpr & llvm::MCExpr::operator= (const MCExpr &) delete
References MCExpr().
print()
void MCExpr::print (raw_ostream & OS, const MCAsmInfo * MAI, bool InParens = false) const
Definition at line 40 of file MCExpr.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, llvm::MCBinaryExpr::AShr, Binary, llvm::cast(), Constant, llvm::MCBinaryExpr::Div, llvm::dyn_cast(), llvm::MCBinaryExpr::EQ, llvm::format(), getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getOpcode(), llvm::MCUnaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbolRefExpr::getVariantKindName(), llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::isa(), llvm::MCBinaryExpr::LAnd, llvm_unreachable, llvm::MCUnaryExpr::LNot, llvm::MCBinaryExpr::LOr, llvm::MCBinaryExpr::LShr, llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, llvm::MCUnaryExpr::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCUnaryExpr::Not, llvm::MCBinaryExpr::Or, llvm::MCBinaryExpr::OrNot, llvm::MCUnaryExpr::Plus, print(), llvm::MCSymbol::print(), llvm::MCBinaryExpr::Shl, llvm::StringRef::starts_with(), llvm::MCBinaryExpr::Sub, SymbolRef, Target, Unary, llvm::MCAsmInfo::useParensForDollarSignNames(), llvm::MCAsmInfo::useParensForSymbolVariant(), llvm::Twine::utohexstr(), llvm::Value, llvm::MCSymbolRefExpr::VK_None, and llvm::MCBinaryExpr::Xor.
Referenced by print(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::ARMInstPrinter::printAdrLabelOperand(), llvm::AMDGPU::printAMDGPUMCExpr(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::CSKYInstPrinter::printConstpool(), llvm::CSKYInstPrinter::printDataSymbol(), llvm::AArch64AuthMCExpr::printImpl(), llvm::AVRMCExpr::printImpl(), llvm::HexagonMCExpr::printImpl(), llvm::MipsMCExpr::printImpl(), llvm::PPCMCExpr::printImpl(), llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), printMemoryImmediateOffset(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::ARMInstPrinter::printOperand(), llvm::CSKYInstPrinter::printOperand(), llvm::RISCVInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::SystemZInstPrinterCommon::printOperand(), llvm::VEInstPrinter::printOperand(), printOperand(), llvm::SystemZInstPrinterCommon::printPCRelOperand(), llvm::ARMInstPrinter::printThumbLdrLabelOperand(), llvm::PPCInstPrinter::printTLSCall(), and llvm::AArch64InstPrinter::printUImm12Offset().
The documentation for this class was generated from the following files:
include/llvm/MC/MCExpr.h
lib/MC/MCExpr.cpp