LLVM: llvm::MachineModuleInfo Class Reference
llvm::MachineModuleInfo Class Reference
This class contains meta information specific to a module.
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Member Functions
MachineModuleInfo (const TargetMachine *TM=nullptr)
MachineModuleInfo (const TargetMachine *TM, MCContext *ExtContext)
MachineModuleInfo (MachineModuleInfo &&MMII)
~MachineModuleInfo ()
void initialize ()
void finalize ()
const TargetMachine & getTarget () const
const MCContext & getContext () const
MCContext & getContext ()
const Module * getModule () const
MachineFunction & getOrCreateMachineFunction (Function &F)
Returns the MachineFunction constructed for the IR function F.
MachineFunction * getMachineFunction (const Function &F) const
Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
void deleteMachineFunctionFor (Function &F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
void insertFunction (const Function &F, std::unique_ptr< MachineFunction > &&MF)
Add an externally created MachineFunction MF for F.
template<typename Ty>
Ty & getObjFileInfo ()
Keep track of various per-module pieces of information for backends that would like to do so.
template<typename Ty>
const Ty & getObjFileInfo () const
Friends
class MachineModuleInfoWrapperPass
class MachineModuleAnalysis
Detailed Description
This class contains meta information specific to a module.
Queries can be made by different debugging and exception handling schemes and reformated for specific use.
Definition at line 82 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
MachineModuleInfo() [1/3]
MachineModuleInfo::MachineModuleInfo (const TargetMachine * TM = nullptr) explicit
Definition at line 51 of file MachineModuleInfo.cpp.
References initialize(), and Options.
Referenced by getObjFileInfo(), MachineModuleAnalysis, and MachineModuleInfo().
MachineModuleInfo() [2/3]
MachineModuleInfo::MachineModuleInfo (const TargetMachine * TM, MCContext * ExtContext) explicit
Definition at line 59 of file MachineModuleInfo.cpp.
References initialize(), and Options.
MachineModuleInfo() [3/3]
MachineModuleInfo::MachineModuleInfo (MachineModuleInfo && MMII)
Definition at line 40 of file MachineModuleInfo.cpp.
References MachineModuleInfo(), llvm::move(), and Options.
~MachineModuleInfo()
MachineModuleInfo::~MachineModuleInfo ()
Definition at line 69 of file MachineModuleInfo.cpp.
References finalize().
Member Function Documentation
deleteMachineFunctionFor()
void MachineModuleInfo::deleteMachineFunctionFor (Function & F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
Definition at line 106 of file MachineModuleInfo.cpp.
References llvm::MachineFunction::erase(), and F.
finalize()
void MachineModuleInfo::finalize ()
Definition at line 32 of file MachineModuleInfo.cpp.
Referenced by ~MachineModuleInfo().
getContext() [1/2]
MCContext & llvm::MachineModuleInfo::getContext () inline
Definition at line 128 of file MachineModuleInfo.h.
getContext() [2/2]
const MCContext & llvm::MachineModuleInfo::getContext () const inline
Definition at line 125 of file MachineModuleInfo.h.
Referenced by llvm::CodeGenTargetMachineImpl::addPassesToEmitFile(), llvm::DirectXTargetMachine::addPassesToEmitFile(), llvm::CodeGenTargetMachineImpl::addPassesToEmitMC(), EmitInlineAsmStr(), emitNonLazyStubs(), and getOrCreateMachineFunction().
getMachineFunction()
MachineFunction * MachineModuleInfo::getMachineFunction (const Function & F) const
Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
NOTE: New pass manager clients shall not use this method to get the MachineFunction, use MachineFunctionAnalysis instead.
Definition at line 72 of file MachineModuleInfo.cpp.
References F, and I.
Referenced by llvm::ARMBaseInstrInfo::getOutliningTypeImpl(), and llvm::MIRParserImpl::parseMachineFunction().
getModule()
const Module * llvm::MachineModuleInfo::getModule () const inline
Definition at line 132 of file MachineModuleInfo.h.
Referenced by llvm::AMDGPUMachineModuleInfo::AMDGPUMachineModuleInfo(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), getAuthPtrSlotSymbolHelper(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), and llvm::MachineModuleInfoELF::MachineModuleInfoELF().
getObjFileInfo() [1/2]
template<typename Ty> Ty & llvm::MachineModuleInfo::getObjFileInfo () inline
Keep track of various per-module pieces of information for backends that would like to do so.
Definition at line 156 of file MachineModuleInfo.h.
Referenced by emitNonLazyStubs(), llvm::AArch64_ELFTargetObjectFile::emitPersonalityValueImpl(), llvm::AArch64_ELFTargetObjectFile::getAuthPtrSlotSymbol(), llvm::AArch64_MachoTargetObjectFile::getAuthPtrSlotSymbol(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getObjFileInfo(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
getObjFileInfo() [2/2]
template<typename Ty> const Ty & llvm::MachineModuleInfo::getObjFileInfo () const inline
Definition at line 163 of file MachineModuleInfo.h.
References getObjFileInfo(), and MachineModuleInfo().
getOrCreateMachineFunction()
MachineFunction & MachineModuleInfo::getOrCreateMachineFunction (Function & F)
Returns the MachineFunction constructed for the IR function F.
Creates a new MachineFunction if none exists yet. NOTE: New pass manager clients shall not use this method to get the MachineFunction, use MachineFunctionAnalysis instead.
Definition at line 77 of file MachineModuleInfo.cpp.
References F, getContext(), I, and llvm::MachineFunction::initTargetMachineFunctionInfo().
Referenced by createFrameHelperMachineFunction(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), and llvm::MIRParserImpl::parseMachineFunction().
getTarget()
const TargetMachine & llvm::MachineModuleInfo::getTarget () const inline
Definition at line 123 of file MachineModuleInfo.h.
Referenced by EmitInlineAsmStr(), and llvm::MIRParserImpl::parseMachineFunction().
initialize()
void MachineModuleInfo::initialize ()
Definition at line 27 of file MachineModuleInfo.cpp.
Referenced by MachineModuleInfo(), and MachineModuleInfo().
insertFunction()
void MachineModuleInfo::insertFunction (const Function & F, std::unique_ptr< MachineFunction > && MF)
Add an externally created MachineFunction MF for F.
Definition at line 112 of file MachineModuleInfo.cpp.
References assert(), F, and I.
Friends And Related Symbol Documentation
MachineModuleAnalysis
friend class MachineModuleAnalysis friend
Definition at line 84 of file MachineModuleInfo.h.
References MachineModuleAnalysis, and MachineModuleInfo().
Referenced by MachineModuleAnalysis.
MachineModuleInfoWrapperPass
friend class MachineModuleInfoWrapperPass friend
Definition at line 83 of file MachineModuleInfo.h.
References MachineModuleInfoWrapperPass.
Referenced by MachineModuleInfoWrapperPass.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp