LLVM: llvm::MCDwarfFrameEmitter Class Reference
llvm::MCDwarfFrameEmitter Class Reference
#include "llvm/MC/MCDwarf.h"
Static Public Member Functions
static void Emit (MCObjectStreamer &streamer, MCAsmBackend *MAB, bool isEH)
static void encodeAdvanceLoc (MCContext &Context, uint64_t AddrDelta, SmallVectorImpl< char > &OS)
Detailed Description
Definition at line 778 of file MCDwarf.h.
Member Function Documentation
Emit()
void MCDwarfFrameEmitter::Emit (MCObjectStreamer & streamer, MCAsmBackend * MAB, bool isEH) static
Definition at line 1881 of file MCDwarf.cpp.
References llvm::ArrayRef< T >::begin(), llvm::MCDwarfFrameInfo::CompactUnwindEncoding, llvm::MCObjectStreamer::emitLabel(), Emitter, llvm::MCObjectStreamer::emitValueToAlignment(), llvm::ArrayRef< T >::end(), llvm::MCStreamer::generateCompactUnwindEncodings(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCObjectFileInfo::getCompactUnwindDwarfEHFrameOnly(), llvm::MCObjectFileInfo::getCompactUnwindSection(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCObjectFileInfo::getDwarfFrameSection(), llvm::MCObjectFileInfo::getOmitDwarfIfHaveCompactUnwind(), llvm::MCObjectFileInfo::getSupportsCompactUnwindWithoutEHFrame(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::stable_sort(), llvm::MCStreamer::switchSection(), X, and Y.
Referenced by llvm::MCObjectStreamer::emitFrames().
encodeAdvanceLoc()
void MCDwarfFrameEmitter::encodeAdvanceLoc (MCContext & Context, uint64_t AddrDelta, SmallVectorImpl< char > & OS) static
Definition at line 1957 of file MCDwarf.cpp.
References assert(), llvm::big, llvm::isUInt(), llvm::isUIntN(), llvm::little, llvm::SmallVectorTemplateBase< T, bool >::push_back(), ScaleAddrDelta(), and llvm::support::endian::write().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp