LLVM: llvm::RegUsageInfoCollectorPass Class Reference
llvm::RegUsageInfoCollectorPass Class Reference
#include "llvm/CodeGen/RegUsageInfoCollector.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< RegUsageInfoCollectorPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< RegUsageInfoCollectorPass >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< RegUsageInfoCollectorPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file RegUsageInfoCollector.h.
Member Function Documentation
run()
PreservedAnalyses RegUsageInfoCollectorPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 108 of file RegUsageInfoCollector.cpp.
References llvm::PreservedAnalyses::all(), assert(), llvm::MachineFunction::getFunction(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and RegUsageInfoCollector.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegUsageInfoCollector.h
lib/CodeGen/RegUsageInfoCollector.cpp