LLVM: llvm::SmallPtrSetIteratorImpl Class Reference
llvm::SmallPtrSetIteratorImpl Class Reference
SmallPtrSetIteratorImpl - This is the common base class shared between all instances of SmallPtrSetIterator.
#include "llvm/ADT/SmallPtrSet.h"
Public Member Functions
SmallPtrSetIteratorImpl (const void *const *BP, const void *const *E)
bool operator== (const SmallPtrSetIteratorImpl &RHS) const
bool operator!= (const SmallPtrSetIteratorImpl &RHS) const
Protected Member Functions
void AdvanceIfNotValid ()
AdvanceIfNotValid - If the current bucket isn't valid, advance to a bucket that is.
void RetreatIfNotValid ()
Protected Attributes
const void *const * Bucket
const void *const * End
Detailed Description
SmallPtrSetIteratorImpl - This is the common base class shared between all instances of SmallPtrSetIterator.
Definition at line 265 of file SmallPtrSet.h.
Constructor & Destructor Documentation
SmallPtrSetIteratorImpl()
llvm::SmallPtrSetIteratorImpl::SmallPtrSetIteratorImpl (const void *const * BP, const void *const * E) inline explicit
Definition at line 271 of file SmallPtrSet.h.
References AdvanceIfNotValid(), Bucket, E(), End, RetreatIfNotValid(), and llvm::shouldReverseIterate().
Referenced by operator!=(), operator==(), and llvm::SmallPtrSetIterator< PtrType >::SmallPtrSetIterator().
Member Function Documentation
AdvanceIfNotValid()
void llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid () inline protected
AdvanceIfNotValid - If the current bucket isn't valid, advance to a bucket that is.
This is guaranteed to stop because the end() bucket is marked valid.
Definition at line 291 of file SmallPtrSet.h.
References assert(), Bucket, End, llvm::SmallPtrSetImplBase::getEmptyMarker(), and llvm::SmallPtrSetImplBase::getTombstoneMarker().
Referenced by llvm::SmallPtrSetIterator< PtrType >::operator++(), and SmallPtrSetIteratorImpl().
operator!=()
bool llvm::SmallPtrSetIteratorImpl::operator!= (const SmallPtrSetIteratorImpl & RHS) const inline
Definition at line 283 of file SmallPtrSet.h.
References Bucket, RHS, and SmallPtrSetIteratorImpl().
operator==()
bool llvm::SmallPtrSetIteratorImpl::operator== (const SmallPtrSetIteratorImpl & RHS) const inline
Definition at line 280 of file SmallPtrSet.h.
References Bucket, RHS, and SmallPtrSetIteratorImpl().
RetreatIfNotValid()
void llvm::SmallPtrSetIteratorImpl::RetreatIfNotValid () inline protected
Definition at line 298 of file SmallPtrSet.h.
References assert(), Bucket, End, llvm::SmallPtrSetImplBase::getEmptyMarker(), and llvm::SmallPtrSetImplBase::getTombstoneMarker().
Referenced by llvm::SmallPtrSetIterator< PtrType >::operator++(), and SmallPtrSetIteratorImpl().
Member Data Documentation
Bucket
const void* const* llvm::SmallPtrSetIteratorImpl::Bucket protected
Definition at line 267 of file SmallPtrSet.h.
Referenced by AdvanceIfNotValid(), operator!=(), llvm::SmallPtrSetIterator< PtrType >::operator*(), llvm::SmallPtrSetIterator< PtrType >::operator++(), operator==(), RetreatIfNotValid(), and SmallPtrSetIteratorImpl().
End
const void* const* llvm::SmallPtrSetIteratorImpl::End protected
Definition at line 268 of file SmallPtrSet.h.
Referenced by AdvanceIfNotValid(), llvm::SmallPtrSetIterator< PtrType >::operator*(), RetreatIfNotValid(), and SmallPtrSetIteratorImpl().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallPtrSet.h