LLVM: llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT > Class Template Reference
llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Static Public Member Functions
static RetT makeValue ()
static void makeSafe (RetT &Result)
static Error deserialize (RetT &Result, const char *ArgData, size_t ArgSize)
Detailed Description
template<typename SPSRetTagT, typename RetT>
class llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >
Definition at line 377 of file WrapperFunctionUtils.h.
Member Function Documentation
deserialize()
template<typename SPSRetTagT, typename RetT> static Error llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::deserialize (RetT & Result, const char * ArgData, size_t ArgSize) inline static
Definition at line 382 of file WrapperFunctionUtils.h.
References llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::orc::Result, and llvm::Error::success().
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call(), and llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync().
makeSafe()
template<typename SPSRetTagT, typename RetT> static void llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::makeSafe (RetT & Result) inline static
Definition at line 380 of file WrapperFunctionUtils.h.
References llvm::orc::Result.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call(), and llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync().
makeValue()
template<typename SPSRetTagT, typename RetT> static RetT llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::makeValue () inline static
Definition at line 379 of file WrapperFunctionUtils.h.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h