LLVM: llvm::sandboxir::CmpSwapOperands Class Reference
llvm::sandboxir::CmpSwapOperands Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
CmpSwapOperands (CmpInst *Cmp)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 182 of file Tracker.h.
Constructor & Destructor Documentation
CmpSwapOperands()
CmpSwapOperands::CmpSwapOperands (CmpInst * Cmp)
Definition at line 331 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::CmpSwapOperands::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 188 of file Tracker.h.
dump() [1/2]
void CmpSwapOperands::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 335 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::CmpSwapOperands::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 190 of file Tracker.h.
revert()
void CmpSwapOperands::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 333 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp