LLVM: llvm::po_iterator_storage< LoopBounds, true > Class Reference
llvm::po_iterator_storage< LoopBounds, true > Class Reference
Public Member Functions
po_iterator_storage (LoopBounds &lb)
void finishPostorder (const MachineBasicBlock *)
bool insertEdge (std::optional< const MachineBasicBlock * > From, const MachineBasicBlock *To)
bool insertEdge (std::optional< NodeRef > From, NodeRef To)
void finishPostorder (NodeRef BB)
Detailed Description
Definition at line 491 of file MachineTraceMetrics.cpp.
Constructor & Destructor Documentation
po_iterator_storage()
llvm::po_iterator_storage< LoopBounds, true >::po_iterator_storage (LoopBounds & lb) inline
Definition at line 495 of file MachineTraceMetrics.cpp.
Member Function Documentation
finishPostorder() [1/2]
void llvm::po_iterator_storage< LoopBounds, true >::finishPostorder (const MachineBasicBlock *) inline
Definition at line 497 of file MachineTraceMetrics.cpp.
finishPostorder() [2/2]
void llvm::po_iterator_storage< LoopBounds, External >::finishPostorder (NodeRef BB) inline
Definition at line 70 of file PostOrderIterator.h.
insertEdge() [1/2]
bool llvm::po_iterator_storage< LoopBounds, true >::insertEdge (std::optional< const MachineBasicBlock * > From, const MachineBasicBlock * To) inline
Definition at line 499 of file MachineTraceMetrics.cpp.
References llvm::MachineBasicBlock::getNumber(), llvm::MachineTraceMetrics::TraceBlockInfo::hasValidDepth(), llvm::MachineTraceMetrics::TraceBlockInfo::hasValidHeight(), and isExitingLoop().
insertEdge() [2/2]
bool llvm::po_iterator_storage< LoopBounds, External >::insertEdge (std::optional< NodeRef > From, NodeRef To) inline
Definition at line 65 of file PostOrderIterator.h.
The documentation for this class was generated from the following file:
lib/CodeGen/MachineTraceMetrics.cpp