LLVM: llvm::sandboxir::GlobalIFunc Class Reference
llvm::sandboxir::GlobalIFunc Class Reference final
#include "llvm/SandboxIR/Constant.h"
Public Member Functions
void setResolver (Constant *Resolver)
Constant * getResolver () const
Function * getResolverFunction ()
const Function * getResolverFunction () const
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::GlobalWithNodeAPI< GlobalIFunc, llvm::GlobalIFunc, GlobalObject, llvm::GlobalObject >
GlobalWithNodeAPI (Value::ClassID ID, llvm::GlobalObject *C, Context &Ctx)
Module * getParent () const
iterator getIterator () const
reverse_iterator getReverseIterator () const
Public Member Functions inherited from llvm::sandboxir::GlobalObject
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
uint64_t getAlignment () const
FIXME: Remove this function once transition to Align is over.
MaybeAlign getAlign () const
Returns the alignment of the given variable or function.
void setAlignment (MaybeAlign Align)
Sets the alignment attribute of the GlobalObject.
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned V)
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
VCallVisibility getVCallVisibility () const
bool canIncreaseAlignment () const
Returns true if the alignment of the value can be unilaterally increased.
Public Member Functions inherited from llvm::sandboxir::GlobalValue
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr V)
bool hasComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
Type * getType () const
Context & getContext () const
void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
static bool isValidLinkage (LinkageTypes L)
Static Public Member Functions inherited from llvm::sandboxir::GlobalObject
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::GlobalValue
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class Context
Additional Inherited Members
Public Types inherited from llvm::sandboxir::GlobalWithNodeAPI< GlobalIFunc, llvm::GlobalIFunc, GlobalObject, llvm::GlobalObject >
using iterator
using reverse_iterator
Public Types inherited from llvm::sandboxir::GlobalObject
using VCallVisibility = llvm::GlobalObject::VCallVisibility
Public Types inherited from llvm::sandboxir::GlobalValue
using LinkageTypes = llvm::GlobalValue::LinkageTypes
using UnnamedAddr = llvm::GlobalValue::UnnamedAddr
using VisibilityTypes = llvm::GlobalValue::VisibilityTypes
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned { DEF_VALUE , DEF_USER , DEF_CONST , DEF_INSTR }
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::GlobalObject
GlobalObject (ClassID ID, llvm::GlobalObject *C, Context &Ctx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const final
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::GlobalValue
GlobalValue (ClassID ID, llvm::GlobalValue *C, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 820 of file Constant.h.
Member Function Documentation
classof()
static bool llvm::sandboxir::GlobalIFunc::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 829 of file Constant.h.
References llvm::sandboxir::Value::getSubclassID().
dumpOS()
void llvm::sandboxir::GlobalIFunc::dumpOS (raw_ostream & OS) const inline override virtual
Reimplemented from llvm::sandboxir::Constant.
Definition at line 859 of file Constant.h.
References llvm::sandboxir::Value::dumpCommonPrefix(), and llvm::sandboxir::Value::dumpCommonSuffix().
getResolver()
Constant * llvm::sandboxir::GlobalIFunc::getResolver () const
Definition at line 335 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, getResolver(), and llvm::sandboxir::Value::Val.
Referenced by getResolver().
getResolverFunction() [1/2]
Function * llvm::sandboxir::GlobalIFunc::getResolverFunction ()
Definition at line 339 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
Referenced by getResolverFunction().
getResolverFunction() [2/2]
const Function * llvm::sandboxir::GlobalIFunc::getResolverFunction () const inline
Definition at line 845 of file Constant.h.
References getResolverFunction().
isValidLinkage()
static bool llvm::sandboxir::GlobalIFunc::isValidLinkage (LinkageTypes L) inline static
Definition at line 849 of file Constant.h.
References llvm::GlobalIFunc::isValidLinkage().
setResolver()
void llvm::sandboxir::GlobalIFunc::setResolver (Constant * Resolver)
Definition at line 326 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
verify()
void llvm::sandboxir::GlobalIFunc::verify () const inline override virtual
Should crash if there is something wrong with the instruction.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 856 of file Constant.h.
References assert(), llvm::isa(), and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 825 of file Constant.h.
References Context.
Referenced by Context.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Constant.h
lib/SandboxIR/Constant.cpp