LLVM: llvm::SILowerSGPRSpillsPass Class Reference
llvm::SILowerSGPRSpillsPass Class Reference
#include "Target/AMDGPU/SILowerSGPRSpills.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
MachineFunctionProperties getClearedProperties () const
Public Member Functions inherited from llvm::PassInfoMixin< SILowerSGPRSpillsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SILowerSGPRSpillsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 15 of file SILowerSGPRSpills.h.
Member Function Documentation
getClearedProperties()
MachineFunctionProperties llvm::SILowerSGPRSpillsPass::getClearedProperties () const inline
Definition at line 20 of file SILowerSGPRSpills.h.
References llvm::MachineFunctionProperties::IsSSA, llvm::MachineFunctionProperties::NoVRegs, and llvm::MachineFunctionProperties::set().
run()
PreservedAnalyses SILowerSGPRSpillsPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 556 of file SILowerSGPRSpills.cpp.
References _, llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::MachineDominatorTreeAnalysis::run().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SILowerSGPRSpills.h
lib/Target/AMDGPU/SILowerSGPRSpills.cpp