LLVM: llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator Class Reference
llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator Class Reference
#include "llvm/ADT/IntervalMap.h"
Public Types
using iterator_category = std::bidirectional_iterator_tag
using value_type = ValT
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using Allocator
using KeyType
using ValueType
using KeyTraits
Public Member Functions
const_iterator ()=default
const_iterator - Create an iterator that isn't pointing anywhere.
void setMap (const IntervalMap &m)
setMap - Change the map iterated over.
bool valid () const
valid - Return true if the current position is valid, false for end().
bool atBegin () const
atBegin - Return true if the current position is the first map entry.
const KeyT & start () const
start - Return the beginning of the current interval.
const KeyT & stop () const
stop - Return the end of the current interval.
const ValT & value () const
value - Return the mapped value at the current interval.
const ValT & operator* () const
bool operator== (const const_iterator &RHS) const
bool operator!= (const const_iterator &RHS) const
void goToBegin ()
goToBegin - Move to the first interval in map.
void goToEnd ()
goToEnd - Move beyond the last interval in map.
const_iterator & operator++ ()
preincrement - Move to the next interval.
const_iterator operator++ (int)
postincrement - Don't do that!
const_iterator & operator-- ()
predecrement - Move to the previous interval.
const_iterator operator-- (int)
postdecrement - Don't do that!
void find (KeyT x)
find - Move to the first interval with stop >= x, or end().
void advanceTo (KeyT x)
advanceTo - Move to the first interval with stop >= x, or end().
IntervalMap (Allocator &a)
~IntervalMap ()
bool empty () const
empty - Return true when no intervals are mapped.
KeyT start () const
start - Return the smallest mapped key in a non-empty map.
KeyT stop () const
stop - Return the largest mapped key in a non-empty map.
ValT lookup (KeyT x, ValT NotFound=ValT()) const
lookup - Return the mapped value at x or NotFound.
void insert (KeyT a, KeyT b, ValT y)
insert - Add a mapping of [a;b] to y, coalesce with adjacent intervals.
void clear ()
clear - Remove all entries.
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_iterator find (KeyT x) const
find - Return an iterator pointing to the first interval ending at or after x, or end().
iterator find (KeyT x)
bool overlaps (KeyT a, KeyT b) const
overlaps(a, b) - Return true if the intervals in this map overlap with the interval [a;b].
IntervalMap (IntervalMap const &RHS)
IntervalMap (IntervalMap &&RHS)
IntervalMap & operator= (IntervalMap const &RHS)
IntervalMap & operator= (IntervalMap &&RHS)
Public Attributes
RootLeaf leaf
RootBranchData branchData
Protected Member Functions
const_iterator (const IntervalMap &map)
bool branched () const
void setRoot (unsigned Offset)
void pathFillFind (KeyT x)
pathFillFind - Complete path by searching for x.
void treeFind (KeyT x)
treeFind - Find in a branched tree.
void treeAdvanceTo (KeyT x)
treeAdvanceTo - Find position after the current one.
KeyT & unsafeStart () const
unsafeStart - Writable access to start() for iterator.
KeyT & unsafeStop () const
unsafeStop - Writable access to stop() for iterator.
ValT & unsafeValue () const
unsafeValue - Writable access to value() for iterator.
Protected Attributes
IntervalMap * map = nullptr
IntervalMapImpl::Path path
Friends
class IntervalMap
class const_iterator
class iterator
Detailed Description
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>>
class llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator
Definition at line 1343 of file IntervalMap.h.
Member Typedef Documentation
Allocator
using llvm::IntervalMap< KeyT, ValT, N, Traits >::Allocator
Definition at line 962 of file IntervalMap.h.
difference_type
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::difference_type = std::ptrdiff_t
Definition at line 1349 of file IntervalMap.h.
iterator_category
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::iterator_category = std::bidirectional_iterator_tag
Definition at line 1347 of file IntervalMap.h.
KeyTraits
using llvm::IntervalMap< KeyT, ValT, N, Traits >::KeyTraits
Definition at line 965 of file IntervalMap.h.
KeyType
using llvm::IntervalMap< KeyT, ValT, N, Traits >::KeyType
Definition at line 963 of file IntervalMap.h.
pointer
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pointer = value_type *
Definition at line 1350 of file IntervalMap.h.
reference
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::reference = value_type &
Definition at line 1351 of file IntervalMap.h.
value_type
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value_type = ValT
Definition at line 1348 of file IntervalMap.h.
ValueType
using llvm::IntervalMap< KeyT, ValT, N, Traits >::ValueType
Definition at line 964 of file IntervalMap.h.
Constructor & Destructor Documentation
const_iterator() [1/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::const_iterator (const IntervalMap & map) inline explicit protected
Definition at line 1361 of file IntervalMap.h.
References IntervalMap, and map.
Referenced by operator!=(), operator++(), operator++(), operator--(), operator--(), and operator==().
const_iterator() [2/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::const_iterator () default
const_iterator - Create an iterator that isn't pointing anywhere.
~IntervalMap()
llvm::IntervalMap< KeyT, ValT, N, Traits >::~IntervalMap () inline
Definition at line 1095 of file IntervalMap.h.
Member Function Documentation
advanceTo()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo (KeyT x) inline
advanceTo - Move to the first interval with stop >= x, or end().
The search is started from the current position, and no earlier positions can be found. This is much faster than find() for small moves.
Definition at line 1494 of file IntervalMap.h.
References branched(), map, path, treeAdvanceTo(), and valid().
atBegin()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::atBegin () const inline
atBegin - Return true if the current position is the first map entry.
Definition at line 1413 of file IntervalMap.h.
References path.
begin() [1/2]
iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::begin () inline
Definition at line 1152 of file IntervalMap.h.
begin() [2/2]
const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::begin () const inline
Definition at line 1146 of file IntervalMap.h.
branched()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::branched () const inline protected
Definition at line 1364 of file IntervalMap.h.
References assert(), and map.
Referenced by advanceTo(), find(), goToBegin(), operator++(), operator--(), setRoot(), unsafeStart(), unsafeStop(), and unsafeValue().
clear()
void llvm::IntervalMap< KeyT, ValT, N, Traits >::clear ()
clear - Remove all entries.
Definition at line 1139 of file IntervalMap.h.
empty()
bool llvm::IntervalMap< KeyT, ValT, N, Traits >::empty () const inline
empty - Return true when no intervals are mapped.
Definition at line 1101 of file IntervalMap.h.
end() [1/2]
iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::end () inline
Definition at line 1164 of file IntervalMap.h.
end() [2/2]
const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::end () const inline
Definition at line 1158 of file IntervalMap.h.
find() [1/3]
iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::find (KeyT x) inline
Definition at line 1178 of file IntervalMap.h.
find() [2/3]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::find (KeyT x) inline
find - Move to the first interval with stop >= x, or end().
This is a full search from the root, the current position is ignored.
Definition at line 1484 of file IntervalMap.h.
References branched(), map, setRoot(), and treeFind().
find() [3/3]
const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::find (KeyT x) const inline
find - Return an iterator pointing to the first interval ending at or after x, or end().
Definition at line 1172 of file IntervalMap.h.
goToBegin()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToBegin () inline
goToBegin - Move to the first interval in map.
Definition at line 1440 of file IntervalMap.h.
References branched(), map, path, and setRoot().
goToEnd()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToEnd () inline
goToEnd - Move beyond the last interval in map.
Definition at line 1447 of file IntervalMap.h.
References map, and setRoot().
insert()
void llvm::IntervalMap< KeyT, ValT, N, Traits >::insert (KeyT a, KeyT b, ValT y) inline
insert - Add a mapping of [a;b] to y, coalesce with adjacent intervals.
It is assumed that no key in the interval is mapped to another value, but overlapping intervals already mapped to y will be coalesced.
Definition at line 1129 of file IntervalMap.h.
IntervalMap() [1/3]
llvm::IntervalMap< KeyT, ValT, N, Traits >::IntervalMap (Allocator & a) inline explicit
Definition at line 1041 of file IntervalMap.h.
IntervalMap() [2/3]
llvm::IntervalMap< KeyT, ValT, N, Traits >::IntervalMap (IntervalMap && RHS) inline
Definition at line 1063 of file IntervalMap.h.
IntervalMap() [3/3]
llvm::IntervalMap< KeyT, ValT, N, Traits >::IntervalMap (IntervalMap const & RHS) inline
NOTE: The moved-from or copied-from object's allocator needs to have a lifetime equal to or exceeding the moved-to or copied-to object to avoid undefined behaviour.
Definition at line 1049 of file IntervalMap.h.
lookup()
ValT llvm::IntervalMap< KeyT, ValT, N, Traits >::lookup (KeyT x, ValT NotFound = ValT()) const inline
lookup - Return the mapped value at x or NotFound.
Definition at line 1119 of file IntervalMap.h.
operator!=()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator!= (const const_iterator & RHS) const inline
Definition at line 1435 of file IntervalMap.h.
References const_iterator(), operator==(), and RHS.
operator*()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const ValT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator* () const inline
Definition at line 1424 of file IntervalMap.h.
References value().
operator++() [1/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++ () inline
preincrement - Move to the next interval.
Definition at line 1452 of file IntervalMap.h.
References assert(), branched(), const_iterator(), map, path, and valid().
Referenced by operator++(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator++().
operator++() [2/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++ (int) inline
postincrement - Don't do that!
Definition at line 1460 of file IntervalMap.h.
References const_iterator(), and operator++().
operator--() [1/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator-- () inline
predecrement - Move to the previous interval.
Definition at line 1467 of file IntervalMap.h.
References branched(), const_iterator(), map, path, and valid().
Referenced by operator--(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--().
operator--() [2/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator-- (int) inline
postdecrement - Don't do that!
Definition at line 1476 of file IntervalMap.h.
References const_iterator(), and operator--().
operator=() [1/2]
IntervalMap & llvm::IntervalMap< KeyT, ValT, N, Traits >::operator= (IntervalMap && RHS) inline
Definition at line 1069 of file IntervalMap.h.
operator=() [2/2]
IntervalMap & llvm::IntervalMap< KeyT, ValT, N, Traits >::operator= (IntervalMap const & RHS) inline
Definition at line 1055 of file IntervalMap.h.
operator==()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator== (const const_iterator & RHS) const inline
Definition at line 1426 of file IntervalMap.h.
References assert(), const_iterator(), leaf, map, path, RHS, and valid().
overlaps()
bool llvm::IntervalMap< KeyT, ValT, N, Traits >::overlaps (KeyT a, KeyT b) const inline
overlaps(a, b) - Return true if the intervals in this map overlap with the interval [a;b].
Definition at line 1186 of file IntervalMap.h.
pathFillFind()
template<typename KeyT, typename ValT, unsigned N, typename Traits> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind (KeyT x) protected
pathFillFind - Complete path by searching for x.
Parameters
x Key to search for.
Definition at line 1508 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeRef::get(), map, path, and llvm::IntervalMapImpl::NodeRef::subtree().
Referenced by treeAdvanceTo(), and treeFind().
setMap()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setMap (const IntervalMap & m) inline
setMap - Change the map iterated over.
This call must be followed by a call to goToBegin(), goToEnd(), or find()
Definition at line 1407 of file IntervalMap.h.
References IntervalMap, and map.
setRoot()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setRoot (unsigned Offset) inline protected
Definition at line 1369 of file IntervalMap.h.
References branched(), map, llvm::Offset, and path.
Referenced by find(), goToBegin(), goToEnd(), treeAdvanceTo(), and treeFind().
start() [1/2]
KeyT llvm::IntervalMap< KeyT, ValT, N, Traits >::start () const inline
start - Return the smallest mapped key in a non-empty map.
Definition at line 1106 of file IntervalMap.h.
start() [2/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const KeyT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::start () const inline
start - Return the beginning of the current interval.
Definition at line 1416 of file IntervalMap.h.
References unsafeStart().
Referenced by unsafeStart().
stop() [1/2]
KeyT llvm::IntervalMap< KeyT, ValT, N, Traits >::stop () const inline
stop - Return the largest mapped key in a non-empty map.
Definition at line 1112 of file IntervalMap.h.
stop() [2/2]
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const KeyT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::stop () const inline
stop - Return the end of the current interval.
Definition at line 1419 of file IntervalMap.h.
References unsafeStop().
Referenced by unsafeStop().
treeAdvanceTo()
template<typename KeyT, typename ValT, unsigned N, typename Traits> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::treeAdvanceTo (KeyT x) protected
treeAdvanceTo - Find position after the current one.
Parameters
x Key to search for.
Definition at line 1532 of file IntervalMap.h.
References map, path, pathFillFind(), setRoot(), and valid().
Referenced by advanceTo().
treeFind()
template<typename KeyT, typename ValT, unsigned N, typename Traits> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::treeFind (KeyT x) protected
treeFind - Find in a branched tree.
Parameters
x Key to search for.
Definition at line 1522 of file IntervalMap.h.
References map, pathFillFind(), setRoot(), and valid().
Referenced by find().
unsafeStart()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> KeyT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart () const inline protected
unsafeStart - Writable access to start() for iterator.
Definition at line 1381 of file IntervalMap.h.
References assert(), branched(), path, start(), and valid().
Referenced by start().
unsafeStop()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> KeyT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop () const inline protected
unsafeStop - Writable access to stop() for iterator.
Definition at line 1388 of file IntervalMap.h.
References assert(), branched(), path, stop(), and valid().
Referenced by stop().
unsafeValue()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> ValT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue () const inline protected
unsafeValue - Writable access to value() for iterator.
Definition at line 1395 of file IntervalMap.h.
References assert(), branched(), path, valid(), and value().
Referenced by value().
valid()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid () const inline
valid - Return true if the current position is valid, false for end().
Definition at line 1410 of file IntervalMap.h.
References path.
Referenced by advanceTo(), operator++(), operator--(), operator==(), treeAdvanceTo(), treeFind(), unsafeStart(), unsafeStop(), and unsafeValue().
value()
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const ValT & llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value () const inline
value - Return the mapped value at the current interval.
Definition at line 1422 of file IntervalMap.h.
References unsafeValue().
Referenced by operator*(), and unsafeValue().
Friends And Related Symbol Documentation
const_iterator
friend class const_iterator friend
Definition at line 1143 of file IntervalMap.h.
IntervalMap
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> friend class IntervalMap friend
Definition at line 1344 of file IntervalMap.h.
References IntervalMap.
Referenced by const_iterator(), IntervalMap, and setMap().
iterator
friend class iterator friend
Definition at line 1144 of file IntervalMap.h.
Member Data Documentation
branchData
RootBranchData llvm::IntervalMap< KeyT, ValT, N, Traits >::branchData
Definition at line 971 of file IntervalMap.h.
leaf
RootLeaf llvm::IntervalMap< KeyT, ValT, N, Traits >::leaf
Definition at line 970 of file IntervalMap.h.
Referenced by operator==().
map
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> IntervalMap* llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::map = nullptr protected
Definition at line 1355 of file IntervalMap.h.
Referenced by advanceTo(), branched(), const_iterator(), find(), goToBegin(), goToEnd(), operator++(), operator--(), operator==(), pathFillFind(), setMap(), setRoot(), treeAdvanceTo(), and treeFind().
path
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> IntervalMapImpl::Path llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::path protected
Definition at line 1359 of file IntervalMap.h.
Referenced by advanceTo(), atBegin(), goToBegin(), operator++(), operator--(), operator==(), pathFillFind(), setRoot(), treeAdvanceTo(), unsafeStart(), unsafeStop(), unsafeValue(), and valid().
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalMap.h