LLVM: llvm::VPValue Class Reference
llvm::VPValue Class Reference
#include "Transforms/Vectorize/VPlanValue.h"
Public Types
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Public Member Functions
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop region.
void setUnderlyingValue (Value *Val)
Protected Member Functions
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
Protected Attributes
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Friends
class VPBuilder
class VPDef
struct VPDoubleValueDef
class VPInstruction
class VPInterleaveRecipe
struct VPlanTransforms
class VPBasicBlock
class VPInterleavedAccessInfo
class VPSlotTracker
class VPRecipeBase
class VPlan
Detailed Description
Definition at line 46 of file VPlanValue.h.
Member Typedef Documentation
const_user_iterator
typedef SmallVectorImpl<VPUser*>::const_iterator llvm::VPValue::const_user_iterator
Definition at line 130 of file VPlanValue.h.
const_user_range
typedef iterator_range<const_user_iterator> llvm::VPValue::const_user_range
Definition at line 132 of file VPlanValue.h.
user_iterator
typedef SmallVectorImpl<VPUser*>::iterator llvm::VPValue::user_iterator
Definition at line 129 of file VPlanValue.h.
user_range
typedef iterator_range<user_iterator> llvm::VPValue::user_range
Definition at line 131 of file VPlanValue.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
Enumerator
VPValueSC
VPVRecipeSC
A generic VPValue, like live-in values or defined by a recipe that defines multiple values.
A VPValue sub-class that is a VPRecipeBase.
Definition at line 93 of file VPlanValue.h.
Constructor & Destructor Documentation
VPValue() [1/5]
VPValue::VPValue (const unsigned char SC, Value * UV = nullptr, VPDef * Def = nullptr) protected
Definition at line 86 of file VPlan.cpp.
References Def, UnderlyingVal, and VPDef.
Referenced by llvm::VPWidenLoadEVLRecipe::execute(), llvm::VPWidenLoadEVLRecipe::getEVL(), llvm::VPWidenLoadEVLRecipe::onlyFirstLaneUsed(), llvm::VPWidenLoadRecipe::onlyFirstLaneUsed(), operator=(), replaceAllUsesWith(), replaceUsesWithIf(), VPValue(), VPValue(), VPValue(), VPValue(), llvm::VPWidenLoadEVLRecipe::VPWidenLoadEVLRecipe(), and llvm::VPWidenLoadRecipe::VPWidenLoadRecipe().
VPValue() [2/5]
llvm::VPValue::VPValue (Value * UV = nullptr) inline protected
Create a live-in VPValue.
Definition at line 74 of file VPlanValue.h.
References VPValue(), and VPValueSC.
VPValue() [3/5]
llvm::VPValue::VPValue (VPDef * Def, Value * UV = nullptr) inline protected
Create a VPValue for a Def which is a subclass of VPValue.
Definition at line 76 of file VPlanValue.h.
References Def, VPDef, VPValue(), and VPVRecipeSC.
VPValue() [4/5]
llvm::VPValue::VPValue (Value * UV, VPDef * Def) inline protected
Create a VPValue for a Def which defines multiple values.
Definition at line 78 of file VPlanValue.h.
References Def, VPDef, VPValue(), and VPValueSC.
VPValue() [5/5]
llvm::VPValue::VPValue (const VPValue &) delete
References VPValue().
~VPValue()
VPValue::~VPValue () virtual
Definition at line 92 of file VPlan.cpp.
References assert(), and Def.
Member Function Documentation
addUser()
void llvm::VPValue::addUser (VPUser & User) inline
Definition at line 118 of file VPlanValue.h.
Referenced by llvm::VPUser::addOperand().
dump()
void VPValue::dump () const
Dump the value to stderr (for debugging).
Definition at line 106 of file VPlan.cpp.
References llvm::dbgs(), Def, llvm::dyn_cast_or_null(), print(), VPRecipeBase, and VPSlotTracker.
getDefiningRecipe() [1/2]
VPRecipeBase * VPValue::getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
is a live-in.
Definition at line 123 of file VPlan.cpp.
References llvm::cast_or_null(), Def, and VPRecipeBase.
Referenced by llvm::VPPartialReductionRecipe::computeCost(), llvm::VPWidenCastRecipe::computeCost(), llvm::VPlanTransforms::createInterleaveGroups(), llvm::VPHeaderPHIRecipe::getBackedgeRecipe(), getOptimizableIVOf(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), hasDefiningRecipe(), llvm::VPWidenIntOrFpInductionRecipe::isCanonical(), isDefinedInsideLoopRegions(), llvm::vputils::isUniformAfterVectorization(), preparePlanForMainVectorLoop(), recursivelyDeleteDeadRecipes(), and llvm::VPRecipeBuilder::tryToCreatePartialReduction().
getDefiningRecipe() [2/2]
const VPRecipeBase * VPValue::getDefiningRecipe () const
Definition at line 127 of file VPlan.cpp.
References llvm::cast_or_null(), Def, and VPRecipeBase.
getLiveInIRValue() [1/2]
Value * llvm::VPValue::getLiveInIRValue () inline
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
Returns nullptr if the VPValue is defined by a VPDef inside a VPlan.
Definition at line 178 of file VPlanValue.h.
References assert(), getUnderlyingValue(), and isLiveIn().
Referenced by llvm::VPHistogramRecipe::computeCost(), llvm::VPDerivedIVRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPWidenCallRecipe::getCalledScalarFunction(), getOptimizableIVOf(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::VPDerivedIVRecipe::getScalarType(), llvm::VPWidenIntOrFpInductionRecipe::isCanonical(), llvm::VPlanPatternMatch::specific_intval< BitWidth >::match(), and llvm::VPlanTransforms::optimizeInductionExitUsers().
getLiveInIRValue() [2/2]
const Value * llvm::VPValue::getLiveInIRValue () const inline
Definition at line 183 of file VPlanValue.h.
References assert(), getUnderlyingValue(), and isLiveIn().
getNumUsers()
unsigned llvm::VPValue::getNumUsers () const inline
Definition at line 117 of file VPlanValue.h.
Referenced by llvm::VPWidenCastRecipe::computeCost(), createReplicateRegion(), hasMoreThanOneUniqueUser(), replaceUsesWithIf(), and llvm::VPlan::resetTripCount().
getUnderlyingValue()
Value * llvm::VPValue::getUnderlyingValue () const inline
Return the underlying Value attached to this VPValue.
Definition at line 89 of file VPlanValue.h.
References UnderlyingVal.
Referenced by llvm::VPBlendRecipe::clone(), llvm::VPWidenCallRecipe::clone(), llvm::VPWidenCastRecipe::clone(), llvm::VPWidenIntrinsicRecipe::clone(), llvm::VPInstruction::computeCost(), llvm::VPReplicateRecipe::computeCost(), llvm::VPWidenCastRecipe::computeCost(), llvm::VPWidenIntrinsicRecipe::computeCost(), llvm::VPWidenRecipe::computeCost(), llvm::VPWidenSelectRecipe::computeCost(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPWidenCallRecipe::execute(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenEVLRecipe::execute(), llvm::VPWidenIntrinsicRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::VPWidenSelectRecipe::execute(), getLiveInIRValue(), getLiveInIRValue(), llvm::VPWidenInductionRecipe::getPHINode(), llvm::VPSingleDefRecipe::getUnderlyingInstr(), llvm::VPSingleDefRecipe::getUnderlyingInstr(), llvm::VPWidenPHIRecipe::print(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), llvm::VPlanTransforms::VPInstructionsToVPRecipes(), and llvm::VPReductionEVLRecipe::VPReductionEVLRecipe().
getVPValueID()
unsigned llvm::VPValue::getVPValueID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 107 of file VPlanValue.h.
hasDefiningRecipe()
bool llvm::VPValue::hasDefiningRecipe () const inline
Returns true if this VPValue is defined by a recipe.
Definition at line 170 of file VPlanValue.h.
References getDefiningRecipe().
Referenced by isLiveIn().
hasMoreThanOneUniqueUser()
bool llvm::VPValue::hasMoreThanOneUniqueUser () const inline
Returns true if the value has more than one unique user.
Definition at line 144 of file VPlanValue.h.
References getNumUsers(), user_begin(), and user_end().
Referenced by llvm::VPWidenCastRecipe::computeCost().
isDefinedOutsideLoopRegions()
bool VPValue::isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop region.
Definition at line 1416 of file VPlan.cpp.
References isDefinedInsideLoopRegions().
Referenced by llvm::VPWidenRecipe::computeCost(), llvm::VPWidenSelectRecipe::computeCost(), llvm::VPWidenSelectRecipe::isInvariantCond(), and llvm::vputils::isUniformAfterVectorization().
isLiveIn()
bool llvm::VPValue::isLiveIn () const inline
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Definition at line 173 of file VPlanValue.h.
References hasDefiningRecipe().
Referenced by llvm::VPHistogramRecipe::computeCost(), llvm::VPWidenCastRecipe::computeCost(), llvm::VPIRInstruction::extractLastLaneOfOperand(), getLiveInIRValue(), getLiveInIRValue(), getOptimizableIVOf(), llvm::VPlan::getOrAddLiveIn(), llvm::VPlanTransforms::handleUncountableEarlyExit(), and llvm::VPlanPatternMatch::specific_intval< BitWidth >::match().
operator=()
VPValue & llvm::VPValue::operator= (const VPValue &) delete
References VPValue().
print()
void VPValue::print (raw_ostream & OS, VPSlotTracker & Tracker) const
Definition at line 99 of file VPlan.cpp.
References Def, llvm::dyn_cast_or_null(), printAsOperand(), VPRecipeBase, and VPSlotTracker.
Referenced by dump().
printAsOperand()
void VPValue::printAsOperand (raw_ostream & OS, VPSlotTracker & Tracker) const
Definition at line 1451 of file VPlan.cpp.
References llvm::VPSlotTracker::getOrCreateName(), and VPSlotTracker.
Referenced by llvm::VPActiveLaneMaskPHIRecipe::print(), llvm::VPBlendRecipe::print(), llvm::VPCanonicalIVPHIRecipe::print(), llvm::VPDerivedIVRecipe::print(), llvm::VPEVLBasedIVPHIRecipe::print(), llvm::VPExpandSCEVRecipe::print(), llvm::VPFirstOrderRecurrencePHIRecipe::print(), llvm::VPHistogramRecipe::print(), llvm::VPInstruction::print(), llvm::VPInterleaveRecipe::print(), llvm::VPPartialReductionRecipe::print(), llvm::VPPredInstPHIRecipe::print(), llvm::VPReductionEVLRecipe::print(), llvm::VPReductionPHIRecipe::print(), llvm::VPReductionRecipe::print(), llvm::VPReplicateRecipe::print(), llvm::VPReverseVectorPointerRecipe::print(), llvm::VPScalarCastRecipe::print(), llvm::VPScalarIVStepsRecipe::print(), llvm::VPScalarPHIRecipe::print(), print(), llvm::VPVectorPointerRecipe::print(), llvm::VPWidenCallRecipe::print(), llvm::VPWidenCanonicalIVRecipe::print(), llvm::VPWidenCastRecipe::print(), llvm::VPWidenEVLRecipe::print(), llvm::VPWidenGEPRecipe::print(), llvm::VPWidenIntOrFpInductionRecipe::print(), llvm::VPWidenIntrinsicRecipe::print(), llvm::VPWidenLoadEVLRecipe::print(), llvm::VPWidenLoadRecipe::print(), llvm::VPWidenPHIRecipe::print(), llvm::VPWidenPointerInductionRecipe::print(), llvm::VPWidenRecipe::print(), and llvm::VPWidenSelectRecipe::print().
removeUser()
void llvm::VPValue::removeUser (VPUser & User) inline
Remove a single User from the list of users.
Definition at line 121 of file VPlanValue.h.
References llvm::find(), and I.
replaceAllUsesWith()
void VPValue::replaceAllUsesWith (VPValue * New)
Definition at line 1419 of file VPlan.cpp.
References replaceUsesWithIf(), and VPValue().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), llvm::VPlanTransforms::createInterleaveGroups(), createReplicateRegion(), legalizeAndOptimizeInductions(), preparePlanForEpilogueVectorLoop(), removeRedundantCanonicalIVs(), removeRedundantInductionCasts(), simplifyRecipe(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), and llvm::VPlanTransforms::VPInstructionsToVPRecipes().
replaceUsesWithIf()
void VPValue::replaceUsesWithIf (VPValue * New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
Definition at line 1423 of file VPlan.cpp.
References llvm::User::getNumOperands(), getNumUsers(), llvm::User::getOperand(), I, llvm::User::setOperand(), and VPValue().
Referenced by mergeReplicateRegionsIntoSuccessors(), replaceAllUsesWith(), and sinkScalarOperands().
setUnderlyingValue()
void llvm::VPValue::setUnderlyingValue (Value * Val) inline
Definition at line 193 of file VPlanValue.h.
References assert(), and UnderlyingVal.
Referenced by llvm::VPBuilder::createNaryOp().
user_begin() [1/2]
user_iterator llvm::VPValue::user_begin () inline
Definition at line 134 of file VPlanValue.h.
Referenced by llvm::VPWidenCastRecipe::computeCost(), hasMoreThanOneUniqueUser(), users(), and users().
user_begin() [2/2]
const_user_iterator llvm::VPValue::user_begin () const inline
Definition at line 135 of file VPlanValue.h.
user_end() [1/2]
user_iterator llvm::VPValue::user_end () inline
Definition at line 136 of file VPlanValue.h.
Referenced by hasMoreThanOneUniqueUser(), users(), and users().
user_end() [2/2]
const_user_iterator llvm::VPValue::user_end () const inline
Definition at line 137 of file VPlanValue.h.
users() [1/2]
user_range llvm::VPValue::users () inline
Definition at line 138 of file VPlanValue.h.
References user_begin(), and user_end().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), collectAllHeaderMasks(), llvm::VPBlendRecipe::onlyFirstLaneUsed(), removeRedundantCanonicalIVs(), removeRedundantInductionCasts(), llvm::VPReplicateRecipe::shouldPack(), sinkRecurrenceUsersAfterPrevious(), sinkScalarOperands(), and transformRecipestoEVLRecipes().
users() [2/2]
const_user_range llvm::VPValue::users () const inline
Definition at line 139 of file VPlanValue.h.
References user_begin(), and user_end().
Friends And Related Symbol Documentation
VPBasicBlock
friend class VPBasicBlock friend
Definition at line 53 of file VPlanValue.h.
References VPBasicBlock.
Referenced by VPBasicBlock.
VPBuilder
friend class VPBuilder friend
Definition at line 47 of file VPlanValue.h.
References VPBuilder.
Referenced by VPBuilder.
VPDef
friend class VPDef friend
Definition at line 48 of file VPlanValue.h.
References VPDef.
Referenced by VPDef, VPValue(), VPValue(), VPValue(), llvm::VPWidenLoadEVLRecipe::VPWidenLoadEVLRecipe(), and llvm::VPWidenLoadRecipe::VPWidenLoadRecipe().
VPDoubleValueDef
friend struct VPDoubleValueDef friend
Definition at line 49 of file VPlanValue.h.
References VPDoubleValueDef.
Referenced by VPDoubleValueDef.
VPInstruction
friend class VPInstruction friend
Definition at line 50 of file VPlanValue.h.
References VPInstruction.
Referenced by llvm::VPInstruction::clone(), and VPInstruction.
VPInterleavedAccessInfo
friend class VPInterleavedAccessInfo friend
Definition at line 54 of file VPlanValue.h.
References VPInterleavedAccessInfo.
Referenced by VPInterleavedAccessInfo.
VPInterleaveRecipe
friend class VPInterleaveRecipe friend
Definition at line 51 of file VPlanValue.h.
References VPInterleaveRecipe.
Referenced by VPInterleaveRecipe.
VPlan
friend class VPlan friend
Definition at line 57 of file VPlanValue.h.
References VPlan.
Referenced by VPlan.
VPlanTransforms
friend struct VPlanTransforms friend
Definition at line 52 of file VPlanValue.h.
References VPlanTransforms.
Referenced by VPlanTransforms.
VPRecipeBase
friend class VPRecipeBase friend
Definition at line 56 of file VPlanValue.h.
References VPRecipeBase.
Referenced by llvm::VPSingleDefRecipe::classof(), dump(), getDefiningRecipe(), getDefiningRecipe(), print(), and VPRecipeBase.
VPSlotTracker
friend class VPSlotTracker friend
Definition at line 55 of file VPlanValue.h.
References VPSlotTracker.
Referenced by dump(), print(), llvm::VPWidenLoadEVLRecipe::print(), llvm::VPWidenLoadRecipe::print(), printAsOperand(), llvm::VPWidenLoadRecipe::VP_CLASSOF_IMPL(), and VPSlotTracker.
Member Data Documentation
Def
VPDef* llvm::VPValue::Def protected
Pointer to the VPDef that defines this VPValue.
If it is nullptr, the VPValue is not defined by any recipe modeled in VPlan.
Definition at line 69 of file VPlanValue.h.
Referenced by dump(), getDefiningRecipe(), getDefiningRecipe(), print(), VPValue(), VPValue(), VPValue(), and ~VPValue().
UnderlyingVal
Value* llvm::VPValue::UnderlyingVal protected
Definition at line 65 of file VPlanValue.h.
Referenced by getUnderlyingValue(), setUnderlyingValue(), and VPValue().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp