LLVM: llvm::SandboxVectorizerPass Class Reference
llvm::SandboxVectorizerPass Class Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/SandboxVectorizer.h"
Public Member Functions
SandboxVectorizerPass ()
SandboxVectorizerPass (SandboxVectorizerPass &&)
~SandboxVectorizerPass ()
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SandboxVectorizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SandboxVectorizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file SandboxVectorizer.h.
Constructor & Destructor Documentation
SandboxVectorizerPass() [1/2]
SandboxVectorizerPass::SandboxVectorizerPass ()
Definition at line 32 of file SandboxVectorizer.cpp.
References llvm::sandboxir::SandboxVectorizerPassBuilder::createFunctionPass(), DefaultPipelineMagicStr, and UserDefinedPassPipeline.
Referenced by SandboxVectorizerPass().
SandboxVectorizerPass() [2/2]
SandboxVectorizerPass::SandboxVectorizerPass (SandboxVectorizerPass &&) default
References SandboxVectorizerPass().
~SandboxVectorizerPass()
SandboxVectorizerPass::~SandboxVectorizerPass () default
References F.
Member Function Documentation
run()
PreservedAnalyses SandboxVectorizerPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 51 of file SandboxVectorizer.cpp.
References llvm::PreservedAnalyses::all(), Changed, F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/SandboxVectorizer.h
lib/Transforms/Vectorize/SandboxVectorizer/SandboxVectorizer.cpp