LLVM: llvm::sandboxir::VecUtils Class Reference
llvm::sandboxir::VecUtils Class Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/VecUtils.h"
Static Public Member Functions
static int getNumElements (Type *Ty)
\Returns the number of elements in Ty.
static Type * getElementType (Type *Ty)
Returns Ty if scalar or its element type if vector.
template<typename LoadOrStoreT>
static bool areConsecutive (LoadOrStoreT *I1, LoadOrStoreT *I2, ScalarEvolution &SE, const DataLayout &DL)
\Returns true if I1 and I2 are load/stores accessing consecutive memory addresses.
template<typename LoadOrStoreT>
static bool areConsecutive (ArrayRef< Value * > &Bndl, ScalarEvolution &SE, const DataLayout &DL)
static unsigned getNumLanes (Type *Ty)
\Returns the number of vector lanes of Ty or 1 if not a vector.
static unsigned getNumLanes (Value *V)
\Returns the expected vector lanes of V or 1 if not a vector.
static unsigned getNumLanes (ArrayRef< Value * > Bndl)
\Returns the total number of lanes across all values in Bndl.
static Type * getWideType (Type *ElemTy, unsigned NumElts)
\Returns <NumElts x ElemTy>.
static Instruction * getLowest (ArrayRef< Instruction * > Instrs)
\Returns the instruction in Instrs that is lowest in the BB.
static Instruction * getLowest (ArrayRef< Value * > Vals, BasicBlock *BB)
\Returns the lowest instruction in Vals, or nullptr if no instructions are found.
static Instruction * getLastPHIOrSelf (Instruction *I)
If I is not a PHI it returns it.
static Type * tryGetCommonScalarType (ArrayRef< Value * > Bndl)
If all values in Bndl are of the same scalar type then return it, otherwise return nullptr.
static Type * getCommonScalarType (ArrayRef< Value * > Bndl)
Similar to tryGetCommonScalarType() but will assert that there is a common type.
static unsigned getFloorPowerOf2 (unsigned Num)
\Returns the first integer power of 2 that is <= Num.
static LLVM_DUMP_METHOD void dump (ArrayRef< Value * > Bndl)
Helper dump function for debugging.
static LLVM_DUMP_METHOD void dump (ArrayRef< Instruction * > Bndl)
Detailed Description
Definition at line 22 of file VecUtils.h.
Member Function Documentation
areConsecutive() [1/2]
template<typename LoadOrStoreT> static bool llvm::sandboxir::VecUtils::areConsecutive (ArrayRef< Value * > & Bndl, ScalarEvolution & SE, const DataLayout & DL) inline static
Definition at line 52 of file VecUtils.h.
References areConsecutive(), assert(), llvm::cast(), DL, llvm::drop_begin(), and llvm::isa().
areConsecutive() [2/2]
template<typename LoadOrStoreT> static bool llvm::sandboxir::VecUtils::areConsecutive (LoadOrStoreT * I1, LoadOrStoreT * I2, ScalarEvolution & SE, const DataLayout & DL) inline static
\Returns true if I1 and I2 are load/stores accessing consecutive memory addresses.
Definition at line 39 of file VecUtils.h.
References DL, llvm::sandboxir::Utils::getNumBits(), and llvm::sandboxir::Utils::getPointerDiffInBytes().
Referenced by areConsecutive().
dump() [1/2]
void llvm::sandboxir::VecUtils::dump (ArrayRef< Instruction * > Bndl) static
Definition at line 29 of file VecUtils.cpp.
References llvm::sandboxir::dumpImpl().
dump() [2/2]
void llvm::sandboxir::VecUtils::dump (ArrayRef< Value * > Bndl) static
Helper dump function for debugging.
Definition at line 28 of file VecUtils.cpp.
References llvm::sandboxir::dumpImpl().
getCommonScalarType()
static Type * llvm::sandboxir::VecUtils::getCommonScalarType (ArrayRef< Value * > Bndl) inline static
Similar to tryGetCommonScalarType() but will assert that there is a common type.
So this is faster in release builds as it won't iterate through the values.
Definition at line 172 of file VecUtils.h.
References assert(), getElementType(), llvm::sandboxir::Utils::getExpectedType(), and tryGetCommonScalarType().
getElementType()
static Type * llvm::sandboxir::VecUtils::getElementType (Type * Ty) inline static
Returns Ty if scalar or its element type if vector.
Definition at line 32 of file VecUtils.h.
References llvm::cast(), and llvm::sandboxir::Type::isVectorTy().
Referenced by getCommonScalarType(), llvm::sandboxir::BottomUpVec::runOnFunction(), and tryGetCommonScalarType().
getFloorPowerOf2()
unsigned llvm::sandboxir::VecUtils::getFloorPowerOf2 (unsigned Num) static
\Returns the first integer power of 2 that is <= Num.
Definition at line 13 of file VecUtils.cpp.
Referenced by llvm::sandboxir::BottomUpVec::runOnFunction().
getLastPHIOrSelf()
static Instruction * llvm::sandboxir::VecUtils::getLastPHIOrSelf (Instruction * I) inline static
If I is not a PHI it returns it.
Else it walks down the instruction chain looking for the last PHI and returns it. \Returns nullptr if I is nullptr.
Definition at line 145 of file VecUtils.h.
References I, and llvm::isa().
Referenced by llvm::sandboxir::getInsertPointAfterInstrs().
getLowest() [1/2]
static Instruction * llvm::sandboxir::VecUtils::getLowest (ArrayRef< Instruction * > Instrs) inline static
\Returns the instruction in Instrs that is lowest in the BB.
Expects that all instructions are in the same BB.
Definition at line 105 of file VecUtils.h.
References llvm::sandboxir::Instruction::comesBefore(), llvm::drop_begin(), llvm::ArrayRef< T >::front(), and I.
Referenced by llvm::sandboxir::getInsertPointAfterInstrs(), and llvm::sandboxir::Scheduler::trySchedule().
getLowest() [2/2]
static Instruction * llvm::sandboxir::VecUtils::getLowest (ArrayRef< Value * > Vals, BasicBlock * BB) inline static
\Returns the lowest instruction in Vals, or nullptr if no instructions are found.
Skips instructions not in BB.
Definition at line 115 of file VecUtils.h.
References llvm::sandboxir::BasicBlock(), llvm::cast(), llvm::sandboxir::Instruction::comesBefore(), llvm::dyn_cast(), llvm::ArrayRef< T >::end(), llvm::find_if(), I, llvm::isa(), and llvm::make_range().
getNumElements()
static int llvm::sandboxir::VecUtils::getNumElements (Type * Ty) inline static
\Returns the number of elements in Ty.
That is the number of lanes if a fixed vector or 1 if scalar. ScalableVectors have unknown size and therefore are unsupported.
Definition at line 27 of file VecUtils.h.
References assert(), llvm::cast(), and llvm::isa().
getNumLanes() [1/3]
static unsigned llvm::sandboxir::VecUtils::getNumLanes (ArrayRef< Value * > Bndl) inline static
\Returns the total number of lanes across all values in Bndl.
Definition at line 86 of file VecUtils.h.
References getNumLanes().
getNumLanes() [2/3]
static unsigned llvm::sandboxir::VecUtils::getNumLanes (Type * Ty) inline static
\Returns the number of vector lanes of Ty or 1 if not a vector.
NOTE: It asserts that Ty is a fixed vector type.
Definition at line 72 of file VecUtils.h.
References assert(), llvm::dyn_cast(), and llvm::isa().
Referenced by getNumLanes(), and getNumLanes().
getNumLanes() [3/3]
static unsigned llvm::sandboxir::VecUtils::getNumLanes (Value * V) inline static
\Returns the expected vector lanes of V or 1 if not a vector.
NOTE: It asserts that V is a fixed vector.
Definition at line 81 of file VecUtils.h.
References llvm::sandboxir::Utils::getExpectedType(), and getNumLanes().
getWideType()
static Type * llvm::sandboxir::VecUtils::getWideType (Type * ElemTy, unsigned NumElts) inline static
\Returns <NumElts x ElemTy>.
It works for both scalar and vector ElemTy.
Definition at line 95 of file VecUtils.h.
References llvm::cast(), and llvm::sandboxir::FixedVectorType::get().
tryGetCommonScalarType()
static Type * llvm::sandboxir::VecUtils::tryGetCommonScalarType (ArrayRef< Value * > Bndl) inline static
If all values in Bndl are of the same scalar type then return it, otherwise return nullptr.
Definition at line 156 of file VecUtils.h.
References llvm::drop_begin(), getElementType(), and llvm::sandboxir::Utils::getExpectedType().
Referenced by getCommonScalarType().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/VecUtils.h
lib/Transforms/Vectorize/SandboxVectorizer/VecUtils.cpp