LLVM: llvm::sandboxir::InsertPosition Class Reference
llvm::sandboxir::InsertPosition Class Reference
#include "llvm/SandboxIR/Instruction.h"
Public Member Functions
InsertPosition (BasicBlock *InsertAtEnd)
InsertPosition (BBIterator InsertAt)
operator BBIterator ()
const BBIterator & getIterator () const
Instruction & operator* ()
BasicBlock * getBasicBlock () const
Detailed Description
Definition at line 25 of file Instruction.h.
Constructor & Destructor Documentation
InsertPosition() [1/2]
llvm::sandboxir::InsertPosition::InsertPosition (BasicBlock * InsertAtEnd) inline
Definition at line 29 of file Instruction.h.
References assert(), llvm::sandboxir::BasicBlock(), and llvm::BasicBlock::end().
InsertPosition() [2/2]
llvm::sandboxir::InsertPosition::InsertPosition (BBIterator InsertAt) inline
Definition at line 33 of file Instruction.h.
Member Function Documentation
getBasicBlock()
BasicBlock * llvm::sandboxir::InsertPosition::getBasicBlock () const inline
Definition at line 37 of file Instruction.h.
References llvm::sandboxir::BasicBlock().
Referenced by llvm::sandboxir::Instruction::setInsertPos().
getIterator()
const BBIterator & llvm::sandboxir::InsertPosition::getIterator () const inline
Definition at line 35 of file Instruction.h.
Referenced by llvm::sandboxir::Instruction::setInsertPos().
operator BBIterator()
llvm::sandboxir::InsertPosition::operator BBIterator () inline
Definition at line 34 of file Instruction.h.
operator*()
Instruction & llvm::sandboxir::InsertPosition::operator* () inline
Definition at line 36 of file Instruction.h.
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Instruction.h