LLVM: llvm::RegAllocFastPass Class Reference
llvm::RegAllocFastPass Class Reference
#include "llvm/CodeGen/RegAllocFast.h"
Public Member Functions
RegAllocFastPass (RegAllocFastPassOptions Opts=RegAllocFastPassOptions())
MachineFunctionProperties getRequiredProperties () const
MachineFunctionProperties getSetProperties () const
MachineFunctionProperties getClearedProperties () const
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< RegAllocFastPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< RegAllocFastPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file RegAllocFast.h.
Constructor & Destructor Documentation
RegAllocFastPass()
llvm::RegAllocFastPass::RegAllocFastPass (RegAllocFastPassOptions Opts = RegAllocFastPassOptions()) inline
Definition at line 27 of file RegAllocFast.h.
Member Function Documentation
getClearedProperties()
MachineFunctionProperties llvm::RegAllocFastPass::getClearedProperties () const inline
Definition at line 44 of file RegAllocFast.h.
References llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::set().
getRequiredProperties()
MachineFunctionProperties llvm::RegAllocFastPass::getRequiredProperties () const inline
Definition at line 30 of file RegAllocFast.h.
References llvm::MachineFunctionProperties::NoPHIs, and llvm::MachineFunctionProperties::set().
getSetProperties()
MachineFunctionProperties llvm::RegAllocFastPass::getSetProperties () const inline
Definition at line 35 of file RegAllocFast.h.
References llvm::MachineFunctionProperties::NoVRegs, and llvm::MachineFunctionProperties::set().
isRequired()
static bool llvm::RegAllocFastPass::isRequired () inline static
Definition at line 54 of file RegAllocFast.h.
printPipeline()
void RegAllocFastPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 1855 of file RegAllocFast.cpp.
run()
PreservedAnalyses RegAllocFastPass::run (MachineFunction & MF, MachineFunctionAnalysisManager &)
Definition at line 1843 of file RegAllocFast.cpp.
References _, llvm::PreservedAnalyses::all(), Changed, and llvm::getMachineFunctionPassPreservedAnalyses().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegAllocFast.h
lib/CodeGen/RegAllocFast.cpp