LLVM: llvm::SDNode::user_iterator Class Reference
llvm::SDNode::user_iterator Class Reference
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = SDNode *
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
user_iterator ()=default
bool operator== (const user_iterator &x) const
bool operator!= (const user_iterator &x) const
user_iterator & operator++ ()
user_iterator operator++ (int)
SDNode * operator* () const
SDNode * operator-> () const
SDUse & getUse () const
Friends
class SDNode
Detailed Description
Definition at line 815 of file SelectionDAGNodes.h.
Member Typedef Documentation
difference_type
using llvm::SDNode::user_iterator::difference_type = std::ptrdiff_t
Definition at line 824 of file SelectionDAGNodes.h.
iterator_category
using llvm::SDNode::user_iterator::iterator_category = std::forward_iterator_tag
Definition at line 822 of file SelectionDAGNodes.h.
pointer
using llvm::SDNode::user_iterator::pointer = value_type *
Definition at line 825 of file SelectionDAGNodes.h.
reference
using llvm::SDNode::user_iterator::reference = value_type &
Definition at line 826 of file SelectionDAGNodes.h.
value_type
using llvm::SDNode::user_iterator::value_type = SDNode *
Definition at line 823 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
user_iterator()
llvm::SDNode::user_iterator::user_iterator () default
Member Function Documentation
getUse()
SDUse & llvm::SDNode::user_iterator::getUse () const inline
Definition at line 849 of file SelectionDAGNodes.h.
operator!=()
bool llvm::SDNode::user_iterator::operator!= (const user_iterator & x) const inline
Definition at line 831 of file SelectionDAGNodes.h.
References operator==().
operator*()
SDNode * llvm::SDNode::user_iterator::operator* () const inline
Definition at line 845 of file SelectionDAGNodes.h.
References SDNode.
Referenced by operator->().
operator++() [1/2]
user_iterator & llvm::SDNode::user_iterator::operator++ () inline
Definition at line 833 of file SelectionDAGNodes.h.
operator++() [2/2]
user_iterator llvm::SDNode::user_iterator::operator++ (int) inline
Definition at line 838 of file SelectionDAGNodes.h.
operator->()
SDNode * llvm::SDNode::user_iterator::operator-> () const inline
Definition at line 847 of file SelectionDAGNodes.h.
References operator*(), and SDNode.
operator==()
bool llvm::SDNode::user_iterator::operator== (const user_iterator & x) const inline
Definition at line 830 of file SelectionDAGNodes.h.
Referenced by operator!=().
Friends And Related Symbol Documentation
SDNode
friend class SDNode friend
Definition at line 816 of file SelectionDAGNodes.h.
References op, and SDNode.
Referenced by operator*(), operator->(), and SDNode.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h