LLVM: llvm::MergeFunctionsPass Class Reference
llvm::MergeFunctionsPass Class Reference
Merge identical functions.
#include "llvm/Transforms/IPO/MergeFunctions.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< MergeFunctionsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool runOnModule (Module &M)
static DenseMap< Function *, Function * > runOnFunctions (ArrayRef< Function * > F)
Static Public Member Functions inherited from llvm::PassInfoMixin< MergeFunctionsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Merge identical functions.
Definition at line 26 of file MergeFunctions.h.
Member Function Documentation
run()
PreservedAnalyses MergeFunctionsPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 309 of file MergeFunctions.cpp.
References llvm::PreservedAnalyses::all(), llvm::PreservedAnalyses::none(), and runOnModule().
runOnFunctions()
DenseMap< Function *, Function * > MergeFunctionsPass::runOnFunctions (ArrayRef< Function * > F) static
Definition at line 328 of file MergeFunctions.cpp.
References F.
runOnModule()
bool MergeFunctionsPass::runOnModule (Module & M) static
Definition at line 318 of file MergeFunctions.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::collectUsedGlobalVariables(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/MergeFunctions.h
lib/Transforms/IPO/MergeFunctions.cpp