LLVM: llvm::sandboxir::Use Class Reference
llvm::sandboxir::Use Class Reference
Represents a Def-use/Use-def edge in SandboxIR.
#include "llvm/SandboxIR/Use.h"
Public Member Functions
operator Value * () const
Value * get () const
void set (Value *V)
class User * getUser () const
unsigned getOperandNo () const
void swap (Use &OtherUse)
Context * getContext () const
bool operator== (const Use &Other) const
bool operator!= (const Use &Other) const
void dumpOS (raw_ostream &OS) const
void dump () const
Friends
class Value
class User
class OperandUseIterator
class UserUseIterator
class CallBase
class CallBrInst
class PHINode
Detailed Description
Represents a Def-use/Use-def edge in SandboxIR.
NOTE: Unlike llvm::Use, this is not an integral part of the use-def chains. It is also not uniqued and is currently passed by value, so you can have more than one sandboxir::Use objects for the same use-def edge.
Definition at line 32 of file Use.h.
Member Function Documentation
dump()
void llvm::sandboxir::Use::dump () const
Definition at line 58 of file Use.cpp.
References llvm::dbgs(), and dumpOS().
dumpOS()
void llvm::sandboxir::Use::dumpOS (raw_ostream & OS) const
Definition at line 30 of file Use.cpp.
Referenced by dump().
get()
Value * llvm::sandboxir::Use::get () const
Definition at line 15 of file Use.cpp.
References Value.
Referenced by llvm::sandboxir::EraseFromParent::EraseFromParent(), llvm::sandboxir::User::getOperand(), and operator Value *().
getContext()
Context * llvm::sandboxir::Use::getContext () const inline
Definition at line 57 of file Use.h.
getOperandNo()
unsigned llvm::sandboxir::Use::getOperandNo () const
Definition at line 22 of file Use.cpp.
getUser()
class User * llvm::sandboxir::Use::getUser () const inline
Definition at line 54 of file Use.h.
References User.
Referenced by llvm::sandboxir::OperandUseIterator::operator+(), and llvm::sandboxir::OperandUseIterator::operator-().
operator Value *()
llvm::sandboxir::Use::operator Value * () const inline
Definition at line 51 of file Use.h.
References get(), and Value.
operator!=()
bool llvm::sandboxir::Use::operator!= (const Use & Other) const inline
Definition at line 62 of file Use.h.
References llvm::Other.
operator==()
bool llvm::sandboxir::Use::operator== (const Use & Other) const inline
Definition at line 58 of file Use.h.
References assert(), and llvm::Other.
set()
void llvm::sandboxir::Use::set (Value * V)
Definition at line 17 of file Use.cpp.
References Value.
Referenced by llvm::sandboxir::CallBase::setCalledOperand().
swap()
void llvm::sandboxir::Use::swap (Use & OtherUse)
Definition at line 24 of file Use.cpp.
Friends And Related Symbol Documentation
CallBase
friend class CallBase friend
Definition at line 46 of file Use.h.
References CallBase.
Referenced by CallBase.
CallBrInst
friend class CallBrInst friend
Definition at line 47 of file Use.h.
References CallBrInst.
Referenced by CallBrInst.
OperandUseIterator
friend class OperandUseIterator friend
Definition at line 44 of file Use.h.
References OperandUseIterator.
Referenced by OperandUseIterator.
PHINode
friend class PHINode friend
Definition at line 48 of file Use.h.
References PHINode.
Referenced by PHINode.
User
friend class User friend
Definition at line 43 of file Use.h.
References User.
Referenced by getUser(), and User.
UserUseIterator
friend class UserUseIterator friend
Definition at line 45 of file Use.h.
References UserUseIterator.
Referenced by UserUseIterator.
Value
friend class Value friend
Definition at line 42 of file Use.h.
References Value.
Referenced by get(), operator Value *(), set(), and Value.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Use.h
lib/SandboxIR/Use.cpp