LLVM: llvm::MCAsmBackend Class Reference
llvm::MCAsmBackend Class Reference abstract
Generic interface to target specific assembler backends.
#include "llvm/MC/MCAsmBackend.h"
Public Member Functions
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
bool allowLinkerRelaxation () const
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
Target Fixup Interfaces
virtual unsigned getNumFixupKinds () const =0
Get the number of target specific fixup kinds.
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const
Get information on a fixup kind.
virtual bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, const uint64_t Value, const MCSubtargetInfo *STI)
Hook to check if a relocation is needed for some target specific reason.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, const MCSubtargetInfo *STI, uint64_t &Value, bool &WasForced)
virtual bool handleAddSubRelocations (const MCAssembler &Asm, const MCFragment &F, const MCFixup &Fixup, const MCValue &Target, uint64_t &FixedValue) const
virtual void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const =0
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Target Relaxation Interfaces
virtual bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const
Check whether the given instruction may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCAssembler &Asm, const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const
Relax the instruction in the given fragment to the next wider instruction.
virtual bool relaxDwarfLineAddr (const MCAssembler &Asm, MCDwarfLineAddrFragment &DF, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (const MCAssembler &Asm, MCDwarfCallFrameFragment &DF, bool &WasRelaxed) const
virtual std::pair< bool, bool > relaxLEB128 (const MCAssembler &Asm, MCLEBFragment &LF, int64_t &Value) const
Public Attributes
const llvm::endianness Endian
const unsigned RelaxFixupKind
Fixup kind used for linker relaxation.
Protected Member Functions
MCAsmBackend (llvm::endianness Endian, unsigned RelaxFixupKind=MaxFixupKind)
Detailed Description
Generic interface to target specific assembler backends.
Definition at line 42 of file MCAsmBackend.h.
Constructor & Destructor Documentation
MCAsmBackend() [1/2]
MCAsmBackend::MCAsmBackend (llvm::endianness Endian, unsigned RelaxFixupKind = MaxFixupKind) protected
Definition at line 27 of file MCAsmBackend.cpp.
References Endian, and RelaxFixupKind.
Referenced by llvm::ARMAsmBackend::ARMAsmBackend(), llvm::AVRAsmBackend::AVRAsmBackend(), llvm::CSKYAsmBackend::CSKYAsmBackend(), llvm::LoongArchAsmBackend::LoongArchAsmBackend(), MCAsmBackend(), llvm::MipsAsmBackend::MipsAsmBackend(), operator=(), llvm::RISCVAsmBackend::RISCVAsmBackend(), and llvm::XtensaMCAsmBackend::XtensaMCAsmBackend().
MCAsmBackend() [2/2]
llvm::MCAsmBackend::MCAsmBackend (const MCAsmBackend &) delete
References MCAsmBackend().
~MCAsmBackend()
MCAsmBackend::~MCAsmBackend () virtual default
Member Function Documentation
allowAutoPadding()
virtual bool llvm::MCAsmBackend::allowAutoPadding () const inline virtual
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
Definition at line 60 of file MCAsmBackend.h.
allowEnhancedRelaxation()
virtual bool llvm::MCAsmBackend::allowEnhancedRelaxation () const inline virtual
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
Definition at line 64 of file MCAsmBackend.h.
allowLinkerRelaxation()
bool llvm::MCAsmBackend::allowLinkerRelaxation () const inline
Definition at line 56 of file MCAsmBackend.h.
References llvm::MaxFixupKind, and RelaxFixupKind.
applyFixup()
virtual void llvm::MCAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const pure virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
References llvm::Data, and Fixup.
Referenced by llvm::MCAssembler::layout().
createDwoObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createDwoObjectWriter (raw_pwrite_stream & OS, raw_pwrite_stream & DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
This function is only supported with ELF targets.
Definition at line 67 of file MCAsmBackend.cpp.
References llvm::cast(), llvm::Triple::COFF, createObjectTargetWriter(), llvm::createWasmDwoObjectWriter(), llvm::createWinCOFFDwoObjectWriter(), llvm::Triple::ELF, Endian, llvm::little, llvm::report_fatal_error(), and llvm::Triple::Wasm.
Referenced by llvm::CodeGenTargetMachineImpl::createMCStreamer().
createObjectTargetWriter()
virtual std::unique_ptr< MCObjectTargetWriter > llvm::MCAsmBackend::createObjectTargetWriter () const pure virtual
Implemented in llvm::ARMAsmBackendDarwin, llvm::ARMAsmBackendELF, llvm::ARMAsmBackendWinCOFF, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
Referenced by createDwoObjectWriter(), and createObjectWriter().
createObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createObjectWriter (raw_pwrite_stream & OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
Definition at line 33 of file MCAsmBackend.cpp.
References llvm::cast(), llvm::Triple::COFF, llvm::createGOFFObjectWriter(), createObjectTargetWriter(), llvm::createSPIRVObjectWriter(), llvm::createWasmObjectWriter(), llvm::createWinCOFFObjectWriter(), llvm::createXCOFFObjectWriter(), llvm::Triple::DXContainer, llvm::Triple::ELF, Endian, llvm::Triple::GOFF, llvm::little, llvm_unreachable, llvm::Triple::MachO, llvm::Triple::SPIRV, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
Referenced by llvm::CodeGenTargetMachineImpl::addPassesToEmitMC(), and llvm::CodeGenTargetMachineImpl::createMCStreamer().
evaluateTargetFixup()
virtual bool llvm::MCAsmBackend::evaluateTargetFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCFragment * DF, const MCValue & Target, const MCSubtargetInfo * STI, uint64_t & Value, bool & WasForced) inline virtual
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 119 of file MCAsmBackend.h.
References DF, Fixup, and llvm_unreachable.
finishLayout()
virtual void llvm::MCAsmBackend::finishLayout (MCAssembler const & Asm) const inline virtual
Give backend an opportunity to finish layout after relaxation.
Definition at line 224 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::layout().
fixupNeedsRelaxation()
virtual bool llvm::MCAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value) const inline virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Reimplemented in llvm::ARMAsmBackend, and llvm::CSKYAsmBackend.
Definition at line 170 of file MCAsmBackend.h.
References Fixup, and llvm_unreachable.
Referenced by fixupNeedsRelaxationAdvanced().
fixupNeedsRelaxationAdvanced()
bool MCAsmBackend::fixupNeedsRelaxationAdvanced (const MCAssembler & Asm, const MCFixup & Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment * DF, const bool WasForced) const virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented in llvm::CSKYAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 120 of file MCAsmBackend.cpp.
References DF, Fixup, and fixupNeedsRelaxation().
generateCompactUnwindEncoding()
virtual uint64_t llvm::MCAsmBackend::generateCompactUnwindEncoding (const MCDwarfFrameInfo * FI, const MCContext * Ctxt) const inline virtual
Generate the compact unwind encoding for the CFI instructions.
Reimplemented in llvm::ARMAsmBackendDarwin.
Definition at line 230 of file MCAsmBackend.h.
Referenced by llvm::MCStreamer::generateCompactUnwindEncodings().
getFixupKind()
std::optional< MCFixupKind > MCAsmBackend::getFixupKind (StringRef Name) const virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented in llvm::ARMAsmBackend, llvm::ARMAsmBackendELF, llvm::AVRAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 86 of file MCAsmBackend.cpp.
Referenced by llvm::MCXCOFFStreamer::emitXCOFFRefDirective(), and llvm::MipsAsmBackend::getFixupKind().
getFixupKindInfo()
const MCFixupKindInfo & MCAsmBackend::getFixupKindInfo (MCFixupKind Kind) const virtual
Get information on a fixup kind.
Reimplemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
Definition at line 90 of file MCAsmBackend.cpp.
References assert(), and llvm::MCFixupKindInfo::FKF_IsPCRel.
Referenced by llvm::ARMAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::RISCVAsmBackend::getFixupKindInfo(), llvm::XtensaMCAsmBackend::getFixupKindInfo(), and llvm::ELFObjectWriter::recordRelocation().
getMaximumNopSize()
virtual unsigned llvm::MCAsmBackend::getMaximumNopSize (const MCSubtargetInfo & STI) const inline virtual
Returns the maximum size of a nop in bytes on this target.
Definition at line 212 of file MCAsmBackend.h.
getMinimumNopSize()
virtual unsigned llvm::MCAsmBackend::getMinimumNopSize () const inline virtual
Returns the minimum size of a nop in bytes on this target.
The assembler will use this to emit excess padding in situations where the padding required for simple alignment would be less than the minimum nop size.
Definition at line 208 of file MCAsmBackend.h.
getNumFixupKinds()
virtual unsigned llvm::MCAsmBackend::getNumFixupKinds () const pure virtual
Get the number of target specific fixup kinds.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
handleAddSubRelocations()
virtual bool llvm::MCAsmBackend::handleAddSubRelocations (const MCAssembler & Asm, const MCFragment & F, const MCFixup & Fixup, const MCValue & Target, uint64_t & FixedValue) const inline virtual
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 127 of file MCAsmBackend.h.
References F, and Fixup.
handleAssemblerFlag()
virtual void llvm::MCAsmBackend::handleAssemblerFlag (MCAssemblerFlag Flag) inline virtual
Handle any target-specific assembler flags. By default, do nothing.
Reimplemented in llvm::ARMAsmBackend.
Definition at line 227 of file MCAsmBackend.h.
Referenced by llvm::MCELFStreamer::emitAssemblerFlag(), llvm::MCWasmStreamer::emitAssemblerFlag(), and llvm::MCWinCOFFStreamer::emitAssemblerFlag().
isDarwinCanonicalPersonality()
bool MCAsmBackend::isDarwinCanonicalPersonality (const MCSymbol * Sym) const
Definition at line 130 of file MCAsmBackend.cpp.
References llvm::MCSymbol::getName(), llvm::MCSymbol::isMachO(), llvm_unreachable, and name.
Referenced by llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding().
isMicroMips()
virtual bool llvm::MCAsmBackend::isMicroMips (const MCSymbol * Sym) const inline virtual
Check whether a given symbol has been flagged with MICROMIPS flag.
Reimplemented in llvm::MipsAsmBackend.
Definition at line 236 of file MCAsmBackend.h.
mayNeedRelaxation()
virtual bool llvm::MCAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const inline virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Reimplemented in llvm::ARMAsmBackend, llvm::CSKYAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
Definition at line 156 of file MCAsmBackend.h.
operator=()
MCAsmBackend & llvm::MCAsmBackend::operator= (const MCAsmBackend &) delete
References MCAsmBackend().
relaxDwarfCFA()
virtual bool llvm::MCAsmBackend::relaxDwarfCFA (const MCAssembler & Asm, MCDwarfCallFrameFragment & DF, bool & WasRelaxed) const inline virtual
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 189 of file MCAsmBackend.h.
References DF.
relaxDwarfLineAddr()
virtual bool llvm::MCAsmBackend::relaxDwarfLineAddr (const MCAssembler & Asm, MCDwarfLineAddrFragment & DF, bool & WasRelaxed) const inline virtual
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 183 of file MCAsmBackend.h.
References DF.
relaxInstruction()
virtual void llvm::MCAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const inline virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented in llvm::ARMAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
Definition at line 180 of file MCAsmBackend.h.
relaxLEB128()
virtual std::pair< bool, bool > llvm::MCAsmBackend::relaxLEB128 (const MCAssembler & Asm, MCLEBFragment & LF, int64_t & Value) const inline virtual
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 198 of file MCAsmBackend.h.
reset()
virtual void llvm::MCAsmBackend::reset () inline virtual
lifetime management
Definition at line 67 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::reset().
shouldForceRelocation()
virtual bool llvm::MCAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, const uint64_t Value, const MCSubtargetInfo * STI) inline virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 96 of file MCAsmBackend.h.
References Fixup.
shouldInsertExtraNopBytesForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment & AF, unsigned & Size) inline virtual
Hook to check if extra nop bytes must be inserted for alignment directive.
For some targets this may be necessary in order to support linker relaxation. The number of bytes to insert are returned in Size.
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 107 of file MCAsmBackend.h.
References Size.
shouldInsertFixupForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertFixupForCodeAlign (MCAssembler & Asm, MCAlignFragment & AF) inline virtual
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
Reimplemented in llvm::LoongArchAsmBackend, and llvm::RISCVAsmBackend.
Definition at line 114 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::layout().
writeNopData()
virtual bool llvm::MCAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const pure virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implemented in llvm::ARMAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::RISCVAsmBackend, and llvm::XtensaMCAsmBackend.
References llvm::Count.
Member Data Documentation
Endian
const llvm::endianness llvm::MCAsmBackend::Endian
Definition at line 51 of file MCAsmBackend.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), llvm::ARMAsmBackend::applyFixup(), llvm::CSKYAsmBackend::applyFixup(), llvm::MipsAsmBackend::applyFixup(), llvm::ARMAsmBackend::ARMAsmBackend(), llvm::ARMAsmBackendELF::ARMAsmBackendELF(), createDwoObjectWriter(), createObjectWriter(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), MCAsmBackend(), and llvm::ARMAsmBackend::writeNopData().
RelaxFixupKind
const unsigned llvm::MCAsmBackend::RelaxFixupKind
Fixup kind used for linker relaxation.
Currently only used by RISC-V and LoongArch.
Definition at line 55 of file MCAsmBackend.h.
Referenced by allowLinkerRelaxation(), and MCAsmBackend().
The documentation for this class was generated from the following files:
include/llvm/MC/MCAsmBackend.h
lib/MC/MCAsmBackend.cpp