LLVM: llvm::VPRecipeBuilder Class Reference
llvm::VPRecipeBuilder Class Reference
Helper class to create VPRecipies from IR instructions.
#include "Transforms/Vectorize/VPRecipeBuilder.h"
Public Member Functions
VPRecipeBuilder (VPlan &Plan, Loop *OrigLoop, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, LoopVectorizationLegality *Legal, LoopVectorizationCostModel &CM, PredicatedScalarEvolution &PSE, VPBuilder &Builder)
std::optional< unsigned > getScalingForReduction (const Instruction *ExitInst)
void collectScaledReductions (VFRange &Range)
Find all possible partial reductions in the loop and track all of those that are valid so recipes can be formed later.
VPRecipeBase * tryToCreateWidenRecipe (Instruction *Instr, ArrayRef< VPValue * > Operands, VFRange &Range, VPBasicBlock *VPBB)
Create and return a widened recipe for I if one can be created within the given VF Range.
VPRecipeBase * tryToCreatePartialReduction (Instruction *Reduction, ArrayRef< VPValue * > Operands)
Create and return a partial reduction recipe for a reduction instruction along with binary operation and reduction phi operands.
void setRecipe (Instruction *I, VPRecipeBase *R)
Set the recipe created for given ingredient.
void createHeaderMask ()
Create the mask for the vector loop header block.
void createBlockInMask (BasicBlock *BB)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True or the loop mask when tail folding.
VPValue * getBlockInMask (BasicBlock *BB) const
Returns the entry mask for the block BB.
void createSwitchEdgeMasks (SwitchInst *SI)
Create an edge mask for every destination of cases and/or default.
VPValue * createEdgeMask (BasicBlock *Src, BasicBlock *Dst)
A helper function that computes the predicate of the edge between SRC and DST.
VPValue * getEdgeMask (BasicBlock *Src, BasicBlock *Dst) const
A helper that returns the previously computed predicate of the edge between SRC and DST.
VPRecipeBase * getRecipe (Instruction *I)
Return the recipe created for given ingredient.
VPReplicateRecipe * handleReplication (Instruction *I, VFRange &Range)
Build a VPReplicationRecipe for I.
void fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
iterator_range< mapped_iterator< Use *, std::function< VPValue *(Value *)> > > mapToVPValues (User::op_range Operands)
Returns a range mapping the values of the range Operands to their corresponding VPValues.
VPValue * getVPValueOrAddLiveIn (Value *V)
Detailed Description
Helper class to create VPRecipies from IR instructions.
Definition at line 47 of file VPRecipeBuilder.h.
Constructor & Destructor Documentation
VPRecipeBuilder()
llvm::VPRecipeBuilder::VPRecipeBuilder (VPlan & Plan, Loop * OrigLoop, const TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, LoopVectorizationLegality * Legal, LoopVectorizationCostModel & CM, PredicatedScalarEvolution & PSE, VPBuilder & Builder) inline
Definition at line 154 of file VPRecipeBuilder.h.
Member Function Documentation
collectScaledReductions()
void VPRecipeBuilder::collectScaledReductions (VFRange & Range)
Find all possible partial reductions in the loop and track all of those that are valid so recipes can be formed later.
Definition at line 8676 of file LoopVectorize.cpp.
References _, llvm::all_of(), llvm::PartialReductionChain::ExtendA, llvm::PartialReductionChain::ExtendB, llvm::SmallSet< T, N, C >::insert(), Range, and llvm::PartialReductionChain::Reduction.
createBlockInMask()
void VPRecipeBuilder::createBlockInMask (BasicBlock * BB)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True or the loop mask when tail folding.
Definition at line 8207 of file LoopVectorize.cpp.
References assert(), createEdgeMask(), llvm::pred_begin(), and llvm::pred_end().
createEdgeMask()
VPValue * VPRecipeBuilder::createEdgeMask (BasicBlock * Src, BasicBlock * Dst)
A helper function that computes the predicate of the edge between SRC and DST.
Definition at line 8113 of file LoopVectorize.cpp.
References assert(), createSwitchEdgeMasks(), llvm::dyn_cast(), getBlockInMask(), llvm::BranchInst::getCondition(), llvm::Instruction::getDebugLoc(), llvm::BranchInst::getSuccessor(), getVPValueOrAddLiveIn(), llvm::is_contained(), llvm::BranchInst::isConditional(), and llvm::predecessors().
Referenced by createBlockInMask().
createHeaderMask()
void VPRecipeBuilder::createHeaderMask ()
Create the mask for the vector loop header block.
Definition at line 8172 of file LoopVectorize.cpp.
References llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::CmpInst::ICMP_ULE, llvm::VPBasicBlock::insert(), and IV.
createSwitchEdgeMasks()
void VPRecipeBuilder::createSwitchEdgeMasks (SwitchInst * SI)
Create an edge mask for every destination of cases and/or default.
Definition at line 8057 of file LoopVectorize.cpp.
References llvm::all_of(), assert(), llvm::CallingConv::C, Cond, getBlockInMask(), getVPValueOrAddLiveIn(), llvm::CmpInst::ICMP_EQ, and llvm::successors().
Referenced by createEdgeMask().
fixHeaderPhis()
void VPRecipeBuilder::fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
Definition at line 8602 of file LoopVectorize.cpp.
References llvm::cast(), getRecipe(), and llvm::VPDef::getVPSingleValue().
getBlockInMask()
VPValue * VPRecipeBuilder::getBlockInMask (BasicBlock * BB) const
Returns the entry mask for the block BB.
Definition at line 8199 of file LoopVectorize.cpp.
References assert().
Referenced by createEdgeMask(), createSwitchEdgeMasks(), handleReplication(), and llvm::VPlanTransforms::handleUncountableEarlyExit().
getEdgeMask()
VPValue * VPRecipeBuilder::getEdgeMask (BasicBlock * Src, BasicBlock * Dst) const
A helper that returns the previously computed predicate of the edge between SRC and DST.
Definition at line 8161 of file LoopVectorize.cpp.
References assert(), llvm::is_contained(), and llvm::predecessors().
getRecipe()
VPRecipeBase * llvm::VPRecipeBuilder::getRecipe (Instruction * I) inline
Return the recipe created for given ingredient.
Definition at line 213 of file VPRecipeBuilder.h.
References assert(), and I.
Referenced by llvm::VPlanTransforms::createInterleaveGroups(), and fixHeaderPhis().
getScalingForReduction()
std::optional< unsigned > llvm::VPRecipeBuilder::getScalingForReduction (const Instruction * ExitInst) inline
Definition at line 162 of file VPRecipeBuilder.h.
Referenced by tryToCreateWidenRecipe().
getVPValueOrAddLiveIn()
VPValue * llvm::VPRecipeBuilder::getVPValueOrAddLiveIn (Value * V) inline
Definition at line 235 of file VPRecipeBuilder.h.
References llvm::dyn_cast(), and I.
Referenced by createEdgeMask(), createSwitchEdgeMasks(), llvm::VPlanTransforms::handleUncountableEarlyExit(), and mapToVPValues().
handleReplication()
VPReplicateRecipe * VPRecipeBuilder::handleReplication (Instruction * I, VFRange & Range)
Build a VPReplicationRecipe for I.
If it is predicated, add the mask as last operand. Range.End may be decreased to ensure same recipe behavior from Range.Start to Range.End.
Definition at line 8612 of file LoopVectorize.cpp.
References assert(), llvm::cast(), llvm::dbgs(), getBlockInMask(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), getIntrinsicID(), I, llvm::isa(), LLVM_DEBUG, mapToVPValues(), and Range.
mapToVPValues()
iterator_range< mapped_iterator< Use *, std::function< VPValue *(Value *)> > > VPRecipeBuilder::mapToVPValues (User::op_range Operands)
Returns a range mapping the values of the range Operands to their corresponding VPValues.
Definition at line 8050 of file LoopVectorize.cpp.
References getVPValueOrAddLiveIn(), llvm::map_range(), mapToVPValues(), and Operands.
Referenced by handleReplication(), and mapToVPValues().
setRecipe()
void llvm::VPRecipeBuilder::setRecipe (Instruction * I, VPRecipeBase * R) inline
Set the recipe created for given ingredient.
Definition at line 184 of file VPRecipeBuilder.h.
References assert(), and I.
tryToCreatePartialReduction()
VPRecipeBase * VPRecipeBuilder::tryToCreatePartialReduction (Instruction * Reduction, ArrayRef< VPValue * > Operands)
Create and return a partial reduction recipe for a reduction instruction along with binary operation and reduction phi operands.
Definition at line 8876 of file LoopVectorize.cpp.
References Accumulator, assert(), llvm::VPValue::getDefiningRecipe(), llvm::isa(), Operands, and std::swap().
Referenced by tryToCreateWidenRecipe().
tryToCreateWidenRecipe()
VPRecipeBase * VPRecipeBuilder::tryToCreateWidenRecipe (Instruction * Instr, ArrayRef< VPValue * > Operands, VFRange & Range, VPBasicBlock * VPBB)
Create and return a widened recipe for I if one can be created within the given VF Range.
Definition at line 8791 of file LoopVectorize.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), GEP, llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::RecurrenceDescriptor::getLoopExitInstr(), llvm::Instruction::getOpcode(), llvm::RecurrenceDescriptor::getRecurrenceStartValue(), getScalingForReduction(), llvm::Value::getType(), llvm::isa(), llvm::ElementCount::isScalar(), llvm::make_range(), Operands, Range, and tryToCreatePartialReduction().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPRecipeBuilder.h
lib/Transforms/Vectorize/LoopVectorize.cpp