LLVM: llvm::SelectionDAGISelPass Class Reference
llvm::SelectionDAGISelPass Class Reference
#include "llvm/CodeGen/SelectionDAGISel.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< SelectionDAGISelPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< SelectionDAGISelPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Protected Member Functions
SelectionDAGISelPass (std::unique_ptr< SelectionDAGISel > Selector)
Detailed Description
Definition at line 552 of file SelectionDAGISel.h.
Constructor & Destructor Documentation
SelectionDAGISelPass()
llvm::SelectionDAGISelPass::SelectionDAGISelPass (std::unique_ptr< SelectionDAGISel > Selector) inline protected
Definition at line 556 of file SelectionDAGISel.h.
References llvm::move().
Referenced by llvm::AMDGPUISelDAGToDAGPass::AMDGPUISelDAGToDAGPass(), and llvm::X86ISelDAGToDAGPass::X86ISelDAGToDAGPass().
Member Function Documentation
isRequired()
static bool llvm::SelectionDAGISelPass::isRequired () inline static
Definition at line 562 of file SelectionDAGISel.h.
run()
PreservedAnalyses SelectionDAGISelPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 422 of file SelectionDAGISel.cpp.
References llvm::PreservedAnalyses::all(), EnableFastISelAbort, llvm::MachineFunction::getFunction(), llvm::getMachineFunctionPassPreservedAnalyses(), llvm::MachineFunction::getProperties(), llvm::Function::hasOptNone(), llvm::MachineFunctionProperties::hasProperty(), llvm::None, llvm::report_fatal_error(), llvm::MachineFunctionProperties::Selected, llvm::MachineFunction::setUseDebugInstrRef(), and llvm::MachineFunction::shouldUseDebugInstrRef().
Referenced by llvm::AMDGPUISelDAGToDAGPass::run().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGISel.h
lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp