LLVM: llvm::sandboxir::PredIterator Class Reference
llvm::sandboxir::PredIterator Class Reference
Iterate over both def-use and mem dependencies.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Public Types
using difference_type = std::ptrdiff_t
using value_type = DGNode *
using pointer = value_type *
using reference = value_type &
using iterator_category = std::input_iterator_tag
Public Member Functions
value_type operator* ()
PredIterator & operator++ ()
PredIterator operator++ (int)
bool operator== (const PredIterator &Other) const
bool operator!= (const PredIterator &Other) const
Friends
class DGNode
class MemDGNode
Detailed Description
Iterate over both def-use and mem dependencies.
Definition at line 58 of file DependencyGraph.h.
Member Typedef Documentation
difference_type
using llvm::sandboxir::PredIterator::difference_type = std::ptrdiff_t
Definition at line 76 of file DependencyGraph.h.
iterator_category
using llvm::sandboxir::PredIterator::iterator_category = std::input_iterator_tag
Definition at line 80 of file DependencyGraph.h.
pointer
using llvm::sandboxir::PredIterator::pointer = value_type *
Definition at line 78 of file DependencyGraph.h.
reference
using llvm::sandboxir::PredIterator::reference = value_type &
Definition at line 79 of file DependencyGraph.h.
value_type
using llvm::sandboxir::PredIterator::value_type = DGNode *
Definition at line 77 of file DependencyGraph.h.
Member Function Documentation
operator!=()
bool llvm::sandboxir::PredIterator::operator!= (const PredIterator & Other) const inline
Definition at line 89 of file DependencyGraph.h.
References llvm::Other.
operator*()
PredIterator::value_type llvm::sandboxir::PredIterator::operator* ()
Definition at line 17 of file DependencyGraph.cpp.
References assert(), llvm::cast(), and llvm::isa().
operator++() [1/2]
PredIterator & llvm::sandboxir::PredIterator::operator++ ()
Definition at line 33 of file DependencyGraph.cpp.
References assert(), llvm::cast(), llvm::isa(), and llvm::sandboxir::skipNonInstr().
operator++() [2/2]
PredIterator llvm::sandboxir::PredIterator::operator++ (int) inline
Definition at line 83 of file DependencyGraph.h.
operator==()
bool llvm::sandboxir::PredIterator::operator== (const PredIterator & Other) const
Definition at line 56 of file DependencyGraph.cpp.
References assert(), and llvm::Other.
Friends And Related Symbol Documentation
DGNode
friend class DGNode friend
Definition at line 72 of file DependencyGraph.h.
References DGNode.
Referenced by DGNode.
MemDGNode
friend class MemDGNode friend
Definition at line 73 of file DependencyGraph.h.
References MemDGNode.
Referenced by MemDGNode.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp