LLVM: llvm::StringMapEntryBase Class Reference
llvm::StringMapEntryBase Class Reference
StringMapEntryBase - Shared base class of StringMapEntry instances.
#include "llvm/ADT/StringMapEntry.h"
Public Member Functions
StringMapEntryBase (size_t keyLength)
size_t getKeyLength () const
Static Protected Member Functions
template<typename AllocatorTy>
static void * allocateWithKey (size_t EntrySize, size_t EntryAlign, StringRef Key, AllocatorTy &Allocator)
Helper to tail-allocate Key.
Detailed Description
StringMapEntryBase - Shared base class of StringMapEntry instances.
Definition at line 25 of file StringMapEntry.h.
Constructor & Destructor Documentation
StringMapEntryBase()
llvm::StringMapEntryBase::StringMapEntryBase (size_t keyLength) inline explicit
Definition at line 29 of file StringMapEntry.h.
Referenced by llvm::StringMapEntryStorage< ValueTy >::StringMapEntryStorage(), llvm::StringMapEntryStorage< ValueTy >::StringMapEntryStorage(), and llvm::StringMapEntryStorage< std::nullopt_t >::StringMapEntryStorage().
Member Function Documentation
allocateWithKey()
template<typename AllocatorTy> void * llvm::StringMapEntryBase::allocateWithKey (size_t EntrySize, size_t EntryAlign, StringRef Key, AllocatorTy & Allocator) static protected
Helper to tail-allocate Key.
It'd be nice to generalize this so it could be reused elsewhere, maybe even taking an llvm::function_ref to type-erase the allocator and put it in a source file.
Definition at line 44 of file StringMapEntry.h.
References Allocator, assert(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::StringMapEntry< std::nullopt_t >::create().
getKeyLength()
size_t llvm::StringMapEntryBase::getKeyLength () const inline
Definition at line 31 of file StringMapEntry.h.
Referenced by llvm::StringMapEntry< std::nullopt_t >::Destroy(), llvm::StringMapImpl::FindKey(), llvm::TargetIntrinsicInfo::getIntrinsicID(), llvm::StringMapEntry< std::nullopt_t >::getKey(), and llvm::StringMapImpl::LookupBucketFor().
The documentation for this class was generated from the following file:
include/llvm/ADT/StringMapEntry.h