LLVM: ShapeCalculator Class Reference
ShapeCalculator Class Reference
Public Member Functions
ShapeCalculator (TargetMachine *TargetM)
std::pair< Value *, Value * > getShape (IntrinsicInst *II, unsigned OpNo)
std::pair< Value *, Value * > getShape (PHINode *Phi)
Value * getRowFromCol (Instruction *II, Value *V, unsigned Granularity)
Value * getColFromRow (Instruction *II, Value *V, unsigned Granularity)
Detailed Description
Definition at line 138 of file X86LowerAMXType.cpp.
Constructor & Destructor Documentation
ShapeCalculator()
ShapeCalculator::ShapeCalculator (TargetMachine * TargetM) inline
Definition at line 148 of file X86LowerAMXType.cpp.
Member Function Documentation
getColFromRow()
Value * ShapeCalculator::getColFromRow (Instruction * II, Value * V, unsigned Granularity)
Definition at line 191 of file X86LowerAMXType.cpp.
References llvm::cast(), llvm::IRBuilderBase::CreateNUWMul(), getFirstNonAllocaInTheEntryBlock(), llvm::IRBuilderBase::getInt16(), II, and llvm::isa().
Referenced by getShape().
getRowFromCol()
Value * ShapeCalculator::getRowFromCol (Instruction * II, Value * V, unsigned Granularity)
Definition at line 155 of file X86LowerAMXType.cpp.
References llvm::cast(), llvm::IRBuilderBase::CreateUDiv(), getFirstNonAllocaInTheEntryBlock(), llvm::IRBuilderBase::getInt16(), II, and llvm::isa().
Referenced by getShape().
getShape() [1/2]
std::pair< Value *, Value * > ShapeCalculator::getShape (IntrinsicInst * II, unsigned OpNo)
Definition at line 216 of file X86LowerAMXType.cpp.
References assert(), getColFromRow(), getRowFromCol(), II, and llvm_unreachable.
Referenced by getShape().
getShape() [2/2]
std::pair< Value *, Value * > ShapeCalculator::getShape (PHINode * Phi)
Definition at line 317 of file X86LowerAMXType.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::Use::getOperandNo(), getShape(), llvm::Use::getUser(), llvm::isa(), isAMXCast(), and isAMXIntrinsic().
The documentation for this class was generated from the following file:
lib/Target/X86/X86LowerAMXType.cpp