LLVM: llvm::AssignGUIDPass Class Reference
llvm::AssignGUIDPass Class Reference
Assign a GUID to functions as metadata.
#include "llvm/Analysis/CtxProfAnalysis.h"
Public Member Functions
AssignGUIDPass ()=default
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Assign a GUID if one is not already assign, as a function metadata named GUIDMetadataName.
Public Member Functions inherited from llvm::PassInfoMixin< AssignGUIDPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static uint64_t getGUID (const Function &F)
Static Public Member Functions inherited from llvm::PassInfoMixin< AssignGUIDPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Static Public Attributes
static const char * GUIDMetadataName = "guid"
Detailed Description
Assign a GUID to functions as metadata.
GUID calculation takes linkage into account, which may change especially through and after thinlto. By pre-computing and assigning as metadata, this mechanism is resilient to such changes (as well as name changes e.g. suffix ".llvm." additions).
Definition at line 163 of file CtxProfAnalysis.h.
Constructor & Destructor Documentation
AssignGUIDPass()
llvm::AssignGUIDPass::AssignGUIDPass () explicit default
References MAM.
Member Function Documentation
getGUID()
GlobalValue::GUID AssignGUIDPass::getGUID (const Function & F) static
Definition at line 57 of file CtxProfAnalysis.cpp.
References assert(), llvm::cast(), F, llvm::GlobalValue::getGUID(), GUIDMetadataName, and llvm::GlobalValue::isExternalLinkage().
Referenced by llvm::InlineFunction(), llvm::promoteCallWithIfThenElse(), llvm::CtxProfAnalysis::run(), and llvm::PGOCtxProfFlatteningPass::run().
run()
PreservedAnalyses AssignGUIDPass::run (Module & M, ModuleAnalysisManager & MAM)
Assign a GUID if one is not already assign, as a function metadata named GUIDMetadataName.
Definition at line 42 of file CtxProfAnalysis.cpp.
References F, llvm::MDNode::get(), GUIDMetadataName, MAM, and llvm::PreservedAnalyses::none().
Member Data Documentation
GUIDMetadataName
const char * AssignGUIDPass::GUIDMetadataName = "guid" static
Definition at line 170 of file CtxProfAnalysis.h.
Referenced by getGUID(), and run().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CtxProfAnalysis.h
lib/Analysis/CtxProfAnalysis.cpp