LLVM: lib/Transforms/Utils/CodeExtractor.cpp File Reference
CodeExtractor.cpp File Reference
#include "llvm/Transforms/Utils/CodeExtractor.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/BlockFrequency.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <map>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "code-extractor"
Functions
static bool isBlockValidForExtraction (const BasicBlock &BB, const SetVector< BasicBlock * > &Result, bool AllowVarArgs, bool AllowAlloca)
Test whether a block is valid for extraction.
static SetVector< BasicBlock * > buildExtractionBlockSet (ArrayRef< BasicBlock * > BBs, DominatorTree *DT, bool AllowVarArgs, bool AllowAlloca)
Build a set of blocks to extract if the input blocks are viable.
static bool definedInRegion (const SetVector< BasicBlock * > &Blocks, Value *V)
definedInRegion - Return true if the specified value is defined in the extracted region.
static bool definedInCaller (const SetVector< BasicBlock * > &Blocks, Value *V)
definedInCaller - Return true if the specified value is defined in the function being code extracted, but not in the region being extracted.
static BasicBlock * getCommonExitBlock (const SetVector< BasicBlock * > &Blocks)
static void applyFirstDebugLoc (Function *oldFunction, ArrayRef< BasicBlock * > Blocks, Instruction *BranchI)
If the original function has debug info, we have to add a debug location to the new branch instruction from the artificial entry block.
static void eraseLifetimeMarkersOnInputs (const SetVector< BasicBlock * > &Blocks, const SetVector< Value * > &SunkAllocas, SetVector< Value * > &LifetimesStart)
Erase lifetime.start markers which reference inputs to the extraction region, and insert the referenced memory into LifetimesStart.
static void insertLifetimeMarkersSurroundingCall (Module *M, ArrayRef< Value * > LifetimesStart, ArrayRef< Value * > LifetimesEnd, CallInst *TheCall)
Insert lifetime start/end markers surrounding the call to the new function for objects defined in the caller.
static void eraseDebugIntrinsicsWithNonLocalRefs (Function &F)
Erase debug info intrinsics which refer to values in F but aren't in F.
static void fixupDebugInfoPostExtraction (Function &OldFunc, Function &NewFunc, CallInst &TheCall)
Fix up the debug info in the old and new functions by pointing line locations and debug intrinsics to the new subprogram scope, and by deleting intrinsics which point to values outside of the new function.
Variables
static cl::opt< bool > AggregateArgsOpt ("aggregate-extracted-args", cl::Hidden, cl::desc("Aggregate arguments to code-extracted functions"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "code-extractor"
Definition at line 73 of file CodeExtractor.cpp.
Function Documentation
applyFirstDebugLoc()
static void applyFirstDebugLoc (Function * oldFunction, ArrayRef< BasicBlock * > Blocks, Instruction * BranchI) static
If the original function has debug info, we have to add a debug location to the new branch instruction from the artificial entry block.
We use the debug location of the first instruction in the extracted blocks, as there is no other equivalent line in the source code.
Definition at line 1057 of file CodeExtractor.cpp.
References llvm::any_of(), llvm::Function::getSubprogram(), I, llvm::isa(), and llvm::Instruction::setDebugLoc().
buildExtractionBlockSet()
static SetVector< BasicBlock * > buildExtractionBlockSet (ArrayRef< BasicBlock * > BBs, DominatorTree * DT, bool AllowVarArgs, bool AllowAlloca) static
Build a set of blocks to extract if the input blocks are viable.
Definition at line 195 of file CodeExtractor.cpp.
References assert(), llvm::dbgs(), llvm::ArrayRef< T >::empty(), isBlockValidForExtraction(), llvm::DominatorTree::isReachableFromEntry(), LLVM_DEBUG, llvm_unreachable, and llvm::predecessors().
Referenced by llvm::CodeExtractor::CodeExtractor().
definedInCaller()
static bool definedInCaller (const SetVector< BasicBlock * > & Blocks, Value * V) static
definedInCaller - Return true if the specified value is defined in the function being code extracted, but not in the region being extracted.
These values must be passed in as live-ins to the function.
Definition at line 267 of file CodeExtractor.cpp.
References llvm::SetVector< T, Vector, Set, N >::count(), llvm::dyn_cast(), I, and llvm::isa().
Referenced by llvm::CodeExtractor::findInputsOutputs().
definedInRegion()
static bool definedInRegion (const SetVector< BasicBlock * > & Blocks, Value * V) static
definedInRegion - Return true if the specified value is defined in the extracted region.
Definition at line 257 of file CodeExtractor.cpp.
References llvm::SetVector< T, Vector, Set, N >::count(), llvm::dyn_cast(), and I.
Referenced by eraseLifetimeMarkersOnInputs(), llvm::CodeExtractor::findAllocas(), llvm::CodeExtractor::findInputsOutputs(), and llvm::CodeExtractor::isEligible().
eraseDebugIntrinsicsWithNonLocalRefs()
static void eraseDebugIntrinsicsWithNonLocalRefs (Function & F) static
Erase debug info intrinsics which refer to values in F but aren't in F.
Definition at line 1212 of file CodeExtractor.cpp.
References F, llvm::findDbgUsers(), I, and instructions.
Referenced by fixupDebugInfoPostExtraction().
eraseLifetimeMarkersOnInputs()
static void eraseLifetimeMarkersOnInputs (const SetVector< BasicBlock * > & Blocks, const SetVector< Value * > & SunkAllocas, SetVector< Value * > & LifetimesStart) static
Erase lifetime.start markers which reference inputs to the extraction region, and insert the referenced memory into LifetimesStart.
The extraction region is defined by a set of blocks (Blocks), and a set of allocas which will be moved from the caller function into the extracted function (SunkAllocas).
Definition at line 1082 of file CodeExtractor.cpp.
References llvm::SetVector< T, Vector, Set, N >::count(), definedInRegion(), llvm::dyn_cast(), I, II, llvm::SetVector< T, Vector, Set, N >::insert(), and llvm::make_early_inc_range().
Referenced by llvm::CodeExtractor::extractCodeRegion().
fixupDebugInfoPostExtraction()
static void fixupDebugInfoPostExtraction (Function & OldFunc, Function & NewFunc, CallInst & TheCall) static
Fix up the debug info in the old and new functions by pointing line locations and debug intrinsics to the new subprogram scope, and by deleting intrinsics which point to values outside of the new function.
Definition at line 1229 of file CodeExtractor.cpp.
References llvm::any_of(), assert(), llvm::cast(), llvm::DILocalScope::cloneScopeForSubprogram(), llvm::DIBuilder::createAutoVariable(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createSubroutineType(), DL, llvm::dyn_cast(), llvm::dyn_cast_or_null(), eraseDebugIntrinsicsWithNonLocalRefs(), llvm::DIBuilder::finalizeSubprogram(), llvm::MDNode::get(), llvm::DbgVariableRecord::getAddress(), llvm::Function::getContext(), llvm::DbgRecord::getDebugLoc(), llvm::Instruction::getDebugLoc(), llvm::DILabel::getFile(), llvm::DIScope::getFile(), llvm::Instruction::getFunction(), llvm::DebugLoc::getInlinedAt(), llvm::DILabel::getLine(), llvm::DILabel::getName(), llvm::DIScope::getName(), llvm::Value::getName(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::GlobalValue::getParent(), llvm::DILabel::getScope(), llvm::Function::getSubprogram(), llvm::DbgVariableRecord::getVariable(), I, instructions, llvm::isa(), llvm::DbgVariableRecord::isDbgAssign(), llvm::DbgVariableRecord::location_ops(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::at::remapAssignID(), llvm::DebugLoc::replaceInlinedAtSubprogram(), llvm::Instruction::setDebugLoc(), llvm::Function::setSubprogram(), llvm::DbgVariableRecord::setVariable(), llvm::stripDebugInfo(), and llvm::updateLoopMetadataDebugLocations().
Referenced by llvm::CodeExtractor::extractCodeRegion().
getCommonExitBlock()
static BasicBlock * getCommonExitBlock (const SetVector< BasicBlock * > & Blocks) static
Definition at line 275 of file CodeExtractor.cpp.
References llvm::any_of(), llvm::Block, llvm::SetVector< T, Vector, Set, N >::count(), and llvm::successors().
Referenced by llvm::CodeExtractor::findAllocas().
insertLifetimeMarkersSurroundingCall()
static void insertLifetimeMarkersSurroundingCall (Module * M, ArrayRef< Value * > LifetimesStart, ArrayRef< Value * > LifetimesEnd, CallInst * TheCall) static
Insert lifetime start/end markers surrounding the call to the new function for objects defined in the caller.
Definition at line 1107 of file CodeExtractor.cpp.
References assert(), llvm::cast(), llvm::CallInst::Create(), llvm::ArrayRef< T >::empty(), getFunction(), llvm::Instruction::getFunction(), llvm::Type::getInt64Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::ConstantInt::getSigned(), llvm::Instruction::insertBefore(), and llvm::isa().
isBlockValidForExtraction()
static bool isBlockValidForExtraction (const BasicBlock & BB, const SetVector< BasicBlock * > & Result, bool AllowVarArgs, bool AllowAlloca) static
Test whether a block is valid for extraction.
Definition at line 84 of file CodeExtractor.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), llvm::dyn_cast(), E(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::BasicBlock::end(), F, getParent(), llvm::BasicBlock::hasAddressTaken(), I, II, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by buildExtractionBlockSet().
Variable Documentation
AggregateArgsOpt
cl::opt< bool > AggregateArgsOpt("aggregate-extracted-args", cl::Hidden, cl::desc("Aggregate arguments to code-extracted functions")) ("aggregate-extracted-args" , cl::Hidden , cl::desc("Aggregate arguments to code-extracted functions")) static
Referenced by llvm::CodeExtractor::CodeExtractor().