LLVM: lib/Support/DeltaTree.cpp File Reference
DeltaTree.cpp File Reference
#include "llvm/ADT/DeltaTree.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <cstring>
Functions
static DeltaTreeNode * getRoot (void *Root)
Function Documentation
getRoot()
static DeltaTreeNode * getRoot (void * Root) static
Definition at line 386 of file DeltaTree.cpp.
Referenced by llvm::DeltaTree::AddDelta(), llvm::RopePieceBTree::clear(), llvm::DeltaTree::DeltaTree(), llvm::RopePieceBTree::erase(), llvm::msgpack::Document::fromYAML(), llvm::DeltaTree::getDeltaAt(), llvm::RopePieceBTree::insert(), llvm::ThreadSafeTrieRawHashMapBase::ImplType::save(), llvm::RopePieceBTree::size(), llvm::msgpack::Document::toYAML(), llvm::DeltaTree::~DeltaTree(), and llvm::RopePieceBTree::~RopePieceBTree().