LLVM: lib/ObjCopy/ELF/ELFObjcopy.cpp File Reference
ELFObjcopy.cpp File Reference
#include "llvm/ObjCopy/ELF/ELFObjcopy.h"
#include "ELFObject.h"
#include "llvm/ADT/BitmaskEnum.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/ObjCopy/CommonConfig.h"
#include "llvm/ObjCopy/ELF/ELFConfig.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/ELFTypes.h"
#include "llvm/Object/Error.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <functional>
#include <memory>
#include <string>
#include <system_error>
#include <utility>
Typedefs
using SectionPred = std::function<bool(const SectionBase &Sec)>
Functions
static bool isDebugSection (const SectionBase &Sec)
static bool isDWOSection (const SectionBase &Sec)
static bool onlyKeepDWOPred (const Object &Obj, const SectionBase &Sec)
static Expected< uint64_t > getNewShfFlags (SectionFlag AllFlags, uint16_t EMachine)
static uint64_t getSectionFlagsPreserveMask (uint64_t OldFlags, uint64_t NewFlags, uint16_t EMachine)
static void setSectionType (SectionBase &Sec, uint64_t Type)
static Error setSectionFlagsAndType (SectionBase &Sec, SectionFlag Flags, uint16_t EMachine)
static ElfType getOutputElfType (const Binary &Bin)
static ElfType getOutputElfType (const MachineInfo &MI)
static std::unique_ptr< Writer > createELFWriter (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
static std::unique_ptr< Writer > createWriter (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, StringRef InputFilename, Object &Obj)
static bool isAArch64MappingSymbol (const Symbol &Sym)
static bool isArmMappingSymbol (const Symbol &Sym)
static bool isRequiredByABISymbol (const Object &Obj, const Symbol &Sym)
static bool isUnneededSymbol (const Symbol &Sym)
static Error updateAndRemoveSymbols (const CommonConfig &Config, const ELFConfig &ELFConfig, Object &Obj)
static Error replaceAndRemoveSections (const CommonConfig &Config, const ELFConfig &ELFConfig, Object &Obj)
static void addSymbol (Object &Obj, const NewSymbolInfo &SymInfo, uint8_t DefaultVisibility)
static Error removeNotes (Object &Obj, endianness Endianness, ArrayRef< RemoveNoteInfo > NotesToRemove, function_ref< Error(Error)> ErrorCallback)
static Error handleUserSection (const NewSectionInfo &NewSection, function_ref< Error(StringRef, ArrayRef< uint8_t >)> F)
static Error verifyNoteSection (StringRef Name, endianness Endianness, ArrayRef< uint8_t > Data)
static Error handleArgs (const CommonConfig &Config, const ELFConfig &ELFConfig, ElfType OutputElfType, Object &Obj)
static Error writeOutput (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
Typedef Documentation
SectionPred
using SectionPred = std::function<bool(const SectionBase &Sec)>
Definition at line 47 of file ELFObjcopy.cpp.
Function Documentation
addSymbol()
static void addSymbol (Object & Obj, const NewSymbolInfo & SymInfo, uint8_t DefaultVisibility) static
Definition at line 560 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Addr, llvm::objcopy::elf::SymbolTableSection::addSymbol(), llvm::objcopy::Default, llvm::objcopy::File, llvm::objcopy::elf::Object::findSection(), llvm::objcopy::Function, llvm::objcopy::Global, llvm::objcopy::Hidden, llvm::objcopy::IndirectFunction, llvm::objcopy::Local, llvm::objcopy::Object, llvm::objcopy::Protected, llvm::objcopy::Section, llvm::ELF::SHN_ABS, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_FILE, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_PROTECTED, llvm::objcopy::elf::SYMBOL_SIMPLE_INDEX, llvm::objcopy::elf::Object::SymbolTable, and llvm::objcopy::Weak.
Referenced by llvm::jitlink::SymbolAddressMap::addSymbols(), and handleArgs().
createELFWriter()
static std::unique_ptr< Writer > createELFWriter (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 152 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, llvm_unreachable, llvm::objcopy::CommonConfig::OnlyKeepDebug, and llvm::objcopy::CommonConfig::StripSections.
Referenced by createWriter().
createWriter()
static std::unique_ptr< Writer > createWriter (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 173 of file ELFObjcopy.cpp.
References llvm::objcopy::Binary, createELFWriter(), llvm::objcopy::IHex, llvm::objcopy::CommonConfig::OutputFilename, llvm::objcopy::CommonConfig::OutputFormat, and llvm::objcopy::SREC.
Referenced by writeOutput().
dumpSectionToFile()
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, StringRef InputFilename, Object & Obj) static
Definition at line 188 of file ELFObjcopy.cpp.
References llvm::FileOutputBuffer::create(), llvm::createFileError(), E(), InputFilename, llvm::object::parse_failed, llvm::objcopy::elf::Object::sections(), llvm::ELF::SHT_NOBITS, llvm::StringRef::str(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().
getNewShfFlags()
static Expected< uint64_t > getNewShfFlags (SectionFlag AllFlags, uint16_t EMachine) static
Definition at line 66 of file ELFObjcopy.cpp.
References llvm::createStringError(), llvm::ELF::EM_X86_64, llvm::invalid_argument, llvm::objcopy::SecAlloc, llvm::objcopy::SecCode, llvm::objcopy::SecExclude, llvm::objcopy::SecLarge, llvm::objcopy::SecMerge, llvm::objcopy::SecReadonly, llvm::objcopy::SecStrings, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_WRITE, and llvm::ELF::SHF_X86_64_LARGE.
Referenced by setSectionFlagsAndType().
getOutputElfType() [1/2]
static ElfType getOutputElfType (const Binary & Bin) static
Definition at line 131 of file ELFObjcopy.cpp.
References llvm::Bin, llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, llvm::isa(), and llvm_unreachable.
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().
getOutputElfType() [2/2]
static ElfType getOutputElfType (const MachineInfo & MI) static
Definition at line 144 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, and MI.
getSectionFlagsPreserveMask()
static uint64_t getSectionFlagsPreserveMask (uint64_t OldFlags, uint64_t NewFlags, uint16_t EMachine) static
Definition at line 91 of file ELFObjcopy.cpp.
References llvm::ELF::EM_X86_64, llvm::ELF::SHF_COMPRESSED, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_INFO_LINK, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MASKOS, llvm::ELF::SHF_MASKPROC, llvm::ELF::SHF_TLS, and llvm::ELF::SHF_X86_64_LARGE.
Referenced by setSectionFlagsAndType().
handleArgs()
static Error handleArgs (const CommonConfig & Config, const ELFConfig & ELFConfig, ElfType OutputElfType, Object & Obj) static
Definition at line 784 of file ELFObjcopy.cpp.
References llvm::objcopy::Add, llvm::objcopy::CommonConfig::AddGnuDebugLink, llvm::objcopy::elf::Object::addNewSymbolTable(), llvm::objcopy::CommonConfig::AddSection, llvm::objcopy::elf::Object::addSection(), addSymbol(), llvm::objcopy::CommonConfig::AllocSectionsPrefix, llvm::objcopy::ELFConfig::AllowBrokenLinks, llvm::big, llvm::objcopy::CommonConfig::ChangeSectionAddress, llvm::objcopy::CommonConfig::ChangeSectionLMAValAll, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::createFileError(), llvm::Data, llvm::objcopy::CommonConfig::DumpSection, dumpSectionToFile(), llvm::dyn_cast(), E(), llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64LE, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::objcopy::elf::Object::Entry, llvm::objcopy::ELFConfig::EntryExpr, llvm::objcopy::CommonConfig::ErrorCallback, llvm::ELF::ET_REL, llvm::objcopy::CommonConfig::ExtractDWO, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::CommonConfig::GnuDebugLinkCRC32, handleUserSection(), I, llvm::objcopy::CommonConfig::InputFilename, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::invalid_argument, llvm::object::invalid_file_type, llvm::little, llvm::objcopy::elf::Object::Machine, llvm::make_range(), llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::SectionFlagsUpdate::NewFlags, llvm::objcopy::SectionRename::NewFlags, llvm::objcopy::SectionRename::NewName, llvm::objcopy::ELFConfig::NewSymbolVisibility, llvm::objcopy::ELFConfig::NotesToRemove, llvm::objcopy::CommonConfig::OnlyKeepDebug, llvm::objcopy::elf::Object::OSABI, llvm::objcopy::CommonConfig::OutputArch, removeNotes(), llvm::objcopy::elf::Object::removeSections(), replaceAndRemoveSections(), llvm::objcopy::elf::Object::sections(), llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::elf::Object::segments(), llvm::objcopy::Set, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionFlags, setSectionFlagsAndType(), llvm::objcopy::CommonConfig::SetSectionType, setSectionType(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::objcopy::CommonConfig::SplitDWO, llvm::objcopy::Subtract, llvm::Error::success(), llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::elf::Object::SymbolTable, llvm::StringMap< ValueTy, AllocatorTy >::try_emplace(), llvm::objcopy::elf::Object::Type, llvm::objcopy::elf::SectionBase::Type, updateAndRemoveSymbols(), llvm::objcopy::CommonConfig::UpdateSection, llvm::objcopy::elf::Object::updateSection(), llvm::Twine::utohexstr(), verifyNoteSection(), and llvm::objcopy::ELFConfig::VerifyNoteSections.
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().
handleUserSection()
static Error handleUserSection (const NewSectionInfo & NewSection, function_ref< Error(StringRef, ArrayRef< uint8_t >)> F) static
Definition at line 721 of file ELFObjcopy.cpp.
References llvm::Data, F, llvm::objcopy::NewSectionInfo::SectionData, and llvm::objcopy::NewSectionInfo::SectionName.
Referenced by handleArgs().
isAArch64MappingSymbol()
static bool isAArch64MappingSymbol (const Symbol & Sym) static
Definition at line 259 of file ELFObjcopy.cpp.
References llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, and llvm::ELF::STT_NOTYPE.
Referenced by isRequiredByABISymbol().
isArmMappingSymbol()
static bool isArmMappingSymbol (const Symbol & Sym) static
Definition at line 269 of file ELFObjcopy.cpp.
References llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, and llvm::ELF::STT_NOTYPE.
Referenced by isRequiredByABISymbol().
isDebugSection()
static bool isDebugSection (const SectionBase & Sec) static
Definition at line 49 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Name, and llvm::StringRef::starts_with().
Referenced by replaceAndRemoveSections().
isDWOSection()
static bool isDWOSection (const SectionBase & Sec) static
Definition at line 53 of file ELFObjcopy.cpp.
References llvm::StringRef::ends_with(), and llvm::objcopy::elf::SectionBase::Name.
Referenced by onlyKeepDWOPred(), and replaceAndRemoveSections().
isRequiredByABISymbol()
static bool isRequiredByABISymbol (const Object & Obj, const Symbol & Sym) static
Definition at line 281 of file ELFObjcopy.cpp.
References llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, isAArch64MappingSymbol(), isArmMappingSymbol(), llvm::objcopy::elf::Object::isRelocatable(), and llvm::objcopy::elf::Object::Machine.
Referenced by updateAndRemoveSymbols().
isUnneededSymbol()
static bool isUnneededSymbol (const Symbol & Sym) static
Definition at line 294 of file ELFObjcopy.cpp.
References llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, and llvm::ELF::STT_SECTION.
Referenced by updateAndRemoveSymbols().
onlyKeepDWOPred()
static bool onlyKeepDWOPred (const Object & Obj, const SectionBase & Sec) static
Definition at line 57 of file ELFObjcopy.cpp.
References isDWOSection(), and llvm::objcopy::elf::Object::SectionNames.
Referenced by replaceAndRemoveSections().
removeNotes()
static Error removeNotes (Object & Obj, endianness Endianness, ArrayRef< RemoveNoteInfo > NotesToRemove, function_ref< Error(Error)> ErrorCallback) static
Definition at line 675 of file ELFObjcopy.cpp.
References llvm::createStringError(), E(), llvm::little, llvm::not_supported, llvm::ELF::PT_NOTE, llvm::objcopy::elf::Object::sections(), llvm::objcopy::elf::Object::segments(), llvm::ELF::SHT_NOTE, llvm::Error::success(), and ToRemove.
Referenced by handleArgs().
replaceAndRemoveSections()
static Error replaceAndRemoveSections (const CommonConfig & Config, const ELFConfig & ELFConfig, Object & Obj) static
Definition at line 412 of file ELFObjcopy.cpp.
References llvm::objcopy::ELFConfig::AllowBrokenLinks, llvm::objcopy::elf::Object::compressOrDecompressSections(), E(), llvm::objcopy::elf::SymbolTableSection::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::CommonConfig::ExtractDWO, llvm::objcopy::CommonConfig::ExtractMainPartition, llvm::objcopy::CommonConfig::ExtractPartition, llvm::objcopy::elf::SymbolTableSection::getStrTab(), isDebugSection(), isDWOSection(), llvm::objcopy::ELFConfig::KeepFileSymbols, llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::NameMatcher::matches(), onlyKeepDWOPred(), llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::elf::Object::removeSections(), llvm::objcopy::elf::Object::SectionNames, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_ARM_ATTRIBUTES, llvm::ELF::SHT_LLVM_PART_EHDR, llvm::ELF::SHT_LLVM_PART_PHDR, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_STRTAB, llvm::ELF::SHT_SYMTAB, llvm::StringRef::starts_with(), llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDebug, llvm::objcopy::CommonConfig::StripDWO, llvm::objcopy::CommonConfig::StripNonAlloc, llvm::objcopy::CommonConfig::StripSections, llvm::objcopy::CommonConfig::StripUnneeded, llvm::Error::success(), llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::elf::Object::SymbolTable, and llvm::objcopy::CommonConfig::ToRemove.
Referenced by handleArgs().
setSectionFlagsAndType()
static Error setSectionFlagsAndType (SectionBase & Sec, SectionFlag Flags, uint16_t EMachine) static
Definition at line 113 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Flags, getNewShfFlags(), getSectionFlagsPreserveMask(), llvm::objcopy::SecContents, llvm::objcopy::SecLoad, setSectionType(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::objcopy::elf::SectionBase::Type.
Referenced by handleArgs().
setSectionType()
static void setSectionType (SectionBase & Sec, uint64_t Type) static
Definition at line 105 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Align, llvm::alignTo(), llvm::objcopy::elf::SectionBase::Offset, llvm::ELF::SHT_NOBITS, and llvm::objcopy::elf::SectionBase::Type.
Referenced by handleArgs(), and setSectionFlagsAndType().
updateAndRemoveSymbols()
static Error updateAndRemoveSymbols (const CommonConfig & Config, const ELFConfig & ELFConfig, Object & Obj) static
Definition at line 300 of file ELFObjcopy.cpp.
References llvm::objcopy::All, llvm::objcopy::CommonConfig::DiscardMode, llvm::objcopy::NameMatcher::empty(), llvm::StringRef::empty(), I, llvm::objcopy::elf::Object::isRelocatable(), isRequiredByABISymbol(), isUnneededSymbol(), llvm::objcopy::ELFConfig::KeepFileSymbols, llvm::objcopy::ELFConfig::LocalizeHidden, llvm::objcopy::Locals, llvm::objcopy::NameMatcher::matches(), llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::elf::Object::removeSymbols(), llvm::objcopy::elf::Object::sections(), llvm::ELF::SHN_UNDEF, llvm::StringRef::size(), llvm::StringRef::starts_with(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDebug, llvm::objcopy::CommonConfig::StripUnneeded, llvm::ELF::STT_FILE, llvm::ELF::STT_SECTION, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, llvm::Error::success(), llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsPrefixRemove, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, llvm::objcopy::CommonConfig::SymbolsToRemove, llvm::objcopy::CommonConfig::SymbolsToRename, llvm::objcopy::ELFConfig::SymbolsToSetVisibility, llvm::objcopy::CommonConfig::SymbolsToSkip, llvm::objcopy::CommonConfig::SymbolsToWeaken, llvm::objcopy::elf::Object::SymbolTable, llvm::objcopy::CommonConfig::UnneededSymbolsToRemove, llvm::objcopy::elf::SymbolTableSection::updateSymbols(), and llvm::objcopy::CommonConfig::Weaken.
Referenced by handleArgs().
verifyNoteSection()
static Error verifyNoteSection (StringRef Name, endianness Endianness, ArrayRef< uint8_t > Data) static
Definition at line 729 of file ELFObjcopy.cpp.
References llvm::alignTo(), llvm::createStringError(), llvm::Data, llvm::ArrayRef< T >::data(), llvm::invalid_argument, llvm::XCOFF::NameSize, llvm::support::endian::read32(), and llvm::Error::success().
Referenced by handleArgs().
writeOutput()
static Error writeOutput (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 1038 of file ELFObjcopy.cpp.
References createWriter(), E(), llvm::objcopy::elf::Writer::finalize(), and llvm::objcopy::elf::Writer::write().
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().