LLVM: lib/Target/AMDGPU/GCNRegPressure.cpp File Reference
GCNRegPressure.cpp File Reference
This file implements the GCNRegPressure class.
#include "GCNRegPressure.h"
#include "AMDGPU.h"
#include "llvm/CodeGen/RegisterPressure.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
#define PFX " "
Functions
static LaneBitmask getDefRegMask (const MachineOperand &MO, const MachineRegisterInfo &MRI)
static void collectVirtualRegUses (SmallVectorImpl< VRegMaskOrUnit > &VRegMaskOrUnits, const MachineInstr &MI, const LiveIntervals &LIS, const MachineRegisterInfo &MRI)
static LaneBitmask getLanesWithProperty (const LiveIntervals &LIS, const MachineRegisterInfo &MRI, bool TrackLaneMasks, Register RegUnit, SlotIndex Pos, LaneBitmask SafeDefault, function_ref< bool(const LiveRange &LR, SlotIndex Pos)> Property)
Mostly copy/paste from CodeGen/RegisterPressure.cpp.
static LaneBitmask findUseBetween (unsigned Reg, LaneBitmask LastUseMask, SlotIndex PriorUseIdx, SlotIndex NextUseIdx, const MachineRegisterInfo &MRI, const SIRegisterInfo *TRI, const LiveIntervals *LIS, bool Upward=false)
Mostly copy/paste from CodeGen/RegisterPressure.cpp Helper to find a vreg use between two indices {PriorUseIdx, NextUseIdx}.
static LaneBitmask getRegLiveThroughMask (const MachineRegisterInfo &MRI, const LiveIntervals &LIS, Register Reg, SlotIndex Begin, SlotIndex End, LaneBitmask Mask=LaneBitmask::getAll())
Variables
static cl::opt< bool > UseDownwardTracker ("amdgpu-print-rp-downward", cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass"), cl::init(false), cl::Hidden)
Detailed Description
This file implements the GCNRegPressure class.
Definition in file GCNRegPressure.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 20 of file GCNRegPressure.cpp.
PFX
#define PFX " "
Referenced by llvm::GCNRegPressurePrinter::runOnMachineFunction(), and llvm::AMDGPULibFunc::setPrefix().
Function Documentation
collectVirtualRegUses()
static void collectVirtualRegUses (SmallVectorImpl< VRegMaskOrUnit > & VRegMaskOrUnits, const MachineInstr & MI, const LiveIntervals & LIS, const MachineRegisterInfo & MRI) static
Definition at line 259 of file GCNRegPressure.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find_if(), llvm::SlotIndex::getBaseIndex(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::getLiveLaneMask(), llvm::LaneBitmask::getNone(), I, MI, MRI, P, Reg, and TRI.
Referenced by llvm::GCNUpwardRPTracker::recede().
findUseBetween()
static LaneBitmask findUseBetween (unsigned Reg, LaneBitmask LastUseMask, SlotIndex PriorUseIdx, SlotIndex NextUseIdx, const MachineRegisterInfo & MRI, const SIRegisterInfo * TRI, const LiveIntervals * LIS, bool Upward = false) static
Mostly copy/paste from CodeGen/RegisterPressure.cpp Helper to find a vreg use between two indices {PriorUseIdx, NextUseIdx}.
The query starts with a lane bitmask which gets lanes/bits removed for every use we find.
Definition at line 331 of file GCNRegPressure.cpp.
References llvm::LiveIntervals::getInstructionIndex(), llvm::LaneBitmask::getNone(), llvm::SlotIndex::getRegSlot(), InRange(), MI, MRI, llvm::LaneBitmask::none(), Reg, and TRI.
getDefRegMask()
static LaneBitmask getDefRegMask (const MachineOperand & MO, const MachineRegisterInfo & MRI) static
Definition at line 246 of file GCNRegPressure.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), and MRI.
Referenced by llvm::GCNDownwardRPTracker::advanceToNext(), and llvm::GCNUpwardRPTracker::recede().
getLanesWithProperty()
static LaneBitmask getLanesWithProperty (const LiveIntervals & LIS, const MachineRegisterInfo & MRI, bool TrackLaneMasks, Register RegUnit, SlotIndex Pos, LaneBitmask SafeDefault, function_ref< bool(const LiveRange &LR, SlotIndex Pos)> Property) static
Mostly copy/paste from CodeGen/RegisterPressure.cpp.
Definition at line 300 of file GCNRegPressure.cpp.
References llvm::LaneBitmask::getAll(), llvm::LiveIntervals::getCachedRegUnit(), llvm::LiveIntervals::getInterval(), llvm::LaneBitmask::getNone(), llvm::LiveInterval::hasSubRanges(), llvm::Register::isVirtual(), MRI, and llvm::LiveInterval::subranges().
getRegLiveThroughMask()
static LaneBitmask getRegLiveThroughMask (const MachineRegisterInfo & MRI, const LiveIntervals & LIS, Register Reg, SlotIndex Begin, SlotIndex End, LaneBitmask Mask = LaneBitmask::getAll()) static
Definition at line 767 of file GCNRegPressure.cpp.
References const, getRegLiveThroughMask(), llvm::LiveInterval::hasSubRanges(), MRI, and Reg.
Referenced by getRegLiveThroughMask(), and llvm::GCNRegPressurePrinter::runOnMachineFunction().
Variable Documentation
UseDownwardTracker
cl::opt< bool > UseDownwardTracker("amdgpu-print-rp-downward", cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass"), cl::init(false), cl::Hidden) ("amdgpu-print-rp-downward" , cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::GCNRegPressurePrinter::runOnMachineFunction().