LLVM: lib/Target/AMDGPU/GCNSubtarget.cpp File Reference
GCNSubtarget.cpp File Reference
Implements the GCN specific subclass of TargetSubtarget.
#include "GCNSubtarget.h"
#include "AMDGPUCallLowering.h"
#include "AMDGPUInstructionSelector.h"
#include "AMDGPULegalizerInfo.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPUSelectionDAGInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/CodeGen/GlobalISel/InlineAsmLowering.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/MDBuilder.h"
#include <algorithm>
#include "AMDGPUGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "gcn-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
#define AMDGPUSubtarget GCNSubtarget
Functions
static unsigned getMaxNumPreloadedSGPRs ()
Variables
static cl::opt< bool > EnableVGPRIndexMode ("amdgpu-vgpr-index-mode", cl::desc("Use GPR indexing mode instead of movrel for vector indexing"), cl::init(false))
static cl::opt< bool > UseAA ("amdgpu-use-aa-in-codegen", cl::desc("Enable the use of AA during codegen."), cl::init(true))
static cl::opt< unsigned > NSAThreshold ("amdgpu-nsa-threshold", cl::desc("Number of addresses from which to enable MIMG NSA."), cl::init(2), cl::Hidden)
Detailed Description
Implements the GCN specific subclass of TargetSubtarget.
Definition in file GCNSubtarget.cpp.
Macro Definition Documentation
AMDGPUSubtarget
#define AMDGPUSubtarget GCNSubtarget
Definition at line 37 of file GCNSubtarget.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "gcn-subtarget"
Definition at line 33 of file GCNSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 36 of file GCNSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 35 of file GCNSubtarget.cpp.
Function Documentation
getMaxNumPreloadedSGPRs()
static unsigned getMaxNumPreloadedSGPRs () static
Definition at line 469 of file GCNSubtarget.cpp.
Referenced by llvm::GCNSubtarget::getMaxNumSGPRs().
Variable Documentation
EnableVGPRIndexMode
cl::opt< bool > EnableVGPRIndexMode("amdgpu-vgpr-index-mode", cl::desc("Use GPR indexing mode instead of movrel for vector indexing"), cl::init(false)) ("amdgpu-vgpr-index-mode" , cl::desc("Use GPR indexing mode instead of movrel for vector indexing") , cl::init(false)) static
Referenced by llvm::GCNSubtarget::useVGPRIndexMode().
NSAThreshold
cl::opt< unsigned > NSAThreshold("amdgpu-nsa-threshold", cl::desc("Number of addresses from which to enable MIMG NSA."), cl::init(2), cl::Hidden) ("amdgpu-nsa-threshold" , cl::desc("Number of addresses from which to enable MIMG NSA.") , cl::init(2) , cl::Hidden) static
Referenced by llvm::GCNSubtarget::getNSAThreshold().
UseAA
cl::opt< bool > UseAA("amdgpu-use-aa-in-codegen", cl::desc("Enable the use of AA during codegen."), cl::init(true)) ("amdgpu-use-aa-in-codegen" , cl::desc("Enable the use of AA during codegen.") , cl::init(true)) static