LLVM: lib/IR/Intrinsics.cpp File Reference
Intrinsics.cpp File Reference
#include "llvm/IR/Intrinsics.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringTable.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IntrinsicsBPF.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/IR/IntrinsicsLoongArch.h"
#include "llvm/IR/IntrinsicsMips.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/IR/IntrinsicsR600.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/IR/IntrinsicsVE.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/IntrinsicsXCore.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/IntrinsicImpl.inc"
#include "llvm/IR/ConstrainedOps.def"
Macros
#define GET_INTRINSIC_NAME_TABLE
Table of string intrinsic names indexed by enum value.
#define GET_INTRINSIC_IITINFO
#define GET_INTRINSIC_GENERATOR_GLOBAL
#define GET_INTRINSIC_OVERLOAD_TABLE
#define GET_INTRINSIC_TARGET_DATA
Table of per-target intrinsic name tables.
#define GET_INTRINSIC_ATTRIBUTES
This defines the "Intrinsic::getAttributes(ID id)" method.
#define GET_LLVM_INTRINSIC_FOR_CLANG_BUILTIN
#define GET_LLVM_INTRINSIC_FOR_MS_BUILTIN
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
Typedefs
using DeferredIntrinsicMatchPair
Enumerations
enum IIT_Info
IIT_Info - These are enumerators that describe the entries returned by the getIntrinsicInfoTableEntries function.
Functions
static std::string getMangledTypeStr (Type *Ty, bool &HasUnnamedType)
Returns a stable mangling for the type specified for use in the name mangling scheme used by 'any' types in intrinsic signatures.
static std::string getIntrinsicNameImpl (Intrinsic::ID Id, ArrayRef< Type * > Tys, Module *M, FunctionType *FT, bool EarlyModuleCheck)
static void DecodeIITType (unsigned &NextElt, ArrayRef< unsigned char > Infos, IIT_Info LastInfo, SmallVectorImpl< Intrinsic::IITDescriptor > &OutputTable)
static Type * DecodeFixedType (ArrayRef< Intrinsic::IITDescriptor > &Infos, ArrayRef< Type * > Tys, LLVMContext &Context)
static int lookupLLVMIntrinsicByName (ArrayRef< unsigned > NameOffsetTable, StringRef Name, StringRef Target="")
Looks up Name in NameTable via binary search.
static std::pair< ArrayRef< unsigned >, StringRef > findTargetSubtable (StringRef Name)
Find the segment of IntrinsicNameOffsetTable for intrinsics with the same target as Name, or the generic table if Name is not target specific.
static bool matchIntrinsicType (Type *Ty, ArrayRef< Intrinsic::IITDescriptor > &Infos, SmallVectorImpl< Type * > &ArgTys, SmallVectorImpl< DeferredIntrinsicMatchPair > &DeferredChecks, bool IsDeferredCheck)
Macro Definition Documentation
GET_INTRINSIC_ATTRIBUTES
#define GET_INTRINSIC_ATTRIBUTES
This defines the "Intrinsic::getAttributes(ID id)" method.
Definition at line 728 of file Intrinsics.cpp.
GET_INTRINSIC_GENERATOR_GLOBAL
#define GET_INTRINSIC_GENERATOR_GLOBAL
Definition at line 443 of file Intrinsics.cpp.
GET_INTRINSIC_IITINFO
#define GET_INTRINSIC_IITINFO
Definition at line 194 of file Intrinsics.cpp.
GET_INTRINSIC_NAME_TABLE
#define GET_INTRINSIC_NAME_TABLE
Table of string intrinsic names indexed by enum value.
Definition at line 38 of file Intrinsics.cpp.
GET_INTRINSIC_OVERLOAD_TABLE
#define GET_INTRINSIC_OVERLOAD_TABLE
GET_INTRINSIC_TARGET_DATA
#define GET_INTRINSIC_TARGET_DATA
Table of per-target intrinsic name tables.
Definition at line 614 of file Intrinsics.cpp.
GET_LLVM_INTRINSIC_FOR_CLANG_BUILTIN
#define GET_LLVM_INTRINSIC_FOR_CLANG_BUILTIN
Definition at line 754 of file Intrinsics.cpp.
GET_LLVM_INTRINSIC_FOR_MS_BUILTIN
#define GET_LLVM_INTRINSIC_FOR_MS_BUILTIN
Definition at line 759 of file Intrinsics.cpp.
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                                   \
    return ROUND_MODE == 1;
Typedef Documentation
DeferredIntrinsicMatchPair
using DeferredIntrinsicMatchPair
Initial value:
    std::pair<Type *, ArrayRef<Intrinsic::IITDescriptor>>
Definition at line 787 of file Intrinsics.cpp.
Enumeration Type Documentation
IIT_Info
enum IIT_Info
IIT_Info - These are enumerators that describe the entries returned by the getIntrinsicInfoTableEntries function.
Defined in Intrinsics.td.
Definition at line 193 of file Intrinsics.cpp.
Function Documentation
DecodeFixedType()
static Type * DecodeFixedType (ArrayRef< Intrinsic::IITDescriptor > & Infos, ArrayRef< Type * > Tys, LLVMContext & Context) static
Definition at line 482 of file Intrinsics.cpp.
References assert(), llvm::cast(), D(), DecodeFixedType(), llvm::dyn_cast(), llvm::ArrayRef< T >::front(), llvm::FixedVectorType::get(), llvm::IntegerType::get(), llvm::PointerType::get(), llvm::StructType::get(), llvm::TargetExtType::get(), llvm::VectorType::get(), llvm::Type::getBFloatTy(), getBitWidth(), llvm::IntegerType::getBitWidth(), llvm::Type::getDoubleTy(), llvm::VectorType::getExtendedElementVectorType(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::VectorType::getHalfElementsVectorType(), llvm::Type::getHalfTy(), llvm::VectorType::getInteger(), llvm::Type::getMetadataTy(), llvm::Type::getPPC_FP128Ty(), llvm::VectorType::getSubdividedVectorType(), llvm::Type::getTokenTy(), llvm::VectorType::getTruncatedElementVectorType(), llvm::Type::getVoidTy(), llvm::Type::getX86_AMXTy(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::slice().
Referenced by DecodeFixedType(), and llvm::Intrinsic::getType().
DecodeIITType()
static void DecodeIITType (unsigned & NextElt, ArrayRef< unsigned char > Infos, IIT_Info LastInfo, SmallVectorImpl< Intrinsic::IITDescriptor > & OutputTable) static
Definition at line 200 of file Intrinsics.cpp.
References DecodeIITType(), Info, llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::size().
Referenced by DecodeIITType(), and llvm::Intrinsic::getIntrinsicInfoTableEntries().
findTargetSubtable()
static std::pair< ArrayRef< unsigned >, StringRef > findTargetSubtable (StringRef Name) static
Find the segment of IntrinsicNameOffsetTable for intrinsics with the same target as Name, or the generic table if Name is not target specific.
Returns the relevant slice of IntrinsicNameOffsetTable and the target name.
Definition at line 689 of file Intrinsics.cpp.
References llvm::ArrayRef(), assert(), llvm::ArrayRef< T >::end(), and llvm::partition_point().
Referenced by llvm::Intrinsic::lookupIntrinsicID().
getIntrinsicNameImpl()
static std::string getIntrinsicNameImpl (Intrinsic::ID Id, ArrayRef< Type * > Tys, Module * M, FunctionType * FT, bool EarlyModuleCheck) static
Definition at line 152 of file Intrinsics.cpp.
References llvm::any_of(), assert(), llvm::Intrinsic::getBaseName(), getMangledTypeStr(), llvm::Intrinsic::getType(), llvm::isa(), llvm::Intrinsic::isOverloaded(), and T.
Referenced by llvm::Intrinsic::getName(), and llvm::Intrinsic::getNameNoUnnamedTypes().
getMangledTypeStr()
static std::string getMangledTypeStr (Type * Ty, bool & HasUnnamedType) static
Returns a stable mangling for the type specified for use in the name mangling scheme used by 'any' types in intrinsic signatures.
The mangling of named types is simply their name. Manglings for unnamed types consist of a prefix ('p' for pointers, 'a' for arrays, 'f_' for functions) combined with the mangling of their component types. A vararg function type will have a suffix of 'vararg'. Since function types can contain other function types, we close a function type mangling with suffix 'f' which can't be confused with it's prefix. This ensures we don't have collisions between two unrelated function types. Otherwise, you might parse ffXX as f(fXX) or f(fX)X. (X is a placeholder for any other type.) The HasUnnamedType boolean is set if an unnamed type was encountered, indicating that extra care must be taken to ensure a unique name.
Definition at line 66 of file Intrinsics.cpp.
References llvm::Type::BFloatTyID, llvm::cast(), llvm::Type::DoubleTyID, llvm::dyn_cast(), llvm::Type::FloatTyID, llvm::Type::FP128TyID, getBitWidth(), getMangledTypeStr(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm_unreachable, llvm::Type::MetadataTyID, llvm::Type::PPC_FP128TyID, llvm::utostr(), llvm::Type::VoidTyID, llvm::Type::X86_AMXTyID, and llvm::Type::X86_FP80TyID.
Referenced by getIntrinsicNameImpl(), and getMangledTypeStr().
lookupLLVMIntrinsicByName()
static int lookupLLVMIntrinsicByName (ArrayRef< unsigned > NameOffsetTable, StringRef Name, StringRef Target = "") static
Looks up Name in NameTable via binary search.
NameTable must be sorted and all entries must start with "llvm.". If NameTable contains an exact match for Name or a prefix of Name followed by a dot, its index in NameTable is returned. Otherwise, -1 is returned.
Definition at line 626 of file Intrinsics.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::StringRef::data(), llvm::ArrayRef< T >::end(), High, LHS, llvm::Low, llvm::StringRef::npos, RHS, and llvm::StringRef::size().
Referenced by llvm::Intrinsic::lookupIntrinsicID().
matchIntrinsicType()
static bool matchIntrinsicType (Type * Ty, ArrayRef< Intrinsic::IITDescriptor > & Infos, SmallVectorImpl< Type * > & ArgTys, SmallVectorImpl< DeferredIntrinsicMatchPair > & DeferredChecks, bool IsDeferredCheck) static
Definition at line 791 of file Intrinsics.cpp.
References assert(), llvm::cast(), D(), llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::IntegerType::get(), llvm::VectorType::getElementType(), llvm::VectorType::getExtendedElementVectorType(), llvm::VectorType::getHalfElementsVectorType(), llvm::VectorType::getInteger(), llvm::FixedVectorType::getNumElements(), llvm::VectorType::getSubdividedVectorType(), llvm::VectorType::getTruncatedElementVectorType(), llvm::isa(), llvm::Type::isIntegerTy(), llvm_unreachable, matchIntrinsicType(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ArrayRef< T >::slice(), T, and true.
Referenced by llvm::Intrinsic::matchIntrinsicSignature(), and matchIntrinsicType().