LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderVTune.h File Reference
JITLoaderVTune.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include "llvm/Support/Compiler.h"
#include <cstdint>
Functions
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerVTuneImpl (const char *Data, uint64_t Size)
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_unregisterVTuneImpl (const char *Data, uint64_t Size)
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_test_registerVTuneImpl (const char *Data, uint64_t Size)
Function Documentation
llvm_orc_registerVTuneImpl()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerVTuneImpl (const char * Data, uint64_t Size)
Definition at line 201 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsupportedBatch().
llvm_orc_test_registerVTuneImpl()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_test_registerVTuneImpl (const char * Data, uint64_t Size)
Definition at line 217 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsupportedBatch().
llvm_orc_unregisterVTuneImpl()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_unregisterVTuneImpl (const char * Data, uint64_t Size)
Definition at line 209 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsuppported().