LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.h File Reference
JITLoaderPerf.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include "llvm/Support/Compiler.h"
#include <cstdint>
Functions
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char *Data, uint64_t Size)
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char *Data, uint64_t Size)
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char *Data, uint64_t Size)
Function Documentation
llvm_orc_registerJITLoaderPerfEnd()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char * Data, uint64_t Size)
Definition at line 451 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfImpl()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char * Data, uint64_t Size)
Definition at line 437 of file JITLoaderPerf.cpp.
References badOSBatch(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfStart()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char * Data, uint64_t Size)
Definition at line 445 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.