LLVM: lib/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.cpp File Reference
JITLoaderGDB.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/FormatVariadic.h"
#include <cstdint>
#include <mutex>
Macros
#define DEBUG_TYPE "orc"
Functions
LLVM_ALWAYS_EXPORT LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
static void appendJITDebugDescriptor (const char *ObjAddr, size_t Size)
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char *Data, size_t Size)
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char *Data, uint64_t Size)
Variables
static constexpr uint32_t JitDescriptorVersion = 1
LLVM_ALWAYS_EXPORT struct jit_descriptor __jit_debug_descriptor
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 17 of file JITLoaderGDB.cpp.
Function Documentation
__jit_debug_register_code()
LLVM_ALWAYS_EXPORT LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
Definition at line 34 of file JITLoaderGDB.cpp.
References LLVM_ATTRIBUTE_NOINLINE.
Referenced by llvm_orc_registerJITLoaderGDBAllocAction(), and llvm_orc_registerJITLoaderGDBWrapper().
appendJITDebugDescriptor()
static void appendJITDebugDescriptor (const char * ObjAddr, size_t Size) static
Definition at line 47 of file JITLoaderGDB.cpp.
References __jit_debug_descriptor, llvm::dbgs(), E(), llvm::formatv(), JIT_REGISTER_FN, LLVM_DEBUG, jit_code_entry::prev_entry, and Size.
Referenced by llvm_orc_registerJITLoaderGDBAllocAction(), and llvm_orc_registerJITLoaderGDBWrapper().
llvm_orc_registerJITLoaderGDBAllocAction()
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char * Data, size_t Size)
Definition at line 78 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::Data, llvm::release, Size, and llvm::Error::success().
llvm_orc_registerJITLoaderGDBWrapper()
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char * Data, uint64_t Size)
Definition at line 94 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::Data, llvm::release, Size, and llvm::Error::success().
Variable Documentation
__jit_debug_descriptor
LLVM_ALWAYS_EXPORT struct jit_descriptor __jit_debug_descriptor
Initial value:
= {JitDescriptorVersion, 0,
                                                nullptr, nullptr}
Definition at line 28 of file JITLoaderGDB.cpp.
Referenced by appendJITDebugDescriptor().
JitDescriptorVersion
uint32_t JitDescriptorVersion = 1 static constexpr
Definition at line 20 of file JITLoaderGDB.cpp.