LLVM: lib/IR/LLVMContext.cpp File Reference
LLVMContext.cpp File Reference
#include "llvm/IR/LLVMContext.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/Remarks/RemarkStreamer.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdlib>
#include <string>
#include <utility>
#include "llvm/IR/FixedMetadataKinds.def"
Macros
#define LLVM_FIXED_MD_KIND(EnumID, Name, Value)
Functions
static StringRef knownBundleName (unsigned BundleTagID)
static bool isDiagnosticEnabled (const DiagnosticInfo &DI)
Macro Definition Documentation
LLVM_FIXED_MD_KIND
#define LLVM_FIXED_MD_KIND (EnumID, Name, Value)
Value:
{EnumID, Name},
Function Documentation
isDiagnosticEnabled()
static bool isDiagnosticEnabled (const DiagnosticInfo & DI) static
Definition at line 215 of file LLVMContext.cpp.
References llvm::dyn_cast(), and llvm::Remark.
Referenced by llvm::LLVMContext::diagnose().
knownBundleName()
static StringRef knownBundleName (unsigned BundleTagID) static
Definition at line 34 of file LLVMContext.cpp.
References llvm_unreachable, llvm::LLVMContext::OB_cfguardtarget, llvm::LLVMContext::OB_clang_arc_attachedcall, llvm::LLVMContext::OB_convergencectrl, llvm::LLVMContext::OB_deopt, llvm::LLVMContext::OB_funclet, llvm::LLVMContext::OB_gc_live, llvm::LLVMContext::OB_gc_transition, llvm::LLVMContext::OB_kcfi, llvm::LLVMContext::OB_preallocated, and llvm::LLVMContext::OB_ptrauth.
Referenced by llvm::LLVMContext::LLVMContext().