LLVM: lib/Transforms/Scalar/LoopTermFold.cpp File Reference
LoopTermFold.cpp File Reference
#include "llvm/Transforms/Scalar/LoopTermFold.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
#include <cassert>
#include <optional>
Macros
#define DEBUG_TYPE "loop-term-fold"
Functions
STATISTIC (NumTermFold, "Number of terminating condition fold recognized and performed")
static std::optional< std::tuple< PHINode *, PHINode *, const SCEV *, bool > > canFoldTermCondOfLoop (Loop *L, ScalarEvolution &SE, DominatorTree &DT, const LoopInfo &LI, const TargetTransformInfo &TTI)
static bool RunTermFold (Loop *L, ScalarEvolution &SE, DominatorTree &DT, LoopInfo &LI, const TargetTransformInfo &TTI, TargetLibraryInfo &TLI, MemorySSA *MSSA)
INITIALIZE_PASS_BEGIN (LoopTermFold, "loop-term-fold", "Loop Terminator Folding", false, false) INITIALIZE_PASS_END(LoopTermFold
Variables
loop term fold
loop term Loop Terminator Folding
loop term Loop Terminator false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-term-fold"
Definition at line 46 of file LoopTermFold.cpp.
Function Documentation
canFoldTermCondOfLoop()
static std::optional< std::tuple< PHINode *, PHINode *, const SCEV *, bool > > canFoldTermCondOfLoop (Loop * L, ScalarEvolution & SE, DominatorTree & DT, const LoopInfo & LI, const TargetTransformInfo & TTI) static
Definition at line 52 of file LoopTermFold.cpp.
References llvm::cast(), llvm::dbgs(), DL, llvm::dyn_cast(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::BranchInst::getCondition(), llvm::getLoopEstimatedTripCount(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::SCEVAddRecExpr::getPostIncExpr(), llvm::ScalarEvolution::getSCEV(), llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::BasicBlock::getTerminator(), llvm::ScalarEvolution::hasLoopInvariantBackedgeTakenCount(), llvm::SCEVNAryExpr::hasNoSelfWrap(), llvm::Instruction::hasPoisonGeneratingFlags(), llvm::SCEVAddRecExpr::isAffine(), llvm::isAlmostDeadIV(), llvm::SCEVExpander::isHighCostExpansion(), llvm::ScalarEvolution::isKnownNonZero(), llvm::SCEVExpander::isSafeToExpand(), llvm::ScalarEvolution::isSCEVable(), llvm::BranchInst::isUnconditional(), LHS, LLVM_DEBUG, llvm::matchSimpleRecurrence(), llvm::mustExecuteUBIfPoisonOnPathTo(), PostInc, RHS, and llvm::SCEVCheapExpansionBudget.
Referenced by RunTermFold().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopTermFold , "loop-term-fold" , "Loop Terminator Folding" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
RunTermFold()
static bool RunTermFold (Loop * L, ScalarEvolution & SE, DominatorTree & DT, LoopInfo & LI, const TargetTransformInfo & TTI, TargetLibraryInfo & TLI, MemorySSA * MSSA) static
Definition at line 230 of file LoopTermFold.cpp.
References assert(), canFoldTermCondOfLoop(), llvm::cast(), llvm::SCEVExpander::clear(), llvm::IRBuilderBase::CreateICmp(), llvm::dbgs(), llvm::DeleteDeadPHIs(), DL, llvm::Instruction::eraseFromParent(), llvm::SCEVExpander::expandCodeFor(), llvm::BranchInst::getCondition(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::CmpInst::ICMP_EQ, llvm::SCEVExpander::isSafeToExpand(), LLVM_DEBUG, llvm::BranchInst::setCondition(), and llvm::BranchInst::swapSuccessors().
Referenced by llvm::LoopTermFoldPass::run().
STATISTIC()
STATISTIC (NumTermFold , "Number of terminating condition fold recognized and performed")
Variable Documentation
false
loop term Loop Terminator false
Definition at line 375 of file LoopTermFold.cpp.
fold
loop term fold
Definition at line 374 of file LoopTermFold.cpp.
Folding
loop term Loop Terminator Folding
Definition at line 374 of file LoopTermFold.cpp.