LLVM: lib/CodeGen/MachineModuleInfo.cpp File Reference
MachineModuleInfo.cpp File Reference
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
Functions
static INITIALIZE_PASS(MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass uint64_t getLocCookie (const SMDiagnostic &SMD, const SourceMgr &SrcMgr, std::vector< const MDNode * > &LocInfos)
Function Documentation
getLocCookie()
static INITIALIZE_PASS(MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass uint64_t getLocCookie (const SMDiagnostic & SMD, const SourceMgr & SrcMgr, std::vector< const MDNode * > & LocInfos) static
Definition at line 170 of file MachineModuleInfo.cpp.
References const, llvm::mdconst::dyn_extract(), getLocCookie(), if(), llvm::SrcMgr, and vector.
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization(), getLocCookie(), and llvm::MachineModuleAnalysis::run().