LLVM: llvm::VPlanPatternMatch::detail Namespace Reference
llvm::VPlanPatternMatch::detail Namespace Reference
Classes
struct MatchRecipeAndOpcode
A helper to match an opcode against multiple recipe types.
struct MatchRecipeAndOpcode< Opcode, RecipeTy >
struct MatchRecipeAndOpcode< Opcode, RecipeTy, RecipeTys... >
Functions
template<typename TupleTy, typename Fn, std::size_t... Is>
bool CheckTupleElements (const TupleTy &Ops, Fn P, std::index_sequence< Is... >)
template<typename TupleTy, typename Fn>
bool all_of_tuple_elements (const TupleTy &Ops, Fn P)
Helper to check if predicate P holds on all tuple elements in Ops.
Function Documentation
all_of_tuple_elements()
template<typename TupleTy, typename Fn> bool llvm::VPlanPatternMatch::detail::all_of_tuple_elements (const TupleTy & Ops, Fn P)
Helper to check if predicate P holds on all tuple elements in Ops.
Definition at line 164 of file VPlanPatternMatch.h.
References AbstractManglingParser< Derived, Alloc >::Ops, CheckTupleElements(), and P.
Referenced by llvm::VPlanPatternMatch::Recipe_match< std::tuple< Op0_t >, Opcode, false, RecipeTys... >< Op0_t, Opcode, VPInstruction >::match().
CheckTupleElements()
template<typename TupleTy, typename Fn, std::size_t... Is> bool llvm::VPlanPatternMatch::detail::CheckTupleElements (const TupleTy & Ops, Fn P, std::index_sequence< Is... >)
Definition at line 158 of file VPlanPatternMatch.h.
References AbstractManglingParser< Derived, Alloc >::Ops, and P.
Referenced by all_of_tuple_elements().