LLVM: llvm::sandboxir Namespace Reference
llvm::sandboxir Namespace Reference
Classes
class AddrSpaceCastInst
class AllocaInst
class Analyses
class Argument
Argument of a sandboxir::Function.
class ArrayType
class AtomicCmpXchgInst
class AtomicRMWInst
class BinaryOperator
class BitCastInst
class BlockAddress
class BottomUpVec
class BranchInst
class CallBase
class CallBrInst
class CallInst
class CastInst
class CastInstImpl
class CatchPadInst
class CatchReturnInst
class CatchSwitchAddHandler
class CatchSwitchInst
class CleanupPadInst
class CleanupReturnInst
class CmpInst
class CmpSwapOperands
class CollectDescr
Describes how to collect the values needed by each lane.
class Constant
class ConstantAggregate
Base class for aggregate constants (with operands).
class ConstantAggregateZero
class ConstantArray
class ConstantExpr
class ConstantFP
class ConstantInt
class ConstantPointerNull
class ConstantPtrAuth
class ConstantStruct
class ConstantTokenNone
class ConstantVector
class Context
class CreateAndInsertInst
class DependencyGraph
class DGNode
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
class DiamondReuse
class DiamondReuseMultiInput
class DiamondReuseWithShuffle
class DSOLocalEquivalent
class EraseFromParent
class ExtractElementInst
class ExtractValueInst
class FCmpInst
class FenceInst
class FixedVectorType
class FPExtInst
class FPMathOperator
class FPToSIInst
class FPToUIInst
class FPTruncInst
class FreezeInst
class FuncletPadInst
class Function
class FunctionPass
A pass that runs on a sandbox::Function.
class FunctionPassManager
class FunctionType
class GenericSetter
This class can be used for tracking most instruction setters.
class GenericSetterWithIdx
Similar to GenericSetter but the setters/getters have an index as their first argument.
class GetElementPtrInst
class GlobalAlias
class GlobalIFunc
class GlobalObject
class GlobalValue
class GlobalVariable
class GlobalWithNodeAPI
Provides API functions, like getIterator() and getReverseIterator() to GlobalIFunc, Function, GlobalVariable and GlobalAlias.
class ICmpInst
class InsertElementInst
class InsertIntoBB
class InsertPosition
class InsertValueInst
class InstrMaps
Maps the original instructions to the vectorized instrs and the reverse.
class Instruction
A sandboxir::User with operands, opcode and linked with previous/next instructions in an instruction list.
class IntegerType
Class to represent integer types.
class Interval
class IntervalIterator
A simple iterator for iterating the interval.
class IntrinsicInst
class IntToPtrInst
class InvokeInst
class IRChangeBase
The base class for IR Change classes.
class IRSnapshotChecker
A class that saves hashes and textual IR snapshots of functions in a SandboxIR Context, and does hash comparison when expectNoDiff is called.
class LandingPadInst
class LegalityAnalysis
Performs the legality analysis and returns a LegalityResult object.
class LegalityResult
The legality outcome is represented by a class rather than an enum class because in some cases the legality checks are expensive and look for a particular instruction that can be passed along to the vectorizer to avoid repeating the same expensive computation.
class LegalityResultWithReason
Base class for results with reason.
class LoadInst
class MemDGNode
A DependencyGraph Node for instructions that may read/write memory, or have some ordering constraints, like with stacksave/stackrestore and alloca/inalloca.
class MemDGNodeIntervalBuilder
Convenience builders for a MemDGNode interval.
class MemSeedBundle
Specialization of SeedBundle for memory access instructions.
class Module
In SandboxIR the Module is mainly used to access the list of global objects.
class MoveInstr
class NoCFIValue
class NullPass
A Region pass that does nothing, for use as a placeholder in tests.
class OpaqueInst
An LLLVM Instruction that has no SandboxIR equivalent class gets mapped to an OpaqueInstr.
class OperandUseIterator
Iterator for the Use edges of a User's operands.
class Operator
class OverflowingBinaryOperator
class Pack
class Pass
The base class of a Sandbox IR Pass.
class PassManager
Base class.
class PHIAddIncoming
class PHINode
class PHIRemoveIncoming
class PointerType
class PoisonValue
class PossiblyDisjointInst
An or instruction, which can be marked as "disjoint", indicating that the inputs don't have a 1 in the same bit position.
class PossiblyNonNegInst
Instruction that can have a nneg flag (zext/uitofp).
class PredIterator
Iterate over both def-use and mem dependencies.
class PrintInstructionCount
A Region pass that prints the instruction count for the region to stdout.
class PriorityCmp
class PtrToIntInst
class ReadyListContainer
The list holding nodes that are ready to schedule. Used by the scheduler.
class Region
The main job of the Region is to point to new instructions generated by vectorization passes.
class RegionPass
A pass that runs on a sandbox::Region.
class RegionPassManager
class RegionsFromMetadata
class RemoveFromParent
class ResumeInst
class ReturnInst
class SandboxVectorizerPassBuilder
class ScalableVectorType
class SchedBundle
The nodes that need to be scheduled back-to-back in a single scheduling cycle form a SchedBundle.
class Scheduler
The list scheduler.
class ScoreBoard
class SeedBundle
A set of candidate Instructions for vectorizing together.
class SeedCollector
class SeedContainer
Class to conveniently track Seeds within SeedBundles.
class SelectInst
class SExtInst
class ShuffleMask
class ShuffleVectorInst
class ShuffleVectorSetMask
class SingleLLVMInstructionImpl
Instructions that contain a single LLVM Instruction can inherit from this.
class SIToFPInst
class StoreInst
class StructType
class SwitchAddCase
class SwitchInst
class SwitchRemoveCase
struct ToStr
class Tracker
The tracker collects all the change objects and implements the main API for saving / reverting / accepting.
class TruncInst
class Type
Just like llvm::Type these are immutable, unique, never get freed and can only be created via static factory methods.
class UIToFPInst
class UnaryInstruction
An abstract class, parent of unary instructions.
class UnaryOperator
class UndefValue
class UnreachableInst
class Use
Represents a Def-use/Use-def edge in SandboxIR.
class User
A sandboxir::User has operands.
class UserUseIterator
Iterator for the Use edges of a Value's users.
class UseSet
Tracks the change of the source Value of a sandboxir::Use.
class UseSwap
Tracks swapping a Use with another Use.
class Utils
class VAArgInst
class Value
A SandboxIR Value has users. This is the base class.
class VectorType
class VecUtils
class Widen
class ZExtInst
Typedefs
using iterator = BBIterator
using StoreSeedBundle = MemSeedBundle<sandboxir::StoreInst>
using LoadSeedBundle = MemSeedBundle<sandboxir::LoadInst>
Enumerations
enum class DGNodeID { DGNode , MemDGNode }
SubclassIDs for isa/dyn_cast etc.
enum class LegalityResultID {
Pack , Widen , DiamondReuse , DiamondReuseWithShuffle ,
DiamondReuseMultiInput
}
enum class ResultReason {
NotInstructions , DiffOpcodes , DiffTypes , DiffMathFlags ,
DiffWrapFlags , DiffBBs , NotConsecutive , CantSchedule ,
Unimplemented , Infeasible
}
The reason for vectorizing or not vectorizing.
Functions
BasicBlock (llvm::BasicBlock *BB, Context &SBCtx)
~BasicBlock ()=default
static bool classof (const Value *From)
For isa/dyn_cast.
Function * getParent () const
iterator begin () const
iterator end () const
std::reverse_iterator< iterator > rbegin () const
std::reverse_iterator< iterator > rend () const
Context & getContext () const
Instruction * getTerminator () const
bool empty () const
Instruction & front () const
Instruction & back () const
void verify () const final
void dumpOS (raw_ostream &OS) const final
static User::op_iterator skipNonInstr (User::op_iterator OpIt, User::op_iterator OpItE)
While OpIt points to a Value that is not an Instruction keep incrementing it.
static llvm::Instruction::CastOps getLLVMCastOp (Instruction::Opcode Opc)
static llvm::Instruction::UnaryOps getLLVMUnaryOp (Instruction::Opcode Opc)
\Returns the LLVM opcode that corresponds to Opc.
static llvm::Instruction::BinaryOps getLLVMBinaryOp (Instruction::Opcode Opc)
\Returns the LLVM opcode that corresponds to Opc.
static bool isOrdered (Instruction *I)
static void dumpBndl (ArrayRef< Value * > Bndl)
static SmallVector< Value *, 4 > getOperand (ArrayRef< Value * > Bndl, unsigned OpIdx)
static BasicBlock::iterator getInsertPointAfterInstrs (ArrayRef< Value * > Vals, BasicBlock *BB)
\Returns the BB iterator after the lowest instruction in Vals, or the top of BB if no instruction found in Vals.
template<typename LoadOrStoreT>
static bool isValidMemSeed (LoadOrStoreT *LSI)
template bool isValidMemSeed< LoadInst > (LoadInst *LSI)
template bool isValidMemSeed< StoreInst > (StoreInst *LSI)
template<typename T>
static void dumpImpl (ArrayRef< T * > Bndl)
Variables
static constexpr int MaxRegisteredCallbacks = 16
cl::opt< unsigned > SeedBundleSizeLimit ("sbvec-seed-bundle-size-limit", cl::init(32), cl::Hidden, cl::desc("Limit the size of the seed bundle to cap compilation time."))
cl::opt< std::string > CollectSeeds ("sbvec-collect-seeds", cl::init(LoadSeedsDef "," StoreSeedsDef), cl::Hidden, cl::desc("Collect these seeds. Use empty for none or a comma-separated " "list of '" LoadSeedsDef "' and '" StoreSeedsDef "'."))
cl::opt< unsigned > SeedGroupsLimit ("sbvec-seed-groups-limit", cl::init(256), cl::Hidden, cl::desc("Limit the number of collected seeds groups in a BB to " "cap compilation time."))
Typedef Documentation
iterator
using llvm::sandboxir::iterator = BBIterator
Definition at line 86 of file BasicBlock.h.
LoadSeedBundle
using llvm::sandboxir::LoadSeedBundle = MemSeedBundle<sandboxir::LoadInst>
Definition at line 168 of file SeedCollector.h.
StoreSeedBundle
using llvm::sandboxir::StoreSeedBundle = MemSeedBundle<sandboxir::StoreInst>
Definition at line 167 of file SeedCollector.h.
Enumeration Type Documentation
DGNodeID
enum class llvm::sandboxir::DGNodeID strong
SubclassIDs for isa/dyn_cast etc.
Enumerator
DGNode
MemDGNode
Definition at line 39 of file DependencyGraph.h.
LegalityResultID
enum class llvm::sandboxir::LegalityResultID strong
Enumerator
Pack
Widen
Collect scalar values.
DiamondReuse
Vectorize by combining scalars to a vector.
DiamondReuseWithShuffle
Don't generate new code, reuse existing vector.
DiamondReuseMultiInput
Reuse the existing vector but add a shuffle.
Definition at line 79 of file Legality.h.
ResultReason
enum class llvm::sandboxir::ResultReason strong
The reason for vectorizing or not vectorizing.
Enumerator
NotInstructions
DiffOpcodes
DiffTypes
DiffMathFlags
DiffWrapFlags
DiffBBs
NotConsecutive
CantSchedule
Unimplemented
Infeasible
Definition at line 88 of file Legality.h.
Function Documentation
back()
Instruction & llvm::sandboxir::back () const
BasicBlock()
llvm::sandboxir::BasicBlock (llvm::BasicBlock * BB, Context & SBCtx)
Definition at line 74 of file BasicBlock.h.
References llvm::Block.
Referenced by llvm::sandboxir::SwitchInst::addCase(), llvm::sandboxir::CatchSwitchInst::addHandler(), llvm::sandboxir::PHINode::addIncoming(), llvm::sandboxir::BlockAddress::Context, llvm::sandboxir::CallBrInst::Context, llvm::sandboxir::CatchReturnInst::Context, llvm::sandboxir::CatchSwitchInst::Context, llvm::sandboxir::CleanupReturnInst::Context, llvm::sandboxir::InvokeInst::Context, llvm::sandboxir::BranchInst::create(), llvm::sandboxir::BranchInst::create(), llvm::sandboxir::CatchReturnInst::create(), llvm::sandboxir::CatchSwitchInst::create(), llvm::sandboxir::InvokeInst::create(), llvm::sandboxir::SwitchInst::create(), llvm::sandboxir::Region::createRegionsFromMD(), llvm::sandboxir::SwitchInst::findCaseDest(), llvm::sandboxir::BlockAddress::get(), llvm::sandboxir::BlockAddress::get(), llvm::sandboxir::BlockAddress::getBasicBlock(), llvm::sandboxir::InsertPosition::getBasicBlock(), llvm::sandboxir::PHINode::getBasicBlockIndex(), llvm::sandboxir::CallBrInst::getDefaultDest(), llvm::sandboxir::SwitchInst::getDefaultDest(), llvm::sandboxir::PHINode::getIncomingBlock(), llvm::sandboxir::PHINode::getIncomingBlock(), llvm::sandboxir::PHINode::getIncomingValueForBlock(), llvm::sandboxir::CallBrInst::getIndirectDest(), getInsertPointAfterInstrs(), llvm::sandboxir::VecUtils::getLowest(), llvm::sandboxir::InvokeInst::getNormalDest(), llvm::sandboxir::Instruction::getParent(), llvm::sandboxir::BranchInst::getSuccessor(), llvm::sandboxir::CallBrInst::getSuccessor(), llvm::sandboxir::CatchReturnInst::getSuccessor(), llvm::sandboxir::CatchSwitchInst::getSuccessor(), llvm::sandboxir::InvokeInst::getSuccessor(), llvm::sandboxir::SwitchInst::getSuccessor(), llvm::sandboxir::CatchSwitchInst::getUnwindDest(), llvm::sandboxir::CleanupReturnInst::getUnwindDest(), llvm::sandboxir::InvokeInst::getUnwindDest(), llvm::sandboxir::Instruction::insertInto(), llvm::sandboxir::InsertPosition::InsertPosition(), llvm::sandboxir::BlockAddress::lookup(), llvm::sandboxir::Instruction::moveBefore(), llvm::sandboxir::PHINode::removeIncomingValue(), llvm::sandboxir::PHINode::replaceIncomingBlockWith(), llvm::sandboxir::SeedCollector::SeedCollector(), llvm::sandboxir::CallBrInst::setDefaultDest(), llvm::sandboxir::SwitchInst::setDefaultDest(), llvm::sandboxir::PHINode::setIncomingBlock(), llvm::sandboxir::InvokeInst::setNormalDest(), llvm::sandboxir::BranchInst::setSuccessor(), llvm::sandboxir::CatchReturnInst::setSuccessor(), llvm::sandboxir::CatchSwitchInst::setSuccessor(), llvm::sandboxir::InvokeInst::setSuccessor(), llvm::sandboxir::SwitchInst::setSuccessor(), llvm::sandboxir::CatchSwitchInst::setUnwindDest(), llvm::sandboxir::CleanupReturnInst::setUnwindDest(), and llvm::sandboxir::InvokeInst::setUnwindDest().
begin()
iterator llvm::sandboxir::begin () const
Referenced by empty(), llvm::sandboxir::Instruction::getPrevNode(), and rend().
classof()
static bool llvm::sandboxir::classof (const Value * From) static
For isa/dyn_cast.
Definition at line 82 of file BasicBlock.h.
References llvm::sandboxir::Value::getSubclassID().
dumpBndl()
static void llvm::sandboxir::dumpBndl (ArrayRef< Value * > Bndl) static
Definition at line 187 of file Legality.cpp.
References llvm::dbgs().
Referenced by llvm::sandboxir::LegalityAnalysis::canVectorize().
dumpImpl()
template<typename T> static void llvm::sandboxir::dumpImpl (ArrayRef< T * > Bndl) static
Definition at line 24 of file VecUtils.cpp.
References llvm::dbgs(), and llvm::enumerate().
Referenced by llvm::sandboxir::VecUtils::dump(), and llvm::sandboxir::VecUtils::dump().
dumpOS()
void llvm::sandboxir::dumpOS (raw_ostream & OS) const final
References const, and dumpOS().
Referenced by llvm::sandboxir::Type::dump(), and dumpOS().
empty()
bool llvm::sandboxir::empty () const
Definition at line 100 of file BasicBlock.h.
References begin(), and end().
Referenced by llvm::sandboxir::Interval< T >::disjoint(), and llvm::sandboxir::Instruction::eraseFromParent().
end()
iterator llvm::sandboxir::end () const
Definition at line 88 of file BasicBlock.h.
References llvm::cast().
Referenced by empty(), llvm::sandboxir::Instruction::getNextNode(), and rbegin().
front()
Instruction & llvm::sandboxir::front () const
getContext()
Context & llvm::sandboxir::getContext () const
Definition at line 98 of file BasicBlock.h.
Referenced by llvm::sandboxir::Constant::getParent(), llvm::sandboxir::ConstantStruct::getTypeForElements(), and llvm::sandboxir::SeedCollector::SeedCollector().
getInsertPointAfterInstrs()
static BasicBlock::iterator llvm::sandboxir::getInsertPointAfterInstrs (ArrayRef< Value * > Vals, BasicBlock * BB) static
\Returns the BB iterator after the lowest instruction in Vals, or the top of BB if no instruction found in Vals.
Definition at line 55 of file BottomUpVec.cpp.
References BasicBlock(), llvm::BasicBlock::begin(), llvm::BasicBlock::empty(), llvm::sandboxir::VecUtils::getLastPHIOrSelf(), and llvm::sandboxir::VecUtils::getLowest().
getLLVMBinaryOp()
static llvm::Instruction::BinaryOps llvm::sandboxir::getLLVMBinaryOp (Instruction::Opcode Opc) static
\Returns the LLVM opcode that corresponds to Opc.
Definition at line 1185 of file Instruction.cpp.
Referenced by llvm::sandboxir::BinaryOperator::create().
getLLVMCastOp()
static llvm::Instruction::CastOps llvm::sandboxir::getLLVMCastOp (Instruction::Opcode Opc) static
Definition at line 998 of file Instruction.cpp.
References llvm::sandboxir::Instruction::Opc.
Referenced by llvm::sandboxir::CastInst::create().
getLLVMUnaryOp()
static llvm::Instruction::UnaryOps llvm::sandboxir::getLLVMUnaryOp (Instruction::Opcode Opc) static
\Returns the LLVM opcode that corresponds to Opc.
Definition at line 1033 of file Instruction.cpp.
References llvm_unreachable, and llvm::sandboxir::Instruction::Opc.
Referenced by llvm::sandboxir::UnaryOperator::create().
getOperand()
static SmallVector< Value *, 4 > llvm::sandboxir::getOperand (ArrayRef< Value * > Bndl, unsigned OpIdx) static
Definition at line 43 of file BottomUpVec.cpp.
References llvm::cast(), and Operands.
Referenced by llvm::sandboxir::ExtractValueInst::getAggregateOperand(), llvm::sandboxir::ExtractValueInst::getAggregateOperand(), llvm::sandboxir::InsertValueInst::getAggregateOperand(), llvm::sandboxir::InsertValueInst::getAggregateOperand(), llvm::sandboxir::CallBase::getArgOperand(), llvm::sandboxir::SelectInst::getCondition(), llvm::sandboxir::SelectInst::getCondition(), llvm::sandboxir::SelectInst::getFalseValue(), llvm::sandboxir::SelectInst::getFalseValue(), llvm::sandboxir::ExtractElementInst::getIndexOperand(), llvm::sandboxir::ExtractElementInst::getIndexOperand(), llvm::sandboxir::InsertValueInst::getInsertedValueOperand(), llvm::sandboxir::InsertValueInst::getInsertedValueOperand(), llvm::sandboxir::AddrSpaceCastInst::getPointerOperand(), llvm::sandboxir::CatchSwitchInst::getSuccessor(), llvm::sandboxir::SelectInst::getTrueValue(), llvm::sandboxir::SelectInst::getTrueValue(), llvm::sandboxir::ExtractElementInst::getVectorOperand(), and llvm::sandboxir::ExtractElementInst::getVectorOperand().
getParent()
Function * llvm::sandboxir::getParent () const
getTerminator()
Instruction * llvm::sandboxir::getTerminator () const
isOrdered()
static bool llvm::sandboxir::isOrdered (Instruction * I) static
Definition at line 145 of file DependencyGraph.cpp.
References assert(), llvm::dyn_cast(), I, llvm::sandboxir::DGNode::isFenceLike(), and llvm::sandboxir::DGNode::isMemDepCandidate().
Referenced by llvm::sandboxir::CmpInst::WRAP_STATIC_PREDICATE().
isValidMemSeed()
template<typename LoadOrStoreT> static bool llvm::sandboxir::isValidMemSeed (LoadOrStoreT * LSI) static
Definition at line 145 of file SeedCollector.cpp.
References llvm::dyn_cast(), llvm::sandboxir::Utils::getExpectedType(), llvm::isa(), and llvm::sandboxir::VectorType::isValidElementType().
Referenced by llvm::sandboxir::SeedCollector::SeedCollector().
isValidMemSeed< LoadInst >()
template bool llvm::sandboxir::isValidMemSeed< LoadInst > (LoadInst * LSI)
isValidMemSeed< StoreInst >()
template bool llvm::sandboxir::isValidMemSeed< StoreInst > (StoreInst * LSI)
rbegin()
std::reverse_iterator< iterator > llvm::sandboxir::rbegin () const
Definition at line 92 of file BasicBlock.h.
References end().
rend()
std::reverse_iterator< iterator > llvm::sandboxir::rend () const
Definition at line 95 of file BasicBlock.h.
References begin().
skipNonInstr()
static User::op_iterator llvm::sandboxir::skipNonInstr (User::op_iterator OpIt, User::op_iterator OpItE) static nodiscard
While OpIt points to a Value that is not an Instruction keep incrementing it.
\Returns the first iterator that points to an Instruction, or end.
Definition at line 50 of file DependencyGraph.h.
References llvm::isa().
Referenced by llvm::sandboxir::PredIterator::operator++(), llvm::sandboxir::DGNode::preds_begin(), and llvm::sandboxir::MemDGNode::preds_begin().
verify()
void llvm::sandboxir::verify () const final
References const.
~BasicBlock()
llvm::sandboxir::~BasicBlock () default
Variable Documentation
CollectSeeds
cl::opt< std::string > llvm::sandboxir::CollectSeeds("sbvec-collect-seeds", cl::init(LoadSeedsDef "," StoreSeedsDef), cl::Hidden, cl::desc("Collect these seeds. Use empty for none or a comma-separated " "list of '" LoadSeedsDef "' and '" StoreSeedsDef "'.")) ("sbvec-collect-seeds" , cl::init(LoadSeedsDef "," StoreSeedsDef) , cl::Hidden , cl::desc("Collect these seeds. Use empty for none or a comma-separated " "list of '" LoadSeedsDef "' and '" StoreSeedsDef "'."))
Referenced by llvm::sandboxir::SeedCollector::SeedCollector().
MaxRegisteredCallbacks
int llvm::sandboxir::MaxRegisteredCallbacks = 16 static constexpr
Definition at line 693 of file Context.cpp.
Referenced by llvm::sandboxir::Context::registerCreateInstrCallback(), llvm::sandboxir::Context::registerEraseInstrCallback(), and llvm::sandboxir::Context::registerMoveInstrCallback().
SeedBundleSizeLimit
cl::opt< unsigned > llvm::sandboxir::SeedBundleSizeLimit("sbvec-seed-bundle-size-limit", cl::init(32), cl::Hidden, cl::desc("Limit the size of the seed bundle to cap compilation time.")) ("sbvec-seed-bundle-size-limit" , cl::init(32) , cl::Hidden , cl::desc("Limit the size of the seed bundle to cap compilation time."))
Referenced by llvm::sandboxir::SeedContainer::insert().
SeedGroupsLimit
cl::opt< unsigned > llvm::sandboxir::SeedGroupsLimit("sbvec-seed-groups-limit", cl::init(256), cl::Hidden, cl::desc("Limit the number of collected seeds groups in a BB to " "cap compilation time.")) ("sbvec-seed-groups-limit" , cl::init(256) , cl::Hidden , cl::desc("Limit the number of collected seeds groups in a BB to " "cap compilation time."))
Referenced by llvm::sandboxir::SeedCollector::SeedCollector().