LLVM: lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp File Reference
NVPTXTargetTransformInfo.cpp File Reference
#include "NVPTXTargetTransformInfo.h"
#include "NVPTXUtilities.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include <optional>
Macros
#define DEBUG_TYPE "NVPTXtti"
Functions
static bool readsThreadIndex (const IntrinsicInst *II)
static bool readsLaneId (const IntrinsicInst *II)
static bool isNVVMAtomic (const IntrinsicInst *II)
static Instruction * convertNvvmIntrinsicToLlvm (InstCombiner &IC, IntrinsicInst *II)
static std::optional< bool > evaluateIsSpace (Intrinsic::ID IID, unsigned AS)
static std::optional< Instruction * > handleSpaceCheckIntrinsics (InstCombiner &IC, IntrinsicInst &II)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "NVPTXtti"
Definition at line 27 of file NVPTXTargetTransformInfo.cpp.
Function Documentation
convertNvvmIntrinsicToLlvm()
static Instruction * convertNvvmIntrinsicToLlvm (InstCombiner & IC, IntrinsicInst * II) static
Definition at line 121 of file NVPTXTargetTransformInfo.cpp.
References llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::dyn_cast(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEsingle(), II, llvm_unreachable, Mode, llvm::DenormalMode::PreserveSign, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::NVPTXTTIImpl::instCombineIntrinsic().
evaluateIsSpace()
static std::optional< bool > evaluateIsSpace (Intrinsic::ID IID, unsigned AS) static
Definition at line 419 of file NVPTXTargetTransformInfo.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_CONST, llvm::NVPTXAS::ADDRESS_SPACE_GENERIC, llvm::NVPTXAS::ADDRESS_SPACE_GLOBAL, llvm::NVPTXAS::ADDRESS_SPACE_LOCAL, llvm::NVPTXAS::ADDRESS_SPACE_PARAM, llvm::NVPTXAS::ADDRESS_SPACE_SHARED, and llvm_unreachable.
Referenced by handleSpaceCheckIntrinsics(), and llvm::NVPTXTTIImpl::rewriteIntrinsicWithAddressSpace().
handleSpaceCheckIntrinsics()
static std::optional< Instruction * > handleSpaceCheckIntrinsics (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 449 of file NVPTXTargetTransformInfo.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_GENERIC, llvm::dyn_cast(), evaluateIsSpace(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), II, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::NVPTXTTIImpl::instCombineIntrinsic().
isNVVMAtomic()
static bool isNVVMAtomic (const IntrinsicInst * II) static
Definition at line 45 of file NVPTXTargetTransformInfo.cpp.
References II.
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().
readsLaneId()
static bool readsLaneId (const IntrinsicInst * II) static
Definition at line 40 of file NVPTXTargetTransformInfo.cpp.
References II.
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().
readsThreadIndex()
static bool readsThreadIndex (const IntrinsicInst * II) static
Definition at line 30 of file NVPTXTargetTransformInfo.cpp.
References II.
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().