LLVM: lib/Target/NVPTX/NVVMReflect.cpp File Reference
NVVMReflect.cpp File Reference
#include "NVPTX.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/CodeGen/CommandFlags.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
#define NVVM_REFLECT_OCL_FUNCTION "__nvvm_reflect_ocl"
#define DEBUG_TYPE "nvptx-reflect"
Functions
void llvm::initializeNVVMReflectPass (PassRegistry &)
INITIALIZE_PASS (NVVMReflect, "nvvm-reflect", "Replace occurrences of __nvvm_reflect() calls with 0/1", false, false) static bool runNVVMReflect(Function &F
if (F.getName()==NVVM_REFLECT_FUNCTION||F.getName()==NVVM_REFLECT_OCL_FUNCTION)
for (Instruction &I :instructions(F))
while (!ToSimplify.empty())
ToRemove erase (NewLastIter, ToRemove.end())
for (Instruction *I :ToRemove) I -> eraseFromParent()
return ToRemove size () > 0
Variables
static cl::opt< bool > NVVMReflectEnabled ("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default"))
unsigned SmVersion
SmallVector< Instruction *, 4 > ToRemove
SmallVector< Instruction *, 4 > ToSimplify
auto NewLastIter = llvm::unique(ToRemove)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-reflect"
Definition at line 48 of file NVVMReflect.cpp.
NVVM_REFLECT_FUNCTION
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
Definition at line 43 of file NVVMReflect.cpp.
Referenced by for(), and if().
NVVM_REFLECT_OCL_FUNCTION
#define NVVM_REFLECT_OCL_FUNCTION "__nvvm_reflect_ocl"
Definition at line 44 of file NVVMReflect.cpp.
Referenced by for(), and if().
Function Documentation
erase()
ToRemove erase (NewLastIter , ToRemove. end())
References NewLastIter, and ToRemove.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::erase().
for() [1/2]
for (Instruction &I :instructionsF)
Definition at line 122 of file NVVMReflect.cpp.
References assert(), Call, llvm::cast(), llvm::dbgs(), llvm::dyn_cast(), llvm::mdconst::extract_or_null(), F, for(), I, llvm::isa(), LLVM_DEBUG, NVVM_REFLECT_FUNCTION, NVVM_REFLECT_OCL_FUNCTION, llvm::StringRef::size(), SmVersion, llvm::StringRef::substr(), ToRemove, and ToSimplify.
for() [2/2]
for (Instruction *I :ToRemove) -> eraseFromParent()
References I, and ToRemove.
if()
if (F. getName() = = NVVM_REFLECT_FUNCTION || F.getName() == NVVM_REFLECT_OCL_FUNCTION)
Definition at line 85 of file NVVMReflect.cpp.
References F, NVVM_REFLECT_FUNCTION, and NVVM_REFLECT_OCL_FUNCTION.
INITIALIZE_PASS()
INITIALIZE_PASS (NVVMReflect , "nvvm-reflect" , "Replace occurrences of __nvvm_reflect() calls with 0/1" , false , false) &
size()
return ToRemove size ()
References ToRemove.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_aligned_reallocate(), _rpmalloc_allocate(), _rpmalloc_allocate_huge(), _rpmalloc_allocate_large(), _rpmalloc_allocate_medium(), _rpmalloc_allocate_small(), _rpmalloc_mmap(), _rpmalloc_mmap_os(), _rpmalloc_reallocate(), _rpmalloc_set_name(), _rpmalloc_unmap(), _rpmalloc_unmap_os(), llvm::pdb::NativeSession::addressForRVA(), llvm::const_iterator< MemoryLocation >::append(), llvm::const_iterator< MemoryLocation >::append(), llvm::SmallString< 0 >::append(), llvm::dwarf_linker::parallel::SectionDescriptor::applyIntVal(), llvm::dwarf_linker::parallel::SectionDescriptor::applySLEB128(), llvm::dwarf_linker::parallel::SectionDescriptor::applyULEB128(), llvm::CanonicalLoopInfo::assertOK(), llvm::const_iterator< MemoryLocation >::assign(), llvm::MutableArrayRef< uint8_t >::back(), llvm::StringRef::back(), CalculateUnswitchCostMultiplier(), llvm::StringRef::compare(), llvm::ValueEnumerator::computeBitsRequiredForTypeIndices(), llvm::LegacyLegalizerInfo::computeTables(), llvm::StringRef::consume_back(), llvm::StringRef::consume_back_insensitive(), llvm::StringRef::copy(), llvm::StringRef::count(), llvm::mca::InstrBuilder::createInstruction(), llvm::orc::createJITLoaderGDBRegistrar(), llvm::StringRef::detectEOL(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::drop_back(), llvm::MutableArrayRef< uint8_t >::drop_back(), llvm::StringRef::drop_back(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::drop_front(), llvm::MutableArrayRef< uint8_t >::drop_front(), llvm::StringRef::drop_front(), llvm::dxil::DXILBitcodeWriter::DXILBitcodeWriter(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::const_iterator< MemoryLocation >::emplace_back(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::empty(), llvm::OutlinedHashTree::empty(), llvm::StableFunctionMap::empty(), llvm::StringRef::empty(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::end(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::end(), llvm::MutableArrayRef< uint8_t >::end(), llvm::StringRef::end(), llvm::StringRef::ends_with(), enlarge(), llvm::StringRef::equals_insensitive(), llvm::VPIRBasicBlock::execute(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::StringRef::find_if(), llvm::DWARFUnitVector::finishedInfoUnits(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::RuntimeDyldCOFF::getDLLImportOffset(), llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), llvm::object::MinidumpFile::getMemory64List(), llvm::DWARFUnitVector::getNumInfoUnits(), llvm::DWARFUnitVector::getNumTypesUnits(), llvm::DWARFUnitVector::getNumUnits(), llvm::cl::generic_parser_base::getOptionWidth(), llvm::cl::bits< DataType, Storage, ParserClass >::getPosition(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::SIRegisterInfo::getSubRegFromChannel(), getSystemRegistryString(), llvm::slpvectorizer::BoUpSLP::VLOperands::getVL(), llvm::SmallVectorBase< Size_T >::grow_pod(), llvm::InlineFunction(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::ShuffleVectorInst::isReplicationMask(), isRightAfterData(), llvm::isSafeToUnrollAndJam(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), lto_input_get_dependent_library(), lto_runtime_lib_symbols_list(), llvm::StringRef::ltrim(), llvm::StringRef::ltrim(), llvm::GlobalMergeFunc::merge(), AbstractManglingParser< Derived, Alloc >::NameState::NameState(), operator new(), llvm::SmallString< 0 >::operator std::string(), llvm::StringRef::operator std::string_view(), llvm::operator+=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::const_iterator< MemoryLocation >::operator==(), llvm::StringMap< std::nullopt_t, AllocatorTy >::operator==(), llvm::MutableArrayRef< uint8_t >::operator[](), llvm::StringRef::operator[](), llvm::R600SchedStrategy::pickNode(), llvm::const_iterator< MemoryLocation >::pop_back_n(), llvm::NodeSet::print(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), llvm::const_iterator< MemoryLocation >::resize(), llvm::StringRef::rfind(), rpaligned_alloc(), rpaligned_calloc(), rpaligned_calloc(), rpaligned_realloc(), rpcalloc(), rpcalloc(), rpmalloc(), rpmalloc_initialize_config(), rpmemalign(), rpposix_memalign(), rprealloc(), llvm::StringRef::rtrim(), llvm::StringRef::rtrim(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::ScopedTemplateParamList(), llvm::SplitEditor::selectIntv(), separateNestedLoop(), llvm::LegacyLegalizerInfo::setAction(), llvm::LegacyLegalizerInfo::setLegalizeScalarToDifferentSizeStrategy(), llvm::LegacyLegalizerInfo::setLegalizeVectorElementToDifferentSizeStrategy(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::shrink_and_clear(), llvm::SIRegisterInfo::SIRegisterInfo(), llvm::orc::shared::SPSSerializationTraits< SPSTuple< SPSTagTs... >, std::tuple< Ts... > >::size(), llvm::adl_detail::size_impl(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::slice(), llvm::MutableArrayRef< uint8_t >::slice(), llvm::MutableArrayRef< uint8_t >::slice(), llvm::StringRef::slice(), llvm::StringRef::starts_with(), llvm::SmallString< 0 >::str(), llvm::StringRef::str(), llvm::StringRef::substr(), llvm::SmallVectorImpl< T >::swap(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::take_back(), llvm::MutableArrayRef< uint8_t >::take_back(), llvm::StringRef::take_back(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::take_front(), llvm::MutableArrayRef< uint8_t >::take_front(), llvm::StringRef::take_front(), llvm::const_iterator< MemoryLocation >::truncate(), llvm::orc::DLLImportDefinitionGenerator::tryToGenerate(), upgradeArmOrAarch64IntrinsicFunction(), and llvm::objcopy::wasm::Writer::write().
while()
while (!ToSimplify. empty())
Definition at line 192 of file NVVMReflect.cpp.
References I, if(), and ToSimplify.
Referenced by INITIALIZE_PASS().
Variable Documentation
NewLastIter
auto NewLastIter = llvm::unique(ToRemove)
Definition at line 211 of file NVVMReflect.cpp.
Referenced by erase().
NVVMReflectEnabled
cl::opt< bool > NVVMReflectEnabled("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default")) ("nvvm-reflect-enable" , cl::init(true) , cl::Hidden , cl::desc("NVVM reflection, enabled by default")) static
SmVersion
unsigned SmVersion
Initial value:
{
  if (!NVVMReflectEnabled)
    return false
Definition at line 81 of file NVVMReflect.cpp.
Referenced by llvm::createNVPTXCtorDtorLoweringLegacyPass(), llvm::createNVVMReflectPass(), for(), and PerformSETCCCombine().
ToRemove
SmallVector<Instruction *, 4> ToRemove
Definition at line 93 of file NVVMReflect.cpp.
ToSimplify
SmallVector<Instruction *, 4> ToSimplify
Definition at line 94 of file NVVMReflect.cpp.
Referenced by for(), runImpl(), simplifyLoopInst(), and while().