LLVM: lib/Transforms/Instrumentation/RealtimeSanitizer.cpp File Reference
RealtimeSanitizer.cpp File Reference
#include "llvm/IR/Analysis.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Demangle/Demangle.h"
#include "llvm/Transforms/Instrumentation/RealtimeSanitizer.h"
Functions
static SmallVector< Type * > getArgTypes (ArrayRef< Value * > FunctionArgs)
static void insertCallBeforeInstruction (Function &Fn, Instruction &Instruction, const char *FunctionName, ArrayRef< Value * > FunctionArgs)
static void insertCallAtFunctionEntryPoint (Function &Fn, const char *InsertFnName, ArrayRef< Value * > FunctionArgs)
static void insertCallAtAllFunctionExitPoints (Function &Fn, const char *InsertFnName, ArrayRef< Value * > FunctionArgs)
static PreservedAnalyses rtsanPreservedCFGAnalyses ()
static PreservedAnalyses runSanitizeRealtime (Function &Fn)
static PreservedAnalyses runSanitizeRealtimeBlocking (Function &Fn)
Variables
const char kRtsanModuleCtorName [] = "rtsan.module_ctor"
const char kRtsanInitName [] = "__rtsan_ensure_initialized"
Function Documentation
getArgTypes()
static SmallVector< Type * > getArgTypes (ArrayRef< Value * > FunctionArgs) static
Definition at line 30 of file RealtimeSanitizer.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by insertCallBeforeInstruction().
insertCallAtAllFunctionExitPoints()
static void insertCallAtAllFunctionExitPoints (Function & Fn, const char * InsertFnName, ArrayRef< Value * > FunctionArgs) static
Definition at line 56 of file RealtimeSanitizer.cpp.
References I, insertCallBeforeInstruction(), instructions, and llvm::isa().
Referenced by runSanitizeRealtime().
insertCallAtFunctionEntryPoint()
static void insertCallAtFunctionEntryPoint (Function & Fn, const char * InsertFnName, ArrayRef< Value * > FunctionArgs) static
Definition at line 49 of file RealtimeSanitizer.cpp.
References llvm::BasicBlock::front(), llvm::Function::front(), and insertCallBeforeInstruction().
Referenced by runSanitizeRealtime(), and runSanitizeRealtimeBlocking().
insertCallBeforeInstruction()
static void insertCallBeforeInstruction (Function & Fn, Instruction & Instruction, const char * FunctionName, ArrayRef< Value * > FunctionArgs) static
Definition at line 37 of file RealtimeSanitizer.cpp.
References llvm::IRBuilderBase::CreateCall(), llvm::FunctionType::get(), getArgTypes(), llvm::Function::getContext(), llvm::Module::getOrInsertFunction(), llvm::GlobalValue::getParent(), and llvm::Type::getVoidTy().
Referenced by insertCallAtAllFunctionExitPoints(), and insertCallAtFunctionEntryPoint().
rtsanPreservedCFGAnalyses()
static PreservedAnalyses rtsanPreservedCFGAnalyses () static
Definition at line 64 of file RealtimeSanitizer.cpp.
References llvm::PreservedAnalyses::preserveSet().
Referenced by runSanitizeRealtime(), and runSanitizeRealtimeBlocking().
runSanitizeRealtime()
static PreservedAnalyses runSanitizeRealtime (Function & Fn) static
Definition at line 70 of file RealtimeSanitizer.cpp.
References insertCallAtAllFunctionExitPoints(), insertCallAtFunctionEntryPoint(), and rtsanPreservedCFGAnalyses().
Referenced by llvm::RealtimeSanitizerPass::run().
runSanitizeRealtimeBlocking()
static PreservedAnalyses runSanitizeRealtimeBlocking (Function & Fn) static
Definition at line 76 of file RealtimeSanitizer.cpp.
References llvm::demangle(), llvm::BasicBlock::front(), llvm::Function::front(), llvm::Value::getName(), insertCallAtFunctionEntryPoint(), and rtsanPreservedCFGAnalyses().
Referenced by llvm::RealtimeSanitizerPass::run().
Variable Documentation
kRtsanInitName
const char kRtsanInitName[] = "__rtsan_ensure_initialized"
Definition at line 28 of file RealtimeSanitizer.cpp.
Referenced by llvm::RealtimeSanitizerPass::run().
kRtsanModuleCtorName
const char kRtsanModuleCtorName[] = "rtsan.module_ctor"
Definition at line 27 of file RealtimeSanitizer.cpp.
Referenced by llvm::RealtimeSanitizerPass::run().