LLVM: AbstractManglingParser< Derived, Alloc > Struct Template Reference
AbstractManglingParser< Derived, Alloc > Struct Template Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Classes
struct NameState
Holds some extra information about a <name> that is being parsed.
struct OperatorInfo
class SaveTemplateParams
class ScopedTemplateParamList
Public Types
using TemplateParamList = PODSmallVector<Node *, 8>
Public Member Functions
AbstractManglingParser (const char *First_, const char *Last_)
Derived & getDerived ()
void reset (const char *First_, const char *Last_)
template<class T, class... Args>
Node * make (Args &&... args)
template<class It>
NodeArray makeNodeArray (It begin, It end)
NodeArray popTrailingNodeArray (size_t FromPosition)
bool consumeIf (std::string_view S)
bool consumeIf (char C)
char consume ()
char look (unsigned Lookahead=0) const
size_t numLeft () const
std::string_view parseNumber (bool AllowNegative=false)
Qualifiers parseCVQualifiers ()
bool parsePositiveInteger (size_t *Out)
std::string_view parseBareSourceName ()
bool parseSeqId (size_t *Out)
Node * parseSubstitution ()
Node * parseTemplateParam ()
Node * parseTemplateParamDecl (TemplateParamList *Params)
Node * parseTemplateArgs (bool TagTemplates=false)
Node * parseTemplateArg ()
bool isTemplateParamDecl ()
Node * parseExpr ()
Parse the <expression> production.
Node * parsePrefixExpr (std::string_view Kind, Node::Prec Prec)
Node * parseBinaryExpr (std::string_view Kind, Node::Prec Prec)
Node * parseIntegerLiteral (std::string_view Lit)
Node * parseExprPrimary ()
template<class Float>
Node * parseFloatingLiteral ()
Node * parseFunctionParam ()
Node * parseConversionExpr ()
Node * parseBracedExpr ()
Node * parseFoldExpr ()
Node * parsePointerToMemberConversionExpr (Node::Prec Prec)
Node * parseSubobjectExpr ()
Node * parseConstraintExpr ()
Node * parseRequiresExpr ()
Node * parseType ()
Parse the <type> production.
Node * parseFunctionType ()
Node * parseVectorType ()
Node * parseDecltype ()
Node * parseArrayType ()
Node * parsePointerToMemberType ()
Node * parseClassEnumType ()
Node * parseQualifiedType ()
Node * parseEncoding (bool ParseParams=true)
bool parseCallOffset ()
Node * parseSpecialName ()
bool resolveForwardTemplateRefs (NameState &State)
Node * parseName (NameState *State=nullptr)
Parse the <name> production>
Node * parseLocalName (NameState *State)
Node * parseOperatorName (NameState *State)
bool parseModuleNameOpt (ModuleName *&Module)
Node * parseUnqualifiedName (NameState *State, Node *Scope, ModuleName *Module)
Node * parseUnnamedTypeName (NameState *State)
Node * parseSourceName (NameState *State)
Node * parseUnscopedName (NameState *State, bool *isSubstName)
Node * parseNestedName (NameState *State)
Node * parseCtorDtorName (Node *&SoFar, NameState *State)
Node * parseAbiTags (Node *N)
const OperatorInfo * parseOperatorEncoding ()
Node * parseUnresolvedName (bool Global)
Parse the <unresolved-name> production.
Node * parseSimpleId ()
Node * parseBaseUnresolvedName ()
Node * parseUnresolvedType ()
Node * parseDestructorName ()
Node * parse (bool ParseParams=true)
Top-level entry point into the parser.
Public Attributes
const char * First
const char * Last
PODSmallVector< Node *, 32 > Names
PODSmallVector< Node *, 32 > Subs
TemplateParamList OuterTemplateParams
PODSmallVector< TemplateParamList *, 4 > TemplateParams
PODSmallVector< ForwardTemplateReference *, 4 > ForwardTemplateRefs
bool TryToParseTemplateArgs = true
bool PermitForwardTemplateReferences = false
bool HasIncompleteTemplateParameterTracking = false
size_t ParsingLambdaParamsAtLevel = (size_t)-1
unsigned NumSyntheticTemplateParameters [3] = {}
Alloc ASTAllocator
Static Public Attributes
static const OperatorInfo Ops []
static const size_t NumOps
Detailed Description
template<typename Derived, typename Alloc>
struct AbstractManglingParser< Derived, Alloc >
Definition at line 2728 of file ItaniumDemangle.h.
Member Typedef Documentation
TemplateParamList
template<typename Derived, typename Alloc> using AbstractManglingParser< Derived, Alloc >::TemplateParamList = PODSmallVector<Node *, 8>
Definition at line 2744 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
AbstractManglingParser()
template<typename Derived, typename Alloc> AbstractManglingParser< Derived, Alloc >::AbstractManglingParser (const char * First_, const char * Last_) inline
Definition at line 2808 of file ItaniumDemangle.h.
References First, and Last.
Referenced by AbstractManglingParser< Derived, Alloc >::NameState::NameState(), AbstractManglingParser< Derived, Alloc >::SaveTemplateParams::SaveTemplateParams(), and AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::ScopedTemplateParamList().
Member Function Documentation
consume()
template<typename Derived, typename Alloc> char AbstractManglingParser< Derived, Alloc >::consume () inline
Definition at line 2863 of file ItaniumDemangle.h.
References First, and Last.
consumeIf() [1/2]
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::consumeIf (char C) inline
Definition at line 2855 of file ItaniumDemangle.h.
References C(), First, and Last.
consumeIf() [2/2]
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::consumeIf (std::string_view S) inline
Definition at line 2847 of file ItaniumDemangle.h.
References First, Last, and starts_with().
Referenced by parse(), parseAbiTags(), parseArrayType(), parseBaseUnresolvedName(), parseCallOffset(), parseClassEnumType(), parseConversionExpr(), parseCtorDtorName(), parseCVQualifiers(), parseDecltype(), parseEncoding(), parseExpr(), parseExprPrimary(), parseFloatingLiteral(), parseFoldExpr(), parseFunctionParam(), parseFunctionType(), parseIntegerLiteral(), parseLocalName(), parseModuleNameOpt(), parseNestedName(), parseNumber(), parseOperatorName(), parsePointerToMemberConversionExpr(), parsePointerToMemberType(), parseQualifiedType(), parseRequiresExpr(), parseSpecialName(), parseSubobjectExpr(), parseSubstitution(), parseTemplateArg(), parseTemplateArgs(), parseTemplateParam(), parseTemplateParamDecl(), parseType(), parseUnnamedTypeName(), parseUnqualifiedName(), parseUnresolvedName(), parseUnscopedName(), and parseVectorType().
getDerived()
template<typename Derived, typename Alloc> Derived & AbstractManglingParser< Derived, Alloc >::getDerived () inline
Definition at line 2811 of file ItaniumDemangle.h.
Referenced by parse(), parseArrayType(), parseBaseUnresolvedName(), parseBinaryExpr(), parseBracedExpr(), parseClassEnumType(), parseConstraintExpr(), parseConversionExpr(), parseCtorDtorName(), parseDecltype(), parseDestructorName(), parseEncoding(), parseExpr(), parseExprPrimary(), parseFoldExpr(), parseFunctionType(), parseLocalName(), parseModuleNameOpt(), parseName(), parseNestedName(), parseOperatorName(), parsePointerToMemberConversionExpr(), parsePointerToMemberType(), parsePrefixExpr(), parseQualifiedType(), parseRequiresExpr(), parseSimpleId(), parseSpecialName(), parseSubobjectExpr(), parseSubstitution(), parseTemplateArg(), parseTemplateArgs(), parseTemplateParamDecl(), parseType(), parseUnnamedTypeName(), parseUnqualifiedName(), parseUnresolvedName(), parseUnresolvedType(), parseUnscopedName(), and parseVectorType().
isTemplateParamDecl()
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::isTemplateParamDecl () inline
Definition at line 2885 of file ItaniumDemangle.h.
References look().
Referenced by parseTemplateArg(), and parseUnnamedTypeName().
look()
template<typename Derived, typename Alloc> char AbstractManglingParser< Derived, Alloc >::look (unsigned Lookahead = 0) const inline
Definition at line 2865 of file ItaniumDemangle.h.
References First, and Last.
Referenced by isTemplateParamDecl(), parse(), parseArrayType(), parseBaseUnresolvedName(), parseBracedExpr(), parseCtorDtorName(), parseDestructorName(), parseEncoding(), parseExpr(), parseExprPrimary(), parseFoldExpr(), parseName(), parseNestedName(), parseOperatorName(), parsePositiveInteger(), parseQualifiedType(), parseSeqId(), parseSimpleId(), parseSpecialName(), parseSubstitution(), parseTemplateArg(), parseType(), parseUnnamedTypeName(), parseUnqualifiedName(), parseUnresolvedName(), parseUnresolvedType(), parseUnscopedName(), and parseVectorType().
make()
template<typename Derived, typename Alloc> template<class T, class... Args> Node * AbstractManglingParser< Derived, Alloc >::make (Args &&... args) inline
Definition at line 2827 of file ItaniumDemangle.h.
References args, ASTAllocator, and T.
Referenced by parse(), parseAbiTags(), parseArrayType(), parseBaseUnresolvedName(), parseBinaryExpr(), parseBracedExpr(), parseClassEnumType(), parseConversionExpr(), parseCtorDtorName(), parseDecltype(), parseDestructorName(), parseEncoding(), parseExpr(), parseExprPrimary(), parseFloatingLiteral(), parseFoldExpr(), parseFunctionParam(), parseFunctionType(), parseIntegerLiteral(), parseLocalName(), parseModuleNameOpt(), parseName(), parseNestedName(), parseOperatorName(), parsePointerToMemberConversionExpr(), parsePointerToMemberType(), parsePrefixExpr(), parseQualifiedType(), parseRequiresExpr(), parseSimpleId(), parseSourceName(), parseSpecialName(), parseSubobjectExpr(), parseSubstitution(), parseTemplateArg(), parseTemplateArgs(), parseTemplateParam(), parseTemplateParamDecl(), parseType(), parseUnnamedTypeName(), parseUnqualifiedName(), parseUnresolvedName(), parseUnscopedName(), and parseVectorType().
makeNodeArray()
template<typename Derived, typename Alloc> template<class It> NodeArray AbstractManglingParser< Derived, Alloc >::makeNodeArray (It begin, It end) inline
Definition at line 2831 of file ItaniumDemangle.h.
References ASTAllocator, and data.
Referenced by parseConversionExpr(), and popTrailingNodeArray().
numLeft()
template<typename Derived, typename Alloc> size_t AbstractManglingParser< Derived, Alloc >::numLeft () const inline
Definition at line 2871 of file ItaniumDemangle.h.
References First, and Last.
Referenced by parse(), parseBareSourceName(), parseEncoding(), parseExpr(), parseFloatingLiteral(), parseNumber(), parseOperatorEncoding(), and parseSourceName().
parse()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parse (bool ParseParams = true)
Top-level entry point into the parser.
Definition at line 6138 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), Last, look(), make(), numLeft(), and parseNumber().
parseAbiTags()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseAbiTags (Node * N)
Definition at line 3867 of file ItaniumDemangle.h.
References consumeIf(), make(), N, and parseBareSourceName().
parseArrayType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseArrayType ()
Definition at line 4048 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), look(), make(), and parseNumber().
parseBareSourceName()
template<typename Alloc, typename Derived> std::string_view AbstractManglingParser< Alloc, Derived >::parseBareSourceName ()
Definition at line 3907 of file ItaniumDemangle.h.
References First, Int, numLeft(), and parsePositiveInteger().
Referenced by parseAbiTags(), parseQualifiedType(), and parseType().
parseBaseUnresolvedName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseBaseUnresolvedName ()
Definition at line 3745 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), look(), and make().
parseBinaryExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseBinaryExpr (std::string_view Kind, Node::Prec Prec)
Definition at line 4675 of file ItaniumDemangle.h.
References getDerived(), LHS, make(), and RHS.
parseBracedExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseBracedExpr ()
Definition at line 4899 of file ItaniumDemangle.h.
References First, getDerived(), look(), and make().
parseCallOffset()
template<typename Alloc, typename Derived> bool AbstractManglingParser< Alloc, Derived >::parseCallOffset ()
Definition at line 5453 of file ItaniumDemangle.h.
References consumeIf(), and parseNumber().
Referenced by parseSpecialName().
parseClassEnumType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseClassEnumType ()
Definition at line 4094 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), and make().
parseConstraintExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseConstraintExpr ()
Definition at line 5041 of file ItaniumDemangle.h.
References getDerived(), and HasIncompleteTemplateParameterTracking.
parseConversionExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseConversionExpr ()
Definition at line 4741 of file ItaniumDemangle.h.
References consumeIf(), E(), getDerived(), make(), makeNodeArray(), Names, popTrailingNodeArray(), and TryToParseTemplateArgs.
parseCtorDtorName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseCtorDtorName (Node *& SoFar, NameState * State)
Definition at line 3529 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), Node::getKind(), look(), make(), and parseName().
parseCVQualifiers()
template<typename Alloc, typename Derived> Qualifiers AbstractManglingParser< Alloc, Derived >::parseCVQualifiers ()
Definition at line 4697 of file ItaniumDemangle.h.
References consumeIf(), QualConst, QualNone, QualRestrict, and QualVolatile.
Referenced by parseFunctionParam(), parseFunctionType(), parseNestedName(), and parseQualifiedType().
parseDecltype()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseDecltype ()
Definition at line 4032 of file ItaniumDemangle.h.
References consumeIf(), E(), getDerived(), and make().
parseDestructorName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseDestructorName ()
Definition at line 3704 of file ItaniumDemangle.h.
References getDerived(), look(), and make().
parseEncoding()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseEncoding (bool ParseParams = true)
Definition at line 5631 of file ItaniumDemangle.h.
References consume(), consumeIf(), AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion, AbstractManglingParser< Derived, Alloc >::NameState::CVQualifiers, AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, getDerived(), AbstractManglingParser< Derived, Alloc >::NameState::HasExplicitObjectParameter, look(), make(), Names, numLeft(), popTrailingNodeArray(), AbstractManglingParser< Derived, Alloc >::NameState::ReferenceQualifier, and resolveForwardTemplateRefs().
parseExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseExpr ()
Parse the <expression> production.
Definition at line 5156 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Array, AbstractManglingParser< Derived, Alloc >::OperatorInfo::Binary, AbstractManglingParser< Derived, Alloc >::OperatorInfo::Call, AbstractManglingParser< Derived, Alloc >::OperatorInfo::CCast, Cond, AbstractManglingParser< Derived, Alloc >::OperatorInfo::Conditional, consumeIf(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Del, DEMANGLE_UNREACHABLE, E(), FP, getDerived(), LHS, look(), make(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Member, AbstractManglingParser< Derived, Alloc >::OperatorInfo::NamedCast, AbstractManglingParser< Derived, Alloc >::OperatorInfo::NameOnly, Names, AbstractManglingParser< Derived, Alloc >::OperatorInfo::New, numLeft(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::OfIdOp, parseOperatorEncoding(), parsePointerToMemberConversionExpr(), parseRequiresExpr(), parseSubobjectExpr(), popTrailingNodeArray(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Postfix, Node::Postfix, AbstractManglingParser< Derived, Alloc >::OperatorInfo::Prefix, RHS, NodeArray::size(), TryToParseTemplateArgs, and Node::Unary.
parseExprPrimary()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseExprPrimary ()
Definition at line 4779 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), look(), make(), N, parseFloatingLiteral(), parseNumber(), parseUnnamedTypeName(), and T.
parseFloatingLiteral()
template<typename Alloc, typename Derived> template<class Float> Node * AbstractManglingParser< Alloc, Derived >::parseFloatingLiteral ()
Definition at line 5762 of file ItaniumDemangle.h.
References C(), consumeIf(), First, make(), N, and numLeft().
Referenced by parseExprPrimary().
parseFoldExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseFoldExpr ()
Definition at line 4946 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Binary, consumeIf(), First, getDerived(), look(), make(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Member, parseOperatorEncoding(), and std::swap().
parseFunctionParam()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseFunctionParam ()
Definition at line 4714 of file ItaniumDemangle.h.
References consumeIf(), make(), parseCVQualifiers(), and parseNumber().
parseFunctionType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseFunctionType ()
Definition at line 3925 of file ItaniumDemangle.h.
References consumeIf(), E(), FrefQualLValue, FrefQualNone, FrefQualRValue, getDerived(), make(), Names, parseCVQualifiers(), popTrailingNodeArray(), and T.
parseIntegerLiteral()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseIntegerLiteral (std::string_view Lit)
Definition at line 4687 of file ItaniumDemangle.h.
References consumeIf(), make(), and parseNumber().
parseLocalName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseLocalName (NameState * State)
Definition at line 3082 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), Last, make(), N, parse_discriminator(), and parseNumber().
parseModuleNameOpt()
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::parseModuleNameOpt (ModuleName *& Module)
Definition at line 3214 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), make(), Module, and Subs.
Referenced by parseSpecialName(), and parseUnqualifiedName().
parseName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseName (NameState * State = nullptr)
Parse the <name> production>
Definition at line 3046 of file ItaniumDemangle.h.
References getDerived(), look(), make(), and Subs.
Referenced by parseCtorDtorName().
parseNestedName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseNestedName (NameState * State)
Definition at line 3586 of file ItaniumDemangle.h.
References consumeIf(), First, FrefQualLValue, FrefQualNone, FrefQualRValue, getDerived(), Node::getKind(), look(), make(), Module, parseCVQualifiers(), and Subs.
parseNumber()
template<typename Alloc, typename Derived> std::string_view AbstractManglingParser< Alloc, Derived >::parseNumber (bool AllowNegative = false)
Definition at line 3882 of file ItaniumDemangle.h.
References consumeIf(), First, and numLeft().
Referenced by parse(), parseArrayType(), parseCallOffset(), parseExprPrimary(), parseFunctionParam(), parseIntegerLiteral(), parseLocalName(), parseSpecialName(), parseSubobjectExpr(), parseType(), parseUnnamedTypeName(), and parseVectorType().
parseOperatorEncoding()
template<typename Derived, typename Alloc> const AbstractManglingParser< Derived, Alloc >::OperatorInfo * AbstractManglingParser< Derived, Alloc >::parseOperatorEncoding ()
Definition at line 3440 of file ItaniumDemangle.h.
References First, numLeft(), NumOps, and Ops.
Referenced by parseExpr(), parseFoldExpr(), and parseOperatorName().
parseOperatorName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseOperatorName (NameState * State)
Definition at line 3466 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::CCast, consumeIf(), First, getDerived(), look(), make(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Member, parseOperatorEncoding(), PermitForwardTemplateReferences, TryToParseTemplateArgs, and AbstractManglingParser< Derived, Alloc >::OperatorInfo::Unnameable.
parsePointerToMemberConversionExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parsePointerToMemberConversionExpr (Node::Prec Prec)
Definition at line 4999 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), and make().
Referenced by parseExpr().
parsePointerToMemberType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parsePointerToMemberType ()
Definition at line 4077 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), and make().
parsePositiveInteger()
template<typename Alloc, typename Derived> bool AbstractManglingParser< Alloc, Derived >::parsePositiveInteger (size_t * Out)
Definition at line 3895 of file ItaniumDemangle.h.
References consume(), and look().
Referenced by parseBareSourceName(), parseSourceName(), and parseTemplateParam().
parsePrefixExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parsePrefixExpr (std::string_view Kind, Node::Prec Prec)
Definition at line 4665 of file ItaniumDemangle.h.
References E(), getDerived(), and make().
parseQualifiedType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseQualifiedType ()
Definition at line 4117 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), Last, look(), make(), parseBareSourceName(), parseCVQualifiers(), QualNone, and starts_with().
parseRequiresExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseRequiresExpr ()
Definition at line 5050 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), make(), Names, popTrailingNodeArray(), and Type.
Referenced by parseExpr().
parseSeqId()
template<typename Alloc, typename Derived> bool AbstractManglingParser< Alloc, Derived >::parseSeqId (size_t * Out)
Definition at line 5778 of file ItaniumDemangle.h.
References First, and look().
Referenced by parseSpecialName(), and parseSubstitution().
parseSimpleId()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseSimpleId ()
Definition at line 3688 of file ItaniumDemangle.h.
References getDerived(), look(), and make().
parseSourceName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseSourceName (NameState * State)
Definition at line 3334 of file ItaniumDemangle.h.
References First, make(), numLeft(), parsePositiveInteger(), and starts_with().
parseSpecialName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseSpecialName ()
Definition at line 5486 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), look(), make(), Module, parseCallOffset(), parseModuleNameOpt(), parseNumber(), and parseSeqId().
parseSubobjectExpr()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseSubobjectExpr ()
Definition at line 5018 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), make(), Names, parseNumber(), and popTrailingNodeArray().
Referenced by parseExpr().
parseSubstitution()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseSubstitution ()
Definition at line 5811 of file ItaniumDemangle.h.
References allocator, basic_string, consumeIf(), First, getDerived(), iostream, istream, look(), make(), ostream, parseSeqId(), string, and Subs.
parseTemplateArg()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArg ()
Definition at line 6030 of file ItaniumDemangle.h.
References consumeIf(), First, getDerived(), isTemplateParamDecl(), look(), make(), Names, and popTrailingNodeArray().
parseTemplateArgs()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArgs (bool TagTemplates = false)
Definition at line 6084 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), Node::getKind(), make(), Names, OuterTemplateParams, popTrailingNodeArray(), and TemplateParams.
parseTemplateParam()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseTemplateParam ()
Definition at line 5877 of file ItaniumDemangle.h.
References consumeIf(), DEMANGLE_ASSERT, First, ForwardTemplateRefs, Node::getKind(), HasIncompleteTemplateParameterTracking, make(), parsePositiveInteger(), ParsingLambdaParamsAtLevel, PermitForwardTemplateReferences, and TemplateParams.
parseTemplateParamDecl()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseTemplateParamDecl (TemplateParamList * Params)
Definition at line 5947 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), HasIncompleteTemplateParameterTracking, make(), N, Names, NonType, NumSyntheticTemplateParameters, P, AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::params(), parseTemplateParamDecl(), parseType(), popTrailingNodeArray(), PODSmallVector< T, N >::push_back(), Template, and Type.
Referenced by parseTemplateParamDecl().
parseType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseType ()
Parse the <type> production.
Definition at line 4184 of file ItaniumDemangle.h.
References consumeIf(), DEMANGLE_FALLTHROUGH, First, getDerived(), look(), LValue, make(), P, parseBareSourceName(), parseNumber(), parseType(), Ptr, RValue, Signed, Size, Subs, and TryToParseTemplateArgs.
Referenced by parseTemplateParamDecl(), and parseType().
parseUnnamedTypeName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName (NameState * State)
Definition at line 3238 of file ItaniumDemangle.h.
References consumeIf(), NodeArray::empty(), getDerived(), isTemplateParamDecl(), look(), make(), Names, P, AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::params(), parseNumber(), ParsingLambdaParamsAtLevel, popTrailingNodeArray(), T, and TemplateParams.
Referenced by parseExprPrimary().
parseUnqualifiedName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseUnqualifiedName (NameState * State, Node * Scope, ModuleName * Module)
Definition at line 3163 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), look(), make(), Module, Names, parseModuleNameOpt(), and popTrailingNodeArray().
parseUnresolvedName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedName (bool Global)
Parse the <unresolved-name> production.
Definition at line 3779 of file ItaniumDemangle.h.
References consumeIf(), DEMANGLE_ASSERT, getDerived(), look(), and make().
parseUnresolvedType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedType ()
Definition at line 3719 of file ItaniumDemangle.h.
References getDerived(), look(), and Subs.
parseUnscopedName()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseUnscopedName (NameState * State, bool * isSubstName)
Definition at line 3123 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), Node::getKind(), look(), make(), and Module.
parseVectorType()
template<typename Derived, typename Alloc> Node * AbstractManglingParser< Derived, Alloc >::parseVectorType ()
Definition at line 3995 of file ItaniumDemangle.h.
References consumeIf(), getDerived(), look(), make(), and parseNumber().
popTrailingNodeArray()
template<typename Derived, typename Alloc> NodeArray AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray (size_t FromPosition) inline
Definition at line 2839 of file ItaniumDemangle.h.
References DEMANGLE_ASSERT, makeNodeArray(), and Names.
Referenced by parseConversionExpr(), parseEncoding(), parseExpr(), parseFunctionType(), parseRequiresExpr(), parseSubobjectExpr(), parseTemplateArg(), parseTemplateArgs(), parseTemplateParamDecl(), parseUnnamedTypeName(), and parseUnqualifiedName().
reset()
template<typename Derived, typename Alloc> void AbstractManglingParser< Derived, Alloc >::reset (const char * First_, const char * Last_) inline
Definition at line 2813 of file ItaniumDemangle.h.
References ASTAllocator, First, I, Last, Names, NumSyntheticTemplateParameters, ParsingLambdaParamsAtLevel, PermitForwardTemplateReferences, Subs, TemplateParams, and TryToParseTemplateArgs.
resolveForwardTemplateRefs()
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs (NameState & State) inline
Definition at line 2934 of file ItaniumDemangle.h.
References E(), ForwardTemplateRefs, I, and TemplateParams.
Referenced by parseEncoding().
Member Data Documentation
ASTAllocator
template<typename Derived, typename Alloc> Alloc AbstractManglingParser< Derived, Alloc >::ASTAllocator
Definition at line 2806 of file ItaniumDemangle.h.
Referenced by make(), makeNodeArray(), and reset().
First
template<typename Derived, typename Alloc> const char* AbstractManglingParser< Derived, Alloc >::First
Definition at line 2729 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser(), consume(), consumeIf(), consumeIf(), look(), numLeft(), parse(), parseBareSourceName(), parseBracedExpr(), parseCtorDtorName(), parseExprPrimary(), parseFloatingLiteral(), parseFoldExpr(), parseLocalName(), parseNestedName(), parseNumber(), parseOperatorEncoding(), parseOperatorName(), parseQualifiedType(), parseSeqId(), parseSourceName(), parseSpecialName(), parseSubstitution(), parseTemplateArg(), parseTemplateParam(), parseType(), and reset().
ForwardTemplateRefs
template<typename Derived, typename Alloc> PODSmallVector<ForwardTemplateReference *, 4> AbstractManglingParser< Derived, Alloc >::ForwardTemplateRefs
Definition at line 2797 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::NameState::NameState(), parseTemplateParam(), and resolveForwardTemplateRefs().
HasIncompleteTemplateParameterTracking
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::HasIncompleteTemplateParameterTracking = false
Definition at line 2801 of file ItaniumDemangle.h.
Referenced by parseConstraintExpr(), parseTemplateParam(), and parseTemplateParamDecl().
Last
template<typename Derived, typename Alloc> const char* AbstractManglingParser< Derived, Alloc >::Last
Definition at line 2730 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser(), consume(), consumeIf(), consumeIf(), look(), numLeft(), parse(), parseLocalName(), parseQualifiedType(), and reset().
Names
template<typename Derived, typename Alloc> PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Names
Definition at line 2735 of file ItaniumDemangle.h.
Referenced by parseConversionExpr(), parseEncoding(), parseExpr(), parseFunctionType(), parseRequiresExpr(), parseSubobjectExpr(), parseTemplateArg(), parseTemplateArgs(), parseTemplateParamDecl(), parseUnnamedTypeName(), parseUnqualifiedName(), popTrailingNodeArray(), and reset().
NumOps
template<typename Derived, typename Alloc> const size_t AbstractManglingParser< Derived, Alloc >::NumOps static
Definition at line 3022 of file ItaniumDemangle.h.
Referenced by parseOperatorEncoding().
NumSyntheticTemplateParameters
template<typename Derived, typename Alloc> unsigned AbstractManglingParser< Derived, Alloc >::NumSyntheticTemplateParameters[3] = {}
Definition at line 2804 of file ItaniumDemangle.h.
Referenced by parseTemplateParamDecl(), and reset().
Ops
template<typename Derived, typename Alloc> const OperatorInfo AbstractManglingParser< Derived, Alloc >::Ops[] static
Definition at line 3021 of file ItaniumDemangle.h.
Referenced by parseOperatorEncoding().
OuterTemplateParams
template<typename Derived, typename Alloc> TemplateParamList AbstractManglingParser< Derived, Alloc >::OuterTemplateParams
Definition at line 2768 of file ItaniumDemangle.h.
Referenced by parseTemplateArgs().
ParsingLambdaParamsAtLevel
template<typename Derived, typename Alloc> size_t AbstractManglingParser< Derived, Alloc >::ParsingLambdaParamsAtLevel = (size_t)-1
Definition at line 2802 of file ItaniumDemangle.h.
Referenced by parseTemplateParam(), parseUnnamedTypeName(), and reset().
PermitForwardTemplateReferences
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::PermitForwardTemplateReferences = false
Definition at line 2800 of file ItaniumDemangle.h.
Referenced by parseOperatorName(), parseTemplateParam(), and reset().
Subs
template<typename Derived, typename Alloc> PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Subs
Definition at line 2740 of file ItaniumDemangle.h.
Referenced by parseModuleNameOpt(), parseName(), parseNestedName(), parseSubstitution(), parseType(), parseUnresolvedType(), and reset().
TemplateParams
template<typename Derived, typename Alloc> PODSmallVector<TemplateParamList *, 4> AbstractManglingParser< Derived, Alloc >::TemplateParams
Definition at line 2775 of file ItaniumDemangle.h.
Referenced by parseTemplateArgs(), parseTemplateParam(), parseUnnamedTypeName(), reset(), resolveForwardTemplateRefs(), and AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::ScopedTemplateParamList().
TryToParseTemplateArgs
template<typename Derived, typename Alloc> bool AbstractManglingParser< Derived, Alloc >::TryToParseTemplateArgs = true
Definition at line 2799 of file ItaniumDemangle.h.
Referenced by parseConversionExpr(), parseExpr(), parseOperatorName(), parseType(), and reset().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h