LLVM: llvm::VPWidenStoreRecipe Struct Reference
llvm::VPWidenStoreRecipe Struct Reference final
A recipe for widening store operations, using the stored value, the address to store to and an optional mask.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenStoreRecipe (StoreInst &Store, VPValue *Addr, VPValue *StoredVal, VPValue *Mask, bool Consecutive, bool Reverse, DebugLoc DL)
VPWidenStoreRecipe * clone () override
Clone the current recipe.
VP_CLASSOF_IMPL (VPDef::VPWidenStoreSC)
VPValue * getStoredValue () const
Return the value stored by this recipe.
void execute (VPTransformState &State) override
Generate a wide store or scatter.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
Public Member Functions inherited from llvm::VPWidenMemoryRecipe
bool isConsecutive () const
Return whether the loaded-from / stored-to addresses are consecutive.
bool isReverse () const
Return whether the consecutive loaded/stored addresses are in reverse order.
VPValue * getAddr () const
Return the address accessed by this recipe.
bool isMasked () const
Returns true if the recipe is masked.
VPValue * getMask () const
Return the mask used by this recipe.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this VPWidenMemoryRecipe.
Instruction & getIngredient () const
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT>
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Static Public Member Functions inherited from llvm::VPWidenMemoryRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::VPWidenMemoryRecipe
void setMask (VPValue *Mask)
VPWidenMemoryRecipe (const char unsigned SC, Instruction &I, std::initializer_list< VPValue * > Operands, bool Consecutive, bool Reverse, DebugLoc DL)
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
VPUser (std::initializer_list< VPValue * > Operands)
template<typename IterT>
VPUser (iterator_range< IterT > Operands)
Protected Attributes inherited from llvm::VPWidenMemoryRecipe
Instruction & Ingredient
bool Consecutive
Whether the accessed addresses are consecutive.
bool Reverse
Whether the consecutive accessed addresses are in reverse order.
bool IsMasked = false
Whether the memory access is masked.
Detailed Description
A recipe for widening store operations, using the stored value, the address to store to and an optional mask.
Definition at line 3111 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenStoreRecipe()
llvm::VPWidenStoreRecipe::VPWidenStoreRecipe (StoreInst & Store, VPValue * Addr, VPValue * StoredVal, VPValue * Mask, bool Consecutive, bool Reverse, DebugLoc DL) inline
Definition at line 3112 of file VPlan.h.
References llvm::VPWidenMemoryRecipe::Consecutive, llvm::VPWidenMemoryRecipe::Reverse, and llvm::VPWidenMemoryRecipe::VPWidenMemoryRecipe().
Referenced by clone().
Member Function Documentation
clone()
VPWidenStoreRecipe * llvm::VPWidenStoreRecipe::clone () inline override virtual
Clone the current recipe.
Reimplemented from llvm::VPWidenMemoryRecipe.
Definition at line 3119 of file VPlan.h.
References llvm::cast(), llvm::VPWidenMemoryRecipe::Consecutive, llvm::VPWidenMemoryRecipe::getAddr(), llvm::VPRecipeBase::getDebugLoc(), llvm::VPWidenMemoryRecipe::getMask(), getStoredValue(), llvm::VPWidenMemoryRecipe::Ingredient, llvm::VPWidenMemoryRecipe::Reverse, and VPWidenStoreRecipe().
execute()
void VPWidenStoreRecipe::execute (VPTransformState & State) override virtual
Generate a wide store or scatter.
Reimplemented from llvm::VPWidenMemoryRecipe.
Definition at line 2730 of file VPlanRecipes.cpp.
References llvm::Value::addMetadata(), llvm::cast(), llvm::VPWidenMemoryRecipe::getAddr(), llvm::VPRecipeBase::getDebugLoc(), llvm::getLoadStoreAlignment(), llvm::VPWidenMemoryRecipe::getMask(), llvm::getStoredValue(), llvm::VPWidenMemoryRecipe::Ingredient, llvm::VPWidenMemoryRecipe::isConsecutive(), and llvm::VPWidenMemoryRecipe::isReverse().
getStoredValue()
VPValue * llvm::VPWidenStoreRecipe::getStoredValue () const inline
Return the value stored by this recipe.
Definition at line 3128 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by clone(), onlyFirstLaneUsed(), and llvm::VPWidenStoreEVLRecipe::VPWidenStoreEVLRecipe().
onlyFirstLaneUsed()
bool llvm::VPWidenStoreRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPUser.
Definition at line 3140 of file VPlan.h.
References assert(), llvm::VPWidenMemoryRecipe::getAddr(), getStoredValue(), llvm::is_contained(), llvm::VPWidenMemoryRecipe::isConsecutive(), and llvm::VPUser::operands().
print()
void VPWidenStoreRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 2769 of file VPlanRecipes.cpp.
References llvm::VPUser::printOperands().
VP_CLASSOF_IMPL()
llvm::VPWidenStoreRecipe::VP_CLASSOF_IMPL (VPDef::VPWidenStoreSC)
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp