LLVM: llvm::simplify_type< From > Struct Template Reference
llvm::simplify_type< From > Struct Template Reference
Define a template that can be specialized by smart pointers to reflect the fact that they are automatically dereferenced, and are not involved with the template selection process... the default implementation is a noop.
#include "llvm/Support/Casting.h"
Public Types
using SimpleType = From
Static Public Member Functions
static SimpleType & getSimplifiedValue (From &Val)
Detailed Description
template<typename From>
struct llvm::simplify_type< From >
Define a template that can be specialized by smart pointers to reflect the fact that they are automatically dereferenced, and are not involved with the template selection process... the default implementation is a noop.
Definition at line 34 of file Casting.h.
Member Typedef Documentation
SimpleType
template<typename From> using llvm::simplify_type< From >::SimpleType = From
Definition at line 35 of file Casting.h.
Member Function Documentation
getSimplifiedValue()
template<typename From> static SimpleType & llvm::simplify_type< From >::getSimplifiedValue (From & Val) inline static
Definition at line 38 of file Casting.h.
Referenced by llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCast(), llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCastIfPossible(), llvm::cast_convert_val< To, From, SimpleFrom >::doit(), llvm::isa_impl_wrap< To, From, SimpleFrom >::doit(), llvm::simplify_type< const From >::getSimplifiedValue(), llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::isPossible(), and llvm::detail::isPresent().
The documentation for this struct was generated from the following files:
include/llvm/ADT/ilist_iterator.h
include/llvm/Support/Casting.h