LLVM: llvm::GlobalMergeFuncPass Struct Reference
llvm::GlobalMergeFuncPass Struct Reference
Global function merging pass for new pass manager.
#include "llvm/CodeGen/GlobalMergeFunctions.h"
Public Member Functions
GlobalMergeFuncPass ()=default
GlobalMergeFuncPass (const ModuleSummaryIndex *ImportSummary)
PreservedAnalyses run (Module &M, AnalysisManager< Module > &)
Public Member Functions inherited from llvm::PassInfoMixin< GlobalMergeFuncPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Attributes
const ModuleSummaryIndex * ImportSummary = nullptr
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GlobalMergeFuncPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Global function merging pass for new pass manager.
Definition at line 80 of file GlobalMergeFunctions.h.
Constructor & Destructor Documentation
GlobalMergeFuncPass() [1/2]
llvm::GlobalMergeFuncPass::GlobalMergeFuncPass () default
GlobalMergeFuncPass() [2/2]
llvm::GlobalMergeFuncPass::GlobalMergeFuncPass (const ModuleSummaryIndex * ImportSummary) inline
Definition at line 83 of file GlobalMergeFunctions.h.
References ImportSummary.
Member Function Documentation
run()
PreservedAnalyses GlobalMergeFuncPass::run (Module & M, AnalysisManager< Module > & AM)
Definition at line 645 of file GlobalMergeFunctions.cpp.
References llvm::PreservedAnalyses::all(), Changed, ImportSummary, llvm::PreservedAnalyses::none(), and llvm::GlobalMergeFunc::run().
Member Data Documentation
ImportSummary
const ModuleSummaryIndex* llvm::GlobalMergeFuncPass::ImportSummary = nullptr
Definition at line 81 of file GlobalMergeFunctions.h.
Referenced by GlobalMergeFuncPass(), and run().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/GlobalMergeFunctions.h
lib/CodeGen/GlobalMergeFunctions.cpp