LLVM: llvm::cast_convert_val< To, From, SimpleFrom > Struct Template Reference
llvm::cast_convert_val< To, From, SimpleFrom > Struct Template Reference
#include "llvm/Support/Casting.h"
Static Public Member Functions
static cast_retty< To, From >::ret_type doit (const From &Val)
Detailed Description
template<class To, class From, class SimpleFrom>
struct llvm::cast_convert_val< To, From, SimpleFrom >
Definition at line 202 of file Casting.h.
Member Function Documentation
doit()
template<class To, class From, class SimpleFrom> static cast_retty< To, From >::ret_type llvm::cast_convert_val< To, From, SimpleFrom >::doit (const From & Val) inline static
Definition at line 204 of file Casting.h.
References doit(), and llvm::simplify_type< From >::getSimplifiedValue().
Referenced by doit().
The documentation for this struct was generated from the following file:
include/llvm/Support/Casting.h