LLVM: llvm::VPTransformState Struct Reference
llvm::VPTransformState Struct Reference
VPTransformState holds information passed down when "executing" a VPlan, needed for generating the output IR.
#include "Transforms/Vectorize/VPlan.h"
Classes
struct CFGState
Hold state information used when constructing the CFG of the output IR, traversing the VPBasicBlocks and generating corresponding IR BasicBlocks.
struct DataState
Public Member Functions
VPTransformState (const TargetTransformInfo *TTI, ElementCount VF, unsigned UF, LoopInfo *LI, DominatorTree *DT, IRBuilderBase &Builder, InnerLoopVectorizer *ILV, VPlan *Plan, Loop *CurrentParentLoop, Type *CanonicalIVTy)
Value * get (VPValue *Def, bool IsScalar=false)
Get the generated vector Value for a given VPValue Def if IsScalar is false, otherwise return the generated scalar.
Value * get (VPValue *Def, const VPLane &Lane)
Get the generated Value for a given VPValue and given Part and Lane.
bool hasVectorValue (VPValue *Def)
bool hasScalarValue (VPValue *Def, VPLane Lane)
void set (VPValue *Def, Value *V, bool IsScalar=false)
Set the generated vector Value for a given VPValue, if IsScalar is false.
void reset (VPValue *Def, Value *V)
Reset an existing vector value for Def and a given Part.
void set (VPValue *Def, Value *V, const VPLane &Lane)
Set the generated scalar V for Def and the given Lane.
void reset (VPValue *Def, Value *V, const VPLane &Lane)
Reset an existing scalar value for Def and a given Lane.
void addNewMetadata (Instruction *To, const Instruction *Orig)
Add additional metadata to To that was not present on Orig.
void addMetadata (Value *To, Instruction *From)
Add metadata from one instruction to another.
void setDebugLocFrom (DebugLoc DL)
Set the debug location in the builder using the debug location DL.
void packScalarIntoVectorValue (VPValue *Def, const VPLane &Lane)
Construct the vector value of a scalarized value V one lane at a time.
Public Attributes
const TargetTransformInfo * TTI
Target Transform Info.
ElementCount VF
The chosen Vectorization Factor of the loop being vectorized.
std::optional< VPLane > Lane
Hold the index to generate specific scalar instructions.
struct llvm::VPTransformState::DataState Data
struct llvm::VPTransformState::CFGState CFG
LoopInfo * LI
Hold a pointer to LoopInfo to register new basic blocks in the loop.
IRBuilderBase & Builder
Hold a reference to the IRBuilder used to generate output IR code.
InnerLoopVectorizer * ILV
Hold a pointer to InnerLoopVectorizer to reuse its IR generation methods.
VPlan * Plan
Pointer to the VPlan code is generated for.
Loop * CurrentParentLoop = nullptr
The parent loop object for the current scope, or nullptr.
LoopVersioning * LVer = nullptr
LoopVersioning.
DenseMap< const SCEV *, Value * > ExpandedSCEVs
Map SCEVs to their expanded values.
VPTypeAnalysis TypeAnalysis
VPlan-based type analysis.
Detailed Description
VPTransformState holds information passed down when "executing" a VPlan, needed for generating the output IR.
Definition at line 231 of file VPlan.h.
Constructor & Destructor Documentation
VPTransformState()
VPTransformState::VPTransformState (const TargetTransformInfo * TTI, ElementCount VF, unsigned UF, LoopInfo * LI, DominatorTree * DT, IRBuilderBase & Builder, InnerLoopVectorizer * ILV, VPlan * Plan, Loop * CurrentParentLoop, Type * CanonicalIVTy)
Definition at line 215 of file VPlan.cpp.
References Builder, CFG, CurrentParentLoop, ILV, LI, LVer, Plan, TTI, TypeAnalysis, and VF.
Member Function Documentation
addMetadata()
void VPTransformState::addMetadata (Value * To, Instruction * From)
Add metadata from one instruction to another.
This includes both the original MDs from From and additional ones (
See also
addNewMetadata). Use this for newly created instructions in the vector loop.
Definition at line 360 of file VPlan.cpp.
References addNewMetadata(), llvm::dyn_cast(), and llvm::propagateMetadata().
addNewMetadata()
void VPTransformState::addNewMetadata (Instruction * To, const Instruction * Orig)
Add additional metadata to To that was not present on Orig.
Currently this is used to add the noalias annotations based on the inserted memchecks. Use this for instructions that are cloned into the vector loop.
Definition at line 352 of file VPlan.cpp.
References llvm::isa(), and LVer.
Referenced by addMetadata().
get() [1/2]
Value * VPTransformState::get (VPValue * Def, bool IsScalar = false)
Get the generated vector Value for a given VPValue Def if IsScalar is false, otherwise return the generated scalar.
\See set.
Definition at line 249 of file VPlan.cpp.
References assert(), B(), Builder, llvm::cast(), CFG, Data, llvm::PoisonValue::get(), llvm::VectorType::get(), get(), llvm::BasicBlock::getTerminator(), hasScalarValue(), hasVectorValue(), llvm::isa(), llvm::vputils::isUniformAfterVectorization(), Lane, llvm::vputils::onlyFirstLaneUsed(), packScalarIntoVectorValue(), Plan, set(), and VF.
Referenced by get(), and packScalarIntoVectorValue().
get() [2/2]
Value * VPTransformState::get (VPValue * Def, const VPLane & Lane)
Get the generated Value for a given VPValue and given Part and Lane.
Definition at line 224 of file VPlan.cpp.
References assert(), Builder, Data, llvm::VPLane::getFirstLane(), hasScalarValue(), hasVectorValue(), llvm::vputils::isUniformAfterVectorization(), Lane, and VF.
hasScalarValue()
bool llvm::VPTransformState::hasScalarValue (VPValue * Def, VPLane Lane) inline
Definition at line 264 of file VPlan.h.
References Data, I, Lane, and VF.
Referenced by get(), and get().
hasVectorValue()
bool llvm::VPTransformState::hasVectorValue (VPValue * Def) inline
Definition at line 262 of file VPlan.h.
References Data.
Referenced by get(), and get().
packScalarIntoVectorValue()
void VPTransformState::packScalarIntoVectorValue (VPValue * Def, const VPLane & Lane)
Construct the vector value of a scalarized value V one lane at a time.
Definition at line 393 of file VPlan.cpp.
References Builder, get(), Lane, set(), and VF.
Referenced by get().
reset() [1/2]
void llvm::VPTransformState::reset (VPValue * Def, Value * V) inline
Reset an existing vector value for Def and a given Part.
Definition at line 285 of file VPlan.h.
References assert(), and Data.
reset() [2/2]
void llvm::VPTransformState::reset (VPValue * Def, Value * V, const VPLane & Lane) inline
Reset an existing scalar value for Def and a given Lane.
Definition at line 301 of file VPlan.h.
References assert(), Data, Lane, and VF.
set() [1/2]
void llvm::VPTransformState::set (VPValue * Def, Value * V, bool IsScalar = false) inline
Set the generated vector Value for a given VPValue, if IsScalar is false.
If IsScalar is true, set the scalar in lane 0.
Definition at line 274 of file VPlan.h.
References assert(), Data, set(), and VF.
Referenced by get(), packScalarIntoVectorValue(), and set().
set() [2/2]
void llvm::VPTransformState::set (VPValue * Def, Value * V, const VPLane & Lane) inline
Set the generated scalar V for Def and the given Lane.
Definition at line 291 of file VPlan.h.
References assert(), Data, Lane, and VF.
setDebugLocFrom()
void VPTransformState::setDebugLocFrom (DebugLoc DL)
Set the debug location in the builder using the debug location DL.
Definition at line 371 of file VPlan.cpp.
References Builder, llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::dbgs(), DL, llvm::EnableFSDiscriminator, LLVM_DEBUG, Plan, and VF.
Member Data Documentation
Builder
IRBuilderBase& llvm::VPTransformState::Builder
Hold a reference to the IRBuilder used to generate output IR code.
Definition at line 364 of file VPlan.h.
Referenced by llvm::VPlan::createInitialVPlan(), get(), get(), packScalarIntoVectorValue(), llvm::VPlan::prepareToExecute(), setDebugLocFrom(), and VPTransformState().
CFG
struct llvm::VPTransformState::CFGState llvm::VPTransformState::CFG
Referenced by get(), and VPTransformState().
CurrentParentLoop
Loop* llvm::VPTransformState::CurrentParentLoop = nullptr
The parent loop object for the current scope, or nullptr.
Definition at line 373 of file VPlan.h.
Referenced by VPTransformState().
Data
struct llvm::VPTransformState::DataState llvm::VPTransformState::Data
Referenced by get(), get(), hasScalarValue(), hasVectorValue(), reset(), reset(), set(), and set().
ExpandedSCEVs
DenseMap<const SCEV *, Value *> llvm::VPTransformState::ExpandedSCEVs
Map SCEVs to their expanded values.
Populated when executing VPExpandSCEVRecipes.
Definition at line 384 of file VPlan.h.
ILV
InnerLoopVectorizer* llvm::VPTransformState::ILV
Hold a pointer to InnerLoopVectorizer to reuse its IR generation methods.
Definition at line 367 of file VPlan.h.
Referenced by VPTransformState().
Lane
std::optional<VPLane> llvm::VPTransformState::Lane
Hold the index to generate specific scalar instructions.
Null indicates that all instances are to be generated, using either scalar or vector instructions.
Definition at line 245 of file VPlan.h.
Referenced by llvm::VPRegionBlock::execute(), get(), get(), hasScalarValue(), packScalarIntoVectorValue(), reset(), and set().
LI
LoopInfo* llvm::VPTransformState::LI
Hold a pointer to LoopInfo to register new basic blocks in the loop.
Definition at line 361 of file VPlan.h.
Referenced by VPTransformState().
LVer
LoopVersioning* llvm::VPTransformState::LVer = nullptr
LoopVersioning.
It's only set up (non-null) if memchecks were used.
This is currently only used to add no-alias metadata based on the memchecks. The actually versioning is performed manually.
Definition at line 380 of file VPlan.h.
Referenced by addNewMetadata(), and VPTransformState().
Plan
VPlan* llvm::VPTransformState::Plan
Pointer to the VPlan code is generated for.
Definition at line 370 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::buildVPlans(), llvm::VPlan::createInitialVPlan(), get(), llvm::LoopVectorizationPlanner::getPlanFor(), llvm::LoopVectorizationPlanner::printPlans(), setDebugLocFrom(), llvm::VPInterleavedAccessInfo::VPInterleavedAccessInfo(), and VPTransformState().
TTI
const TargetTransformInfo* llvm::VPTransformState::TTI
Target Transform Info.
Definition at line 237 of file VPlan.h.
Referenced by VPTransformState().
TypeAnalysis
VPTypeAnalysis llvm::VPTransformState::TypeAnalysis
VPlan-based type analysis.
Definition at line 387 of file VPlan.h.
Referenced by VPTransformState().
VF
ElementCount llvm::VPTransformState::VF
The chosen Vectorization Factor of the loop being vectorized.
Definition at line 240 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::buildVPlans(), llvm::VPBasicBlock::cost(), llvm::VPRegionBlock::cost(), llvm::VPRegionBlock::execute(), get(), get(), llvm::LoopVectorizationPlanner::getPlanFor(), hasScalarValue(), packScalarIntoVectorValue(), reset(), set(), set(), setDebugLocFrom(), and VPTransformState().
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp