LLVM: llvm::IntrusiveBackListBase Struct Reference
llvm::IntrusiveBackListBase Struct Reference
#include "llvm/CodeGen/DIE.h"
Public Types
using Node = IntrusiveBackListNode
Public Member Functions
bool empty () const
void push_back (Node &N)
void push_front (Node &N)
Public Attributes
Node * Last = nullptr
Detailed Description
Definition at line 532 of file DIE.h.
Member Typedef Documentation
Node
using llvm::IntrusiveBackListBase::Node = IntrusiveBackListNode
Definition at line 533 of file DIE.h.
Member Function Documentation
empty()
bool llvm::IntrusiveBackListBase::empty () const inline
Definition at line 537 of file DIE.h.
References Last.
Referenced by llvm::IntrusiveBackList< Node >::empty().
push_back()
void llvm::IntrusiveBackListBase::push_back (Node & N) inline
Definition at line 539 of file DIE.h.
References assert(), Last, and N.
Referenced by llvm::IntrusiveBackList< Node >::push_back().
push_front()
void llvm::IntrusiveBackListBase::push_front (Node & N) inline
Definition at line 550 of file DIE.h.
References assert(), Last, and N.
Referenced by llvm::IntrusiveBackList< Node >::push_front().
Member Data Documentation
Last
Node* llvm::IntrusiveBackListBase::Last = nullptr
Definition at line 535 of file DIE.h.
Referenced by llvm::IntrusiveBackList< Node >::back(), llvm::IntrusiveBackList< Node >::back(), llvm::IntrusiveBackList< Node >::begin(), llvm::IntrusiveBackList< Node >::deleteNode(), empty(), llvm::IntrusiveBackList< Node >::front(), llvm::IntrusiveBackList< Node >::front(), push_back(), and push_front().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/DIE.h