LLVM: llvm::isa_impl_cl< To, From > Struct Template Reference
llvm::isa_impl_cl< To, From > Struct Template Reference
#include "llvm/Support/Casting.h"
Static Public Member Functions
static bool doit (const From &Val)
Detailed Description
template<typename To, typename From>
struct llvm::isa_impl_cl< To, From >
Definition at line 73 of file Casting.h.
Member Function Documentation
doit()
template<typename To, typename From> static bool llvm::isa_impl_cl< To, From >::doit (const From & Val) inline static
Definition at line 74 of file Casting.h.
References llvm::isa_impl< To, From, Enabler >::doit().
Referenced by llvm::isa_impl_cl< To, const std::unique_ptr< From > >::doit(), and llvm::isa_impl_wrap< To, FromTy, FromTy >::doit().
The documentation for this struct was generated from the following file:
include/llvm/Support/Casting.h