LLVM: llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type Struct Reference
llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type Struct Reference
#include "llvm/ADT/TrieRawHashMap.h"
Public Member Functions
value_type (value_type &&)=default
value_type (const value_type &)=default
value_type (ArrayRef< uint8_t > Hash, const T &Data)
value_type (ArrayRef< uint8_t > Hash, T &&Data)
Public Attributes
const HashT Hash
T Data
Friends
class LazyValueConstructor
Detailed Description
template<class T, size_t NumHashBytes>
struct llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type
Definition at line 187 of file TrieRawHashMap.h.
Constructor & Destructor Documentation
value_type() [1/4]
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::value_type (value_type &&) default
References value_type().
Referenced by value_type(), and value_type().
value_type() [2/4]
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::value_type (const value_type &) default
References value_type().
value_type() [3/4]
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::value_type (ArrayRef< uint8_t > Hash, const T & Data) inline
Definition at line 194 of file TrieRawHashMap.h.
References Data, Hash, and T.
value_type() [4/4]
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::value_type (ArrayRef< uint8_t > Hash, T && Data) inline
Definition at line 196 of file TrieRawHashMap.h.
References Data, Hash, llvm::move(), and T.
Friends And Related Symbol Documentation
LazyValueConstructor
template<class T, size_t NumHashBytes> friend class LazyValueConstructor friend
Definition at line 200 of file TrieRawHashMap.h.
References LazyValueConstructor.
Referenced by LazyValueConstructor.
Member Data Documentation
Data
template<class T, size_t NumHashBytes> T llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::Data
Definition at line 189 of file TrieRawHashMap.h.
Referenced by value_type(), and value_type().
Hash
template<class T, size_t NumHashBytes> const HashT llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::value_type::Hash
Definition at line 188 of file TrieRawHashMap.h.
Referenced by llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::insert(), value_type(), and value_type().
The documentation for this struct was generated from the following file:
include/llvm/ADT/TrieRawHashMap.h