LLVM: llvm::DenseMapInfo< const SwitchSuccWrapper * > Struct Reference
llvm::DenseMapInfo< const SwitchSuccWrapper * > Struct Reference
Static Public Member Functions
static const SwitchSuccWrapper * getEmptyKey ()
static const SwitchSuccWrapper * getTombstoneKey ()
static unsigned getHashValue (const SwitchSuccWrapper *SSW)
static bool isEqual (const SwitchSuccWrapper *LHS, const SwitchSuccWrapper *RHS)
Detailed Description
Definition at line 7506 of file SimplifyCFG.cpp.
Member Function Documentation
getEmptyKey()
static const SwitchSuccWrapper * llvm::DenseMapInfo< const SwitchSuccWrapper * >::getEmptyKey () inline static
Definition at line 7507 of file SimplifyCFG.cpp.
getHashValue()
static unsigned llvm::DenseMapInfo< const SwitchSuccWrapper * >::getHashValue (const SwitchSuccWrapper * SSW) inline static
Definition at line 7515 of file SimplifyCFG.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), SwitchSuccWrapper::Dest, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::BranchInst::getNumSuccessors(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::hash_combine(), llvm::hash_combine_range(), llvm::BranchInst::isUnconditional(), SwitchSuccWrapper::PhiPredIVs, llvm::BasicBlock::phis(), and llvm::BasicBlock::size().
getTombstoneKey()
static const SwitchSuccWrapper * llvm::DenseMapInfo< const SwitchSuccWrapper * >::getTombstoneKey () inline static
Definition at line 7511 of file SimplifyCFG.cpp.
isEqual()
static bool llvm::DenseMapInfo< const SwitchSuccWrapper * >::isEqual (const SwitchSuccWrapper * LHS, const SwitchSuccWrapper * RHS) inline static
Definition at line 7540 of file SimplifyCFG.cpp.
References A(), assert(), B(), llvm::cast(), llvm::BranchInst::getSuccessor(), llvm::BranchInst::isUnconditional(), and llvm::BasicBlock::phis().
The documentation for this struct was generated from the following file:
lib/Transforms/Utils/SimplifyCFG.cpp