LLVM: llvm::CastIsPossible< To, From, Enable > Struct Template Reference
llvm::CastIsPossible< To, From, Enable > Struct Template Reference
This struct provides a way to check if a given cast is possible.
#include "llvm/Support/Casting.h"
Static Public Member Functions
static bool isPossible (const From &f)
Detailed Description
template<typename To, typename From, typename Enable = void>
struct llvm::CastIsPossible< To, From, Enable >
This struct provides a way to check if a given cast is possible.
It provides a static function called isPossible that is used to check if a cast can be performed. It should be overridden like this:
template<> struct CastIsPossible<foo, bar> { static inline bool isPossible(const bar &b) { return bar.isFoo(); } };
Definition at line 253 of file Casting.h.
Member Function Documentation
isPossible()
template<typename To, typename From, typename Enable = void> static bool llvm::CastIsPossible< To, From, Enable >::isPossible (const From & f) inline static
Definition at line 254 of file Casting.h.
Referenced by llvm::CastInfo< To, From, Enable >::doCastIfPossible(), llvm::isa(), llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::isPossible(), and llvm::CastInfo< To, PointerUnion< PTs... > >::isPossible().
The documentation for this struct was generated from the following file:
include/llvm/Support/Casting.h