LLVM: llvm::MachineInstrBundleIteratorHelper< false > Struct Reference
llvm::MachineInstrBundleIteratorHelper< false > Struct Reference
#include "llvm/CodeGen/MachineInstrBundleIterator.h"
Static Public Member Functions
template<class Iterator>
static Iterator getBundleBegin (Iterator I)
Get the beginning of the current bundle.
template<class Iterator>
static Iterator getBundleFinal (Iterator I)
Get the final node of the current bundle.
template<class Iterator>
static void increment (Iterator &I)
Increment forward ilist iterator.
template<class Iterator>
static void decrement (Iterator &I)
Decrement forward ilist iterator.
Detailed Description
Definition at line 51 of file MachineInstrBundleIterator.h.
Member Function Documentation
decrement()
template<class Iterator> static void llvm::MachineInstrBundleIteratorHelper< false >::decrement (Iterator & I) inline static
Decrement forward ilist iterator.
Definition at line 74 of file MachineInstrBundleIterator.h.
References getBundleBegin(), and I.
Referenced by llvm::MachineInstrBundleIterator< MachineInstr >::operator--().
getBundleBegin()
template<class Iterator> static Iterator llvm::MachineInstrBundleIteratorHelper< false >::getBundleBegin (Iterator I) inline static
Get the beginning of the current bundle.
Definition at line 53 of file MachineInstrBundleIterator.h.
References I.
Referenced by decrement().
getBundleFinal()
template<class Iterator> static Iterator llvm::MachineInstrBundleIteratorHelper< false >::getBundleFinal (Iterator I) inline static
Get the final node of the current bundle.
Definition at line 61 of file MachineInstrBundleIterator.h.
References I.
Referenced by increment().
increment()
template<class Iterator> static void llvm::MachineInstrBundleIteratorHelper< false >::increment (Iterator & I) inline static
Increment forward ilist iterator.
Definition at line 69 of file MachineInstrBundleIterator.h.
References getBundleFinal(), and I.
Referenced by llvm::MachineInstrBundleIterator< MachineInstr >::operator++().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineInstrBundleIterator.h