LLVM: llvm::cl::GenericOptionValue Struct Reference
llvm::cl::GenericOptionValue Struct Reference abstract
#include "llvm/Support/CommandLine.h"
Public Member Functions
virtual bool compare (const GenericOptionValue &V) const =0
Protected Member Functions
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Detailed Description
Definition at line 532 of file CommandLine.h.
Constructor & Destructor Documentation
GenericOptionValue() [1/2]
llvm::cl::GenericOptionValue::GenericOptionValue () protected default
Referenced by compare(), llvm::cl::OptionValueBase< DataType, isClass >::compare(), llvm::cl::OptionValueCopy< DataType >::compare(), GenericOptionValue(), and operator=().
GenericOptionValue() [2/2]
llvm::cl::GenericOptionValue::GenericOptionValue (const GenericOptionValue &) protected default
References GenericOptionValue().
~GenericOptionValue()
llvm::cl::GenericOptionValue::~GenericOptionValue () protected default
Member Function Documentation
compare()
virtual bool llvm::cl::GenericOptionValue::compare (const GenericOptionValue & V) const pure virtual
Implemented in llvm::cl::OptionValueBase< DataType, isClass >, llvm::cl::OptionValueBase< bool, std::is_class_v< bool > >, llvm::cl::OptionValueBase< DataType, false >, llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >, llvm::cl::OptionValueCopy< DataType >, llvm::cl::OptionValueCopy< cl::boolOrDefault >, llvm::cl::OptionValueCopy< FnT >, and llvm::cl::OptionValueCopy< std::string >.
References GenericOptionValue().
operator=()
GenericOptionValue & llvm::cl::GenericOptionValue::operator= (const GenericOptionValue &) protected default
References GenericOptionValue().
The documentation for this struct was generated from the following files:
include/llvm/Support/CommandLine.h
lib/Support/CommandLine.cpp