LLVM: llvm::memprof::IndexedCallstackIdConveter Struct Reference
llvm::memprof::IndexedCallstackIdConveter Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
IndexedCallstackIdConveter ()=delete
IndexedCallstackIdConveter (IndexedMemProfData &MemProfData)
IndexedCallstackIdConveter (const IndexedCallstackIdConveter &)=delete
IndexedCallstackIdConveter & operator= (const IndexedCallstackIdConveter &)=delete
std::vector< Frame > operator() (CallStackId CSId)
Public Attributes
FrameIdConverter< decltype(IndexedMemProfData::Frames)> FrameIdConv
CallStackIdConverter< decltype(IndexedMemProfData::CallStacks)> CSIdConv
Detailed Description
Definition at line 1035 of file MemProf.h.
Constructor & Destructor Documentation
IndexedCallstackIdConveter() [1/3]
llvm::memprof::IndexedCallstackIdConveter::IndexedCallstackIdConveter () delete
Referenced by IndexedCallstackIdConveter(), and operator=().
IndexedCallstackIdConveter() [2/3]
llvm::memprof::IndexedCallstackIdConveter::IndexedCallstackIdConveter (IndexedMemProfData & MemProfData) inline
Definition at line 1037 of file MemProf.h.
References CSIdConv, and FrameIdConv.
IndexedCallstackIdConveter() [3/3]
llvm::memprof::IndexedCallstackIdConveter::IndexedCallstackIdConveter (const IndexedCallstackIdConveter &) delete
References IndexedCallstackIdConveter().
Member Function Documentation
operator()()
std::vector< Frame > llvm::memprof::IndexedCallstackIdConveter::operator() (CallStackId CSId) inline
Definition at line 1048 of file MemProf.h.
References CSIdConv.
operator=()
IndexedCallstackIdConveter & llvm::memprof::IndexedCallstackIdConveter::operator= (const IndexedCallstackIdConveter &) delete
References IndexedCallstackIdConveter().
Member Data Documentation
CSIdConv
CallStackIdConverter<decltype(IndexedMemProfData::CallStacks)> llvm::memprof::IndexedCallstackIdConveter::CSIdConv
Definition at line 1051 of file MemProf.h.
Referenced by IndexedCallstackIdConveter(), and operator()().
FrameIdConv
FrameIdConverter<decltype(IndexedMemProfData::Frames)> llvm::memprof::IndexedCallstackIdConveter::FrameIdConv
Definition at line 1050 of file MemProf.h.
Referenced by IndexedCallstackIdConveter().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h