LLVM: OperandInfo Struct Reference
OperandInfo Struct Reference
Represents the EMUL and EEW of a MachineOperand.
Public Member Functions
OperandInfo (RISCVII::VLMUL EMUL, unsigned Log2EEW)
OperandInfo (std::pair< unsigned, bool > EMUL, unsigned Log2EEW)
OperandInfo (unsigned Log2EEW)
OperandInfo ()=delete
void print (raw_ostream &OS) const
Static Public Member Functions
static bool EMULAndEEWAreEqual (const OperandInfo &A, const OperandInfo &B)
static bool EEWAreEqual (const OperandInfo &A, const OperandInfo &B)
Public Attributes
std::optional< std::pair< unsigned, bool > > EMUL
unsigned Log2EEW
Detailed Description
Represents the EMUL and EEW of a MachineOperand.
Definition at line 81 of file RISCVVLOptimizer.cpp.
Constructor & Destructor Documentation
OperandInfo() [1/4]
OperandInfo::OperandInfo (RISCVII::VLMUL EMUL, unsigned Log2EEW) inline
Definition at line 89 of file RISCVVLOptimizer.cpp.
References EMUL, and Log2EEW.
Referenced by EEWAreEqual(), and EMULAndEEWAreEqual().
OperandInfo() [2/4]
OperandInfo::OperandInfo (std::pair< unsigned, bool > EMUL, unsigned Log2EEW) inline
Definition at line 92 of file RISCVVLOptimizer.cpp.
References EMUL, and Log2EEW.
OperandInfo() [3/4]
OperandInfo::OperandInfo (unsigned Log2EEW) inline
Definition at line 95 of file RISCVVLOptimizer.cpp.
References Log2EEW.
OperandInfo() [4/4]
OperandInfo::OperandInfo () delete
Member Function Documentation
EEWAreEqual()
static bool OperandInfo::EEWAreEqual (const OperandInfo & A, const OperandInfo & B) inline static
Definition at line 104 of file RISCVVLOptimizer.cpp.
References A(), B(), and OperandInfo().
EMULAndEEWAreEqual()
static bool OperandInfo::EMULAndEEWAreEqual (const OperandInfo & A, const OperandInfo & B) inline static
Definition at line 99 of file RISCVVLOptimizer.cpp.
References A(), B(), and OperandInfo().
print()
void OperandInfo::print (raw_ostream & OS) const inline
Definition at line 108 of file RISCVVLOptimizer.cpp.
References EMUL, and Log2EEW.
Referenced by operator<<().
Member Data Documentation
EMUL
std::optional<std::pair<unsigned, bool> > OperandInfo::EMUL
Definition at line 85 of file RISCVVLOptimizer.cpp.
Referenced by OperandInfo(), OperandInfo(), and print().
Log2EEW
unsigned OperandInfo::Log2EEW
Definition at line 87 of file RISCVVLOptimizer.cpp.
Referenced by OperandInfo(), OperandInfo(), OperandInfo(), and print().
The documentation for this struct was generated from the following file:
lib/Target/RISCV/RISCVVLOptimizer.cpp