LLVM: llvm::opt::OptTable::Info Struct Reference
llvm::opt::OptTable::Info Struct Reference
Entry for a single option instance in the option data table.
#include "llvm/Option/OptTable.h"
Public Member Functions
bool hasNoPrefix () const
unsigned getNumPrefixes (ArrayRef< StringTable::Offset > PrefixesTable) const
ArrayRef< StringTable::Offset > getPrefixOffsets (ArrayRef< StringTable::Offset > PrefixesTable) const
void appendPrefixes (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, SmallVectorImpl< StringRef > &Prefixes) const
StringRef getPrefix (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, unsigned PrefixIndex) const
StringRef getPrefixedName (const StringTable &StrTable) const
StringRef getName (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable) const
Public Attributes
unsigned PrefixesOffset
StringTable::Offset PrefixedNameOffset
const char * HelpText
std::array< std::pair< std::array< unsigned int, 2 >, const char * >, 1 > HelpTextsForVariants
const char * MetaVar
unsigned ID
unsigned char Kind
unsigned char Param
unsigned int Flags
unsigned int Visibility
unsigned short GroupID
unsigned short AliasID
const char * AliasArgs
const char * Values
Detailed Description
Entry for a single option instance in the option data table.
Definition at line 56 of file OptTable.h.
Member Function Documentation
appendPrefixes()
void llvm::opt::OptTable::Info::appendPrefixes (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable, SmallVectorImpl< StringRef > & Prefixes) const inline
Definition at line 96 of file OptTable.h.
References getPrefixOffsets(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getName()
StringRef llvm::opt::OptTable::Info::getName (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable) const inline
Definition at line 113 of file OptTable.h.
References llvm::StringRef::drop_front(), getPrefix(), getPrefixedName(), hasNoPrefix(), and llvm::StringRef::size().
getNumPrefixes()
unsigned llvm::opt::OptTable::Info::getNumPrefixes (ArrayRef< StringTable::Offset > PrefixesTable) const inline
Definition at line 84 of file OptTable.h.
References PrefixesOffset.
Referenced by getPrefixOffsets().
getPrefix()
StringRef llvm::opt::OptTable::Info::getPrefix (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable, unsigned PrefixIndex) const inline
Definition at line 103 of file OptTable.h.
References getPrefixOffsets().
Referenced by getName().
getPrefixedName()
StringRef llvm::opt::OptTable::Info::getPrefixedName (const StringTable & StrTable) const inline
Definition at line 109 of file OptTable.h.
References PrefixedNameOffset.
Referenced by getName().
getPrefixOffsets()
ArrayRef< StringTable::Offset > llvm::opt::OptTable::Info::getPrefixOffsets (ArrayRef< StringTable::Offset > PrefixesTable) const inline
Definition at line 90 of file OptTable.h.
References llvm::ArrayRef(), getNumPrefixes(), hasNoPrefix(), and PrefixesOffset.
Referenced by appendPrefixes(), llvm::opt::GenericOptTable::GenericOptTable(), and getPrefix().
hasNoPrefix()
bool llvm::opt::OptTable::Info::hasNoPrefix () const inline
Definition at line 82 of file OptTable.h.
References PrefixesOffset.
Referenced by getName(), and getPrefixOffsets().
Member Data Documentation
AliasArgs
const char* llvm::opt::OptTable::Info::AliasArgs
Definition at line 79 of file OptTable.h.
AliasID
unsigned short llvm::opt::OptTable::Info::AliasID
Definition at line 78 of file OptTable.h.
Flags
unsigned int llvm::opt::OptTable::Info::Flags
Definition at line 75 of file OptTable.h.
Referenced by llvm::opt::OptTable::findNearest(), and llvm::opt::OptTable::printHelp().
GroupID
unsigned short llvm::opt::OptTable::Info::GroupID
Definition at line 77 of file OptTable.h.
HelpText
const char* llvm::opt::OptTable::Info::HelpText
Definition at line 59 of file OptTable.h.
Referenced by llvm::opt::OptTable::getOptionHelpText().
HelpTextsForVariants
std::array<std::pair<std::array<unsigned int, 2 >, const char *>, 1 > llvm::opt::OptTable::Info::HelpTextsForVariants
Definition at line 70 of file OptTable.h.
Referenced by llvm::opt::OptTable::getOptionHelpText().
ID
unsigned llvm::opt::OptTable::Info::ID
Definition at line 72 of file OptTable.h.
Kind
unsigned char llvm::opt::OptTable::Info::Kind
Definition at line 73 of file OptTable.h.
MetaVar
const char* llvm::opt::OptTable::Info::MetaVar
Definition at line 71 of file OptTable.h.
Param
unsigned char llvm::opt::OptTable::Info::Param
Definition at line 74 of file OptTable.h.
PrefixedNameOffset
StringTable::Offset llvm::opt::OptTable::Info::PrefixedNameOffset
Definition at line 58 of file OptTable.h.
Referenced by getPrefixedName().
PrefixesOffset
unsigned llvm::opt::OptTable::Info::PrefixesOffset
Definition at line 57 of file OptTable.h.
Referenced by getNumPrefixes(), getPrefixOffsets(), and hasNoPrefix().
Values
const char* llvm::opt::OptTable::Info::Values
Definition at line 80 of file OptTable.h.
Visibility
unsigned int llvm::opt::OptTable::Info::Visibility
Definition at line 76 of file OptTable.h.
Referenced by llvm::opt::OptTable::findNearest(), and llvm::opt::OptTable::printHelp().
The documentation for this struct was generated from the following file:
include/llvm/Option/OptTable.h