LLVM: llvm::TypeSanitizerPass Struct Reference
llvm::TypeSanitizerPass Struct Reference
#include "llvm/Transforms/Instrumentation/TypeSanitizer.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< TypeSanitizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< TypeSanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file TypeSanitizer.h.
Member Function Documentation
isRequired()
static bool llvm::TypeSanitizerPass::isRequired () inline static
Definition at line 25 of file TypeSanitizer.h.
run()
PreservedAnalyses TypeSanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 882 of file TypeSanitizer.cpp.
References llvm::appendToGlobalCtors(), llvm::createSanitizerCtorAndInitFunctions(), F, FAM, kTysanInitName, kTysanModuleCtorName, MAM, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/TypeSanitizer.h
lib/Transforms/Instrumentation/TypeSanitizer.cpp