LLVM: llvm::GraphTraits< ValueInfo > Struct Reference
llvm::GraphTraits< ValueInfo > Struct Reference
GraphTraits definition to build SCC for the index.
#include "llvm/IR/ModuleSummaryIndex.h"
Public Types
typedef ValueInfo NodeRef
using EdgeRef = FunctionSummary::EdgeTy &
using ChildIteratorType
using ChildEdgeIteratorType
using NodeRef
Static Public Member Functions
static NodeRef valueInfoFromEdge (FunctionSummary::EdgeTy &P)
static NodeRef getEntryNode (ValueInfo V)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
static NodeRef edge_dest (EdgeRef E)
Detailed Description
GraphTraits definition to build SCC for the index.
Definition at line 1923 of file ModuleSummaryIndex.h.
Member Typedef Documentation
ChildEdgeIteratorType
using llvm::GraphTraits< ValueInfo >::ChildEdgeIteratorType
Initial value:
      SmallVector<FunctionSummary::EdgeTy, 0>::iterator
Definition at line 1934 of file ModuleSummaryIndex.h.
ChildIteratorType
using llvm::GraphTraits< ValueInfo >::ChildIteratorType
Initial value:
      mapped_iterator<SmallVector<FunctionSummary::EdgeTy, 0>::iterator,
                      decltype(&valueInfoFromEdge)>
Definition at line 1930 of file ModuleSummaryIndex.h.
EdgeRef
using llvm::GraphTraits< ValueInfo >::EdgeRef = FunctionSummary::EdgeTy &
Definition at line 1925 of file ModuleSummaryIndex.h.
NodeRef [1/2]
using llvm::GraphTraits< ValueInfo >::NodeRef
Definition at line 95 of file GraphTraits.h.
NodeRef [2/2]
typedef ValueInfo llvm::GraphTraits< ValueInfo >::NodeRef
Definition at line 1924 of file ModuleSummaryIndex.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< ValueInfo >::child_begin (NodeRef N) inline static
Definition at line 1939 of file ModuleSummaryIndex.h.
References llvm::cast(), llvm::FunctionSummary::ExternalNode, F, N, and valueInfoFromEdge().
child_edge_begin()
static ChildEdgeIteratorType llvm::GraphTraits< ValueInfo >::child_edge_begin (NodeRef N) inline static
Definition at line 1959 of file ModuleSummaryIndex.h.
References llvm::cast(), llvm::FunctionSummary::ExternalNode, F, and N.
child_edge_end()
static ChildEdgeIteratorType llvm::GraphTraits< ValueInfo >::child_edge_end (NodeRef N) inline static
Definition at line 1968 of file ModuleSummaryIndex.h.
References llvm::cast(), llvm::FunctionSummary::ExternalNode, F, and N.
child_end()
static ChildIteratorType llvm::GraphTraits< ValueInfo >::child_end (NodeRef N) inline static
Definition at line 1949 of file ModuleSummaryIndex.h.
References llvm::cast(), llvm::FunctionSummary::ExternalNode, F, N, and valueInfoFromEdge().
edge_dest()
static NodeRef llvm::GraphTraits< ValueInfo >::edge_dest (EdgeRef E) inline static
Definition at line 1977 of file ModuleSummaryIndex.h.
References E().
getEntryNode()
static NodeRef llvm::GraphTraits< ValueInfo >::getEntryNode (ValueInfo V) inline static
Definition at line 1937 of file ModuleSummaryIndex.h.
valueInfoFromEdge()
static NodeRef llvm::GraphTraits< ValueInfo >::valueInfoFromEdge (FunctionSummary::EdgeTy & P) inline static
Definition at line 1927 of file ModuleSummaryIndex.h.
References P.
Referenced by child_begin(), and child_end().
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h