LLVM: llvm::VPlanPatternMatch::specific_intval< BitWidth > Struct Template Reference
llvm::VPlanPatternMatch::specific_intval< BitWidth > Struct Template Reference
Match a specified integer value or vector of all elements of that value.
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
specific_intval (APInt V)
bool match (VPValue *VPV) const
Public Attributes
APInt Val
Detailed Description
template<unsigned BitWidth = 0>
struct llvm::VPlanPatternMatch::specific_intval< BitWidth >
Match a specified integer value or vector of all elements of that value.
BitWidth optionally specifies the bitwidth the matched constant must have. If it is 0, the matched constant can have any bitwidth.
Definition at line 72 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
specific_intval()
template<unsigned BitWidth = 0> llvm::VPlanPatternMatch::specific_intval< BitWidth >::specific_intval (APInt V) inline
Definition at line 75 of file VPlanPatternMatch.h.
References llvm::move(), and Val.
Member Function Documentation
match()
template<unsigned BitWidth = 0> bool llvm::VPlanPatternMatch::specific_intval< BitWidth >::match (VPValue * VPV) const inline
Definition at line 77 of file VPlanPatternMatch.h.
References llvm::BitWidth, llvm::CallingConv::C, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::VPValue::getLiveInIRValue(), llvm::VPValue::isLiveIn(), llvm::APInt::isSameValue(), and Val.
Member Data Documentation
Val
template<unsigned BitWidth = 0> APInt llvm::VPlanPatternMatch::specific_intval< BitWidth >::Val
Definition at line 73 of file VPlanPatternMatch.h.
Referenced by match(), and specific_intval().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h