LLVM: llvm::orc::MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB > Struct Reference
llvm::orc::MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB > Struct Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Public Member Functions
MachOBuilderLoadCommand (std::string Name, uint32_t Timestamp, uint32_t CurrentVersion, uint32_t CompatibilityVersion)
size_t write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) override
MachOBuilderLoadCommand ()=default
MachOBuilderLoadCommand (ArgTs &&...Args)
Public Attributes
std::string Name
Detailed Description
Definition at line 108 of file MachOBuilder.h.
Constructor & Destructor Documentation
MachOBuilderLoadCommand() [1/3]
llvm::orc::MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB >::MachOBuilderLoadCommand (std::string Name, uint32_t Timestamp, uint32_t CurrentVersion, uint32_t CompatibilityVersion) inline
Definition at line 111 of file MachOBuilder.h.
References llvm::move(), and Name.
MachOBuilderLoadCommand() [2/3]
llvm::orc::MachOBuilderLoadCommand< LCType >::MachOBuilderLoadCommand () default
MachOBuilderLoadCommand() [3/3]
llvm::orc::MachOBuilderLoadCommand< LCType >::MachOBuilderLoadCommand (ArgTs &&... Args) inline
Definition at line 80 of file MachOBuilder.h.
Member Function Documentation
write()
size_t llvm::orc::MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB >::write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) inline override
Definition at line 120 of file MachOBuilder.h.
References llvm::MutableArrayRef< T >::data(), Name, llvm::Offset, and llvm::orc::writeMachOStruct().
Member Data Documentation
Name
std::string llvm::orc::MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB >::Name
Definition at line 127 of file MachOBuilder.h.
Referenced by MachOBuilderLoadCommand(), and write().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h