LLVM: llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > > Struct Template Reference
llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > > Struct Template Reference
This struct provides an overload for CastInfo where From has simplify_type defined.
#include "llvm/Support/Casting.h"
Public Types
using Self = CastInfo<To, From>
using SimpleFrom = typename simplify_type<From>::SimpleType
using SimplifiedSelf = CastInfo<To, SimpleFrom>
using Self
using CastReturnType
Static Public Member Functions
static bool isPossible (From &f)
static decltype(auto) doCast (From &f)
static decltype(auto) castFailed ()
static decltype(auto) doCastIfPossible (From &f)
static CastReturnType doCast (const From &f)
static CastReturnType castFailed ()
static CastReturnType doCastIfPossible (const From &f)
Static Public Member Functions inherited from llvm::CastIsPossible< To, From, Enable >
static bool isPossible (const From &f)
Detailed Description
template<typename To, typename From>
struct llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >
This struct provides an overload for CastInfo where From has simplify_type defined.
This simply forwards to the appropriate CastInfo with the simplified type/value, so you don't have to implement both.
Definition at line 503 of file Casting.h.
Member Typedef Documentation
CastReturnType
using llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::CastReturnType
Definition at line 479 of file Casting.h.
Self [1/2]
using llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::Self
Definition at line 477 of file Casting.h.
Self [2/2]
template<typename To, typename From> using llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::Self = CastInfo<To, From>
Definition at line 504 of file Casting.h.
SimpleFrom
template<typename To, typename From> using llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::SimpleFrom = typename simplify_type<From>::SimpleType
Definition at line 505 of file Casting.h.
SimplifiedSelf
template<typename To, typename From> using llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::SimplifiedSelf = CastInfo<To, SimpleFrom>
Definition at line 506 of file Casting.h.
Member Function Documentation
castFailed() [1/2]
static CastReturnType llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::castFailed () inline static
Definition at line 490 of file Casting.h.
castFailed() [2/2]
template<typename To, typename From> static decltype(auto) llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::castFailed () inline static
Definition at line 517 of file Casting.h.
References llvm::CastInfo< To, SimpleFrom >::castFailed().
doCast() [1/2]
static CastReturnType llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCast (const From & f) inline static
Definition at line 481 of file Casting.h.
doCast() [2/2]
template<typename To, typename From> static decltype(auto) llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCast (From & f) inline static
Definition at line 513 of file Casting.h.
References llvm::CastInfo< To, SimpleFrom >::doCast(), and llvm::simplify_type< From >::getSimplifiedValue().
doCastIfPossible() [1/2]
static CastReturnType llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCastIfPossible (const From & f) inline static
Definition at line 492 of file Casting.h.
doCastIfPossible() [2/2]
template<typename To, typename From> static decltype(auto) llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::doCastIfPossible (From & f) inline static
Definition at line 521 of file Casting.h.
References llvm::CastInfo< To, SimpleFrom >::doCastIfPossible(), and llvm::simplify_type< From >::getSimplifiedValue().
isPossible()
template<typename To, typename From> static bool llvm::CastInfo< To, From, std::enable_if_t<!is_simple_type< From >::value > >::isPossible (From & f) inline static
Definition at line 508 of file Casting.h.
References llvm::simplify_type< From >::getSimplifiedValue(), and llvm::CastIsPossible< To, From, Enable >::isPossible().
The documentation for this struct was generated from the following file:
include/llvm/Support/Casting.h