LLVM: llvm::isa_impl< To, From, Enabler > Struct Template Reference
llvm::isa_impl< To, From, Enabler > Struct Template Reference
#include "llvm/Support/Casting.h"
Static Public Member Functions
static bool doit (const From &Val)
Detailed Description
template<typename To, typename From, typename Enabler = void>
struct llvm::isa_impl< To, From, Enabler >
Definition at line 63 of file Casting.h.
Member Function Documentation
doit()
template<typename To, typename From, typename Enabler = void> static bool llvm::isa_impl< To, From, Enabler >::doit (const From & Val) inline static
Definition at line 64 of file Casting.h.
Referenced by llvm::isa_impl_cl< To, From >::doit(), llvm::isa_impl_cl< To, const From * >::doit(), llvm::isa_impl_cl< To, const From *const >::doit(), llvm::isa_impl_cl< To, const From >::doit(), llvm::isa_impl_cl< To, From * >::doit(), and llvm::isa_impl_cl< To, From *const >::doit().
The documentation for this struct was generated from the following file:
include/llvm/Support/Casting.h