LLVM: llvm::GraphTraits< MachineRegionInfo * > Struct Reference
llvm::GraphTraits< MachineRegionInfo * > Struct Reference
#include "llvm/CodeGen/MachineRegionInfo.h"
Public Types
using nodes_iterator
using NodeRef
Public Types inherited from llvm::GraphTraits< FlatIt< MachineRegionNode * > >
using NodeRef
Static Public Member Functions
static NodeRef getEntryNode (MachineRegionInfo *RI)
static nodes_iterator nodes_begin (MachineRegionInfo *RI)
static nodes_iterator nodes_end (MachineRegionInfo *RI)
Detailed Description
Definition at line 137 of file MachineRegionInfo.h.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< MachineRegionInfo * >::NodeRef
Definition at line 95 of file GraphTraits.h.
nodes_iterator
using llvm::GraphTraits< MachineRegionInfo * >::nodes_iterator
Initial value:
 df_iterator<NodeRef, df_iterator_default_set<NodeRef>,
                                     false, GraphTraits<FlatIt<NodeRef>>>
Definition at line 139 of file MachineRegionInfo.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< MachineRegionInfo * >::getEntryNode (MachineRegionInfo * RI) inline static
Definition at line 142 of file MachineRegionInfo.h.
References getEntryNode(), and llvm::RegionInfoBase< Tr >::getTopLevelRegion().
Referenced by getEntryNode(), nodes_begin(), and nodes_end().
nodes_begin()
static nodes_iterator llvm::GraphTraits< MachineRegionInfo * >::nodes_begin (MachineRegionInfo * RI) inline static
Definition at line 147 of file MachineRegionInfo.h.
References llvm::df_iterator< NodeRef, df_iterator_default_set< NodeRef >, false, GraphTraits< FlatIt< NodeRef > > >::begin(), and getEntryNode().
nodes_end()
static nodes_iterator llvm::GraphTraits< MachineRegionInfo * >::nodes_end (MachineRegionInfo * RI) inline static
Definition at line 151 of file MachineRegionInfo.h.
References llvm::df_iterator< NodeRef, df_iterator_default_set< NodeRef >, false, GraphTraits< FlatIt< NodeRef > > >::end(), and getEntryNode().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineRegionInfo.h