LLVM: llvm::AMDGPU::PredicateMapping Struct Reference
llvm::AMDGPU::PredicateMapping Struct Reference
#include "Target/AMDGPU/AMDGPURegBankLegalizeRules.h"
Public Member Functions
PredicateMapping (std::initializer_list< UniformityLLTOpPredicateID > OpList, std::function< bool(const MachineInstr &)> TestFunc=nullptr)
bool match (const MachineInstr &MI, const MachineUniformityInfo &MUI, const MachineRegisterInfo &MRI) const
Public Attributes
SmallVector< UniformityLLTOpPredicateID, 4 > OpUniformityAndTypes
std::function< bool(const MachineInstr &)> TestFunc
Detailed Description
Definition at line 191 of file AMDGPURegBankLegalizeRules.h.
Constructor & Destructor Documentation
PredicateMapping()
PredicateMapping::PredicateMapping (std::initializer_list< UniformityLLTOpPredicateID > OpList, std::function< bool(const MachineInstr &)> TestFunc = nullptr)
Definition at line 36 of file AMDGPURegBankLegalizeRules.cpp.
References OpUniformityAndTypes, and TestFunc.
Member Function Documentation
match()
bool PredicateMapping::match (const MachineInstr & MI, const MachineUniformityInfo & MUI, const MachineRegisterInfo & MRI) const
Definition at line 134 of file AMDGPURegBankLegalizeRules.cpp.
References llvm::AMDGPU::_, matchUniformityAndLLT(), MI, MRI, OpUniformityAndTypes, and TestFunc.
Member Data Documentation
OpUniformityAndTypes
SmallVector<UniformityLLTOpPredicateID, 4> llvm::AMDGPU::PredicateMapping::OpUniformityAndTypes
Definition at line 192 of file AMDGPURegBankLegalizeRules.h.
Referenced by match(), and PredicateMapping().
TestFunc
std::function<bool(const MachineInstr &)> llvm::AMDGPU::PredicateMapping::TestFunc
Definition at line 193 of file AMDGPURegBankLegalizeRules.h.
Referenced by match(), and PredicateMapping().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPURegBankLegalizeRules.h
lib/Target/AMDGPU/AMDGPURegBankLegalizeRules.cpp