LLVM: llvm::AMDGPUPerfHintAnalysisPass Struct Reference
llvm::AMDGPUPerfHintAnalysisPass Struct Reference
#include "Target/AMDGPU/AMDGPUPerfHintAnalysis.h"
Public Member Functions
AMDGPUPerfHintAnalysisPass (const GCNTargetMachine &TM)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUPerfHintAnalysisPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Attributes
const GCNTargetMachine & TM
std::unique_ptr< AMDGPUPerfHintAnalysis > Impl
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUPerfHintAnalysisPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 64 of file AMDGPUPerfHintAnalysis.h.
Constructor & Destructor Documentation
AMDGPUPerfHintAnalysisPass()
llvm::AMDGPUPerfHintAnalysisPass::AMDGPUPerfHintAnalysisPass (const GCNTargetMachine & TM) inline
Definition at line 69 of file AMDGPUPerfHintAnalysis.h.
References Impl, and TM.
Member Function Documentation
run()
PreservedAnalyses AMDGPUPerfHintAnalysisPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 482 of file AMDGPUPerfHintAnalysis.cpp.
References llvm::PreservedAnalyses::all(), Changed, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), Impl, llvm::PreservedAnalyses::preserve(), and TM.
Member Data Documentation
Impl
std::unique_ptr<AMDGPUPerfHintAnalysis> llvm::AMDGPUPerfHintAnalysisPass::Impl
Definition at line 67 of file AMDGPUPerfHintAnalysis.h.
Referenced by AMDGPUPerfHintAnalysisPass(), and run().
TM
const GCNTargetMachine& llvm::AMDGPUPerfHintAnalysisPass::TM
Definition at line 66 of file AMDGPUPerfHintAnalysis.h.
Referenced by AMDGPUPerfHintAnalysisPass(), and run().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPUPerfHintAnalysis.h
lib/Target/AMDGPU/AMDGPUPerfHintAnalysis.cpp