LLVM: llvm::telemetry::TelemetryInfo Struct Reference
llvm::telemetry::TelemetryInfo Struct Reference
TelemetryInfo is the data courier, used to move instrumented data from the tool being monitored to the Telemetry framework.
#include "llvm/Telemetry/Telemetry.h"
Public Member Functions
TelemetryInfo ()=default
virtual ~TelemetryInfo ()=default
virtual void serialize (Serializer &serializer) const
virtual KindType getKind () const
Static Public Member Functions
static bool classof (const TelemetryInfo *T)
Public Attributes
std::string SessionId
Detailed Description
TelemetryInfo is the data courier, used to move instrumented data from the tool being monitored to the Telemetry framework.
This base class contains only the basic set of telemetry data. Downstream implementations can define more subclasses with additional fields to describe different events and concepts.
For example, The LLDB debugger can define a DebugCommandInfo subclass which has additional fields about the debug-command being instrumented, such as CommandArguments or CommandName.
Definition at line 97 of file Telemetry.h.
Constructor & Destructor Documentation
TelemetryInfo()
llvm::telemetry::TelemetryInfo::TelemetryInfo () default
Referenced by classof().
~TelemetryInfo()
virtual llvm::telemetry::TelemetryInfo::~TelemetryInfo () virtual default
Member Function Documentation
classof()
static bool llvm::telemetry::TelemetryInfo::classof (const TelemetryInfo * T) inline static
Definition at line 115 of file Telemetry.h.
References llvm::telemetry::EntryKind::Base, T, and TelemetryInfo().
getKind()
virtual KindType llvm::telemetry::TelemetryInfo::getKind () const inline virtual
Definition at line 114 of file Telemetry.h.
References llvm::telemetry::EntryKind::Base.
serialize()
void llvm::telemetry::TelemetryInfo::serialize (Serializer & serializer) const virtual
Definition at line 6 of file Telemetry.cpp.
References SessionId, and llvm::telemetry::Serializer::write().
Member Data Documentation
SessionId
std::string llvm::telemetry::TelemetryInfo::SessionId
Definition at line 106 of file Telemetry.h.
Referenced by serialize().
The documentation for this struct was generated from the following files:
include/llvm/Telemetry/Telemetry.h
lib/Telemetry/Telemetry.cpp