LLVM: llvm::ilist_detail::NodeAccess Struct Reference
llvm::ilist_detail::NodeAccess Struct Reference
An access class for ilist_node private API.
#include "llvm/ADT/ilist_node.h"
Static Protected Member Functions
template<class OptionsT>
static ilist_node_impl< OptionsT > * getNodePtr (typename OptionsT::pointer N)
template<class OptionsT>
static const ilist_node_impl< OptionsT > * getNodePtr (typename OptionsT::const_pointer N)
template<class OptionsT>
static OptionsT::pointer getValuePtr (ilist_node_impl< OptionsT > *N)
template<class OptionsT>
static OptionsT::const_pointer getValuePtr (const ilist_node_impl< OptionsT > *N)
template<class OptionsT>
static ilist_node_impl< OptionsT > * getPrev (ilist_node_impl< OptionsT > &N)
template<class OptionsT>
static ilist_node_impl< OptionsT > * getNext (ilist_node_impl< OptionsT > &N)
template<class OptionsT>
static const ilist_node_impl< OptionsT > * getPrev (const ilist_node_impl< OptionsT > &N)
template<class OptionsT>
static const ilist_node_impl< OptionsT > * getNext (const ilist_node_impl< OptionsT > &N)
Detailed Description
An access class for ilist_node private API.
This gives access to the private parts of ilist nodes. Nodes for an ilist should friend this class if they inherit privately from ilist_node.
Using this class outside of the ilist implementation is unsupported.
Definition at line 228 of file ilist_node.h.
Member Function Documentation
getNext() [1/2]
template<class OptionsT> static const ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getNext (const ilist_node_impl< OptionsT > & N) inline static protected
Definition at line 270 of file ilist_node.h.
References N.
getNext() [2/2]
template<class OptionsT> static ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getNext (ilist_node_impl< OptionsT > & N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-20.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 258 of file ilist_node.h.
References N.
Referenced by llvm::ilist_detail::IteratorHelper< true >::decrement(), and llvm::ilist_detail::IteratorHelper< false >::increment().
getNodePtr() [1/2]
template<class OptionsT> static const ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getNodePtr (typename OptionsT::const_pointer N) inline static protected
Definition at line 237 of file ilist_node.h.
References N.
getNodePtr() [2/2]
template<class OptionsT> static ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getNodePtr (typename OptionsT::pointer N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-20.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 231 of file ilist_node.h.
References N.
Referenced by llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getNodePtr(), and llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getNodePtr().
getPrev() [1/2]
template<class OptionsT> static const ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getPrev (const ilist_node_impl< OptionsT > & N) inline static protected
Definition at line 264 of file ilist_node.h.
References N.
getPrev() [2/2]
template<class OptionsT> static ilist_node_impl< OptionsT > * llvm::ilist_detail::NodeAccess::getPrev (ilist_node_impl< OptionsT > & N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-20.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 253 of file ilist_node.h.
References N.
Referenced by llvm::ilist_detail::IteratorHelper< false >::decrement(), and llvm::ilist_detail::IteratorHelper< true >::increment().
getValuePtr() [1/2]
template<class OptionsT> static OptionsT::const_pointer llvm::ilist_detail::NodeAccess::getValuePtr (const ilist_node_impl< OptionsT > * N) inline static protected
Definition at line 248 of file ilist_node.h.
References N.
getValuePtr() [2/2]
template<class OptionsT> static OptionsT::pointer llvm::ilist_detail::NodeAccess::getValuePtr (ilist_node_impl< OptionsT > * N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-20.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 242 of file ilist_node.h.
References N.
Referenced by llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getValuePtr(), and llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getValuePtr().
The documentation for this struct was generated from the following file:
include/llvm/ADT/ilist_node.h