LLVM: llvm::gsym::CallSiteInfo Struct Reference
llvm::gsym::CallSiteInfo Struct Reference
#include "llvm/DebugInfo/GSYM/CallSiteInfo.h"
Public Types
enum Flags : uint8_t { None = 0 , InternalCall = 1 << 0 , ExternalCall = 1 << 1 , LLVM_MARK_AS_BITMASK_ENUM =(ExternalCall) }
Public Member Functions
bool operator== (const CallSiteInfo &RHS) const
Equality comparison operator for CallSiteInfo.
bool operator!= (const CallSiteInfo &RHS) const
Inequality comparison operator for CallSiteInfo.
llvm::Error encode (FileWriter &O) const
Encode this CallSiteInfo object into a FileWriter stream.
Static Public Member Functions
static llvm::Expected< CallSiteInfo > decode (DataExtractor &Data, uint64_t &Offset)
Decode a CallSiteInfo object from a binary data stream.
Public Attributes
uint64_t ReturnOffset = 0
The return offset of the call site - relative to the function start.
std::vector< uint32_t > MatchRegex
Offsets into the string table for function names regex patterns.
uint8_t Flags = CallSiteInfo::Flags::None
Bitwise OR of CallSiteInfo::Flags values.
Detailed Description
Definition at line 30 of file CallSiteInfo.h.
Member Enumeration Documentation
Flags
enum llvm::gsym::CallSiteInfo::Flags : uint8_t
Enumerator
None
InternalCall
ExternalCall
LLVM_MARK_AS_BITMASK_ENUM
Definition at line 31 of file CallSiteInfo.h.
Member Function Documentation
decode()
Expected< CallSiteInfo > CallSiteInfo::decode (DataExtractor & Data, uint64_t & Offset) static
Decode a CallSiteInfo object from a binary data stream.
Parameters
Data The binary stream to read the data from.
Offset The current offset within the data stream.
Returns
A CallSiteInfo or an error describing the issue.
Definition at line 36 of file CallSiteInfo.cpp.
References llvm::createStringError(), llvm::Data, MatchRegex, llvm::Offset, and ReturnOffset.
Referenced by llvm::gsym::CallSiteInfoCollection::decode().
encode()
Error CallSiteInfo::encode (FileWriter & O) const
Encode this CallSiteInfo object into a FileWriter stream.
Parameters
O The binary stream to write the data to.
Returns
An error object that indicates success or failure.
Definition at line 27 of file CallSiteInfo.cpp.
References encode(), MatchRegex, ReturnOffset, and llvm::Error::success().
Referenced by encode().
operator!=()
bool llvm::gsym::CallSiteInfo::operator!= (const CallSiteInfo & RHS) const inline
Inequality comparison operator for CallSiteInfo.
Definition at line 59 of file CallSiteInfo.h.
References RHS.
operator==()
bool llvm::gsym::CallSiteInfo::operator== (const CallSiteInfo & RHS) const inline
Equality comparison operator for CallSiteInfo.
Definition at line 53 of file CallSiteInfo.h.
References MatchRegex, ReturnOffset, and RHS.
Member Data Documentation
Flags
uint8_t llvm::gsym::CallSiteInfo::Flags = CallSiteInfo::Flags::None
Bitwise OR of CallSiteInfo::Flags values.
Definition at line 50 of file CallSiteInfo.h.
MatchRegex
std::vector<uint32_t> llvm::gsym::CallSiteInfo::MatchRegex
Offsets into the string table for function names regex patterns.
Definition at line 47 of file CallSiteInfo.h.
Referenced by decode(), llvm::gsym::GsymReader::dump(), encode(), llvm::gsym::operator<<(), and operator==().
ReturnOffset
uint64_t llvm::gsym::CallSiteInfo::ReturnOffset = 0
The return offset of the call site - relative to the function start.
Definition at line 44 of file CallSiteInfo.h.
Referenced by decode(), llvm::gsym::GsymReader::dump(), encode(), llvm::gsym::operator<<(), and operator==().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/GSYM/CallSiteInfo.h
lib/DebugInfo/GSYM/CallSiteInfo.cpp