LLVM: llvm::indent Struct Reference
llvm::indent Struct Reference
#include "llvm/Support/raw_ostream.h"
Public Member Functions
indent (unsigned NumIndents, unsigned Scale=1)
void operator+= (unsigned N)
void operator-= (unsigned N)
indent operator+ (unsigned N) const
indent operator- (unsigned N) const
indent & operator++ ()
indent operator++ (int)
indent & operator-- ()
indent operator-- (int)
indent & operator= (unsigned N)
Public Attributes
unsigned NumIndents
unsigned Scale
Detailed Description
Definition at line 781 of file raw_ostream.h.
Constructor & Destructor Documentation
indent()
llvm::indent::indent (unsigned NumIndents, unsigned Scale = 1) inline explicit
Definition at line 786 of file raw_ostream.h.
References NumIndents, and Scale.
Referenced by operator+(), operator++(), operator++(), operator-(), operator--(), operator--(), and operator=().
Member Function Documentation
operator+()
indent llvm::indent::operator+ (unsigned N) const inline
Definition at line 795 of file raw_ostream.h.
References indent(), N, NumIndents, and Scale.
operator++() [1/2]
indent & llvm::indent::operator++ () inline
Definition at line 800 of file raw_ostream.h.
References indent(), and NumIndents.
operator++() [2/2]
indent llvm::indent::operator++ (int) inline
Definition at line 804 of file raw_ostream.h.
References indent(), and NumIndents.
operator+=()
void llvm::indent::operator+= (unsigned N) inline
Definition at line 790 of file raw_ostream.h.
References N, and NumIndents.
operator-()
indent llvm::indent::operator- (unsigned N) const inline
Definition at line 796 of file raw_ostream.h.
References assert(), indent(), N, NumIndents, and Scale.
operator--() [1/2]
indent & llvm::indent::operator-- () inline
Definition at line 809 of file raw_ostream.h.
References assert(), indent(), and NumIndents.
operator--() [2/2]
indent llvm::indent::operator-- (int) inline
Definition at line 814 of file raw_ostream.h.
References assert(), indent(), and NumIndents.
operator-=()
void llvm::indent::operator-= (unsigned N) inline
Definition at line 791 of file raw_ostream.h.
References assert(), N, and NumIndents.
operator=()
indent & llvm::indent::operator= (unsigned N) inline
Definition at line 820 of file raw_ostream.h.
References indent(), N, and NumIndents.
Member Data Documentation
NumIndents
unsigned llvm::indent::NumIndents
Definition at line 783 of file raw_ostream.h.
Referenced by indent(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), llvm::operator<<(), and operator=().
Scale
unsigned llvm::indent::Scale
Definition at line 784 of file raw_ostream.h.
Referenced by indent(), operator+(), operator-(), and llvm::operator<<().
The documentation for this struct was generated from the following file:
include/llvm/Support/raw_ostream.h