LLVM: lib/Object/TapiFile.cpp File Reference
TapiFile.cpp File Reference
#include "llvm/Object/TapiFile.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/TextAPI/ArchitectureSet.h"
#include "llvm/TextAPI/InterfaceFile.h"
#include "llvm/TextAPI/Platform.h"
#include "llvm/TextAPI/Symbol.h"
Functions
static uint32_t getFlags (const Symbol *Sym)
static SymbolRef::Type getType (const Symbol *Sym)
Function Documentation
getFlags()
static uint32_t getFlags (const Symbol * Sym) static
Definition at line 26 of file TapiFile.cpp.
References llvm::MachO::Symbol::isUndefined(), llvm::MachO::Symbol::isWeakDefined(), llvm::MachO::Symbol::isWeakReferenced(), llvm::object::BasicSymbolRef::SF_Exported, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
Referenced by handleCompressedSection(), LLVMDITypeGetFlags(), llvm::MDNodeKeyImpl< DIBasicType >::MDNodeKeyImpl(), llvm::MDNodeKeyImpl< DICompositeType >::MDNodeKeyImpl(), llvm::MDNodeKeyImpl< DILocalVariable >::MDNodeKeyImpl(), and llvm::MDNodeKeyImpl< DISubroutineType >::MDNodeKeyImpl().
getType()
static SymbolRef::Type getType (const Symbol * Sym) static
Definition at line 39 of file TapiFile.cpp.
References llvm::MachO::Symbol::isData(), llvm::MachO::Symbol::isText(), llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Function, and llvm::object::SymbolRef::ST_Unknown.
Referenced by llvm::CallLowering::ArgInfo::ArgInfo(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBoolExt(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), callBufferedPrintfStart(), llvm::ShuffleVectorInst::changesLength(), coerceArguments(), CompareSCEVComplexity(), llvm::computeMinimumValueSizes(), llvm::pdb::PDBSymbolTypeFunctionSig::dumpArgList(), llvm::VPWidenEVLRecipe::execute(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::AddrSpaceCastOperator::getDestAddressSpace(), llvm::BitCastOperator::getDestTy(), llvm::MachineInstr::getFirst2LLTs(), llvm::MachineInstr::getFirst2RegLLTs(), llvm::MachineInstr::getFirst3LLTs(), llvm::MachineInstr::getFirst3RegLLTs(), llvm::MachineInstr::getFirst4LLTs(), llvm::MachineInstr::getFirst4RegLLTs(), llvm::MachineInstr::getFirst5LLTs(), llvm::MachineInstr::getFirst5RegLLTs(), getFPSequenceIfElementsMatch(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::MemTransferBase< BaseCL >::getSourceAddressSpace(), llvm::ConstantExpr::getWithOperands(), llvm::ShuffleVectorInst::increasesLength(), interleaveVectors(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::LandingPadInst::isCatch(), llvm::object::Elf_Sym_Impl< ELFType< E, Is64 > >::isCommon(), llvm::HexagonMCInstrInfo::isCompound(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::LandingPadInst::isFilter(), llvm::HexagonMCInstrInfo::isHVX(), llvm::ShuffleVectorInst::isIdentity(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), LLVMBinaryGetType(), LLVMTypeOf(), llvm::AArch64TargetLowering::lowerDeinterleaveIntrinsicToLoad(), llvm::RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleaveIntrinsicToStore(), llvm::RISCVTargetLowering::lowerInterleaveIntrinsicToStore(), llvm::fuzzerop::matchFirstLengthWAnyType(), llvm::fuzzerop::matchFirstType(), matchScalarInAggregate(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::fuzzerop::matchSecondType(), llvm::MachineIRBuilder::materializePtrAdd(), llvm::ValueLatticeElement::mergeIn(), performBlockTailMerging(), llvm::VPReplicateRecipe::print(), llvm::RuntimeCheckingPtrGroup::RuntimeCheckingPtrGroup(), llvm::object::Elf_Sym_Impl< ELFType< E, Is64 > >::setBinding(), llvm::PHINode::setIncomingValue(), llvm::MemTransferBase< BaseCL >::setSource(), llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setSymbol(), llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::setSymbol(), llvm::MemSetBase< BaseCL >::setValue(), simplifyFPOp(), simplifyGEPInst(), tryInterleave(), upgradeAArch64IntrinsicCall(), llvm::UpgradeIntrinsicCall(), upgradeX86IntrinsicCall(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitSwitchInst().