LLVM: lib/DebugInfo/CodeView/TypeHashing.cpp File Reference
TypeHashing.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeHashing.h"
#include "llvm/DebugInfo/CodeView/TypeIndexDiscovery.h"
#include "llvm/Support/BLAKE3.h"
Variables
LocallyHashedType DenseMapInfo< LocallyHashedType >::Empty {0, {}}
LocallyHashedType DenseMapInfo< LocallyHashedType >::Tombstone {hash_code(-1), {}}
static std::array< uint8_t, 8 > EmptyHash
static std::array< uint8_t, 8 > TombstoneHash
GloballyHashedType DenseMapInfo< GloballyHashedType >::Empty {EmptyHash}
GloballyHashedType DenseMapInfo< GloballyHashedType >::Tombstone {TombstoneHash}
Variable Documentation
DenseMapInfo< GloballyHashedType >::Empty
GloballyHashedType DenseMapInfo< GloballyHashedType >::Empty {EmptyHash}
Definition at line 25 of file TypeHashing.cpp.
DenseMapInfo< GloballyHashedType >::Tombstone
GloballyHashedType DenseMapInfo< GloballyHashedType >::Tombstone {TombstoneHash}
Definition at line 26 of file TypeHashing.cpp.
DenseMapInfo< LocallyHashedType >::Empty
LocallyHashedType DenseMapInfo< LocallyHashedType >::Empty {0, {}}
Definition at line 17 of file TypeHashing.cpp.
Referenced by llvm::MemorySSAUpdater::applyUpdates(), llvm::dumpRegSetPressure(), llvm::HexagonRegisterInfo::getCallerSavedRegs(), getDebugLocFromInstOrOperands(), llvm::logicalview::LVSymbolTable::getEntry(), getFirstCompositeRange(), llvm::SIRegisterInfo::getRegUnitPressureSets(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), markAliveBlocks(), and llvm::PredicatedScalarEvolution::PredicatedScalarEvolution().
DenseMapInfo< LocallyHashedType >::Tombstone
LocallyHashedType DenseMapInfo< LocallyHashedType >::Tombstone {hash_code(-1), {}}
Definition at line 18 of file TypeHashing.cpp.
Referenced by llvm::RangeListEntry::dump(), llvm::DWARFDebugRangeList::getAbsoluteRanges(), llvm::DWARFDebugRnglist::getAbsoluteRanges(), llvm::DWARFDie::getHighPC(), llvm::pdb::SymbolDenseMapInfo::getTombstoneKey(), and llvm::DWARFDebugLine::LineTable::parse().
EmptyHash
std::array<uint8_t, 8> EmptyHash static
Initial value:
= {
    {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
Definition at line 20 of file TypeHashing.cpp.
TombstoneHash
std::array<uint8_t, 8> TombstoneHash static
Initial value:
= {
    {0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
Definition at line 22 of file TypeHashing.cpp.